### ISSUE TITLE
[Proposal] Create the SQL Server Compact provider

### ISSUE THREAD

**Issue by ErikEJ** [Mimetis/Dotmim.Sync#10]
Happy to help!

**Comment by Mimetis** [comment]
Wow that would be SO great Erik, if you could help on the SQL Server Compact provider :)

**Comment by Mimetis** [comment]
I would love to implement the SQL CE provider, but I'm not sure it's worth it ...
Closing the issue for now.
Will see in the future if it should be reconsidered.

By the way, @ErikEJ, I LOVE your work on SqlCeToolbox, I use it everyday :)
