### ISSUE TITLE
2000000 rows sync Stucks in the middle of synchronization. 

### ISSUE THREAD

**Issue by abdulhamid3183924** [Mimetis/Dotmim.Sync#1004]
Xamarin. Forms project syncing SQL Db to Slight one way, it works fine when the database is not that much large. but it hangs after a while if the database is large. 
I tried it with 400000 rows was fine, but it hanged with database of 2000000 rows.

**Comment by Mimetis** [comment]
You should have a timeout on the server side I guess

**Comment by symbiogenesis** [comment]
Maybe try fiddling with the batch mode? Or try UseBulkOperations, listed just below that in the documentation?

https://dotmimsync.readthedocs.io/Configuration.html?highlight=batch#batch-mode

**Comment by abdulhamid3183924** [comment]
Thank u for reply
I have set timeout in server side as shown below, but nothing changes and the sync still hangs. 
-----------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore  requestTimeout="00:20:00"  processPath="dotnet" arguments=".\SyncWepAPI.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
</configuration>

**Comment by abdulhamid3183924** [comment]
Thank u for reply
I have set timeout in server side as shown below, but nothing changes, and the sync still hangs.

 [requestTimeout="00:20:00"  processPath="dotnet" arguments=".\SyncWepAPI.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />]

**Comment by abdulhamid3183924** [comment]
Regarding UseBulkOperations , can u give me how to apply it on HTTP mode with ASP. Net Core Web API, I could not find any example!!

**Comment by abdulhamid3183924** [comment]
After changing the Batch mode and set the batch size to 100 it works fine. Thank u all

**Comment by Mimetis** [comment]
100 is too small in my opinion.
I guess you should try with values between 1000 and 2000, in my opinion.
It could improve the overall perf

**Comment by abdulhamid3183924** [comment]
unfortunately, I tried with another SQL Database of 4 millions records and the issue happened again, while the sync process goes on, it freezes, I tried with different batch sizes ,100,  1000 , 2000 , 3000  , but nothing changed. 
have u tried it with that number of rows ?

**Comment by Mimetis** [comment]
Yes

**Comment by Mimetis** [comment]
Did you consider using [snapshot](https://dotmimsync.readthedocs.io/Snapshot.html) to reduce the first sync (that should be the one that timeouts I guess) ?

**Comment by abdulhamid3183924** [comment]
Regarding the snapshot, what I do not understand is in the console Example u mentioned the "Environment.CurrentDirectory" which will direct the snapshot files to current directory of the console, but in the server-side u mentioned the "Environment.SpecialFolder.UserProfile" which will be different directory than the one in the first time.  I tried that but what I see is that the client-side which is Xamarin.forms App always gets the batches files not the same as those was prepared in snapshot.  and also, the batch size will take the default size not the one set when I took the snapshot.

**Comment by abdulhamid3183924** [comment]
this video shows how it freezes at batch _0009.
 
https://github.com/Mimetis/Dotmim.Sync/assets/32239757/2df658b0-0793-428d-a2c9-b6f7535fb951

**Comment by abdulhamid3183924** [comment]
By the way when I tried the client-side as windows application using the same ASP. Net Core Web API it works fine. but Xamarin. Forms freezes in large DB.

**Comment by Mimetis** [comment]
I dont know
Not sure syncing 4 M rows is a good idea for a mobile application
Maybe you are getting a limit here ?
