### ISSUE TITLE
InferSharp detected possible errors in Dotmim.Sync.Core

### ISSUE THREAD

**Issue by symbiogenesis** [Mimetis/Dotmim.Sync#1005]
> C:/Users/symbi/source/repos/Dotmim.Sync/Projects/Dotmim.Sync.Core/Interceptors/Interceptors.cs:83: error: Pulse Resource Leak
>   Resource dynamically allocated by constructor Dotmim.Sync.InterceptorWrapper`1<!0>() on line 80 is not closed after the last access at line 83, column 13.
> 
> C:/Users/symbi/source/repos/Dotmim.Sync/Projects/Dotmim.Sync.Core/Logger/SyncLogger.cs:142: warning: Thread Safety Violation
>   Read/Write race. Non-private method `SyncLogger.GetLogMessageFrom(...)` reads without synchronization from container `Sync.SyncLogger.Dotmim.Sync.SyncLogger.MembersInfo` via call to `Dictionary`2<!0,!1>.get_Item(...)`. Potentially races with write in method `SyncLogger.GetLogMessageFrom(...)`.
>  Reporting because this access may occur on a background thread.
> 
> C:/Users/symbi/source/repos/Dotmim.Sync/Projects/Dotmim.Sync.Core/Orchestrators/Commands/BaseOrchestrator.Commands.cs:261: error: Pulse Resource Leak
>   Resource dynamically allocated by constructor Dotmim.Sync.SyncSet() on line 256 is not closed after the last access at line 261, column 9.
> 
> C:/Users/symbi/source/repos/Dotmim.Sync/Projects/Dotmim.Sync.Core/Serialization/LocalJsonSerializer.cs:54: warning: Thread Safety Violation
>   Read/Write race. Non-private method `LocalJsonSerializer.get_IsOpen()` reads without synchronization from `this.Dotmim.Sync.Serialization.LocalJsonSerializer.<IsOpen>k__BackingField`. Potentially races with write in method `LocalJsonSerializer.OpenFile(...)`.
>  Reporting because another access to the same memory occurs on a background thread, although this access may not.
> 
> C:/Users/symbi/source/repos/Dotmim.Sync/Projects/Dotmim.Sync.Core/Serialization/LocalJsonSerializer.cs:54: warning: Thread Safety Violation
>   Unprotected write. Non-private method `LocalJsonSerializer.set_IsOpen(...)` writes to field `this.Dotmim.Sync.Serialization.LocalJsonSerializer.<IsOpen>k__BackingField` outside of synchronization.
>  Reporting because another access to the same memory occurs on a background thread, although this access may not.
> 
> C:/Users/symbi/source/repos/Dotmim.Sync/Projects/Dotmim.Sync.Core/Serialization/LocalJsonSerializer.cs:68: warning: Thread Safety Violation
>   Read/Write race. Non-private method `LocalJsonSerializer.CloseFile()` indirectly reads without synchronization from `this.Dotmim.Sync.Serialization.LocalJsonSerializer.<IsOpen>k__BackingField`. Potentially races with write in method `LocalJsonSerializer.OpenFile(...)`.
>  Reporting because this access may occur on a background thread.
> 
> C:/Users/symbi/source/repos/Dotmim.Sync/Projects/Dotmim.Sync.Core/Serialization/LocalJsonSerializer.cs:90: warning: Thread Safety Violation
>   Read/Write race. Non-private method `LocalJsonSerializer.OpenFile(...)` reads without synchronization from `this.Dotmim.Sync.Serialization.LocalJsonSerializer.writer`. Potentially races with write in method `LocalJsonSerializer.OpenFile(...)`.
>  Reporting because this access may occur on a background thread.
> 
> C:/Users/symbi/source/repos/Dotmim.Sync/Projects/Dotmim.Sync.Core/Serialization/LocalJsonSerializer.cs:102: warning: Thread Safety Violation
>   Unprotected write. Non-private method `LocalJsonSerializer.OpenFile(...)` indirectly writes to field `this.Dotmim.Sync.Serialization.LocalJsonSerializer.<IsOpen>k__BackingField` outside of synchronization.
>  Reporting because this access may occur on a background thread.
> 
> C:/Users/symbi/source/repos/Dotmim.Sync/Projects/Dotmim.Sync.Core/Serialization/LocalJsonSerializer.cs:188: warning: Thread Safety Violation
>   Read/Write race. Non-private method `LocalJsonSerializer.GetCurrentFileSizeAsync()` reads without synchronization from `this.Dotmim.Sync.Serialization.LocalJsonSerializer.sw`. Potentially races with write in method `LocalJsonSerializer.OpenFile(...)`.
>  Reporting because another access to the same memory occurs on a background thread, although this access may not.
> 
> Found 9 issues
>                         Issue Type(ISSUED_TYPE_ID): #
>   Thread Safety Violation(THREAD_SAFETY_VIOLATION): 7
>           Pulse Resource Leak(PULSE_RESOURCE_LEAK): 2
>

**Comment by Mimetis** [comment]
No clue what I can do here.
Feel free to open a Pull Request, if you are able to fix this warnings
