### ISSUE TITLE
Feature request: Add System.Text.Json as a JSON serializer option

### ISSUE THREAD

**Issue by symbiogenesis** [Mimetis/Dotmim.Sync#1021]
I think this would be a good thing to add in SyncOptions, and could allow for a performance improvement. Would you be interested in something like this?

It would probably break compatibility, and thus should be in addition to Newtonsoft, not a replacement.

At least for the foreseeable future.

**Comment by Mimetis** [comment]
Something I'm thinking about for some times, but it will certainly breaks a lot of things.
As it's not a bug / issue / missing mandatory feature, I want to stabilize this version to ship version 1 before moving forward for new features
