### ISSUE TITLE
SqlServer.ChangeTracking [UpdateUntrackedRowsAsync]..Invalid object name 'ServiceTickets_tracking'

### ISSUE THREAD

**Issue by charristti** [Mimetis/Dotmim.Sync#1026]
Using SqlSyncChangeTrackingProvider and calling UpdateUntrackedRowsAsync generates the following exception:

Dotmim.Sync.SyncException
  HResult=0x80131500
  Message=[UpdateUntrackedRowsAsync]..Invalid object name 'ServiceTickets_tracking'.
  Source=Dotmim.Sync.Core
  StackTrace:
   at Dotmim.Sync.LocalOrchestrator.<UpdateUntrackedRowsAsync>d__11.MoveNext() in C:\Users\charr\source\githubrepos\Dotmim.Sync\Projects\Dotmim.Sync.Core\Orchestrators\LocalOrchestrator.Untracked.cs:line 57
   at AlreadyExstingDatabases.Program.<SynchronizeAsync>d__3.MoveNext() in C:\Users\charr\source\githubrepos\Dotmim.Sync\Samples\AlreadyExistingDatabases\Program.cs:line 48
   at AlreadyExstingDatabases.Program.<Main>d__2.MoveNext() in C:\Users\charr\source\githubrepos\Dotmim.Sync\Samples\AlreadyExistingDatabases\Program.cs:line 27
   at AlreadyExstingDatabases.Program.<Main>()

  This exception was originally thrown at this call stack:
    Microsoft.Data.SqlClient.SqlConnection.OnError(Microsoft.Data.SqlClient.SqlException, bool, System.Action<System.Action>)
    Microsoft.Data.SqlClient.SqlInternalConnection.OnError(Microsoft.Data.SqlClient.SqlException, bool, System.Action<System.Action>)
    Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(Microsoft.Data.SqlClient.TdsParserStateObject, bool, bool)
    Microsoft.Data.SqlClient.TdsParser.TryRun(Microsoft.Data.SqlClient.RunBehavior, Microsoft.Data.SqlClient.SqlCommand, Microsoft.Data.SqlClient.SqlDataReader, Microsoft.Data.SqlClient.BulkCopySimpleResultSet, Microsoft.Data.SqlClient.TdsParserStateObject, out bool)
    Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(System.IAsyncResult, bool, string)
    Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(System.IAsyncResult)
    Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(System.IAsyncResult)
    System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(System.IAsyncResult, System.Func<System.IAsyncResult, TResult>, System.Action<System.IAsyncResult>, System.Threading.Tasks.Task<TResult>, bool)
    Dotmim.Sync.LocalOrchestrator.InternalUpdateUntrackedRowsAsync(Dotmim.Sync.ScopeInfo, Dotmim.Sync.SyncContext, Dotmim.Sync.SyncTable, System.Data.Common.DbConnection, System.Data.Common.DbTransaction, System.Threading.CancellationToken, System.IProgress<Dotmim.Sync.ProgressArgs>) in LocalOrchestrator.Untracked.cs
    Dotmim.Sync.LocalOrchestrator.InternalUpdateUntrackedRowsAsync(Dotmim.Sync.ScopeInfo, Dotmim.Sync.SyncContext, Dotmim.Sync.SyncTable, System.Data.Common.DbConnection, System.Data.Common.DbTransaction, System.Threading.CancellationToken, System.IProgress<Dotmim.Sync.ProgressArgs>) in LocalOrchestrator.Untracked.cs
    ...
    [Call Stack Truncated]

Inner Exception 1:
SqlException: Invalid object name 'ServiceTickets_tracking'.

Since change tracking is enabled and SqlSyncChangeTrackingProvider is in use a '[table name]_tracking' table will not be present in the database. I have not finished investigation, but it appears that one or more of the sql change tracking functions should be called instead of using the _tracking table. 

Again happy to help with development of a PR to fix this issue. Thank you. Please PM me with guidance or comments about creating the PR.

**Comment by Mimetis** [comment]
`UpdateUntrackedRowsAsync` is not working with change tracking

It will raise an exception more explicit on the next version

**Comment by charristti** [comment]
Are you saying that this functionality is never intended to work when using
track changes? If so, do you have a recommendation/best practice for
handling the situation for which the UpdateUntrackedRowsAsync feature is
intended?

**Comment by Mimetis** [comment]
Indeed, as we don't have any sql statements we can use to "change" the value from change tracking for each rows.

I guess one thing you can do is, instead of using `UpdateUntrackedRowsAsync`, maybe make an `Update` statement (without changing any values) for all rows you want to upload

Be careful, like `UpdateUntrackedRowsAsync`, you need to make a first `SynchronizeAsync` call before trying to update rows
