### ISSUE TITLE
Sync for each user

### ISSUE THREAD

**Issue by Diledio** [Mimetis/Dotmim.Sync#1033]
hello, i use this library to sync, everything is okay, i sync sql server and sqlite in xamarin, i use this code in button clicked

SQLitePCL.Batteries_V2.Init();

                var serverOrchestrator = new WebRemoteOrchestrator("http://test/api/sync");

                var sqliteFilename = "WH.db";
                string documentsDirectoryPath = System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal);
                var path = Path.Combine(documentsDirectoryPath, sqliteFilename);

                var clientProvider = new SqliteSyncProvider(path);
                
                var agent = new SyncAgent(clientProvider, serverOrchestrator);
                var setup = new SyncSetup("Users",  "Movs");
               
                var s1 = await agent.SynchronizeAsync("test2", setup);
               
                lblResult.Text = "Sinkronizimi mbaroi";
                lblResult.FontAttributes = FontAttributes.Bold;
                lblResult.FontSize = 35;
                lblResult.TextColor = Color.LightSeaGreen;
                Device.StartTimer(TimeSpan.FromSeconds(3), () =>
                {
                    // Reset the label text
                    lblResult.Text = string.Empty;

                    // Stop the timer from repeating
                    return false;
                });
This app in xamarin is used by many users for example 10, and i have this button to sync, what i want is when the user click this button to sync own data, because for now i have this sync when clicked sync everthing, is that possible ?

**Comment by Mimetis** [comment]
https://dotmimsync.readthedocs.io/Filters.html

**Comment by Diledio** [comment]
i am a little confused, i read this article but did not udnerstand how to implement with my code in button clicked, eg. i have a login form, user login, after the user is logged in i have this button to sync, now i have this button, but this sync everything, i want to sync each data per user when he is logged in, the data what i want ot ysnc is in the table Movs

**Comment by Mimetis** [comment]
I guess you need to filter your Movs table based on the UserId field ?

**Comment by Diledio** [comment]
Yeap, in the table Movs are actions per each user, for example 10 user inserting and getting data from there, so when the button is clicked will get and insert data for this user

**Comment by Mimetis** [comment]
Make filter based on Userid

**Comment by Diledio** [comment]
here is the example : 

var filter = new SetupFilter("Customer");
// Add a column as parameter. This column will be automaticaly added in the tracking table
filter.AddParameter("CustomerID", "Customer");
// add the side where expression, mapping the parameter to the column
filter.AddWhere("CustomerID", "Customer", "CustomerID");
// add this filter to setup
setup.Filters.Add(filter);

how to implement with my own code?

**Comment by Mimetis** [comment]
https://github.com/Mimetis/Dotmim.Sync/blob/master/Samples/FilterWebSync/FilterWebSyncServer/Startup.cs

**Comment by Mimetis** [comment]
You have everything in this sample I think : [https://github.com/Mimetis/Dotmim.Sync/blob/master/Samples/FilterWebSync/FilterWebSyncServer/](https://github.com/Mimetis/Dotmim.Sync/blob/master/Samples/FilterWebSync/FilterWebSyncServer/Startup.cs)

**Comment by Mimetis** [comment]
I don'k know, sorry. 
I don't enough information to help you here.
The best thing you can do, is to create a very small Github sample I can use to reproduce your error.

**Comment by Diledio** [comment]
th error is because the parameters are not the same, because in client side i have a parameter to get the current userid and i did like this 

var loginId = Global.loginId;
var parameters = new SyncParameters
                {
                       { loginId, "aUsers" },
                };

                var s1 = await agent.SynchronizeAsync("testi30", setup, parameters);


and in server side i have this code 

var addressFilter = new SetupFilter("aUsers");
                addressFilter.AddParameter("loginId", "aUsers", true);
                setup.Filters.Add(addressFilter);

in server side i filter by column name, but what i want is to sync data for each user where loggin to sync own data

**Comment by Mimetis** [comment]
> > I don'k know, sorry. I don't enough information to help you here. The best thing you can do, is to create a very small Github sample I can use to reproduce your error.
