### ISSUE TITLE
sync multiple client with the server

### ISSUE THREAD

**Issue by AnasAyy** [Mimetis/Dotmim.Sync#1034]
First I want to thank you what a great framework you have made.
In my scenario I have five client  and one server I want to sync the data between clients and the server 
I use sync form clients to server one by one 
I sync client one with the server and after that I sync client two with the server, I realize that when I sync 
the second client with the server it delete the existing data and add the data from the second client and the 
data from the first client it gone I want a way to sync all clients with the server without deleting any data
so I will have all data from my clients to the server 
can you offer my a code.
Thank you.

**Comment by ErickHeredia92** [comment]
https://github.com/Mimetis/Dotmim.Sync/issues/590

I think your problem is something like that.

I recommend not using Int columns as primary keys, instead I recommend switching to Guid type.

**Comment by Mimetis** [comment]
I was thinking the same thing as @ErickHeredia92 
If you are using an identity column, two clients syncing two lines with the same auto generated ID will be considered as an INSERT for the first one (as it's not yet exist on server) and the second one will be considered as an UPDATE as it's already exists on the server
