### ISSUE TITLE
how to use dynamic  stored procedures

### ISSUE THREAD

**Issue by xyun52** [Mimetis/Dotmim.Sync#1035]
I don't have a large data table, but tables often change, and maintaining stored procedures is too cumbersome. Too many stored procedures seem uncomfortable, I want a clean database

**Comment by xyun52** [comment]
![微信截图_20230601084335](https://github.com/Mimetis/Dotmim.Sync/assets/5417624/7c406960-0143-4f72-ad64-232b06f4ca36)

**Comment by Mimetis** [comment]
There is not option to use dynamic procedures in SQL Server.
I have tried it on PostgreSQL, but it's not implemented in SQL Server.

I you change a lot your schema, I guess you are playing with scopes, 
Everytime you are changing your schema, you are using a new scope with new tables / columns ?

If it's the case, then you can `DeprovisionAsync` an old unused scope and then drop all unused stored procedures

**Comment by xyun52** [comment]
@Mimetis  Is there a plan to support SQL server？

**Comment by Mimetis** [comment]
No, sorry
