### ISSUE TITLE
Replace List<?> with IEnumerable<?> in IDbManagerTable

### ISSUE THREAD

**Issue by workgroupengineering** [Mimetis/Dotmim.Sync#104]
https://github.com/Mimetis/Dotmim.Sync/blob/dad9cc210af1f8a7a6de5ea05fe3f40273f9a82c/Projects/Dotmim.Sync.Core/Manager/IDbManagerTable.cs#L9-L29

**Comment by Mimetis** [comment]
Is this something you really need for any purpose ?
And indeed, an `IEnumeable`, `ICollection` or `IList` should be a better choice in any interface ;)

**Comment by workgroupengineering** [comment]
From the study of your code, IDbManagerTable has the task of returning a snapshot of the table schema.
If that is indeed the intent, the return of methods and interfaces should be immutable.

**Comment by Mimetis** [comment]
Ok make sense.
If we replace in `IDbManagerTable` we should look on others classes as well
