### ISSUE TITLE
Multi-tenancy with ABp

### ISSUE THREAD

**Issue by MarkLFT** [Mimetis/Dotmim.Sync#1040]
I can see several posts regarding using this lib in a multi-tenant way with ABP. But none of the posts seems to describe a solution. Can anyone confirm if they managed to achieve this, and would mind sharing some insight as to how you achieved it.

Thanks in advance.

**Comment by Mimetis** [comment]
What is ABP ?

**Comment by MarkLFT** [comment]
Look at abp.io. it is a Framework with many services included using DDD etc.

**Comment by Mimetis** [comment]
Okay, never tried it, sorry.
