### ISSUE TITLE
SQLite Error 1: 'ON CONFLICT clause dose not match any PRIMARY KEY or UNIQE constraint

### ISSUE THREAD

**Issue by abdulhamid3183924** [Mimetis/Dotmim.Sync#1049]
Two databases SQL server and SQLite synchronized in one direction, everything went fine and after days of being synchronized in a good way, today I got this error "SQLite Error 1: 'ON CONFLICT clause dose not match any PRIMARY KEY or UNIQE constraint", I tried many times to sync but the same message appears, until I deleted the SQLite DB and started the Sync from scratch.

**Comment by Mimetis** [comment]
seems you have a foreign key conflict somewhere

**Comment by abdulhamid3183924** [comment]
what I want to know when the changes being applied, does it take it in sequence according to the scope definition sequence?

**Comment by Mimetis** [comment]
i dont know
if you can provide me a sample repro, i can check
otherwise, no idea

**Comment by abdulhamid3183924** [comment]
I came back to the same issue again today, and I noticed that the "TrackingTables" that was created by (DMS) in the destination SQLite database is empty, and as far as I know that those Tables's purpose to keep track of the rows has been synced.
may it could help you.

**Comment by Mimetis** [comment]
i dont know
if you can provide me a sample repro, i can check
otherwise, no idea
