### ISSUE TITLE
Challenges with Schema-Based Filtering and Joins in a Multi-Tenant Server Database

### ISSUE THREAD

**Issue by nicolazreinh** [Mimetis/Dotmim.Sync#1052]
Hello,

I am encountering an issue with my multi-tenant server database. Each client has a schema name, and I'm currently working on implementing a filter that involves a join operation. However, I've discovered that the "add join" method does not accept a schema name as a parameter. As a result, I receive a "table not found" error.
Why is the "add join" method lacking support for schema names? Are there alternative approaches or workarounds available to achieve the desired functionality?

**Comment by nicolazreinh** [comment]
Yes, I did. But it doesn't work

**Comment by Mimetis** [comment]
Yes, I think you are right, we miss the schema name in the `AddJoin` method

Until it's fixed, you still can use the `AddCustomWhere`

**Comment by nicolazreinh** [comment]
Ok, thanks

**Comment by nicolazreinh** [comment]
How to get the 0.9.8 source code to look at, I cannot find a tag or a release for it.
Can we safely take the latest code from master? And when is the next release?
