### ISSUE TITLE
Temp Location

### ISSUE THREAD

**Issue by rohitshres** [Mimetis/Dotmim.Sync#107]
How to change temp location of sync

**Comment by Mimetis** [comment]
Ok, so it seems we have a bug :)

which providers are you using ?

**Comment by rohitshres** [comment]
I'm using Dotmim.Sync.SqlServer -Version 0.2.1, Dotmim.Sync.Sqlite -Version 0.2.1 and Dotmim.Sync.Web as well. 
Thank you.

**Comment by rohitshres** [comment]
when will this bug gonna solve ??

**Comment by Mimetis** [comment]
I just upload a beta version on myget. Can you try this version ?

**Beta version 0.3.0** is hosted on [myget.org](https://www.myget.org): 
- [https://www.myget.org/feed/dotmimsync/package/nuget/Dotmim.Sync.SqlServer](https://www.myget.org/feed/dotmimsync/package/nuget/Dotmim.Sync.SqlServer)
- [https://www.myget.org/feed/dotmimsync/package/nuget/Dotmim.Sync.MySql](https://www.myget.org/feed/dotmimsync/package/nuget/Dotmim.Sync.MySql)
- [https://www.myget.org/feed/dotmimsync/package/nuget/Dotmim.Sync.Sqlite](https://www.myget.org/feed/dotmimsync/package/nuget/Dotmim.Sync.Sqlite)
- [https://www.myget.org/feed/dotmimsync/package/nuget/Dotmim.Sync.Web.Client](https://www.myget.org/feed/dotmimsync/package/nuget/Dotmim.Sync.Web.Client)
- [https://www.myget.org/feed/dotmimsync/package/nuget/Dotmim.Sync.Web.Server](https://www.myget.org/feed/dotmimsync/package/nuget/Dotmim.Sync.Web.Server)
