### ISSUE TITLE
relationships seems to have issue when tables gets created

### ISSUE THREAD

**Issue by sojan1** [Mimetis/Dotmim.Sync#1071]
eg: **_clnt** table is the parent of PROJECT table, but insertion is denied in _clnt
https://gist.github.com/sojan1/6ab6aca19440cd835788c49bd9bb120d
![image](https://github.com/Mimetis/Dotmim.Sync/assets/111710684/aa4421ce-8e2d-44a0-a373-d1a1f7a992ac)

**Comment by sojan1** [comment]
Foreign key got created the opposite way. 

Parent Table: _clnt
Child Table: Project

https://gist.github.com/sojan1/6ab6aca19440cd835788c49bd9bb120d

When clicked on sync, it,

**Comment by Mimetis** [comment]
You are trying to make a relationship from `PROJECT` to `_clnt` using a unique key `CLNT_ID` that is not a primary key
It's not supported.
