### ISSUE TITLE
I am getting this error

### ISSUE THREAD

**Issue by talley** [Mimetis/Dotmim.Sync#1073]
Dotmim.Sync.SyncException: '[NeedsToUpgradeAsync]..[GetConnectionAsync]..You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().'

**Comment by Mimetis** [comment]
look here 
https://github.com/Mimetis/Dotmim.Sync/blob/b1d7fa923b5aab677fb29298993a2836d1d313a1/Samples/MAUI/MauiAppClient/App.xaml.cs#L11
