### ISSUE TITLE
Very slow bulk insert performance in Sqlite for Android

### ISSUE THREAD

**Issue by tipoman9** [Mimetis/Dotmim.Sync#1075]
We are currently using our old legacy syncing framework for Android Sqlite which does more than 1000 inserts per second in a Android SQLite table. 
The speed of Dotmim.sync for the same table is about 60 per second.
I looked at the code and noticed that SqliteSyncAdapter.GetCommand returns always isBatch="false" to Orchestrator, so each command for every row is prepared, executed and then committed.
Generally, the Java pseudo-code for fast bulk inserting in Android is:
```
            stmt = _conn.compileStatement(InsertCommandSQL); //Similar to Command.Prepare()                     
            for (i = 0; i < (Rows.size()); i++) {
                for (int c = 1; c <= Columns.length; c++) {//Binding values to parameters.
		    colval = Values.get(i).get(Columns[c - 1]);
                    if (colval instanceof String) stmt.bindString(c, (String) colval);
                    if (colval instanceof Double) stmt.bindDouble(c, (Double) colval);                    
                }            
                stmt.executeInsert();//This is very fast since the statement is already prepared
                stmt.clearBindings();
            }
```

Is there any reason ExecuteBatchCommandAsync returns NotImplementedException in SqliteSyncAdapter ? 
I mean was the BatchInsert approach tested and there were problems with it or simply there was no time to implement it?
Thanks.

**Comment by Mimetis** [comment]
The **DMS** `SQLiteSyncProvider` is way faster than the old legacy `Sync Framework` stuff.
There is no batch technic for **SQLite** (like `TVP` with **SQL Server**)

**SQLite** is fast, in Insert mode, if you are using one single transaction, and the preparation is cached.

Give me a simple reproduction to show that the insert is slow, and I will investigate :)

**Comment by Mimetis** [comment]
With 15 columns

![image](https://github.com/Mimetis/Dotmim.Sync/assets/4592555/1ef35005-9093-4c8b-b4d8-57eb8451ea5e)

**Comment by tipoman9** [comment]
Ok, thanks, I'll test a little more on improving performance on Android and will share the results

**Comment by Mimetis** [comment]
@tipoman9  Any feedback regarding `SQLite` performance in general ?
Do you think we can close this issue ?

**Comment by tipoman9** [comment]
So, a few findings on performance. 
 Hooking to interceptors do debug information in console further slows down a lot.
 I hooked to most of them to simply write in the debug console to trace performance like this:
 localOrchestrator.OnExecuteCommand(async args =>{ System.Diagnostics.Debug.WriteLine($"{DateTime.Now.ToString("HH:mm:ss:fff")} " + args.Command); });
 localOrchestrator.OnTableChangesApplied (...
 localOrchestrator.OnRowsChangesApplying(...
 Which increased the total time of the above example from 19 to more than 60 seconds.
 
 Then I recreated the insert locally, using the fastest insert approach as of my knowledge for SQLite with .NET. 
```
         private void CustomActionInsert1000Codes() {
            using var sqliteConnection = new SqliteConnection(this.settings.DataSource);

            string sql = @"Insert into Codes(
Name1 , Name2 , Name3 , Name4 , Name5 , Name6 , Name7 , Name8 , Name9 , Date1 , Date2 , Date3 , Date4 , Date5 , Date6 , Date7 , Date8 , Date9 , Date10, Date11, Date12, Date13, Date14, Date15, Date16, Date17, Date18, Date19, Date20, Date30, Date31, Date32, Date33, Date34, Date35, Date36, Date37, Date38, Date39, Date40
) VALUES(
@Name1 , @Name2 , @Name3 , @Name4 , @Name5 , @Name6 , @Name7 , @Name8 , @Name9 , @Date1 , @Date2 , @Date3 , @Date4 , @Date5 , @Date6 , @Date7 , @Date8 , @Date9 , @Date10, @Date11, @Date12, @Date13, @Date14, @Date15, @Date16, @Date17, @Date18, @Date19, @Date20, @Date30, @Date31, @Date32, @Date33, @Date34, @Date35, @Date36, @Date37, @Date38, @Date39, @Date40
)";


            var c = new SqliteCommand(sql) {
                Connection = sqliteConnection
            };

            SqliteParameter p;
            for (int i = 1; i < 10; i++) {
                p = new SqliteParameter {
                    DbType = DbType.String,
                    Size = 36,
                    ParameterName = "@Name" + i.ToString()
                };
                c.Parameters.Add(p);
            }
            for (int i = 1; i < 41; i++) {
                p = new SqliteParameter {
                    DbType = DbType.DateTime,
                    ParameterName = "@Date" + i.ToString()
                };
                c.Parameters.Add(p);
            }



            sqliteConnection.Open();
            var CheckID = Guid.NewGuid().ToString();
            c.Prepare();
            DateTime start= DateTime.Now;
            SyncServices.L("Start inserting 1000 records");
            using (var t = sqliteConnection.BeginTransaction()) {
                for (var i = 0; i < 1000; i++) {
                    c.Transaction = t;                  

                    for (int k = 0; k < 9; k++)
                        c.Parameters[k].Value = "Product " +i.ToString() + k.ToString();
                    for (int k = 9; k < 49; k++)
                        c.Parameters[k].Value = DateTime.Now;

                    c.ExecuteNonQuery();
                }

                t.Commit();
            }
            this.SyncProgressionText = "Inserted 1000 records 50 cols in " + (DateTime.Now - start).TotalSeconds + " seconds";         

            sqliteConnection.Close();
        }
 ```
 The above gets executed for 4.8 seconds.
 So assuming initial Sync has to prepare and download the 1000 row recordset before starting the insert (didn't measure it, but judging from progress status message about 4 seconds), we have about 3 times faster insert rate with this approach. Which is not as much as I expected, but still worth implementing if speed is important for the project.

**Comment by Mimetis** [comment]
Your comparison is not faire, because you need to ensure you are in the same protocol, when making the comparison.

I mean, the first time you are syncing from a server to a client, **DMS** will get the complete schema from server, and then it will create the `SQLite` schema, tables, and triggers...

Once it's done, you need also to measure the time needed to get the rows from server, serialize them and write them locally in a json file, then we have an http request, with a batch mode where several payload are sent to the client, then the client saved the payload locally and then at the end, make an insert.

Remember also that it's not "_just an insert_" query, because for each row, **DMS** needs to see if the row is good, dirty, deleted or in conflict, and we have also some triggers running in parrallel.

It's not "just an insert" :)

Here is the SQL statement used to upsert a row in `SQLite`(I took your example, and removed a lot of columns to have a better view of the statement itself):

``` sql
WITH CHANGESET as (SELECT [c].[Code], [c].[Name1], [c].[Date1]
FROM (SELECT @Code as [Code], @Name1 as [Name1], @Date1 as [Date1]) as [c]
LEFT JOIN [Codes_tracking] AS [side] ON [side].[Code] = @Code
LEFT JOIN [Codes] AS [base] ON [base].[Code] = @Code
WHERE ([side].[timestamp] < @sync_min_timestamp OR [side].[update_scope_id] = @sync_scope_id) 
OR ([base].[Code] IS NULL  AND ([side].[timestamp] < @sync_min_timestamp OR [side].[timestamp] IS NULL)) 
OR @sync_force_write = 1)
INSERT INTO [Codes] ([Code], [Name1], [Date1])
 SELECT * from CHANGESET WHERE TRUE
 ON CONFLICT ([Code]) DO UPDATE SET 
[Name1]=excluded.[Name1], [Date1]=excluded.[Date1];

UPDATE OR IGNORE [Codes_tracking] SET 
[update_scope_id] = @sync_scope_id,
[sync_row_is_tombstone] = 0,
[timestamp] = replace(strftime('%Y%m%d%H%M%f', 'now'), '.', ''),
[last_change_datetime] = datetime('now')
WHERE [Code] = @Code
 AND (select changes()) > 0;
```

A little bit more complex than your `Insert` ;) but necessary if you want to support a bi directional sync mechanism

By the way, if you have any idea to make this query faster and better, let me know, I'm interested !

That being said, if you really want to see the differences, in term of performances, it would be better to make a sync between SQL and SQLite, using a TCP direct connection, and not using an HTTP mode.

Here is my code, using your Codes tables with 50 columns, that I ran on my PC:

``` cs
// Create 2 Sql Sync providers
var serverProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(serverDbName));
var clientProvider = new SqliteSyncProvider(Path.GetRandomFileName().Replace(".", "").ToLowerInvariant() + ".db");

var setup = new SyncSetup("Codes");

var options = new SyncOptions();
// big payload to ensure we have only 1 file serialized on disk
options.BatchSize = 5000;

// Creating an agent that will handle all the process
var agent = new SyncAgent(clientProvider, serverProvider, options);

// 1st sync: No rows in tables Codes.
// Will allow to create the whole schema on sqlite, with tables and triggers
// Also will create everything on server side
var s1 = await agent.SynchronizeAsync(setup);
var durationTs = TimeSpan.FromTicks(s1.CompleteTime.Ticks).Subtract(TimeSpan.FromTicks(s1.StartTime.Ticks));
Console.WriteLine($"Create SQLite db and configure everything. No rows synced : {durationTs:hh\\.mm\\:ss\\.fff}");
Console.WriteLine($"----------------------------------------");

// Now insert 1000 thousand rows in server side
var result = CustomActionInsert1000CodesInProvider(serverProvider, 2000);
Console.WriteLine($"Insert 1000 rows into server (SQL Server): {result:hh\\.mm\\:ss\\.fff}");
Console.WriteLine($"----------------------------------------");

// Now making another sync where we can have a better measurement
var sqliteWatch = new Stopwatch();
agent.LocalOrchestrator.OnTableChangesApplying(args => sqliteWatch.Start());
agent.LocalOrchestrator.OnTableChangesApplied(args =>sqliteWatch.Stop());

s1 = await agent.SynchronizeAsync(setup);
durationTs = TimeSpan.FromTicks(s1.CompleteTime.Ticks).Subtract(TimeSpan.FromTicks(s1.StartTime.Ticks));
Console.WriteLine($"Sync 1000 rows from Server in SQLite: {durationTs:hh\\.mm\\:ss\\.fff}");
Console.WriteLine($"Pure Merge in SQLite: {sqliteWatch.Elapsed:hh\\.mm\\:ss\\.fff}");
Console.WriteLine($"----------------------------------------");

// Now Insert 1000 thousand rows in sqlite
result = CustomActionInsert1000CodesInProvider(clientProvider, 3000);
Console.WriteLine($"Insert 1000 rows into client (SQLite): {result:hh\\.mm\\:ss\\.fff}");
Console.WriteLine($"----------------------------------------");

// Sync back to server
s1 = await agent.SynchronizeAsync(setup);
durationTs = TimeSpan.FromTicks(s1.CompleteTime.Ticks).Subtract(TimeSpan.FromTicks(s1.StartTime.Ticks));
Console.WriteLine($"Sync 1000 rows from SQLite to SQL Server: {durationTs:hh\\.mm\\:ss\\.fff}");
Console.WriteLine($"----------------------------------------");

```

And the result:

``` bash
Create SQLite db and configure everything. No rows synced : 00.00:01.603
----------------------------------------
Insert 1000 rows into server (SQL Server): 00.00:00.441
----------------------------------------
Sync 1000 rows from Server in SQLite: 00.00:00.765
Pure Merge in SQLite: 00.00:00.653
----------------------------------------
Insert 1000 rows into client (SQLite): 00.00:00.123
----------------------------------------
Sync 1000 rows from SQLite to SQL Server: 00.00:01.706
----------------------------------------
```

Indeed, the performances of the bulk insert from SQLite is slower than your method, but overall the performances are quite good, I guess :)

**Comment by Mimetis** [comment]
By the way, during my tests, I found a bug in the `SqlSyncProvider`, so thank you for that ;)

**Comment by tipoman9** [comment]
There should be an option to fast bulk insert a large amount of data in SQLite with DMS...
With Java I can reach 2000 rows per second, so a 100 000 rows table with 10 columns takes about a minute.
I changed Codes table to ``` SyncDirection.DownloadOnly ``` but there are again triggers on that table in SQLite, and they definitely slow down the insert rate a lot.
What if I need to simply upload a table from the server to mobile ONCE, only on initial setup, without any update possibility for it?
How can I setup this or I should I manually drop all triggers on the mobile table to achieve it?

**Comment by Mimetis** [comment]
Regarding your scenario, do you really need a Sync Framework for your need ?

Maybe create your local DB, download all your data locally and once you are good with it, configure and activate the sync mechanism with DMS ?

**Comment by Mimetis** [comment]
Oh and an advanced scenario would be to create your own provider for download only support without trigger.
I remember i made a sample on that, but its outdated now.
If you are interested in, I can some time to find it and update it with the Last version of DMS

**Comment by tipoman9** [comment]
Thanks. 
In my scenario it is not worth to sync huge recordsets (100k+ records), it is enough to bulk upload them once per week for example. 
 I'll investigate the options.

**Comment by Mimetis** [comment]
I've found a performance bottleneck in the row per row upsert (used by SQLite)
I've made a fix and the results are pretty good:

As a comparison, I've manually made on my machine a massive insert in a SQLite table (using your table structure with more or less 50 columns)
This massive insert is made by reading a json file containing between 20K and 40K rows

```
Insert 20000 rows into client (SQLite): 00.00:01.253
Insert 40000 rows into client (SQLite): 00.00:02.604
```
More or less between **1.2sec** and **2.6sec** (for **20K** rows and **40K** rows)

Using the current beta version, without the fix, the results are :

```
Sync 20000 rows into client (SQLite) :00.00:06.812 
Sync 40000 rows into client (SQLite): 00.00:11.113 
```

Using the version with the fix:

```
Sync 20000 rows into client (SQLite) :00.00:02.925 
Sync 40000 rows into client (SQLite): 00.00:06.285
```

I've created a small provider for **SQLite** that is doing **ONLY** the mode `DownloadOnly`, without upload, without conflict detection, without tracking tables, without triggers.
This provider is provided "_as is_" as  a sample code you can find here https://github.com/Mimetis/Dotmim.Sync/blob/master/Samples/CustomProvider/SqliteSyncDownloadOnlyProvider.cs

Using this provider the results are:

```
Sync 20000 rows into client (SQLite) :00.00:01.934
Sync 40000 rows into client (SQLite): 00.00:03.570
```
