### ISSUE TITLE
dotmin sync syncing issue after updating to 0.9.8 from 0.9.7

### ISSUE THREAD

**Issue by AnshP371** [Mimetis/Dotmim.Sync#1083]
So i will explain the scenario where i am getting the error,i had dotmin sync 0.9.7 for my project which was working fine and syncing properly but what happened is the client side did not sync there data base for some time while the server side was regularly getting updated along with there resepective sync scope versions so after some time when the 0.9.8 version came and we updated that in both client and server side and after updating the version the client then tried to sync his side of the database but he got an error 
"Seems your client setup is different from your server setup. Please create a new scope or deprovision and provision again your client scope with the server scope." so what can be done so that older version of dotmin sync can sync with the newer version if possible.

**Comment by Mimetis** [comment]
Can u try the last beta 1.0 on server side and see if its working ?
