### ISSUE TITLE
Scope name received from client is different from the scope name specified in the web server agent DefaultScope

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#1084]
Using DMS 1.0.0-beta-1514. SQLite client SQL Server change tracking via https.

SyncController has been working nicely with this config using DMS 1.0.0-beta-1509 

```
SyncSetup syncSetup = SyncHelper.GetSyncSetup(scopeName);
SyncOptions syncOptions = SyncHelper.GetSyncOptionsShared(databaseName);
string batchDirectory = SyncOptions.GetDefaultUserBatchDirectory();
syncOptions.BatchDirectory = Path.Combine(batchDirectory, databaseName);
WebServerAgent webServerAgent = new(serverProvider, syncSetup, syncOptions);
```

But DMS 1.0.0-beta-1514 throws HttpSyncWebException with the message 

> Scope name received from client is different from the scope name specified in the web server agent DefaultScope

I've put the scope name back in like this
```
WebServerAgent webServerAgent = new(serverProvider, syncSetup, syncOptions);
webServerAgent.ScopeName = scopeName;
```

Now sync is working fine. Has something changed in the instantiation of WebServerAgent for it to lose the scope name?

**Comment by Mimetis** [comment]
Indeed;

I've added the `identifier` in the last beta, because it was complicated when you have to deal, on the server side, with **multiple servers** and the **same scope name** in each **database**.

Basically, you scenario, if I remember well.

- `identifier` was created and added to the server side for this purpose.
- `scopeName`  was still mandatory when you have to deal with **multiple setups**, in the **same database**.

Regarding `Identifier`, It allows you to do add multiple connection strings, but with the same scope for each database, like this:

``` cs
var setup = new SyncSetup("ProductCategory", "ProductModel", "Product",
"Address", "Customer", "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail");

// different servers, but same databases with same scope (here using "DefaultScope" as default value)
services.AddSyncServer<SqlSyncProvider>(connectionString1, setup, options, identifier: "server1");
services.AddSyncServer<SqlSyncProvider>(connectionString2, setup, options, identifier: "server2");
```
And your controller will be able to retrieve the correct server, since the identifier can be send by the client

``` cs
[HttpPost]
public async Task Post()
{
    // get the identifier send by the client
    var identifier = HttpContext.GetIdentifier();

    // retrieve the correct web server agent
    var webserverAgent = webserverAgents.FirstOrDefault(wsa => wsa.Identifier == identifier);
    await webserverAgent.HandleRequestAsync(HttpContext).ConfigureAwait(false);
}
```

Now the problem we have is the other scenario, where we have 1 server with 1 database but multiple setup / scope name
This is where we need multiple `scopename`, as `identifier` is not appropriate:

``` cs
// two setups for the same database
var setup1 = new SyncSetup("ProductCategory", "ProductModel", "Product");
var setup2 = new SyncSetup("Address", "Customer", "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail");

// Same server, with different scopes
services.AddSyncServer<SqlSyncProvider>(connectionString1, setup1, options, scopeName: "products");
services.AddSyncServer<SqlSyncProvider>(connectionString1, setup2, options, scopeName: "customers");
```

The controller is kind the same, a part that we are retrieving the correct `WebServerAgent` based on the `scopeName` value:

``` cs
[HttpPost]
public async Task Post()
{
    // get the scope name send by the client
    var scopeName = HttpContext.GetScopeName();

    // retrieve the correct web server agent
    var webserverAgent = webserverAgents.FirstOrDefault(wsa => wsa.ScopeName== scopeName);
    await webserverAgent.HandleRequestAsync(HttpContext).ConfigureAwait(false);
}
```

Of course, the last scenario is : **Multiple servers & databases** with **multiple scopes in each database**.
You can obviously combine the `identifier` and `scopeName` values to retrieve the correct `WebServerAgent` instance:

``` cs
[HttpPost]
public async Task Post()
{
    // get the scope name send by the client and the identifier
    var scopeName = HttpContext.GetScopeName();
    var identifier = HttpContext.GetIdentifier();

    // first retrieve all the web server agents configured for the correct server connection string:
    var agents = webserverAgents.Where(wsa => wsa.Identifier == identifier);

    if (agents == null || agents.Count() <= 0)
        throw new Exception("No web server agent found for the current identifier");

    // then on this list of agents, get the correct agent for the current scope name
    var webserverAgent = agents.FirstOrDefault(wsa => wsa.ScopeName == scopeName);

    if (webserverAgent == null)
        throw new Exception("no web server agent configured with this scope name");

    await webserverAgent.HandleRequestAsync(HttpContext).ConfigureAwait(false);
}
```

Make sense ?

**Comment by VagueGit** [comment]
Thank you for the explanation and heads up. It seems to be that the scope is being passed in to WebServerAgent ctor twice, in syncSetup and as scopeName. Would it be tidier if scopeName was defined in syncSetup?

From my birds-eye perspective I wonder if semantically it would make sense to conflate the provider and the setup. Define the server, the database and the tables all in one place?

**Comment by Mimetis** [comment]
There is no `ScopeName` in `SyncSetup`.
I don't think there is any redundant `ScopeName` here, do I ?

`ScopeName` should not be tied to `SyncSetup`, because you can create multiple scopes with the same `SyncSetup` and different scope names (for example One scope with some particular filter values and another one with some others filter values)

**Comment by VagueGit** [comment]
OK so we've got DMS 1.0.0-beta-1515 and sync is working with
`WebServerAgent webServerAgent = new(provider: serverProvider, setup: syncSetup, options: syncOptions, scopeName: scopeName);`

**Comment by Mimetis** [comment]
You are not using the Identifier property ??

**Comment by VagueGit** [comment]
Isn't the identifier the database? 
```
databaseName = HttpContext.GetIdentifier();
string connectionString = databaseHelper.DatabaseConnection(databaseName);
SqlSyncChangeTrackingProvider serverProvider = new SqlSyncChangeTrackingProvider(connectionString);
```

Something wrong with that?

**Comment by Mimetis** [comment]
Oh, OK  now I remember you are not using DI to get an instance of WebServerAgent, but you are doing it manually. 
Make sense

**Comment by sojan1** [comment]
Hi,

i suddenly started getting this . I have not changed anything.  Please kindly help
 

![image](https://github.com/Mimetis/Dotmim.Sync/assets/111710684/746e7607-d1e6-4d48-8913-1a0297d327ed)


            // Database script used for this sample : https://github.com/Mimetis/Dotmim.Sync/blob/master/CreateAdventureWorks.sql 

            var serverOrchestrator = new WebRemoteOrchestrator("http://192.168.1.67:81/api/sync");

            // Second provider is using plain old Sql Server provider, relying on triggers and tracking tables to create the sync environment
            //var clientProvider = new SqlSyncProvider(clientConnectionString);
            var clientProvider = new SqliteSyncProvider("CoreDatabase.db");

            var options = new SyncOptions
            {
                BatchSize = 1000
            };

            // Creating an agent that will handle all the process
            var agent = new SyncAgent(clientProvider, serverOrchestrator, options);

            do
            {
                try
                {
                    var progress = new SynchronousProgress<ProgressArgs>(args => Console.WriteLine($"{args.ProgressPercentage:p}:\t{args.Message}"));

                    // Launch the sync process
                   // var s1 = await agent.SynchronizeAsync(Dotmim.Sync.Enumerations.SyncType.Reinitialize, progress);
                    var s1 = await agent.SynchronizeAsync("v0", Dotmim.Sync.Enumerations.SyncType.Reinitialize, progress);
                    // Write results
                    Console.WriteLine(s1);

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }

            } while (Console.ReadKey().Key != ConsoleKey.Escape);

            Console.WriteLine("End");
