### ISSUE TITLE
Adding a new table to SyncConfiguration (WebProxyServer)

### ISSUE THREAD

**Issue by lordofffarm** [Mimetis/Dotmim.Sync#109]
Setup:
Server: WebProxyServer
Client: Xamarin.Android app

Steps to reproduce:
1. Add sync server with one table
`services.AddSyncServer<MySqlSyncProvider>(connectionString, configuration =>
            {
                configuration.Add(new []
                {
                    "Table1"
                });
            });`

2. Synchronize on client
`await _syncAgent.SynchronizeAsync();`

3. Add a new table to the configuration
`services.AddSyncServer<MySqlSyncProvider>(connectionString, configuration =>
            {
                configuration.Add(new []
                {
                    "Table1",
                    "Table2"
                });
            });`

4. Synchronize on client like this
`await _syncAgent.SynchronizeAsync();`
or like this
`await _syncAgent.SynchronizeAsync(SyncType.Reinitialize);`

5. Get the exception - "MySql.Data.MySqlClient.MySqlException (0x80004005): PROCEDURE mydb.Table2_selectchanges does not exist"

I suppose the logic is that one has to deprovision to add a new table.
But how do you do that if you are using the WebProxyServer?

Also, the same thing happens if you add a new filter to the configuration after you have synchronized once.
`configuration.Filters.Add(new FilterClause("Table1", "Id"));`

"MySql.Data.MySqlClient.MySqlException (0x80004005): PROCEDURE mydb.Table1_Id_selectchanges does not exist"

**Comment by lordofffarm** [comment]
So basically, there are no procedures and no _tracking table for the new Table2.

**Comment by Mimetis** [comment]
Indeed, once you have done a sync, the configuration can't change.
Basically, everything is generated once, and used everytime.
Changing Something after first sync, won't work at all.

You have to deprovision everything, and then create a new configuration, to make it work

**Comment by lordofffarm** [comment]
Hi, @Mimetis ! Thank you for the reply!

I created a Console app with a MySqlSyncProvider and tried to DeprovisionAsync, which threw a NotImplementedException 

> at Dotmim.Sync.MySql.MySqlBuilderProcedure.DropBulkInsert() in /Dotmim.Sync.MySql/Builders/MySqlBuilderProcedure.cs:line 987
   at Dotmim.Sync.Builders.DbBuilder.DropProcedures(DbConnection connection, DbTransaction transaction) in 
/Dotmim.Sync.Core/Builders/DbBuilder.cs:line 319
   at Dotmim.Sync.CoreProvider.DeprovisionAsync(SyncConfiguration configuration, SyncProvision provision) in 
/Dotmim.Sync.Core/CoreProvider.Database.cs:line 57

as it tries to drop bulk procedures at line 317 in /Dotmim.Sync.Core/Builders/DbBuilder.cs, because 
`private readonly bool useBulkProcedures = true;` 
by default, even though MySql does not support bulk operations.

**Comment by Mimetis** [comment]
The `useBulkProcedures` effect should be resolved in the last commit.
Please let me know if it's working for you ?

**Comment by Mimetis** [comment]
I close this issue, since it's resolved in the last beta.  
Feel free to re-open it if you still have the issue.
