### ISSUE TITLE
Dotmim sync v0.9.7 - Records deleted from server side not synced on client side

### ISSUE THREAD

**Issue by Bella1890** [Mimetis/Dotmim.Sync#1094]
On the server when i delete records or data  , the same records or data gets deleted on client side, once i sync the data
below is the code
setup.Tables["SyncDetail"].Columns.AddRange(new string[] { "SyncDetailGUID", "VesselID", "EditedOn", "EditedBy" });
            var SyncDetailFilter = new SetupFilter("SyncDetail");
            SyncDetailFilter.AddParameter("VesselID", "SyncDetail", true);
            SyncDetailFilter.AddCustomWhere("VesselID = @VesselID  OR side.sync_row_is_tombstone = 1");
            setup.Filters.Add(SyncDetailFilter);

The above works only for tables which  has filter parameter applied

Tables which do not have filter parameters , how to achieve deleteion of records from server to client , once i sync the data.

**Comment by Mimetis** [comment]
I'm sorry, I don't understand what you are meaning here.
The most simple way is to create a small sample repro to help me understand what's your problem
Otherwise, try to add more details to your question

**Comment by Bella1890** [comment]
I have two databases: sql server db and sqlite db
I am trying to sync the tables and its data from sql server db to sqlite db using dotmim package

I have created a table on sql server db => "Sync Detail" , and got it synced on sqlite db

If i delete any data from table "SyncDetail" from sql server db , the same is not geeting deleted on sqlite db  when i sync the data

**Comment by Mimetis** [comment]
Ok, Can you create a small sample reproduction ?
Because on my side, I'm able to delete some rows on the server and have these rows deleted on the client
