### ISSUE TITLE
Client and Server schema must be the same

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#11]
Hello!

I was wondering, how you are planning to solve the problem, that client and server schemas are not always quite the same.

For example: In our production system, we have a tasks table.
This table looks different on the server and client. I.e. server and client table share a set of columns, but both, server and client, add additional columns to their own tasks tables.

This also leads me to the following question:
Are you planning to solve the problem of the old sync framework which is, that those schemas must be equal and must not ever change?
(e.g. a schema update would be necessary)

You could:
1) add an (optional) middle layer between client and server that can process all rows and convert them from one schema to another. That way you could allow downward compatibility in case the server schema changes.

2) please have a look at this library, as I think it could save you a to of work: [DatabaseSchemaReader](https://github.com/martinjw/dbschemareader)

Not only allows it to inspect the schema of all databases you want to support, it even allows to create schema-migration sql and the like.
So - very powerful stuff here.

Also, it runs on .NET Core.

**Comment by Mimetis** [comment]
I didn't know `DatabaseSchemaReader` and it looks really cool. 
I will definitively investigate this Library and see if it could be a good replacement from the current implementation in `Dotmim.Sync`

For the **schema** question, actually, the schema should be the same on the client and the server, only if you're targetting SQL Server on both side.
If you're targetting any other clients, the schema is not replicated.

**Comment by Mimetis** [comment]
Schema management is available on SQL Server provider
