### ISSUE TITLE
Error after adding authentication 

### ISSUE THREAD

**Issue by sojan1** [Mimetis/Dotmim.Sync#1102]
Hi 
It fails after sync reaches 100%  and it says **UNIQUE constraint failed**  Is this related to  #974 , #907?

I am using the **sample application** (**HelloWebAuthSync**).  
Hub Database - SQL Server
Client Database -SQLite
i tried from both console application and MAUI. it both shows the same error.

Authentication works well, as i tested it by giving a 'key' different from that of server. and it responds  'unauthorised'
i have also tried [AllowAnonymous] on server still the error is the same.

**Error:** Dotmim.Sync.SyncException: '[InternalSaveScopeInfoClientAsync]..SQLite Error 19: **UNIQUE constraint failed**:  scope_info_client.sync_scope_id, scope_info_client.sync_scope_name, scope_info_client.sync_scope_hash'.'

**Same scope 'v0' synchronizes through a different port (81)**  [ **Sample WebApi with NoAuth** under MAUI folder].
![image](https://github.com/Mimetis/Dotmim.Sync/assets/111710684/b27f28c6-8036-47fe-b876-3c08c6862392)

![image](https://github.com/Mimetis/Dotmim.Sync/assets/111710684/efa2af3d-cbf1-42dd-ada5-178477956e1e)

**Client** 
        private static async Task SynchronizeAsync()
        {
            string clientConnectionString = $"Data Source=C:\\Users\\sojan.GEROC\\Documents\\Projects\\Dotmim.Sync-master\\Samples\\HelloWebAuthSync\\HelloWebAuthSyncClient\\CoreDatabase.db";

            var token = GenerateJwtToken("spertus@microsoft.com", "SPERTUS01");
            HttpClient httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            var serverOrchestrator = new WebRemoteOrchestrator("http://192.168.1.77:82/api/sync", client: httpClient);
            var clientProvider = new SqliteSyncProvider(clientConnectionString);

            // Set the web server Options
            var options = new SyncOptions
            {
                BatchDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDirectory(), "client")
            };
            //options.TransactionMode = TransactionMode.AllOrNothing;
            var agent = new SyncAgent(clientProvider, serverOrchestrator, options);

            var progress = new SynchronousProgress<ProgressArgs>(
                  pa => Console.WriteLine($"{pa.ProgressPercentage:p}\t {pa.Message}"));

            var parameters2 = new SyncParameters
                {
                    { "CLNT_ID","D1" },
                    { "PROJ_ID","MASTER" }
                };

            var s1 = await agent.SynchronizeAsync("v0", SyncType.Normal, parameters2, progress);
            Console.WriteLine(s1);

            Console.WriteLine("End");
        }

**Server**
     

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddDistributedMemoryCache();
            services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

            
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear(); // => remove default claims

            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddJwtBearer(options =>
                    {
                        options.RequireHttpsMetadata = false;
                        options.SaveToken = true;
                        options.TokenValidationParameters = new TokenValidationParameters
                        {
                            ValidIssuer = "Dotmim.Sync.Bearer",
                            ValidAudience = "Dotmim.Sync.Bearer",
                            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("SOME_RANDOM_KEY_DO_NOT_SHARE"))
                        };

                        options.Events = new JwtBearerEvents
                        {
                            OnAuthenticationFailed = context =>
                            {
                                Debug.WriteLine("OnAuthenticationFailed: " + context.Exception.Message);
                                return Task.CompletedTask;
                            },
                            OnTokenValidated = context =>
                            {
                                Debug.WriteLine("OnTokenValidated: " + context.SecurityToken);
                                return Task.CompletedTask;
                            }
                        };
                    });
            var connectionString = Configuration.GetSection("ConnectionStrings")["SqlConnection"];
            var scopeName =  Configuration.GetSection("Scope")["ScopeName"];

            // Set the web server Options
            var options = new SyncOptions
            {
                BatchDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDirectory(), "server")
            };
            var setup = new SyncSetup();
            services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString, setup, null, null, scopeName);
        }

**Comment by sojan1** [comment]
@Mimetis any idea what it is. 
It works perfectly with the same database that is provisioned with no authentication.
Even the authentication works because i can see the local database is getting provisioned.

With authentication 
![image](https://github.com/Mimetis/Dotmim.Sync/assets/111710684/5832120a-f95b-47d0-9830-db62ce9abdb7)


Without authentication 
![image](https://github.com/Mimetis/Dotmim.Sync/assets/111710684/f28ab8e9-d452-4634-86f5-8e8e2726d663)

**Comment by sojan1** [comment]
Hi @Mimetis 
Please see the attached.

[HelloWebAuthSyncClient.zip](https://github.com/Mimetis/Dotmim.Sync/files/12667088/HelloWebAuthSyncClient.zip)
[HelloWebAuthSyncServer.zip](https://github.com/Mimetis/Dotmim.Sync/files/12667096/HelloWebAuthSyncServer.zip)
[Other Files.zip](https://github.com/Mimetis/Dotmim.Sync/files/12667109/Other.Files.zip)

**Comment by Mimetis** [comment]
plz create a github repository

**Comment by sojan1** [comment]
Hi @Mimetis 

https://github.com/sojan1/Dotmim.Sync.Samples

**Comment by Mimetis** [comment]
Please create a repository with your sample only.
What should I do with a repository with ALL THE DMS SAMPLES ?

**Comment by sojan1** [comment]
Hi 

i have removed all other samples and uploaded again
https://github.com/sojan1/Dotmim.Sync.Samples1

**Comment by Mimetis** [comment]
link is not working
last link still the same

**Comment by sojan1** [comment]
link is now working. 
but i think you will also need the projects included .  currently it works against the dlls, you will be able to see the error but cannot debug isnt it.?

So i will recomplile and send you on weekend.

Thanks

**Comment by sojan1** [comment]
i am so sorry for that.  
The repository was defaulted to private when uploaded from Visual Studio
i have tested the latest version and have also confirmed that it is a public 

https://github.com/sojan1/Dotmim.Sync.Samples2

**Comment by sojan1** [comment]
@Mimetis , Hi, have you had a chance to see the error?

**Comment by Mimetis** [comment]
In the sample you provided, you forgot to add tables to your SyncSetup instance:

``` cs
// [Required]: Get a connection string to your server data source
var connectionString = Configuration.GetSection("ConnectionStrings")["SqlConnection"];

// Set the web server Options
var options = new SyncOptions
{
    BatchDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDirectory(), "server")
};

// ADD TABLES !!!!!!!!!!!!!!!!!!!!
var setup = new SyncSetup();
// ADD


var provider = new SqlSyncChangeTrackingProvider(connectionString);


services.AddSyncServer(provider, setup, options, null);

```


Before testing, be sure you are using a fresh server / client database
My advice, for any test, be sure you have provision correctly your database.


Last thing, your sample is not running correctly and is not raising the issue you are mentionning.
Please do the effort to provider a clean sample I can use to reproduce your error, otherwise I will not be able to help you.

**Comment by sojan1** [comment]
provisioning is already done for the database? should u again have the tables added in the SyncSetup().
i am already synching the maui example with the hub using the same code above.
