### ISSUE TITLE
I started to get SSL error

### ISSUE THREAD

**Issue by amir-inbar-software** [Mimetis/Dotmim.Sync#1104]
Hi,

Thanks for great product.

i started to get exception while sync with .net core website (secured properly with ssl certificate): 

the error mention SSL when trying to connect to the sql server (don't understand the relation of these 2 things)

Exception thrown: 'Dotmim.Sync.Web.Client.HttpSyncWebException' in System.Private.CoreLib.dll
Exception thrown: 'Dotmim.Sync.Web.Client.HttpSyncWebException' in System.Private.CoreLib.dll
Exception thrown: 'Dotmim.Sync.Web.Client.HttpSyncWebException' in System.Private.CoreLib.dll
An unhandled exception of type 'Dotmim.Sync.Web.Client.HttpSyncWebException' occurred in System.Private.CoreLib.dll
[NeedsToUpgradeAsync]..[GetConnectionAsync]..A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
  -----------------------

  ├  ─ A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
  └  ─  ─ The certificate chain was issued by an authority that is not trusted.

when i check the WriteHelloAsync i get 👍 

![image](https://github.com/Mimetis/Dotmim.Sync/assets/70964980/698dea8f-f67c-429d-8187-31c6ece4f8e8)

i have upgraded to 0.9.8

Any Hint?

Regards,

**Comment by amir-inbar-software** [comment]
When i check this.HttpContext.WriteHelloAsync(webServerAgent);

the start of the page is:

![image](https://github.com/Mimetis/Dotmim.Sync/assets/70964980/fac927af-8072-4017-bc7b-d291130837ae)

**Comment by amir-inbar-software** [comment]
i have upgraded to 0.9.8

**Comment by Mimetis** [comment]
Newer version of `SqlClient`.
Use `TrustServerCertificate=True` in your sql connection string
