### ISSUE TITLE
Transport level error

### ISSUE THREAD

**Issue by mcash95** [Mimetis/Dotmim.Sync#1106]
![image](https://github.com/Mimetis/Dotmim.Sync/assets/58281418/0ac31ef1-6ca1-47ad-93f0-16cb0647f7a0)

I am new to Dotmim.Sync, and am getting an odd error why trying to do my first sync. Any help would be appreciated. I cant find any documentation on the error.

Thank you!

**Comment by Mimetis** [comment]
Not able to reach your database

**Comment by mcash95** [comment]
> Not able to reach your database

thank you for the prompt response! I've made some changes and now receive a timeout error when attempting to connect to my SqlAzure instance. I am able to pull records using the Microsoft SQLClient so i know the azure instance is functioning. Any thoughts?

Thank you again!

**Comment by Mimetis** [comment]
I don't know, if Microsoft.SqlClient is working, it should work also in DMS

Need more info / sample to help you here

**Comment by Mimetis** [comment]
Oh, got it
Are you trying from a mobile application ?
On mobile, you can't reach directly a SQL Server instance, you need to use an API in between

**Comment by mcash95** [comment]
> Oh, got it Are you trying from a mobile application ? On mobile, you can't reach directly a SQL Server instance, you need to use an API in between

Makes sense, stupid mistake on my part. do you have a github link for me to the demo/example? 

Thank you!

**Comment by Mimetis** [comment]
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/HelloWebSync
