### ISSUE TITLE
Sample fails with error

### ISSUE THREAD

**Issue by 420tech** [Mimetis/Dotmim.Sync#1114]
I tried the tutorial as described and got this error:
Dotmim.Sync.SyncException
  HResult=0x80131500
  Message=[InternalApplyChangesAsync]..Error on table [ProductCategory]: SQLite Error 19: 'FOREIGN KEY constraint failed'.. Row:[Sync state]:ApplyModifiedFailed, [ProductCategoryID]:7c782bbe-5a16-495a-aa50-10afe5a84af2, [ParentProductCategoryID]:c657828d-d808-4aba-91a3-af2ce02300e9, [Name]:Headsets, [rowguid]:5de142e8-f2a5-4009-a455-f32714407a83, [ModifiedDate]:6/1/2002 12:00:00 AM, [IsActive]:True. ApplyType:Modified
  Source=Dotmim.Sync.Core
  StackTrace:
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__28.MoveNext()
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__28.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\timbe\source\repos\TestDotMim\TestDotMim\Program.cs:line 24

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ApplyChangesException: Error on table [ProductCategory]: SQLite Error 19: 'FOREIGN KEY constraint failed'.. Row:[Sync state]:ApplyModifiedFailed, [ProductCategoryID]:7c782bbe-5a16-495a-aa50-10afe5a84af2, [ParentProductCategoryID]:c657828d-d808-4aba-91a3-af2ce02300e9, [Name]:Headsets, [rowguid]:5de142e8-f2a5-4009-a455-f32714407a83, [ModifiedDate]:6/1/2002 12:00:00 AM, [IsActive]:True. ApplyType:Modified

Inner Exception 2:
SqliteException: SQLite Error 19: 'FOREIGN KEY constraint failed'.

**Comment by Mimetis** [comment]
try with `DisableConstraintsOnApplyChanges`

``` cs
var options = new SyncOptions { DisableConstraintsOnApplyChanges = true }

// Sync agent
SyncAgent agent = new SyncAgent(clientProvider, serverProvider, options);
```
