### ISSUE TITLE
Synching with WebOrchestrator on version 0.9.7

### ISSUE THREAD

**Issue by sojan1** [Mimetis/Dotmim.Sync#1116]
Synching with WebOrchestrator is failing on version 0.9.7, but it works with the SqlSyncProvider

using 0.9.7 for provisioning
using 0.9.7 for Web API
using 0.9.7 for Synching

Client DB : Sqlite
Server DB : SQL Server

any idea what the below is 
![image](https://github.com/Mimetis/Dotmim.Sync/assets/111710684/4bc9db4c-abd7-4654-8f1d-b2bbee6853aa)
**Newtonsoft.Json.JsonSerializationException: 'Required property 'tables' not found in JSON. Path 'bi.parts[0]', line 1, position 314.'**
This exception was originally thrown at this call stack:
    [External Code]
    Dotmim.Sync.Serialization.JsonConverter<T>.DeserializeAsync(System.IO.Stream) in JsonConverter.cs
    Dotmim.Sync.Web.Client.WebRemoteOrchestrator.InternalApplyThenGetChangesAsync(Dotmim.Sync.ScopeInfoClient, Dotmim.Sync.ScopeInfo, Dotmim.Sync.SyncContext, Dotmim.Sync.ClientSyncChanges, System.Data.Common.DbConnection, System.Data.Common.DbTransaction, System.Threading.CancellationToken, System.IProgress<Dotmim.Sync.ProgressArgs>) in WebRemoteOrchestrator.ApplyChanges.cs
    Dotmim.Sync.Web.Client.WebRemoteOrchestrator.InternalApplyThenGetChangesAsync(Dotmim.Sync.ScopeInfoClient, Dotmim.Sync.ScopeInfo, Dotmim.Sync.SyncContext, Dotmim.Sync.ClientSyncChanges, System.Data.Common.DbConnection, System.Data.Common.DbTransaction, System.Threading.CancellationToken, System.IProgress<Dotmim.Sync.ProgressArgs>) in WebRemoteOrchestrator.ApplyChanges.cs
    Dotmim.Sync.SyncAgent.SynchronizeAsync(string, Dotmim.Sync.SyncSetup, Dotmim.Sync.Enumerations.SyncType, Dotmim.Sync.SyncParameters, System.Threading.CancellationToken, System.IProgress<Dotmim.Sync.ProgressArgs>) in SyncAgent.cs
 
Where can i find the sourcecode point for 0.9.7. 19th Sep 2022 was the date when it was uploaded to nuget.
![image](https://github.com/Mimetis/Dotmim.Sync/assets/111710684/fc5f23c8-3c09-49aa-aebb-077c0ee0dad6)
![image](https://github.com/Mimetis/Dotmim.Sync/assets/111710684/149cb650-8834-495e-aff3-cb865e20bb33)
 
Thanks

**Comment by Mimetis** [comment]
No Idea
Provide a code sample
