### ISSUE TITLE
Conflict Issue while using GUID as Primary Keys

### ISSUE THREAD

**Issue by hsharma89** [Mimetis/Dotmim.Sync#1118]
Hi Sébastien Pertus,
We are facing a weird situation regarding conflicts. 
**Issue:** I have 2 applications 1 website Connected with SQL Server Main Database and 1 desktop app connected with Sqlite Database. 

Whenever I modify any row using my website and try to sync data using the Desktop application, the Modified data is not syncing to the local SQLite Database. 
This issue is mostly happening on the tables where I have used GUID as the Primary Key. 
I have created a console application to check the issue, **agent.LocalOrchestrator.OnApplyChangesConflictOccured** shows that there is a conflict. (This is not a conflict as data is only modified using the server not from the client). 
**Conflict Scenario as per your documentation:** Conflicts occurs when a client update / delete/insert a record that is updated/deleted or inserted on the server as well before any sync happens.

I have found that Dotmim has Automatically resolved the conflict but changes are not applied to the client.
See the Below screenshot. 
![image](https://github.com/Mimetis/Dotmim.Sync/assets/22783551/c41e5200-9267-4dd2-810f-9579e26f39ab)
However, if I use the following code:
```
agent.LocalOrchestrator.OnApplyChangesConflictOccured(args =>
{
       args.Resolution = ConflictResolution.MergeRow;
});

```

It will apply changes to the client. My question is this a good approach? 
![image](https://github.com/Mimetis/Dotmim.Sync/assets/22783551/286a3f59-1aaa-4934-86db-33c4d624d910)

More Information: 
I am using **ConflictResolutionPolicy.ClientWins**
**Dotmim Version: 0.9.7.**

**One Other Question:** Can we use the same user for desktop clients on different machines?

**Comment by Mimetis** [comment]
Can you try with the last beta version and see if the result is the same ?

**Comment by symbiogenesis** [comment]
I had a problem with this and switched my primary keys to use ULID via NUlid
