### ISSUE TITLE
Column name error

### ISSUE THREAD

**Issue by mcash95** [Mimetis/Dotmim.Sync#1120]
Provisioning the server when it has decimals in column names fails. 

Ex a table with column names of 7.5, 8.5 will throw the below error

_Dotmim.Sync.SyncException
  HResult=0x80131500
  Message=[ProvisionAsync].Provision:TrackingTable, StoredProcedures, Triggers.Overwrite:False..[InternalProvisionServerAsync].Provision:TrackingTable, StoredProcedures, Triggers.Overwrite:False..[InternalProvisionAsync].Provision:TrackingTable, StoredProcedures, Triggers.Overwrite:False..[InternalCreateStoredProceduresAsync].Table:WomensCurves.Overwrite:False..[InternalCreateStoredProcedureAsync].Table:WomensCurves.StoredProcedure:BulkTableType..Column names in each table must be unique. Column name '5' in table 'WomensCurves_BulkType' is specified more than once.
  Source=Dotmim.Sync.Core
  StackTrace:
   at Dotmim.Sync.RemoteOrchestrator.<ProvisionAsync>d__6.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\Max\source\repos\thswebapp\Program.cs:line 36

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
SqlException: Column names in each table must be unique. Column name '5' in table 'WomensCurves_BulkType' is specified more than once._

I've included a screenshot of the table columns for reference. 

![image](https://github.com/Mimetis/Dotmim.Sync/assets/58281418/b4b31b38-ca7d-41c8-a20a-fceed5221749)

Thank you for a fantastic library! This has made developing mobile apps with offline functionality SOOOO much easier.

**Comment by Mimetis** [comment]
Provide a small sample to be able to reproduce your error

**Comment by mcash95** [comment]
![image](https://github.com/Mimetis/Dotmim.Sync/assets/58281418/1ab80a07-6224-4b6d-9901-555675aded8e)
Here is the setup on ASP web layer.


![image](https://github.com/Mimetis/Dotmim.Sync/assets/58281418/1a9b3291-f8f6-44d3-885c-b2552449659b)
here is the sync call within the mobile app.

Does this suffice?

**Comment by Mimetis** [comment]
nop, I need something I can use, like copy paste your sql script that will create basic tables and fill some rows and a piece of code I can use to reproduce
I can't copy paste from a screenshot

**Comment by mcash95** [comment]
`SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MensCurves](
	[Style] [int] NULL,
	[PoNumber] [int] NOT NULL,
	[VendorID] [int] NULL,
	[StartDate] [date] NULL,
	[EndDate] [date] NULL,
	[Total] [int] NULL,
	[Complete] [int] NULL,
	[TargetPair] [int] NULL,
	[MerchGroup] [varchar](50) NULL,
	[QtyRecd] [int] NULL,
	[DeptID] [int] NULL,
	[ClassID] [int] NULL,
	[Subclass] [int] NULL,
	[Division] [char](1) NULL,
	[5] [int] NULL,
	[6] [int] NULL,
	[7] [int] NULL,
	[7.5] [int] NULL,
	[8] [int] NULL,
	[8.5] [int] NULL,
	[9] [int] NULL,
	[9.5] [int] NULL,
	[10] [int] NULL,
	[10.5] [int] NULL,
	[11] [int] NULL,
	[11.5] [int] NULL,
	[12] [int] NULL,
	[13] [int] NULL,
	[13.5] [int] NULL,
	[14] [int] NULL,
	[15] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MensCurves] ADD  CONSTRAINT [PK_MensCurves] PRIMARY KEY CLUSTERED 
(
	[PoNumber] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

INSERT INTO MensCurves (
	Style
	,PoNumber
	,VendorID
	,StartDate
	,EndDate
	,Total
	,TargetPair
	,MerchGroup
	,QtyRecd
	,DeptID
	,ClassID
	,SubClass
	,Division
	,[5]
	,[6]
	,[7]
	,[7.5]
	,[8]
	,[8.5]
	,[9]
	,[9.5]
	,[10]
	,[10.5]
	,[11]
	,[11.5]
	,[12]
	,[13]
	,[13.5]
	,[14]
	,[15]
	)
VALUES (
	'803206'
	,'45299'
	,'431'
	,'1/8/2020'
	,'3/12/2020'
	,260
	,1
	,233
	,NULL
	,778
	,8
	,8000
	,8003
	,'M'
	,NULL
	,NULL
	,7
	,NULL
	,21
	,NULL
	,39
	,NULL
	,68
	,NULL
	,51
	,NULL
	,45
	,23
	,NULL
	,6
	,NULL
	),
    (
	'853206'
	,'45300'
	,'431'
	,'1/8/2020'
	,'6/08/2020'
	,280
	,1
	,234
	,NULL
	,780
	,8
	,8500
	,8503
	,'M'
	,NULL
	,NULL
	,6
	,NULL
	,28
	,NULL
	,55
	,NULL
	,70
	,NULL
	,56
	,NULL
	,39
	,24
	,NULL
	,2
	,NULL
	)
GO`

^^ that give you 2 real rows from my table


`        public async Task<SyncResult> Syncdb()
        {
            var serverProvider = new WebRemoteOrchestrator(Constants.endpoint);
            var clientProvider = new SqliteSyncProvider(Constants.DatabasePath);
            var agent = new SyncAgent(clientProvider, serverProvider);
            try
            {
                var syncContext = await agent.SynchronizeAsync("Curves");
                Debug.WriteLine(syncContext);
                return syncContext;
            }
            catch (Exception e)
            {
                Debug.WriteLine(e);
                return null;
            }
        }
`
^Sync on device

`var curvetables = new string[] 
{
    "KidsCurves",
    "InfantCurves" ,
    "MensCurves",
    "WomensCurves",
    "JuniorsCurves",
    "ToddlerCurves"
};
builder.Services.AddSyncServer<SqlSyncProvider>(con,"Curves",curvetables, options);
`
^ASP sync setup


Will that suffice?

Thank you again, fastest responses I've gotten on GitHub in forever!

**Comment by Mimetis** [comment]
add markdown formatting, and we are good to go

**Comment by Mimetis** [comment]
Your script does not work....
- `Style`, `PoNumber`, `VendorID` are int and your script is inserting **string** values..
-  There are fewer columns in the `INSERT` statement than values specified in the `VALUES` clause.

Here is the script I used, formatted, correct, readable, with table and db creation:

``` sql
USE [master]
GO 

-- Server database
if (exists (select * from sys.databases where name = 'AdventureWorks'))
Begin
	ALTER DATABASE [AdventureWorks] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [AdventureWorks]
End
Create database [AdventureWorks]
Go
USE [AdventureWorks]

CREATE TABLE [dbo].[MensCurves](
[Style] [int] NULL,
[PoNumber] [int] NOT NULL,
[VendorID] [int] NULL,
[StartDate] [date] NULL,
[EndDate] [date] NULL,
[Total] [int] NULL,
[Complete] [int] NULL,
[TargetPair] [int] NULL,
[MerchGroup] varchar NULL,
[QtyRecd] [int] NULL,
[DeptID] [int] NULL,
[ClassID] [int] NULL,
[Subclass] [int] NULL,
[Division] char NULL,
[5] [int] NULL,
[6] [int] NULL,
[7] [int] NULL,
[7.5] [int] NULL,
[8] [int] NULL,
[8.5] [int] NULL,
[9] [int] NULL,
[9.5] [int] NULL,
[10] [int] NULL,
[10.5] [int] NULL,
[11] [int] NULL,
[11.5] [int] NULL,
[12] [int] NULL,
[13] [int] NULL,
[13.5] [int] NULL,
[14] [int] NULL,
[15] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MensCurves] ADD CONSTRAINT [PK_MensCurves] PRIMARY KEY CLUSTERED
(
[PoNumber] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

INSERT INTO MensCurves (Style,PoNumber,VendorID,StartDate,EndDate,Total,TargetPair,MerchGroup,QtyRecd,DeptID,ClassID,SubClass,Division,
						[5],[6],[7],[7.5],[8],[8.5],[9],[9.5],[10],[10.5],[11],[11.5],[12],[13],[13.5],[14],[15])
VALUES	(803206,45299,431,'1/8/2020','3/12/2020',260,1,233,NULL,778,8,8000,'M',
		 NULL,NULL,7,NULL,21,NULL,39,NULL,68,NULL,51,NULL,45,23,NULL,6,NULL),
		('853206','45300','431','1/8/2020','6/08/2020',280,1,234,NULL,780,8,8500,'M',
		 NULL,NULL,6,NULL,28,NULL,55,NULL,70,NULL,56,NULL,39,24,NULL,2,NULL)
GO
```

Your problem is coming from the column names with a "_dot_" `.` in the name.
**DMS** is removing the "_dot_" and the left or right part of the column name

`[7.5]` is transformed to `[5]` that is already existing.

Do not use "_dot_" in column names and it should work.
