### ISSUE TITLE
 agent.LocalOrchestrator.OnRowsChangesApplied called twice.

### ISSUE THREAD

**Issue by rahulworx** [Mimetis/Dotmim.Sync#1121]
I have setup a timer to call synchronise every 3 minutes for the changes that occurs in a table. But my 
agent.LocalOrchestrator.OnRowsChangesApplied get called twice for every single change.
What can be the issue?

**Comment by Mimetis** [comment]
`OnRowsChangesApplied` is called for every table and depends on multiple factors:

- If you have multiple batch files to be applied, for one table, it will be called for each batch
- If you have set a batch a max lines count, it will be called also for each max lines count applied
- And finally it will be called for each state of your table `Modified` and `Deleted`

If your scenario, I guess it's called for the state `Modified` and `Deleted`

One thing you can do, is to check the values of the argument, something like that:

``` cs
agent.LocalOrchestrator.OnRowsChangesApplied(args =>
{
    // check state
    if (args.State == SyncRowState.Modified)
        Console.WriteLine("State: Insert or Edit rows");
    else if (args.State == SyncRowState.Deleted)
        Console.WriteLine("State: Delete rows");
    else
        Console.WriteLine($"State: Retry or Fail ?: {args.State}");

    // Check if we have some rows applied
    if (args.SyncRows == null || args.SyncRows.Count <= 0)
        Console.WriteLine($"No rows applied for this state");

});
```

If you don't have bulk mode enabled (Only `SqlSyncProvider` supports it),  `OnRowsChangesApplied` is called for every rows, twice (each state)

If you need less granular event, you can use 
- `OnBatchChangesApplied` that will only be raised for each batch files applied.
- `OnTableChangesApplied` that will occurs at the end, after all batches are applied and all conflicts resolved.

That being said, you still have two events raised, for each state (`Deleted` / `Modified`)

Obviously the lesser granular level would be `OnDatabaseChangesApplied`, I guess.

Make sense ?

**Comment by Mimetis** [comment]
That being said, I just made some tests and the interceptor should not be called twice for each rows...
Can you provide me a sample to be able to reproduce your issue ?
