### ISSUE TITLE
Insert in table with IDENTITY field fails

### ISSUE THREAD

**Issue by martonb** [Mimetis/Dotmim.Sync#1123]
Hi,
I have a table with an IDENTITY Id field, syncing into this fails even if I have DisableConstraintsOnApplyChanges in SyncOptions on true. I expected this option to set IDENTITY_INSERT to ON. Or this is the intended behaviour and I should change this myself?

Latest trunk version
SqlSyncChangeTrackingProvider

Cheers!

**Comment by Mimetis** [comment]
Identity works fine if it's used as primary keys.
It's not working if identity column are used as classic columns.
Is it your case ?

**Comment by martonb** [comment]
In the table it's defined as `[Id] [bigint] IDENTITY(1,1) NOT NULL`
Then the constraint is `ALTER TABLE [dbo].[TestTable] ADD  CONSTRAINT [PK_TestTable] PRIMARY KEY CLUSTERED ([Id] ASC)`

**Comment by Mimetis** [comment]
So it should work

**Comment by martonb** [comment]
The exact exception I got was: "Cannot insert explicit value for identity column in table 'TestTable' when IDENTITY_INSERT is set to OFF"

**Comment by Mimetis** [comment]
Can you provide the table definition you are using ?

**Comment by martonb** [comment]
Sure, I removed some fields to make it shorter:
`SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TestTable](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[UTCDateTime] [int] NULL,
	[Longitude] [decimal](18, 6) NULL,
	[Latitude] [decimal](18, 6) NULL,
	[Speed] [int] NULL,
	[Bearing] [int] NULL,
	[Altitude] [int] NULL,
	[InsertedOn] [datetime] NULL,
	[Partition] [smallint] NULL,
 CONSTRAINT [PK_TestTable] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TestTable] ADD  CONSTRAINT [DF_TestTable_InsertedOn]  DEFAULT (getdate()) FOR [InsertedOn]
GO`

**Comment by Mimetis** [comment]
It's working for me.

![image](https://github.com/Mimetis/Dotmim.Sync/assets/4592555/38664af3-30f7-4d76-98bb-fcdebc6d1b3b)

Is there any chance you made some tests with your table, and you have modified it without reprovisioning your sync ?

One thing you can do is trying to **deprovision** and then **provision** again your server & client databases.
Doing so will ensure your new table schema will be updated in stored procedures, triggers and tracking tables:

``` cs
var clientProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(clientDbName));
var serverProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(serverDbName));
var setup = new SyncSetup("TestTable");
var options = new SyncOptions();

var agent = new SyncAgent(clientProvider, serverProvider, options);

// Deprovision both remote and local db
await agent.RemoteOrchestrator.DeprovisionAsync(setup);
await agent.LocalOrchestrator.DeprovisionAsync(setup);

// Provision again
var serverScope = await agent.RemoteOrchestrator.ProvisionAsync(setup);
await agent.LocalOrchestrator.ProvisionAsync(serverScope);

```

**Comment by martonb** [comment]
I'll attach my test app, this one is with source code of Dotmim.Sync lib (trunk).
[EcomotiveSyncTest2.zip](https://github.com/Mimetis/Dotmim.Sync/files/13364726/EcomotiveSyncTest2.zip)

**Comment by Mimetis** [comment]
I will not download any zip file on my machine, sorry.
Please create a github repository if you want me to look into it

**Comment by martonb** [comment]
Just text files in the zip (project, C# sources, etc), but I understand your reluctance. Issue is, I have no git setup in our dev environment...

**Comment by Mimetis** [comment]
The idea is to recreate a really simple project reproducing the issue.
Not using your current project
Will be easier to debug for me if you are sharing a really simple project, because I will not have to go through a big project.
Focusing on the problem only, that's the key

**Comment by martonb** [comment]
Found the issue: the server table I was syncing from didn't actually have IDENTITY on the ID field (!), but my local data model, where I was syncing to, still contained IDENTITY. Recreated my local table from script of server table, issue does not reproduce any more.
Thank you!
