### ISSUE TITLE
Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) 

### ISSUE THREAD

**Issue by anthtoonaing** [Mimetis/Dotmim.Sync#1125]
I am using MariaDb on local machine and Google Cloud DB (MySQL) as backend database. I create both databases using **utf8mb4_unicode_ci** collations. I checked on both databases that all text fields are using **utf8mb4_unicode_ci**. I use WebSynchronization hosted in CloudRun using docker image. On local machine, I run DataSync agent on Windows Service. When I try to sync, I got the following error on local DataSync agent.

`  ├  ─ Error on table [customers]: Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='. Row:[Sync state]:ApplyModifiedFailed, [id]:123456, [name]:Mya Mya, [contact_number]:09123456789, [address]:<NULL />, [company_id]:123456, [is_referal]:False, [active]:True, [customer_discount_group_id]:<NULL />, [point_id]:<NULL />, [created_at]:12/01/2023 16:24:45, [updated_at]:<NULL />. ApplyType:Modified
  └  ─  ─ Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT) for operation '='
         at Dotmim.Sync.SyncAgent.SynchronizeAsync(String scopeName, SyncSetup setup, SyncType syncType, SyncParameters parameters, CancellationToken cancellationToken, IProgress``1 progress)
         at IV.DataSyncAgent.Worker.<>c__DisplayClass7_0.<<StartAsync>b__0>d.MoveNext() in D:\Working\saysaing\apps\DataSync\IV.DataSyncAgent\Workers.cs:line 55 ` 

When I google, I find that **utf8mb4_0900_ai_ci** is default collation of MySql. But my database on Google Cloud SQL doesn't use it. I create database using **utf8mb4_unicode_ci** collation. 

Please help how to solve this issue.

**Comment by Mimetis** [comment]
I don't have a solution for now.
What you can do, as a test, is to create the schema of your database on both side, client and server, and not let DMS do it for you.
That way, you are sure the collation is good.
On the first sync, DMS will create the required triggers and additional tracking tables

Let me know if it helps

**Comment by AvaSharkawy** [comment]
I have the same exception while trying to sync MySql Db with Sqlite Db
I've created MySql scheme using normal db script in Workbench, and created Sqlite db using ef core context migration
The exception occures when I modify value in sqlite db and try to sync it back to mysql, the opposite is working fine from mysql to sqlite.
Do you have any ideas?
Note: mysql use  utf8mb4_unicode_ci collation for every table, and my sql use TEXT COLLATE NOCASE on every string column in tables

**Comment by AvaSharkawy** [comment]
Update: I've scaffolded the source mysql database into classes and context, then I created the clientdb using the Ef Core Migrate and changed the sync to be mysql to mysql. The weird thing that the client db is created automatically using utf8mb4_0900_ai_ci collation. I don't know why that happens, but I believe if I fixed this it will solve my original issue with syncing mysql with sqlite without facing this exception illegal mix... 
I'll update here when I find solution

**Comment by AvaSharkawy** [comment]
I finally found the solution for my problem, the default mysql server charset was utf8mb4_0900_ai_ci, so when the sync initialized first time it was utf8mb4_0900_ai_ci
when I changed the default server collation to utf8mb4_unicode_ci and recreated the clientdb in my sql the same exception occured. so I deleted the server and client dbs and recreated them, and reinitialized the sync process it reinitialized with utf8mb4_unicode_ci
every thing working fine now, even with sqlite database

So the final solution is to change default server collation to utf8mb4_unicode_ci and reinitialize the sync process it will work perfect.

**Comment by AvaSharkawy** [comment]
I don't know if there is another solution as I'm new to mysql, I'm always using sql server
but with my searches and help of chat gpt I find this solution to my problem.
You can find better solution if you are familiar with mysql and its configs

**Comment by anthtoonaing** [comment]
It works on local machine, but does not on Google Cloud Database (MySql). I end up with using VM and install MariaDB on that VM instead of using Google Cloud MySql.

**Comment by AvaSharkawy** [comment]
Send this issue to google, tell them that yiu want to take control of mysql collation, to change it to utf8mb4_unicode_ci, I think if you do some search you will find this setting somewhere
