### ISSUE TITLE
[Critical] SQLite tables are created without indexes

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#113]
I noticed, that the _tracking tables on the sqlite client side are created without any indexes.

I consider this a **critical bug**

What could already help us a lot is some documentation about which columns to choose for indexing.
And a note in the documentation?

**Comment by gentledepp** [comment]
Here a short follow up!
I played around with a local sqlite database containing about ~50.000 records in a table "contentitems" - and of course also in the tracking table.
Now running the following query without indices (Note: as SQLite does not support parameters, I replaced them with some constant values)
```sql


SELECT 	[side].[Id], 
	[base].*, 
	[side].[sync_row_is_tombstone], 
	[side].[create_scope_id], 
	[side].[create_timestamp], 
	[side].[update_scope_id], 
	[side].[update_timestamp] 
FROM [ContentItems_tracking] [side]
LEFT JOIN [ContentItems] [base]
ON [base].[ID] = [side].[ID]
WHERE (
	-- Update made by the local instance
	[side].[update_scope_id] IS NULL
	-- Or Update different from remote
	OR [side].[update_scope_id] <> '3b1b537f-f34b-4883-bef3-e21ff205802a'
	-- Or we are in reinit mode so we take rows even thoses updated by the scope
	OR 0 = 1
    )
AND (
	-- And Timestamp is > from remote timestamp
	[side].[timestamp] > 20190909112002800
	OR
	-- remote instance is new, so we don't take the last timestamp
	0 = 1
	)
AND (
	[side].[sync_row_is_tombstone] = 1 
	OR
	([side].[sync_row_is_tombstone] = 0 AND [base].[ID] is not null	)
);

```

Now I thought  I could improve this query by adding indices on `update_scope_id` and `timestamp`.
So I played around a bit with one or both indices in place - or without them
```sql

create index ci_nulls on contentitems_tracking(update_scope_id);
--create index ci_nulls on contentitems_tracking(update_scope_id) where update_scope_id is null; 
create index ci_timestamp on contentitems_tracking(timestamp);
--drop index ci_nulls;
--drop index ci_timestamp;

``` 
Interestingly, no matter what I did, the query time was always around **0.030**

So I ran the query with "EXPLAIN QUERY PLAN"

```SQL

explain query plan
SELECT 	[side].[Id], 
	[base].*, 
	[side].[sync_row_is_tombstone], 
	[side].[create_scope_id], 
	[side].[create_timestamp], 
	[side].[update_scope_id], 
	[side].[update_timestamp] 
FROM [ContentItems_tracking] [side]
LEFT JOIN [ContentItems] [base]
ON [base].[ID] = [side].[ID]
WHERE (
	-- Update made by the local instance
	[side].[update_scope_id] IS NULL
	-- Or Update different from remote
	OR [side].[update_scope_id] <> '3b1b537f-f34b-4883-bef3-e21ff205802a'
	-- Or we are in reinit mode so we take rows even thoses updated by the scope
	OR 0 = 1
    )
AND (
	-- And Timestamp is > from remote timestamp
	[side].[timestamp] > 20190909112002800
	OR
	-- remote instance is new, so we don't take the last timestamp
	0 = 1
	)
AND (
	[side].[sync_row_is_tombstone] = 1 
	OR
	([side].[sync_row_is_tombstone] = 0 AND [base].[ID] is not null	)
);

```
which showed me:
| selectid | order | from | detail                                                                               |   |
|----------|-------|------|--------------------------------------------------------------------------------------|---|
| 0        | 0     | 0    | SCAN TABLE ContentItems_tracking AS side                                             |   |
| 0        | 1     | 1    | SEARCH TABLE ContentItems AS base USING INDEX sqlite_autoindex_ContentItems_1 (Id=?) |   |
|          |       |      |                                                                                      |   |

As you can see, there is a `SCAN` going on, which does not use any index!

Now having a bit of experience with query optimization, I figured that the query was simply too complicated for SQLite to create a query plan that uses indexes only.
This is most of the time because of an OR statement.
Rule of thumb: Place an index on a column that has unique values - if possible. 
As `update_scope_id` will not have many different values (just a couple to several dozens), but `timestamp` has many unique ones, I removed the part 
```SQL 
        OR
	-- remote instance is new, so we don't take the last timestamp
	0 = 1
```

This yielded **much** better query times at around **0.006**!
This is already faster by a factor of **5**!

Keep in mind, that I ran this on a full-blown developer machine (i7 with 32 GB RAM and SSD)
On a mobile device, the query time is surely several times higher!

So I ran "explain query" again
```SQL
explain query plan
SELECT 	[side].[Id], 
	[base].*, 
	[side].[sync_row_is_tombstone], 
	[side].[create_scope_id], 
	[side].[create_timestamp], 
	[side].[update_scope_id], 
	[side].[update_timestamp] 
FROM [ContentItems_tracking] [side]
LEFT JOIN [ContentItems] [base]
ON [base].[ID] = [side].[ID]
WHERE (
	-- Update made by the local instance
	[side].[update_scope_id] IS NULL
	-- Or Update different from remote
	OR [side].[update_scope_id] <> '3b1b537f-f34b-4883-bef3-e21ff205802a'
	-- Or we are in reinit mode so we take rows even thoses updated by the scope
	OR 0 = 1
    )
AND (
	-- And Timestamp is > from remote timestamp
	[side].[timestamp] > 20190909112002800
	)
AND (
	[side].[sync_row_is_tombstone] = 1 
	OR
	([side].[sync_row_is_tombstone] = 0 AND [base].[ID] is not null	)
);

```
which now showed
| selectid | order | from | detail                                                                               |   |
|----------|-------|------|--------------------------------------------------------------------------------------|---|
| 0        | 0     | 0    | SCAN TABLE ContentItems_tracking AS side                                             |   |
| 0        | 1     | 1    | SEARCH TABLE ContentItems AS base USING INDEX sqlite_autoindex_ContentItems_1 (Id=?) |   |
|          |       |      |                                                                                      |   |

As you can see, there are two `SEARCH` es now instead of a `SCAN`.

So my idea:
As you do know if you are running a "reinit" or if the remote instance is new **before** running the query, you could very well have **separate queries** for each of those scenarios.
Then, they would not need to have this "OR - complexity" and the performance improvements on the query side would be enormous!

I did not yet find the time to also have a look at the query plan and performance of the queries in MS SQL Server, but I could imagine that it is the same story there.

What do you think?

**Comment by gentledepp** [comment]
you closed this issue - does this mean indexes are now created for sqlite tables? 😀

**Comment by Mimetis** [comment]
Hey @gentledepp !   
Good to see you here again :)

Indeed, I've updated the tracking table indexes on the SQLite provider.   
You can see the result here : 

https://github.com/Mimetis/Dotmim.Sync/blob/168879f81a8e13a0f294de36e6d7ba3f1d2ed0e5/Projects/Dotmim.Sync.Sqlite/Builders/SQLiteBuilderTrackingTable.cs#L118

You're way better than me on SQLite indexes diagnostics, so if you want to make some tests with the new version `v0.5`, I'll really appreciate and it will help a lot.

Let me know.

**Comment by Mimetis** [comment]
By the way, the `table_changes` stored procedure is way more simplier and performant than before.
I've tried to reduce the amount of clauses in the where statement:

``` sql
SELECT DISTINCT	[side].[CustomerID], 
	[base].[EmployeeID], 
	[base].[NameStyle], 
	[base].[Title], 
	[base].[FirstName], 
	[base].[LastName], 
	[side].[sync_row_is_tombstone], 
	[side].[update_scope_id] 
FROM [Customer] [base]
RIGHT JOIN [Customer_tracking] [side] ON [base].[CustomerID] = [side].[CustomerID]
WHERE (
	[side].[timestamp] > @sync_min_timestamp
	AND ([side].[update_scope_id] <> @sync_scope_id OR [side].[update_scope_id] IS NULL)
```

So far, an index placed on `timestamp`, `update_scope_id` and `sync_row_is_tombstone` should be enough, I guess

**Comment by gentledepp** [comment]
> You can see the result here :

Nice!

> You're way better than me on SQLite indexes diagnostics, so if you want to make some tests with the new version v0.5, I'll really appreciate and it will help a lot.

Well *if* on the sqlite side there are now also 3 (?) stored procedures (for re-init, sync and full-sync so that the stored procedures do not rely on ` or ` conditions so much anymore) **and** you also have this timestamp index then this will be fast as f*** 🚀

Is that the case? (with the separate stored procedures?)

Sorry - I really have very little time. We're working hard on our product and while I still have a list of things I'd like to contribute I just never find the time or motivation to...  :-|

**Comment by gentledepp** [comment]
Uh... you were too fast.
Sry

> So far, an index placed on timestamp, update_scope_id and sync_row_is_tombstone should be enough, I guess

No matter which relational database you use, you should only ever index columns which have a "distinct enough value" so that indexing actually makes sense.
This means, a column where 50% of the values are equal is a very bad choice for indexes, because you will have the overhead of managing this index while any read operation will not be faster than a full table scan.

This means:
 - `sync_row_is_tombstone` is boolean and thus should not be indexed ;-)
 -  `timestamp` is a good choice because it is used in filter expressions a lot *and* contains very different values
 - `update_scope_id` is a GUID column and therefore also a good choice. While some of the values will be NULL, I expect most of them to be filled with the servers ID and the IDs of numerous other clients

You can read this in the following book: [SQL Server 2008 Query Performance Tuning Distilled (Expert's Voice in SQL Server) ](https://www.amazon.de/Server-Performance-Tuning-Distilled-Experts/dp/1430219025) - I learned almost everything about query perf with this. And while it is written for SQL Server, a lot of it applies to other databases as well.

One key takeaway is also: Combined indexes are very specialized for certain queries.
Let's assume you have an index 
'CREATE INDEX IX_CombinedDemo on demo_tracking (timestamp, update_scope_id)` 
Then the *order* of the columns used in the index matters!
In this demo, the index *can* be used if you filter on `timestamp` only.
like here
'select * from demo_tracking where timestamp > 5542'  
However, the index **cannot** be used if you only filter on `update_scope_id`!
So 
'select * from demo_tracking where update_scope_id > 'c83f8614-a8a2-48ab-bf7a-8cf5d479a758''  
will actually do a **full table scan**!
Quite interesting - isn't it? :-)


That is the absolute indexing 101 - everything you need to consider when thinking about applying an index on a column (or multiple columns) ;-)

**Comment by Mimetis** [comment]
yes, make sense :)

So far, the `_changes` stored procedure is the only stored procedure, who needs to be indexed.   
I guess it simplifies things :)

Regarding the `sync_row_is_tombstone ` bit, included in the index.   
It's intentional to add it in the index, even if it's not used "as an index".

If I don't include it, the SQL engine will have to make a "lookup" on the cluster b-tree to retrieve the value, because the `_changes` stored procedure needs the `sync_row_is_tombstone ` value in the `Select` clause:

``` sql
SELECT DISTINCT	[side].[CustomerID], 
	[base].[EmployeeID], 
        ...
	[side].[sync_row_is_tombstone], 
	[side].[update_scope_id]
```

Including the value in the index allows us to basically "not have to lookup the cluster b'tree in the tracking table, for a single bit value'

So far, we can say that:

Creating an index with `timeStamp` and `update_scope_id` will force the engine to:
- Make a **index seek** on the non clustered index to get the  `timestamp`, `update_scope` and the customer table primary keys values in the best and efficient way to do it
- Make a **look up** query on the customer `tracking table` to get the `sync_row_is_tombstone` value
- Make an **index seek** in the customer table to get relevant rows 

Creating an index with `timeStamp` `update_scope_id` and `sync_row_is_tombstone` will force the engine to:
- Make a **index seek** on the non clustered index to get the  `timestamp`, `update_scope`, `sync_row_is_tombstone`  and the table primary keys values in the best and efficient way to do it
- Make an **index seek** in the customer table to get relevant rows

**Comment by gentledepp** [comment]
> Regarding the sync_row_is_tombstone bit, included in the index.
> It's` intentional to add it in the index, even if it's not used "as an index".
> 
If I don't include it, the SQL engine will have to make a "lookup" on the cluster b-tree to retrieve the value, because the _changes stored procedure needs the sync_row_is_tombstone value in the Select clause

Ah I see. So in T-SQL you could use "include" here (to just include column in an index but not index it itself) but SQLite apparently does not have that functionality.
Nice work!

**Comment by Mimetis** [comment]
Yes, I know the "include" stuff, I kept everything simple, and including *1* bit is not a big deal for a non clustered index :)
#KeepItSimple
