### ISSUE TITLE
.Net Standard 2.1 for use with Unity?

### ISSUE THREAD

**Issue by darren-beckett** [Mimetis/Dotmim.Sync#1131]
Is there a possibility you can provide a .Net Standard 2.1 version for use with Unity?

or a .Net 4.8, i think that'll work too.

**Comment by Mimetis** [comment]
**DMS** supports  `.Net Standard 2.0` 
Is it not enough ?

**Comment by darren-beckett** [comment]
Unfortunately not, it produces an error stating it won't run on this
platform.

Regards
Darren Beckett

**Comment by Mimetis** [comment]
Can you add more context please ?
Which kind of error ?
I don't have unity, so I can't figure it out with no context

**Comment by darren-beckett** [comment]
```
// Sql Server provider, the "server" or "hub".
SqlSyncProvider serverProvider = new SqlSyncProvider(db_remote);

// Sqlite Client provider acting as the "client"
SqliteSyncProvider clientProvider = new SqliteSyncProvider(db_local);

// Sync agent
syncService = new SyncAgent(clientProvider, serverProvider);

SyncSetup syncAllSetup = new SyncSetup("UserProfiles", "Games");

Task task = syncService.SynchronizeAsync(syncAllSetup);
yield return new WaitUntil(() => task.IsCompleted);
```

**Error produced:**
"System.AggregateException: One or more errors occurred. ([NeedsToUpgradeAsync]..[GetConnectionAsync]..Windows Principal functionality is not supported on this platform.) ---> Dotmim.Sync.SyncException: [NeedsToUpgradeAsync]..[GetConnectionAsync]..Windows Principal functionality is not supported on this platform. ---> System.PlatformNotSupportedException: Windows Principal functionality is not supported on this platform.\r\n  at System.Security.Principal.WindowsIdentity.GetCurrent () [0x00005] in <d063f3526787470781589fcdd6107c4c>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrentNative () [0x00000] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionPoolIdentity.Windows.cs:23 \r\n  at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent () [0x00000] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionPoolIdentity.Windows.cs:17 \r\n  at Microsoft.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool (Microsoft.Data.ProviderBase.DbConnectionFactory connectionFactory) [0x00020] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionPoolGroup.cs:170 \r\n  at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPool (System.Data.Common.DbConnection owningObject, Microsoft.Data.ProviderBase.DbConnectionPoolGroup connectionPoolGroup) [0x00065] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Common\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionFactory.cs:197 \r\n  at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection (System.Data.Common.DbConnection owningConnection, System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.Common.DbConnectionOptions userOptions, Microsoft.Data.ProviderBase.DbConnectionInternal oldConnection, Microsoft.Data.ProviderBase.DbConnectionInternal& connection) [0x00011] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionFactory.cs:45 \r\n  at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal (System.Data.Common.DbConnection outerConnection, Microsoft.Data.ProviderBase.DbConnectionFactory connectionFactory, System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.Common.DbConnectionOptions userOptions) [0x00036] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Common\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionInternal.cs:350 \r\n  at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection (System.Data.Common.DbConnection outerConnection, Microsoft.Data.ProviderBase.DbConnectionFactory connectionFactory, System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.Common.DbConnectionOptions userOptions) [0x00000] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Common\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionClosed.cs:39 \r\n  at Microsoft.Data.SqlClient.SqlConnection.TryOpen (System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.SqlClient.SqlConnectionOverrides overrides) [0x000df] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Microsoft\\Data\\SqlClient\\SqlConnection.cs:1844 \r\n  at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync (System.Threading.CancellationToken cancellationToken) [0x000c9] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Microsoft\\Data\\SqlClient\\SqlConnection.cs:1627 \r\n--- End of stack trace from previous location where exception was thrown ---\r\n\r\n  at Dotmim.Sync.SyncPolicy+<>c__DisplayClass14_0.<ExecuteAsync>b__0 () [0x0006d] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.SyncPolicy.InternalExecuteAsync[TResult] (System.Func`1[TResult] operation, System.Threading.CancellationToken cancellationToken, System.Object arg) [0x00132] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.BaseOrchestrator.OpenConnectionAsync (Dotmim.Sync.SyncContext context, System.Data.Common.DbConnection connection, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00140] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.DbConnectionRunnerExtensions.GetConnectionAsync (Dotmim.Sync.BaseOrchestrator orchestrator, Dotmim.Sync.SyncContext context, Dotmim.Sync.Enumerations.SyncMode syncMode, Dotmim.Sync.Enumerations.SyncStage syncStage, System.Data.Common.DbConnection connection, System.Data.Common.DbTransaction transaction, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00161] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n   --- End of inner exception stack trace ---\r\n  at Dotmim.Sync.RemoteOrchestrator.NeedsToUpgradeAsync (Dotmim.Sync.SyncContext context) [0x0068a] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.SyncAgent.SynchronizeAsync (System.String scopeName, Dotmim.Sync.SyncSetup setup, Dotmim.Sync.Enumerations.SyncType syncType, Dotmim.Sync.SyncParameters parameters, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x017e0] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.SyncAgent.SynchronizeAsync (System.String scopeName, Dotmim.Sync.SyncSetup setup, Dotmim.Sync.Enumerations.SyncType syncType, Dotmim.Sync.SyncParameters parameters, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x019aa] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n   --- End of inner exception stack trace ---\r\n---> (Inner Exception #0) Dotmim.Sync.SyncException: [NeedsToUpgradeAsync]..[GetConnectionAsync]..Windows Principal functionality is not supported on this platform. ---> System.PlatformNotSupportedException: Windows Principal functionality is not supported on this platform.\r\n  at System.Security.Principal.WindowsIdentity.GetCurrent () [0x00005] in <d063f3526787470781589fcdd6107c4c>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrentNative () [0x00000] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionPoolIdentity.Windows.cs:23 \r\n  at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent () [0x00000] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionPoolIdentity.Windows.cs:17 \r\n  at Microsoft.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool (Microsoft.Data.ProviderBase.DbConnectionFactory connectionFactory) [0x00020] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionPoolGroup.cs:170 \r\n  at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPool (System.Data.Common.DbConnection owningObject, Microsoft.Data.ProviderBase.DbConnectionPoolGroup connectionPoolGroup) [0x00065] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Common\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionFactory.cs:197 \r\n  at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection (System.Data.Common.DbConnection owningConnection, System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.Common.DbConnectionOptions userOptions, Microsoft.Data.ProviderBase.DbConnectionInternal oldConnection, Microsoft.Data.ProviderBase.DbConnectionInternal& connection) [0x00011] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionFactory.cs:45 \r\n  at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal (System.Data.Common.DbConnection outerConnection, Microsoft.Data.ProviderBase.DbConnectionFactory connectionFactory, System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.Common.DbConnectionOptions userOptions) [0x00036] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Common\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionInternal.cs:350 \r\n  at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection (System.Data.Common.DbConnection outerConnection, Microsoft.Data.ProviderBase.DbConnectionFactory connectionFactory, System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.Common.DbConnectionOptions userOptions) [0x00000] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Common\\src\\Microsoft\\Data\\ProviderBase\\DbConnectionClosed.cs:39 \r\n  at Microsoft.Data.SqlClient.SqlConnection.TryOpen (System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.SqlClient.SqlConnectionOverrides overrides) [0x000df] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Microsoft\\Data\\SqlClient\\SqlConnection.cs:1844 \r\n  at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync (System.Threading.CancellationToken cancellationToken) [0x000c9] in D:\\a\\_work\\1\\s\\src\\Microsoft.Data.SqlClient\\netcore\\src\\Microsoft\\Data\\SqlClient\\SqlConnection.cs:1627 \r\n--- End of stack trace from previous location where exception was thrown ---\r\n\r\n  at Dotmim.Sync.SyncPolicy+<>c__DisplayClass14_0.<ExecuteAsync>b__0 () [0x0006d] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.SyncPolicy.InternalExecuteAsync[TResult] (System.Func`1[TResult] operation, System.Threading.CancellationToken cancellationToken, System.Object arg) [0x00132] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.BaseOrchestrator.OpenConnectionAsync (Dotmim.Sync.SyncContext context, System.Data.Common.DbConnection connection, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00140] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.DbConnectionRunnerExtensions.GetConnectionAsync (Dotmim.Sync.BaseOrchestrator orchestrator, Dotmim.Sync.SyncContext context, Dotmim.Sync.Enumerations.SyncMode syncMode, Dotmim.Sync.Enumerations.SyncStage syncStage, System.Data.Common.DbConnection connection, System.Data.Common.DbTransaction transaction, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00161] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n   --- End of inner exception stack trace ---\r\n  at Dotmim.Sync.RemoteOrchestrator.NeedsToUpgradeAsync (Dotmim.Sync.SyncContext context) [0x0068a] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.SyncAgent.SynchronizeAsync (System.String scopeName, Dotmim.Sync.SyncSetup setup, Dotmim.Sync.Enumerations.SyncType syncType, Dotmim.Sync.SyncParameters parameters, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x017e0] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.SyncAgent.SynchronizeAsync (System.String scopeName, Dotmim.Sync.SyncSetup setup, Dotmim.Sync.Enumerations.SyncType syncType, Dotmim.Sync.SyncParameters parameters, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x019aa] in <b500f13f719d4797bcaad4e5c360168d>:0 <---\r\n"

**Comment by Mimetis** [comment]
Seems the problem is coming from `Microsoft.Data.SqlClient`
Are you able to use `Microsoft.Data.SqlClient` in a Unity project ?

**Comment by darren-beckett** [comment]
I believe it's compatible:
https://www.nuget.org/packages/Microsoft.Data.SqlClient#supportedframeworks-body-tab

Regards
Darren Beckett.

**Comment by Mimetis** [comment]
Did you tested it ?

**Comment by darren-beckett** [comment]
This is my first use of dotmim.sync, so I have only just added
Microsoft.Data.SqlClient to the Unity project, but I have seen posts from
others who have used it successfully.

**Comment by darren-beckett** [comment]
I have refreshed my Plugins folder and used nuget to grab everything again, I am now getting this:

"System.AggregateException: One or more errors occurred. ([NeedsToUpgradeAsync]..[GetConnectionAsync]..The method or operation is not implemented.) ---> Dotmim.Sync.SyncException: [NeedsToUpgradeAsync]..[GetConnectionAsync]..The method or operation is not implemented. ---> System.NotImplementedException: The method or operation is not implemented.\r\n  at System.Security.Principal.WindowsIdentity.get_AccessToken () [0x00000] in <17d9ce77f27a4bd2afb5ba32c9bea976>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrentNative () [0x00006] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent () [0x00007] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool (Microsoft.Data.ProviderBase.DbConnectionFactory connectionFactory) [0x00020] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPool (System.Data.Common.DbConnection owningObject, Microsoft.Data.ProviderBase.DbConnectionPoolGroup connectionPoolGroup) [0x00065] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection (System.Data.Common.DbConnection owningConnection, System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.Common.DbConnectionOptions userOptions, Microsoft.Data.ProviderBase.DbConnectionInternal oldConnection, Microsoft.Data.ProviderBase.DbConnectionInternal& connection) [0x00011] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal (System.Data.Common.DbConnection outerConnection, Microsoft.Data.ProviderBase.DbConnectionFactory connectionFactory, System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.Common.DbConnectionOptions userOptions) [0x00036] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection (System.Data.Common.DbConnection outerConnection, Microsoft.Data.ProviderBase.DbConnectionFactory connectionFactory, System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.Common.DbConnectionOptions userOptions) [0x00000] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.SqlClient.SqlConnection.TryOpen (System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.SqlClient.SqlConnectionOverrides overrides) [0x000f3] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync (System.Threading.CancellationToken cancellationToken) [0x000c9] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n--- End of stack trace from previous location where exception was thrown ---\r\n\r\n  at Dotmim.Sync.SyncPolicy+<>c__DisplayClass14_0.<ExecuteAsync>b__0 () [0x0006d] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.SyncPolicy.InternalExecuteAsync[TResult] (System.Func`1[TResult] operation, System.Threading.CancellationToken cancellationToken, System.Object arg) [0x00132] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.BaseOrchestrator.OpenConnectionAsync (Dotmim.Sync.SyncContext context, System.Data.Common.DbConnection connection, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00140] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.DbConnectionRunnerExtensions.GetConnectionAsync (Dotmim.Sync.BaseOrchestrator orchestrator, Dotmim.Sync.SyncContext context, Dotmim.Sync.Enumerations.SyncMode syncMode, Dotmim.Sync.Enumerations.SyncStage syncStage, System.Data.Common.DbConnection connection, System.Data.Common.DbTransaction transaction, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00161] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n   --- End of inner exception stack trace ---\r\n  at Dotmim.Sync.RemoteOrchestrator.NeedsToUpgradeAsync (Dotmim.Sync.SyncContext context) [0x0068a] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.SyncAgent.SynchronizeAsync (System.String scopeName, Dotmim.Sync.SyncSetup setup, Dotmim.Sync.Enumerations.SyncType syncType, Dotmim.Sync.SyncParameters parameters, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x017e0] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.SyncAgent.SynchronizeAsync (System.String scopeName, Dotmim.Sync.SyncSetup setup, Dotmim.Sync.Enumerations.SyncType syncType, Dotmim.Sync.SyncParameters parameters, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x019aa] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n   --- End of inner exception stack trace ---\r\n---> (Inner Exception #0) Dotmim.Sync.SyncException: [NeedsToUpgradeAsync]..[GetConnectionAsync]..The method or operation is not implemented. ---> System.NotImplementedException: The method or operation is not implemented.\r\n  at System.Security.Principal.WindowsIdentity.get_AccessToken () [0x00000] in <17d9ce77f27a4bd2afb5ba32c9bea976>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrentNative () [0x00006] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent () [0x00007] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool (Microsoft.Data.ProviderBase.DbConnectionFactory connectionFactory) [0x00020] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPool (System.Data.Common.DbConnection owningObject, Microsoft.Data.ProviderBase.DbConnectionPoolGroup connectionPoolGroup) [0x00065] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection (System.Data.Common.DbConnection owningConnection, System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.Common.DbConnectionOptions userOptions, Microsoft.Data.ProviderBase.DbConnectionInternal oldConnection, Microsoft.Data.ProviderBase.DbConnectionInternal& connection) [0x00011] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal (System.Data.Common.DbConnection outerConnection, Microsoft.Data.ProviderBase.DbConnectionFactory connectionFactory, System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.Common.DbConnectionOptions userOptions) [0x00036] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection (System.Data.Common.DbConnection outerConnection, Microsoft.Data.ProviderBase.DbConnectionFactory connectionFactory, System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.Common.DbConnectionOptions userOptions) [0x00000] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.SqlClient.SqlConnection.TryOpen (System.Threading.Tasks.TaskCompletionSource`1[TResult] retry, Microsoft.Data.SqlClient.SqlConnectionOverrides overrides) [0x000f3] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n  at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync (System.Threading.CancellationToken cancellationToken) [0x000c9] in <c42b2cf9cc9d45d3a2f9ef43cee85790>:0 \r\n--- End of stack trace from previous location where exception was thrown ---\r\n\r\n  at Dotmim.Sync.SyncPolicy+<>c__DisplayClass14_0.<ExecuteAsync>b__0 () [0x0006d] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.SyncPolicy.InternalExecuteAsync[TResult] (System.Func`1[TResult] operation, System.Threading.CancellationToken cancellationToken, System.Object arg) [0x00132] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.BaseOrchestrator.OpenConnectionAsync (Dotmim.Sync.SyncContext context, System.Data.Common.DbConnection connection, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00140] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.DbConnectionRunnerExtensions.GetConnectionAsync (Dotmim.Sync.BaseOrchestrator orchestrator, Dotmim.Sync.SyncContext context, Dotmim.Sync.Enumerations.SyncMode syncMode, Dotmim.Sync.Enumerations.SyncStage syncStage, System.Data.Common.DbConnection connection, System.Data.Common.DbTransaction transaction, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00161] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n   --- End of inner exception stack trace ---\r\n  at Dotmim.Sync.RemoteOrchestrator.NeedsToUpgradeAsync (Dotmim.Sync.SyncContext context) [0x0068a] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.SyncAgent.SynchronizeAsync (System.String scopeName, Dotmim.Sync.SyncSetup setup, Dotmim.Sync.Enumerations.SyncType syncType, Dotmim.Sync.SyncParameters parameters, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x017e0] in <b500f13f719d4797bcaad4e5c360168d>:0 \r\n  at Dotmim.Sync.SyncAgent.SynchronizeAsync (System.String scopeName, Dotmim.Sync.SyncSetup setup, Dotmim.Sync.Enumerations.SyncType syncType, Dotmim.Sync.SyncParameters parameters, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x019aa] in <b500f13f719d4797bcaad4e5c360168d>:0 <---\r\n"
