### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by BabethMuissa** [Mimetis/Dotmim.Sync#1135]
Hi,
How can i log synchronization activities? can i get an example?
which one would work better: syncoption.logger or interceptors?
thanks

**Comment by Mimetis** [comment]
I think Logging can fit your need
Take a look here : https://github.com/Mimetis/Dotmim.Sync/blob/97142a7864afc4631f5ee043869c127a0c612590/Samples/Dotmim.Sync.SampleConsole/Program.cs#L775

I guess, I should create a real sample about logging
