### ISSUE TITLE
Unexpected end when deserializing array

### ISSUE THREAD

**Issue by damien-c-d** [Mimetis/Dotmim.Sync#1136]
Occasionally during the sync process using SqlSyncChangeTrackingProvider I encounter the error: 

Newtonsoft.Json.JsonSerializationException: 'Unexpected end when deserializing array. Path 't[0].c[69].t', line 1, position 2048.'

It is happening in LocalJsonSerializer.cs at the breakpoint here:

![image](https://github.com/Mimetis/Dotmim.Sync/assets/53846872/63a4057a-4170-4dae-b7f4-bbba2508036f)

**Comment by Mimetis** [comment]
are you able to reproduce it ?

**Comment by damien-c-d** [comment]
I believe it had something to with differences in Collation. One database was using Latin1_General_CI_AS and the other was using SQL_Latin1_General_CP1_CI_AS. We had to use sqlpackage to get around this and migrate from one to the other. 

We are now experiencing a different error which I'll open another issue for.
