### ISSUE TITLE
ArgumentOutOfRangeException during sync.

### ISSUE THREAD

**Issue by damien-c-d** [Mimetis/Dotmim.Sync#1137]
I am getting an error with the message below when calling SyncAgent.SyncrhonizeAsync(). I am using the [ASP.NET Core Web Proxy](https://dotmimsync.readthedocs.io/Web.html#simple-scope) and [handling conflicts from the client side](https://dotmimsync.readthedocs.io/Conflict.html#handling-conflicts-from-the-client-side). The exception doesn't provide much helpful information e.g. what table the error occurred in and we have over 60 tables that are syncing.

Dotmim.Sync.SyncException: '[InternalApplyChangesAsync]..[InternalApplyChangesAsync]..[InternalApplyTableChangesAsync]..Specified argument was out of the range of valid values. (Parameter 'Can't make a query on primary keys since number of primary keys columns in criteria is not matching the number of primary keys columns in this table')'

![image](https://github.com/Mimetis/Dotmim.Sync/assets/53846872/c2f928a1-cfc3-44c9-8fff-de3a853bc95d)

**Comment by Mimetis** [comment]
Hard to debug with that stacktrace

Did you make any schema changes recently ?
Could be cause of this kind of error

**Comment by damien-c-d** [comment]
Haven't made schema changes. It seems to occur after a client doesn't sync for a day or so after changes are being synced from other clients.  Is there something I should try or check for?

**Comment by Nicmanthecodeman** [comment]
@damien-c-d Did you manage to solve the problem? I'm having the exact same exception when the client is idle for a time while other clients synced.

**Comment by Nicmanthecodeman** [comment]
I managed to retrieve more information regarding the exception by using the following code and inspecting the args:

![image](https://github.com/Mimetis/Dotmim.Sync/assets/44663302/fccaa0a8-7554-4da7-b5b4-d147739d2e77)

**Comment by damien-c-d** [comment]
Not really. I did find that it is the result of another exception being swallowed when caught internally within the library. Most common ones I've seen are violation of constraints e.g. Unique indexes that aren't a primary key, or auto-incrementing identity columns that aren't a primary key.

Whenever it happens I have to get a copy of the client database and run in Debug mode with Just my code disabled in VS2022. 

Sometimes this doesn't work though and I have to remove the NuGet packages, clone the repo, and reference the projects directly.

**Comment by Nicmanthecodeman** [comment]
@damien-c-d  In my case I was able to inspect the exception using the OnApplyChangesErrorOccured method on the LocalOrchestrator and it was indeed a violation of a constraint on the client database.

Thank you for the feedback.

**Comment by Mimetis** [comment]
I tried as much as possible to get the most detailed exception message I can retrieve, but sometimes the only thing I have is coming from the database itself.
And when the database is sqlite, the messages are often to really useful.
Regarding the first message, this is obviously a problem of an alter schema somewhere where you have modified the primary keys.
Or maybe, as you said, a constraint violation.
If you have any idea that could improve the error handling, let me know.

**Comment by Mimetis** [comment]
I think I've found the issue.
It has been resolved in this commit https://github.com/Mimetis/Dotmim.Sync/commit/f740ca8412ac6bd0cc9893b1c1713798a477cb8b

You can test with the latest beta version

Do not hesitate to re open the issue if you still have this issue
