### ISSUE TITLE
Provisioning and Deprovisioning

### ISSUE THREAD

**Issue by charristti** [Mimetis/Dotmim.Sync#1138]
Using 1.0.0-beta-1517 with Net8.02, MS Sql Server Express 2017, with Sql Change Tracking
1) When provisioning a scope, occasionally getting scope_info records with sync_scope_schema and sync_scope_setup both set to null. Deleting the records and reprovisioning usually works.
2) When deprovisioning a scope the table property Change Tracking is being set to False even though there are other scopes still referencing the same table.

**Comment by Mimetis** [comment]
> When provisioning a scope, occasionally getting scope_info records with `sync_scope_schema` and `sync_scope_setup` both set to null. Deleting the records and reprovisioning usually works.

Not sure I understand.
Can you elaborate a little bit ?

> When deprovisioning a scope the table property Change Tracking is being set to False even though there are other scopes still referencing the same table.

`DeprovisionAsync` is .... deprovioning.... regardless any others scopes.
IF you don't want to deprovision a table, check the others scopes before, to see if the table is used somewhere else ?

That's being said, this is something we can also do in the framework

**Comment by charristti** [comment]
Thank you for your response. I have changed the settings when
deprovisioning to no longer remove the tracking file. I have not been able
to reproduce the first issue since I added some additional logging to try
and isolate the issue

Thanks again.
