### ISSUE TITLE
Force sync in particular direction regardless?

### ISSUE THREAD

**Issue by spj-uk** [Mimetis/Dotmim.Sync#1140]
Is it possible to force a sync in one direction? 

For example a users table in SQL Server and pull it down to the local to overwrite any existing records.

**Comment by RafaelFOl** [comment]
I have the same question.
I need to configure in one direction Sqlite -> postgres.
This is possible?

**Comment by Mimetis** [comment]
I guess you have to set the `SyncDirection` : https://dotmimsync.readthedocs.io/Synchronize.html#syncdirection 

Will close the issue, but feel free to ask for reopening if I misunderstood
