### ISSUE TITLE
SynchronousProgress<T> in WinUI 3/AppSdk app: The send method is not supported, use Post instead.

### ISSUE THREAD

**Issue by Christian-Fenzl** [Mimetis/Dotmim.Sync#1141]
If SynchronousProgress<T> is used in a WinUI 3/AppSdk application an exception is thrown when the sync is started which tells:
"The send method is not supported, use Post instead."

Changing line 73 in /Projects/Dotmim.Sync.Core/Interceptors/SynchronousProgress.cs 
`m_synchronizationContext.Send(m_invokeHandlers, value);`
to
`m_synchronizationContext.Post(m_invokeHandlers, value);`
and everything works fine.

Thanks for the great lib!

**Comment by Mimetis** [comment]
`SynchronousProgress` should only be used in a console application.

Use a classich `Progress<T>` instead.

That's being said, if `Post` is better than `Send` it's worth !

Can you make a quick PR ?
