### ISSUE TITLE
Error: Procedure or function expects parameter which was not supplied..

### ISSUE THREAD

**Issue by KaloyJS** [Mimetis/Dotmim.Sync#1147]
Hi,
Trying out the library to sync our SQL Server from local to cloud and I keep running to errors like these:

 Error during synchronization: [InternalApplyChangesAsync]..Error on table [Performance_Person_T]: Procedure or function 'Performance_Person_T_EYjWb_update' expects parameter '@Performance_Person_ID', which was not supplied.. 

Row:[Sync state]:ApplyModifiedFailed, [Performance_ID]:9089, [Person_Position_Organization_ID]:7996, [Timestamp_DT]:12/12/2007 12:57:40 PM, [PerformanceId]:00002381-0000-0000-0000-000000000000, [PersonPositionOrganizationId]:00001f3c-0000-0000-0000-000000000000, [Id]:00000100-0000-0000-0000-000000000000, [TenantId]:00000000-0000-0000-0000-000000000000, [ExtraProperties]:<NULL />, [ConcurrencyStamp]:<NULL />, [CreatorId]:00000000-0000-0000-0000-000000000000, [CreationTime]:12/12/2007 12:57:40 PM, [LastModifierId]:<NULL />, [LastModificationTime]:<NULL />, [EntityVersion]:0. ApplyType:Modified

Also can anyone point me to see what are the allowed column types?

**Comment by KaloyJS** [comment]
Also is there a way to skips stored procedures, views and udf?

**Comment by Mimetis** [comment]
If you have some errors with stored procedure, usually, it comes the fact that you probably change your schema, removing or adding columns or table, after having setup your sync

If you are just testing, try to make a `DeprovisionAsync` and then `ReprovisionAsync` each time you are changing your schema

Regarding, tracking tables & triggers you can skips them if you are using sql server change tracking
Stored procedures are always needed.

**Comment by KaloyJS** [comment]
So something like this right: https://github.com/Mimetis/Dotmim.Sync/blob/master/Samples/ProvisionDeprovision/Program.cs?

**Comment by Mimetis** [comment]
a good starting point, yes

**Comment by KaloyJS** [comment]
Ok did the example, added progression to see the status and still getting this error on my first sync attempt, so no changes to schema was made: 

Transaction rollback:InternalApplyChangesAsync Rollback. Error:Error on table [Performance_Person_T]: Procedure or function 'Performance_Person_T_Test 3_update' expects parameter '@Performance_Person_ID', which was not supplied.. Row:[Sync state]:ApplyModifiedFailed, [Performance_ID]:10021518, [Person_Position_Organization_ID]:21171, [Timestamp_DT]:2022-12-12 5:47:25 PM, [PerformanceId]:0098ea8e-0000-0000-0000-000000000000, [PersonPositionOrganizationId]:000052b3-0000-0000-0000-000000000000, [Id]:0006160d-0000-0000-0000-000000000000, [TenantId]:00000000-0000-0000-0000-000000000000, [ExtraProperties]:<NULL />, [ConcurrencyStamp]:<NULL />, [CreatorId]:00000000-0000-0000-0000-000000000000, [CreationTime]:2022-12-12 5:47:25 PM, [LastModifierId]:<NULL />, [LastModificationTime]:<NULL />, [EntityVersion]:0. ApplyType:Modified

**Comment by Mimetis** [comment]
can you try with a fresh database, without any DMS things generated
Like a backup of you database before any try with DMS ?
I mean, a good starting point is to see if it's working from scratch

Otherwise, give me a sample that reproduce the error, and  I will look into it

**Comment by KaloyJS** [comment]
Here is the code i am using
`private static async Task SynchronizeAsyncProgress()
{
    // Database script used for this sample : https://github.com/Mimetis/Dotmim.Sync/blob/master/CreateAdventureWorks.sql 

    // Create 2 Sql Sync providers
    // First provider is using the Sql change tracking feature. Don't forget to enable it on your database until running this code !
    // For instance, use this SQL statement on your server database : ALTER DATABASE AdventureWorks  SET CHANGE_TRACKING = ON  (CHANGE_RETENTION = 10 DAYS, AUTO_CLEANUP = ON)  
    // Otherwise, if you don't want to use Change Tracking feature, just change 'SqlSyncChangeTrackingProvider' to 'SqlSyncProvider'
    var serverProvider = new SqlSyncChangeTrackingProvider(serverConnectionString);
    //var clientProvider = new SqlSyncProvider(clientConnectionString);
    var clientProvider = new SqlSyncChangeTrackingProvider(clientConnectionString);

    // Tables involved in the sync process:
    var setup = new SyncSetup("Performance_Person_T");

    //var setup = new SyncSetup(
    //     "Performance_T"
    //     , "Score_T"
    //     , "Performance_Person_T"
    //     , "Person_T"
    //     , "Position_T"
    //     , "Organization_T"
    //    );

    //setup.Tables["Performance_T"].SyncDirection = SyncDirection.DownloadOnly;
    //setup.Tables["Score_T"].SyncDirection = SyncDirection.DownloadOnly;
    //setup.Tables["Performance_Person_T"].SyncDirection = SyncDirection.DownloadOnly;
    //setup.Tables["Person_T"].SyncDirection = SyncDirection.DownloadOnly;
    //setup.Tables["Position_T"].SyncDirection = SyncDirection.DownloadOnly;
    //setup.Tables["Organization_T"].SyncDirection = SyncDirection.DownloadOnly;

    // Creating an agent that will handle all the process
    var agent = new SyncAgent(clientProvider, serverProvider);

    agent.Options.BatchSize = 2000;

    // Using the IProgress<T> pattern to handle progession dring the synchronization
    // Be careful, Progress<T> is not synchronous. Use SynchronousProgress<T> instead !
    var progress = new SynchronousProgress<ProgressArgs>(args => Console.WriteLine($"{args.ProgressPercentage:p}:\t{args.Message}"));

    // --------------------------------------------
    // Using Interceptors
    // --------------------------------------------

    // CancellationTokenSource is used to cancel a sync process in the next example
    var cts = new CancellationTokenSource();


    // Intercept a table changes selecting
    // Because the changes are not yet selected, we can easily interrupt the process with the cancellation token
    agent.LocalOrchestrator.OnTableChangesSelecting(args =>
    {
        Console.WriteLine($"-------- Getting changes from table {args.SchemaTable.GetFullName()} ...");

        if (args.SchemaTable.TableName == "Table_That_Should_Not_Be_Sync")
            cts.Cancel();
    });

    // Row has been selected from datasource.
    // You can change the synrow before the row is serialized on the disk.
    agent.LocalOrchestrator.OnRowsChangesSelected(args =>
    {
        Console.Write(".");
    });

    // Tables changes have been selected
    // we can have all the batch part infos generated
    agent.RemoteOrchestrator.OnTableChangesSelected(tcsa =>
    {
        Console.WriteLine($"Table {tcsa.SchemaTable.GetFullName()}: " +
            $"Files generated count:{tcsa.BatchPartInfos.Count()}. " +
            $"Rows Count:{tcsa.TableChangesSelected.TotalChanges}");
    });


    // This event is raised when a table is applying some rows, available on the disk
    agent.LocalOrchestrator.OnTableChangesApplying(args =>
    {
        Console.WriteLine($"Table {args.SchemaTable.GetFullName()}: " +
            $"Applying changes from {args.BatchPartInfos.Count()} files. " +
            $"{args.BatchPartInfos.Sum(bpi => bpi.RowsCount)} rows.");
    });

    // This event is raised for each batch rows (maybe 1 or more in each batch)
    // that will be applied on the datasource
    // You can change something to the rows before they are applied here
    agent.LocalOrchestrator.OnRowsChangesApplying(args =>
    {
        foreach (var syncRow in args.SyncRows)
            Console.Write(".");
    });

    // This event is raised once all rows for a table have been applied
    agent.LocalOrchestrator.OnTableChangesApplied(args =>
    {
        Console.WriteLine();
        Console.WriteLine($"Table applied: ");
    });

    do
    {
        // Launch the sync process
        var s1 = await agent.SynchronizeAsync("Test 5", setup, SyncType.Normal, null, cts.Token, progress);
        // Write results
        Console.WriteLine(s1);

    } while (Console.ReadKey().Key != ConsoleKey.Escape);

    Console.WriteLine("End");
}`

and the error i am getting at the end of the sync

> Transaction rollback:InternalApplyChangesAsync Rollback. Error:Error on table [Performance_Person_T]: Procedure or function 'Performance_Person_T_Test 5_update' expects parameter '@Performance_Person_ID', which was not supplied.. Row:[Sync state]:ApplyModifiedFailed, [Performance_ID]:22606, [Person_Position_Organization_ID]:13918, [Timestamp_DT]:2010-03-15 6:18:25 PM, [PerformanceId]:0000584e-0000-0000-0000-000000000000, [PersonPositionOrganizationId]:0000365e-0000-0000-0000-000000000000, [Id]:00010000-0000-0000-0000-000000000000, [TenantId]:00000000-0000-0000-0000-000000000000, [ExtraProperties]:<NULL />, [ConcurrencyStamp]:<NULL />, [CreatorId]:00000000-0000-0000-0000-000000000000, [CreationTime]:2010-03-15 6:18:25 PM, [LastModifierId]:<NULL />, [LastModificationTime]:<NULL />, [EntityVersion]:0. ApplyType:Modified

Let me know if you need anything else

**Comment by Mimetis** [comment]
I need the schema to be able to reproduce your error, for tables  
"Performance_T"
, "Score_T"
, "Performance_Person_T"
, "Person_T"
, "Position_T"
, "Organization_T"

Otherwise I can't help you

**Comment by KaloyJS** [comment]
Is structure ok?

**Comment by Mimetis** [comment]
I tried your code and your setup, and everything is working for me :

```
0,00 %: Session Begins. Id:da227ba6-7bbc-44a3-b30f-c5baa835795d. Scope name:Test 5.
0,00 %: Session Begins. Id:da227ba6-7bbc-44a3-b30f-c5baa835795d. Scope name:Test 5.
0,00 %: Schema Loaded For 6 Tables.
0,00 %: Provisioned Organization_T. Provision:TrackingTable, StoredProcedures, Triggers.
0,00 %: Provisioned Performance_T. Provision:TrackingTable, StoredProcedures, Triggers.
0,00 %: Provisioned Score_T. Provision:TrackingTable, StoredProcedures, Triggers.
0,00 %: Provisioned Performance_Person_T. Provision:TrackingTable, StoredProcedures, Triggers.
0,00 %: Provisioned Person_T. Provision:TrackingTable, StoredProcedures, Triggers.
0,00 %: Provisioned Position_T. Provision:TrackingTable, StoredProcedures, Triggers.
0,00 %: Provisioned 6 Tables. Provision:TrackingTable, StoredProcedures, Triggers.
0,00 %: Provisioned Organization_T. Provision:Table, TrackingTable, StoredProcedures, Triggers.
0,00 %: Provisioned Performance_T. Provision:Table, TrackingTable, StoredProcedures, Triggers.
0,00 %: Provisioned Score_T. Provision:Table, TrackingTable, StoredProcedures, Triggers.
0,00 %: Provisioned Performance_Person_T. Provision:Table, TrackingTable, StoredProcedures, Triggers.
0,00 %: Provisioned Person_T. Provision:Table, TrackingTable, StoredProcedures, Triggers.
0,00 %: Provisioned Position_T. Provision:Table, TrackingTable, StoredProcedures, Triggers.
0,00 %: Provisioned 6 Tables. Provision:Table, TrackingTable, StoredProcedures, Triggers.
Table Organization_T: Files generated count:0. Rows Count:0
Table Performance_T: Files generated count:0. Rows Count:0
Table Score_T: Files generated count:0. Rows Count:0
Table Performance_Person_T: Files generated count:0. Rows Count:0
Table Person_T: Files generated count:0. Rows Count:0
Table Position_T: Files generated count:0. Rows Count:0
100,00 %:       Session Ends. Id:da227ba6-7bbc-44a3-b30f-c5baa835795d. Scope name:Test 5.
100,00 %:       Session Ends. Id:da227ba6-7bbc-44a3-b30f-c5baa835795d. Scope name:Test 5.
Synchronization done.
        Total changes  uploaded: 0
        Total changes  downloaded: 0
        Total changes  applied on client: 0
        Total changes  applied on server: 0
        Total changes  failed to apply on client: 0
        Total changes  failed to apply on server: 0
        Total resolved conflicts: 0
        Total duration :00.00:01.309 
```

**Comment by KaloyJS** [comment]
Thank you for checking, can you try this one with data, thanks in advance

https://drive.google.com/file/d/1NMiTOPtWGuTFMWITODSgoGZf-PPOjZLW/view?usp=sharing

**Comment by KaloyJS** [comment]
Can you try this one with dummy data, this one generates errors for me

https://drive.google.com/file/d/1NMiTOPtWGuTFMWITODSgoGZf-PPOjZLW/view?usp=sharing

TIA

**Comment by Mimetis** [comment]
Because your column `Performance_Person_ID` in the table `Performance_Person_T` is an auto increment and not also a primary key.

If you are using an auto increment column in your table, this column should be used a primary key otherwise `DMS` is failing.
Thanks for raising this issue.

In the next version an error will be raised every time DMS is finding an auto increment that is not primary key.

For you, you have two options:

- Remove the auto increment on this column will fix the issue 
- Create a setup and for this particular table, declare all the columns used in the sync, where you are removing the auto inc column

``` cs
var setup = new SyncSetup(
     "Performance_T"
     , "Score_T"
     , "Performance_Person_T"
     , "Person_T"
     , "Position_T"
     , "Organization_T"
    );

setup.Tables["Performance_Person_T"].Columns.AddRange("Performance_ID", "Person_Position_Organization_ID",
    "Timestamp_DT", "Timestamp_TS", "PerformanceId", "PersonPositionOrganizationId",
    "Id", "TenantId", "ExtraProperties", "ConcurrencyStamp", "CreatorId", "CreationTime", 
    "LastModifierId", "LastModificationTime", "EntityVersion");

```

(In both cases, dont forget to `DeprovisionAsync` if you want to retest. Or better use a fresh database without any `DMS` stuff in it, like the script you shared)

**Comment by KaloyJS** [comment]
Thank you again for looking at this!

**Comment by Mimetis** [comment]
nop

**Comment by arjunbharara** [comment]
HI ,
i am getting this error while provisioning 
Dotmim.Sync.SyncException: '[ProvisionAsync].Provision:TrackingTable, StoredProcedures, Triggers, ScopeInfo, ScopeInfoClient.Overwrite:False..[GetConnectionAsync]..The type initializer for 'Microsoft.Data.SqlClient.TdsParser' threw an exception.'

**Comment by arjunbharara** [comment]
Dotmim.Sync.SyncException: '[ProvisionAsync].Provision:TrackingTable, StoredProcedures, Triggers, ScopeInfo, ScopeInfoClient.Overwrite:False..[InternalEnsureScopeInfoAsync].Overwrite:False..[InternalGetSchemaAsync]..[InternalGetTableSchemaAsync].Table:AdminSessionDbo..Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'.'

even though it accept System.Data.SqlClientConnection

**Comment by Mimetis** [comment]
Remove your reference to System.Data.SqlClient

**Comment by arjunbharara** [comment]
after removing the reference it throws this exception
Dotmim.Sync.SyncException: '[ProvisionAsync].Provision:TrackingTable, StoredProcedures, Triggers, ScopeInfo, ScopeInfoClient.Overwrite:False..[GetConnectionAsync]..The type initializer for 'Microsoft.Data.SqlClient.TdsParser' threw an exception.'

**Comment by Mimetis** [comment]
No idea, can you provide a **really simple** sample that reproduce the error
