### ISSUE TITLE
[Question/Bug] Table only with a composite primary key

### ISSUE THREAD

**Issue by marjanoh2** [Mimetis/Dotmim.Sync#115]
I have a table composed of only two columns that are the primary key. I noticed that  method "CreateStoredProcedures(DbConnection connection, DbTransaction transaction = null)" does not  create these procedures ... bulkupdate and ... update. Probably because these procedures do not exist when synchronizing this table, an exception occurs - "Dotmim.Sync.SyncException: 'Invalid index 0 for this SqlParameterCollection with Count = 0.'"

Procedures are not created due to the hasMutableColumns requirement
    if (hasMutableColumns)
                        procBuilder.CreateBulkUpdate();

How can this case be solved?

![table](https://user-images.githubusercontent.com/37705345/47100814-a7cc8480-d238-11e8-819a-d6016186cbe6.jpg)

![procedures](https://user-images.githubusercontent.com/37705345/47101540-aa2fde00-d23a-11e8-986b-1ba033bfeca5.jpg)

**Comment by Mimetis** [comment]
Hi @marjanoh2 

When a table has only primary keys, we can't make update, it's a non sense :)   
That's why we don't generate any *_update* stored procedures.

BTW, I've tested your solution with the latest bit (beta 0.3.x available on pre release on nuget)  and it seems it's working correctly.

Here is my setup:

``` sql
CREATE TABLE [dbo].[r_kasi](
	[r_kasi_id] [int] IDENTITY(1,1) NOT NULL,
	[r_kasi_title] [nvarchar](50) NULL,
 CONSTRAINT [PK_r_kasi] PRIMARY KEY CLUSTERED ([r_kasi_id] ASC)) 
GO
CREATE TABLE [dbo].[r_kasi_payment_types](
	[r_kasi_id] [int] NOT NULL,
	[r_kasi_payment_value] [int] NOT NULL,
 CONSTRAINT [PK_r_kasi_payment] PRIMARY KEY CLUSTERED 
(
	[r_kasi_id] ASC,
	[r_kasi_payment_value] ASC
))
GO
CREATE TABLE [dbo].[r_payment_types](
	[r_payment_type_value] [int] IDENTITY(1,1) NOT NULL,
	[r_payment_type_title] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_r_payment] PRIMARY KEY CLUSTERED 
(
	[r_payment_type_value] ASC
))
GO
SET IDENTITY_INSERT [dbo].[r_kasi] ON 
INSERT [dbo].[r_kasi] ([r_kasi_id], [r_kasi_title]) VALUES (1, N'kasi 1 paid by cash')
INSERT [dbo].[r_kasi] ([r_kasi_id], [r_kasi_title]) VALUES (2, N'kasi 2 paid par card')
INSERT [dbo].[r_kasi] ([r_kasi_id], [r_kasi_title]) VALUES (3, N'kasi 3 paid par card')
SET IDENTITY_INSERT [dbo].[r_kasi] OFF
GO
SET IDENTITY_INSERT [dbo].[r_payment_types] ON 
INSERT [dbo].[r_payment_types] ([r_payment_type_value], [r_payment_type_title]) VALUES (1, N'credit card')
INSERT [dbo].[r_payment_types] ([r_payment_type_value], [r_payment_type_title]) VALUES (2, N'cash')
SET IDENTITY_INSERT [dbo].[r_payment_types] OFF
GO
SET IDENTITY_INSERT [dbo].[r_kasi_payment_types] ON 
INSERT [dbo].[r_kasi_payment_types] ([r_kasi_id], [r_kasi_payment_value]) VALUES (1, 2)
INSERT [dbo].[r_kasi_payment_types] ([r_kasi_id], [r_kasi_payment_value]) VALUES (2, 1)
INSERT [dbo].[r_kasi_payment_types] ([r_kasi_id], [r_kasi_payment_value]) VALUES (3, 1)
SET IDENTITY_INSERT [dbo].[r_kasi_payment_types] OFF
Go
ALTER TABLE [dbo].[r_kasi_payment_types]  WITH CHECK ADD  CONSTRAINT [FK_r_kasi_payment_r_kasi_payment] FOREIGN KEY([r_kasi_id])
REFERENCES [dbo].[r_kasi] ([r_kasi_id])
GO
ALTER TABLE [dbo].[r_kasi_payment_types]  WITH CHECK ADD  CONSTRAINT [FK_r_kasi_payment_r_payment] FOREIGN KEY([r_kasi_payment_value])
REFERENCES [dbo].[r_payment_types] ([r_payment_type_value])
```

And my code to synchronize those tables:
``` csharp
    private static async Task TestKasiSample()
    {
        var serverProvider = new SqlSyncProvider(GetDatabaseConnectionString("kasi"));
        var builder = new SqliteConnectionStringBuilder { DataSource = Path.Combine(Directory.GetCurrentDirectory(), "kasi.db") };
        var clientProvider = new SqliteSyncProvider(builder);

        var tables = new string[] {"r_kasi", "r_payment_types", "r_kasi_payment_types" };

        var agent = new SyncAgent(clientProvider, serverProvider, tables);

        do
        {
            Console.Clear();
            Console.WriteLine("Sync Start");
            try
            {
                var s1 = await agent.SynchronizeAsync();
                Console.WriteLine(s1);
            }
            catch (SyncException e)
            {
                Console.WriteLine(e.ToString());
            }
            catch (Exception e)
            {
                Console.WriteLine("UNKNOW EXCEPTION : " + e.Message);
            }


            //Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");
        } while (Console.ReadKey().Key != ConsoleKey.Escape);

        Console.WriteLine("End");
    }

```

Can you confirm ?  
 I close the issue, but feel free to re open it if you still have the issue.

**Comment by marjanoh2** [comment]
It is true that the composite primary key does not have the logic to be updated, but it can be deleted and after a while it is re-inserted into the table the same combination of external keys from which the composite primary key is composed. In that case, if it is added, it will not be synchronized. I noticed that in the latest version.
Try the example above to delete the first row of the table r_kasi_payment_type (1,2), wait until it is synchronized and then re-enter the same row (1,2).

**Comment by marjanoh2** [comment]
@Mimetis did you checked this situation?

**Comment by Mimetis** [comment]
Nop.

Right now, I just don't know how to handle this situation for now. 
I think I need to add a new condition in the `_Insert` proc stock, but I think it could cause a lot of edges effects.

**Comment by Mimetis** [comment]
By the way, I think it's not the `_inserted` proc stock that sould be modified, but the triggers `_insert_trigger` instead.

I just checked the last version trigger generation and it seems good even for this situation:

Indeed, I try to make an update on the row if it were previously deleted.
Did you try the last version from the source code ?

``` sql
ALTER TRIGGER [dbo].[PostTag_insert_trigger] ON [dbo].[PostTag] FOR INSERT AS

-- If row was deleted before, it already exists, so just make an update
UPDATE [side] 
SET 	[sync_row_is_tombstone] = 0
	,[update_scope_id] = NULL -- since the update if from local, it's a NULL
	,[last_change_datetime] = GetUtcDate()
FROM [PostTag_tracking] [side]
JOIN INSERTED AS [i] ON [side].[PostId] = [i].[PostId] AND [side].[TagId] = [i].[TagId]

INSERT INTO [PostTag_tracking] (
	[i].[PostId]
	,[i].[TagId]
	,[create_scope_id]
	,[create_timestamp]
	,[update_scope_id]
	,[update_timestamp]
	,[sync_row_is_tombstone]
	,[last_change_datetime]
) 
SELECT
	[i].[PostId]
	,[i].[TagId]
	,NULL
	,@@DBTS+1
	,NULL
	,0
	,0
	,GetUtcDate()

FROM INSERTED [i]
LEFT JOIN [PostTag_tracking] [side] ON [i].[PostId] = [side].[PostId] AND [i].[TagId] = [side].[TagId]
WHERE [side].[PostId] IS NULL AND [side].[TagId] IS NULL

```

**Comment by marjanoh2** [comment]
The trigger looks good, but it is not synchronized again. I'll upload a video of my testing shortly.

**Comment by marjanoh2** [comment]
Hi @Mimetis , is there anything new related to this case?
In the meantime, I have temporarily solved the problem by adding another column to the table that I do not use, but only to have the synchronization work. But I discovered another problem and I will try to explain it to you, and if necessary, I'll  record video from screen..
Three-column table (area_id, source_id, order_no), primary keys -area_id, source_id and these steps:
1. On the client(or server) side I add one row, e.g.( 2,3,1)
2. I am waiting for the other side to synchronize.
3. On the client(or server) side I delete that row (2,3,1)
4. I am waiting for the other side to synchronize.
5. Re-add the same values ​​(2.3.1) to the client(or server) side.
6. I am waiting for  the other side to synchronize, but that row is not added there.

**Comment by Mimetis** [comment]
This bug has been resolved in the last version.
Let me know if it's ok for you
