### ISSUE TITLE
 Issue with Redundant Data Transfer in Dotmim.Sync

### ISSUE THREAD

**Issue by ivanpetrus** [Mimetis/Dotmim.Sync#1159]
Hello,

I’m encountering an issue with the synchronization process using Dotmim.Sync. Here’s the scenario:

I perform the initial sync, and my local database receives all the necessary data.
I make some changes to a table.
During the second sync, the modified data is transferred to the local database again.
Subsequent syncs continue to transfer the same modified data, even though it already exists locally.
This behavior is not expected, as the framework should handle incremental sync efficiently. Could you please investigate and provide guidance on resolving this issue?

Thank you for your assistance.

Best regards, Ivan.

**Comment by Mimetis** [comment]
Are you using `Auto Increment Identity` columns ?

**Comment by ivanpetrus** [comment]
I use Guids

**Comment by ivanpetrus** [comment]
This is actually old database, with data

**Comment by ivanpetrus** [comment]
Seems i know why it did not work for me, 
I used SqlSyncChangeTrackingProvider, when I changed it to  SqlSyncProvider, it just start working as expected
