### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by symbiogenesis** [Mimetis/Dotmim.Sync#1162]
Lots of tests have identical setup and could make use of [shared context](https://xunit.net/docs/shared-context) in order to speed things up.

Relatedly, we could look at improving parallelism, such as making more separation between classes when there are different test setups. Tests within classes run sequentially, but the different classes are run in parallel.

There are other possibilities, but this seems to be the safest and lowest hanging fruit.

**Comment by Mimetis** [comment]
I have already used shared context, but it's not working.
You can't use the same db for each test, coz you never know the state of the database, the records it contains, and even the change in the schema

If you have any idea, do not hesitate to share them here
