### ISSUE TITLE
Support SQLite server-side

### ISSUE THREAD

**Issue by symbiogenesis** [Mimetis/Dotmim.Sync#1169]
SQLite is becoming more and more capable, such as with WAL2 mode. New releases support lots of great features, and more people are finding it useful on the server-side.

You could run small servers on something like a Raspberry Pi and get decent performance.

There was some community interest in this already in this discussion thread: https://github.com/Mimetis/Dotmim.Sync/discussions/619

I think we should implement it.

**Comment by Mimetis** [comment]
Sqlite is not meant to be a server side database, in my opinion :)

**Comment by Mimetis** [comment]
**To be clear**, I don't say we won't make it ! I just say "_I'm not sure if it's worth it_" :)
