### ISSUE TITLE
[Critical] - Another situation in the moment of synchronization.

### ISSUE THREAD

**Issue by marjanoh2** [Mimetis/Dotmim.Sync#117]
I started to use it in production with 60 tables. I noticed that sometimes some new rows are not synchronized. The synchronization takes about 15 seconds. I tested through the sourcing code and noticed something in the EnumerateChangesInternal method. 
This method checks all tables for eventual changes. The problem occurs in this case - while checking the tables takes place if a new row is added to an already checked table, then that new row will not be synchronized. This is something like a "race condition" problem. For example, the table is checked and there are no changes at that moment, but if you add a new row in the next 5-6 seconds while checking the other tables, then that change(new row) will be "forgotten" every subsequent synchronization.

**Comment by Mimetis** [comment]
Hello @marjanoh2 

> I started to use it in production with 60 tables

Wow, you know, it's not even a beta version !! A lot of changes can change on the next version !!

> but if you add a new row in the next 5-6 seconds while checking the other tables, then that change(new row) will be "forgotten" every subsequent synchronization

I did already notice this behavior, and I fixed it, in the current version (0.2.x) 
To help me debuging this, do you have a small reproduction sample ?
I know it's a little bit complicated, but it could help me a lot.

Thx

**Comment by marjanoh2** [comment]
I tested in laboratory conditions as much as I could and decided to take a little risk in production. This problem is rare. For example, when synchronizing one table from the added 4000 new rows, about 20 are not synchronized. I looked at the code a bit, and that part (EnumerateChangesInternal) seemed suspicious to me.

Here's how I reproduced the problem:

https://drive.google.com/open?id=16LyUdw-epJ0fObvrnevjhKKy3N7LnT4f

1. Synchronize two tables (r_phone_additional, app_settings)
2. I debug the EnumerateChangesInternal method and when the r_phone_addition check is passed, I add a new row to that table while it's "last" (in this case, deliberately paused code when debugging, and in reality, there will be several seconds of real-time reality in multiple tables). So that new line will never be synchronized.

**Comment by marjanoh2** [comment]
Do you try this reproduction simple? 
Also, the method ApplyChangesInternal  may have the same problem. 
In fact, all the tables are checked in both methods. The last timestamp is taken initially, checked one by one (EnumerateChangesInternal) or updated (ApplyChangesInternal), but it can take more time, in my case 15 seconds for 60 tables. For example. if the first table is checked and updated in the first second then the changes in that table in the next 14 seconds will be "forgotten" because the timestamp is updated at the end.

**Comment by Mimetis** [comment]
Sorry @marjanoh2 for late answer
Was busy with [Microsoft Experiences](https://experiences18.microsoft.fr/) events those days :)

I should have some times now, so I will be able to investigate it pretty soon.

thx
seb

**Comment by marjanoh2** [comment]
@Mimetis , did you investigate this case? Can I help you somehow differently?

**Comment by Mimetis** [comment]
Hey @marjanoh2 I made a fix for this one, and the test based on it.
Can you please get the latest source code (not the published nuget package, the source code from the repository) and try it on your scenario ?
Keep me informed :)

**Comment by marjanoh2** [comment]
I am testing the new version on two different databases with a high frequency of change. So the next few days I'll tell you if it's ok.

**Comment by Mimetis** [comment]
Thanks a lot !
Your works helps a lot !

**Comment by Mimetis** [comment]
Thx for your time and all the tests you made.
It helps a lot
