### ISSUE TITLE
Field not synced - help

### ISSUE THREAD

**Issue by pazunino** [Mimetis/Dotmim.Sync#1172]
Hi,
first of all, thanks for the great job.
Now I'm using ver 0.9.6, all tables are synced and in the configured direction.
But there is a float field that is no synced, in this case the table is configured to upload only.
I tried to reset server and clients but this fields keeps in 0.
I upgrade to 0.9.8 and in this particular table throws the following error:

Dotmim.Sync.Web.Client.HttpSyncWebException: [InternalApplyThenGetChangesAsync]..[InternalApplyThenGetChangesAsync]..Error on table [Cosecha]: Procedure or function Cosecha_update has too many arguments specified.. Row:[Sync state]:ApplyModifiedFailed, [ProduccionId]:4, [TarjetaCosecha]:1, [FechaHoraLectura]:2024-04-14 23:15:18, [ProductividadId]:1, [JornadaId]:2, [CuadrillaId]:2, [CorteId]:1, [ModalidadId]:2, [VariedadId]:2, [QuintaId]:1, [CuadroId]:2, [PagoId]:1, [UnidadPagoId]:1, [Cantidad]:1, [BolsosBin]:0, [BolsosCosechero]:1, [EsSupera]:0, [EmpleadoId]:<NULL />, [EspeciePagoId]:1, [AcumuladoFraccionJornal]:0.0316203348338604. ApplyType:Modified

I downgrade to 0.9.6 and again the field (AcumuladoFraccionJornal) is not synced.
I'm using Azure SQL Server and Sqlite with MAUI Android.
Perhaps I'm not doing correctly the "reset" of the scopes.
That field was the last added, but I started the first sync in 0.9.6 after that migration.
Sorry for my English.
Regards.

**Comment by symbiogenesis** [comment]
If you make a sample project you could get more help.
