### ISSUE TITLE
Timeout Issue and Foreign Keys and Unique Constraint bypass

### ISSUE THREAD

**Issue by KaloyJS** [Mimetis/Dotmim.Sync#1174]
Hey there,

You guys have a great library and I using it to sync my db cloud to local and local to cloud after an operation. Doing some testing and I am getting timeout issues 

Here is the error I am getting
[InternalApplyThenGetChangesAsync]..[InternalApplyThenGetChangesAsync]..[InternalGetChangesAsync].Directory:C:\Users\carlo\AppData\Local\Temp\DotmimSync.Supports MultiActiveResultSets:False.Is New:True.Interval:/16..[InternalReadSyncTableChangesAsync].SelectChangesCommand:[dbo].[Score_T_wewrwrfsdfg_initialize].Table:Score_T.Is New:True.LastTimestamp:..Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
End

Sample repo: https://github.com/KaloyJS/Sync/tree/master/Sync

Sample schema: https://drive.google.com/file/d/1NMiTOPtWGuTFMWITODSgoGZf-PPOjZLW/view?usp=sharing

Also is there a way to ignore table relationships like foreign keys and unique key constraints
 [Performance_T] Changes Modified Applied:88825. Resolved Conflicts:0.
Transaction rollback:InternalApplyChangesAsync Rollback. Error:Error on table [Performance_T]: The MERGE statement conflicted with the FOREIGN KEY constraint "FK_Performance_T_Competition_T". The conflict occurred in database "DigitalJudge_20231204_1032EST", table "dbo.Competition_T", column 'Competition_ID'.
The statement has been terminated.. Row:[Sync state]:ApplyModifiedFailed, [Performance_ID]:10026401, [Performance_Revision_IN]:1, [Web_Performance_ID]:0, [Competition_ID]:174, [Competition_Date_ID]:0, [Organization_ID]:595, [Performance_Type_ID]:4, [Performance_Size_ID]:4, [Performance_Expertise_ID]:3, [Performance_Awardable_Type_ID]:1, [Age_Group_ID]:3, [Name_NV]:Test 001, [ST_Performance_Number_IN]:0, [Age_Average_IN]:18, [Schedule_Type_ID]:0, [Time_Start_DT]:1/1/1900 12:00:00 AM, [Duration_DT]:1/1/1900 12:03:30 AM, [Time_End_DT]:1/1/1900 12:00:00 AM, [Audio_Last_Save_Time_DT]:1/1/1900 12:00:00 AM, [Audio_Last_Save_Path_NV]:, [Preparation_DT]:1/1/1900 12:00:00 AM, [Fee_Registration_ID]:78, [Amount_Fees_Pretax_MN]:296.46, [Amount_Tax_MN]:38.5398, [Amount_Fees_Posttax_MN]:334.9998, [Competition_Performance_Position_IN]:0, [Scheduling_Notes_NV]:, [Has_Scheduling_Notes_BT]:False, [Is_Break_BT]:False, [Conflict_Margin_IN]:0, [Conflict_Check_Exclude_Breaks_BT]:False, [Excluded_Report_Performance_Category_Last_Performance_BT]:False, [Excluded_Report_High_Score_Last_Performance_BT]:False, [Excluded_Report_Overalls_BT]:False, [Costume_Award_Finalist_BT]:False, [Inappropriate_Performance_Pending_Review_BT]:False, [Title_Competition_Eligible_BT]:False, [Timestamp_DT]:10/31/2023 3:26:12 AM, [Id]:10e27670-4d21-5f04-d210-3a0e95f14c41, [CompetitionId]:edad3432-d2f1-404f-bed0-731ab0e52ca9, [CompetitionDateId]:00000000-0000-0000-0000-000000000000, [OrganizationId]:00000253-0000-0000-0000-000000000000, [PerformanceTypeId]:00000004-0000-0000-0000-000000000000, [PerformanceSizeId]:00000004-0000-0000-0000-000000000000, [PerformanceExpertiseId]:00000003-0000-0000-0000-000000000000, [PerformanceAwardableTypeId]:00000001-0000-0000-0000-000000000000, [AgeGroupId]:00000003-0000-0000-0000-000000000000, [ScheduleTypeId]:00000000-0000-0000-0000-000000000000, [FeeRegistrationId]:d9028aa0-1dd2-45fc-9ae4-15de6f3ee7c4, [TenantId]:<NULL />, [ExtraProperties]:<NULL />, [ConcurrencyStamp]:<NULL />, [CreatorId]:955af502-0972-4899-8259-2b22309e1c8d, [CreationTime]:10/31/2023 3:26:12 AM, [LastModifierId]:955af502-0972-4899-8259-2b22309e1c8d, [LastModificationTime]:2/21/2024 8:28:07 PM, [EntityVersion]:<NULL />, [MusicFilename]:The Unforgettable Fire.wav. ApplyType:Modified

 [Score_T] Changes Modified Applied:197060. Resolved Conflicts:0.
Transaction rollback:InternalApplyChangesAsync Rollback. Error:Error on table [Score_T]: Violation of UNIQUE KEY constraint 'IX_Score_T'. Cannot insert duplicate key in object 'dbo.Score_T'. The duplicate key value is (10019355, 48599).
The statement has been terminated.. Row:[Sync state]:ApplyModifiedFailed, [Score_ID]:259359, [Performance_ID]:10019355, [Person_Position_Organization_ID]:48599, [Criteria_Performance_DC]:35.46, [Criteria_Choreography_DC]:8.87, [Criteria_Costume_DC]:8.87, [Criteria_Technique_DC]:35.46, [Costume_Award_Candidate_BT]:False, [Inappropriate_Performance_BT]:False, [Exclude_from_Video_Timing_BT]:False, [Timestamp_DT]:2023-04-20 9:03:45 AM, [Id]:0003f51f-0000-0000-0000-000000000000, [PerformanceId]:0098e21b-0000-0000-0000-000000000000, [PersonPositionOrganizationId]:0000bdd7-0000-0000-0000-000000000000, [TenantId]:00000000-0000-0000-0000-000000000000, [ExtraProperties]:<NULL />, [ConcurrencyStamp]:<NULL />, [CreatorId]:00000000-0000-0000-0000-000000000000, [CreationTime]:2023-04-20 9:03:45 AM, [LastModifierId]:<NULL />, [LastModificationTime]:<NULL />, [EntityVersion]:0. ApplyType:Modified

**Comment by Mimetis** [comment]
Didn't test, but it seems your server is taking too much time to get the changes to sync on your client
Is it happening during the first (initialization) sync ?

**Comment by KaloyJS** [comment]
The issue seems intermittent. It went through initially then all day yesterday it was timing out, and it went through once today. My additional question is, is there anyway to bypass foreign keys constraint and unique key constarint?

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Mimetis** [comment]
Are you using `DisableConstraintsOnApplyChanges` option ?

**Comment by KaloyJS** [comment]
No, can you point out an example where I can see how to use that option?

**Comment by Mimetis** [comment]
var options = new SyncOptions();
options.DisableConstraintOnChanges = true;

**Comment by KaloyJS** [comment]
Thanks, advice on how to avoid the timeout issue?

**Comment by Mimetis** [comment]
https://dotmimsync.readthedocs.io/Timeout.html

**Comment by KaloyJS** [comment]
thank you!
