### ISSUE TITLE
Database Sync Error with SQL Server

### ISSUE THREAD

**Issue by nicolazreinh** [Mimetis/Dotmim.Sync#1177]
I am encountering an error while attempting to synchronize two databases using a web server. The databases in question are both SQL Server databases. The specific error message I received is as follows:
Transaction rollback:InternalApplyThenGetChangesAsync during apply changes Rollback. 
Error: Error on table [dbo.tbl_employee_wage_checks]: The MERGE statement conflicted with the FOREIGN KEY constraint "FK_tbl_employee_wage_checks_tbl_cheque_prints". The conflict occurred in database "testsyncdb", table "dbo.tbl_cheque_prints", column 'pk_cheque_print_id'.
The statement has been terminated.. 
Row:[Sync state]:ApplyModifiedFailed, [pk_employee_wage_check_id]:1, [fk_employee_wage_id]:53866, [fk_cheque_print_id]:12096. 
ApplyType:Modified

How to fix this issue, it seems like the data is being transferred before their relevant foreign keys.

**Comment by Mimetis** [comment]
try to disable foreign constraints, using `options.DisableConstraintsOnApplyChanges` to see if it's resolving your issue

**Comment by nicolazreinh** [comment]
Works, thank you
