### ISSUE TITLE
[Bug] Cannot sync updated FK that refers to new row on client db

### ISSUE THREAD

**Issue by gb0o** [Mimetis/Dotmim.Sync#118]
Steps to reproduce
- Deploy AdventureWorks db to SQL Server
- Sync to Sqlite db on client
- Create a new Product row in AdventureWorks SQL Server db
- Sync new Product to client db
- Create a new ProductCategory on client db
- Set the ProductCategoryID FK on the new Product to be the new ProductCategory on client db
- Sync back to the server
- Inspect the new Product row and observe ProductCategoryID FK is NULL on the server db. It should have been updated.

I traced the problem to the order of Update and Insert. Each of these actions occurs in table order as expected. However a FK constraint exception occurred on the server side when a FK update was executed on the Product row before the insert of the new ProductCategory row. The solution would be to execute both Update and Insert for a given table in order and not all Updates in order then all Inserts in order. 

The problem was difficult to find because everything looked correct from the client side. One row was created and one updated. However the FK constraint exception was silently eaten on the server side. A conflict was logged on the server side but this is not actually a conflict. The server side should throw the exception so that the client is notified of the problem.

@Mimetis happy to put up a PR. I have made some changes and created a test on my fork which I think will work.

Regards,
Guy

**Comment by gb0o** [comment]
@Mimetis am I allowed permissions to create a branch?

**Comment by Mimetis** [comment]
Hello
Sorry for late response, I'm very busy these days...
Of course, you can create a branch and push a PR !

Thx

Sebastien

**Comment by gb0o** [comment]
@Mimetis here is my PR to fix this issue: https://github.com/Mimetis/Dotmim.Sync/pull/121

**Comment by gb0o** [comment]
@Mimetis confirmed this issue has been fixed. When running locally temporary files at C:\Users\<user>\AppData\Local\Temp\DotmimSync are cleared after the server and client are finished exchanging data.
