### ISSUE TITLE
Clean metadata

### ISSUE THREAD

**Issue by marjanoh2** [Mimetis/Dotmim.Sync#1183]
![Screenshot 2024-05-30 230411sync](https://github.com/Mimetis/Dotmim.Sync/assets/37705345/62595814-1f81-4adc-b8b8-9665b21f2dda)

Why code for creating stored procedures for deleting metadata is commented. When I checked this option, I noticed that it does not delete the metadata. Could the reason be that these procedures are not created?

**Comment by Mimetis** [comment]
indeed, these procedures are not created anymore

**Comment by maxrodro** [comment]
Hi @Mimetis 

I was passing by and read this comment, in which version are the stored procedures that perform part of the magic of Dotmim no longer generated? :-)

**Comment by Mimetis** [comment]
I just talk about the metadata clean up procedures, not the others ones :)

**Comment by marjanoh2** [comment]
Why aren't these procedures being created? Am I missing something? I notice that the metadata isn't being deleted.

**Comment by Mimetis** [comment]
Ok, my bad, you are right. We have an issue here, as the `DeleteMetadata` has been removed, but should not have to.

In a nutshell, I've removed the stored procedure to replace it with a single command text, build by code, but I never add this code ....

Huge mistake, I will make a quick update and will deploy a new package as soon as possible.

Thanks for finding this issue !

**Comment by marjanoh2** [comment]
In examples and user implementations, I noticed the following code is used for cleaning up tracking metadata on server side:

```
// get all scope info clients
var sScopeInfoClients = await remoteOrchestrator.GetAllScopeInfoClientsAsync();

// select only clients that have synced at least 30 days earlier
var oneMonthMaxScopeInfoClients = sScopeInfoClients.Where(
    sic => sic.LastSync.HasValue && sic.LastSync.Value >= DateTime.Now.AddDays(-30));

// Get the min timestamp
var minTimestamp = oneMonthMaxScopeInfoClients.Min(h => h.LastSyncTimestamp);

// Call the delete metadatas with this timestamp
await remoteOrchestrator.DeleteMetadatasAsync(minTimestamp.Value);
```


However, this appears to use the client's local timestamp (LastSyncTimestamp), not the one from the server's tracking system.

**Problem**
LastSyncTimestamp refers to the local timestamp generated on the client database.

Server-side tracking tables (e.g. table_tracking) use server-generated timestamps, which are usually much higher in value (e.g., 212212257 vs 1636038).

Therefore, calling DeleteMetadatasAsync(minClientTimestamp) may never delete any tracking rows if those rows have higher timestamps.

**Suggestion**
Shouldn't the correct property be LastServerSyncTimestamp?

` var minTimestamp = oneMonthMaxScopeInfoClients.Min(h => h.LastServerSyncTimestamp);`
This ensures that the cleanup uses a timestamp from the same origin as the tracking entries on the server.

Both client and server can have very different internal timestamp ranges, especially when they’re on separate SQL Server instances. Using LastSyncTimestamp in this context leads to no metadata ever being cleaned up.
