### ISSUE TITLE
NullReferenceException in AgentApplyChangedFailed

### ISSUE THREAD

**Issue by sPhinX-LHJ** [Mimetis/Dotmim.Sync#119]
I want to sync two mysql tables with Dotmim.Sync, but I got NullReferenceException when update tables, below is my log, somebody can help me?

`
<<<<<<<<<<
2018-12-03 11:01:05
AgentSyncProgress
Continue
Selecting changes
TableName:order
TableName: order
MySqlSyncProvider, Dotmim.Sync.MySql.MySqlSyncProvider
TableChangesSelecting
>>>>>>>>>>

<<<<<<<<<<
2018-12-03 11:03:49
AgentTableChangesSelected
Continue
MySqlSyncProvider, Dotmim.Sync.MySql.MySqlSyncProvider
TableChangesSelected
0
176820
order
176820
0
>>>>>>>>>>

<<<<<<<<<<
2018-12-03 11:03:49
AgentSyncProgress
Continue
Changes selected
TableName:order
Deletes:0
Inserts:176820
Updates:0
TotalChanges:176820
TableName: order Deletes: 0 Inserts: 176820 Updates: 0 TotalChanges: 176820

MySqlSyncProvider, Dotmim.Sync.MySql.MySqlSyncProvider
TableChangesSelected
>>>>>>>>>>

<<<<<<<<<<
2018-12-03 11:03:49
AgentTableChangesSelecting
Continue
MySqlSyncProvider, Dotmim.Sync.MySql.MySqlSyncProvider
TableChangesSelecting
orderdetail
>>>>>>>>>>

<<<<<<<<<<
2018-12-03 11:03:49
AgentSyncProgress
Continue
Selecting changes
TableName:orderdetail
TableName: orderdetail
MySqlSyncProvider, Dotmim.Sync.MySql.MySqlSyncProvider
TableChangesSelecting
>>>>>>>>>>

<<<<<<<<<<
2018-12-03 11:04:23
AgentTableChangesSelected
Continue
MySqlSyncProvider, Dotmim.Sync.MySql.MySqlSyncProvider
TableChangesSelected
0
180991
orderdetail
180991
0
>>>>>>>>>>

<<<<<<<<<<
2018-12-03 11:04:23
AgentSyncProgress
Continue
Changes selected
TableName:orderdetail
Deletes:0
Inserts:180991
Updates:0
TotalChanges:180991
TableName: orderdetail Deletes: 0 Inserts: 180991 Updates: 0 TotalChanges:
180991
MySqlSyncProvider, Dotmim.Sync.MySql.MySqlSyncProvider
TableChangesSelected
>>>>>>>>>>

<<<<<<<<<<
2018-12-03 11:35:57
AgentApplyChangedFailed
ServerWins
Sync Exception: 未将对象引用设置到对象的实例。. Type:NullReference. On provider:
 MySqlSyncProvider, Dotmim.Sync.MySql.MySqlSyncProvider.
<<<<<<<<<<
2018-12-03 11:35:57
AgentEndSession
Continue
MySqlSyncProvider, Dotmim.Sync.MySql.MySqlSyncProvider
EndSession
>>>>>>>>>>

<<<<<<<<<<
2018-12-03 11:35:57
AgentSyncProgress
Continue
End session

MySqlSyncProvider, Dotmim.Sync.MySql.MySqlSyncProvider
EndSession
>>>>>>>>>>

<<<<<<<<<<
2018-12-03 11:35:57
AgentSessionStateChanged
Ready
>>>>>>>>>>

未经处理的异常:  Dotmim.Sync.SyncException: 未将对象引用设置到对象的实例。 --->
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 TinySync.Program.AgentApplyChangedFailed(Object sender, ApplyChangeFailedE
ventArgs e)
   在 Dotmim.Sync.CoreProvider.GetConflictAction(SyncConflict conflict, Conflict
ResolutionPolicy policy, DbConnection connection, DbTransaction transaction)
   在 Dotmim.Sync.DbSyncAdapter.HandleConflict(SyncConflict conflict, ConflictRe
solutionPolicy policy, ScopeInfo scope, Int64 fromScopeLocalTimeStamp, DmRow& fi
nalRow)
   在 Dotmim.Sync.CoreProvider.ApplyChangesInternal(SyncContext context, Message
ApplyChanges message, DbConnection connection, DbTransaction transaction, DmRowS
tate applyType, ChangesApplied changesApplied)
   在 Dotmim.Sync.CoreProvider.<ApplyChangesAsync>d__0.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Dotmim.Sync.CoreProvider.<ApplyChangesAsync>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   在 Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__82.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__82.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   在 Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__79.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   在 TinySync.Program.<Main>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   在 TinySync.Program.<Main>(String[] args)
`

**Comment by sPhinX-LHJ** [comment]
actually, I also got MySQLTransction exception when I sync the two tables together first time. after many test, I choose sync table one by one, I can upload the error later.

**Comment by Mimetis** [comment]
Please try with the last beta avaialable on nuget and confirm the issue is resolved.
feel free to reopen if you still have the issue.
