### ISSUE TITLE
Dotmim.Sync Turkish character error

### ISSUE THREAD

**Issue by SinanGunsel** [Mimetis/Dotmim.Sync#12]
I wanted to use Dotmim.Sync on my project, but I got across with an error. When I examine the source code, the **InsertOrUpdateScopeInfo(ScopeInfo scopeInfo)** method in **...ScopeInfoBuilder.cs** has `scopeInfo.Id = (Guid) reader ["sync_scope_Id"]; ` The line I casts an error because the characters I and i are different characters as the big typed Turkish Character.

**Comment by Mimetis** [comment]
I've made the correction.
You can download and rebuild the solution from the github repository, or you can wait a little I publish the version 0.1.2 on nuget.
Thx for the feedback and the issue !

**Comment by Mimetis** [comment]
As disccussed, it seems you don't use the last version of VS 2017 to be able to target .Net Standard 2.0
I close this issue for now, do not hesitate to re open it if the bug persists with .Net Standard 2.0
