### ISSUE TITLE
Unable to Update Scope Info in SQL Server Sync with RemoteOrchestrator

### ISSUE THREAD

**Issue by nicolazreinh** [Mimetis/Dotmim.Sync#1207]
**Description:**
I am experiencing an issue with updating the scope info using the Dotmim.Sync library. I am using [ASP.NET Core Web Proxy](https://dotmimsync.readthedocs.io/Web.html#asp-net-core-web-proxy) with change tracking in SQL Server.

**Steps to Reproduce:**
1. Call:
   ```csharp
   await remoteOrchestrator.DeprovisionAsync(scopeName, SyncProvision.ScopeInfo);
   ```
2. Verify that the scope info is not removed.
3. Attempt to update the scope info using:
   ```csharp
   await remoteOrchestrator.ProvisionAsync(scopeName, setup, overwrite: true);
   ```
4. Verify that the old scope info remains unchanged.

**Expected Behavior:**
Calling `DeprovisionAsync` should remove the scope info, and `ProvisionAsync` with `overwrite` set to `true` should refresh and update the scope info as documented.

**Actual Behavior:**
- The call to `DeprovisionAsync` does not remove the scope info.
- The call to `ProvisionAsync` with `overwrite` set to `true` retains the old scope info instead of refreshing it.

**Additional Context:**
- Dotmim.Sync Version: 1.0.2

Any assistance in resolving this issue would be greatly appreciated. Thank you!

**Comment by Mimetis** [comment]
`DeprovisionAsync(SyncProvision.ScopeInfo)` removes the table itself.
It's literally a `DROP TABLE` query that is excuted behind the scene

Just tried with AdventureWorks; and it's seems it's working fine for me:

``` cs
 var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options);
 await remoteOrchestrator.DeprovisionAsync(SyncProvision.ScopeInfo);
```

![image](https://github.com/Mimetis/Dotmim.Sync/assets/4592555/3ec18f0c-4961-4b17-b37b-cfa7aa83cd92)

And `ProvisionAsync` is all about creating the table, not `INSERT` or `UPDATE` any records in it

IF you want to remove a `ScopeInfo`, you can do it, using the `DeleteScopeInfoAsync` method:

``` cs
var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options);

var scopeInfo = await remoteOrchestrator.GetScopeInfoAsync(scopeName);
await remoteOrchestrator.DeleteScopeInfoAsync(scopeInfo);
```

IF you want to recreate a scope, you don't have to explicitly create it, just call a `ProvisionAsync` that will:
- Create the scope
- Create all the metadatas required (stored procedures; triggers, scope info row etc...)

``` cs
// Create a new setup for a new scope:
var newSetup = new SyncSetup("Customer", "CustomerAddress");

// Provision will create everything needed for this scope and will return the new scope
var newScopeInfo = await remoteOrchestrator.ProvisionAsync("CustomerScope", newSetup);
```

And finally, if you just want to overwrite an existing scope (without deleting it before) you can use the overwrite thing:

``` cs
// Create a new setup for a new scope:
var newSetup = new SyncSetup("Address", "Customer", "CustomerAddress");

// Provision will create everything needed for this scope and will return the new scope
var newScopeInfo = await remoteOrchestrator.ProvisionAsync("CustomerScope", newSetup, overwrite:true);
```

Make sense ?
