### ISSUE TITLE
Potential issue

### ISSUE THREAD

**Issue by symbiogenesis** [Mimetis/Dotmim.Sync#1214]
I was looking at the analyzers around [CA1507](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1507) and [RCS1015](https://josefpihrt.github.io/docs/roslynator/analyzers/RCS1015/) and I noticed the following code:

https://github.com/Mimetis/Dotmim.Sync/blob/63d56ef91e6fb55401b3989f01393a1967c5a7d3/Projects/Dotmim.Sync.Core/Orchestrators/Commands/BaseOrchestrator.Commands.cs#L185-L189

All of the _other_ added command parameters in this function have matching variables to the string literal, and could actually be improved by converting them to use nameof().

Except this one.

On this one the string literal is `"sync_row_timestamp"` but there is no corresponding variable by that name, and the value being passed on line 189 is actually `sync_min_timestamp`

This has a comment about a glitch, so maybe it is intentional. Or, maybe this is why there is a glitch. I'm not sure.

**Comment by Mimetis** [comment]
Yes, this is just an historical mistake I've made in older versions that I still not fixed (coz it's working :) )
Will make a fix sooner or later :D
