### ISSUE TITLE
SSL CONNECTION ERROR- Dotmim sync httpresponse

### ISSUE THREAD

**Issue by Bella1890** [Mimetis/Dotmim.Sync#1218]
Hi, 

I have Implemented the dotmim.sync nuget package to sync the data from clent to server and server to client db

my client site uses a self signed certificate and the data is stored in sqlite db
My server site uses a ssl certificate which is valid and is obtained from Certificate Authority with a proper domain..

When i try to sync the data using dotmim.sync , i get the below error:

Dotmim.Sync.HttpResponseContentException: The SSL connection could not be established, see inner exception.
   at Dotmim.Sync.Web.Client.HttpRequestHandler.ProcessRequestAsync(HttpClient client, SyncContext context, String baseUri, Byte[] data, HttpStep step, ISerializerFactory serializerFactory, IConverter converter, Int32 batchSize, SyncPolicy policy, CancellationToken cancellationToken, IProgress1 progress)

Please help. my both sites are hosted with port 443 (https).

**Comment by Mimetis** [comment]
You can use your own `HttpClient` when using the `WebRemoteOrchestrator`.

I didn't test it, but I think you need to configure the `HttpClient` instance to use your certificate

Making a quick google search, I found :

- https://stackoverflow.com/questions/40014047/add-client-certificate-to-net-core-httpclient
- https://stackoverflow.com/questions/12553277/allowing-untrusted-ssl-certificates-with-httpclient
- https://stackoverflow.com/questions/64586721/ssl-client-authentication-with-certificate-using-c-sharp
- https://www.thecodebuzz.com/configure-certificate-with-httpclient-authentication/
