### ISSUE TITLE
Functions and store procedures are not created in postgres

### ISSUE THREAD

**Issue by edgardonovelovarguez** [Mimetis/Dotmim.Sync#1225]
Good day.
I'm using:
--Postgres 16v.
--Dotmim 1.0.2v
--Api net 6
--Xamarin

I have an application in xamarin, when sending the data to the api and trying to store it in postgres throws the exception there is no function to initialize, update, insert or delete the information.

I did the tests in SQL Serv 2022 and if it creates the Functions and Store procedures, if it stores the information in the database, everything is fine.

My question, what do I need for me to work in postgres?

I appreciate you reading my problem, have a good day

![Multimedia](https://github.com/user-attachments/assets/8b6158ad-4c33-4c39-9ffb-588e4dd905c4)

**Comment by Mimetis** [comment]
Would it be possible to have the `adv_visit` table schema definition ?
I need a sample database to recreate the problem

In PostgreSQL, the stored procedures are created on the fly, temporarily, and are deleted once the sync is done.
This is different from SQL Server, where stored procedures are persisted.

On Xamarin, I guess you are using SQLite to store the data locally ?

**Comment by edgardonovelovarguez** [comment]
Hi
 my schema adv_vist

CREATE TABLE adv_visit (
visit_uuid CHAR(36)  NOT NULL PRIMARY KEY,  --53d6c2a6-e2e4-11ee-96eb-425032353034
tour_uuid CHAR(36)  NULL,  --fb1a22fa-e22c-11ee-9442-425032353034
tour_position INTEGER  NULL, --1
customer_id CHAR(10)  NULL, --0000000001
cust_uuid CHAR(36)  NULL, 
was_executed BOOLEAN  NULL, 
cancel_motive TEXT  NULL, 
started_at TIMESTAMP  NULL, --2024-03-15 09:54:38
ended_at TIMESTAMP  NULL,  --2024-03-15 09:57:42.
elapsed_time NUMERIC  NULL, --3
gps_available BOOLEAN  NULL, --0
has_coordinates BOOLEAN  NULL, --1
latitude FLOAT  NULL,  --0.0
longitude FLOAT  NULL,  ..0.0
ticket_code TEXT, --USD-04-00000362C
ticket_code_return TEXT,	
public_invoice BOOLEAN,--0 
visit_type CHAR(1), --C
dist_channel CHAR(2) NOT NULL --04 )

I have another scheme

CREATE TABLE advp_session(
username TEXT NOT NULL PRIMARY KEY, --XV2604
token TEXT NOT NULL, --E47978A1C725D83244C22FB811158F2C54C8F43D
expiration_date date NULL, --2023-11-03 00:00:00
uuid TEXT NOT NULL, 7a93c2bc-74c4-11ee-92a8-00113236c5bf

)

and presents the same detail which does not find the functions and stored procedures.

As I mentioned earlier when modifying data in the client in Xamarin and synchronizing, these are stored in SQL Serv but not in Postgres, showing the exception that the functions do not exist


On Xamarin, I guess you are using SQLite to store the data locally ? Yes, that's right

Thanks for reading

**Comment by federicoMoroni-git** [comment]
I was also able to replicate this issue on this configuration: right now I was not able to make the sync work between sqlite and postgres.
`PostgreSQL 16.3 on x86_64 - 
Dotmim 1.0.2v - 
.net v8.0`

sqlite table 
```
CREATE TABLE "trackplot_cog" (
    "gid"	INTEGER PRIMARY KEY AUTOINCREMENT,
    "id"	INTEGER,
    "timestamp"	TEXT,
    "name"	TEXT,
    "lat"	REAL,
    "long"	REAL
);
```
postgres table
```
PostgreSQL table (server):
CREATE TABLE dataengine.trackplot_cog (
    gid serial primary key,
    id integer,
    "timestamp" timestamp,
    name character varying(255),
    lat numeric (38,8),
    long numeric (38,8)
);
```
program 
```
        static async Task Main(string[] args)
        {

            var localConnectionString = "Host=localhost;Port=5432;Database=issue1225;Username=postgres;Password=postgres";
            var serverProvider = new NpgsqlSyncProvider(localConnectionString);

            var clientProvider = new SqliteSyncProvider(@"C:\Users\myuser\Desktop\issue1225.db");

            SyncAgent agent = new SyncAgent(clientProvider, serverProvider);

            var setup = new SyncSetup("trackplot_cog");
            var options = new SyncOptions();

            options.DisableConstraintsOnApplyChanges = true;

            var progress = new SynchronousProgress<ProgressArgs>(s =>
                Console.WriteLine($"{s.ProgressPercentage:p}:  " +
                $"\t[{s?.Source?[..Math.Min(4, s.Source.Length)]}] {s.TypeName}: {s.Message}"));
            do
            {
                try
                {
                    Console.ForegroundColor = ConsoleColor.Green;
                    var s = await agent.SynchronizeAsync("scopename", setup, progress: progress);
                    Console.WriteLine(s);
                }
                catch (SyncException e)
                {
                    Console.ResetColor();
                    Console.WriteLine(e.Message);
                }
                catch (Exception e)
                {
                    Console.ResetColor();
                    Console.WriteLine("UNKNOW EXCEPTION : " + e.Message);
                }

                Console.WriteLine("--------------------");
            }
            while (Console.ReadKey().Key != ConsoleKey.Escape);
        }

```
the exception is raised when you do this on the postgres database. and then try to start the sync.
```
INSERT INTO dataengine.trackplot_cog (id, "timestamp", name, lat, long)
VALUES
    (1, '2024-08-10 12:34:56', 'Sample Name 1', 37.7749295, -122.4194155),
    (2, '2024-08-11 13:45:00', 'Sample Name 2', 34.0522342, -118.2436849),
    (3, '2024-08-12 14:56:10', 'Sample Name 3', 40.7127753, -74.0059728);
```
oddly enough I`ve also noticed that by importing manually the projects reference in my solution (no nuget install) this exception is raised and both sync (to the server or to the client are not working)
`[InternalApplyChangesAsync]..[InternalApplyChangesAsync]..[InternalApplyTableChangesAsync]..SQLite Error 1: 'no such table: pg_proc'.`

I`ve posted my environment [HERE](https://drive.google.com/drive/folders/1EDAW8M9F2_NJRhQSUaKy4AokPbD5m7v6?usp=sharing) for further confrontation (must change the sqlite conn string and deploy a postgres locally)

**Comment by federicoMoroni-git** [comment]
I`ve found the issue by trying a ultra simple table.
```
CREATE TABLE single_text_field (
    field_name TEXT PRIMARY KEY
);

```
with this table on the sqlite and the postgres side it works. 
I think that the problem is that the FUNCTION pg_temp. was called with the wrong parameters due to the discrepancy in datatypes between sqlite and postgres. I think some checks must be done to verify this before attempting to execute the function, also the exception text is missleading. the function is not missing is just called with wrong params

**Comment by federicoMoroni-git** [comment]
> What happens if you try to sync an empty SQLITE database (delegating the table creation to DMS) ?

same issue. a trackplot_cog table is created in the sqlite with a timstamp field of type text. but when you do 
```
[InternalApplyThenGetChangesAsync]..[InternalApplyThenGetChangesAsync]..[InternalApplyChangesAsync]..[InternalApplyTableChangesAsync]..42883: function pg_temp.trackplot_cog_scopename7_update(integer, integer, timestamp with time zone, text, numeric, numeric, uuid, bigint, bigint) does not exist

**Comment by Mimetis** [comment]
I'm able to reproduce the error.

The problem is coming from the "timestamp without time zone" in the pre-command and "timestamp with time zone" when calling the pre-command

**Comment by Mimetis** [comment]
can you try to use this command : `AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
`

**Comment by federicoMoroni-git** [comment]
> can you try to use this command : `AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true); `

at first try this seems to solve the issue. thanks a lot for the help I believe you can mark this issue as solved

**Comment by Mimetis** [comment]
Not really, as the `EnableLegacyTimestampBehavior` is meant to be used with _legacy_ applications :)

I've made a correction in the postgresql provider for the next version.
Still need to test it a little bit, but hopefully you won't have to deal with that anymore.
