### ISSUE TITLE
deadlocked in MSSQL or Timeout

### ISSUE THREAD

**Issue by dorathoto** [Mimetis/Dotmim.Sync#1237]
I have noticed that when the system is doing the sync (Server -> Client)

I have been receiving some SQL errors when another application tries to do an insert, for example, the errors are:

> SqlException: Transaction (Process ID 64) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

Or 

> Timeout

Something I had not seen before.

When executing SynchronizeAsync() does it lock the read-only tables?

Sometimes my sync goes into a clean mode and I don't know if that is when it locks
```
var localOrchestrator = new LocalOrchestrator(clientProvider);
await localOrchestrator.DropAllAsync();
await localOrchestrator.DeleteMetadatasAsync();
var serverOrchestrator = new LocalOrchestrator(serverProvider);
await serverOrchestrator.DropAllAsync();
await serverOrchestrator.DeleteMetadatasAsync();

```
I need to know if:
- it is a package failure;
- an expected behavior, if so when it happens;
- it is not from the component, probably another event;

**Comment by Mimetis** [comment]
Can occurs from different reasons

## DisableConstraintsOnApplyChanges

First one is the options [DisableConstraintsOnApplyChanges](https://dotmimsync.readthedocs.io/Configuration.html#disableconstraintsonapplychanges) when it's set to `true`.

``` cs
var options = new SyncOptions {
  DisableConstraintsOnApplyChanges = true
};
```

This option will lock the entire table during the synchronization (**as it's disabling all the constraints** for the whole entire table)

Set it to false will drastically reduce the lock on each table, but you need to be sure you won't have any issue with constraints on your tables.

## IsolationLevel

The level of isolation also plays a role in locking. You can set the `IsolationLevel` on the provider you are using :

``` cs
var serverProvider = new SqlSyncProvider(....);
serverProvider.IsolationLevel = IsolationLevel.ReadCommitted;
```

## TransactionLevel

You can also defining the level of transaction:

``` cs
var options = new SyncOptions {
  TransactionMode= TransactionMode.PerBatch
};
```

- `TransactionMode.AllOrNothing` : **Default** : Everything works or everything is rollback
- `TransactionMode.PerBatch` : Each batch has its own transaction (if you don't have too much rows, consider one batch == one table)
- `TransactionMode.None` : No transaction: Use at your own risk

**Comment by MaTToX3** [comment]
@Mimetis setting `DisableConstraintsOnApplyChanges = true` actually locks the entire table on the server side?

**Comment by MaTToX3** [comment]
@Mimetis offtopic, but I would really like to understand this lock if `DisableConstraintsOnApplyChanges = true` is enabled. So, does that mean, that some specific table on the server side is locked for read/write operations while data is being inserted/updated in that table? So, IF sync takes like 5 minutes, does that mean that lock is there for the whole duration of the sync or just for the time of data being applied to that specific table?

**Comment by Mimetis** [comment]
Table is locked because the constraints are disabled
And locked is maintained during the whole transaction
If transaction is `AllOrNothing` (default value) then yes table is locked during the whole sync.
