### ISSUE TITLE
Question: How do you bring tables from the client to the server in stages?

### ISSUE THREAD

**Issue by JScrivo** [Mimetis/Dotmim.Sync#1238]
In my use-case the client database is an existing database for an originally offline-only application.

Lets say on the client have I have table A, B, C.
Initially I specify tables A and B in the SyncSetup and call LocalOrchestrator.UpdateUntrackedRowsAsync() to track all of the original rows and send it to the server in the next sync.

In this scenario table C is a feature that is fully implemented on the client but on the server it is bottom of the priority list and won't be implemented for some time. Is there a way to call UpdateUntrackedRowsAsync() specifically for table C down the road and then sync all tables normally? Or do I have to include it in the SyncSetup from the beginning?

I mainly ask because my database is large and I would like to leave out stuff that isn't going to be useful to the server initially to speed up the initial sync. Then bring over those tables later when they are actually useful.

**Comment by Mimetis** [comment]
You can play around with multi scopes. You can find more info here : https://dotmimsync.readthedocs.io/Scopes.html#multi-scopes

In your case, I guess you can have a scope with table A & B and then a scope with only table C ?

**Comment by JScrivo** [comment]
Thank you for the help! That was exactly what I needed, I guess I missed that when I first read through the docs.

Also thank you for making this framework and maintaining it. This is the only library I've found that fits with my stack, specifically the web proxy stuff, everything else doesn't have safe options for sending stuff over the internet. I'll have to send some support your way in the near future.

**Comment by Mimetis** [comment]
Hey @JScrivo, can you send me your mail plz ?
