### ISSUE TITLE
MySqlSyncAdapter throwing NotImplementedException?

### ISSUE THREAD

**Issue by Morvayn** [Mimetis/Dotmim.Sync#1249]
Hi there Sebastien

First of all thanks for the great work.
Im writing my first project using DMS and, as i upgraded to the latest stable version 1.2.0 , i started having this error:

HttpSyncWebException: [InternalApplyThenGetChangesAsync]..[InternalApplyThenGetChangesAsync]..[InternalGetChangesAsync].Directory:C:\Users\Asus\AppData\Local\Temp\DotmimSync.Supports MultiActiveResultSets:False.Is New:True.From:..[InternalReadSyncTableChangesAsync].Table:aspnetusers.Is New:True.LastTimestamp:..[InternalGetSelectChangesCommandAsync].Table:aspnetusers.Is New:True.dbCommandType:SelectInitializedChangesWithFilters..The method or operation is not implemented.
  -----------------------

  └  ─ The method or operation is not implemented.
  
  
  
After downloading the source code and compiled it on my own the issue still remains. Here are the details of how i got there:
![image](https://github.com/user-attachments/assets/b219bd6a-155c-4650-8588-c80be50f237c)
The exception is thrown when i call agent.SyncronizeAsync within the client app.

The use case is as follows:
- the main database is mysql mariabd running behind a webapi (running .NET 7.0). DMS 1.2.0 dependencies loaded by Nuget.
![image](https://github.com/user-attachments/assets/f1a1497a-e6fb-42fd-ab84-1c103e57b901)
- the client app written in .net maui (also running .NET 7.0) is referencing the source projects core, sqliteadapter and web.client.
![image](https://github.com/user-attachments/assets/6bd577da-8c0d-47de-b71c-ca35d7b7032e)

The webapi startup is as follows (regarding DMS instructions)
1 - this particular table is partialy synced.
![image](https://github.com/user-attachments/assets/c781edbf-b4f4-4aac-b8f0-b47d86b97c46)

2 - others are fully synced(either with normal sync or DownloadOly) like this
![image](https://github.com/user-attachments/assets/67f20248-51e4-4ccf-ae5b-8ab5f25bfd32)

3 - DMS SyncServer is instanced with previous set of instructions
![image](https://github.com/user-attachments/assets/398e0bc2-2656-455b-9eee-68125d0b5289)

What am i doing wrong? Is there anything wrong with mysqlsync adapter?
How can i fix this?

Best Regards

**Comment by Mimetis** [comment]
oh wow, sorry about that, will look into it as soon as possible

**Comment by Mimetis** [comment]
Can you make a test with the last source code commit to see if everything is running correctly now ?

**Comment by Morvayn** [comment]
Hi there.
Sure. I will do so as soon as i'm able to (later tonight) and report back.
Thanks for your effort

**Comment by Morvayn** [comment]
Hi there.

I just tried it out and syncing performed as expected.
As far as i can tell everythings is now fine :)

Many thanks
Best Regards,
Morv

**Comment by Mimetis** [comment]
You can test the last beta version `1.3.0`

**Comment by Morvayn** [comment]
Hi there.
Beta 1809 Is working as intended (as far as i can tell in my prototype) :)
