### ISSUE TITLE
Sqlite sync has auto increment issue

### ISSUE THREAD

**Issue by Lerseb** [Mimetis/Dotmim.Sync#1250]
Hi Sebastien and Dotmim team,

I am struggling for a couple days on this, read in detail the documentation and still didn't find a solution.

Here is the error message I get:
InternalEnsureScopeInfoAsync].Overwrite:False..[InternalGetSchemaAsync]..[InternalGetTableSchemaAsync].Table:ObservationItems..[SetPrimaryKeysAsync].Table:ObservationItems..The column ClusteredId is an auto increment column, but it's not used as a primary key for the table ObservationItems. It's not allowed in DMS. Please consider to remove this column from your sync setup. ----------------------- └ ─ The column ClusteredId is an auto increment column, but it's not used as a primary key for the table ObservationItems. It's not allowed in DMS. Please consider to remove this column from your sync setup.

In order to avoid this, I already used this code below  to remove "ClusteredId" (which is used as index on my server Postgres Db. I have also a uuid as primary key) from the sync but the message still pops up. I also removed the byte array columns (not used anymore) which would be blobs in sqlite.

        var authState = await _authenticationStateProvider.GetAuthenticationStateAsync();
        var tableObservatinoItems = _mobileContext.ObservationItems.EntityType.GetTableName();
        var dataKey = authState.User.Claims
            .FirstOrDefault(c => c.Type == DataAuthConstants.HierarchicalKeyClaimName).Value;
        var status = new StatusGenericHandler<string>();
        var serverOrchestrator = new WebRemoteOrchestrator(ApiUrls.DbSyncUrl);
        var clientProvider = new SqliteSyncProvider(_database.CreateConnectionStringWithEncryption());
        var setup = new SyncSetup();
        setup.Tables.Add(_mobileContext.ObservationItems.EntityType.GetTableName());
        var fields = _mobileContext.Model
            .GetEntityTypes()
            .Where(x => x.GetTableName() == tableObservatinoItems)
            .FirstOrDefault()
            .GetProperties()
            .Where(x => x.Name != "ClusteredId" && x.Name != "ImageBytea" && x.Name != "ThumbnailBytea")
            .Cast<object>()
            .Select(x => x.ToString())
            .ToArray();
        setup.Tables[tableObservatinoItems].Columns.AddRange(fields);
        setup.Filters.Add(tableObservatinoItems,"DataKey");
        var parameters= new SyncParameters{{"DataKey", dataKey}};
        var agent = new SyncAgent(clientProvider, serverOrchestrator);
        var syncResult = await agent.SynchronizeAsync(setup,parameters);

During debug, I can confirm that the 3 columns are not included in the syncSetup/table/columns
I am calling an API server but all the code above is in the MAUI mobile client side.

Thanks in advance for your help.
Best regards.
Sebastien

**Comment by Mimetis** [comment]
Make a test with a clean database (on server and client side)
I guess, since you have made some tests, you still have an old setup registered in the server database with this auto inc column.

In a HTTP scenario, where you are using the `WebRemoteOrchestrator`, the setup is defined on the web api side, you don't need to define it also on the client side (as it's retrieved from the server side on first sync)
