### ISSUE TITLE
Procedure or function 'sp_flush_CT_internal_table_on_demand' expects parameter '@TableToClean' in SyncAgent.cs:line 456

### ISSUE THREAD

**Issue by dorathoto** [Mimetis/Dotmim.Sync#1257]
Sometimes the following error occurs:

[InternalApplyChangesAsync]..[InternalDeleteMetadatasAsync].TimestampLimit:60..Procedure or function 'sp_flush_CT_internal_table_on_demand' expects parameter '@TableToClean', which was not supplied.

well when I run it:
var result = await agent.SynchronizeAsync(setup, parameters, progress);

StackTrace:
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__26.MoveNext() in /_/Projects/Dotmim.Sync.Core/SyncAgent.cs:line 456

In: Dotmim.Sync.Core
Any suggestions on what might be going on? Can I help with some additional logs?

**Comment by Mimetis** [comment]
You are using `SqlChangeTrackingSyncProvider`.
The "_auto cleanup metadata_" for sql server change tracking have been implemented in the last beta version, but it seems it's not working as expected (and is pretty slow)

It will be removed in the next beta version.
Until then, you can disable the clean up metadata with the `SyncOptions` object

**Comment by Mimetis** [comment]
the last beta version has the fix
