### ISSUE TITLE
Is there any support for image, nText datatype 

### ISSUE THREAD

**Issue by arjunbharara** [Mimetis/Dotmim.Sync#1267]
.It is throwing me a exception which is  ntext from provider SqlSyncProvider, Dotmim.Sync.SqlServer.SqlSyncProvider is not currently supported.'

**Comment by Mimetis** [comment]
As said, it's not supported.
My advice: Change `ntext` to `varchar(max)`

**Comment by Mimetis** [comment]
and change `Image` to `varbinary(max)`

**Comment by arjunbharara** [comment]
thank you for your reply .
i had one more question 
By using SetCreateProceduresForAdditionalScopeDefault, you can prevent redundant stored procedures from being created, reducing the number of database objects and improving maintenance efficiency. When additional scopes for the same table do not require unique stored procedures (i.e., they share similar filtering or data requirements), you can reuse the existing procedures. This approach optimizes storage and minimizes the complexity of managing multiple scopes, especially when the same tables are involved in each scope.
can we do the same in Dtmim ?

**Comment by Mimetis** [comment]
No, each scope has its own set of stored procedures.

That being said, it something we can think about, but definitively not in my priority list :)

**Comment by arjunbharara** [comment]
What are the alternate if do not want to upgrade my database from using image and nText dataType. because migrating my database would cost me a lot work and data changes.

**Comment by arjunbharara** [comment]
Beside Text ,nText and image data types is there any other data types which are not supported by the sqlSyncProvider.
It will be great if you can update the documentation to the latest version.
thank you.

**Comment by arjunbharara** [comment]
For the first sync it downloads all the data from server and applies it to client(does not sync the client data to server).
If i have data from both side with exactly same setup and i want to sync data form server to client and client to server(Bidirectional in the First Syncing itself). Is there any possibility i can do that in Dotmim?
