### ISSUE TITLE
Speed to Deprovision and Provision

### ISSUE THREAD

**Issue by spj-uk** [Mimetis/Dotmim.Sync#1271]
Our process sets up a new database by taking a backup of a template db and then restoring it as a new db. We then deprovision and provision the db. However this takes around a minute for the deprovision and reprovision. This template db is a master for the user and we try not to change the schema but certainly the template should be the latest. Any tips for speeding this up? Or do I need it all of the schema has not changed?

`var serverProvider = new SqlSyncProvider(connStrNew);
var remoteOrchestrator = new RemoteOrchestrator(serverProvider);

var p = SyncProvision.TrackingTable |
        SyncProvision.StoredProcedures | SyncProvision.Triggers |
        SyncProvision.ScopeInfo | SyncProvision.ScopeInfoClient;

await remoteOrchestrator.DeprovisionAsync(p);

var scopeInfo = await remoteOrchestrator.ProvisionAsync(setup, p, overwrite: true);`

**Comment by Mimetis** [comment]
Your code is provisioning a **server** database, right ?

Your code seems to be pretty legit, in my opinion.

- The `DeprovisionAsync()` is mandatory only if there is an existing provisioning from your backup.
- You can maybe optimize the provisioning as, whatever the columns of a given table, the trigger is always the same. 
- Tracking table is also the same if the primary key did not changed
- `ScopeInfo` and `ScopeInfoClient` are the same, if you already have them, just drop the rows

I'm curious about why it takes so much time.
As it's not related to the data, but more the schema, is it possible to share with me a copy of the schema of your database, to make some tests and see where the performances issues are occurring  during provisioning ?

**Comment by spj-uk** [comment]
Hi,

I have attached the script. Yes, this is provisioning a server database.

Simno.

Simon Jeffs
Director

Mapyx Limited and 3S Group Limited
8A Cranmere Road, Okehampton, Devon, EX20 1UE

Tel:   +44 (0)1392 241428
Out of Hours Emergency: +44 (0) 333 210 0420

www.mapyx.com<http://www.mapyx.com/>
www.linkedin.com/in/simonjeffs<http://www.linkedin.com/in/simonjeffs/>

Confidentiality:  This communication may contain confidential information that is confidential and/or privileged and is for the exclusive use of the intended recipient(s).  Any form of distribution, copying or use by anyone else is strictly prohibited.  If you have received this communication in error, please delete it and advise us accordingly.

**Comment by spj-uk** [comment]
Correct, we are provisioning a server database. 

I have a script file I can share with you - can I send it directly?

**Comment by Mimetis** [comment]
I've tried your schema, that is empty.

Here is my code:

``` cs
var serverProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString("............"));
var setup = new SyncSetup(".......................................");

var watch = Stopwatch.StartNew();

var options = new SyncOptions { 
  DisableConstraintsOnApplyChanges = false, 
  TransactionMode = TransactionMode.None 
};

serverProvider.IsolationLevel = IsolationLevel.ReadUncommitted;

var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options);

var p = SyncProvision.TrackingTable | SyncProvision.StoredProcedures | SyncProvision.Triggers | 
    SyncProvision.ScopeInfo | SyncProvision.ScopeInfoClient;

Console.WriteLine("Deprovisioning");
await remoteOrchestrator.DeprovisionAsync(p);

Console.WriteLine("Provisioning");
await remoteOrchestrator.ProvisionAsync(setup);

watch.Stop();
var ellapsedTime = $"{watch.Elapsed.Minutes}:{watch.Elapsed.Seconds}.{watch.Elapsed.Milliseconds}";

Console.WriteLine($"Ellapsed time:{ellapsedTime}");
```

And the result I've got:

``` bash
Deprovisioning
Provisioning
Ellapsed time:0:6.617
```

I tried with some dirty options as you can see (like `DisableConstraintsOnApplyChanges`, `TransactionMode` and `IsolationLevel`) but as the database I got is empty, it did not affected the results

I guess an empty database is easier to deprovision / provision as there is no rows.

You could try with these options also, but you may face some errors (especially with `DisableConstraintsOnApplyChanges`) if your tables has foreign keys that can break the consistency
But it's worth a try !
