### ISSUE TITLE
Getting This SqlTransaction has completed; it is no longer usable  for Large data

### ISSUE THREAD

**Issue by arjunbharara** [Mimetis/Dotmim.Sync#1273]
Dotmim.Sync.SyncException: [InternalApplyChangesAsync]..[InternalApplyChangesAsync]..[InternalApplyTableChangesAsync]..This SqlTransaction has completed; it is no longer usable. ---> System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable. at Microsoft.Data.SqlClient.SqlTransaction.ZombieCheck() at Microsoft.Data.SqlClient.SqlTransaction.Commit() at Dotmim.Sync.DbConnectionRunner.<CommitAsync>d__29.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Dotmim.Sync.BaseOrchestrator.<>c__DisplayClass1_1.<<InternalApplyTableChangesAsync>b__5>d.MoveNext() --- End of inner exception stack trace --- at Cluster.Manager.DotmimSync.DotmimSyncProvider.Sync(ClusterServerDbo localServerDbo, ClusterServerDbo remoteServerDbo, Boolean decryptConnection, String dbSyncScope) at Cluster.Manager.ServerManager.DoDBSync(Boolean overideModeCheck)

**Comment by arjunbharara** [comment]
![large data](https://github.com/user-attachments/assets/bc711fb9-687d-43cf-a026-b4606c0f8a8a)

**Comment by Mimetis** [comment]
No idea, need a sample to reproduce, to be able to help you

**Comment by arjunbharara** [comment]
Thank you for your response; the issue was resolved when I upgraded to the latest version.

Currently, I’m experiencing performance issues during synchronization. I’m syncing around 37,000 rows, with the table size being approximately 1.2 GB. The process takes a minimum of 5 minutes to complete. Is this expected, or am I encountering performance bottlenecks?

Here’s my current SyncOptions configuration:
var syncOptions = new SyncOptions
{
    CleanMetadatas = true,
    DisableConstraintsOnApplyChanges = true,
    DbCommandTimeout = 360,
    BatchSize = 50000
};

Even when I set TransactionMode to PerBatch, the performance does not improve. Could you provide suggestions to optimize the synchronization process further?

**Comment by Mimetis** [comment]
How many columns do you have in your table ?

**Comment by arjunbharara** [comment]
I am currently facing an exception while filtering data. The exception thrown is:

Dotmim.Sync.FilterParamColumnNotExistsException: The parameter 'IsSystemUser' does not exist as a column in the table 'MMCUserDbo'.

This occurs when I attempt to provision, and the following code is executed:

if (setup.Tables[tableForFilter.TableName] != null)
{
    var filter = new SetupFilter(tableForFilter.TableName);
    filter.AddParameter(clusterColumnSyncDbo.ColumnName, tableForFilter.TableName);
    filter.AddCustomWhere(clusterColumnSyncDbo.Filter);
    setup.Filters.Add(filter);
}
The filter value I am using is: [side].[IsSystemUser] = 0.

Although my table contains the column IsSystemUser, I am still encountering this exception. Could you help me resolve this issue?

**Comment by arjunbharara** [comment]
clusterColumnSyncDbo.ColumnName is part of the tableForFilter. the clusterColumnSyncDbo.ColumnName  added to the parameter but it still thows the same error.

**Comment by Mimetis** [comment]
I don't know, I need more info, like the table schema and the custom where clause, to be able to reproduce the error

**Comment by arjunbharara** [comment]
table schema
USE [EDCDB_arjun1]
GO
/****** Object:  Table [dbo].[MMCUserDbo]    Script Date: 28-11-2024 16:26:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MMCUserDbo](
	[Id] [uniqueidentifier] NOT NULL,
	[UserName] [nvarchar](100) NOT NULL,
	[UserDisplayName] [nvarchar](200) NOT NULL,
	[AdServerId] [uniqueidentifier] NULL,
	[UserType] [int] NULL,
	[IsSystemUser] [bit] NOT NULL,
	[OrganizationNodeId] [uniqueidentifier] NOT NULL,
	[UserPrincipalName] [nvarchar](320) NULL,
	[EmailId] [nvarchar](320) NULL,
	[PhoneNumber] [nvarchar](15) NULL,
 CONSTRAINT [PK_MMCUser] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MMCUserDbo]  WITH NOCHECK ADD  CONSTRAINT [FK_AuthServerId] FOREIGN KEY([AdServerId])
REFERENCES [dbo].[AuthenticationServerDbo] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[MMCUserDbo] CHECK CONSTRAINT [FK_AuthServerId]
GO

ALTER TABLE [dbo].[MMCUserDbo]  WITH NOCHECK ADD  CONSTRAINT [FK_MMcUser_OrganizationNode] FOREIGN KEY([OrganizationNodeId])
REFERENCES [dbo].[OrganizationNodeDbo] ([Id])
GO

ALTER TABLE [dbo].[MMCUserDbo] CHECK CONSTRAINT [FK_MMcUser_OrganizationNode]
GO



custom where condition :-  "[side].[IsSystemUser]= 0"
parameter name is :- 
![filterDeatails](https://github.com/user-attachments/assets/a6181b1e-abc6-48f8-919f-9c667493d7db)
![2nd](https://github.com/user-attachments/assets/ec834e4d-5454-4b97-a7c5-de44dea7cb8b)

getting this error while provisioning
Dotmim.Sync.SyncException: '[ProvisionAsync].Provision:TrackingTable, StoredProcedures, Triggers, ScopeInfo, ScopeInfoClient.Overwrite:False..[InternalProvisionServerAsync].Provision:TrackingTable, StoredProcedures, Triggers, ScopeInfo, ScopeInfoClient.Overwrite:False..[InternalProvisionAsync].Provision:TrackingTable, StoredProcedures, Triggers, ScopeInfo, ScopeInfoClient.Overwrite:False..[InternalCreateStoredProceduresAsync].Table:MMCUserDbo.Overwrite:False..[InternalCreateStoredProcedureAsync].Table:MMCUserDbo.StoredProcedure:SelectInitializedChangesWithFilters..Invalid column name 'IsSystemUser'.'

**Comment by Mimetis** [comment]
I think you don't have to use `AddCustomWhere`, A classic filter should be fine, in my opinion.

> Side note: I see you are using CASCADE DELETE. It's not working with DMS as the triggers are not triggered when a cascaded row is deleted

I used this code, that is correctly working:

``` sql
USE [master]
GO 

-- Server database
if (exists (select * from sys.databases where name = 'AdventureWorks'))
Begin
	ALTER DATABASE [AdventureWorks] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [AdventureWorks]
End
Create database [AdventureWorks]
Go
-- Client database. No need to create the schema, Dotmim.Sync will do
if (exists (select * from sys.databases where name = 'Client'))
Begin
	ALTER DATABASE [Client] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [Client]
End
Create database [Client]
Go

USE [AdventureWorks]
GO
CREATE TABLE [dbo].[MMCUserDbo](
[Id] [uniqueidentifier] NOT NULL,
[UserName] nvarchar(50) NOT NULL,
[UserDisplayName] nvarchar(50) NOT NULL,
[AdServerId] [uniqueidentifier] NULL,
[UserType] [int] NULL,
[IsSystemUser] [bit] NOT NULL,
[OrganizationNodeId] [uniqueidentifier] NOT NULL,
[UserPrincipalName] nvarchar(50) NULL,
[EmailId] nvarchar(50) NULL,
[PhoneNumber] nvarchar(50) NULL,
CONSTRAINT [PK_MMCUser] PRIMARY KEY CLUSTERED
(
[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

Insert into [MMCUserDbo] Values 
	(newid(), 'John', 'John', NEWID(), 1, 1, NEWID(), 'John', 'John@contoso.com', '01-01-01-01'),
	(newid(), 'Jane', 'Jane', NEWID(), 1, 0, NEWID(), 'Jane', 'Jane@contoso.com', '01-01-01-01')
```

And the sync code:

``` cs
var serverProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(ServerDb);
var clientProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(ClientDb);
var options = new SyncOptions();

var setup = new SyncSetup("MMCUserDbo");

var filter = new SetupFilter("MMCUserDbo");
filter.AddParameter("IsSystemUser", "MMCUserDbo");
filter.AddWhere("IsSystemUser", "MMCUserDbo", "IsSystemUser");
setup.Filters.Add(filter);

var progress = new SynchronousProgress<ProgressArgs>(s =>
    Console.WriteLine($"{s.ProgressPercentage:p}:  " +
    $"\t[{s?.Source?[..Math.Min(4, s.Source.Length)]}] {s.TypeName}: {s.Message}"));

var agent = new SyncAgent(clientProvider, serverProvider, options);

do
{
    try
    {
        Console.ForegroundColor = ConsoleColor.Green;
        var parameters = new SyncParameters
        {
            { "IsSystemUser", true   }
        };
        var s = await agent.SynchronizeAsync(setup, parameters, progress: progress);
        Console.WriteLine(s);
    }
    catch (SyncException e)
    {
        Console.ResetColor();
        Console.WriteLine(e.Message);
    }
    catch (Exception e)
    {
        Console.ResetColor();
        Console.WriteLine("UNKNOW EXCEPTION : " + e.Message);
    }

    Console.WriteLine("--------------------");
}
while (Console.ReadKey().Key != ConsoleKey.Escape);

```

**Comment by arjunbharara** [comment]
I am facing an issue where I need to apply multiple complex filters on a single table. Some of these filters involve calling functions, such as:

[dbo].[IsTeamValidforDCDRSync]([side].[TeamCreationType]) = 1
[base].[Id] IS NULL OR ([base].[ClientType] = 5 AND [side].[PoolId] IN (SELECT [innerpool].[Id] FROM [dbo].[PoolDbo] [innerpool] WHERE [innerpool].[Id] = [side].[PoolId] AND [dbo].[IsPoolValidforDCDRSync]([innerpool].[DVMCreationType], [innerpool].[PoolCreationType], [innerpool].[PoolType], [innerpool].[PoolProviderType]) = 1))
Because of the complexity and reliance on scalar function calls, I cannot use a simple WHERE clause. Additionally, while testing a previous condition, I found an interesting behavior: when I removed [side] from the filter [side].[IsSystemUser] = 0, the provisioning process was successful.

Do you have any suggestions or alternatives for implementing these filters more efficiently?

**Comment by Mimetis** [comment]
Please open new issue if needed and you found a bug in DMS, or go to the discussion to ask questions.

Seems you did not confirmed my solution works (or confirm it is) but I will close the issue as it's not relevant to the title
Thanks

**Comment by arjunbharara** [comment]
sorry ,i totally forgot to answer that 
yes it is working like that but i have lots of filters and those filters are long and complex that is why i can use simple where condition.

**Comment by nicolazreinh** [comment]
Hi all, I am facing the same issue
Stack Trace: at Microsoft.Data.SqlClient.SqlTransaction.ZombieCheck() at Microsoft.Data.SqlClient.SqlTransaction.Commit() at Dotmim.Sync.DbConnectionRunner.d__29.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) at Dotmim.Sync.BaseOrchestrator.<>c__DisplayClass1_1.<b__5>d.MoveNext() ********** Exception: This SqlTransaction has completed; it is no longer usable. ********** 
How can I fix it?

**Comment by Mimetis** [comment]
You have something that takes too much time to execute.
You have plenty of articles on internet about how to monitor long execution and how to tune queries for better performances
