### ISSUE TITLE
MSSql ChangeTracking not working for deleted rows

### ISSUE THREAD

**Issue by truthz03** [Mimetis/Dotmim.Sync#1275]
Hi,

I'm using 1.3.0-beta-1818 and my server is MSSql with ChangeTracking enabled.
If I modify columns or add new rows and sync the client, the client gets the new data.

If I delete a row from the server database and sync the client nothing happens!!
Does the MSSql ChangeTracking not work with row delete?

**Comment by Mimetis** [comment]
it's working with deleted rows.
Can you share the server code and the client code you are using ?

**Comment by truthz03** [comment]
I made a simple test to reproduce it with a minimum example.
While using `AddWhere` everything is working. If using `AddCustomWhere` it is not working anymore!
You give me the hint already [here](https://github.com/Mimetis/Dotmim.Sync/discussions/1274#discussioncomment-11376653) ;)

**Comment by Mimetis** [comment]
Nice ! :)

**Comment by truthz03** [comment]
Using the MSSql ChangeTracking needs change tracking enabled inside the database.
Enabling the change tracking needs a retention time.
What happens if the retention time is 7 days and the client syncs after about 20 days? Did the client miss some changes then?

**Comment by Mimetis** [comment]
You will be out of date, and an error will be raised .
See https://dotmimsync.readthedocs.io/Interceptors.html#onoutdated for more
