### ISSUE TITLE
Can't Filter Data when sync

### ISSUE THREAD

**Issue by waelbouchnak** [Mimetis/Dotmim.Sync#128]
Hey,
i want to sync using AdventureWorks db for sql server .
sync is working properly without filter but when i try to add a Filter, the App crash when syncing
> Exeption :  {"There is already an open DataReader associated with this Command which must be closed >first."}

Client Side:
```
agent.Parameters.Add("Customer", "Title", "Mr."); 
var syncResponse = agent.SynchronizeAsync();
```
Server Side:
```
var tables = new string[] { "Customer" ,  "Product"  };
conf.Add(tables);
conf.Filters.Add(new FilterClause("Customer", "Title"));
```
does anyone have any idea about this?

**Comment by Mimetis** [comment]
hello @waelbouchnak !
Thanks for the report.
Which version are you using (released or beta version from nuget, or source code) ?

I will investigate on my side

Sebastien

**Comment by waelbouchnak** [comment]
i'm using the version "0.2.1" from nuget.

Thanks,
Wael

**Comment by Mimetis** [comment]
Do you have any foreign table who reference the `Customer` primary key ?
If you're using `AdventureWorks`, you should have a table `CustomerAddress`

The problem is : If you're filtering on **Mr.** you don't have all the `Customers` and `CustomerAddress` will fail because he won't be able to insert some records

**Comment by waelbouchnak** [comment]
the problem is solved.
Thanks Sébastien.

**Comment by Mimetis** [comment]
No pb, just curious, what was the problem here?

**Comment by waelbouchnak** [comment]
it was not working Because i tried to sync the customer table only without the tables that has reference to it.

**Comment by yodiaz87** [comment]
I am having the same issue, I followed the documentation and tried to filter a simple Table that has no relationship with any other table, I just want to filter for one of its columns: ```Table: Person``` ```Columns: id, name, genre``` and I want to filter by genre for example.

**Comment by Mimetis** [comment]
Try the `v0.4` 
The issue should be resolved.
And let me know if you still have the problem

**Comment by yodiaz87** [comment]
Thank you for the quick answer, I already was trying that but there are some things that I am missing in this example:

Where is the code of this.FilterParameters, this.FilterSetup.
Where do you use filterParameters variable.

You mention before that this code example you have it in the tests, could you provide the github link?

**Comment by Mimetis** [comment]
https://github.com/Mimetis/Dotmim.Sync/blob/Mimetis-Simplified-Flow/Tests/Dotmim.Sync.Tests/TcpFilterTests.cs

**Comment by yodiaz87** [comment]
var proxyClientProvider = new WebClientOrchestrator("http://localhost:5000/api/sync");
            
var agent = new SyncAgent(clientProvider, proxyClientProvider, tables);

SyncAgent is expecting that proxyClientProvider be an CoreProvider I tried this:

```proxyClientProvider.Provider```
but is returning null. I think is the only that is missing.

**Comment by yodiaz87** [comment]
This worked for me:

```var clientProvider = new SqlSyncProvider(clientConnectionString);

var proxyClientProvider = new WebClientOrchestrator("http://localhost:52288/api/Sync");

var filterParameters = new List<SyncParameter>
{
        new SyncParameter("Customer", "CustomerID", null, customerIdValue),
  
};

// create agent with filtered tables and parameter
var agent = new SyncAgent(clientProvider, proxyClientProvider);
agent.Parameters.AddRange(filterParameters);

var s = await agent.SynchronizeAsync();```

**Comment by yodiaz87** [comment]
Thank you @Mimetis
