### ISSUE TITLE
NullReferenceException - SyncOptions

### ISSUE THREAD

**Issue by lordofffarm** [Mimetis/Dotmim.Sync#129]
Setup:
Server: WebProxyServerProvider
Client: Xamarin.Android app - SqliteSyncProvider

When synchronizing
NullReferenceException at line 568 WebProxyServerProvider at server side, Options is null.

SyncAgent.Options is also null at client side, after getting a new instance of SyncAgent.

<code>var syncAgent = new SyncAgent(localProvider, remoteProvider);</code>
<code>syncAgent.Options.BatchDirectory = batchDirectory;</code>

**Comment by Mimetis** [comment]
Thx for reporting this issue.

Will be fixed in my next commit.

Until then, you just have to create a `SyncOptions` object, before adding the `BatchDirectory`
