### ISSUE TITLE
Xamarin.Droid SyncAgent BatchDirectory is set from the webservice

### ISSUE THREAD

**Issue by waelbouchnak** [Mimetis/Dotmim.Sync#130]
i'm using Dotmim v0.2 from nuget for Xamarin Project
when synchronizing between the Android app and the Webservice i'm getting this exception

`Dotmim.Sync.SyncException: Access to the path "C:\Users\****\AppData\Local\Temp\DotmimSync" is denied. `

the problem is that the Android app cannot access to the temp folder which is in "c:\\......." .
1) i tried to change the BatchDirectory from the mobile app to the local android app folder 
`conf.BatchDirectory = "/data/user/0/*****/files/tempFromWeb";`  
but when the app start synchonizing,the BatchDirectory is changed with a value `C:\Users\****\AppData\Local\Temp\DotmimSync`
2) i tried to set the batch directory from the webservice to this
`conf.BatchDirectory = "/data/user/0/*****/files/tempFromWeb";`
 then the sync worked and i got the same batchDirectory from the Client side

what i understood is that the Dotmim Lib of the webservice is not testing whether the client is an android, ios or desktop app to generate the right temp path.
 i think the best way is to set the client temp folder from the client app

**Comment by lordofffarm** [comment]
Hi, this has been fixed in the Prerelease version 0.3.0 with a workaround, you can try this version. 
But, using BatchDirectory in further releases (with a proper fix) is going to have some minor changes.
