### ISSUE TITLE
Cant sync after updating the local data over web proxies

### ISSUE THREAD

**Issue by vishnusr831** [Mimetis/Dotmim.Sync#134]
Hi,
We are currently working on this project to sync SQL and SQLite. We are syncing it over web proxy.
We are using the version 0.3.0-beta-0113. I tried 0.3.0-beta-0139 and the sync was not even happening.

**Issue-**
Initially, I synced the data to the mobile device and then I updated the local database and after that, I am not able to sync anymore and getting an exception "Invalid index 0 for this SqlParameterCollection with Count=0".

All the functionalities work perfectly if I don't use web proxies. I tried the stable versions, but I was not able to filter the table(over web proxies, because of this issue I guess - #73 ). Please, help us to tackle this issue. If you need more information, please let me know.

**Comment by Mimetis** [comment]
Can you provide me a repro ? 
Let's say, not your code, but just your schema database, and the code you're using to configure `Dotmim.Sync`

In the meantime, I will make more tests on the proxy involving SQL Server and SQLite

Thx for the feedback, and sorry for the bug

Sebastien

**Comment by vishnusr831** [comment]
More info-
Steps to reproduce-
Fill the DB with some data and then sync it with the client.
Then change the table value from the client side and then try to sync and it fails.
Dotmin version -  0.3.0-beta-0139 or 0.3.0-beta-0113

**Comment by Mimetis** [comment]
thx, will test asap

**Comment by vishnusr831** [comment]
Hey, I got an update.
I tested in other system and the same code was working. I did a research and I found that the table design was different(no from my side). 

For Eg:
I created a table named "beta" and did a sync. After updating the data from the client side, the sync was not working. After that, I created a new table and it was working perfectly. There is no difference between this two table when I created them(I used the same SQL query). The difference I noticed was that, once the table is created for the alpha table, there was some custom code(eg: triggers) were added and for the beta table, it was not there. So I believe that something went wrong during the initialization of these tables. 

In the alpha table -
`CREATE TABLE [dbo].[alpha] (
    [Id]     INT            NOT NULL,
    [userid] INT            NOT NULL,
    [data]   NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
CREATE TRIGGER [dbo].[alpha_insert_trigger] ON [alpha] FOR INSERT AS

-- If row was deleted before, it already exists, so just make an update
UPDATE [side] 
SET 	[sync_row_is_tombstone] = 0
etc...
`

In beta table-
`CREATE TABLE [dbo].[beta] (
    [Id]     INT            NOT NULL,
    [userid] INT            NOT NULL,
    [data]   NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

`

I will continue work to figure out this behavior.

**Comment by Mimetis** [comment]
You should not modify your database once the databas is provisioned byt the `Dotmim.Sync`
If you change the schema, you need to reset everything (use `Provision` and `Deprovision` methods, or test on a new fresh database)

Did you make a sync, THEN edit the schema (in this case, if youd reprovision, it won't work)
