### ISSUE TITLE
ApplyChangedFailed Event is not raised

### ISSUE THREAD

**Issue by waelbouchnak** [Mimetis/Dotmim.Sync#138]
sync and filtering is working properly in the version 0.113 nuget package but custom conflict solving is not working.
i have :
Server value( Table.Column 2) ---> A
Client Value( Table.Column 2) ---> B
if i set the conflict solving strategy ( ServerWin Or ClientWins), its working
but when i set the "ApplyChangedFailed"  to the sync agent, the server always win and "ApplyChangedFailed" is never called.

**Comment by Mimetis** [comment]
Can you share your server side code ? (just the part where you configure and handle ApplyChangedFailed stuff)

**Comment by waelbouchnak** [comment]
Server Side : 
```
 services.AddSyncServer<SqlSyncProvider>(SqlServerCnxString, (conf)=>
                {
                    var tables = new string[] { "Customers"  };
                    conf.Add(tables);
                    conf.Filters.Add(new FilterClause("Customers", "ID"  ));          
                });
```
Client Side:
```
var httpAdress = "http://10.124.0.91:27017/api/values";
WebProxyClientProvider proxyClient = new WebProxyClientProvider(new Uri(httpAdress));
string dpPath =            Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal), "MyDb.db");
sqliteSync = new SqliteSyncProvider(dpPath);
SyncAgent agent = new SyncAgent(sqliteSync, proxyClient);
agent.Parameters.Add("Customers", "ID", "1");
agent.ApplyChangedFailed += Agent_ApplyChangedFailed;
var s = await agent.SynchronizeAsync();
```
```
 private void Agent_ApplyChangedFailed(object sender, ApplyChangeFailedEventArgs e)
        {
         }
```

**Comment by Mimetis** [comment]
The resolution must occur on the server side.   
Just saw that the doc is outdated and there is no sample explaining how to deal with it :(   
Sorry for that

You must add your `ApplyChangedFailed` stuff on the server in the controller.   
Something like
``` csharp
webproxyServerProvider.LocalProvider.ApplyChangedFailed(object sender, ApplyChangeFailedEventArgs e)
...
```

**Comment by waelbouchnak** [comment]
Thank you Sébastien :)
Custom Conflict Solving is working
