### ISSUE TITLE
Add better exception messages

### ISSUE THREAD

**Issue by Thaval** [Mimetis/Dotmim.Sync#140]
Hi,

for better exception handling and for fixing problem faster, it would be neat if the thrown exception would include more precise messages. 
For example:

> Table {TableDescription.TableName} must have at least one dmColumn as Primary key"

Is thrown often within CreateTable, CreateForeignKeys, CreateTriggers.. it would be good if the taken action is included within the message, so the developer knows what excactly went wrong (or at least at which action)

Suggestion: 

> Create database: Table {TableDescription.TableName} must have at least one dmColumn as Primary key"

> Create trigger: Table {TableDescription.TableName} must have at least one dmColumn as Primary key"

Another example:

> There is already an open DataReader associated with this Command which must be closed first

This actually tells me that a second reader is activated. Either "MultipleActiveResultSets=true;" is not set or the tables are synchronized in the wrong order, right? 

Suggestion if MultipleActiveResultSets=false:

> There is already an open DataReader associated with this Command which must be closed first. Try setting MultipleActiveResultSets to true.

Suggestion if MultipleActiveResultSets=true:

> There is already an open DataReader associated with this Command which must be closed first. Seems like you specified a wrong order for you tables. Check your constraints and reorder the tables in your configuration.

In accordance to this problem, wouldn't it be nice if you must not specify all tables that you wish to be synced? Like, if I pass null or do not specify any table, all tables should be synced? (Algorithm to determine the correct order to sync tables by foreign key analysis. How the hell does that work?)

**Comment by Mimetis** [comment]
Yes, exceptions messages should be improved (feel free to make a PR :) )
About the fact you must specify tables, the behavior is intended. 
If I allow to "not specify tables", what will happen, when you will add or remove a table from your DB ? (If you forget to Deprovision / Provision your Sync .?)
Having a "null" option is a good thing, technically, but will make more frustration and problems, in my opinion, in the long term

**Comment by Thaval** [comment]
I will as soon as I find the time. I'm still trying to grasp everything what's going on (I'm not a DB expert, nor I'm a git expert).

Well, I didn't think about that fact yet but you're true. Maybe for a later point, when we run out of ideas.

May I ask you a question here? Do you have a roadmap or something like this? I wanna do some changes but don't want to implement something new while breaking changes occur. 

I think I will try to make the PR tonight.

**Comment by Mimetis** [comment]
If you're not sure about a new feature, open an issue and let's discuss it
