### ISSUE TITLE
Issue with database columns with blank spaces

### ISSUE THREAD

**Issue by FranVillaVainilla** [Mimetis/Dotmim.Sync#142]
Hi Sébastien, thanks for this great job.

Hi know that's not a good practice using column names with blank spaces. Anyway, seems like Dotmim.Sync is in trouble with that, and i'm getting an exception when trying to sync tables with columns names containing blank spaces. 

there is any option to get Dotmim.Sync working apart from removing blank spaces in database column names?

Regards!

**Comment by Mimetis** [comment]
Until it's fixed, I suppose you should avoid white space in columns.

I will try to fix it for the next release, thx for the issue !

**Comment by FranVillaVainilla** [comment]
Thanks Sébastien.

**Comment by Mimetis** [comment]
Hello @FranVillaVainilla     
Just to let you know, I'm actually working on fixing this issue.       
It will be probably done by the end of the week (hopefully)

**Comment by Mimetis** [comment]
Hey @FranVillaVainilla, this issue should be fixed with the last commit :)
Please test it and give me some feedback !
