### ISSUE TITLE
Is it OK to use a Database both as Source AND Destination for sync

### ISSUE THREAD

**Issue by ralph-fuechtenkort** [Mimetis/Dotmim.Sync#145]
We have a scenario where we want to sync a SQL server db on azure first with another SQL server on a dedicated linux machine and from there with Xamarin based Android and IOS devices using sqlite.
On Azure it should be (obviously) via web-service. On the local server it could be both, web-service OR database direct.
Would that be possible or do you expect any sync issues with that. For the information. Data-Flow between Azure and server is PER TABLE usually only in one direction.
Any Info/hint appreciated.
Thanks and Greets
Ralph

**Comment by Mimetis** [comment]
Hum... I've never think about such scenario, to be honest...   
Maybe you could try something like Azure SQL DB -> SQL Linux with a first Scope named "scope1"   
And then make the sync SQL Linux <-> SQLite with another scope "scope2"

Never tested this solution. Let me know if it's working.

**Comment by ralph-fuechtenkort** [comment]
Hi,
Thanks for the info. Just started trying this but failed with a maybe - rookie - error.
Have deployed server side to azure and it seams that the connection works as tables in the client db (also SQL Server) are generated.
Anyway, using the sample code for the client, sync finished with the following error:
Sync Exception: Could not find stored procedure 'dbo.FbMenuCardItems_selectchanges'.. Type:Data.

What have i actually missed :)

Greets from Manila 
RAlph

**Comment by Mimetis** [comment]
Close this one, since we have the issue #147 open
