### ISSUE TITLE
SQLite adapter sometimes does not send changes back to the server

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#146]
Hi!

we have some weird issues in our system.
**Scenario**
Users get a task and once they compete it, they are to flag them as completed and then synchronize so the server gets the status update as well.

**Problem**
the sync never gives us any errors but sometimes (very rarely - like once in a week) one to two tasks are marked as completed on the client, but are still new on the server.
Even though we did a fresh sync.
Now we went through the code and it is impossible that this is due to a sync conflit: There are no foreign key constraints that could be violated, nor is there any way the task could have changed on the server.

**Solution**
So I am having this weird feeling, that there may be an issue with the timestamp handling on the client side. I am currently investigating and try to do a PR if I find an issue.

However, I do not completely understand the select changed query on sqlite. Could you please explain it a little more?
I took the query form the integration tests sample.
```
SELECT 	[side].[ServiceTicketID], 
	[base].[Title], 
	[base].[Description], 
	[base].[StatusValue], 
	[base].[EscalationLevel], 
	[base].[Opened], 
	[base].[Closed], 
	[base].[CustomerID], 
	[side].[sync_row_is_tombstone], 
	[side].[create_scope_id], 
	[side].[create_timestamp], 
	[side].[update_scope_id], 
	[side].[update_timestamp] 
FROM [ServiceTickets_tracking] [side]
LEFT JOIN [ServiceTickets] [base]
ON [base].[ServiceTicketID] = [side].[ServiceTicketID]
WHERE (
	-- Update made by the local instance
	[side].[update_scope_id] IS NULL
	-- Or Update different from remote
        -- isn't the local scope always null?
	OR [side].[update_scope_id] <> @sync_scope_id
	-- Or we are in reinit mode so we take rows even thoses updated by the scope
        -- if we reinit, shouldn't we send everything to the server?
       -- because this way, the change is still only sent if the other two clause-groups apply
      -- meaning the row must be newer than the remove timestamp
	OR @sync_scope_is_reinit = 1
    )
AND (
	-- And Timestamp is > from remote timestamp
	[side].[timestamp] > @sync_min_timestamp --int64
	OR
	-- remote instance is new, so we don't take the last timestamp
-- what is remote here? SQLIte, or do you mean the remote MSSQL Server
	@sync_scope_is_new = 1
	)
AND (
 -- i assume this means that we send changes
 -- if this is a deleted row
-- or the row is not deleted, and there actually exists the original row in the tracked table
-- (which causes this to be ignored if the row was not deleted but is not present? Does that make sense at all?)
	[side].[sync_row_is_tombstone] = 1 
	OR
	([side].[sync_row_is_tombstone] = 0 AND [base].[ServiceTicketID] is not null	)
)

```

Please enlighten me if you find a minute or two :-)

**Comment by gentledepp** [comment]
@Mimetis it seems I found a **critical** **bug** in Dotmim.Sync that can cause changes to be "forgotten" by either the client or the server side ☹

I will try to pinpoint it and hope that you can clarify that I am right, and I can fix this asap.

The SyncAgent uses the following flow:

##sync agent

1) get local changes at t1
2) get local timestamp "right after" at t2

3) get remote changes at t3
4) get remote timestamp "right after" at t4

Now in a typical concurrent system, on both, cliend and serverside, the following can happen:

1) get local changes at t1
1b) some row is added/udated/deleted at t1a
2) get local timestamp "right after" at t2

=> therefore a local change at t1a can be forgotten! I.e. the client will *never* send it to the server. (this is what we see in our production environtment unfortunately)

The same applies to the remove part:
3) get remote changes at t3
3b) some row is added/updated/deleted at t3a on the server
4) get remote timestamp "right after" at t4

In this case the risk is even higher, because between 3 and 4, http messages are sent which might take a considerable amount of time! 
We will try to change this to  the following to mitigate this issue:


1) get local timestamp "right after" at t1
2) get local changes at t2

3) get remote timestamp "right after" at t3
4) get remote changes at t4

This has the following advantage:
 - no data is ever "forgotten" in the sync process
the disadvantage clearly is, that some data may be sent twice (or even more often)

A clean fix would therefore be the following:

1) get local timestamp at t1
2) get local changes from last_sync_timestamp to t1

3) get changes **and** remote timestamp in one call from server
   on the server side the provider
    - gets the current timestamp at t3
    - queries all changes from sync_min_timestamp until t3
    - then send back the canges along with the timestamp t3 as the response.

This would have the following benefits:
 - no data is ever forgotten
 - no data is synced twice
 - and we spare one request roundtrip - which is always a good thing as there is always quite some delay between request and response and the more you got, the unnecessarily longer takes the sync process


Do you agree?

**Comment by Mimetis** [comment]
Thanks @gentledepp  for opening this issue.  
I see you tried something on your fork ?   
Can you make a PR ?   
Or do we need more investigation ?

**Comment by gentledepp** [comment]
I would like to hear your opinion on this matter first.
1) do you think I may be right?
2) what happens, if we send the **same** changes twice to the server? (which might happen with our quickfix)
3 what happens, if we get the **same** changes twice on the client? (which might happen with our quickfix)

Thanks!

**Comment by Mimetis** [comment]
I'm in the middle of a big customer meeting, so I will look into it, maybe at the end of the week

**Comment by lordofffarm** [comment]
Related?
https://github.com/Mimetis/Dotmim.Sync/issues/117

**Comment by gentledepp** [comment]
yeah it is exactly the same code that I changed to fix it.
Seems our issue is, that  we are running on a fork of dotmim.sync.

You can close this then!
