### ISSUE TITLE
Stored Procedures not generated in Azure SQL Server

### ISSUE THREAD

**Issue by ralph-fuechtenkort** [Mimetis/Dotmim.Sync#147]
Good Morning,
I have a web server project set up at azure for the server side of the dotmim synchronisation.
On the client side - for testing purposes - i just use the console app. 
on running this i receive an error that the ...change procedure could not be found.
Checking shows that the SP is generated on the client database (SQL Server too) but NOT at the Azure Database.
There actually just ONE set of SP (for one table) is generated not for the rest (another 6 tables in list).
If i try the same with another local Database on my machine, it works fine.

**Comment by Mimetis** [comment]
Hello @ralph-fuechtenkort 
Can you share you database schema with us ? (maybe just one table that is not actually working on azure)
