### ISSUE TITLE
Question: How can I customize the conversion of data types?

### ISSUE THREAD

**Issue by staterium** [Mimetis/Dotmim.Sync#149]
Hi, is it possible to change how the sync provider stores data in client DB? I want to receive DateTimeOffset from server, and store as Ticks (int64) on client. Reason is that PCL SqlLite client wrapper stores datetimeoffset as ticks, so any records added on client looks different to sync provider.

**Comment by Mimetis** [comment]
I think about implementing this kind of service, for a next version.   
If you have any idea, we can discuss about it !

**Comment by Mimetis** [comment]
See documentation here https://mimetis.github.io/Dotmim.Sync/SerializerConverter
