### ISSUE TITLE
Reserved words are not supported

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#15]
Hello Sébastien,
I have done some tests with my databases and discovered, that fieldnames like 
[File], [Read], [From] [To], [Document] are not supported.

Is this by design or will you enhance to support these fieldnames too?

Thanks
Reinhold

**Comment by Mimetis** [comment]
I've made a correction.
Can you make a test with the latest version (0.1.3) ?
You can clone this repo or you can make an update from nuget as well.

If you have the bug again, can you post your database schema , as a sample ?

**Comment by thefonzi** [comment]
Hello,
i have included a complete sample and my test database. 
Please note: I'm using DevExpress XPO/XAF to generate database and the included database is at 90% generated by a standard XAF project. I have then added a few tables, that cause problems with the sync. 
Please have a look at the SyncServer sample. I generate table list to sync in dependency order and then exclude some of the tables. You will find a comment above every exclusion related to the reason. (PopulateSyncTables).

Maybe I would be handy to integrate the possiblility to get table list without opening a separate sqlConnection. What do you think?

Thanks
Reinhold
[SyncServer.zip](https://github.com/Mimetis/Dotmim.Sync/files/1465972/SyncServer.zip)

**Comment by Mimetis** [comment]
Hi;

With the latest version, the tables `Event`, `Resource`, `ResourceResources_EventEvents` and `C4File` should work

Please notice that :
* Reserved keywords as 'Event', 'From', 'Read' and so on, should work with last version
* Circular references does not work
* One field table (only the primary key, your `C4Report` table) does not work

**Comment by thefonzi** [comment]
I have cloned the current repository (3min ago) but, commenting out C4File and/or Resource produces: 

Error occured during SelectingChanges of type Unknown: Unknown error has occured

**Comment by thefonzi** [comment]
For your help. These are the detailed relations: 
![involvedrelations](https://user-images.githubusercontent.com/6755910/32717939-c503438c-c85b-11e7-89be-1f372ad8eac6.PNG)

**Comment by Mimetis** [comment]
I don't have any datas on my sample, based on your schema.

What I've done here as worked for me (at least sync schema initialization):

```
       SyncConfiguration configuration = new SyncConfiguration(new string[] {
        "Analysis", "Event", "FileData", "HCategory", "ModelDifference", "PermissionPolicyUser",
        "Resource", "XPObjectType", "C4File", "ModelDifferenceAspect", "PermissionPolicyRole",
        "ReportDataV2", "ResourceResources_EventEvents", 
        "PermissionPolicyNavigationPermissionsObject", "PermissionPolicyTypePermissionsObject",
        "PermissionPolicyUserUsers_PermissionPolicyRoleRoles", "PermissionPolicyMemberPermissionsObject",
        "PermissionPolicyObjectPermissionsObject"});

```

**Comment by Mimetis** [comment]
To go further, I need more détails on your error, or maybe a backup (without sensitive datas) of your database

**Comment by thefonzi** [comment]
Attached you find the backup of the database as bak from MSSQL-Server 2014 (12.0.4237). 
The data in the database are a sort of initial data after creation of the database and populating with some basic user data.

you just need to start the project, I attached above "SyncServer" and comment out the lines of the exclusion list block by block and you will get the error I have pasted.

[DotminXAF.zip](https://github.com/Mimetis/Dotmim.Sync/files/1466259/DotminXAF.zip)

**Comment by Mimetis** [comment]
Your backup is working for me but :

* From your backup, you have to delete the `scope_info` table, before making another test
* I made a test (with the configuration I mentioned) and it worked on my machine, but your backup does not have any datas :(

**Comment by thefonzi** [comment]
Sorry, did not know, the scope was to delete.
Let me populate the db and do some test.
Will let you know soon

**Comment by Mimetis** [comment]
Nice !
Since your last question is not about reserved key words, I will close it :)
Will take a look on your double reference issue (maybe you should open a new issue with a simple example ? )
