### ISSUE TITLE
Error when modify or add new field in server database

### ISSUE THREAD

**Issue by aliebrahimi2015** [Mimetis/Dotmim.Sync#152]
hi
when I add new or  modify the field on tables of server database
exceptin throw and error
how to reset options client and server database (triggers , stored procedurs,scope_info,tracking and ....)?
how to fix this error?
thanks

**Comment by Mimetis** [comment]
The best way to do that, is to use `Provision` and `Deprovision` methods

See the doc here : https://mimetis.github.io/Dotmim.Sync/Provision
