### ISSUE TITLE
Filter Not work

### ISSUE THREAD

**Issue by aliebrahimi2015** [Mimetis/Dotmim.Sync#153]
I want to filter by DateCreated
Only the DateCreated =today to sync
but not work

` SqlSyncProvider serverProvider = new SqlSyncProvider(
    @"Data Source=.\SQLEXPRESS;Initial Catalog=DBServer;Integrated Security=true;MultipleActiveResultSets=true;");

            // Sqlite Client provider for a Sql Server <=> Sqlite sync
           string path = Directory.GetCurrentDirectory() + @"\DB2.sqlite";
            SqliteSyncProvider clientProvider = new SqliteSyncProvider(path);

            // Tables involved in the sync process:
                               
            var tables = new string[] {"T1"};
            // Sync orchestrator
            serverProvider.SetConfiguration(c => c.Filters.Add("T1", "DateCreated", DbType.Date));
            SyncAgent agent = new SyncAgent(clientProvider, serverProvider, tables);

            var p = new SyncParameter("T1", "DateCreated", DateTime.Now.Date);
            agent.Parameters.Add(p);
           
            await agent.SynchronizeAsync();`

**Comment by Mimetis** [comment]
It could not work, because the filter works on a value *existing* in the table.
AND the filter value should always be the same value.

Datetime.Now is not deterministic.
