### ISSUE TITLE
[Enhancement] Improve JSON (de)serialization performance

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#154]
I just saw that the `JsonConverter` is implemented in an non-optimal manner: by first deserializing the json stream into a string and then parsing the string.
This creates quite a GC overhead which is bad for both, the ASP.NET webserver and Xamarin apps, as these are quire memory constrainted.

Especially on Xamarin.Andoid, the garbage collector is very slow.
NewtonSoft Json has its own article since version 5 about this topic "optimizing memory usage": https://www.newtonsoft.com/json/help/html/Performance.htm 

Moreover, you do not dispose the MemoryStream at all! So this is quite some serious **memory leak**

Our approach:
```
    using Newtonsoft.Json;
    using System.IO;
    
    namespace Dotmim.Sync.Serialization
    {
        public class JsonConverter<T> : BaseConverter<T>
        {
            public override T Deserialize(Stream ms)
            {
                using (StreamReader sr = new StreamReader(ms))
                using (JsonReader reader = new JsonTextReader(sr))
                {
                    JsonSerializer serializer = new JsonSerializer();
                    return serializer.Deserialize<T>(reader);
                }
            }
    
            public override void Serialize(T obj, Stream ms)
            {
                using (var writer = new StreamWriter(ms))
                using (var jsonWriter = new JsonTextWriter(writer))
                {
                    var serializer = new JsonSerializer();
                    serializer.Serialize(jsonWriter, obj);
                }
            }
    
            public override byte[] Serialize(T obj)
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    Serialize(obj, ms);
                    return ms.ToArray();
                }
            }
        }
    }

```

**Comment by Mimetis** [comment]
hey @gentledepp .
Thanks for raising this weird perf issue :)
It's fixed in this commit: https://github.com/Mimetis/Dotmim.Sync/commit/bce216f7ce3f88f1bf8b6973a273bed323b25367

Thanks a lot, really appreciate your investigations !

Seb
