### ISSUE TITLE
[Bug] - Deletion does not take foreign key constraints into account

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#156]
As of now, all tables are synced in the order that is provided in the sync configuration.

Let's assume we have two tables: 
- Order
- OrderDetail

Now OrderDetail has a foreign key which points to Order.
For that reason, we have to configure the sync as such, that the Order table is synchronized first, and the OrderDetail table thereafter.
Otherwise, it could happen that the sync process tries to insert an OrderDetail for an Order which does not exist in the local database yet.

So far so good. According to the current implementation, each sync process goes as follows:
For each table:
1. insert all new rows
2. update all changed rows
3. delete all tombstoned rows

This brings us to the following problem.
Let's assume, that we delete an Order and the OrderDetail that references it.
What happens is
For the Order table:
1. all new rows are inserted
2. all changed rows are updated
3. the database refuses to delete the Order, because the OrderDetail is still referencing it (it has not been deleted yet)

So what should happen is:
For each table:
1. insert all new rows
2. update all changed rows

When that is done, go through all tables again **in reverse order** and delete the tombstoned rows.

**Comment by Mimetis** [comment]
We already reached this issue in #143 
The fact is that you will always find a situation where the order is not the good one (as explained in #143 )   
The only way to resolve it, is to disable the constraints. 

This behavior has been implemented in the last version, this commit : https://github.com/Mimetis/Dotmim.Sync/commit/77925d3ec8cc176bfff567433204d8fb7a209953
