### ISSUE TITLE
Mysql Sync Provider date type not supported?

### ISSUE THREAD

**Issue by krvrian** [Mimetis/Dotmim.Sync#157]
i'm trying to sync between mysql and sqlite, but there's a error stating that "The Column check_in_date of type date from provider MySqlSyncProvider, Dotmim.Sync.MySql.MySqlSyncProvider is not currently supported.", how can i fix that?

**Comment by Mimetis** [comment]
Hello @krvrian . Can you provide a simple repro ?
Let's say, just the table structure, it should be enough to make a quick test 

Sebastien

**Comment by Mimetis** [comment]
Oh I think I get it.  
It seems we had a small bug in the `IsValid` method in the `MySqlProvider`...

I've just made a quick fix on the master branch.  Can you test it and get back to me with the result ?

See here : https://github.com/Mimetis/Dotmim.Sync/blob/047d856d77831ff5412adeb10bcbf7a6929b2db4/Projects/Dotmim.Sync.MySql/Builders/MySqlDbMetadata.cs#L473-L474 

Seb

**Comment by krvrian** [comment]
sorry for the delay! thanks for the fix, i'll be back in 2 days to post the result! good to hear that my issue has been responded
