### ISSUE TITLE
SQLite Error 19: 'FOREIGN KEY constraint failed'.. Type:Data.

### ISSUE THREAD

**Issue by pulsegroupb2b** [Mimetis/Dotmim.Sync#158]
We are trying to get this great sync package up and running between our sqlite clients and an azure sql server. We are getting the above error when we try and Sync.
`BeginSession:   
ScopeLoading:   Id:f733ba42-3aca-458b-b05c-e4b30680b323 LastSync: LastSyncDuration:0 SyncState:Successful
SchemaApplied:  Tables count:8
DatabaseTableApplied:   TableName: ScanData Provision:All
DatabaseTableApplied:   TableName: Exams Provision:All
DatabaseTableApplied:   TableName: PracticeSettings Provision:All
DatabaseTableApplied:   TableName: Scans Provision:All
DatabaseTableApplied:   TableName: AspNetUsers Provision:All
DatabaseTableApplied:   TableName: Locations Provision:All
DatabaseTableApplied:   TableName: Patients Provision:All
DatabaseApplied:        TableName: Practices Provision:All
DatabaseApplied:        Tables count:175 Provision:All
TableChangesSelected:   Practices Inserts:0 Updates:0 Deletes:0 TotalChanges:0
TableChangesSelected:   AspNetUsers Inserts:0 Updates:0 Deletes:0 TotalChanges:0
TableChangesSelected:   Exams Inserts:0 Updates:0 Deletes:0 TotalChanges:0
TableChangesSelected:   Locations Inserts:0 Updates:0 Deletes:0 TotalChanges:0
TableChangesSelected:   Patients Inserts:0 Updates:0 Deletes:0 TotalChanges:0
TableChangesSelected:   PracticeSettings Inserts:0 Updates:0 Deletes:0 TotalChanges:0
TableChangesSelected:   ScanData Inserts:0 Updates:0 Deletes:0 TotalChanges:0
TableChangesSelected:   Scans Inserts:0 Updates:0 Deletes:0 TotalChanges:0
TableChangesApplied:    Practices State:Added Applied:1 Failed:0
TableChangesApplied:    AspNetUsers State:Added Applied:11 Failed:0
Sync Exception: SQLite Error 19: 'FOREIGN KEY constraint failed'.. Type:Data.`
I attached a diagram of the azure db.

`_clientProvider = new SqliteSyncProvider("box.db");
 _proxyClientProvider = new WebProxyClientProvider(new Uri(_configuration["ClaWebApiServer"] + "/sync/post"));
var progress = new Progress<ProgressArgs>(s => Console.WriteLine($"{s.Context.SyncStage}:\t{s.Message}"));
var result = await _agent.SynchronizeAsync(progress);
 _logger.LogInformation($"[SyncService] Sync Result {result}");`

[ClaSql.pdf](https://github.com/Mimetis/Dotmim.Sync/files/3414131/ClaSql.pdf)

**Comment by pulsegroupb2b** [comment]
I found it to be an issue with the order of the tables I was syncing. Once I adjusted the table order to be sure the foreign keys would exist, it worked correctly

**Comment by Mimetis** [comment]
great you found your issue :) !!

**Comment by akema-trebla** [comment]
Hi I recently updated my nuget package version to 0.8 from 0.6 and now I'm getting this error.

Seems to fail on a table with a custom where filter.

Help needed.

**Comment by Mimetis** [comment]
Did you tried to use `DisableConstraintsOnApplyChanges` options (set to `true` ) ?

**Comment by akema-trebla** [comment]
Just tried it on the client side and it worked. Thanks. 

Is the sync order set according to the order of tables listed in the sync setup?

**Comment by Mimetis** [comment]
Order can be important if you decide to not use `DisableConstraintsOnApplyChanges` 
Not using `DisableConstraintsOnApplyChanges` can have some benefits on the perfomances if you are dealing with big tables

Just make some tests, and you will see, I guess
