### ISSUE TITLE
[Question]  insert new data from the client into server database on ID conflict

### ISSUE THREAD

**Issue by asanchez128** [Mimetis/Dotmim.Sync#159]
First of all, congrats on your awesome framework. 

I am working on syncing a legacy web app with a mobile app.  Changing the IDs to GUIDs is not an option as the legacy app is closed. So I have to work with integer IDs in both places (server and client). The one issue that I'm facing, though, is that sometimes the client and the server could create a new entity with the same ID. At the time of conflict, with the default configuration, the server wins and the changes from the client get lost. 

So I was picturing a solution in which a new record is inserted into the server table if the client and the server have the same integer ID. Right after, the new ID generated on the server is replaced on the client. However, I did not get very far. Debugging the code, I noticed that the logic to handle  conflicts is found in the HandleConflictAsync method on the CoreProvider.ApplyChanges class. According to the code, only if the update is not successful, an insert will take place.
`isUpdated = syncAdapter.ApplyUpdate(row, scope, true);

                        if (!isUpdated)
                        {
                            // Insert the row
                            isInserted = syncAdapter.ApplyInsert(row, scope, true);`

Could you please give me some pointers as to how to implement that feature.

Another solution that I explored was to create a LocalId field on each entity in the client and to set the Id as a nullable. However, the fields with null IDs don't get added to the tracking tables. The behavior that I would like would be as follows:

If ID on client is NULL
    insert data into server and send back to client the new ID that was created on server.

I know the schemas have to match. However, the fact that the ID is set to nullable on the client doesn't seem to bother Dotmim.Sync. Thank you for your share of expertise on this one.

**Comment by Mimetis** [comment]
The only way to work with Identity columns as Primary keys is to define range of ids.

For instance, you can define something like that:
- Server IDS range: 1 -  99 999 999
- Client 1 IDS range:  100 000 000 - 100 999 999
- Client 2 IDS range:  101 000 000 - 101 999 999
- Client 3 IDS range:  102 000 000 - 102 999 999

You can store these values in any configuration table.   
When you reach the limit for one client (or server), just change the range for a new one.

It's this method that use SQL Server merge fusion, internally
Some useful links:
- https://docs.microsoft.com/en-us/sql/relational-databases/replication/publish/replicate-identity-columns?view=sql-server-2017
- https://www.mssqltips.com/sqlservertip/6093/sql-server-merge-replication-identity-range-management/

**Comment by asanchez128** [comment]
Thank you @Mimetis for your kind reply. I also ran into an article that describes a possible solution: https://jtabadero.wordpress.com/2011/03/14/upload-synchronization-where-the-client-and-server-primary-keys-are-different/ . I didn't implement it, though. I just wanted to add my two cents to this conversation.
