### ISSUE TITLE
Sqlite Encryption

### ISSUE THREAD

**Issue by dgrothman** [Mimetis/Dotmim.Sync#161]
I have encryption working on a sqlite database, but how do I pass the connection to the SyncAgent?

````
var db = "box.db";
var conn = new SQLiteConnection($"Data Source={db};");
// Open connection to allow encryption
conn.Open();
var cmd = conn.CreateCommand();
var password = _configuration["SqlPassword"];
// Prevent SQL Injection
cmd.CommandText = "SELECT quote($password);";
cmd.Parameters.AddWithValue("$password", password);
var quotedPassword = (string)cmd.ExecuteScalar();
// Encrypt database
cmd.CommandText = "PRAGMA key = " + quotedPassword;
cmd.Parameters.Clear();
cmd.ExecuteNonQuery();
// Now pass it to db context for use
_agent = new SyncAgent(_clientProvider,_proxyClientProvider);
````

**Comment by Mimetis** [comment]
Hey @dgrothman 
I have just pushed a new commit that could actually help you on this.
I have added a new couple of `Interceptors` called `OnConnectionOpen` and `OnConnectionClose`.

These interceptors are called every time a connection is opened (or closed)

Not sure if it's everything you need so far, but can you try something like this:

```
        sqliteProvider.InterceptConnectionOpen(args =>
        {
            var cmd = args.Connection.CreateCommand();
            cmd.CommandText = "Something";
            cmd.ExecuteNonQuery();
        });

```

**Comment by pulsegroupb2b** [comment]
Great I will pull that and build it and let you know, sounds like its exactly what I need. Thanks!

**Comment by pulsegroupb2b** [comment]
Hey @Mimetis 
I have built from source and have the packages in the project, but the interceptor is not triggering before the SyncService fails with an error of "[12:45:11 ERR] [SyncService] Error during sync: SQLite Error 26: 'file is not a database'". I have verified I can open the box.db file with https://sqlitebrowser.org/ using cypher version 3 and the password "p@ssw0rd".
I have updated the github repo with my latest files 
https://github.com/pulsegroupb2b/dotmim-sqlite

**Comment by Mimetis** [comment]
I use `Microsoft.Data.SQLite` for SQLite queries   
Does it work "as is" with SQLite Cypher db ?

**Comment by pulsegroupb2b** [comment]
yes, I am opening the box.db file in the Startup.cs file using Microsoft.Data.SQLite without issue.

**Comment by Mimetis** [comment]
Which package do you use for Cypher ?

**Comment by pulsegroupb2b** [comment]
SQLitePCLRaw.bundle_sqlcipher
I followed this blog:
https://www.bricelam.net/2016/06/13/sqlite-encryption.html

**Comment by Mimetis** [comment]
Ok, got it.   
It seems the encryption command needs to be set after connection is opened and before any transaction is created.   
I've updated the code base to allow the interceptor right after a connection is opened.  
Then I've created 2 new interceptors for transactions (Created and Commited)  

I'm sorry, I'm in vacations and I can't do in depth tests. Can you test it on your own and make a feedback here if anything goes wrong ?

Thx

**Comment by Mimetis** [comment]
right commit : https://github.com/Mimetis/Dotmim.Sync/commit/a2d481e88560e4c47a596eaa7ef76723ebc81398

**Comment by dgrothman** [comment]
That was it, works flawlessly! Thank you so much!

**Comment by Mimetis** [comment]
I have added the tests here https://github.com/Mimetis/Dotmim.Sync/blob/master/Tests/Dotmim.Sync.Tests/Sqlite/SqliteEncryptedTests.cs

**Comment by gaurakshay** [comment]
Just in case this is useful to somebody, with the latest Microsoft.Data.Sqlite packages, we can pass the password directly:

```
var serverOrchestrator = new WebClientOrchestrator(<SYNCURL>);
var sqliteConnStrBuilder = new SqliteConnectionStringBuilder()
  {
      DataSource = <PathToDB>,
      Password = <Password>
  };
var clientProvider = new SqliteSyncProvider(sqliteConnStrBuilder);
var agent = new SyncAgent(clientProvider, serverOrchestrator);
var s1 = await agent.SynchronizeAsync();
Console.WriteLine(s1);
```
