### ISSUE TITLE
Interceptor Usage

### ISSUE THREAD

**Issue by pulsegroupb2b** [Mimetis/Dotmim.Sync#162]
I am using the latest 3.0 verison of Dotmim and the SyncAgent class doesn't seem to have access to the interceptors shown in the documentation. The closest thing I could find inside the class is a SetInterceptor function, but I am not sure how to use it correctly. I would like to try and intercept the connection of the SyncAgent to the localprovider to allow me to add encryption to the sqlite connection.

**Comment by gb0o** [comment]
I think the interceptor implementation is in master but not yet published as a package.

**Comment by Mimetis** [comment]
Hey @pulsegroupb2b .
As @gb0o mentionned, the `Interceptors` methods are not published yet.
Can you try with the source code ?

**Comment by pulsegroupb2b** [comment]
building from source does include the Interceptors as documented. Thank you
