### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by mingyangzhu** [Mimetis/Dotmim.Sync#164]
hi, @Mimetis ：
can you issue this project roadmap? thanks!!!

**Comment by mingyangzhu** [comment]
version 1.0 publish date.

**Comment by Mimetis** [comment]
No roadmap defined yet.
Why do you need the v 1.0 publish date ?
Even if I publish a potential v 1.0, it is still an OSS project, with no warranty.

**Comment by mingyangzhu** [comment]
ok ,i kown. thank you for your reply.this tool is  awesome.I will try to use it for production.
