### ISSUE TITLE
Sqlite Encryption not working

### ISSUE THREAD

**Issue by abunoman2003** [Mimetis/Dotmim.Sync#167]
@Mimetis 
Hello,
I have tested that sqlite encryption not working. The Database can be accessed without password/encryption key which is set using PRAGMA Key.

Any Help appreciated

**Comment by Mimetis** [comment]
Can you provide a simple repro ?

**Comment by Mimetis** [comment]
It should be resolved now.
Please take a look here : https://github.com/Mimetis/Dotmim.Sync/issues/161
