### ISSUE TITLE
[Proposal] Enhance ConnectionString parsing of SQLiteSyncProvider to support Journal Mode=WAL

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#17]
Hi,
actually, adding for example a ";" at the end of SQLite ConnectionString produces a database file like: TestDB.db; 
Could this be parsed by using "Data Source=TestDB.db; Journal Mode=WAL;" 
It is actually possible activating Journal Mode=WAL, adding this line in SQLiteSyncProvider.cs: 
builder.JournalMode = SQLiteJournalModeEnum.Wal;

Maybe it is possible to read this setting from ConnectionString

**Comment by thefonzi** [comment]
Should be enough to change this code. I have tested.

public SQLiteSyncProvider(string filePath) : base()
        {
            this.filePath = filePath;
            var builder = new SQLiteConnectionStringBuilder(); // { DataSource = filePath };
            builder.ConnectionString = filePath;
            // prefer to store guid in text
            builder.BinaryGUID = false;            
            
            this.ConnectionString = builder.ConnectionString;
        }

**Comment by thefonzi** [comment]
if you make the change indicated above (builder.ConnectionString=filepath), the passed connectionstring for SQLite can look like this:
"Data Source=D:\database\myData.db;Journal Mode=WAL;Page Size=8192" or similar. 

Please apply this change.

**Comment by Mimetis** [comment]
Here is my suggestion :  

First of all, adding a method to be able to construct your ConnectionString through a nice object builder, `SQLiteConnectionStringBuilder `:

```
       public SQLiteSyncProvider(SQLiteConnectionStringBuilder sQLiteConnectionStringBuilder) : base()
        {
            if (String.IsNullOrEmpty(sQLiteConnectionStringBuilder.DataSource))
                throw new Exception("You have to provide at least a DataSource property to be able to connect to your SQlite database.");

            // prefer to store guid in text
            sQLiteConnectionStringBuilder.BinaryGUID = false;

            this.ConnectionString = sQLiteConnectionStringBuilder.ConnectionString;
        }
```

For your need, I will also modify the initial constructor like this:

```
        public SQLiteSyncProvider(string filePath) : base()
        {
            this.filePath = filePath;
            var builder = new SQLiteConnectionStringBuilder();

            if (filePath.ToLowerInvariant().StartsWith("data source"))
            {
                builder.ConnectionString = filePath;
            }
            else
            {
                var fileInfo = new FileInfo(filePath);

                if (!Directory.Exists(fileInfo.Directory.FullName))
                    throw new Exception($"filePath directory {fileInfo.Directory.FullName} does not exists.");

                if (string.IsNullOrEmpty(fileInfo.Name))
                    throw new Exception($"SQLite database file path needs a file name");

                builder.DataSource = filePath;
            }

            // prefer to store guid in text
            builder.BinaryGUID = false;
            this.ConnectionString = builder.ConnectionString;
        }
```

Like that, I keep the descendant compatibility :)

Is it make sense for you ?

**Comment by thefonzi** [comment]
Perfect!
