### ISSUE TITLE
Commit overwrite

### ISSUE THREAD

**Issue by lordofffarm** [Mimetis/Dotmim.Sync#171]
I think the last commit 859b2345a75ca7e1832d212864d3c4dc61b6ae23
might have overwritten some previous commits.
For example, changes from the PR https://github.com/Mimetis/Dotmim.Sync/pull/169 are currently not in the master branch.

**Comment by lordofffarm** [comment]
When was branch Mimetis-ConfigureAwait-False checked out?
Cause, other commits might have been overwritten as well...

**Comment by Mimetis** [comment]
oh god ... I've made this PR yesterday at the airport.
I've probably made a mistake ...

**Comment by Mimetis** [comment]
Ok, I `reset --hard` to the last PR #169 

I will make a new PR for the `ConfigureAwait(false)` feature :)

**Comment by Mimetis** [comment]
Thx @lordofffarm to raise this point, I really did not see anything !!!

**Comment by lordofffarm** [comment]
All good, sir) thank you for your work
