### ISSUE TITLE
How to clear the sync link from server database to client database?

### ISSUE THREAD

**Issue by kevincheng201903** [Mimetis/Dotmim.Sync#172]
How to clear the sync link from server database to client database?

I have two sql server databases, 1) the first time I created a sync job from server to client, it worked very well, 2) but some guy told me he wanted to add more tables into client database, and hoped to sync back to the  server database, 3) this time I just add new tables name into the job, It didnot work.

**My question is that Could we clear the old sync  and rebuild a new sync between these two database?**

**Comment by Mimetis** [comment]
When you are modifying the schema of your databases, you have to recreated the whole thing.

The best way to do it, is to `Deprovision` then to `Provision` again you dbs.

Look this doc  : https://mimetis.github.io/Dotmim.Sync/Provision
