### ISSUE TITLE
Issues keeping "read-only" copies of tables in sync

### ISSUE THREAD

**Issue by jeremykieley** [Mimetis/Dotmim.Sync#173]
### Use case

I have multiple tables where I want the client tables to just be exact copies of the server tables. I'm not able to have a direct connection between the databases so I'm trying to accomplish it through an ASP.NET Core API with this library. The only code that should be modifying these tables on the client is the sync feature.

If I could sync with `SyncType.Reinitialize` every time it would probably work, but I can't because it's too costly, both from a performance and data usage standpoint. So I was hoping to accomplish the same result with `SyncType.Normal` but I'm running into issues.

### Configuration details

- The tables all use `SyncDirection.DownloadOnly`
- The conflict resolution is `ServerWins`
- The sync uses `SyncType.Normal`
- The sync is being done through a web service so the `SyncAgent` is using `SqlSyncProvider` for the client and `WebProxyClientProvider` for the server. Both databases are SQL Server.
- I'm creating my own `DmTable` configurations so I can specify a subset of columns for each table. For example:

```csharp
services.AddSyncServer<SqlSyncProvider>(Configuration.GetConnectionString("Db"), configuration =>
{
    var table = new DmTable("MyTable") { Schema = "dbo", SyncDirection = SyncDirection.DownloadOnly };
    table.Columns.Add(new DmColumn<int>("Id"));
    table.Columns.Add(new DmColumn<string>("SomeValue") { DbType = DbType.AnsiStringFixedLength, MaxLength = 30 });
    table.PrimaryKey = new DmKey(table.Columns[0]);

    configuration.Add(table);

    var table2 = new DmTable("MyTable2") {Schema = "dbo", SyncDirection = SyncDirection.DownloadOnly};
    table2.Columns.Add(new DmColumn<int>("Id1"));
    table2.Columns.Add(new DmColumn<int>("Id2"));
    table2.Columns.Add(new DmColumn<bool>("SomeFlag"));
    table2.PrimaryKey = new DmKey(new[] {table2.Columns[0], table2.Columns[1]});

    configuration.Add(table2);

    // etc
});
```

I'm using the latest master branch at the time of writing this ([Oct 8 commit](https://github.com/Mimetis/Dotmim.Sync/tree/40b11e705484d86f4d21a6b212c180d569306110)).

### Issues

Take this scenario

1. Delete 1 or more rows on the server
2. Sync changes (this successfully deletes them on the client)
3. Add back in the deleted row(s) on the server
4. Sync changes (this doesn't add them back on the client)
5. Sync again (doesn't detect any changes, so the row(s) stay missing)

From what I can tell, the change from step 3 is detected and is treated as an update in step 4. Since the row is missing on the client the update query doesn't do anything. This is recorded as a conflict and I believe it attempts an `ApplyAction.RetryWithForceWrite` but that doesn't insert the row and it shows 1 for `TotalSyncConflicts` and 0 for everything else.

Then on subsequent syncs (ie: step 5), it doesn't detect any changes and the `SyncContext` shows 0 for `TotalChangesDownloaded`, `TotalChangesUploaded`, `TotalSyncConflicts`, and `TotalSyncErrors`. So even though it wasn't able to add the row in step 4, it no longer detects that the databases aren't in sync anymore.

- Is there any way to configure it so that an insert query will do an update if the row already exists and an update query will do an insert if the row doesn't exist?
- Is there a way to configure it so that the metadata doesn't change if there's a sync error/conflict so the changes will be detected/retried on subsequent syncs?

**Comment by Mimetis** [comment]
Hello @jeremykieley.

Thanks a lot for raising the issue ! 
I've found the issue and it will be corrected in the next version.  
Until then, you can *manually* resolve the issue.   
The problems come from the stored procedure `sTable_Insert` and the trigger `Table_insert_trigger`.

Here is the *before* and *after* version:

*Let's imagine we work on a `Product` table:*

**trigger `Product_insert_trigger` before**:
``` sql
UPDATE [side] 
SET 	[sync_row_is_tombstone] = 0
	,[update_scope_id] = NULL -- since the update if from local, it's a NULL
	,[last_change_datetime] = GetUtcDate()
FROM [tProduct] [side]
JOIN INSERTED AS [i] ON [side].[ID] = [i].[ID]

INSERT INTO [tProduct] (
... bla bla bla...

```

**trigger after correction:**
``` sql
UPDATE [side] 
SET 	[sync_row_is_tombstone] = 0
	,[update_scope_id] = NULL -- since the update if from local, it's a NULL
	,[update_timestamp]=@@DBTS+1
	,[last_change_datetime] = GetUtcDate()
FROM [tProduct] [side]
JOIN INSERTED AS [i] ON [side].[ID] = [i].[ID]

INSERT INTO [tProduct] (
... bla bla bla...
```
As you can see, we miss to update the `	,[update_timestamp]` column in the tracking table.

**stored procedure `sProduct_Insert` before:**

``` sql
ALTER PROCEDURE [dbo].[sProduct_insert]
	@ID uniqueidentifier,
	@Name varchar(50),
	@sync_row_count int OUTPUT
AS
BEGIN
SET @sync_row_count = 0;
IF NOT EXISTS (SELECT * FROM [tProduct] WHERE [ID] = @ID) 
BEGIN 
	INSERT INTO [Product]
	([ID], [Name])
	VALUES (@ID, @Name);

	SET @sync_row_count = @@rowcount; 
END 

END
```

**stored procedure after:**

```sql
ALTER PROCEDURE [dbo].[sProduct_insert]
	@ID uniqueidentifier,
	@Name varchar(50),
	@sync_row_count int OUTPUT
AS
BEGIN

	SET @sync_row_count = 0;
	INSERT INTO [Product]
	([ID], [Name])
	VALUES (@ID, @Name);

	SET @sync_row_count = @@rowcount; 

END
```
As you can see, the condition `IF` is not needed (it's an historical condition, from a really first version of `Dotmim.Sync`, but it's not needed now)

I will update the `master` branch with the correct generation code as soon as possible.
You can correct the stored procedures and triggers manually, or wait for the next version of the code (on this case, you will have to manually reprovision everything, or start from scratch with a new sync)

Let me know !

**Comment by Mimetis** [comment]
You can try the version from branch https://github.com/Mimetis/Dotmim.Sync/tree/Mimetis-Simplified-Flow   
Be careful, it's a new version, not compatible with the current version !    
You will have to recreate a full sync on a new database
