### ISSUE TITLE
[SQLITE] - Bug detecting changes and possible fix

### ISSUE THREAD

**Issue by mssergiosilva** [Mimetis/Dotmim.Sync#175]
Hi,

First thank you this great sync framework!

I have detected a bug in SQLITE insert trigger. If we insert a record, delete it and insert again (all with same primary key) the sync framework detects that have to insert the record instead of update.

More easy with a example (my client is sqlite and server is sql server):

1. Insert record ID=1 in table A;
2. Sync;
3. Delete record ID=1 in table A;
4. Insert record ID=1 in table A;
5. Sync;

The data are not synced.

I have made a fix for my self (in class SQLiteBuilderTrigger) and maybe you can implemented in this way (I have attached the code)
[InsertTriggerBodyText fix.txt](https://github.com/Mimetis/Dotmim.Sync/files/3932608/InsertTriggerBodyText.fix.txt)

**Comment by Mimetis** [comment]
Thx for reporting it!
Can you take on look on #173 and confirm if it's the same issue.
If yes, you can test a new version, not compatible with the current 0.3, which should resolve the issur

**Comment by mssergiosilva** [comment]
Hi,

It's not the same issue.
I have tested the fix suggested in #173 and did not work.

**Comment by Mimetis** [comment]
OK thanks, will take a look quickly

**Comment by gentledepp** [comment]
We fixed exactly this issue in #160
but did not push it yet.
Have a look at the stored procedure code that is created, because that is the spot where you can fix this issue (the sp checks if a row with the id exists - if so, it treats it as "update", otherwise as "insert")
