### ISSUE TITLE
Sync via WebServer mixes System.String and System.Byte

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#18]
Hi Sébastien,
I think there is a small issue when synchronizing via the webserver.  I have added the tables to sync in the webserver, and have modified the SyncServer project to connect to the webserver.
While the included database syncs fine when using direct sync, it produces the following error via webserver: System.String cannot be converted to System.Byte.
Please restore the database, adjust connectionstrings and run webserver+syncServer.

Regards
Reinhold
[DotminSyncWeb.zip](https://github.com/Mimetis/Dotmim.Sync/files/1468205/DotminSyncWeb.zip)

**Comment by thefonzi** [comment]
Here comes a cleaned version of the sample. Synchronizing via webServer gives problems with varbinary(MAX)-field. 
Attached database contains table FileData (with field "Content") only.
The sample just syncs this table.

[Dotmim.Sync.SampleWebserver.zip](https://github.com/Mimetis/Dotmim.Sync/files/1469988/Dotmim.Sync.SampleWebserver.zip)

**Comment by Mimetis** [comment]
Thx for the issue !!  
I had a bug in the serialization process.  
JSON.NET generate a Base64 string for byte array.  And I didn't deserialize it in byte array after.  
It's corrected in the last commit.  
Can you make a Pull and make a test again ?  

Seb

**Comment by thefonzi** [comment]
Testing..

**Comment by thefonzi** [comment]
Works perfect now!. thanks
