### ISSUE TITLE
GetCachedProviderInstance always returns null - cannot sync

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#180]
clean pull of your code. When running with Visual studio for Mac it errors when running console sync.

tracked it down to GetCachedProviderInstance always returns null

**Comment by Mimetis** [comment]
Hello @mdonogma 

> Before starting the conversation, if you're making some tests, be sure you're testing on the next version of the framework, that you can obtain from this PR : #177 or from [Nuget as beta version](https://www.nuget.org/packages?q=Dotmim.Sync)
> Actual release, tagged, `v0.3` will be replaced with the `v0.4` in less than one month
> `v0.4` brings a lot of bug fixing, performances and new feature, and this new version will not be compatible with `v0.3`

Can you make this test on `v0.4` #177 ?

**Comment by Mimetis** [comment]
No answer from you, I guess it's ok

**Comment by mdonogma** [comment]
Works in 0.4 this can be closed
