### ISSUE TITLE
Documentation issue - Direction

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#182]
Indicates the following can be used to set direction.

agent.SetConfiguration(c => {
    c["Address"].SyncDirection = SyncDirection.DownloadOnly;
    c["Customer"].SyncDirection = SyncDirection.DownloadOnly;
    c["CustomerAddress"].SyncDirection = SyncDirection.DownloadOnly;
});

This doesn't work as indexer cannot be used on c - according to compiler.  See screenshot.

I copied code directly from documentation.[
<img width="723" alt="Screen Shot 2020-01-11 at 3 31 55 pm" src="https://user-images.githubusercontent.com/13458476/72199436-c1826900-3487-11ea-88b5-898a93bfadcc.png">
](url)

**Comment by Mimetis** [comment]
Hello @mdonogma 

> Before starting the conversation, if you're making some tests, be sure you're testing on the next version of the framework, that you can obtain from this PR : #177 or from [Nuget as beta version](https://www.nuget.org/packages?q=Dotmim.Sync)
> Actual release, tagged, `v0.3` will be replaced with the `v0.4` in less than one month
> `v0.4` brings a lot of bug fixing, performances and new feature, and this new version will not be compatible with `v0.3`


Sorry about that, the doc is not up to date
I have to work on it. 
The documentation will be updated with the next major release

**Comment by mdonogma** [comment]
Can you guide on how to correct while document is updated

**Comment by Mimetis** [comment]
doc updated today
