### ISSUE TITLE
console App - Sync via WebAPI - after a few sync's keep getting n: There is already an open DataReader associated with this Command which must be closed first.. Type:InvalidOpe

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#183]
Setup the sample app sync server and sync console.

Run few a few times then ": There is already an open DataReader associated with this Command which must be closed first.. "

Is there a way to kill these data readers automatically in the code?

see attached image
<img width="574" alt="Screen Shot 2020-01-11 at 3 49 44 pm" src="https://user-images.githubusercontent.com/13458476/72199619-466e8200-348a-11ea-946f-a7f772cee68c.png">

**Comment by Mimetis** [comment]
Hello @mdonogma 

> Before starting the conversation, if you're making some tests, be sure you're testing on the next version of the framework, that you can obtain from this PR : #177 or from [Nuget as beta version](https://www.nuget.org/packages?q=Dotmim.Sync)
> Actual release, tagged, `v0.3` will be replaced with the `v0.4` in less than one month
> `v0.4` brings a lot of bug fixing, performances and new feature, and this new version will not be compatible with `v0.3`

Can you make a test on the `v0.4` #177 and check if you still have the issue ?
