### ISSUE TITLE
filtering by a collection of items when sync runs

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#184]
I have a security requirement to ensure users only get access to specific customer data.

For this I would have either a SQL View or list of CustomerID's each user can sync with.

from what I can tell the filter is only allowing 1 item to be filtered at a time.

What if I need to give a user sync with customer record A, B, H, J.

extract from the documents:
agent.Parameters.Add("ServiceTickets", "CustomerID", 10);

Is it possible to do something like this in a filter:
agent.Parameters.Add("ServiceTickets", "CustomerID", [A, B, H, J]);

OR give it the name of a security stored proc or security SQLView that will return a list of customerID's the user can sync with.

**Comment by Mimetis** [comment]
Hello @mdonogma 

> Before starting the conversation, if you're making some tests, be sure you're testing on the next version of the framework, that you can obtain from this PR : #177 or from [Nuget as beta version](https://www.nuget.org/packages?q=Dotmim.Sync)
> Actual release, tagged, `v0.3` will be replaced with the `v0.4` in less than one month
> `v0.4` brings a lot of bug fixing, performances and new feature, and this new version will not be compatible with `v0.3`

The filter feature is not really powerful today. 
I'm still thinking on a new system to allow more options and more flexibility.

But for now, it's not possible to have an array parameter value.

Today, if you want to extract multiple customers, I think the best way is to create a `CustomerGroup`.
Each `Customer` will has a foreign key on this table.
Then make a filter on `CustomerGroup` primary key
