### ISSUE TITLE
Sync - multi TimeZone scenario

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#185]
If I have multiple clients each running different timezones.

Will the sync work correctly?

i.e. does it always use UTC when syncronizing?

**Comment by Mimetis** [comment]
Hello @mdonogma 

> Before starting the conversation, if you're making some tests, be sure you're testing on the next version of the framework, that you can obtain from this PR : #177 or from [Nuget as beta version](https://www.nuget.org/packages?q=Dotmim.Sync)
> Actual release, tagged, `v0.3` will be replaced with the `v0.4` in less than one month
> `v0.4` brings a lot of bug fixing, performances and new feature, and this new version will not be compatible with `v0.3`

The answer is a little bit tricky, but let's say:
- **Yes**, all tracking tables have a datetime which is UTC based.
- **But** the timestamp used to compare rows are not based on a `datetime` value, but more on a `bigint` (`Timestamp` for Sql Server, `Double` ticks for MySql and Sqlite)

Even more, the framework works *without* having to compare a date from a client and a date from a server. 
Each part is completly independant, managing itself its `timestamp` value.

**Comment by gentledepp** [comment]
@mdonogma we do have an app that is being used in multiple time zones already, so I can confirm, that this works just fine.

**Comment by mdonogma** [comment]
Champion. Love your work!

Sent from my iPhone

On 13 Jan 2020, at 01:08, Sébastien Pertus <notifications@github.com> wrote:

﻿

Hello @mdonogma<https://github.com/mdonogma>

Before starting the conversation, if you're making some tests, be sure you're testing on the next version of the framework, that you can obtain from this PR : #177<https://github.com/Mimetis/Dotmim.Sync/pull/177> or from Nuget as beta version<https://www.nuget.org/packages?q=Dotmim.Sync>
Actual release, tagged, v0.3 will be replaced with the v0.4 in less than one month
v0.4 brings a lot of bug fixing, performances and new feature, and this new version will not be compatible with v0.3

The answer is a little bit tricky, but let's say:

  *   Yes, all tracking tables have a datetime which is UTC based.
  *   But the timestamp used to compare rows are not based on a datetime value, but more on a bigint (Timestamp for Sql Server, Double ticks for MySql and Sqlite)

Even more, the framework works without having to compare a date from a client and a date from a server.
Each part is completly independant, managing itself its timestamp value.
