### ISSUE TITLE
<head><title>413 Request Entity Too Large</title></head>

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#188]
Running locally would sync fine with 10000 rows.

Deployed to AWS (good server spec) - ran sync again fails with error: <head><title>413 Request Entity Too Large</title></head>

Tried updating buffer to 50 - still failed.

Scaled down the number of rows to 10 - Sync runs fine.

Help!

**Comment by Mimetis** [comment]
Did you tried something like 5000?

Le mar. 21 janv. 2020 à 11:08, Fun stuff <notifications@github.com> a
écrit :

**Comment by mdonogma** [comment]
Maybe I should ask it this way , what is the max number of rows this library will support. I cannot invest time into something that has net been tested against large tables.

Example : backend dB has 5 million records however using filter the client has access to only 10000 records. It worked on local dev machine but bombs out when deployed to close with the error stated.

**Comment by mdonogma** [comment]
It appear this is a web server config issue. Sorry. 
![6CFD8C73-CA5E-4678-8036-4262B619AC3C](https://user-images.githubusercontent.com/13458476/72838447-030ee180-3cdc-11ea-99b8-71f8c17f6952.png)
![91A135C8-EB97-4C10-B27E-3D38B3920193](https://user-images.githubusercontent.com/13458476/72838448-030ee180-3cdc-11ea-81a2-df99a8cac618.png)

See attached image on how to fix

**Comment by Mimetis** [comment]
Feel free to invest time or not.
This project is open source, and the author (me) wrote it on his spare time.

I cannot invest time into something that has not cleary identified.
Give me a repro or more details, other than "it's not working"

If you want a more robust framework with support, you should consider other solutions like [SQL Server merge replication](https://docs.microsoft.com/en-us/sql/relational-databases/replication/merge/merge-replication?view=sql-server-ver15)
