### ISSUE TITLE
[Bug] Insert statment is not passed to a second client

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#19]
Hi Sébastien,
i have discovered a bug and will try to describe the steps to reproduce.

a) Master database on MSSQL
b) sync to SQLite database Slave1 
c) sync to SQLite database Slave2
d) Now insert a new record in one of the slave databases and sync. The record is uploaded to master.
e) Sync on second slave: **no record is downloaded to slave**2
f) update the record on slave1 and sync: update is synched to master
g) sync on slave2, record is now downloaded

If this is not enough information to reproduce, please let me know and I will setup a small reduced sample. 

Reinhold

**Comment by Mimetis** [comment]
Will check that !

**Comment by Mimetis** [comment]
Hello Reinhold;

I made a correction on the Core assembly.  
I've added new tests to check this behavior.   
Can you please test with the last version ?

**Comment by thefonzi** [comment]
Hello Sébastien,
I have now tested with a MasterDB and 3 Slaves and this works now! 

But in testing I discovered another strange behavior. Please note: i have not changed the server/client, means there is no expizit conflict management. 

Steps: 
a) I change a field value in slave1 and sync. Update is uploaded to master
b) I sync on slave2 and upload is downloaded. 
c) i change the same field in slave3 and sync. Now I get the message "bad request" and the value is not synched. I have attached a screenshot.

![screenshot 3](https://user-images.githubusercontent.com/6755910/32838047-049e211e-ca10-11e7-9df0-9d7ffab67cb5.png)

**Comment by Mimetis** [comment]
Strange behavior...  and hard to test..  
Can you provide more informations on your setup ?

**Comment by thefonzi** [comment]
I'm trying to setup a testcase, with and without webserver.

**Comment by thefonzi** [comment]
[testCase.zip](https://github.com/Mimetis/Dotmim.Sync/files/1479268/testCase.zip)
Hi Sébastien,
I have found the exact problem of sync with varbinary(max) fields.
Here are the steps I do:
Sync works via webService!
a) insert a file in master database  (MSSQL)
b) sync and record is copied to slave database (SQLite)
c) file is correct and can be opened
d) now I insert a file in slave database and sync. File is uploaded to master database
e) here the file is corrupted.
I have attached a video of the steps and the syncClient, which does the sync. 
If you need the whole client + database to reproduce, please let me know.

[SyncTest.zip](https://github.com/Mimetis/Dotmim.Sync/files/1479261/SyncTest.zip)

**Comment by Mimetis** [comment]
OK, i will check that

**Comment by Mimetis** [comment]
Can you test with the last version ?  
The setup to be able to reproduce your bug is quite difficult :) I have to recreate a viewer application, which works with both **SQL Server** and **SQLite** 
It will take some times...  
Will try to create a sample next week (if you still have the issue)

by the way, be careful of the breakings changes from `0.1.5` (see #21)

**Comment by thefonzi** [comment]
I will test and let you know. 
BTW: I can provide a client, that works with both databases just by switching the connection string. 
Let me know, if you want to get that viewer.

**Comment by thefonzi** [comment]
Hello Sébastien,
here is a client you can use for testing. 
There is a key in config "UpdateDatabase", which forces to create/update the database. Comment this key out on slaves.
And select the right connectionstring for desired database. 
I have inserted 3 classes: C4Contact with just a few text fields, C4File with varbinary(max) and C4Photo with image.
Let me know, if you need any additional infos.

Reinhold

[DotminXAF.7z001.zip](https://github.com/Mimetis/Dotmim.Sync/files/1484981/DotminXAF.7z001.zip)
[DotminXAF.7z002.zip](https://github.com/Mimetis/Dotmim.Sync/files/1484982/DotminXAF.7z002.zip)
[DotminXAF.7z003.zip](https://github.com/Mimetis/Dotmim.Sync/files/1484983/DotminXAF.7z003.zip)

**Comment by thefonzi** [comment]
<add name="ConnectionString" connectionString="XpoProvider=MySql;Server=localhost;User ID=root;Password=mypass;Persist Security Info=true;Charset=utf8;Database=DotminXAF"/>

**Comment by thefonzi** [comment]
"<add name="ConnectionString" connectionString="XpoProvider=MySql;Server=localhost;User ID=root;Password=mypass;Persist Security Info=true;Charset=utf8;Database=DotminXAF"/>"

**Comment by thefonzi** [comment]
add name="ConnectionString" connectionString="XpoProvider=MySql;Server=localhost;User ID=root;Password=mypass;Persist Security Info=true;Charset=utf8;Database=DotminXAF"/

**Comment by thefonzi** [comment]
actually i need some time to proceed testing, as my client works with char(36) in GUIDs.
I'm not sure, if that is simple to change. 
I'll check and be back soon :-)

**Comment by Mimetis** [comment]
Hey Reinhold;

Eventually, I've found the bug about the image problem.  
Actually, the SQL Provider was trunking varbinary to 8000.  
It's corrected in the last push.  
Can you give it a try and let me know if it's working ?  

Sebastien

**Comment by thefonzi** [comment]
I will need to write a custom connection provider to access the Sqlite.db with guid.blobs, except you provide a workaround to switch to guid.text (see my post in other thread). 
I bear with you :-)
