### ISSUE TITLE
Master detail inserts on client - how do id’s get synchronised with server so integrity is maintained.

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#191]
Master detail inserts on client - how do id’s get synchronised with server so integrity is maintained.

In this scenario:
Table1
Id - int (primary key)
Title

Table 2:
Id - int (primary key)
Table1Id - foreign key
Title

Without using GUID’s as primary -foreign key-
Need to ensure master detail ids aren’t messed up on sync with server.

Given table 1’s primary key is auto generated  on inserts how would sync ensure detail tables get correct Is

**Comment by Mimetis** [comment]
if you have same ID on both part, sync will make an update.

IF you don't want to have this issue, the best thing you can do is:
- Define a range for your server side. Let's say from 1 to 9 000 000
- Define a range for each of your clients. Let's say
   - Client 1 : 10 000 001 to 11 000 000
   - Client 2 : 11 000 001 to 12 000 000

And so on...

There is no other options

**Comment by mdonogma** [comment]
Perfect!
