### ISSUE TITLE
Filters: master detail

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#192]
Is there a way to have a filter on master table then only records in master and detail tables are synchronised based on foreign key relationship between two tables.

Example: master table is a security table indication what records a user had access to. The detail table has the records.

It’s a way to create row base security

**Comment by Mimetis** [comment]
Yes, have a look here : https://github.com/Mimetis/Dotmim.Sync/issues/179#issuecomment-579950154
