### ISSUE TITLE
0.4 sync bombs for any reason it will not run again

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#194]
if 0.4 fails for any reason, it will not sync again.
Keeps saying "Dotmim.Sync.SyncException: Synchronization already in progress " in the console.

Have to shut the client down before trying again.

**Comment by Mimetis** [comment]
Damn... It should not !

I need more information to debug this issue, I'm not able to reproduce it.
Can you share more info?
