### ISSUE TITLE
Ideas and Feature Requests

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#2]
Hi!

I have had a look at Dotmim.Sync, and compared its current capabilities with the stuff, that we currently have in production. (we are using [SyncWinRT](https://github.com/Mimetis/SyncWinRT) - I guess you know that library ;-))

What we definitively need is:

**1) a way to specify a filter on a table that is being synced.**  
Currently, when a filter is active, the Microsoft Syncframework regards all filtered records as "out of the sync scope". However, when the rows change in a way that should re-include them to that sync scope, the old Syncframework was not able to detect this.
We made that possible by updating the "_tracking" tables manually, using our server side logic.

**1b) we even need to be able to filter based on a table join!**
We currently achieve that by modifying the sql scripts (stored procedures) which are generated by the framework, so that they add a join expression. The complexity in that approac is, that the join filter also needs to take into account, that the joined table might have changes as well. (so while the current row should have not been synced to the client, it now should based on some changes in the joined table)
The only part where it got too complicated was with many-to-many joins. (I might be able to assist you with that feature ;-))

**2) Another part that was kinda cumbersome is, that SyncWinRT identified the sync master by its fully qualified domain name.**
That was a problem when users hat to use a different URL when they were in their corporate network. 
A quite easy fix would be, that the master database generates some guid, which is in turn used to identify it. In that case, the URL does not matter anymore.

**3) allow to change serialization format**
I have been playing around with protobuf-net recently and I am amazed by its performance. 
As it normally uses reflection just as any other formatter, it also allows you compile a dll with a "hard-coded" serializer. Dude that one is sooooo fast!!!
So I would really like to use that insead of json or the like. (Again: I could help you with that)

**4) Support one-way sync.**
That one is interesting, because we are thinking about syncinc an Event Stream (neventstore) from server to client, thereby applying some filters (as in (1) and (1b))
However, as the event stream **must** only be edited on the server, there is no need for two-way syncing.
So a one-way sync option for a specific table would be great!

**5) Use dotmim.sync for a file syncing api**
A colleague of me created a github library, that allows you to split up your binary files into aprts, send them to a Web-API server, and fuse them back together.
That allows you to send large files over weak internet connections.
Now it would be great to have that combined with dotmim sync as a file sync framework:
That way, on the client side you know which files are already uploaded, and which are pending.
You can also send the list of files a client requires (using sync) and let him/her decide which files to actually download.
Sure, this is far beyond the scope of Dotmim.Sync, but I wanted to share this idea with you nevertheless, as you might have some interesting ideas for it too. ;-)

So what do you think about my ideas and feature requests?

**Comment by Mimetis** [comment]
@gentledepp  THX A LOT for your feedbacks !!

**1** : Yes, I  know, it's complicated, I have some ideas, but your ideas seems interesting. Can you explains more in détails, how you deal with it ?

**2** : It's way way way more simplier here :) Identify your server db with a connection string. THAT'S ALL :)

**3** : The architecture is based on providers, and I will implement more serialization providers. Currently we have JSON and a "home made" BINARY serialization.

**4** : Working on it :)

**5** : Argh, that could be really ... complicated. I don't think the core project could handle this scenario.
Maybe for a later version, why not, but not sure it's possible.

All your ideas are just great. 
Since we are on Github, please open an issue per idea (except for 5, at least for now ;) )
I will then close this one.

THX !

**Comment by gentledepp** [comment]
Hello again - sorry for the delay.

**@1**
For the 'table-join-filters' that was quite a task for us.
* we had to modify the stored procedures SQL generated by sync framework and as we have quite complex filters, it is quite messy, unfortunately. (we join not one table alone...)
For the sake of simplicity, I created a simple sample around tasks.
In our example, a user gets all tasks that are either directly assigned to him, or that he is a candidate for.
So when selecting the changes of his tasks (in the stored procedure Tasks_selectchanges) we actually need to join the taskcandidates table as well and the taskcandidates_tracking table as well.
To get all tasks that became available to a user because of an inserted or updated taskcandidate row, we need to combine the values of the timestamp columns of the two tracking tables.
```

Create PROCEDURE [Tasks_selectchanges]
	@sync_min_timestamp BigInt,
	@sync_scope_local_id Int,
	@sync_scope_restore_count Int,
	@sync_update_peer_key Int,
	@UserId BigInt
AS
BEGIN
SELECT [side].[Id], [base].[Title], [base].[AssignedUserId], [base].[Description], [base].[StartDate], [base].[DueDate], 
[side].[sync_row_is_tombstone] as sync_row_is_tombstone,
[side].[local_update_peer_timestamp] as sync_row_timestamp, 
case when ([side].[update_scope_local_id] is null or [side].[update_scope_local_id] <> @sync_scope_local_id) 
	then 
		-- propagate task changes if taskcandidate was added afterwards
		case when [tct].[local_update_peer_timestamp] > [side].[restore_timestamp] OR [tct].[local_update_peer_timestamp] > [side].[local_update_peer_timestamp]
			then [tct].[local_update_peer_timestamp]
		-- propagate task changes if taskcandidate was added afterwards
		when [tct].[local_create_peer_timestamp] > [side].[restore_timestamp] OR [tct].[local_create_peer_timestamp] > [side].[local_update_peer_timestamp]
			then [tct].[local_create_peer_timestamp]
		else 
			COALESCE([side].[restore_timestamp], [side].[local_update_peer_timestamp]) 
		end
	else [side].[scope_update_peer_timestamp] 
end as sync_update_peer_timestamp, 

case when ([side].[update_scope_local_id] is null or [side].[update_scope_local_id] <> @sync_scope_local_id) 
then case when ([side].[local_update_peer_key] > @sync_scope_restore_count) 
	then @sync_scope_restore_count 
	else [side].[local_update_peer_key] 
	end 
	else [side].[scope_update_peer_key] 
end as sync_update_peer_key, 

case when ([side].[create_scope_local_id] is null or [side].[create_scope_local_id] <> @sync_scope_local_id) 
	then [side].[local_create_peer_timestamp] else [side].[scope_create_peer_timestamp] 
	end 
as sync_create_peer_timestamp, 
case when ([side].[create_scope_local_id] is null or [side].[create_scope_local_id] <> @sync_scope_local_id) 
	then case when ([side].[local_create_peer_key] > @sync_scope_restore_count) 
		then @sync_scope_restore_count 
		else [side].[local_create_peer_key] 
		end 
	else [side].[scope_create_peer_key] 
end as sync_create_peer_key 

FROM [Tasks] [base] 
RIGHT JOIN [Tasks_tracking] [side] ON [base].[Id] = [side].[Id] 
-- here we join with TaskCandidates tracking table 
LEFT JOIN [TaskCandidates_tracking] [tct] on [tct].[TaskId] = [side].[Id] and [tct].[UserId] = @UserId
WHERE 
(
-- filtering which tasks a user gets synced on his/her device
-- 1) all tasks that are assigned to her/him directly (assigneduser)
([side].AssignedUserId = @UserId
-- 2) or the user is in the list of candidates, that are allowed to perform this task, even though not directly assigned to it (e.g. collaboratively work off all tasks)
 OR Exists (SELECT tr.Id FROM TaskCandidates_tracking tr where tr.UserId = @UserId and tr.TaskId = [side].[Id])) 

OR 

([side].[sync_row_is_tombstone] = 1 AND ([side].[update_scope_local_id] = @sync_scope_local_id OR [side].[update_scope_local_id] IS NULL) 
AND [side].[AssignedUserId] IS NULL 
AND  ([side].[update_scope_local_id] IS NULL 
OR [side].[update_scope_local_id] <> @sync_scope_local_id 
OR ([side].[update_scope_local_id] = @sync_scope_local_id 
AND [side].[scope_update_peer_key] <> @sync_update_peer_key)) 
AND ([side].[local_update_peer_timestamp] > @sync_min_timestamp 
	-- or the associated taskcandidate entry has changed => this may cause task to become available to user
	OR ([tct].[local_update_peer_timestamp] > @sync_min_timestamp OR [tct].[local_create_peer_timestamp] > @sync_min_timestamp))
	
GO

```

As you can see the required SQL (and this is only a simple example without tenancy filter and the like) is quite complex unfortunately.

**@2** please consider testing MessagePack in combination with LZ4 compression for data transmission.
I have made several test runs in the past few days and [MessagePack-CSharp](https://github.com/neuecc/MessagePack-CSharp) is not only blazingly fast but also compresses the data quite good. (as opposed to JSON.net - obviously - and Protobuf-net)
MsgPack & LZ4 is also what uber seems to be using [See this article](http://highscalability.com/blog/2016/3/21/to-compress-or-not-to-compress-that-was-ubers-question.html) 

**@5** you are right - this is absolutely out of scope. I just wanted to mention it to get the thought into your head ;-)

**Comment by gentledepp** [comment]
For @1 - I created a small diagram trying to explain my ideas:
[Sync Filter Diagram](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=sync_filters.html#R7Vptb9s4Ev41xrUFGsh27CYfm5f2gutie5ssdu9TQEu0xYskqiIVx%2F31NzMcUpSlpC7OvbvFbYA2JkUOh%2FM883AoZzK%2FLJ8%2BNqLOf9KZLCazJHuazK8ms9l0draEX9izcz2LhDs2jcp4UNdxq75K7ky4t1WZNL2BVuvCqrrfmeqqkqnt9Ymm0dv%2BsLUu%2BqvWYiMHHbepKIa9v6nM5q73bPau6%2F%2BrVJvcrzxdnrsnK5E%2BbBrdVrzeZDZf0497XApvizdqcpHpbdQ1v57MLxutrftUPl3KAmPrw%2BbmfXjmafC7kZU9aALj8iiKVnqXyTG788GQGcSGm2BW2d0vshBW6eq6e3KR27KAAVP4KKvsPYIAzetfdCXv9E%2Bi2uGDJ2V%2Fx0EnCSzs2v%2BAdnKyTE65%2FVk2qpRWNthPxmyz%2Bz1uuBkLaA53ywEwum1Sdn92ygQSzUbyMD8OtxZN5Bh9lBo8aHYwYNuhP00YszxG3nc2FJLHPn8E03ATDIY1PmsFPs8STpnZOcedE2a6OO%2BbcDviWTGge4ZOPbPY0OzdrG%2FIhWFgCD5EG%2B%2B6iC%2FPcOfdj%2BbOV9noO%2F1zhWMMOG67R6WoMvcgkKpHqNl38%2BN%2Fhwtn530uzE%2BPw4Wpb%2F8ALpwNuHAnzIO5tw0ooqo2A2aYrSoLQQimuSqyT2KnW4wkAJ0%2B%2BNZFrhv1VVdWeIIQD%2FjEmCe9Ebc4k5VirYriUhe6odXmSXKWgghDP4yM%2Bj%2FQD%2FSTZsuMF8FRvAawnNvse0JONPohHA0znC8NjP%2FsqZaErk%2FCWO%2B6F3t8mgmT03rYEIXaVPA5hdmofM8z91E2Vj69yNNn0F9wM6JxOG97NN5nSczYHkVe4sP5iDZc3MBvOHDm04S2eNHWmbDy3qS6lveFhvP3Hgz0hpzAz4A7PlyFXNuAhke10kSqmADcZWqRAhU%2F0ayr0xGcMboK3HjPC1hdeyDFKqDfaCts1AaYPMQjuJ0dDBwDNT8QqPMj4OSxHuQthA%2BZ%2BGfW%2FpezNiD0zbRdHIMO0wEdRtL2Qhh5A3mavPrwN6rM4T9izev%2BOLgXqLWSNPLXu0u8D0C67w26MVeygHqPRq2U3Xt8JR9Vyqt9%2FPXm6vUfWgxCuh1dDI6i2rP5uBr8KQP%2FaRmYTvsycD6kwXT5w2hweogK%2FNEP5kD2fycXR0E4ysG8GGCAscJrrHnAOwZwcbYsMMqZeoSPG0o4WHKG15AEwgv%2F4YylKDFW1crUFAc3CdaP5o2Y6gr3eK39aXv4QyBt%2Fz63D1GNlw2Ky%2BJisrjC9GmtNgx1lE1MoXHgmTB32Lh6e3qcnJudL3s5txzCfT6C9ukx0B6%2BhhminQR0xyGNwcMj%2BQ3882VcQu%2FE%2Fi9A7AvnfDqStLMRGOfHgHHs1uNink99vO9yBPYmkyLCo3vsO%2Bv9DghXNWJj%2Fj4yE4%2Fx3avmJUvvSSOBKI0ukW9keAUFHpEPIYfCyxd3iaiyMKiSqTRGUPAjsehPCvd%2FmI0FoFojNLrFWlCuFXFcRDy9dOarve5gVWEGrKRbKm0k1JPZyfM7%2FWZI7nJhx9ZJsSZRlWE%2FXP6tSVSlSPMuM11EuC%2BjYhUWTQuFFObt0BI2J995mvusaTOYfbsqpQp4q2x%2BgtDilJLYyUPWUhjlnKN5jczaVEaGsRO29aXFd8cXz%2FvaGtypH%2Bd8lI8UckKH%2FXXDWHPKFt%2B90%2BJuj%2BYkCvGAqqHj5zXFsm2QT4xtQ%2FFFUNzGvrTKehoUGpfW6yBYiarCFnH%2BqsUBW0mHW7EjGkrHSU2cXdCCRVtWB7r4m2MbIkCsugwEt72LcJ%2BC%2FwQFpHVFoauNUZnspm0RCY07NRRHR1basKoqsoXTR2iLin1TUXhMZJBjJp%2BUsWiy0nvKHnvNuJWtsRSdRzdIpgo%2BhlFwERMHrd%2BELYvBoiNZt3cwDc6qN28CD5X9C1GruyTi7dCvBhpRbWipV6UmJ2ALkFOvHUOrsJPhfL3uQdiRyPfcD%2BUq0p1%2Bojr%2Bj2QqRRamFCCC4wr0XbE4JBSUAMqG8fHVeV2IjZ9gpH1hR8yM%2Fm5ol50qWF2ujNVE8b5SGE3L%2B6WyzoH4AHH694IwxwpMhkBwU1lbwhkUASoO9CrLFH5XIAoakQXxe5Cy%2FlaetrUf7YLZyYeb9qWVdHY5pTSwkdTyuQL82pAD5JoXKKNKJ4H%2BFGzxaS0bsFAK2q7LHtA7Sld4BGFIeW3noAn2catQ6ZCIOYu5eHQORHKbalz0iTUDZ7%2Fa5opUfavbIvNIuj2R6qBT2vjDQtR1o%2FkY0ARg8eiPDUwmUzihhctt5aPy1qqST0GUtgYiujsQTI6sQdh8ALcsI8zDAVImj3fy4GigvCpHFU5fqUSHJcoZFy0F5CXSxeuubdRm4%2BLOJ5t8kmkbjpzbv3%2BKfQLUgHvGeY8pTuWNC4fokihQBJElAolJ0F7AvVTeBo9EcjDVPW6leOiQA5CwnCKHRWW4Bibzud46Fb%2F0qectcKoEIxQu0hEKgUuVimoXsdLEfb8lzxT3pVwXHLFeQx6YYDIuzOIqoZOAis5spyQHkWQPOyBoAZcDJoyHL7CcGSTCuQ9ZQpC7C5KIXW1I2XTNtrai8y8qn1zCt8T%2BjpoMAgwpedVe8ebK4vRBUqa%2BckY97dBSho7rmoJKPgONasyfeFHULaZlFN237jR26WbsuHJen2xOxinJrFOsmK4c0vwQ%2FxgBhbDTcSxtGwVKqDEp%2Buq%2Bv0%2Fom0%2BC9DZtKIi9ePpikb7I2WeNiXKcHJKVaTnccU1cyW3kaSnLVVR6CibXvavBTQ2VDB6SIyG6wedW0ZUMsnjtRMatEckgme34C36Tk4eViy%2FeNZ6fdrdXshN2JRzsod7l3HVl7%2BVkP%2F%2FiihnOhBWXn%2BugPXToc%2B2DB%2BLzFPKq3uGNWunEp9Ablfap714AJ4KAg3NObMJNxdVVUpQkb9eemtAR4%2BjiX8A501HTSOk6oxXiKg1MhOOUHXE1KWlgBUkiMr9dugZykT3Zr1FfuLTt%2BYmW3c00ZXl198vJYVdAZ%2B1yEiSpf7HsHdamXa9VyiVSMn5o5o7uraNsjwmxKXeLzp4h7zff7HznG1roWAze3MzwlRDItZW30I9LbRuBBa4GQqwLemmeKxCm6jiveJZn3%2Fxie%2FFu5A3Pcvn9r3ig2f0xlvu7iO4v3ubX%2FwI%3D)

**Comment by Mimetis** [comment]
access is denied :(

**Comment by gentledepp** [comment]
hmmm... ok - so I created a png and updated the link. Works now on all my browsers - please check :-)

**Comment by Mimetis** [comment]
Nice !
I've readed your design diagram, and adding a new table could be a first approach.

One of your solution is to delegate the data consistency to the application.  
Actually I'm trying to be the more "application less" as possible. 
So this option is not a good solution for me, for now at least.

I will continue to think about your design and architecture for filtering rows.
I you want to make a test based on Dotmim.Sync, feel free to get a clone of the repository and make an hard coded sample !

Thx A LOT !

**Comment by gentledepp** [comment]
Hi!
We have made some nice progress when it comes to the "_filter" tables.
I recently posted a question on stackexchange [efficient join technique for two very large tables](https://dba.stackexchange.com/questions/213541/efficient-join-technique-for-two-very-large-tables)
and answered it myself.

I provided the full SQL code required 
* understand the technique
* and test it with lots of data

What do you think?
