### ISSUE TITLE
Custom sync to client provider

### ISSUE THREAD

**Issue by jromerus** [Mimetis/Dotmim.Sync#20]
Hi! Your project is very interesting for me. I also see demo entities referencing XAF core tables...this is the framework that I use for business so it would be very promissing working with Dotmim at sync scenarios.

I wonder if there is a recomended approach, not to make a complete sync, but using Dotmim trigger capabilities and agent logic, subscribing to the event or method that tries to sync data to client provider. My idea is to make a light use and make by myself a custom insert, update or delete at client direction because is not a stadar RDBMS (I plan using couchbase syncing data with mysql).

Regards,
José Enrique

**Comment by Mimetis** [comment]
Hi José !
You have some useful handlers during the whole sync process, as shwon here: [ wiki 02-Sync-progression](https://github.com/Mimetis/Dotmim.Sync/wiki/02-Sync-progression)

Is it enough for you ?

**Comment by jromerus** [comment]
It seems to be what I need. I will research if I can stop progression at that point, retrieve data pending to sync, make my own transformation and export, and finally mark at source data that its synced.

Thanks!

**Comment by Mimetis** [comment]
Let me know if you need Something :)
