### ISSUE TITLE
0.4 still creates tracking table when change tracking on SQL DB

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#200]
CLient DB:
ALTER DATABASE DotMimSyncv4Client4  
SET CHANGE_TRACKING = ON  
(CHANGE_RETENTION = 14 DAYS, AUTO_CLEANUP = ON)  

ALTER DATABASE DotMimSyncv4Server4  
SET CHANGE_TRACKING = ON  
(CHANGE_RETENTION = 14 DAYS, AUTO_CLEANUP = ON)  

Ran Sync
still created t[tablename]

I thought tracking tables were not created with change tracking on?

**Comment by Mimetis** [comment]
Did you used `SqlSyncChangeTrackingProvider` instead of `SqlSyncProvider` ?
