### ISSUE TITLE
0.4 set table to sync with from client

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#201]
I have some specific scenarios which require client to control tables to sql with and the filters.

Example:before login, sync with only language table.

After login , sync with table xyz.

When switching tables I need the data in previous sync tables to be retained till I run specific sync on those tables

**Comment by Mimetis** [comment]
It's possible, if you are creating a **multi scopes** scenario.

How it's working ?
Each scope has its own schema with related tables.
Each scope has its own timestamp regarding its last sync.

Each time you sync one named scope, the sync will work based on metadatas saved in the scope table, for this named scope.

One thing to notice: Be sure you do not overlap table in two differents scopes.
If you have one table in each scope, it will most probably fail at some point.

``` cs
// Create 2 Sql Sync providers
var serverProvider = new SqlSyncChangeTrackingProvider(DbHelper.GetDatabaseConnectionString(serverDbName));
var clientProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(clientDbName));

// Create 2 tables list (one for each scope)
string[] productScopeTables = new string[] { "ProductCategory", "ProductModel", "Product" };
string[] customersScopeTables = new string[] { "Address", "Customer", "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail" };

// Create 2 sync setup with named scope 
var setupProducts = new SyncSetup(productScopeTables, "productScope");
var setupCustomers = new SyncSetup(customersScopeTables, "customerScope");

// Create 2 agents, one for each scope
var agentProducts = new SyncAgent(clientProvider, serverProvider, setupProducts);
var agentCustomers = new SyncAgent(clientProvider, serverProvider, setupCustomers);

// Using the Progress pattern to handle progession during the synchronization
// We can use the same progress for each agent
var progress = new SynchronousProgress<ProgressArgs>(s =>
{
    Console.ForegroundColor = ConsoleColor.Green;
    Console.WriteLine($"{s.Context.SyncStage}:\t{s.Message}");
    Console.ResetColor();
});

var remoteProgress = new SynchronousProgress<ProgressArgs>(s =>
{
    Console.ForegroundColor = ConsoleColor.Yellow;
    Console.WriteLine($"{s.Context.SyncStage}:\t{s.Message}");
    Console.ResetColor();
});

// Spying what's going on the server side
agentProducts.AddRemoteProgress(remoteProgress);
agentCustomers.AddRemoteProgress(remoteProgress);


do
{
    Console.Clear();
    Console.WriteLine("Sync Start");
    try
    {
        Console.WriteLine("Hit 1 for sync Products. Hit 2 for sync customers and sales");
        var k = Console.ReadKey().Key;

        if (k == ConsoleKey.D1)
        {
            Console.WriteLine("Sync Products:");
            var s1 = await agentProducts.SynchronizeAsync(progress);
            Console.WriteLine(s1);
        }
        else
        {
            Console.WriteLine("Sync Customers and Sales:");
            var s1 = await agentCustomers.SynchronizeAsync(progress);
            Console.WriteLine(s1);
        }

    }
    catch (Exception e)
    {
        Console.WriteLine(e.Message);
    }
} while (Console.ReadKey().Key != ConsoleKey.Escape);

Console.WriteLine("End");
```

**Comment by mdonogma** [comment]
Love the flexibility, so much better than the azure offline sync. Yours is very fast in comparison with far more flexibility.



Sent from my iPhone

On 3 Feb 2020, at 19:27, Sébastien Pertus <notifications@github.com> wrote:

﻿

It's possible, if you are creating a multi scopes scenario.

How it's working ?
Each scope has its own schema with related tables.
Each scope has its own timestamp regarding its last sync.

Each time you sync one named scope, the sync will work based on metadatas saved in the scope table, for this named scope.

One thing to notice: Be sure you do not overlap table in two differents scopes.
If you have one table in each scope, it will most probably fail at some point.

// Create 2 Sql Sync providers
var serverProvider = new SqlSyncChangeTrackingProvider(DbHelper.GetDatabaseConnectionString(serverDbName));
var clientProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(clientDbName));

// Create 2 tables list (one for each scope)
string[] productScopeTables = new string[] { "ProductCategory", "ProductModel", "Product" };
string[] customersScopeTables = new string[] { "Address", "Customer", "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail" };

// Create 2 sync setup with named scope
var setupProducts = new SyncSetup(productScopeTables, "productScope");
var setupCustomers = new SyncSetup(customersScopeTables, "customerScope");

// Create 2 agents, one for each scope
var agentProducts = new SyncAgent(clientProvider, serverProvider, setupProducts);
var agentCustomers = new SyncAgent(clientProvider, serverProvider, setupCustomers);

// Using the Progress pattern to handle progession during the synchronization
// We can use the same progress for each agent
var progress = new SynchronousProgress<ProgressArgs>(s =>
{
    Console.ForegroundColor = ConsoleColor.Green;
    Console.WriteLine($"{s.Context.SyncStage}:\t{s.Message}");
    Console.ResetColor();
});

var remoteProgress = new SynchronousProgress<ProgressArgs>(s =>
{
    Console.ForegroundColor = ConsoleColor.Yellow;
    Console.WriteLine($"{s.Context.SyncStage}:\t{s.Message}");
    Console.ResetColor();
});

// Spying what's going on the server side
agentProducts.AddRemoteProgress(remoteProgress);
agentCustomers.AddRemoteProgress(remoteProgress);


do
{
    Console.Clear();
    Console.WriteLine("Sync Start");
    try
    {
        Console.WriteLine("Hit 1 for sync Products. Hit 2 for sync customers and sales");
        var k = Console.ReadKey().Key;

        if (k == ConsoleKey.D1)
        {
            Console.WriteLine("Sync Products:");
            var s1 = await agentProducts.SynchronizeAsync(progress);
            Console.WriteLine(s1);
        }
        else
        {
            Console.WriteLine("Sync Customers and Sales:");
            var s1 = await agentCustomers.SynchronizeAsync(progress);
            Console.WriteLine(s1);
        }

    }
    catch (Exception e)
    {
        Console.WriteLine(e.Message);
    }
} while (Console.ReadKey().Key != ConsoleKey.Escape);

Console.WriteLine("End");
