### ISSUE TITLE
Hello @Mimetis, I am having a similar issue trying to sync a table that has a computed column as primary key, the error looks like this:

### ISSUE THREAD

**Issue by yodiaz87** [Mimetis/Dotmim.Sync#204]
Hello @Mimetis, I am having a similar issue trying to sync a table that has a computed column as primary key, the error looks like this:
 ```Incorrect syntax near ','.```

Below is the definition of my table:
CREATE TABLE [dbo].[TableA](
	[id]  AS (isnull([idgenerator]+(1),(0))) PERSISTED NOT NULL,
	[name] [nchar](10) NOT NULL,
	[siteid] [int] NOT NULL,
	[idgenerator] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_TableA] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

Could you help me please??

_Originally posted by @yodiaz87 in https://github.com/Mimetis/Dotmim.Sync/issues/202#issuecomment-582116856_

**Comment by yodiaz87** [comment]
Hello @Mimetis ,
I can't change my primary key, is there another way to make the sync works?

**Comment by Mimetis** [comment]
*Copy / Paste my answer from closed issue :)*

Any "non writable" column is always removed from the list of syncable columns
The problem is that a primary key (writable) is required to make a sync.
So far, in your table, the only solution would be to:

- Set idgenerator as Primary key
- Set id as unique index

Otherwise it won't work with Dotmim.Sync

No, I don't think I can do something for this kind of situation (readonly primary key)

**Comment by yodiaz87** [comment]
Thank you very much for your always fast answer, I will see what I can do then.

**Comment by YoselYohan** [comment]
```
Hello @Mimetis  I changed my Primarykey to a composite Key by (IdGenerator and SiteId). TalbeAId in TableA is a computed column using a  deterministic function "dbo.CalculateId" with Schemabinding and a UNIQUE NONCLUSTERED index that will guarantee the creation of a unique value across all my sites. If I only replicate TableA I can see than column TableAId is null due to the fact that the function referenced in that column in the source is not moved to the destination. I understand that computed column "values" can not be replicated but as it is now, they will not be generated at destination by the lack of the the settings (formula and IsPersisted).


CREATE TABLE [dbo].[TableA](
	[TableAId]  AS (isnull(CONVERT([varchar](60),[dbo].[CalculateId]([SiteId],[IdGenerator])),'0')) PERSISTED NOT NULL,
	[FromTableA] [nvarchar](35) NOT NULL,
	[IdGenerator] [bigint] IDENTITY(1,1) NOT NULL,
	[SiteId] [int] NOT NULL,
 CONSTRAINT [PK_TableA] PRIMARY KEY CLUSTERED 
(
	[IdGenerator] ASC,
	[SiteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_TableA] UNIQUE NONCLUSTERED 
(
	[TableAId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TableA] ADD  CONSTRAINT [DF_TableA_SiteId]  DEFAULT ((1)) FOR [SiteId]
GO


CREATE TABLE [dbo].[TableB](
	[TableBId]  AS (isnull(CONVERT([varchar](60),[dbo].[CalculateId]([SiteId],[IdGenerator])),'0')) PERSISTED NOT NULL,
	[TableAId] [varchar](60) NOT NULL,
	[FromTableB] [nvarchar](35) NOT NULL,
	[IdGenerator] [bigint] IDENTITY(1,1) NOT NULL,
	[SiteId] [int] NOT NULL,
 CONSTRAINT [PK_TableB] PRIMARY KEY CLUSTERED 
(
	[IdGenerator] ASC,
	[SiteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TableB] ADD  CONSTRAINT [DF_TableB_SiteId]  DEFAULT ((1)) FOR [SiteId]
GO

ALTER TABLE [dbo].[TableB]  WITH CHECK ADD  CONSTRAINT [FK_TableB_TableA] FOREIGN KEY([TableAId])
REFERENCES [dbo].[TableA] ([TableAId])
GO

ALTER TABLE [dbo].[TableB] CHECK CONSTRAINT [FK_TableB_TableA]
GO




```

**Comment by Mimetis** [comment]
If you want it to be replicated on the client database, my advice is to create the schema on your own on the client, before launch the first sync.
The `Dotmim.Sync` process (for schema creation) is something like:

*If TableA does not exists on Client Then create TableA otherwise, do nothing*

So far, before sync, just create an empty client database, apply an empty schema and try to sync again.
You should be fine
Let me know if it's working :)

**Comment by YoselYohan** [comment]
Thank you for your quick response as always...I will try it as per your suggestion.
