### ISSUE TITLE
0.4 basic filter not working

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#205]
Tried basic filter against the Advertureworks DB and it doesn't filter.

Code:

      //Setup Filter
        var productDescriptionFilter = new SetupFilter("ProductDescriptionFilter");
        productDescriptionFilter.AddParameter("ProductDescriptionId", "ProductDescription", false);

        //Add filter
        clientSetup.Filters.Add(productDescriptionFilter);

        var agent = new SyncAgent(clientProvider, proxyClientProvider, clientSetup, clientOptions);

        //Custom Param
        if (!agent.Parameters.Contains("ProductDescriptionId"))
            agent.Parameters.Add("ProductDescriptionId", 3);

//It should only sync Product description with ID = 3

doesn't - all records are filtered.

**Comment by Mimetis** [comment]
``` cs
clientSetup.Filters.Add("ProductDescriptionFilter", "ProductDescriptionId");

var agent = new SyncAgent(clientProvider, proxyClientProvider, clientSetup, clientOptions);

//Custom Param
if (!agent.Parameters.Contains("ProductDescriptionId"))
        agent.Parameters.Add("ProductDescriptionId", 3);
```
Remember to restart from scratch to be sure all the stored proc will be re-generated

**Comment by mdonogma** [comment]
Aah so if I change a filter on existing deployment I need to flush out all existing stored prices on dB the try sync again with new filter?

Sent from my iPhone

On 6 Feb 2020, at 08:18, Sébastien Pertus <notifications@github.com> wrote:

﻿

clientSetup.Filters.Add("ProductDescriptionFilter", "ProductDescriptionId");

var agent = new SyncAgent(clientProvider, proxyClientProvider, clientSetup, clientOptions);

//Custom Param
if (!agent.Parameters.Contains("ProductDescriptionId"))
        agent.Parameters.Add("ProductDescriptionId", 3);

Remember to restart from scratch to be sure all the stored proc will be re-generated

**Comment by mdonogma** [comment]
Does framework have command to flush out all stored price for all tables. That way I can call it when needed.

I assume it would need to flush client and server stored profs or just server ?

Sent from my iPhone

On 6 Feb 2020, at 08:18, Sébastien Pertus <notifications@github.com> wrote:

﻿

clientSetup.Filters.Add("ProductDescriptionFilter", "ProductDescriptionId");

var agent = new SyncAgent(clientProvider, proxyClientProvider, clientSetup, clientOptions);

//Custom Param
if (!agent.Parameters.Contains("ProductDescriptionId"))
        agent.Parameters.Add("ProductDescriptionId", 3);

Remember to restart from scratch to be sure all the stored proc will be re-generated

**Comment by mdonogma** [comment]
Downloaded latest master (with 0.4 changes)
Deleted both DB's
Recreated adventureworks using your script
Applied filter exactly per above.
same result - all records are synchronised. (all exist on client and server).

Here's exact code + attachment shows client and server records 
<img width="922" alt="Screen Shot 2020-02-06 at 6 03 13 pm" src="https://user-images.githubusercontent.com/13458476/73917416-18565380-490b-11ea-8b04-55d6bf7b6dc1.png">

 var clientProvider = new SqlSyncProvider(connectionString);

        var handler = new HttpClientHandler { AutomaticDecompression = DecompressionMethods.GZip };
        var client = new HttpClient(handler) { Timeout = TimeSpan.FromMinutes(5) };

        var proxyClientProvider = new WebClientOrchestrator("http://localhost:5000/api/Sync", null, null, client);

        // ----------------------------------
        // Client side
        // ----------------------------------
        var clientOptions = new SyncOptions
        {
            ScopeInfoTableName = "client_scopeinfo",
            BatchDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDiretory(), "sync_client"),
            BatchSize = 50,
            CleanMetadatas = true,
            UseBulkOperations = true,
            UseVerboseErrors = false,
        };

        var clientSetup = new SyncSetup
        {
            StoredProceduresPrefix = "cli",
            StoredProceduresSuffix = "",
            TrackingTablesPrefix = "cli",
            TrackingTablesSuffix = "",
            TriggersPrefix = "",
            TriggersSuffix = "",
        };

        clientSetup.Filters.Add("ProductDescriptionFilter", "ProductDescriptionId");

        var agent = new SyncAgent(clientProvider, proxyClientProvider, clientSetup, clientOptions);

        //Custom Param
        if (!agent.Parameters.Contains("ProductDescriptionId"))
            agent.Parameters.Add("ProductDescriptionId", 3);

        Console.WriteLine("Press a key to start (be sure web api is running ...)");
        Console.ReadKey();
        do
        {
            Console.Clear();
            Console.WriteLine("Web sync start");
            try
            {
                var progress = new SynchronousProgress<ProgressArgs>(pa => Console.WriteLine($"{pa.Context.SessionId} - {pa.Context.SyncStage}\t {pa.Message}"));

                var s = await agent.SynchronizeAsync(progress);

                Console.WriteLine(s);

            }
            catch (SyncException e)
            {
                Console.WriteLine(e.ToString());
            }
            catch (Exception e)
            {
                Console.WriteLine("UNKNOW EXCEPTION : " + e.Message);
            }


            Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");
        } while (Console.ReadKey().Key != ConsoleKey.Escape);

        Console.WriteLine("End");

**Comment by Mimetis** [comment]
## Flush

Use the [Provision and Deprovision](https://mimetis.github.io/Dotmim.Sync/Provision) methods

## Filters

The filter should be applied on the server side, when used on http mode

Here is an example of the `Startup.cs` file, from the server ASP.Net Core side:

``` cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

    // Mandatory to be able to handle multiple sessions
    services.AddMemoryCache();

    // Get a connection string for your server data source
    var connectionString = Configuration.GetSection("ConnectionStrings")["DefaultConnection"];

    // Set the web server Options
    var options = new WebServerOptions()
    {
        BatchDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDiretory(), "server"),
        SnapshotsDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Snapshots")
    };


    // Create the setup used for your sync process
    var tables = new string[] {"ProductCategory",
    "ProductDescription", "ProductModel",
    "Product", "ProductModelProductDescription",
    "Address", "Customer", "CustomerAddress",
    "SalesOrderHeader", "SalesOrderDetail" };

    var setup = new SyncSetup(tables)
    {
        // optional :
        StoredProceduresPrefix = "server",
        StoredProceduresSuffix = "",
        TrackingTablesPrefix = "server",
        TrackingTablesSuffix = ""
    };

    setup.Filters.Add("ProductDescriptionFilter", "ProductDescriptionId");

    // add a SqlSyncProvider acting as the server hub
    services.AddSyncServer<SqlSyncProvider>(connectionString, setup, options);
}
```
On the client side, remove `clientSetup.Filters.Add("ProductDescriptionFilter", "ProductDescriptionId");`

**Comment by mdonogma** [comment]
If the filter is server side:
1. How do I pass the parameter from the client?
2. Can the parameter be different per client. Example userA can pass 1 for Id, for userB it can be ID=2

**Comment by Mimetis** [comment]
The agent contains the parameter, from the client side

``` cs
 //Custom Param
    if (!agent.Parameters.Contains("ProductDescriptionId"))
        agent.Parameters.Add("ProductDescriptionId", 3);
```

And yes, obviously, users can pass differents values

**Comment by mdonogma** [comment]
Deleted both DB's
Created them again
Moved the filter to server as suggested above
Passed the param from client per suggestion above.

Still does not filter based on the parameter passed.

CLIENT CODE:
private static async Task TestSyncThroughWebApi()
    {
        var clientProvider = new SqlSyncProvider(connectionString);

        var handler = new HttpClientHandler { AutomaticDecompression = DecompressionMethods.GZip };
        var client = new HttpClient(handler) { Timeout = TimeSpan.FromMinutes(5) };

        var proxyClientProvider = new WebClientOrchestrator("http://localhost:5000/api/Sync", null, null, client);

        // ----------------------------------
        // Client side
        // ----------------------------------
        var clientOptions = new SyncOptions
        {
            ScopeInfoTableName = "client_scopeinfo",
            BatchDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDiretory(), "sync_client"),
            BatchSize = 50,
            CleanMetadatas = true,
            UseBulkOperations = true,
            UseVerboseErrors = false,
        };
        var tables = new string[] { "ProductDescription" };

        var clientSetup = new SyncSetup(tables)
        {
            StoredProceduresPrefix = "cli",
            StoredProceduresSuffix = "",
            TrackingTablesPrefix = "cli",
            TrackingTablesSuffix = "",
            TriggersPrefix = "",
            TriggersSuffix = "",
        };

     
        var agent = new SyncAgent(clientProvider, proxyClientProvider, clientSetup, clientOptions);

        //Custom Param
        if (!agent.Parameters.Contains("ProductDescriptionId"))
            agent.Parameters.Add("ProductDescriptionId", 3);

        Console.WriteLine("Press a key to start (be sure web api is running ...)");
        Console.ReadKey();
        do
        {
            Console.Clear();
            Console.WriteLine("Web sync start");
            try
            {
                var progress = new SynchronousProgress<ProgressArgs>(pa => Console.WriteLine($"{pa.Context.SessionId} - {pa.Context.SyncStage}\t {pa.Message}"));

                var s = await agent.SynchronizeAsync(progress);

                Console.WriteLine(s);

            }
            catch (SyncException e)
            {
                Console.WriteLine(e.ToString());
            }
            catch (Exception e)
            {
                Console.WriteLine("UNKNOW EXCEPTION : " + e.Message);
            }


            Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");
        } while (Console.ReadKey().Key != ConsoleKey.Escape);

        Console.WriteLine("End");

    }

SERVER CODE:
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

            // Mandatory to be able to handle multiple sessions
            services.AddMemoryCache();

            // Get a connection string for your server data source
         var connectionString = Configuration.GetSection("ConnectionStrings")["DefaultConnection"];
          

            // Set the web server Options
            var options = new WebServerOptions()
            {
                BatchDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDiretory(), "server"),
                SnapshotsDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Snapshots")
            };

            var tables = new string[] { "ProductDescription"};

            var setup = new SyncSetup(tables)
            {
                // optional :
                StoredProceduresPrefix = "server",
                StoredProceduresSuffix = "",
                TrackingTablesPrefix = "server",
                TrackingTablesSuffix = ""
            };

            setup.Filters.Add("ProductDescriptionFilter", "ProductDescriptionId");

            // add a SqlSyncProvider acting as the server hub
            services.AddSyncServer<SqlSyncProvider>(connectionString, setup, options);
        }

**Comment by mdonogma** [comment]
Champion! Worked after moving the filter to the server.
Will be good if the example you gave can indicate both scenarios to make it easier for newbees

**Comment by Mimetis** [comment]
Indeed, I will update the doc asap
