### ISSUE TITLE
timeouts settings don't work

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#206]
Used latest build, the timeout in web.config indicates 20 minutes.

It times out within 20 seconds.

![Screen Shot 2020-02-07 at 3 22 35 pm](https://user-images.githubusercontent.com/13458476/74003273-c28eb380-49bd-11ea-9217-1d2af96b2df5.png)

**Comment by Mimetis** [comment]
Is it happening when you're initializing a new client ?

Maybe you should prepare a Snapshot before sync. This way, the server will not be under heavy pressure on a first call.
See documentation here: https://mimetis.github.io/Dotmim.Sync/Snapshot

**Comment by mdonogma** [comment]
It's not that. 

Config: 21 tables. Each with 1 filter.

Sync works fine when small amount of data in DB.

When we hit about 10000 rows per table the timeout happens on every sync.

in less than 1 min it times out.

Used your default project from master + extra tables + 1 filter per table.
SQL Connection string is set to 10 minute timeout.

**Comment by mdonogma** [comment]
Another error is popping up - Dotmim.Sync.SyncException: too much batches !!!

**Comment by Mimetis** [comment]
Wow, too much batches, because you reach for **1** sync, more than **999** batches :o

My advice : Make a `Batchsize` between 2000 and 5000. Less is to lightweight, more is probably too heavy.
By the way a `Batchsize = 0` means *no batch* so *everything in memory*
No batch could be ok when running locally on **tcp** but can be dangerous in **http**

I can't do nothing for timeout, it's ASP.Net Core behavior.
If the [timeout section](https://mimetis.github.io/Dotmim.Sync/Timeout) is not working for you, I don't have any other solution.

**Comment by mdonogma** [comment]
Why the 999 batch limit? Can this be increased?

Sent from my iPhone

On 9 Feb 2020, at 03:45, Sébastien Pertus <notifications@github.com> wrote:

﻿

Wow, too much batches, because you reach for 1 sync, more than 999 batches :o

My advice : Make a Batchsize between 2000 and 5000. Less is to lightweight, more is probably too heavy.
By the way a Batchsize = 0 means no batch so everything in memory
No batch could be ok when running locally on tcp but can be dangerous in http

I can't do nothing for timeout, it's ASP.Net Core behavior.
If the timeout section<https://mimetis.github.io/Dotmim.Sync/Timeout> is not working for you, I don't have any other solution.

**Comment by Mimetis** [comment]
It's hard coded.
Why don't you test to increase batch size?

**Comment by mdonogma** [comment]
The web config timeout setting works with release mode but not debug for some reason.

This fixes it for both:


public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseKestrel(o => { o.Limits.KeepAliveTimeout = TimeSpan.FromMinutes(10); })
        .Build();

Sent from my iPhone

On 9 Feb 2020, at 08:08, Sébastien Pertus <notifications@github.com> wrote:

﻿It's hard coded.
Why don't you test to increase batch size?
