### ISSUE TITLE
Dotmim.Sync.SyncException: Synchronization already in progress 

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#207]
using HTTP Sync:

TO repro this: Dotmim.Sync.SyncException: Synchronization already in progress 

Stop you Sync Server
Run the Client - it will return an error :Dotmim.Sync.SyncException: Connection refused -
Start the sync server
Don't stop the client console - just click key so it reruns. 
result: Dotmim.Sync.SyncException:TO repro this: Dotmim.Sync.SyncException: Synchronization already in progress 

Have to shutdown console and server - sometimes it allows me to continue - else I have to flush out the DB's and try again.

**Comment by Mimetis** [comment]
Hey, I get it !
I fixed the issue in the last commit :
https://github.com/Mimetis/Dotmim.Sync/commit/36cf9b0f73745a91087e8570f60d759b5b5a3e14
