### ISSUE TITLE
batch directory - security pen testing

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#208]
Security pen testing are going to flag these batch directories.

I see it writes to disk.

Essentially it doesn't help having encrypted SQL DB on server and client if the data is being written to tmp folder.

Is there a way to do the batching in memory , then flush out memory when sync complete?

**Comment by Mimetis** [comment]
Nop

If yo set `BatchSize = 0` then everything will run in memory with no batch, but you will be in a big trouble if you are in **Http** mode, because you will send only one Huge request to your client, that could potentially fail

**Comment by mdonogma** [comment]
How about an option to encrypt and decrypt what gets written to disk. That way if drive was hacked the data is as secure as the encrypted SQLite dB.

**Comment by Mimetis** [comment]
Good point, let me think about it

**Comment by Mimetis** [comment]
This issue has been fixed with the release of the version `v0.5`.
If you still experiencing the same bug, please comment here, I will re-open the issue.

Encryption sample : https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/Encryption
