### ISSUE TITLE
Filter thats value can change in DB?

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#209]
Filters don't appear to like the value in the record changing.

Example; Filter call Archived (Boolean).

We need to be able to tag a record as archived so only admins can see archived records. 

On first sync the Archived=false records show on the client.
When updating all records on server to Archived = true.
Result: The client does nothing.
Its like the client records are fixed to the original value of the filter and does not check if server value has changed on the filter column.

**Comment by Mimetis** [comment]
It's not possible in this release
I'm actually working on a new system where this scenario will work, but it's damn not easy at all

For now, if the filter value is changing it's just not sent to the client, because it's not part of the filter value for this client
