### ISSUE TITLE
SqlSyncChangeTrackingProvider - tracking tables created on client

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#211]
When filters are used - do the tracking tables contain the info on filtered records or does the table try track the entire server table?

Reason: this could be problematic with large DB's. Example: If I have 100000 customers in DB and  each client should only have access to approx 1000 records. Why would I need the entire 100000 info tracked in tracking table

see screenshot
<img width="498" alt="Screen Shot 2020-02-08 at 6 18 14 pm" src="https://user-images.githubusercontent.com/13458476/74081929-11ad1500-4aa0-11ea-9477-8eba80e257fe.png">

**Comment by Mimetis** [comment]
For `SqlSyncChangeTrackingProvider ` there is no *tracking* tables
And the filter depends on your `sp_table_changes` stored procedure

So far, if you're client is correctly configured, it will have only filtered records

**Comment by mdonogma** [comment]
I think this is happening because the app is running SQLite and server is running sql server.?

Looks like both dbs need to be sqlserver in order to use  the change tracking provider. Pls confirm?
Sent from my iPhone

On 9 Feb 2020, at 03:47, Sébastien Pertus <notifications@github.com> wrote:

﻿

For SqlSyncChangeTrackingProvider there is no tracking tables
And the filter depends on your sp_table_changes stored procedure

So far, if you're client is correctly configured, it will have only filtered records

**Comment by mdonogma** [comment]
In scenario where SqlSyncChangeTrackingProvider  is used. Will tracking tables be created if client is SQLite and server is sql server .  Documentation indicates it will only work in scenario where both client and server sql server db’s. just wanting to confirm

**Comment by Mimetis** [comment]
Yes

Will update the doc to be sure it's better explained
