### ISSUE TITLE
Timeout fix

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#212]
For those battling with timeouts when in debug mode.

This fixes it:
public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseKestrel(o => { o.Limits.KeepAliveTimeout = TimeSpan.FromMinutes(10); })
        .Build();

The webconfig setting only appears to work when deployed / running in release mode

**Comment by Mimetis** [comment]
Thank you !! I will add it to the documentation
