### ISSUE TITLE
Option to include SET NOTCOUNT ON in SQL Server triggers

### ISSUE THREAD

**Issue by YoselYohan** [Mimetis/Dotmim.Sync#213]
Hi,
Looking at the code there is nothing available to set this option on. In our queries we are expecting only one record to be modified (Updated/Deleted)  and the lack of this functionality is giving us an error. I know in other database types this is not available but in SQL Server this could be problematic. In our case just placing  SET NOTCOUNT ON at  the beginning of the triggers solved the problem. Do you have a solution for this issue?

Thank you very much for this framework...GREAT JOB!!!

```
       ...
                    var insTriggerName = this.sqlObjectNames.GetCommandName(DbCommandType.InsertTrigger).name;
                    var createTrigger = new StringBuilder($"CREATE TRIGGER {insTriggerName} ON {tableName.Schema().Quoted().ToString()} FOR INSERT AS");
                    createTrigger.AppendLine();
                    createTrigger.AppendLine(this.InsertTriggerBodyText());
...
    private string InsertTriggerBodyText()
        {
            var stringBuilder = new StringBuilder();
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("-- If row was deleted before, it already exists, so just make an update");
            stringBuilder.AppendLine("UPDATE [side] ");
            stringBuilder.AppendLine("SET  [sync_row_is_tombstone] = 0");
```

**Comment by Mimetis** [comment]
Yes, I can definitively.
But can you explaned a little bit, what kind of issues you're facing "without" nocount on ?

Thx

**Comment by YoselYohan** [comment]
For instance ExecuteNonQuery returns the number of rows affected. We have wrapper around this function expecting One, ZeroOrOne, or Ignore. the First two are being used all over the place to avoid updating/deleting multiple records by mistake when forgot to add a WHERE or the filter criteria return more that the amount of expected records to be updated/deleted.

**Comment by YoselYohan** [comment]
We have a function in the system. We could send in the last parameter ExpectedRows.Ignore but in our case will bypass the safety check.
```
  public static int Execute(this SqlUpdate query, IDbConnection connection, ExpectedRows expectedRows = ExpectedRows.One)
        {
            return CheckExpectedRows(expectedRows, ExecuteNonQuery(connection, query.ToString(), query.Params));
        }

        private static int CheckExpectedRows(ExpectedRows expectedRows, int affectedRows)
        {
            if (expectedRows == ExpectedRows.Ignore)
                return affectedRows;

            if (expectedRows == ExpectedRows.One && affectedRows != 1)
                throw new InvalidOperationException(String.Format(ExpectedRowsError, affectedRows, 1));

            if (expectedRows == ExpectedRows.ZeroOrOne && affectedRows > 1)
                throw new InvalidOperationException(String.Format(ExpectedRowsError, affectedRows, "0 or 1"));

            return affectedRows;
        }
```

**Comment by Mimetis** [comment]
Ok, got it. It makes perfectly sense !

Will make a quick fix on the master branch to add the nocount in the triggers

**Comment by yodiaz87** [comment]
Thank you @Mimetis

**Comment by Mimetis** [comment]
You should be able to test it with the last commit on the master branch.

Reopen the issue if you're still facing some issues

**Comment by YoselYohan** [comment]
It works great!. Thank you.
