### ISSUE TITLE
null values cause sync to fail

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#216]
![image](https://user-images.githubusercontent.com/13458476/74582463-dd89a500-5007-11ea-887e-acf679cf5e82.png)

Dotmim.Sync.SyncException: Value cannot be null.
Parameter name: Table AttributesCategories does not exist in the SyncSet ---> System.ArgumentNullException: Value cannot be null.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/13458476/74582470-f003de80-5007-11ea-9faa-9f9e6ea96339.png">

**Comment by Mimetis** [comment]
Need more info.
Maybe you have a filtered table without a column that can't be null.
But I need more info to help you

**Comment by mdonogma** [comment]
Silly me, fields are set to not allow nulls
