### ISSUE TITLE
'timestamp' Column (type datetime)

### ISSUE THREAD

**Issue by andreasfromch** [Mimetis/Dotmim.Sync#217]
Great library - thank you :-)!!!

I’ve a Column 'timestamp' (type datetime) on each of my tables. Therefore, it’s currently no possible to sync the tables. Because this is in a productive database with another sync mechanism it would be quite difficult to rename the field. Is the marked statement in the screenshot still in use?
And if yes, do you have a hint for me to solve this "problem"?

![timestamp](https://user-images.githubusercontent.com/30843010/74584869-1fe6be00-4fd7-11ea-882f-62dbfb669029.png)

**Comment by Mimetis** [comment]
I'm sorry, actually, the problem is that I'm using a column named timestamp in the tracking tables, and so far, in all stored procedures and triggers.
It would be too complicated to change this code to take into account custom fields.
