### ISSUE TITLE
Open DataReader with command must be closed

### ISSUE THREAD

**Issue by champcbg** [Mimetis/Dotmim.Sync#221]
The sync works fine, I am testing against several clients at the same time.  When the filter setup gets added

```
var vbSetupFilter = new SetupFilter("vbSetup", "VBConfig");
            vbSetupFilter.AddParameter("UserId", "vbSetup", "VBConfig");
            vbSetupFilter.AddWhere("UserId", "vbSetup", "userId", "VBConfig");
            syncSetup.Filters.Add(vbSetupFilter);
```

and 

```
            if (!syncAgent.Parameters.Contains("UserId"))
            {
                syncAgent.Parameters.Add("UserId", "29AE2BFC-5685-434B-1B75-08D76379C24D");
            }

```

then the executing the synchronize

`var syncContext = await syncAgent.SynchronizeAsync(progress);`

throws the following exception **'There is already an open DataReader associated with this Command which must be closed first.'**

**Comment by Mimetis** [comment]
I think your problem come from the fact you have modified your sync setup.
In that case, all stored procedure / tracking table / triggers have to be regenerated.

So far, two solutions:
- Start with a fresh database
- Use the `Provision` and `Deprovision` methods

Let me know

**Comment by champcbg** [comment]
I just tried with 2 fresh sqlite databases and got the same error.

**Comment by Mimetis** [comment]
I think you have a bad filter.
Regarding your schema, shared in issue #219, here is my version:

```
var vbSetupFilter = new SetupFilter("vbSetup", "vbs");
vbSetupFilter.AddParameter("UserId", "vbSetup", "vbs");
vbSetupFilter.AddWhere("UserId", "vbSetup", "userId", "vbs");
        
syncSetup.Filters.Add(vbSetupFilter);
```
You have an error in the *schemaName* property

Using this, it worked for me

let me know

**Comment by champcbg** [comment]
I have habit of renaming tables and schemas when posting sorry.

The schema and table names in the actual code match the schema and table names that i added in the tables array.

**Comment by Mimetis** [comment]
Here is what I tried

``` sql
CREATE TABLE [vbs].[VBSetup](
	[Id] [uniqueidentifier] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[Name] [nvarchar](128) NOT NULL,
	[Description] [nvarchar](2048) NOT NULL,
	[PlannedStartDate] [date] NOT NULL,
	[PlannedAccomplishDate] [date] NOT NULL,
	[SnapshotUrl] [nvarchar](128) NULL,
	[ShortCode] [nvarchar](32) NOT NULL,
	[UserId] [uniqueidentifier] NOT NULL,
	[ModifiedAt] [datetimeoffset](7) NULL,
	[CreatedAt] [datetimeoffset](7) NOT NULL,
	[IsPublished] [bit] NOT NULL,
	[PublishedAt] [datetimeoffset](7) NULL,
 CONSTRAINT [PK_VisionBoardSetup] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
```


``` cs
var serverProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(serverDbName));
var clientProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(clientDbName));

// Create the setup used for your sync process
var tables = new string[] { "[vbs].VBSetup", };

//  [Optional] : database setup
var syncSetup = new SyncSetup(tables)
{
    // optional :
    StoredProceduresPrefix = "sync_",
    StoredProceduresSuffix = "",
    TrackingTablesPrefix = "sync_",
    TrackingTablesSuffix = "",
    ScopeName = "SStGMobile_Sync",
    TriggersPrefix = "sync",
};

var vbSetupFilter = new SetupFilter("vbSetup", "vbs");
vbSetupFilter.AddParameter("UserId", "vbSetup", "vbs");
vbSetupFilter.AddWhere("UserId", "vbSetup", "userId", "vbs");

syncSetup.Filters.Add(vbSetupFilter);

var syncAgent = new SyncAgent(clientProvider, serverProvider, syncSetup);

// Using the IProgress<T> pattern to handle progession dring the synchronization
// Be careful, Progress<T> is not synchronous. Use SynchronousProgress<T> instead !
var progress = new SynchronousProgress<ProgressArgs>(s => Console.WriteLine($"{s.Context.SyncStage}:\t{s.Message}"));

var syncContext = await syncAgent.SynchronizeAsync(progress);
```

Can you try this version and report if it's working for you ?

**Comment by champcbg** [comment]
Got it to work when there were no records in the database.

When I use the existing table with records already in it, then i get the  initial error **'There is already an open DataReader associated with this Command which must be closed first.'**

**Comment by Mimetis** [comment]
Did you reset **also** the server database ?

**Comment by champcbg** [comment]
Sorry didnt explain that well.  It worked when the The Server (Master) DB Table was empty.  

When the Server (Master) DB table had existing records then the error wold come up.

Every time I run a new test i reset the sync DB(s) and also change scopeName, so that it use the current set of changes.

**Comment by Mimetis** [comment]
Please send me a sample repro with your server db schema and some lines in it, I want to test and figure out what happened

**Comment by champcbg** [comment]
The create a repo to send to you, created 2 new tables, an empty table and table with the existing 144 records.  I was doing this to send you the scripts and the data.

When I ran a test against the new tables to make sure everything worked before i packaged everything up to send over it worked.  From the report below you will see it sync 7 records which match the filter exactly.  

**Sync Start
BeginSession:   7:03:11 AM.538
ScopeLoading:   7:03:13 AM.534   Id:f4d9914b-d1d9-47a4-ab6e-1f2e115f1cac LastSync: LastSyncDuration:0
TableSchemaApplied:     7:03:16 AM.608   TableName: VBSetup Provision:All
SchemaApplied:  7:03:16 AM.609   Tables count:1 Provision:All
TableChangesApplied:    7:03:17 AM.375   VBSetup State:Modified Applied:7 Failed:0
DatabaseChangesApplied: 7:03:17 AM.377   Changes applied on database main: Applied: 7 Failed: 0
ScopeSaved:     7:03:17 AM.385   Id:f4d9914b-d1d9-47a4-ab6e-1f2e115f1cac LastSync:2/21/2020 12:03:17 PM LastSyncDuration:60597987
EndSession:     7:03:17 AM.386
Synchronization done.
        Total changes downloaded: 7
        Total changes uploaded: 0
        Total conflicts: 0
        Total duration :0:0:6.59
Sync Complete**

I clearly see I made a mistake somewhere in my testing, looking through the SPROC's, there are additional sprocs built for the filter which are on the new tables, but not on the original one, which means it never got created.  Which to early message would of been solved with the Provision & Deprovision.  I had tried Provision & Deprovision before but got an error, and figured i was doing to much at one time, so i commented the code out.

Thanks for the help and patience.  I am going to add Provision & Deprovision and keep testing.

**Comment by Mimetis** [comment]
Nice :)

It's something I see often. 
Changing the `SyncSetup` over time, and then everything broke..

We may have something to handle this scenario. Being able to make the schema evolving, depending on the evolution of your `SyncSetup` instance.

I'm actually looking into this.

Thanks for sharing

**Comment by champcbg** [comment]
> We may have something to handle this scenario. Being able to make the schema evolving, depending on the evolution of your SyncSetup instance.
> 
> I'm actually looking into this.

That would be great!
