### ISSUE TITLE
No sql (mongodb/ couchDB) support

### ISSUE THREAD

**Issue by ishamfazal** [Mimetis/Dotmim.Sync#225]
Is there anyway i could use this for mongodb or couchdb? Or any plans on implementing it? Would be a great help if i can get it done through this. Thanks in advance

**Comment by Mimetis** [comment]
nop, sorry, this Framework is all about relational databases (supporting schema tables, stored procedures, and triggers)

Maybe one day, in a long future, I will take a look on what is possible with No SQL databases, but it will be another framework I guess.
