### ISSUE TITLE
Server setup - multiple sync servers

### ISSUE THREAD

**Issue by mdonogma** [Mimetis/Dotmim.Sync#228]
In you document it shows how to setup webapi services.AddSyncServer<SqlSyncProvider>(connectionString, setup, options);

Question: is it possible to add multiple sync servers each with different tables , scopes and filters.

Essentially try to setup two scopes client side that connect to webapi for sync

First scope should sync with table 1,2,3,4,5

Second scope should sync with table 1,6,7,8,9 

I want to reduce the amount of server side tables to align with the list of tables in each of the scopes when needed.

It’s a performance thing: when too many tables in the server setup it takes long to sync . If I could split the tables server side using different sync servers.

Hope that makes sense.

**Comment by Mimetis** [comment]
This issue has been fixed with the release of the version `v0.5`.
If you still experiencing the same bug, please comment here, I will re-open the issue.
