### ISSUE TITLE
Could not find stored procedure 'sp_msforeachtable'

### ISSUE THREAD

**Issue by dgrothman** [Mimetis/Dotmim.Sync#230]
Upgrading from .3 to .4 and I have deprovisioned the old tracking tables, triggers and stored procedures. I then created new .4 ones using 
```
Task.WaitAll(serverProvider.ProvisionAsync(syncSet,
                    SyncProvision.Triggers | SyncProvision.TrackingTable | SyncProvision.StoredProcedures));
```
Everything syncs down from the server to the client just fine, but when I try and sync anything from client to server the client errors out  
 ```
Upload TableChangesSelected:     4:20:17 PM.135  Practices Upserts:0 Deletes:0 TotalChanges:0 
Upload TableChangesSelected:     4:20:17 PM.148   AspNetRoles Upserts:0 Deletes:0 TotalChanges:0
Upload TableChangesSelected:     4:20:17 PM.157   AspNetUserTokens Upserts:0 Deletes:0 TotalChanges:0
Upload TableChangesSelected:     4:20:17 PM.168   AspNetUsers Upserts:0 Deletes:0 TotalChanges:0 
Upload TableChangesSelected:     4:20:17 PM.176   AspNetUserRoles Upserts:0 Deletes:0 TotalChanges:0
Upload TableChangesSelected:     4:20:17 PM.185   Locations Upserts:0 Deletes:0 TotalChanges:0 
Upload TableChangesSelected:     4:20:17 PM.200   Patients Upserts:5 Deletes:0 TotalChanges:5 
Upload TableChangesSelected:     4:20:17 PM.208   PracticeSettings Upserts:0 Deletes:0 TotalChanges:0
Upload TableChangesSelected:     4:20:17 PM.223   Scans Upserts:15 Deletes:0 TotalChanges:15 
Upload TableChangesSelected:     4:20:17 PM.487   ScanData Upserts:166 Deletes:0 TotalChanges:166 
Upload TableChangesSelected:     4:20:17 PM.501   Exams Upserts:5 Deletes:0 TotalChanges:5
[16:20:20 ERR] [SyncService] Error during sync: Could not find stored procedure 'sp_msforeachtable'. 
```

**Comment by dgrothman** [comment]
Here is the syncSet info:
```
var syncSet = serverProvider.ReadSchema(syncSetup, connection, null);
                syncSet.StoredProceduresPrefix = "ds";
                syncSet.StoredProceduresSuffix = "";
                syncSet.TrackingTablesPrefix = "ds";
                syncSet.TrackingTablesSuffix = "";
                syncSet.TriggersPrefix = "ds";
                syncSet.TriggersSuffix = "";
```

**Comment by Mimetis** [comment]
What is the version of your server database ?

If your server database does not support `sp_msforeachtable`, try to set the option `Options.DisableConstraintsOnApplyChanges = false;`

**Comment by dgrothman** [comment]
our server database is an azure Sql database. It looks like azure doesn't support that. I will try the options setting.

**Comment by Mimetis** [comment]
Let me know if it's working with the setting.
Anyway, I will find a way to make it work on Azure

**Comment by dgrothman** [comment]
I changed the option and it got through that error and now is responding with 
`Error during sync: An SqlParameter with ParameterName '@changeTable' is not contained by this SqlParameterCollection.`

**Comment by dgrothman** [comment]
After about 10 tries that error went away and this one is back.
`Error during sync: Cannot implicitly convert type 'decimal' to 'float'. An explicit conversion exists (are you missing a cast?)`
I am running the master branch with the changes you fixed for that issue for the package Dotmim.Sync.Core. I am running the 0.4.3 versions of the other packages.

**Comment by Mimetis** [comment]
can you share with me the schema you're trying to sync ? (at least the table which seems to make this issue happening) ?
I suppose the clients are sqlite ?

**Comment by dgrothman** [comment]
yes its sqlite, let me find out what table its crashing on

**Comment by dgrothman** [comment]
Here is the exception for the first SqlParameter error
```
System.IndexOutOfRangeException: An SqlParameter with ParameterName '@changeTable' is not contained by this SqlParameterCollection.
   at System.Data.SqlClient.SqlParameterCollection.GetParameter(String parameterName)
   at System.Data.SqlClient.SqlParameterCollection.get_Item(String parameterName)
   at Dotmim.Sync.SqlServer.Builders.SqlSyncAdapter.ExecuteBatchCommand(DbCommand cmd, Guid senderScopeId, IEnumerable`1 applyRows, SyncTable schemaChangesTable, SyncTable failedRows, Int64 lastTimestamp)
   at Dotmim.Sync.DbSyncAdapter.ApplyBulkChanges(Guid localScopeId, Guid senderScopeId, SyncTable changesTable, Int64 lastTimestamp, List`1 conflicts)
   at Dotmim.Sync.CoreProvider.ApplyChangesInternalAsync(SyncTable schemaTable, SyncContext context, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, DataRowState applyType, DatabaseChangesApplied changesApplied, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.CoreProvider.ApplyChangesAsync(SyncContext context, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.RemoteOrchestrator.ApplyThenGetChangesAsync(SyncContext context, ScopeInfo scope, SyncSet schema, BatchInfo clientBatchInfo, Boolean disableConstraintsOnApplyChanges, Boolean useBulkOperations, Boolean cleanMetadatas, Boolean cleanFolder, Int32 clientBatchSize, String batchDirectory, ConflictResolutionPolicy policy, CancellationToken cancellationToken, IProgress`1 progress)
```
I am still trying to get a breakpoint to find out what table its crashing on

**Comment by dgrothman** [comment]
The SqlParameter is happening on the Practices Table I have attached the Sql schema
![Screen Shot 2020-02-27 at 12 30 42 PM](https://user-images.githubusercontent.com/10801916/75484169-19ecc780-595d-11ea-8d34-cf1c5d031566.png)

I have the following filters in use on the server side
```
syncSetup.Filters.Add("Practices", "Id");
                syncSetup.Filters.Add("AspNetUsers","PracticeId");
                syncSetup.Filters.Add("Locations","PracticeId");
                syncSetup.Filters.Add("Patients","PracticeId");
                syncSetup.Filters.Add("PracticeSettings","PracticeId");
                syncSetup.Filters.Add("Scans","PracticeId");
                syncSetup.Filters.Add("ScanData","PracticeId");
                syncSetup.Filters.Add("Exams","PracticeId");
```
and on the client side
```
if (!_agent.Parameters.Contains("Id"))
                    _agent.Parameters.Add("Id", _pracId);
                if (!_agent.Parameters.Contains("PracticeId"))
                    _agent.Parameters.Add("PracticeId", _pracId);
```

**Comment by dgrothman** [comment]
Disregaurd previous post, I believe it is crashing on the Patients Table here is that Sql schema
![Screen Shot 2020-02-27 at 12 40 02 PM](https://user-images.githubusercontent.com/10801916/75484797-4f45e500-595e-11ea-90b4-dd4767909cef.png)

**Comment by Mimetis** [comment]
Strange, because you don't have decimal / float column in this table

**Comment by dgrothman** [comment]
That was for the first error `Error during sync: An SqlParameter with ParameterName '@changeTable' is not contained by this SqlParameterCollection.`, I am still trying to get the second error to show up

**Comment by dgrothman** [comment]
So I just got a complete sync by setting `UseBulkOperations = false`

**Comment by dgrothman** [comment]
I will keep working to see if I can get the second error to show up, but i couldn't debug it any deeper than ApplyBulkChanges inside ApplyChangesInternalAsync in CoreProvider.cs. Let me know if I can get you any more information.

**Comment by dgrothman** [comment]
I found out the second error was due to another developer pushing an update that didn't have the fixes you already applied. Sorry for the mix up there. But I would be curious about the first error.

**Comment by Mimetis** [comment]
It's late night in france;, will take a look tomorrow morning

**Comment by Mimetis** [comment]
I'm not able to reproduce the error.

Can you please confirm that for each table, you have ( for example the table `Patients`) :
- 1 tracking table `Patients_tracking`
- 1 delete trigger `Patients_delete_trigger` on table `Patients`
- 1 insert trigger `Patients_insert_trigger` on table `Patients`
- 1 update trigger `Patients_update_trigger` on table `Patients`
- 1 stored procedure `Patients_bulkdelete`
- 1 stored procedure `Patients_bulkupdate`
- 1 stored procedure `Patients_changes`
- 1 stored procedure `Patients_delete`
- 1 stored procedure `Patients_deletemetadata`
- 1 stored procedure `Patients_initialize`
- 1 stored procedure `Patients_reset`
- 1 stored procedure `Patients_selectrow`
- 1 stored procedure `Patients_update`
- 1 TVP  table `Patients_BulkType`
I you have a filter on the table, you should have also:
- 1 stored procedure `Patients_PracticeId_changes`
- 1 stored procedure `Patients_PracticeId_initialize`

**Comment by dgrothman** [comment]
I am checking on this now, sorry for the delay

**Comment by dgrothman** [comment]
- 1 tracking table Patients_tracking [YES dsPatients]
- 1 delete trigger Patients_delete_trigger on table Patients [YES]
- 1 insert trigger Patients_insert_trigger on table Patients [YES]
- 1 update trigger Patients_update_trigger on table Patients [YES]
- 1 stored procedure Patients_bulkdelete [No, I only have a delete and deletemetadata]
- 1 stored procedure Patients_bulkupdate [No, I only have an update]
- 1 stored procedure Patients_changes [Yes]
- 1 stored procedure Patients_delete [Yes]
- 1 stored procedure Patients_deletemetadata [Yes]
- 1 stored procedure Patients_initialize [Yes]
- 1 stored procedure Patients_reset [Yes]
- 1 stored procedure Patients_selectrow [Yes]
- 1 stored procedure Patients_update [Yes]
- 1 TVP table Patients_BulkType [Yes]
- I you have a filter on the table, you should have also:
- 1 stored procedure Patients_PracticeId_changes [Yes]
- 1 stored procedure Patients_PracticeId_initialize [Yes]

<img width="299" alt="Screen Shot 2020-03-01 at 7 54 01 AM" src="https://user-images.githubusercontent.com/10801916/75628901-260d9a80-5b92-11ea-895e-09e080cd20ab.png">

This is the code i used to setup the trackingTables, stored procedures, triggers. Why would it not create the bulk stored procedures?

```
SqlSyncProvider serverProvider = new SqlSyncProvider(syncBuilder.ConnectionString);
                var connection = serverProvider.CreateConnection();

                var syncSet = serverProvider.ReadSchema(syncSetup, connection, null);
                syncSet.StoredProceduresPrefix = "ds";
                syncSet.StoredProceduresSuffix = "";
                syncSet.TrackingTablesPrefix = "ds";
                syncSet.TrackingTablesSuffix = "";
                syncSet.TriggersPrefix = "ds";
                syncSet.TriggersSuffix = "";
                Task.WaitAll(serverProvider.ProvisionAsync(syncSet,
                    SyncProvision.Triggers | SyncProvision.TrackingTable | SyncProvision.StoredProcedures));
```

**Comment by dgrothman** [comment]
syncSetup:

```
var tables = new string[] {
                    "Practices",
                    "AspNetRoles",
                    "AspNetUserTokens",
                    "AspNetUsers",
                    "AspNetUserRoles",
                    "Locations",
                    "Patients",
                    "PracticeSettings",
                    "Scans",
                    "ScanData",
                    "Exams"
                };
                var syncSetup = new SyncSetup(tables)
                {
                    StoredProceduresPrefix = "ds",
                    StoredProceduresSuffix = "",
                    TrackingTablesPrefix = "ds",
                    TrackingTablesSuffix = ""
                };
                syncSetup.Filters.Add("Practices", "Id");
                syncSetup.Filters.Add("AspNetUsers","PracticeId");
                syncSetup.Filters.Add("Locations","PracticeId");
                syncSetup.Filters.Add("Patients","PracticeId");
                syncSetup.Filters.Add("PracticeSettings","PracticeId");
                syncSetup.Filters.Add("Scans","PracticeId");
                syncSetup.Filters.Add("ScanData","PracticeId");
                syncSetup.Filters.Add("Exams","PracticeId");
```

**Comment by Mimetis** [comment]
Can you try it on a new blank database ?
Can you share the schema ?

**Comment by dgrothman** [comment]
Let me know if this is not what you need. I am working to setup a new db to test it on.

[dbo.uml.zip](https://github.com/Mimetis/Dotmim.Sync/files/4272505/dbo.uml.zip)

**Comment by dgrothman** [comment]
I was able to get the bulk stored procedures to create by doing the following:

- Rename [TrackingTableName]_update to [TrackingTableName]_bulkupdate
- Rename [TrackingTableName]_delete to [TrackingTableName]_delete
- Run ProvisionAsync (this repalces the *_update and *_delete stored procedures)
- Run DeprovisionAsync (this would fail before when looking for *_bulkupdate/delete procedures, but passes now)
- Re-Run ProvisionAsync this successfully creates all required stored procedures including bulkdelete/bulkdelete
