### ISSUE TITLE
[SQLITE] - Provision - Bug on creating tracking table and possible fix

### ISSUE THREAD

**Issue by mssergiosilva** [Mimetis/Dotmim.Sync#232]
Hi,

First thank you this great sync framework!
This new version is giving me awesome fight getting work =) I have to refactoring all my code to this new version.

 The bug result in wrong field datatype.

I have implemented a fix in the method "GetStringFromOwnerDbType" ((I have attached the code)

Kind regards,

[SQLiteDbMetadata.txt](https://github.com/Mimetis/Dotmim.Sync/files/4294040/SQLiteDbMetadata.txt)

**Comment by Mimetis** [comment]
Can you describe a liitle bit more what king of bug you find ?

**Comment by mssergiosilva** [comment]
It is difficult for me to explain right without showing you the debug but I will try to explain the steps that I have made to detect this problem.

I had a synced database and then I had to deprovision with SyncProvision options "SyncProvision.TrackingTable | SyncProvision.Triggers | SyncProvision.StoredProcedures".
The database maintains all data tables. Then I made a provision with the same options "SyncProvision.TrackingTable | SyncProvision.Triggers | SyncProvision.StoredProcedures".

A remark - for provision the framework only have the local schema.

The creating of tracking table is in SQLiteBuilderTrackingTable class and the method is CreateTableCommandText.

When the framework is creating the tracking table, the first thing to do is getting primary keys. For each primary key the framework will try to get the column type. 

`            // Adding the primary key
            foreach (var pkColumn in this.tableDescription.GetPrimaryKeysColumns())
            {
                var quotedColumnName = ParserName.Parse(pkColumn).Quoted().ToString();

                var columnTypeString = this.sqliteDbMetadata.TryGetOwnerDbTypeString(pkColumn.OriginalDbType, pkColumn.GetDbType(), false, false, pkColumn.MaxLength, this.tableDescription.OriginalProvider, SqliteSyncProvider.ProviderType);
                var columnPrecisionString = this.sqliteDbMetadata.TryGetOwnerDbTypePrecision(pkColumn.OriginalDbType, pkColumn.GetDbType(), false, false, pkColumn.MaxLength, pkColumn.Precision, pkColumn.Scale, this.tableDescription.OriginalProvider, SqliteSyncProvider.ProviderType);
                var quotedColumnType = ParserName.Parse(columnTypeString).Quoted().ToString();
                quotedColumnType += columnPrecisionString;

                stringBuilder.AppendLine($"{quotedColumnName} {quotedColumnType} NOT NULL COLLATE NOCASE, ");
            }`

To get column type is invoked TryGetOwnerDbTypeString method. This method is in the DbMetadata.
`        public string TryGetOwnerDbTypeString(string originalDbType, DbType fallbackDbType, bool isUnsigned, bool isUnicode, long maxLength, string fromProviderType, string ownerProviderType)
        {
            // We MUST check if we are from the same provider (if it's mysql or oracle, we fallback on dbtype
            if (!String.IsNullOrEmpty(originalDbType) && fromProviderType == ownerProviderType)
            {
                Object ownedDbType = ValidateOwnerDbType(originalDbType, isUnsigned, isUnicode, maxLength);
                return GetStringFromOwnerDbType(ownedDbType);
            }

            // if it's not the same provider, fallback on DbType instead.
            return GetStringFromDbType(fallbackDbType);
        }`

Then is invoked ValidateOwnerDbType and then GetStringFromOwnerDbType.
`        public override string GetStringFromOwnerDbType(object ownerType)
        {
            return GetStringFromDbType((DbType)ownerType);
        }`
Here is not the direct problem but we are trying to cast a SQLiteDataType to DBType which is resulting in bad DBType.

**Comment by Mimetis** [comment]
This issue has been fixed with the release of the version `v0.5`.
If you still experiencing the same bug, please comment here, I will re-open the issue.
