### ISSUE TITLE
[SQLITE] - Provision - Bug getting primary keys (when multiple) for table and possible fix

### ISSUE THREAD

**Issue by mssergiosilva** [Mimetis/Dotmim.Sync#233]
Hi,

First thank you this great sync framework!
This new version is giving me awesome fight getting work =) I have to refactoring all my code to this new version.

I have detected this making a provision and on tracking table - when I have a table with multiple primary keys the tracking table is only created with one primary key.

I have implemented a fix in the method "PrimaryKeysForTable" (I have attached the code)

Kind regards,

[SQLiteManagementUtils.txt](https://github.com/Mimetis/Dotmim.Sync/files/4294081/SQLiteManagementUtils.txt)

**Comment by Mimetis** [comment]
This issue has been fixed with the release of the version `v0.5`.
If you still experiencing the same bug, please comment here, I will re-open the issue.
