### ISSUE TITLE
[Enhancement] - Add Prefix/Suffix to all fields or variables

### ISSUE THREAD

**Issue by mssergiosilva** [Mimetis/Dotmim.Sync#235]
Hi,

First thank you this great sync framework!
This new version is giving me awesome fight getting work =) I have to refactoring all my code to this new version.

This enhancement is to not create name collisions with existing fields or variables.

Kind regards

**Comment by Mimetis** [comment]
We have already prefix and suffix for stored procedure, triggers and tracking table
Where do you need to add prefix and suffix ?

**Comment by mssergiosilva** [comment]
I have a Product table that have a field named "CHANGED".

The update procedure created by the framework will have a @CHANGED parameter and will have a @changed variable.

Original:
`CREATE PROCEDURE [dbo].[syncPO_PRODUCTS_update]
	@IDENTIF nvarchar(50),
	@SUBSYSTEM_INDEX nvarchar(50),
	@INTERFACE_INDEX int,
	@SUBSYSTEM nvarchar(50) NULL,
	@SUBGROUP nvarchar(50) NULL,
	@CODE nvarchar(50) NULL,
	@PRODUCT_NAME nvarchar(50) NULL,
	@QUANTITY decimal(18, 4) NULL,
	@PRICE decimal(18, 4) NULL,
	@PRODUCT_TIME decimal(18, 4) NULL,
	@REQUISITOS_TECNICOS nvarchar(2000) NULL,
	@TEXTO_COMERCIAL nvarchar(2000) NULL,
	@ORIGINAL_QUANTITY decimal(18, 4) NULL,
	@FREE_ITEM int NULL,
	@FORMULA nvarchar(2000) NULL,
	@CHANGED bit NULL,
	@SUBSYSTEM_REQUISITOS_TECNICOS nvarchar(2000) NULL,
	@SUBSYSTEM_TEXTO_COMERCIAL nvarchar(2000) NULL,
	@sync_min_timestamp bigint,
	@sync_scope_id uniqueidentifier,
	@sync_force_write int,
	@sync_row_count int OUTPUT
AS
BEGIN
-- use a temp table to store the list of PKs that successfully got updated/inserted
declare @changed TABLE ([IDENTIF] [nvarchar](50), [SUBSYSTEM_INDEX] [nvarchar](50), [INTERFACE_INDEX] [int],  PRIMARY KEY ([IDENTIF], [SUBSYSTEM_INDEX], [INTERFACE_INDEX]));

;WITH [changes] AS (
	SELECT [p].[IDENTIF], [p].[SUBSYSTEM_INDEX], [p].[INTERFACE_INDEX], [p].[SUBSYSTEM], [p].[SUBGROUP], [p].[CODE], [p].[PRODUCT_NAME], [p].[QUANTITY], [p].[PRICE], [p].[PRODUCT_TIME], [p].[REQUISITOS_TECNICOS], [p].[TEXTO_COMERCIAL], [p].[ORIGINAL_QUANTITY], [p].[FREE_ITEM], [p].[FORMULA], [p].[CHANGED], [p].[SUBSYSTEM_REQUISITOS_TECNICOS], [p].[SUBSYSTEM_TEXTO_COMERCIAL], 
	[side].[update_scope_id], [side].[timestamp], [side].[sync_row_is_tombstone]
	FROM (SELECT 
		 @IDENTIF as [IDENTIF], @SUBSYSTEM_INDEX as [SUBSYSTEM_INDEX], @INTERFACE_INDEX as [INTERFACE_INDEX], @SUBSYSTEM as [SUBSYSTEM], @SUBGROUP as [SUBGROUP], @CODE as [CODE], @PRODUCT_NAME as [PRODUCT_NAME], @QUANTITY as [QUANTITY], @PRICE as [PRICE], @PRODUCT_TIME as [PRODUCT_TIME], @REQUISITOS_TECNICOS as [REQUISITOS_TECNICOS], @TEXTO_COMERCIAL as [TEXTO_COMERCIAL], @ORIGINAL_QUANTITY as [ORIGINAL_QUANTITY], @FREE_ITEM as [FREE_ITEM], @FORMULA as [FORMULA], @CHANGED as [CHANGED], @SUBSYSTEM_REQUISITOS_TECNICOS as [SUBSYSTEM_REQUISITOS_TECNICOS], @SUBSYSTEM_TEXTO_COMERCIAL as [SUBSYSTEM_TEXTO_COMERCIAL]) AS [p]
	LEFT JOIN [syncPO_PRODUCTS] [side] ON 	[p].[IDENTIF] = [side].[IDENTIF] AND [p].[SUBSYSTEM_INDEX] = [side].[SUBSYSTEM_INDEX] AND [p].[INTERFACE_INDEX] = [side].[INTERFACE_INDEX]
	)
MERGE [PO_PRODUCTS] AS [base]
USING [changes] on [changes].[IDENTIF] = [base].[IDENTIF] AND [changes].[SUBSYSTEM_INDEX] = [base].[SUBSYSTEM_INDEX] AND [changes].[INTERFACE_INDEX] = [base].[INTERFACE_INDEX]
WHEN MATCHED AND ([changes].[timestamp] <= @sync_min_timestamp OR [changes].[timestamp] IS NULL OR [changes].[update_scope_id] = @sync_scope_id OR @sync_force_write = 1) THEN

	UPDATE SET
	[SUBSYSTEM] = [changes].[SUBSYSTEM]
	, [SUBGROUP] = [changes].[SUBGROUP]
	, [CODE] = [changes].[CODE]
	, [PRODUCT_NAME] = [changes].[PRODUCT_NAME]
	, [QUANTITY] = [changes].[QUANTITY]
	, [PRICE] = [changes].[PRICE]
	, [PRODUCT_TIME] = [changes].[PRODUCT_TIME]
	, [REQUISITOS_TECNICOS] = [changes].[REQUISITOS_TECNICOS]
	, [TEXTO_COMERCIAL] = [changes].[TEXTO_COMERCIAL]
	, [ORIGINAL_QUANTITY] = [changes].[ORIGINAL_QUANTITY]
	, [FREE_ITEM] = [changes].[FREE_ITEM]
	, [FORMULA] = [changes].[FORMULA]
	, [CHANGED] = [changes].[CHANGED]
	, [SUBSYSTEM_REQUISITOS_TECNICOS] = [changes].[SUBSYSTEM_REQUISITOS_TECNICOS]
	, [SUBSYSTEM_TEXTO_COMERCIAL] = [changes].[SUBSYSTEM_TEXTO_COMERCIAL]
WHEN NOT MATCHED BY TARGET AND ([changes].[timestamp] <= @sync_min_timestamp OR [changes].[timestamp] IS NULL OR @sync_force_write = 1) THEN

	INSERT
	([IDENTIF], [SUBSYSTEM_INDEX], [INTERFACE_INDEX], [SUBSYSTEM], [SUBGROUP], [CODE], [PRODUCT_NAME], [QUANTITY], [PRICE], [PRODUCT_TIME], [REQUISITOS_TECNICOS], [TEXTO_COMERCIAL], [ORIGINAL_QUANTITY], [FREE_ITEM], [FORMULA], [CHANGED], [SUBSYSTEM_REQUISITOS_TECNICOS], [SUBSYSTEM_TEXTO_COMERCIAL])
	VALUES ([changes].[IDENTIF], [changes].[SUBSYSTEM_INDEX], [changes].[INTERFACE_INDEX], [changes].[SUBSYSTEM], [changes].[SUBGROUP], [changes].[CODE], [changes].[PRODUCT_NAME], [changes].[QUANTITY], [changes].[PRICE], [changes].[PRODUCT_TIME], [changes].[REQUISITOS_TECNICOS], [changes].[TEXTO_COMERCIAL], [changes].[ORIGINAL_QUANTITY], [changes].[FREE_ITEM], [changes].[FORMULA], [changes].[CHANGED], [changes].[SUBSYSTEM_REQUISITOS_TECNICOS], [changes].[SUBSYSTEM_TEXTO_COMERCIAL])

OUTPUT INSERTED.[IDENTIF], INSERTED.[SUBSYSTEM_INDEX], INSERTED.[INTERFACE_INDEX]
INTO @changed; -- populates the temp table with successful PKs

SET @sync_row_count = 0;

-- Since the update trigger is passed, we update the tracking table to reflect the real scope updater
UPDATE [side] SET
	[update_scope_id] = @sync_scope_id,
	[sync_row_is_tombstone] = 0,
	[last_change_datetime] = GETUTCDATE()
FROM [syncPO_PRODUCTS] [side]
JOIN @changed [t] on [t].[IDENTIF] = [side].[IDENTIF] AND [t].[SUBSYSTEM_INDEX] = [side].[SUBSYSTEM_INDEX] AND [t].[INTERFACE_INDEX] = [side].[INTERFACE_INDEX]

SET @sync_row_count = @@ROWCOUNT;

END`

**Comment by Mimetis** [comment]
oh god, I understand :)
I will make an update on the stored proc with a name that will be more complex :)

**Comment by mssergiosilva** [comment]
=)

Sorry for my English ;)

**Comment by Mimetis** [comment]
This issue has been fixed with the release of the version `v0.5`.
If you still experiencing the same bug, please comment here, I will re-open the issue.
