### ISSUE TITLE
filtering table with data related to multiple tables (audit trail/notes etc)

### ISSUE THREAD

**Issue by YoselYohan** [Mimetis/Dotmim.Sync#236]
There is a common scenario where you have tables for "audit trail" or "notes" that contains records from multiple tables. These type of tables usually contain the recordId/Primarykey and the table name where they were created. I would not want all the records from this tables to travel the multiple sites/client. How could this type of tables be filtered?. My first sought was using a view to inner join with but views are not supported.

Thank you very much for this framework!.

**Comment by Mimetis** [comment]
This kind of table is called EAV : Entity Attribute Value table.
You can filter this type of table, quite easily.
Just make a filter on Table Column, it should work

**Comment by YoselYohan** [comment]
Thank you for your fast response.
as per the documentation 
"you can not have more than one SetupFilter per table".In the EAV table I need to filter records from TableA, TableB and TableC based on their creation SiteId(this is fine). How to filter "Notes table" only records from TableA, TableB and TableC that were created on each Site (1,2,3)?.

`
 var setup = new SyncSetup("TableA, TableB, TableC, Notes"){};
var myNotesFilter = new SetupFilter("Notes");
myNotesFilter .AddParameter("SiteId", "Sites", false);

myNotesFilter .AddJoin(Join.Left, "TableA").On("TableA", "TableAId", "Notes", "EntityId");
myNotesFilter .AddJoin(Join.Inner, "Sites").On("Sites", "SiteId", "TableA", "CreatedOnSiteId");

myNotesFilter .AddJoin(Join.Left, "TableB").On("TableB", "TableBId", "Notes", "EntityId");
myNotesFilter .AddJoin(Join.Inner, "Sites").On("Sites", "SiteId", "TableB", "CreatedOnSiteId");

myNotesFilter .AddJoin(Join.Left, "TableC").On("TableC", "TableCId", "Notes", "EntityId");
myNotesFilter .AddJoin(Join.Inner, "Sites").On("Sites", "SiteId", "TableC", "CreatedOnSiteId");

myNotesFilter .AddWhere("SiteId", "Sites", "SiteId");
setup.Filters.Add(myNotesFilter );
`

**Comment by Mimetis** [comment]
Quite complicated to answer here.
Can you share a small repro ?
