### ISSUE TITLE
[Bug] Sync with MariaDB brings SQL syntax error

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#24]
Hi,
i have used the client I posted in the other thread to test sync with MariaDB. And I get the following result: 

Master: http://localhost:56782/api/values
Slave1: Server=127.0.0.1; Port=3306; Database=DotminXAF1; Uid=root; Pwd=geheim;
Slave2: Server=127.0.0.1; Port=3306; Database=DotminXAF2; Uid=root; Pwd=geheim;
Sync Start
Begin Session.
Ensure Scopes
Ensure Configuration
Configuration readed. 8 table(s) involved.
End Session.
Error occured during EnsureDatabase of type DataStore: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'inFile VARCHAR(36),
        inOptimisticLockField INT,
        inGCRecord INT
)
BEGIN
IF ((SEL' at line 4
Sync Ended. Press a key to start again, or Escapte to end

**Comment by Mimetis** [comment]
Actually, I don't made any test with MariaDB database.  
Today, only MySQL is supported. But I will make some tests in a future version, and will make a compatible version.
