### ISSUE TITLE
Table Doest not have PK Exception, but table does have PK

### ISSUE THREAD

**Issue by champcbg** [Mimetis/Dotmim.Sync#240]
I have a web server setup.  That runs Deprovision and Provision.

  ```
var syncProvider =
                new SqlSyncProvider(
                    Configuration
                        .GetConnectionString(
                            "SStGConnection")); // serviceScope.ServiceProvider.GetService<SqlSyncProvider>();

            // delete triggers and sp
            var syncSet = new SyncSet();
            syncSet.Tables.Add(BaseDbContext.SyncTables);

            await syncProvider.DeprovisionAsync(syncSet,
                SyncProvision.StoredProcedures | SyncProvision.Triggers);

            UpdateDatabaseLogDatabase(app);
            UpdateDatabaseSStGDatabase(app);
            UpdateDatabaseCommunicationDatabase(app);

            await syncProvider.ProvisionAsync(syncSet,
                SyncProvision.StoredProcedures | SyncProvision.Triggers);
```
The updateDatabase(*) statements run EFCore 3 migrations.  Then when this line runs 

**await syncProvider.ProvisionAsync(syncSet, SyncProvision.StoredProcedures | SyncProvision.Triggers);** 

the exception below gets thrown 

 **Table AVBActivityQuestion does not have any primary key.**

but the table does have a PK

```
/****** Object:  Table [AVB].[AVBActivityQuestion]    Script Date: 3/16/2020 7:17:29 AM ******/
CREATE TABLE [AVB].[AVBActivityQuestion](
	[Id] [smallint] IDENTITY(1,1) NOT NULL,
	[Question] [nvarchar](256) NOT NULL,
	[AnswerType] [nvarchar](16) NOT NULL,
	[QuestionForActivityType] [nvarchar](64) NOT NULL,
	[Hint] [nvarchar](256) NULL,
	[CreatedAt] [datetimeoffset](7) NOT NULL,
	[ModifiedAt] [datetimeoffset](7) NULL,
	[IsActive] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_AVBActivityQuestion] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [AVB].[AVBActivityQuestion] ADD  DEFAULT (getutcdate()) FOR [CreatedAt]
GO

ALTER TABLE [AVB].[AVBActivityQuestion] ADD  DEFAULT (getutcdate()) FOR [ModifiedAt]
GO
```

This is also the initial setup and provisioning of the DB.  None of the Sync objects (triggers, tables,etc) exist in the current database.  It is the 1st run of the Web Server project that will host the data sync endpoint.

**Comment by Mimetis** [comment]
that's strange
can you give me the schema before and after migration ? (at least tables that fail)

**Comment by champcbg** [comment]
Im testing starting with an empty DB that gets build from scratch with EF Migrations.

more details about the error:
```
This exception was originally thrown at this call stack:
	Dotmim.Sync.Builders.DbTableBuilder.CreateTriggers(System.Data.Common.DbConnection, System.Data.Common.DbTransaction)
	Dotmim.Sync.CoreProvider.ProvisionAsync(Dotmim.Sync.SyncSet, Dotmim.Sync.Enumerations.SyncProvision, string)
```

**Comment by champcbg** [comment]
Pulled in the latest master branch and found where the problem is happening at.  In the CoreProvider.Database.cs the **SchemaTable** has no columns.  

So in the function CreateTriggers() the error gets thrown.

![image](https://user-images.githubusercontent.com/4595766/77044302-8d4e8b80-6995-11ea-841e-472a6f420d66.png)

I am try to figure out why the table has no columns.  I checked the connectionString and it pointing to a database that has all the tables and columns.

**Comment by champcbg** [comment]
![image](https://user-images.githubusercontent.com/4595766/77046137-cf2d0100-6998-11ea-9a8f-5423f09187a1.png)


This code here where the SyncSet is created, populates the tables, lines 366 in image

```
 var syncSet = new SyncSet();
            syncSet.Tables.Add(BaseDbContext.SyncTables);

```

I couldnt find anywhere in the Provision logic where the columns get added to the Table in the SyncSet.

**Comment by Mimetis** [comment]
Can you share a simple repro ?
I will try to find the issue. 
Thanks !

**Comment by champcbg** [comment]
Line 150 

the syncSet has the collection of Tables, None of the tables have Columns.  Which the tables populate their columns collections, and leads to images in the thread above.

I used table from adventure works DB, so it is easy to replicate.

[DataSync.Sample.zip](https://github.com/Mimetis/Dotmim.Sync/files/4397698/DataSync.Sample.zip)

**Comment by Mimetis** [comment]
This issue has been fixed with the release of the version `v0.5`.  
If you still experiencing the same bug, please comment here, I will re-open the issue

**Comment by champcbg** [comment]
I have a question about the setting up the configuration for provision and deprovision with the web proxy

this is what my startup looks like in the web project.

            ```

            services.AddMemoryCache();

            // [Required]: Get a connection string to your server data source
            var connectionString = Configuration.GetConnectionString("SStGConnection");

            //  [Optional] : database setup
            var syncSetup = new SyncSetup(BaseDbContext.SyncTables)
            {
                // optional :
                StoredProceduresPrefix = "sync_",
                StoredProceduresSuffix = "",
                TrackingTablesPrefix = "sync_",
                TrackingTablesSuffix = "",
                TriggersPrefix = "sync_",
            };

            var syncOptions = new SyncOptions()
            {
                BatchDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDiretory(), "server"),
                SnapshotsDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
                    "Snapshots"),
                ConflictResolutionPolicy = ConflictResolutionPolicy.ClientWins, UseVerboseErrors = true
            };

            #region direction
            ...
            #endregion 

            #region filters
             ...
            #endregion

            // [Required]: Add a SqlSyncProvider acting as the server hub.
            // If you don't specify a SyncSetup object, just add the tables array.
            services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString, syncSetup, syncOptions);
        
```

with the changes to how the deprovision and provision , I am not sure where or to use to call the **`GetSchemaASync()`**..  The code below is doing this

1. deprovision 
2. Run EF Core MIgrations on 
3. Provision

```
private async Task UpdateDatabasesAsync(IApplicationBuilder app)
        {
            using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                using (var logcontext = serviceScope.ServiceProvider.GetService<InsightsDbContext>())
                {
                    var syncProvider = serviceScope.ServiceProvider.GetService<SqlSyncChangeTrackingProvider>();

                var syncSet = await syncProvider.GetSchemaAsync();

                await syncProvider.DeprovisionAsync(syncSet,
                    SyncProvision.StoredProcedures | SyncProvision.Triggers);

                UpdateDatabaseLogDatabase(serviceScope, logcontext);
                UpdateDatabaseSStGDatabase(serviceScope, logcontext);
                UpdateDatabaseCommunicationDatabase(serviceScope, logcontext);

                await syncProvider.ProvisionAsync(syncSet,
                    SyncProvision.StoredProcedures | SyncProvision.Triggers);
                }
            }
        }
```

The GetSchemaASync on this line **`var syncSet = await syncProvider.GetSchemaAsync();`** has this signature
![image](https://user-images.githubusercontent.com/4595766/78948720-51d84600-7a97-11ea-9068-7beabfe8b65a.png)

I am clearly calling the method on the wrong provider.  Not sure what it should be.

**Comment by Mimetis** [comment]
which version are you working on ? (0.4 / 0.5 ) ?

**Comment by champcbg** [comment]
.5

**Comment by Mimetis** [comment]
Let's try to be more precise.

Before making a *deprovision*-*update db*-*provision*, be sure your clients are synced with the server...

## Client deprovision

When you are making a `DeprovisionAsync`, the `DMS` framework needs *only* the table names.   
Actually, `DMS` does not care about the columns, their data type and so on, to be able to *drop* things ...   
That's why it is quite easy.  
Just create a `SyncSetup` (`SyncSetup` contains only the table names, and sometime columns names, but it does not contains any information on the columns data type, the relations, fk and so on...) instance with the list of tables to deprovision, the `Provision` type, and you're good to go:

``` cs
var clientProvider = new SqlSyncProvider(clientConnectionString);

var setup = new SyncSetup(new string[]{"Product", "ProductCategory"});

// Create a local orchestrator, to manage the local database
var localOrchestrator = new LocalOrchestrator(clientProvider, new SyncOptions(), setup);

var provision = SyncProvision.ClientScope | SyncProvision.StoredProcedures | SyncProvision.Triggers;

// deprovision the local database
await localOrchestrator.DeprovisionAsync(schema, provision);
```
In this example, we are deprovisionning 2 tables stored procedures and triggers : `Product` and `ProductCategory` *plus* the `scope_client` table that contains the client metadatas.

The `scope_client` table contains all the required info to be able to sync with the server.  
Droping this table will requires us to get all the metdata informations again from the server.    
Like ... a first sync for instance :)

So be sure your client does not have any rows "out synced" before making a deprovision.

## Client provision

Provision is a little bit more tricky, because `DMS` requires more information.   
For instance, provisioning a full table requires **all** the columns, their datatype and so on...   
That's why passing a `SyncSetup` instance containing only the tables names, is not enough 

We need the full schema, containing all the information.  
That's why we are calling the `remoteOrchestrator.GetSchemaAsync();` method, to get the full schema from the server side.

The provision becomes something like that:
``` cs
var serverProvider = new SqlSyncProvider(serverConnectionString);
var clientProvider = new SqlSyncProvider(clientConnectionString);

// Create a local orchestrator, to manage the local database
var localOrchestrator = new LocalOrchestrator(clientProvider, Config.GetClientOptions(), Config.GetSetup());

// Create a remote orchestrator, to manage hub server database
var remoteOrchestrator = new RemoteOrchestrator(serverProvider, Config.GetClientOptions(), Config.GetSetup());

// Get schema from server side
var schema = await remoteOrchestrator.GetSchemaAsync();

var provision = SyncProvision.ClientScope | SyncProvision.StoredProcedures | SyncProvision.Table | SyncProvision.TrackingTable | SyncProvision.Triggers;

// provision the local database
await localOrchestrator.ProvisionAsync(schema, provision);
```
That way, all the tables will be provision again (even the new ones)   
And you will get a fresh new `client_scope` metadata table.

## Server deprovision

Server deprovision is quite similar:

``` cs
var serverProvider = new SqlSyncProvider(serverConnectionString);

var setup = new SyncSetup(new string[]{"Product", "ProductCategory"});

// Create a remote orchestrator, to manage the local database
var remoteOrchestrator = new RemoteOrchestrator(serverProvider, new SyncOptions(), setup);

var provision = SyncProvision.ServerScope | SyncProvision.StoredProcedures | SyncProvision.Triggers;

// deprovision the local database
await remoteOrchestrator.DeprovisionAsync(schema, provision);
```
Here, the difference comes from the `Provision` enum : we are replacing `SyncProvision.ClientScope` with `SyncProvision.ServerScope`

## Server provision

Server provision is quite similar as well:
``` cs
var serverProvider = new SqlSyncProvider(serverConnectionString);

// Create a local orchestrator, to manage the local database
var remoteOrchestrator = new RemoteOrchestrator(serverProvider, Config.GetClientOptions(), Config.GetSetup());

// Create a remote orchestrator, to manage hub server database
var remoteOrchestrator = new RemoteOrchestrator(serverProvider, Config.GetClientOptions(), Config.GetSetup());

// Get schema from server side
var schema = await remoteOrchestrator.GetSchemaAsync();

var provision = SyncProvision.ServerScope | SyncProvision.StoredProcedures | SyncProvision.TrackingTable | SyncProvision.Triggers;

// provision the local database
await remoteOrchestrator.ProvisionAsync(schema, provision);
```

**Comment by champcbg** [comment]
> Before making a deprovision-update db-provision, be sure your clients are synced with the server...

This is most likely my problem.  I never initiated a sync 1st on my clients.  Which explains the error I get on the clients during provision that the tables dont exist.  They dont exist because they are not `client_scope` meta table.  which makes perfect sense.  I do remember looking through those tables, when i 1st running test locally against SQL server and SQLite.

Let me ask this.  my client is  xamarin.forms, which means I have no control over the client.  If i publish a new version of the server DB that has run some migrations, added, removed, renamed columns, or even tables,  Wont that break the sync if i attempt a sync before a migration?

I ask the thought in the back of mind, that once this strategy is in place, there needs to be more strategic or methodical way of changing DB objects.

**Comment by Mimetis** [comment]
Indeed, as you said, when a sync is in place, it's quite complicated to make the database evolve.

If you do not have the choice, my guess would be to make a full Reinit for all clients, when you have made the upgrade of your server database.
So far, be sure they have all made their sync before.

In a future version, I will try to simplify things by allowing *some* minors changes to the schema, but anyway I won't be able to solve ALL the scenario and problems that can occirs

**Comment by champcbg** [comment]
> I won't be able to solve ALL the scenario and problems that can occirs

LOL, i been in this business long enough to solving for everything is not a thing.  

I was asking cause your experience might have some best practice methodologies.    Realistically once the DB is mature, there or not sweeping changes like that.  and if there big changes like that, each one will have its own unique conditions.

Im making the logic changes discussed above, will let you know of my success.

**Comment by champcbg** [comment]
In the **Client Provision** this concerns me

`            _remoteOrchestrator = new RemoteOrchestrator(_clientProvider, _clientOptions, _clientSetup);
`
that means the mobile client needs to be aware server side connection string to the DB.  I understand the reasoning, but from security standpoint seems high risk

**Comment by Mimetis** [comment]
Depending on what you want from the server ?

if you need this:

```cs
// Create a remote orchestrator, to manage hub server database
var remoteOrchestrator = new RemoteOrchestrator(serverProvider, Config.GetClientOptions(), Config.GetSetup());

// Get schema from server side
var schema = await remoteOrchestrator.GetSchemaAsync();

```

You can replace with this:
```cs
// Create a remote orchestrator, to manage hub server database
var remoteOrchestrator = new WebClientOrchestrator("https://www.yourserver.com/api/sync");

// Get schema from server side
var schema = await remoteOrchestrator.GetSchemaAsync();

```
