### ISSUE TITLE
can't establish a seed / step in Sqlite autoinc value

### ISSUE THREAD

**Issue by rajeshgithub001** [Mimetis/Dotmim.Sync#242]
1. Created Web APi in net core using Dotmim.Sync
2. Create console app
3. First time doing sync
4. It giving this error
5. All table has PK with autoincreament

Please help why this error coming

**Comment by rajeshgithub001** [comment]
CREATE TABLE [dbo].[ToFindList](
	[ToFindListId] [bigint] IDENTITY(1,1) NOT NULL,
	[FindListName] [varchar](200) NOT NULL,
	[RegionId] [bigint] NOT NULL,
	[Status] [bit] NOT NULL,
	[CreatedOn] [datetime] NOT NULL,
	[UpdatedOn] [datetime] NOT NULL,
 CONSTRAINT [PK_ToFindLists] PRIMARY KEY CLUSTERED 
(
	[ToFindListId] ASC
)
GO

**Comment by Mimetis** [comment]
Hello @rajeshgithub001 

I've tried your example and it's working fine for me.
I've created a small repro that you can download here : [TestSqliteAutoInc.zip](https://github.com/Mimetis/Dotmim.Sync/files/4409828/TestSqliteAutoInc.zip)

For the server side, you miss the `varchar` `length`, so I've tested with `varchar(50)`:

``` sql
CREATE TABLE [dbo].[ToFindList](
	[ToFindListId] [bigint] IDENTITY(1,1) NOT NULL,
	[FindListName] [varchar](50) NOT NULL,
	[RegionId] [bigint] NOT NULL,
	[Status] [bit] NOT NULL,
	[CreatedOn] [datetime] NOT NULL,
	[UpdatedOn] [datetime] NOT NULL,
 CONSTRAINT [PK_ToFindLists] PRIMARY KEY CLUSTERED ( [ToFindListId] ASC ))

GO
SET IDENTITY_INSERT [dbo].[ToFindList] ON 
INSERT [dbo].[ToFindList] ([ToFindListId], [FindListName], [RegionId], [Status], [CreatedOn], [UpdatedOn]) VALUES (1, N'Name1', 1, 1, CAST(N'2020-03-01T00:00:00.000' AS DateTime), CAST(N'2020-02-02T00:00:00.000' AS DateTime))
INSERT [dbo].[ToFindList] ([ToFindListId], [FindListName], [RegionId], [Status], [CreatedOn], [UpdatedOn]) VALUES (2, N'Name2', 1, 0, CAST(N'2020-03-01T00:00:00.000' AS DateTime), CAST(N'2020-02-02T00:00:00.000' AS DateTime))
SET IDENTITY_INSERT [dbo].[ToFindList] OFF
GO

```
The server side is pretty simple:
*Note* that SyncSetup stored procedures and tracking table prefix / suffix are optional

``` cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    // Mandatory to be able to handle multiple sessions
    services.AddMemoryCache();

    // Get a connection string for your server data source
    var connectionString = "Data Source=(localdb)\\mssqllocaldb; Initial Catalog=TestDb; Integrated Security=true;";

    // Create the setup used for your sync process
    var tables = new string[] { "ToFindList" };

    var setup = new SyncSetup(tables)
    {
        // optional :
        StoredProceduresPrefix = "sp",
        StoredProceduresSuffix = "",
        TrackingTablesPrefix = "s",
        TrackingTablesSuffix = "_trck"
    };

    // add a SqlSyncProvider acting as the server hub
    services.AddSyncServer<SqlSyncProvider>(connectionString, setup);
}
```
The controller as well is pretty simple
**Note** that the `[Get]` handler is here to debug purpose. Navigating through a web browser to this web page will show you your setup options

``` cs
[Route("api/[controller]")]
[ApiController]
public class SyncController : ControllerBase
{
    private WebProxyServerOrchestrator webProxyServer;

    // Injected thanks to Dependency Injection
    public SyncController(WebProxyServerOrchestrator proxy) => this.webProxyServer = proxy;

    [HttpPost]
    public async Task Post()
    {
        await webProxyServer.HandleRequestAsync(this.HttpContext);
    }


    /// <summary>
    /// Optional Get handler
    /// </summary>
    [HttpGet]
    public async Task Get()
    {
        await webProxyServer.HandleRequestAsync(this.HttpContext);
    }
}
```
On the client side, I used the `SqliteSyncProvider` to create and use a `Sqlite` database.

``` cs
static async Task Main(string[] args) => await SyncAsync();

private static async Task SyncAsync()
{
    var clientProvider = new SqliteSyncProvider("TestDb.sqlite");
    var proxyClientProvider = new WebClientOrchestrator("https://localhost:44375/api/sync");

    var agent = new SyncAgent(clientProvider, proxyClientProvider);

    Console.WriteLine("Press a key to start (be sure web api is running ...)");
    Console.ReadKey();
    do
    {
        Console.Clear();
        Console.WriteLine("Web sync start");
        try
        {
            var progress = new SynchronousProgress<ProgressArgs>(pa => Console.WriteLine($"{pa.Context.SessionId} - {pa.Context.SyncStage}\t {pa.Message}"));
            var s = await agent.SynchronizeAsync(progress);
            Console.WriteLine(s);
        }
        catch (SyncException e)
        {
            Console.WriteLine(e.Message);
        }
        catch (Exception e)
        {
            Console.WriteLine("UNKNOW EXCEPTION : " + e.Message);
        }

        Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");
    } while (Console.ReadKey().Key != ConsoleKey.Escape);

    Console.WriteLine("End");
}
```

Let me known if you still have an issue

**Comment by rajeshgithub001** [comment]
> Hello @rajeshgithub001
> 
> I've tried your example and it's working fine for me.
> I've created a small repro that you can download here : [TestSqliteAutoInc.zip](https://github.com/Mimetis/Dotmim.Sync/files/4409828/TestSqliteAutoInc.zip)
> 
> For the server side, you miss the `varchar` `length`, so I've tested with `varchar(50)`:
> 
> ```sql
> CREATE TABLE [dbo].[ToFindList](
> 	[ToFindListId] [bigint] IDENTITY(1,1) NOT NULL,
> 	[FindListName] [varchar](50) NOT NULL,
> 	[RegionId] [bigint] NOT NULL,
> 	[Status] [bit] NOT NULL,
> 	[CreatedOn] [datetime] NOT NULL,
> 	[UpdatedOn] [datetime] NOT NULL,
>  CONSTRAINT [PK_ToFindLists] PRIMARY KEY CLUSTERED ( [ToFindListId] ASC ))
> 
> GO
> SET IDENTITY_INSERT [dbo].[ToFindList] ON 
> INSERT [dbo].[ToFindList] ([ToFindListId], [FindListName], [RegionId], [Status], [CreatedOn], [UpdatedOn]) VALUES (1, N'Name1', 1, 1, CAST(N'2020-03-01T00:00:00.000' AS DateTime), CAST(N'2020-02-02T00:00:00.000' AS DateTime))
> INSERT [dbo].[ToFindList] ([ToFindListId], [FindListName], [RegionId], [Status], [CreatedOn], [UpdatedOn]) VALUES (2, N'Name2', 1, 0, CAST(N'2020-03-01T00:00:00.000' AS DateTime), CAST(N'2020-02-02T00:00:00.000' AS DateTime))
> SET IDENTITY_INSERT [dbo].[ToFindList] OFF
> GO
> ```
> 
> The server side is pretty simple:
> _Note_ that SyncSetup stored procedures and tracking table prefix / suffix are optional
> 
> ```cs
> public void ConfigureServices(IServiceCollection services)
> {
>     services.AddControllers();
> 
>     // Mandatory to be able to handle multiple sessions
>     services.AddMemoryCache();
> 
>     // Get a connection string for your server data source
>     var connectionString = "Data Source=(localdb)\\mssqllocaldb; Initial Catalog=TestDb; Integrated Security=true;";
> 
>     // Create the setup used for your sync process
>     var tables = new string[] { "ToFindList" };
> 
>     var setup = new SyncSetup(tables)
>     {
>         // optional :
>         StoredProceduresPrefix = "sp",
>         StoredProceduresSuffix = "",
>         TrackingTablesPrefix = "s",
>         TrackingTablesSuffix = "_trck"
>     };
> 
>     // add a SqlSyncProvider acting as the server hub
>     services.AddSyncServer<SqlSyncProvider>(connectionString, setup);
> }
> ```
> 
> The controller as well is pretty simple
> **Note** that the `[Get]` handler is here to debug purpose. Navigating through a web browser to this web page will show you your setup options
> 
> ```cs
> [Route("api/[controller]")]
> [ApiController]
> public class SyncController : ControllerBase
> {
>     private WebProxyServerOrchestrator webProxyServer;
> 
>     // Injected thanks to Dependency Injection
>     public SyncController(WebProxyServerOrchestrator proxy) => this.webProxyServer = proxy;
> 
>     [HttpPost]
>     public async Task Post()
>     {
>         await webProxyServer.HandleRequestAsync(this.HttpContext);
>     }
> 
> 
>     /// <summary>
>     /// Optional Get handler
>     /// </summary>
>     [HttpGet]
>     public async Task Get()
>     {
>         await webProxyServer.HandleRequestAsync(this.HttpContext);
>     }
> }
> ```
> 
> On the client side, I used the `SqliteSyncProvider` to create and use a `Sqlite` database.
> 
> ```cs
> static async Task Main(string[] args) => await SyncAsync();
> 
> private static async Task SyncAsync()
> {
>     var clientProvider = new SqliteSyncProvider("TestDb.sqlite");
>     var proxyClientProvider = new WebClientOrchestrator("https://localhost:44375/api/sync");
> 
>     var agent = new SyncAgent(clientProvider, proxyClientProvider);
> 
>     Console.WriteLine("Press a key to start (be sure web api is running ...)");
>     Console.ReadKey();
>     do
>     {
>         Console.Clear();
>         Console.WriteLine("Web sync start");
>         try
>         {
>             var progress = new SynchronousProgress<ProgressArgs>(pa => Console.WriteLine($"{pa.Context.SessionId} - {pa.Context.SyncStage}\t {pa.Message}"));
>             var s = await agent.SynchronizeAsync(progress);
>             Console.WriteLine(s);
>         }
>         catch (SyncException e)
>         {
>             Console.WriteLine(e.Message);
>         }
>         catch (Exception e)
>         {
>             Console.WriteLine("UNKNOW EXCEPTION : " + e.Message);
>         }
> 
>         Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");
>     } while (Console.ReadKey().Key != ConsoleKey.Escape);
> 
>     Console.WriteLine("End");
> }
> ```
> 
> Let me known if you still have an issue

Thanks for looking into it. The actual reason i found that one of the table don't have primary key. Once i remove that table then its working fine. I have one question does sync will not work on table without primary key ? Like some table just textual information. for these type of table what we do ?

**Comment by Mimetis** [comment]
Well, it won't work for a table without a primary key.
If you have that kind of table, just add a fancy column with auto increment, as primary key.
or an uniqueidentifier, with default(newguid()) as primary key

**Comment by rajeshgithub001** [comment]
Thank you.
