### ISSUE TITLE
Running WebOrchestrator as an azure function

### ISSUE THREAD

**Issue by dgrothman** [Mimetis/Dotmim.Sync#243]
Has anyone used the weborchestrator as an azure function? I am looking into this now.

**Comment by Mimetis** [comment]
hey it's a good idea !
If you made some tests, and need help, let me know, I'm interested :)

**Comment by rajeshgithub001** [comment]
Well it should work as way in core web api. Only difference here is every time configuration setup will also execute.

**Comment by dgrothman** [comment]
I am having trouble getting it to run with the azure functions it seems it fighting with the http trigger, 
`Microsoft.AspNetCore.Server.Kestrel.Core: StatusCode cannot be set because the response has already started.` I will report back once i get further

**Comment by dgrothman** [comment]
Okay I think I have it running, still early on; but here are some tips and info for anyone interested.
First, Use a startup file for DI
(https://docs.microsoft.com/bs-latn-ba/azure/azure-functions/functions-dotnet-dependency-injection)
Then, Create a HttpTrigger Function and make sure you have `return new EmptyResult();` after the HandleRequestAsync
[Archive.zip](https://github.com/Mimetis/Dotmim.Sync/files/4417010/Archive.zip)

**Comment by champcbg** [comment]
I tried when it came to adding the memory cache i stopped.  My instant thought was function don't have caching and never looked any deeper to know if that was true or not.

**Comment by dgrothman** [comment]
Seems to be working with the memory cache on dotnet core 3.1, working on getting snapshots working

**Comment by champcbg** [comment]
Im going to give it try once i fully have the Web API core 3.1 up and running with provisioning and EF Core migrations working.

**Comment by champcbg** [comment]
> 
> 
> Seems to be working with the memory cache on dotnet core 3.1, working on getting snapshots working

@dgrothman did you ever snapshots working?

I am moving to a function also

**Comment by champcbg** [comment]
version 0.5.6-beta-413

This error is being thrown attempting to AddSyncServer

`  builder.Services.AddSyncServer<SqlSyncProvider>(connectionString, _syncNewSetup, _syncOptions);`

**Unable to resolve service for type 'Microsoft.Azure.WebJobs.Script.IFileLoggingStatusManager' while attempting to activate 'Microsoft.Azure.WebJobs.Script.Diagnostics.HostFileLoggerProvider'.'**

here is start up for the function

            ```
var connectionString = Environment.GetEnvironmentVariable(
                        "SStGConnectionString");

            //  [Optional] : database setup
            var existingTables =
                CommunicationBaseDbContext.NewSyncTables.Union(SStGBaseDbContext.NewSyncTables);

            _syncNewSetup = new SyncSetup(existingTables)
            {
                // optional :
                StoredProceduresPrefix = Constants.SyncSprocPrefix,
                StoredProceduresSuffix = "",
                TrackingTablesPrefix = Constants.SyncTrackingTablePrefix,
                TrackingTablesSuffix = "",
                // ScopeName = "SStGMobile_Sync",
                TriggersPrefix = Constants.SyncTriggersPrefix,
            };

            _syncOptions = new SyncOptions()
            {
                //BatchDirectory = Path.Combine(SyncOptions.GetDefaultUserBatchDiretory(), "server"),
                //SnapshotsDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
                //    "Snapshots"),
                ConflictResolutionPolicy = ConflictResolutionPolicy.ClientWins,
                DisableConstraintsOnApplyChanges = false,
                UseBulkOperations = true,
                UseVerboseErrors = true

            };
... 

            // [Required]: Add a SqlSyncProvider acting as the server hub.
            // If you don't specify a SyncSetup object, just add the tables array.
            builder.Services.AddSyncServer<SqlSyncProvider>(connectionString, _syncNewSetup, _syncOptions);
```

**Comment by dgrothman** [comment]
> > Seems to be working with the memory cache on dotnet core 3.1, working on getting snapshots working
> 
> @dgrothman did you ever snapshots working?
> 
> I am moving to a function also

I just finished moving away from function apps and moving back to a webapp. The reason is due to the function apps were a much higher cost to run due to accessing the storage share way more then a webapp does. 
As for snapshots, I ended up using hangfire running on a webapp to run a job on at a scheduled time.

**Comment by champcbg** [comment]
I am familiar with working with hangfire.

Thanks for your insights into the cost. The purpose of moving to a function was for scale and cost.

Ill just leave it in webapp for now
