### ISSUE TITLE
Syncing any particular table at time....

### ISSUE THREAD

**Issue by rajeshgithub001** [Mimetis/Dotmim.Sync#245]
I have requirement that i want to sync a table based on name or some identifier.
Like we have 10 tables which are at both side server & client both side.
Now i want that mobile able to sync any particular table not whole database.

Like:-
http://somedomain/api/sync/table/T1
http://somedomain/api/sync/table/T2

So by passing table name i can only sync that table.
I have seen multiscope scenario, but that requires to define multi groups.
I don't want groups to be define , just be sending table name it should sync that table ?

Also seen WebClientOrchestrator() doesnt working for multi scope environment.

**Comment by Mimetis** [comment]
Multi scopes is the only way for now
Sync for the issue regarding `WebClientOrchestrator()` and multi scopes. See #246
