### ISSUE TITLE
Same Identity value giving sync problem....

### ISSUE THREAD

**Issue by rajeshgithub001** [Mimetis/Dotmim.Sync#248]
I have table which are in sync on both side server & mobile side.

**Environment**:-
1. .Net Core Web Api giving sync fuctionality
2. Mobile client using it.

Today we face a problem:-
1. A new row generated in table T1 at server side. New Row PK value = 70
2. A new row generated in table T1 at mobile side. . New Row PK value = 70
3. Now both side PK value of new row become same 

Now when mobile going to sync it giving an exception.
Let me know how do resolve this ?

**Comment by Mimetis** [comment]
If you have 2 rows with same primary key, you will have a conflict generated, and the row will be replaced on client with the one from server (if ConflictResolution is set to ServerWins) 

If you have an exception, please give me more details

**Comment by rajeshgithub001** [comment]
Thank you. It working now.
