### ISSUE TITLE
[Bug] Adding a bunch of changes results in exception

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#25]
Hello,
i have now tested sync with sampleebserver and syncclient, i posted. Both (all three) ends are MSSQL.
Adding 1 file works, adding more files results in:

Begin Session.
Ensure Scopes
Ensure Configuration
Configuration readed. 8 table(s) involved.
Selecting changes...
Changes selected : 56
End Session.
UNKNOW EXCEPTION : Not Found
Sync Ended. Press a key to start again, or Escapte to end

**Comment by Mimetis** [comment]
Maybe your request is too heavy.
Did you try to setup a batch request sync ?

See the wiki part here : [https://github.com/Mimetis/Dotmim.Sync/wiki/03-Configuration-options](https://github.com/Mimetis/Dotmim.Sync/wiki/03-Configuration-options)

In your case, on the server part, you should try Something like:
```
configuration.DownloadBatchSizeInKB = 3000;
```

Be careful, if one row size is more than `DownloadBatchSizeInKB` you will probably have an error raised.  

Give it a try and let me know.  
On my side, I will test as well !

**Comment by thefonzi** [comment]
you are right! 
Using "configuration.UseBulkOperations = true;" solves the problem. 
Thanks

**Comment by Mimetis** [comment]
```
configuration.UseBulkOperations = true;
```
This property is set by default, if you are using SQL Server.

Are you sure, it's working with that, and without ?

**Comment by Mimetis** [comment]
I close the issue, feel free to re open it, if the bug is not resolved !
