### ISSUE TITLE
Can we define DTO for an Entity.......

### ISSUE THREAD

**Issue by rajeshgithub001** [Mimetis/Dotmim.Sync#250]
Environment:-
1. Web API provide offline sync.
2. Mobile app will use api.

Currently what i have seen is that it bring same entity properties what is in table at server database side.

Is it possible we can define DTO for an entity so that client should not be tightly coupled with database entity. Like a azure offline sync framework ?

**Comment by Mimetis** [comment]
Not really

The only thing you can do (see here : https://mimetis.github.io/Dotmim.Sync/Configuration) is defining a `SyncSetup` on the web api server side, with the columns you want to sync (and then omit the ones you don't want to sync)

For instance, in this sample:

``` csharp
var tables = new string[] {"ProductCategory", "ProductModel", "Product",
        "Address", "Customer", "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail" };

// Creating a sync setup object
var setup = new SyncSetup(tables);

// Filter columns
setup.Tables["Customer"].Columns.AddRange(new string[] { "CustomerID", "EmployeeID", "NameStyle", "FirstName", "LastName" });
setup.Tables["Address"].Columns.AddRange(new string[] { "AddressID", "AddressLine1", "City", "PostalCode" });
```
All the tables are synced with their columns, excepting `Customer` and `Address` where we take only some columns from the server.
