### ISSUE TITLE
Version differences between 0.4.3 and 0.5.1

### ISSUE THREAD

**Issue by dgrothman** [Mimetis/Dotmim.Sync#254]
Is there any breaking changes from 0.4 to 0.5? 
Any list of changes / new features?

**Comment by Mimetis** [comment]
https://github.com/Mimetis/Dotmim.Sync/pull/252

There are some new tables on the server side, that should be created

Be sure to make some tests before going for 0.5

**Comment by Mimetis** [comment]
Also, look these new docs about some new features :  
- https://mimetis.github.io/Dotmim.Sync/Migration  
- https://mimetis.github.io/Dotmim.Sync/Metadatas
- https://mimetis.github.io/Dotmim.Sync/Provision

**Comment by dgrothman** [comment]
Yes I am in production mode and I have access to the clients. I will check those out

**Comment by Mimetis** [comment]
Ok let me know.

I think I'm really close to a full feature framework.
Hopefully before summer, I will have a real `v1.0` of this framework.
From that point, every new version will be back compatible.

But for now, I still have some new features to implement that can possibly break something...

**Comment by gentledepp** [comment]
@Mimetis thanks for this great news!
We will wait for 1.0 then before migrating to it!

Btw: I wasn't here for a while now - seems you made great progress! 💪

**Comment by Mimetis** [comment]
Yes, I miss you @gentledepp  :)

**Comment by gentledepp** [comment]
😘😆
