### ISSUE TITLE
CommandTimeout

### ISSUE THREAD

**Issue by Messan** [Mimetis/Dotmim.Sync#258]
Hello,

It will be nice if there is a parameter somewhere  to change the default-30 secs on SQL Server)  **CommandTimeout** which is sometimes not enough for large updates in, for example, ApplyBulkChangesAsync

Regards

**Comment by Mimetis** [comment]
Hello @Messan 
Thanks for the feedback.

By the way if your bulk changes are too big, you may consider using the batch mode, using the `BatchSize` property.

Is it the case or are you using the in memory sync ?

**Comment by Messan** [comment]
@Mimetis
Apparently the Batch Size parameter I used was a little too large for the default timeout. I reduce its value and I was able to insert the rows. But this confirms the fact that this parameter will be welcome ;-)

**Comment by Mimetis** [comment]
Just for curiosity.
What was your batch size value, before and after?

**Comment by Messan** [comment]
10*1024 then 1024. To be honest i just set the value _au pif_ as they say en French

**Comment by Mimetis** [comment]
If you want to even more frenchy, say "au pifomètre" :)
A good starting point for batch size is around 1000 to 5000 max, in my opinion
