### ISSUE TITLE
Errors using webproxy (MissingTableException and Cannot drop the trigger)

### ISSUE THREAD

**Issue by tijntje** [Mimetis/Dotmim.Sync#259]
I am trying out the webproxy but I am almost immediately running into problems; probably I am probably doing something wrong. Can you assist? 

**Setup:**
Tutorial setup as found on your website.
server: Azure Sql db as a service
client: Local Sql Express

**Working Client Code:**
```
        static void Main(string[] args)
        {
            var serverOrchestrator = new WebClientOrchestrator("https://localhost:44335/api/sync");
            var clientProvider = new SqlSyncChangeTrackingProvider(@"Data Source=.;Initial Catalog=dbTest;Integrated Security = true;");
            var agent = new SyncAgent(clientProvider, serverOrchestrator);

            do
            {
                var s1 = agent.SynchronizeAsync().GetAwaiter().GetResult();
                Console.WriteLine(s1);
            } while (Console.ReadKey().Key != ConsoleKey.Escape);

            Console.WriteLine("End");
        }
```

**Working Server Code:**
```
  public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.AddMemoryCache();
            var connectionString = @"Data Source=***";

            var tables = new string[] { "AccessRules" };

            var syncSetup = new SyncSetup(tables);
            //syncSetup.Tables["AccessRules"].SyncDirection = SyncDirection.UploadOnly;
            //syncSetup.Tables["AccessRules"].Columns.AddRange(new string[] { "Id", "Name", "RowVersion" });

            services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString,syncSetup);
        }
```

**Scenarios**

1. Works with the code shown above

2.  When I remove the comments from the server line: syncSetup.Tables["AccessRules"].Columns.AddRange(new string[] { "Id", "Name", "RowVersion" });
I get following exception client side:

`Dotmim.Sync.SyncException: 'Cannot drop the trigger 'dbo.Parking_AccessRules_insert_trigger', because it does not exist or you do not have permission.'`

3. When I remove the comments from the server line: syncSetup.Tables["AccessRules"].SyncDirection = SyncDirection.UploadOnly;
I get following startup exception server side:

```
MissingTableException: Table Parking_AccessRules does not exists.
Dotmim.Sync.SetupTables.get_Item(string tableName)
Dotmim.Sync.Webserver.Startup.ConfigureServices(IServiceCollection services) in Startup.cs
+
            syncSetup.Tables["Parking_AccessRules"].Columns.AddRange(new string[] { "Id", "Name", "RowVersion" }); //, "Type", "DriverTypeId", "ZoneId" });
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

Any clues?

**Comment by Mimetis** [comment]
Hello @tijntje ,
Thanks for the feedback.

I found the 2 bugs involved here.
- First one was the `tableName` retrieval from the SetupTable (The `MissingTableException` you get)
- Second one was raised by the `SqlSyncChangeTrackingProvider` when trying to deprovision a trigger, that obviously does not exists.

You can test from the last commit on the master branch.
Just clone the repository locally, then compile all the projects.

If you can't recompile everything locally for some reasons, I will publish an early prerelease of version `0.5.3`

Let me know if everything is working as expected now.

Just one more thing.
I see you are modifying your `SetupTable` by adding columns (or removing)  
In that case, the client table is dropped and recreated.
Don't forget to relaunch a sync with a `SyncType.Reinitialize` to be sure your table will get all the rows again

**Comment by tijntje** [comment]
thanks for the feedback,I will try the 0.5.3 pre release once it is released!

**Comment by tijntje** [comment]
tried with the self build assemblies, which can be the reason it was not working.
I get this exception client side:

{"sc":{"id":"b48a8a43-6599-47fa-a65d-d8f2388270a9","csid":"1f4bfd88-d954-4941-bf0d-ef7c92fe8eaf","sn":"DefaultScope","typ":1,"stage":4,"ps":[]},"schema":{"t":[{"n":"AccessRules","op":"SqlSyncProvider, Dotmim.Sync.SqlServer.SqlSyncProvider","sd":4,"c":[{"n":"Id","dt":"6","iu":true,"ia":true,"seed":1,"step":1,"ps":true,"p1":10,"odb":"Int","oty":"int","db":11},{"n":"Name","dt":"17","iuc":true,"ml":256,"o":1,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"RowVersion","dt":"12","an":true,"ir":true,"o":2,"odb":"Timestamp","oty":"timestamp","db":12}],"pk":["Id"]}],"r":[],"f":[]},"ssi":{"n":"DefaultScope","s":{"tbls":[{"tn":"AccessRules","cols":["Id","Name","RowVersion"],"sd":4}],"fils":[],"v":"1"},"v":"1"}}

**Comment by Mimetis** [comment]
Did you tried with a fresh new database ?
Can you share the schema you are using (at least table AccessRules) ?
And then show me the code you are using, and the flow you are trying

**Comment by tijntje** [comment]
When using the new version it worked without issues. Thanks.

I do have 2 other questions, not related to this topic, so if you want me to move them please give me a sign:
**client performance:**
I have a one direction sync only from server to client with 12 tables and a relative small dataset (max 200 records in a table). I notice that changes are collected fast on the server (300-400ms), but take around 11seconds to apply on the client. Is this normal?

```
Synchronization done.
        Total changes  uploaded: 0
        Total changes  downloaded: 1
        Total changes  applied: 1
        Total resolved conflicts: 0
        Total duration :0:0:11.582
```

**views:**
I tried syncing a view as a table from server to client, but this is not working (I get a table not found exception). Is such a scenario supported?

**Comment by Mimetis** [comment]
## Client Performance

That's not normal. 
Such bad performance on applying changes locally is a problem.
Do you have this kind of performance when you are trying with a brand new client database ?

What kind of client database are you using ? SQL / SQLite / MySQL ?
Which provider ?

Can you share with me your database schema ? (all the tables)
The best for me would be to have a script .sql with the tables and the data, then I would be able to test it faster.

## Views

Yes views is not an option. You can't sync a view, since the **DMS** framework is working only on tables.

**Comment by tijntje** [comment]
I'll try to see what I can do for the schema / data because I am testing it on a commercial application.

I'll use SqlSyncChangeTrackingProvider on both ends, Sql express as a clientdb and azure sql as a service as the serverdb.

**Comment by Mimetis** [comment]
are you exposing your server DB behind a Web API ?
Or are you allowing client to connect directly to the server ?

Maybe your delay comes from the HTTP connection.

Did you try with a server db, locally ? 
Just to ensure the delay is not coming from the http connection

**Comment by Mimetis** [comment]
Since no answer, I will close this issue.
If you're still experiencieng some performance issue, please open a new Github Issue
