### ISSUE TITLE
Trigger error creation

### ISSUE THREAD

**Issue by GerardoHess** [Mimetis/Dotmim.Sync#261]
Hi. I am testing the framework with a SQL Server datamodel that needs to be syncronized thru trigger model.  I am very happy with the results so far. However I am facing a little problem that it seems to be related with the fact that it has some tables with identical name, different schema and same primary key in the model. When I look on the  PrimaryKeys properties info seems to be duplicated. When I reinitialize the agent I recorded this errors.  Any guess where to look at specifically?

![Exception](https://user-images.githubusercontent.com/64089571/79883385-156aeb00-83b1-11ea-9550-0f605d824ee2.png)

![pk duplicated](https://user-images.githubusercontent.com/64089571/79883387-16038180-83b1-11ea-8939-f78dc48b3cfd.png)

**Comment by GerardoHess** [comment]
Thanks!  I attached the script (.tsql) for creating the database and the c# used for sync. 
[Demo.zip](https://github.com/Mimetis/Dotmim.Sync/files/4511742/Demo.zip)

**Comment by Mimetis** [comment]
Ok, got it.
Seems I forgot to add the schema parameter when getting primary keys...

It's fixed in the last commit.

Here is the code I used, and it's working fine. It's a little bit different from your code, for testing purpose, but you will see it's almost same as you:

``` cs
var clientProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(clientDbName));
var serverProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString("Demo"));

// Tables involved in the sync process:
var tables = new string[] { "dbo.Tipo_Zona", "dbo.Institucion_SIRHP", "pag.Institucion_Sirhp" };

var syncSetup = new SyncSetup(tables);
var syncOptions = new SyncOptions();

syncOptions.ScopeInfoTableName = "sscopeInfo";
syncSetup.TrackingTablesPrefix = "s";
syncSetup.StoredProceduresPrefix = "s";
syncSetup.TriggersPrefix = "s";

syncSetup.Tables["dbo.Tipo_Zona"].SyncDirection = SyncDirection.DownloadOnly;
syncSetup.Tables["dbo.Institucion_SIRHP"].SyncDirection = SyncDirection.DownloadOnly;

var agent = new SyncAgent(clientProvider, serverProvider, syncOptions, syncSetup);
do
{
    Console.Clear();
    Console.WriteLine("Web sync start");
    try
    {
        var progress = new SynchronousProgress<ProgressArgs>(pa => Console.WriteLine($"{pa.Context.SessionId} - {pa.Context.SyncStage}\t {pa.Message}"));

        var s = await agent.SynchronizeAsync(progress);

        Console.WriteLine(s);
    }
    catch (SyncException e)
    {
        Console.WriteLine(e.Message);
    }
    catch (Exception e)
    {
        Console.WriteLine("UNKNOW EXCEPTION : " + e.Message);
    }


    Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");
} while (Console.ReadKey().Key != ConsoleKey.Escape);
```

You can test with the source code from master, otherwise waiting for next version `v0.5.3` that I will publish later today, hopefully.

**Comment by Mimetis** [comment]
Can you try with the last version `v0.5.3` ? 
It's now available on **nuget**: https://www.nuget.org/packages?q=dotmim.sync

**Comment by GerardoHess** [comment]
Hi! The new version worked perfectly. If I face any other situation I let you know. Great job, thanks!
