### ISSUE TITLE
First server migration fails due to null initial serverScopeInfo.Setup, Version and so on

### ISSUE THREAD

**Issue by jeremy-waguet** [Mimetis/Dotmim.Sync#265]
I found another issue (but I hope the very last issue) when running my reprovision routine with an empty database (with no serverScopeInfo entry) that can be (UGLY) worked around by try / catching the block
```c#
if (isClentReprovisioning)
{
    var localOrchestrator = (LocalOrchestrator)orchestrator;
    var scopeInfo = await localOrchestrator.GetClientScopeAsync().ConfigureAwait(false);
    scopeInfo.Setup = syncSetup;
    scopeInfo.Schema = newSchema;
    await localOrchestrator.WriteClientScopeAsync(scopeInfo).ConfigureAwait(false);
}
else
{
    var remoteOrchestrator = (RemoteOrchestrator)orchestrator;
    var serverScopeInfo = await remoteOrchestrator.GetServerScopeAsync().ConfigureAwait(false);
    serverScopeInfo.Setup = syncSetup;
    serverScopeInfo.Schema = newSchema;
    await remoteOrchestrator.WriteServerScopeAsync(serverScopeInfo).ConfigureAwait(false);
}
```

or better by initializing the serverScopeInfo instance with setup, schema and version as in the Dotmim.Sync.RemoteOrchestrator.GetServerScopeAsync method right after the "// Compare serverscope setup with current if (serverScopeInfo.Setup != this.Setup) {" (as it is already done in the EnsureSchemaAsync method in the same class) like this :

```c#
SyncSet schema;
// 1) Get Schema from remote provider
(ctx, schema) = await this.Provider.GetSchemaAsync(ctx, this.Setup, connection, transaction, cancellationToken, progress).ConfigureAwait(false);
schema.EnsureSchema();

// Initialize serverscope setup with current if not existing yet
if (serverScopeInfo.Setup == null)
{
    // Generated the first serverscope to be updated
    serverScopeInfo.LastCleanupTimestamp = 0;
    serverScopeInfo.Schema = schema;
    serverScopeInfo.Setup = this.Setup;
    serverScopeInfo.Version = "1";
}

this.logger.LogDebug(SyncEventsId.GetServerScope, $"[{ctx.SyncStage}] database {connection.Database}. serverScopeInfo.Setup != this.Setup. Need migrations ");
```
After patching this, it works even with an empty serverScopeInfo on first run and I checked it also works when adding a dummy column to an existing table

**Comment by Mimetis** [comment]
The provision or Deprovision methods are useful only if you have already done a first sync before.

For the modification you've done, do you want to make a PR ?

**Comment by jeremy-waguet** [comment]
#266 here is it :)

**Comment by jeremy-waguet** [comment]
#266 closing this issue as related PR has been closed.
