### ISSUE TITLE
Handling Offline record recreation with auto increment Primary Key

### ISSUE THREAD

**Issue by paintballkev812** [Mimetis/Dotmim.Sync#267]
Hi, I was wondering if Dotmim.Sync has a way to handle the a scenario I would need. I tried searching the docs, but didn't find what I was looking for.

I have an application that has a MS SQL as a remote server and SQLite as the local database. There are occasions where the client application will not have network connectivity and will need to create records on the local table and sync the data at a later time. There is also the very likely possibility that multiple client applications will be creating records to the table during this time span. The table in question has a simple ID column that is set as the primary key and auto increments.

My question is specifically handle the following scenario:

Client A and Client B sync Table 1 at the same time so they both have an identical copy of the remote data stored into an SQLite local DB. Table 1 has the last record ID of 505. Client A uses the application without an internet connection and adds a new record to Table 1. In sqlite, it is assigned the row ID of 506. Client B has a stable internet connection and inserts a new row into Table 1 and is assigned the row ID of 506 and sync's without issue.  Some time later, Client A gets back to a stable internet connection and sync's the data. 

In my test of this scenario, dotmim.sync will try to add the record to the remote Db, notices that there is a record with row ID 506 already existing and will resolve the conflict with the server winning and client A's data being discarded. 

What I am hoping to accomplish is for dotmim.sync to somehow realize (or for me to somehow notate) that Client A's 506 record was newly created created locally and that it is a different record than the remote DB's 506 (originating from Client B) so it should insert Client A's record into the remote DB with a new ID (ie 507) and then update Client A's local database to match the remote DB.

Is there someway to accomplish this in Dotmim.sync (or some way I could accomplish this by handling the Primary Key differently)?

**Comment by Mimetis** [comment]
The only way to work with Identity columns as Primary keys is to define range of ids.

For instance, you can define something like that:
- Server IDS range: 1 -  99 999 999
- Client 1 IDS range:  100 000 000 - 100 999 999
- Client 2 IDS range:  101 000 000 - 101 999 999
- Client 3 IDS range:  102 000 000 - 102 999 999

You can store these values in any configuration table.   
When you reach the limit for one client (or server), just change the range for a new one.

It's this method that uses SQL Server merge fusion, internally
Some useful links:
- https://docs.microsoft.com/en-us/sql/relational-databases/replication/publish/replicate-identity-columns?view=sql-server-2017
- https://www.mssqltips.com/sqlservertip/6093/sql-server-merge-replication-identity-range-management/

**Comment by paintballkev812** [comment]
Thanks! I was hoping there would be a better method, but I may just need to go with this.

**Comment by Mimetis** [comment]
I'm currently working on an option to allow you to manage identity more easily.
I will let you know once it's done, and you will be able to test it, if you want

**Comment by paintballkev812** [comment]
That sounds great, I'll keep an eye out for it.
