### ISSUE TITLE
Errors in tests and build

### ISSUE THREAD

**Issue by jader1313** [Mimetis/Dotmim.Sync#268]
I am trying to build and test the project to implement a new provider for the Visual FoxPro database (DBC / DBF) but it is showing errors in the Dotmim.Sync.Postgres project:
- Builders folder empty.
- NpgsqlManager class name error
- missing NpgsqlScopeBuilder, NpgsqlTableBuilder and NpgsqlBuilder

Is there any documentation for developing a new provider?

**Comment by jader1313** [comment]
What is the path of the stones to build and test the project?

**Comment by Mimetis** [comment]
Hey @jader1313 .
Sorry for the errors raised from the Postgres provider.
I'm currently working on it !

If you want to build everything correctly, just remove the Postgres project, it should be fine.

The minimum projects list is:
- Dotmim.Sync.Core
- Dotmim.Sync.MySql
- Dotmim.Sync.Sqlite
- Dotmim.Sync.SqlServer
- Dotmim.Sync.SqlServer.ChangeTracking
- Dotmim.Sync.Web.Client
- Dotmim.Sync.Web.Server

There is no documentation for developing a new provider.
You should start from an existing one I guess.
SQL Server is the most advanced one, and SQLite is quite simple, but does not work as a Server provider.
Just choose one you understand well, and start from there
