### ISSUE TITLE
[Proposal] - Use schema as table prefix on client providers other than mssql

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#27]
Hi!

Seems you are making great progress here! It really looks awesome!
I went through the wiki, and saw the schema option:
https://github.com/Mimetis/Dotmim.Sync/wiki/04-Sql-Server-provider-:-Schema

I know a CMS called "Orchard" (Orchard Core is now the vnext in beta) which also supports a wide range of sql databases and requires something like a schema where it is not supported (mysql, sqlite, etc.)

Here, they simply use the schema name as prefix (e.g. with an underscore)

So in the example 
`agent.Configuration["Address"].Schema = "SalesLT";`

On sqlite thos could become something like
`SalesLT_Address`

This could also be configurable:
* enable/disable prefixes  (for compatibility reasons, I think the no brainer option would be to add these prefixes by default for all tables that do not belong to the [dbo] schema)
* [optionally] define how the prefix schould be calculated (Func<string, string>) so that I could:
   use another concatenator than underscore, or uppercase/lowercase the whole schemaname

This would be a nice addition :-)

**Comment by Mimetis** [comment]
Hey, thx @gentledepp  for your feedback !!!   
That could be a nice feature indeed. I will made investigations on that, and if it's Something not too complicated, will implement it 👍

**Comment by Mimetis** [comment]
Fo now, and until v1 is out, this feature is abandonned
