### ISSUE TITLE
Support SQL-Server "Synonym"

### ISSUE THREAD

**Issue by alexkleinwaechter** [Mimetis/Dotmim.Sync#271]
Hi,
we have an exisiting application with different table names on client and server with the same column definitions. We can't rename tables on either side easily. 

My Idea was to use sql server synonyms (https://docs.microsoft.com/en-us/sql/t-sql/statements/create-synonym-transact-sql) to have equal table names.

Synonyms are supported by the t-sql CHANGETABLE command (https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/changetable-transact-sql):
"The table name can be a synonym to the table"

Unfortunately Dotmim throws an "table does not exist" error at agent.SynhronizeAsync().

Is there a possibilty for us to solve our problem without renaming the tables?

Best!
Alex from Berlin

**Comment by alexkleinwaechter** [comment]
Fun-Fact which is perhaps sufficent for us:

We use download direction only
You can then make Synonyms work:
1. Rename Tables on server temporary to the same name as client tables
2. Provision
3. Rename Tables on server back to old names (different names than client)
4. Create synonyms on server equal to the names on client
5. Run synchronization (works fine!)

Best!
Alex

**Comment by Mimetis** [comment]
Using Synonym is really an *edge feature*

I even don't know if I can implement "something" that could help here.

I'm happy to see you figured it out !

**Comment by Mimetis** [comment]
I'm closing this issue since you found a solution,
Let me know if I should reopen it.
