### ISSUE TITLE
SQL-Error if there is a dot in constraint name

### ISSUE THREAD

**Issue by alexkleinwaechter** [Mimetis/Dotmim.Sync#274]
Hi,

in our SQL-Server database we have some dots in the constraint names for primary and foreign keys:
![image](https://user-images.githubusercontent.com/24670532/81592599-7e48f000-93be-11ea-83bf-14d97fd34f5a.png)
In this case we get an sql error while syncing: sql error near "."....
If we rename the constraints things are working again.
Best!
Alex

**Comment by Mimetis** [comment]
Thanks Alex;
I will look into it

**Comment by Mimetis** [comment]
resolved in `v0.5.5-beta-0411`
You can test it with the prerelease nuget packages https://www.nuget.org/packages/Dotmim.Sync.Core/0.5.5-beta-0411

Let me know if it's actually resolved for you.
if not, I will re-open the issue.
