### ISSUE TITLE
combined PrimaryKey nvarchar + guid gives conversion error

### ISSUE THREAD

**Issue by alexkleinwaechter** [Mimetis/Dotmim.Sync#277]
Hi,
me again :-)
I have a table kike this:
![image](https://user-images.githubusercontent.com/24670532/81846018-b9c7f380-9551-11ea-8cac-f85b1961e613.png)
On sync I get an overflow conversion error:
Dotmim.Sync.SyncException
  HResult=0x80131500
  Message=Arithmetischer Überlauffehler beim Konvertieren von expression in den nvarchar-Datentyp.
Die Anweisung wurde beendet.
  Source=Dotmim.Sync.Core
  StackTrace:
   at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception)
   at Dotmim.Sync.LocalOrchestrator.<ApplyChangesAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__54.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TesrDbSync.DotmimSyncXSP.<Sync>d__1.MoveNext() in C:\Source_ITI\dev\TesrDbSync\TesrDbSync\DotmimSyncXSP.cs:line 100

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
**SqlException: Arithmetischer Überlauffehler beim Konvertieren von expression in den nvarchar-Datentyp.**
Die Anweisung wurde beendet.

I really like your project!
Best 
Alex

**Comment by alexkleinwaechter** [comment]
No hurry, I changed the nvarchar key part to varchar. Then it worked.

**Comment by Mimetis** [comment]
@alexkleinwaechter ,
I've made some tests, and it's working for me.
Can you describe a little bit more ?
Server provider ? Client Provider ? Is it happening on first sync ? during conflict ? during client insert / server insert ?
can you share your code / schema ?

**Comment by alexkleinwaechter** [comment]
I am on version 0.5.4 with SQL Server 2016
`            var serverProvider = new SqlSyncChangeTrackingProvider(serverConnectionString);
            var clientProvider = new SqlSyncChangeTrackingProvider(clientConnectionString);
            var tables = new string[]
            {
                "NewsClient",
                "NewsClientLanguages"
            };
            syncSetup.Tables["NewsClient"].SyncDirection = SyncDirection.DownloadOnly;
            syncSetup.Tables["NewsClientLanguages"].SyncDirection = SyncDirection.DownloadOnly;
            var options = new SyncOptions();
            var localOrchestrator = new LocalOrchestrator(clientProvider, options, syncSetup);
            var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, syncSetup);
            var agent = new SyncAgent(localOrchestrator, remoteOrchestrator);
            var result = await agent.SynchronizeAsync();`

Database script for the two tables:
`CREATE TABLE [dbo].[NewsClient](
	[Guid] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[BaseAddress] [nvarchar](255) NULL,
	[ServicePath] [nvarchar](500) NOT NULL,
	[ContactEmails] [varchar](8000) NULL,
	[LastSyncDate] [datetime] NULL,
	[LastSyncStatus] [bit] NOT NULL,
	[LastSuccessfulSyncDate] [datetime] NULL,
	[Logo] [nvarchar](max) NULL,
	[Active] [bit] NOT NULL,
	[NewsletterPath] [nvarchar](500) NULL,
	[IsEnabledForNewsletter] [bit] NOT NULL,
	[IsPublicForNewsletter] [bit] NOT NULL,
	[IsNewsletterClient] [bit] NOT NULL,
 CONSTRAINT [PK_NewsClient] PRIMARY KEY CLUSTERED 
(
	[Guid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[NewsClient] ADD  CONSTRAINT [DF_NewsClient_Active]  DEFAULT ((1)) FOR [Active]
GO

ALTER TABLE [dbo].[NewsClient] ADD  DEFAULT ((0)) FOR [IsEnabledForNewsletter]
GO

ALTER TABLE [dbo].[NewsClient] ADD  DEFAULT ((0)) FOR [IsPublicForNewsletter]
GO

ALTER TABLE [dbo].[NewsClient] ADD  DEFAULT ((0)) FOR [IsNewsletterClient]
GO



CREATE TABLE [dbo].[NewsClientLanguages](
	[Language] [nvarchar](10) NOT NULL,
	[NewsClientGuid] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_NewsClientLanguages] PRIMARY KEY CLUSTERED 
(
	[NewsClientGuid] ASC,
	[Language] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[NewsClientLanguages]  WITH CHECK ADD  CONSTRAINT [FK_NewsClientLanguages_NewsClient] FOREIGN KEY([NewsClientGuid])
REFERENCES [dbo].[NewsClient] ([Guid])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[NewsClientLanguages] CHECK CONSTRAINT [FK_NewsClientLanguages_NewsClient]
GO

`

**Comment by Mimetis** [comment]
Thanks. I will make some tests.
I have edited your post for a better formatting using ` ` `

**Comment by Mimetis** [comment]
resolved in `v0.5.5-beta-0411`
You can test it with the prerelease nuget packages https://www.nuget.org/packages/Dotmim.Sync.Core/0.5.5-beta-0411

Let me know if it's actually resolved for you.
if not, I will re-open the issue.
