### ISSUE TITLE
Request: Document Enhancement for SqlSyncChangeTrackingProvider

### ISSUE THREAD

**Issue by alexkleinwaechter** [Mimetis/Dotmim.Sync#278]
Hi,
I try to adapt the deprovision examples from https://dotmimsync.readthedocs.io/Provision.html with the SqlSyncChangeTrackingProvider. On the RemoteOrchestrator there is no method: WriteServerScopeAsync. Isn't it needed in that case?
![image](https://user-images.githubusercontent.com/24670532/82038169-6d8cc880-96a3-11ea-87ff-f9a8e83e4923.png)

Best.
Alex

**Comment by Mimetis** [comment]
Hello @alexkleinwaechter.
Which version are you using ?

**Comment by alexkleinwaechter** [comment]
version 0.5.4

**Comment by Mimetis** [comment]
You should try with the last pre release version 0.5.5, it should work as expected
