### ISSUE TITLE
Does not sync and Dotmim.Sync.SyncException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by TybbyAce** [Mimetis/Dotmim.Sync#279]
Hi,

Please help!

DMS does not sync if client database was created before fist sync attempt.

All scenarios involves MySql server and SQLite client and run on Xamarin.iOS.

**Scenario 1**: Server table exists and has a record - but not supporting tables - , client database does not exist. After sync, client DB gets created - with all additional tables on both server and client - and after records added to the client, subsequent syncs work just fine.

**Scenario 1.a**: Server table exists -without supporting tables - but is empty, client database does not exist. After first sync all supporting tables get created on both server and client side. After adding a record to the client and attempting to sync again it throws a "Dotmim.Sync.SyncException: Input string was not in a correct format" error.

**Scenario 2**: Both client and server tables exist, with same structure - without supporting tables - , server table is empty, client has records. Sync creates supporting tables, stored procedures etc. both on the server and client but does not upload any record from client to server. No error thrown.

**Scenario 2.a**: Both client and server tables exist, with same structure - without supporting tables - , (client table got created before 1st sync attempt) both tables are empty. First sync with empty tables is successful! After writing a record to the client and attempting to sync an error is thrown by var result = await agent.SynchronizeAsync(progress);

**Dotmim.Sync.SyncException: Input string was not in a correct format.**

at Dotmim.Sync.BaseOrchestrator.RaiseError (System.Exception exception) [0x0004a] in /Users/tibor/Dropbox/C# projects/Repos/Dotmim.Sync/Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.cs:207

  at Dotmim.Sync.RemoteOrchestrator.ApplyThenGetChangesAsync (Dotmim.Sync.ScopeInfo clientScope, Dotmim.Sync.Batch.BatchInfo clientBatchInfo, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00f5f] in /Users/tibor/Dropbox/C# projects/Repos/Dotmim.Sync/Projects/Dotmim.Sync.Core/Orchestrators/RemoteOrchestrator.cs:651

  at Dotmim.Sync.SyncAgent.SynchronizeAsync (Dotmim.Sync.Enumerations.SyncType syncType, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x010ea] in /Users/tibor/Dropbox/C# projects/Repos/Dotmim.Sync/Projects/Dotmim.Sync.Core/SyncAgent.cs:580
  

Please advise.

Thank you

Code:
```c#

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Dotmim.Sync;
using Dotmim.Sync.Enumerations;
using Dotmim.Sync.MySql;
using Dotmim.Sync.Sqlite;
using Xamarin.Forms;
using Microsoft.Data.Sqlite;

namespace XamarinSynctest
{
    // Learn more about making custom code visible in the Xamarin.Forms previewer
    // by visiting https://aka.ms/xamarinforms-previewer
    [DesignTimeVisible(false)]
    public partial class MainPage : ContentPage
    {

        private static readonly string serverConnectionString = "server = xxxxxxxxx.eu-west-1.rds.amazonaws.com;SSL Mode=Required; user id = XXXX; password =XXXXX; database = test database; AllowLoadLocalInfile=true; ConnectionTimeout=30";
        static private readonly string clientPathAndName = Path.Combine(Xamarin.Essentials.FileSystem.AppDataDirectory, "test.db3");
        static private readonly string sqliteConnectionString = $"Data source = {clientPathAndName}";

        public MainPage()
        {
            InitializeComponent();
        }

        public static async Task SyncDB()
        {
            SQLitePCL.Batteries_V2.Init();

            // Sql Server provider, the "server" or "hub".
            MySqlSyncProvider serverProvider = new MySqlSyncProvider(serverConnectionString);

            // Sqlite Client provider acting as the "client"
            SqliteSyncProvider clientProvider = new SqliteSyncProvider(clientPathAndName);

            // Tables involved in the sync process:
            var tables = new string[] { "testtable" };

            var options = new SyncOptions { ConflictResolutionPolicy = ConflictResolutionPolicy.ClientWins };
            // Sync agent

            SyncAgent agent = new SyncAgent(clientProvider, serverProvider, tables);
            var progress = new SynchronousProgress<ProgressArgs>(args => Console.WriteLine($"{args.Context.SyncStage}:{args.Message}"));

            var result = await agent.SynchronizeAsync(progress);
            Console.WriteLine(result);
        }

        private async void Button_Clicked(System.Object sender, System.EventArgs e)
        {
            await SyncDB();
        }

        void btnWriteARecord_Clicked(System.Object sender, System.EventArgs e)
        {
            Guid guid = Guid.NewGuid();
            string GUID = guid.ToString().ToUpper();
            string sql = $"INSERT INTO testtable (ID,F1,F2,F3) VALUES ( '{GUID}', '1stItem','1','1111111')";
            Console.WriteLine(sql);
            using (SqliteConnection dBase = new SqliteConnection(sqliteConnectionString))
            {
                try
                {
                    dBase.Open();
                    SqliteCommand cmd = new SqliteCommand(sql, dBase);
                    cmd.ExecuteNonQuery();
                    dBase.Close();
                    Console.WriteLine("Record added " + clientPathAndName);
                }
                catch (SqliteException ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }
        }

        void btnCreateSQLite_Clicked(System.Object sender, System.EventArgs e)
        {
            if (!File.Exists(clientPathAndName))
            {
                string sql = "CREATE TABLE [testtable] (" +
   "[ID] blob NOT NULL UNIQUE" +
   ",[F1] integer NULL" +
   ",[F2] text NOT NULL COLLATE NOCASE" +
   ",[F3] text NULL COLLATE NOCASE" +
 ", PRIMARY KEY([ID]))";

             using (SqliteConnection dBase = new SqliteConnection(sqliteConnectionString))
                {
                    try
                    {
                        dBase.Open();
                        SqliteCommand cmd = new SqliteCommand(sql, dBase);
                        cmd.ExecuteNonQuery();
                        dBase.Close();
                        Console.WriteLine("Database created: " + clientPathAndName);
                    }
                    catch (SqliteException ex)
                    {
                        Console.WriteLine(ex.Message);
                    }

                }

            }
        }
    }
}

**Comment by Mimetis** [comment]
Can you share 3 repro projects?

**Comment by Mimetis** [comment]
> **Scenario 1.a** : Server table exists -without supporting tables - but is empty, client database does not exist. After first sync all supporting tables get created on both server and client side. After adding a record to the client and attempting to sync again it throws a "Dotmim.Sync.SyncException: Input string was not in a correct format" error.

Can you share a repro project ?

> **Scenario 2** : Both client and server tables exist, with same structure - without supporting tables - , server table is empty, client has records. Sync creates supporting tables, stored procedures etc. both on the server and client but does not upload any record from client to server. No error thrown.

That's normal. Client has rows, but these rows are not tracked, that's why they are not uploaded
IF you want to upload them, you can manually provision the `tracking` table rows.
Something like

``` sql
INSERT INTO [Client_tracking]
 ([ClientID] ,[update_scope_id] ,[sync_row_is_tombstone],[last_change_datetime]) 
SELECT [Client].[ClientID] ,NULL ,0 ,GetUtcDate()
FROM [Client] [i]
```

> **Scenario 2.a** : Both client and server tables exist, with same structure - without supporting tables - , (client table got created before 1st sync attempt) both tables are empty. First sync with empty tables is successful! After writing a record to the client and attempting to sync an error is thrown by var result = await agent.SynchronizeAsync(progress);

I need a repro. This scenario seems similar to **Scenario 1.a**, right ?

**Comment by Mimetis** [comment]
You have an error here :

``` csharp
string sql = $"INSERT INTO testtable (ID,F1,F2,F3) VALUES ( '{GUID}', '1stItem','1','1111111')";
```
**F1** is **NOT** A STRING, if we look at your create table statement:

``` csharp
string sql = "CREATE TABLE [testtable] (" +
   "[ID] blob NOT NULL UNIQUE" +
   ",[F1] integer NULL" +
   ",[F2] text NOT NULL COLLATE NOCASE" +
   ",[F3] text NULL COLLATE NOCASE" +
 ", PRIMARY KEY([ID]))";
```
It seems to be an **INTEGER** ...

That's why you have this issue "`Dotmim.Sync.SyncException: Input string was not in a correct format`"

Please be careful with your hard coded statements ...

**Comment by Mimetis** [comment]
Eventually everything is working correctly:
Please remember than:
- A client database with existing rows won't be applied on the server, if rows exists *before* sync is enabled
- Please be careful with your statements.

**Comment by TybbyAce** [comment]
Thank you for spotting the error in the statement! It was the problem.
As for the manual provisioning, no dice. I created the whole SQLite with index and insert trigger etc., when added a record it got into the _tracking table with no problem but still didn't get synced (the server didn't have all the stored procs etc., just the main table. They got created, no issue, but the record didn't get uploaded.)

What would be your recommendation for a mobile app when the user uses the app for god knows how long, then after a while they decide to share it with colleagues, friends etc.? The data has to be stored long before the first sync. Forcing the app to sync on the very first launch -behind the scenes - is a solution but 1) what if the user never gets to sync 2) first launch might be a bit slow, messing with user experience (hell, if there's no better way I have to do that anyways).

Thanks for your support!

**Comment by Mimetis** [comment]
I will provider a sample, but it will require two sync, I think

**Comment by Mimetis** [comment]
I've created a new method that will help you a lot in this situation, called
It's still not documented, but here is a quick sample:

``` csharp

// Make a first sync to get the schema from server, provision all tracking tables , 
// stored procedures, triggers and so on...
var s = await agent.SynchronizeAsync();

// Here, we should not have any uploaded rows, since it's the first sync.
// But, eventually we have all the rows from server.
Console.WriteLine(s);

// Get local schema
var schema = await agent.LocalOrchestrator.GetSchemaAsync();

// Update all rows on the client side that does not have any tracking rows
await agent.LocalOrchestrator.UpdateUntrackedRowsAsync(schema);

// Make as second sync.
// All local rows that were existing before first sync happened, will be uploaded correctly
s = await agent.SynchronizeAsync();

```
This method is available in the last prerelease version, available from nuget.

Let me know if it's working correctly for you !

**Comment by Blogrammer** [comment]
The `UpdateUntrackedRowsAsync()` is worth documenting. I don't know if it has been documented already. 

I had difficulty figuring out why rows created before the first sync could not be uploaded from the client database to the server.

@Mimetis, if you don't have the time I can help out with the documentation. 

I appreciate your hard work. :)

**Comment by Mimetis** [comment]
I would love !

**Comment by sojan1** [comment]
Dotmim.Sync.SyncException: '[NeedsToUpgradeAsync]..[GetConnectionAsync]..Instance failure.'

error
![image](https://github.com/Mimetis/Dotmim.Sync/assets/111710684/5953ead4-65f3-4ae6-8471-a4ccc5d0b386)
