### ISSUE TITLE
[Proposal] Syncconflict - allow to merge changes

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#28]
Hello!

Just had a look at the conflict resolution documentation here
https://github.com/Mimetis/Dotmim.Sync/wiki/06-Sync-conflict

My question:
What if I wanted to manually merge the information from client and server (combine them)

Would that be possible, by editing the client-rows like so?

```
 var dmRowClient = e.Conflict.LocalChanges.Rows[0];

// Example 1 : Resolution based on rows values
if ((int)dmRowServer["ClientID"] == 100 && (int)dmRowClient["ClientId"] == 0)
{
  dmRowClient["CLientId"] = 100;
  e.Action = ApplyAction.RetryWithForceWrite;
}
```
Would that already work?

But in that case, it would overwrite all the columns of the server row.

Would it also be possible to modify the server row (so I can edit only the one or two columns from the client that I care about, without risking to overwrite server columns that should not be affected) with client data and store that one?

**Comment by Mimetis** [comment]
You will have (soon) an `Action` enumeration to be able to merge row.  
Then you will be able to do Something like that:

```
 var dmRowClient = e.Conflict.LocalChanges.Rows[0];

// Example 1 : Resolution based on rows values
if ((int)dmRowServer["ClientID"] == 100 && (int)dmRowClient["ClientId"] == 0)
{
  dmRowClient["CLientId"] = 999;
  dmRowServer["ClientID"] = 999
  e.Action = ApplyAction.Merge;
}
```

**Comment by Mimetis** [comment]
Eventually this feature has been implemented !  
See wiki here : [https://github.com/Mimetis/Dotmim.Sync/wiki/06-Sync-conflict](https://github.com/Mimetis/Dotmim.Sync/wiki/06-Sync-conflict)   

If you want to *merge* a row, you will have to handle the `ApplyChangedFailed` event and then fill the FinalRow object with the value you want to provider for both server and client:  

In this sample the client and server row is in conflict. The final row is overriding both values:

```
static void ApplyChangedFailed(object sender, ApplyChangeFailedEventArgs e)
{
    e.Action = ConflictAction.MergeRow;
    e.FinalRow["RegionDescription"] = "Eastern alone !";
}
```
