### ISSUE TITLE
Can we use SQL CE database having .sdf extentsion

### ISSUE THREAD

**Issue by lv1986** [Mimetis/Dotmim.Sync#280]
Hi, 
This is not an issue but I would like to know if we can use SQL CE database having .sdf extenstion? If yes how?

**Comment by Mimetis** [comment]
I'm sorry SQL CE is not supported
If you want to use DMS with a standalone database, you can use SQLite instead of SQL CE.

**Comment by lv1986** [comment]
Thanks for your quick reply
