### ISSUE TITLE
How to add OR Condtion using .AddCustomWhere()

### ISSUE THREAD

**Issue by lv1986** [Mimetis/Dotmim.Sync#281]
Hi,
When I am using .AddCustomWhere() it is adding string at the end of stored procedure like 

Select * from TableName where id=@id and [String in .AddCustomWhere()). 

What I am trying to achieve is using OR instead of AND 

Say I have table name AbpUsers which have TenantId [NULL Bool Column], I would like to have query like this : 
`Select * from AbpUsers where TenantId=@TenantIdOR TenantId IS NULL`

I have used filters like this:

`
//----- Filters 
SetupFilter userFilter = new SetupFilter("AbpUsers");
userFilter.AddParameter("TenantId", DbType.Int64,false);
userFilter.AddWhere("TenantId", "AbpUsers", "TenantId");
userFilter.AddCustomerWhere("TenantId IS NULL");
setup.Filters.Add(userFilter);`

This  is creating stored procedure like: 

`WHERE
 (
   ([base].[TenantId] = @TenantId)
  )

AND
(
  TenantId IS NULL
)
`

But I need OR instead of AND in last condition.

One More thing: Who to update stored procedures if I add/remove filters? Do they automatically updated or there is any other process?

**Comment by TenantID** [comment]
Excuse me, who are you and what are you trying to do with our TenantID code?

**Comment by Mimetis** [comment]
First option:

You need to get tenant by id or all tenant if **tenant parameter** is set to NULL

Instead of
``` cs
userFilter.AddParameter("TenantId", DbType.Int64, false);
```

You may want to say "hey this parameter **could** be null"
``` cs
userFilter.AddParameter("TenantId", DbType.Int64, true);
```

Then the code generated will be

``` sql
WHERE
(
[base].[TenantId] = @TenantID OR @TenantID is null
)
```

Now second option: You need to get tenant when **tenant column** value is null.
You can't use the `AddWhere()` 
Instead, you need to use `AddCustomeWhere()`

Something like
``` cs
userFilter.AddCustomerWhere("[base].[TenantId] = @TenantId OR [base].[TenantId] IS NULL")
```

**Comment by lv1986** [comment]
Thanks, 
Can you please answer: 
One More thing: How to update stored procedures if I add/remove filters? Do they automatically updated or there is any other process?

**Comment by Mimetis** [comment]
You need to Provision and Deprovision
See here for more info : https://dotmimsync.readthedocs.io/Provision.html

**Comment by lv1986** [comment]
Thanks a lot it worked 

`userFilter.AddCustomerWhere("[base].[TenantId] = @TenantId OR [base].[TenantId] IS NULL")`

**Comment by gentledepp** [comment]
@lv1986  just curious: Are you using AspNet Boilerplate?

**Comment by TenantID** [comment]
Guys, I own @tenantid and I keep getting emails from you all about some
issue you have.
Can you please stop putting '@tenantid' in your GitHib questions?
We are a tenant identity service and we have @tenantid so for some reason
your emails are all copying to me.
Thank you!

**Comment by Mimetis** [comment]
@TenantID : It should be fixed. The problem was from the first message where the `SQL` statement contains a `@TenantID` parameter, but @lv1986 did not quote the word inside csharp ` 

Should be ok now

**Comment by lv1986** [comment]
> 
> 
> @lv1986 just curious: Are you using AspNet Boilerplate?

Yes I am
