### ISSUE TITLE
Problem with SyncDirection.UploadOnly

### ISSUE THREAD

**Issue by TybbyAce** [Mimetis/Dotmim.Sync#282]
Hi,

I am trying to minimize the sync overhead in my mobile app (xamarin) with uploading only to the server of the modified client record instead of a full sync every time.
So, the scenario is that the user modifies data in an entry on the phone and when the entry_unfocused runs I call a sync where I want to upload the changed record to the server without downloading anything.
Server: Mysql.
Client:SQLite.
What happens is that the modified record does not get uploaded and the next full sync the client database loses all of the records! The sync empties the table :(

Please help.

Thanks

Here's the full sync: (Runs fine if the upload-only routine is never called)
```c#

   public static async Task Sync()   
        {
            MySqlSyncProvider serverProvider = new MySqlSyncProvider(serverConnectionString);

            SqliteSyncProvider clientProvider = new SqliteSyncProvider(databasePathAndName);
            var progress = new SynchronousProgress<ProgressArgs>(args => Console.WriteLine($"{args.Context.SyncStage}:{args.Message}"));
            var tables = new string[] { myTablename };
            var syncSetup = new SyncSetup(tables);
            syncSetup.Tables[myTablename].SyncDirection = Dotmim.Sync.Enumerations.SyncDirection.Bidirectional;
            SyncAgent agent = new SyncAgent(clientProvider, serverProvider, new SyncOptions(), tables);
            var result =  await agent.SynchronizeAsync(progress);
            Console.WriteLine(result);
        }


And the upload-only procedure:

 public static async Task SyncUploadOnly()   
        {
          
            var tables = new string[] { myTablename };
            var syncSetup = new SyncSetup(tables);
            syncSetup.Tables[myTablename].SyncDirection = Dotmim.Sync.Enumerations.SyncDirection.UploadOnly;
            MySqlSyncProvider serverProvider = new MySqlSyncProvider(serverConnectionString);
            SqliteSyncProvider clientProvider = new SqliteSyncProvider(databasePathAndName);
            var progress = new SynchronousProgress<ProgressArgs>(args => Console.WriteLine($"{args.Context.SyncStage}:{args.Message}"));
            SyncAgent agent = new SyncAgent(clientProvider, serverProvider,new SyncOptions(), syncSetup);
            var result = await agent.SynchronizeAsync(progress);
            Console.WriteLine(result);
        }

**Comment by Mimetis** [comment]
can you share your table schema ?

**Comment by TybbyAce** [comment]
Hi,

This is what I get out the database managers:
(Note: ID is GUID)

Thanks a bunch!

Client SQLite:

```SQL
CREATE TABLE [TEST] (
	[ID] text   NOT NULL COLLATE NOCASE
	,[F1] integer   NOT NULL 
	,[F2] text   NOT NULL COLLATE NOCASE
	,[F3] text   NULL COLLATE NOCASE
	,[F4] text   NULL COLLATE NOCASE
	,[F5] text   NULL COLLATE NOCASE
	,PRIMARY KEY ([ID]))

```

Server MySQL:

```SQL
CREATE TABLE `TEST` (
  `ID` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `F1` tinyint(4) NOT NULL,
  `F2` varchar(45) COLLATE utf8mb4_bin NOT NULL,
  `F3` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `F4` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  `F5` varchar(45) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

**Comment by Mimetis** [comment]
Hello @TybbyAce 

The issue should be fixed with my last commit.
Can you please test with the last source code from the master branch ?

**Comment by gentledepp** [comment]
@Mimetis 
Best practice is to *always* add a unit test for any bug you fix!
The first versions of Dotmim.Sync were very, very brittle and instable and caused us a lot of headache.
Please make sure you also improve the code coverage and stability towards an 1.0 release! :-|

**Comment by Mimetis** [comment]
I know, I know...
Just a lack of time...
This project is so time consuming ! :)

But you're right, apologizes for that, will try to make the unit test asap

God damn it ! It was "just" a side project at the very begining !!!!! ;)

**Comment by YouthLab** [comment]
> I know, I know...
> Just a lack of time...
> This project is so time consuming ! :)
> 
> But you're right, apologizes for that, will try to make the unit test asap
> 
> God damn it ! It was "just" a side project at the very begining !!!!! ;)

Not everyone understands the meaning of the open source and contribution.
Thank you for your hard work.

**Comment by TybbyAce** [comment]
Sorry, I don't think I understand what you mean.

**Comment by Mimetis** [comment]
This main method contains a full test I made, regarding your issue

https://github.com/Mimetis/Dotmim.Sync/blob/03233f12adfb280720dfabea3d6a9b28a7b7eef4/Samples/Dotmim.Sync.SampleConsole/Program.cs#L43

Look at it, and analyze the diff between you and me
