### ISSUE TITLE
dotmim.sync.syncexception: there is already an object named 'orders_update' in the database.

### ISSUE THREAD

**Issue by dmrnht** [Mimetis/Dotmim.Sync#289]
I requested a synchronization of a table from my mssql database on my local machine to mssql on the live server with your default codes and the error returned was "dotmim.sync.syncexception: there is already an object named 'orders_update' in the database." It was. There are neither a field nor a column named "orders_update" in both databases I want to match.
Do I have to do something for synchronization in the database?

**Comment by Mimetis** [comment]
Do you find your issue ?

**Comment by dmrnht** [comment]
I caught the reason for my problem from the sentences you sent via e-mail, but now I opened the issue as to how I can solve it. I will be grateful if you could help me. thanks
