### ISSUE TITLE
about the error caused by triggers

### ISSUE THREAD

**Issue by dmrnht** [Mimetis/Dotmim.Sync#290]
There are defined triggers in the tables in the database that I want to synchronize. Therefore, during synchronization, "dotmim.sync.syncexception: there is already an object named 'orders_update' in the database." I get an error. What is the way to get rid of this error?

**Comment by Mimetis** [comment]
It depends why we have this "orders_update" thing
is it a trigger that already exists or stored procedure ?

I need more info to help you

Maybe share your database table schema

**Comment by dmrnht** [comment]
The database I wanted to synchronize is a database used by another application that I cannot interfere with. For this reason, I will perform my own works from the database located in the place I carry by doing a synchronization. Unfortunately, when I want to do this, I am experiencing the error I mentioned.
![Capture](https://user-images.githubusercontent.com/46296165/84784003-777f4f80-aff2-11ea-89be-4a006c1ff81f.PNG)

**Comment by Mimetis** [comment]
the triggeres were already existing before trying to create the sync ?

**Comment by Mimetis** [comment]
Look the doc here : https://dotmimsync.readthedocs.io/Configuration.html

You can customize the triggers naming convention, by using `TriggersPrefix` from your `SyncSetup` instance:

For example:

``` csharp
var tables = new string[] {"ProductCategory", "ProductModel", "Product",
        "Address", "Customer", "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail" };

var setup = new SyncSetup(tables)
    {
        StoredProceduresPrefix = "s",
        StoredProceduresSuffix = "",
        TrackingTablesPrefix = "t",
        TrackingTablesSuffix = "",
        TriggersPrefix = "t",
        TriggersSuffix = ""
    };
```

Let me know if it's working for you

**Comment by dmrnht** [comment]
Thank you so much. My problem has improved.
