### ISSUE TITLE
Nuget package loading issue

### ISSUE THREAD

**Issue by janardhan96** [Mimetis/Dotmim.Sync#291]
While running the project  following issue occurred. I have installed all the dependency DLLs.
![image](https://user-images.githubusercontent.com/22150637/84796622-73652900-b016-11ea-8246-8e16d74c1ae9.png)

**Comment by Mimetis** [comment]
Can you try with the preview version `0.5.6` ?

https://www.nuget.org/packages/Dotmim.Sync.Core/0.5.6-beta-0413

**Comment by Mimetis** [comment]
Will close the issue, since no feedback 
If you still have the problem, please let me know, we will reopen the issue
