### ISSUE TITLE
SQL Server UniqueIdentifier to Sqlite BLOB sync issue

### ISSUE THREAD

**Issue by lv1986** [Mimetis/Dotmim.Sync#294]
Hi,
I have used "uniqueidentifier"  datatype in my Main database (SQL Server) for primary keys. When I synced the data it created column as type "BLOB" (SQLite) database. 

My client application is also in c# (Desktop Application), When I am trying to convert stored BLOB data into GUID or vice versa it is throwing errors. 
Did I have missed something? 
Is it correct way to sync "uniqueidentifier" columns to Sqlite?

Here is the error when I am trying to converted BLOB (From Sqlite) to GUID:
![GUID_Issue](https://user-images.githubusercontent.com/66375806/86240289-8eab6900-bbbe-11ea-8af8-52d1eb43cb8a.png)

Data stored in Sqlite datbase is byte[36] length.

**Comment by gb0o** [comment]
You may be using nuget package `Microsoft.Data.Sqlite` version >= 3.0 where `guid` is now stored as text instead of bytes. Unfortunately ~3 times more bytes are required to store a guid as text. It is easier to read but less space efficient and possibly slower than the older binary format.

See https://www.bricelam.net/2019/08/22/microsoft-data-sqlite-3-0.html and search for ```New Guid mapping (breaking change)```

**Comment by Mimetis** [comment]
Hi @lv1986 

The `Microsoft.Data.Sqlite` package has changed the way it's storing GUID.   
Please have a look here: https://www.bricelam.net/2019/08/22/microsoft-data-sqlite-3-0.html 

For instance, here is a small piece of code that is working for me:

``` csharp
var r = await agent.SynchronizeAsync(progress);
// Write results
Console.WriteLine(r);

using (var sqliteConnection = new SqliteConnection(clientProvider.ConnectionString))
{
    using (var command = new SqliteCommand("Select * from Product", sqliteConnection))
    {
        sqliteConnection.Open();
        var reader = command.ExecuteReader();

        while (reader.Read())
        {
            var rowId = reader["rowguid"] != DBNull.Value? new Guid((string)reader["rowguid"]) : Guid.Empty;
        }
        sqliteConnection.Close();

    }
}

```

**Comment by lv1986** [comment]
Hi @Mimetis,

I have created below to methods to convert BLOB stored int Sqlite database to GUID and GUID to Byte[].

```public static Guid ConvertToGUID(byte[] byteData)
{
     string str = Encoding.ASCII.GetString(byteData);
     Guid guid = Guid.Parse(str);
      return guid;
}

public static byte[] GuidToByteArray(string guidData)
{
      return Encoding.ASCII.GetBytes(guidData.ToString());
}
```
I am using first method "ConvertToGUID" to convert bytes[] received from Sqlite database to GUID. I am using this method when to use plain GUID instead of bytes example while bind in dropdowns (Value field).
Second method I am using to convert GUID to bytes when there is a need to store value into database. 

Hope this makes sense. Thanks a lot for your reply.

**Comment by lv1986** [comment]
Hi,
How to properly use GUID as primary key for syncing data, I am getting trouble syncing data when records are created from desktop app which is using SQLite database. 
1.	Here is the screenshot of record from main SQL Server database:
 
![1](https://user-images.githubusercontent.com/66375806/89177239-96d53a80-d5a8-11ea-956b-d9bda84fcbde.png)

2.	Here is the screenshot of Sqlite database after my first Sync: 
 
![2](https://user-images.githubusercontent.com/66375806/89177250-a05ea280-d5a8-11ea-80b7-cb49671fa8a1.png)

3.	But when I add a new record into Sqlite database from my Desktop application it stores data as BLOB: 
 
![3](https://user-images.githubusercontent.com/66375806/89177260-a48ac000-d5a8-11ea-8d20-500ddb02a5be.png)

4.	When I try to sync data again I am getting following error: 
![4](https://user-images.githubusercontent.com/66375806/89177304-c126f800-d5a8-11ea-9e6a-a1265f5a8f63.png)

Do you have any idea about how I can insert GUID into ID column which I can also sync back to my Main SQL Server. I have tried entity frame work and ADO .net in my Desktop application to insert data. 
I have tried following: 
 ![5](https://user-images.githubusercontent.com/66375806/89177311-c71cd900-d5a8-11ea-8f9c-5769e10fd581.png)

Also this: 
![6](https://user-images.githubusercontent.com/66375806/89177330-ce43e700-d5a8-11ea-9c5b-5f96ad6d1475.png)

But same results on both the cases. 

Here is the database sample when I have used custom methods to generate blob and bytes, which I have discussed in my previous threads:
 
![7](https://user-images.githubusercontent.com/66375806/89177350-dbf96c80-d5a8-11ea-8d74-c95ce3bdbd59.png)

It store data like this but when I try to sync it also gave me same error: 
 
![4](https://user-images.githubusercontent.com/66375806/89177359-e156b700-d5a8-11ea-81dd-3c68eb93472c.png)

**Comment by lv1986** [comment]
HI have also tried with example provided by you, https://www.bricelam.net/2019/08/22/microsoft-data-sqlite-3-0.html

```
connection.Open();
SqliteCommand command = connection.CreateCommand();
command.CommandText = @"INSERT INTO OWNERS (Name,IsActive,IsDeleted,CreationTime,Id) VALUES (@Name,@IsActive,@IsDeleted,@CreationTime,@Id)";
Guid _guid = Guid.NewGuid();
command.Parameters.AddWithValue("@Name", "Hello");
command.Parameters.AddWithValue("@IsActive", true);
command.Parameters.AddWithValue("@IsDeleted", false);
command.Parameters.AddWithValue("@CreationTime", DateTime.Now);
command.Parameters.AddWithValue("@Id", _guid).SqliteType = SqliteType.Blob; ;
command.ExecuteNonQuery();
connection.Close();
```

I am successfully able to converted saved value to GUID using this:
```
byte[] aa = medlogicEntities.Owners.FirstOrDefault(a => a.Name == "Hello").Id;
Guid guid = new Guid(aa);
```
But same error occurs when I try to sync data: 
![4](https://user-images.githubusercontent.com/66375806/89256261-583f8e80-d641-11ea-8566-31bd8839574e.png)

**Comment by Mimetis** [comment]
still an issue here ?

**Comment by Mimetis** [comment]
I'm closing since it seems you resolved this issue by yourself :)

**Comment by hims889** [comment]
@Mimetis As I have got no response from your side and no other solution found. I have finally changed my columns from GUID to String in my main SQL Server database and after I performed sync my SQLite columns are created as Text. This is how I resolved/fix this.
