### ISSUE TITLE
Can we change the connectionString?

### ISSUE THREAD

**Issue by dmrnht** [Mimetis/Dotmim.Sync#295]
Can we change the connectionString that we assign in ConfigureServices with HTTP mode with ASP.Net Core Web API in the POST endpoint in SyncController?

**Comment by dmrnht** [comment]
thanks i solved it with; 
orchestrator.Provider.ConnectionString = string.Format(orchestrator.Provider.ConnectionString, client.DatabaseName);

**Comment by Mimetis** [comment]
If you are working with multiple server databases, your best option, in my opinion, is to use `scopes` (https://dotmimsync.readthedocs.io/MultiScopes.html)

Something like:

``` csharp

services.AddSyncServer<SqlSyncProvider>(connectionStringForServer1, "ScopeForServer1", tables);
services.AddSyncServer<SqlSyncProvider>(connectionStringForServer2, "ScopeForServer2", tables);
services.AddSyncServer<SqlSyncProvider>(connectionStringForServer3, "ScopeForServer3", tables);
```

It really depends on your scenario, anyway.
