### ISSUE TITLE
There is already an object named 'Departments_update' in the database.

### ISSUE THREAD

**Issue by dmrnht** [Mimetis/Dotmim.Sync#296]
Dear Sir, When I run my sync codes, I get the following error. Below it you can see the local and server tables and what Dotmim.Sync has added. What is the reason why I got this error?

Do we have the chance to convert it to client-server in the form of server-client in synchronization priority?

What I want to do is synchronization from the client (with console app) database to the server database API. What kind of suggestion can you have in this regard?

**Error**
![Error](https://user-images.githubusercontent.com/46296165/86532554-9c6d3100-bed3-11ea-9259-c9e2d4de1aef.PNG)

**Server Table** 
![ServerTable](https://user-images.githubusercontent.com/46296165/86532552-9bd49a80-bed3-11ea-8870-7f1136a9347c.PNG)

**Local Table**
![LocalTable](https://user-images.githubusercontent.com/46296165/86532553-9c6d3100-bed3-11ea-8bf5-4c2e98585c46.PNG)

**Comment by Mimetis** [comment]
`DMS` tries to create triggers, but it seems you already have some existing triggers with the same name
Check the doc : https://dotmimsync.readthedocs.io/Configuration.html
Try to use `SyncSetup` and set the properties `TriggersPrefix` or (and) `TriggersSuffix `.

example

``` csharp
    var setup = new SyncSetup(tables)
    {
        StoredProceduresPrefix = "s",
        StoredProceduresSuffix = "",
        TrackingTablesPrefix = "t",
        TrackingTablesSuffix = "",
        TriggersPrefix = "",
        TriggersSuffix = "t"
    };
```
