### ISSUE TITLE
Column sync_scope_name of type nvarchar error

### ISSUE THREAD

**Issue by darenwai** [Mimetis/Dotmim.Sync#298]
I download your web api sample. Currently xamarin.android sync with the web api scope A, Database A at Server A.
I then setup server B which uses SqlSyncChangeTrackingProvider to sync with Server A Database A.
The idea is to duplicate Database A so that if Server A is down. Xamarin.android could sync with server B Database A without much effort.

At Server B. I encounter this error. Does this mean current dotmim doesn't support duplicate database A which is already in sync?

Dotmim.Sync.SyncException: The Column sync_scope_name of type nvarchar from provider SqlSyncProvider,
DotmimSync.SqlServer.SqlSyncProvider is not currently supported

**Comment by Mimetis** [comment]
I've never tested this scenario.
I'm not sure it's possible to be honest.

Maybe, you should provision the server B manually before trying a sync, just to see if it could work

**Comment by darenwai** [comment]
Hi. Actually i am trying to fully duplicate the database so that if server A down. Then i still have the database. If re-provision is required, then i am sure it will work. So i guess the simplest way is, if server A down, copy server A database to server B and continue syncing. Thank you.

**Comment by darenwai** [comment]
Actually using SqlSyncChangeTrackingProvider to sync with Server A Database A. I sync using Scope B. It works except it doesnt allow to sync the scope table due type nvarchar type not supported. All other table sync perfectly. At first i thought if you allow to sync the scope table also. The whole database will be fully duplicated. But if is not this simple. Then no need. Thank you.
