### ISSUE TITLE
Azure sql db - can you use TCP and not HTTP

### ISSUE THREAD

**Issue by cognociente** [Mimetis/Dotmim.Sync#299]
My hub server dB will be in the cloud and I want to avoid the complexities that seem to arise with an http endpoint. Would it be possible to treat the azure sql dB as a tcp connection to the sync agent?

**Comment by Mimetis** [comment]
Yes, of course, but it's not a good idea, from a security perspectives :)

Be sure your server database is reachable from anywhere (firewall, user rights, tcp connection and so on ...) and use a correct connection string and it should work as is

**Comment by cognociente** [comment]
Thanks for the quick reply. My networking knowledge is limited - why is it not a good idea?

**Comment by Mimetis** [comment]
Make a quick search on internet about exposing a database over the internet, you should find a lot of answers
