### ISSUE TITLE
Column is null exception when using filters on table with filtered columns

### ISSUE THREAD

**Issue by VA-01** [Mimetis/Dotmim.Sync#302]
Great project! 

Sync throws a SyncException "Column is null" when I attempt to sync a table that has filtered set of columns and then specify a filter with a join and where clause. 
- Specifying all the columns does not fix the issue
- Works perfectly if I do not specify columns

Thanks

**Comment by Mimetis** [comment]
can you share a sample to be able to reproduce ?

**Comment by VA-01** [comment]
`//web api SyncController`
` var setupOptions = new SyncSetup(new HashSet<string>{"Definitions", "Products"});
setupOptions.Tables["Definitions"].Columns.AddRange(new[] {"ID", "[Name]", "CreatorId"});

var pdFilter = new SetupFilter("Definitions");
pdFilter.AddParameter(P_USER_ID, DbType.Int32);
pdFilter.AddJoin(Join.Left, "Products").On("Products", "ProductionDefinitionId", "Definitions", "ID");
pdFilter.AddWhere("CreatorId", "Products", P_USER_ID);
setupOptions.Filters.Add(pdFilter);`

**Comment by Mimetis** [comment]
Man, it's not enough to help you figure out what's ur problem

**Comment by VA-01** [comment]
I'm very sorry. Was testing provisioning then set BatchSize which made it call ProvisionAsync for each batch and confused everything. It works perfectly.
