### ISSUE TITLE
Dotmim.Sync.SyncException: 'Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by VIAINFO** [Mimetis/Dotmim.Sync#303]
I work with VS 2019 with Xamarin
I would like to know if there is an example built for xamarin, and where can I download it?

I thank you in advance for your help, and my current code is as follows:

 async void Sincronizar_Clicked(object sender, EventArgs e)
        {

             //crear la base si no existe

            SqlSyncProvider serverProvider = new SqlSyncProvider(@"Data Source =viasvr001.donweb-homeip.net; initial catalog =AdventureWorks; user id =ViaSoftware; password =A?mOKw0MSomK;");
             Boolean sw = false;

            string databaseFileName = System.IO.Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal), "advworks.db");
            if (databaseFileName != null)
            {
                sw = true;
            }

            SqliteSyncProvider clientProvider = new SqliteSyncProvider(databaseFileName);

            // Tables involved in the sync process:
            var tables = new string[] {"ProductCategory",
            "ProductDescription", "ProductModel",
            "Product", "ProductModelProductDescription",
            "Address", "Customer", "CustomerAddress",
            "SalesOrderHeader", "SalesOrderDetail" };

            // Sync orchestrator
            SyncAgent agent = new SyncAgent(clientProvider, serverProvider, tables);

            //await agent.SynchronizeAsync();

            var syncContext = await agent.SynchronizeAsync();

            do
            {
                var s = await agent.SynchronizeAsync();
                Console.WriteLine($"Total Changes downloaded : {s.TotalChangesDownloaded}");

            } while (Console.ReadKey().Key != ConsoleKey.Escape);

        }

**Comment by Mimetis** [comment]
I need more info to help you

**Comment by akema-trebla** [comment]
`Console.ReadKey()` may not be supported. 

Use another condition to break your loop.

**Comment by elkanahomonitan** [comment]
Please help, I have the same issue using MS SQL Server  as server and MySQL as client after running sync below is the error am getting.

Dotmim.Sync.SyncException: 'Object cannot be cast from DBNull to other types.'

exception was originally thrown at this call stack:
    System.DBNull.System.IConvertible.ToInt64(System.IFormatProvider)
    System.Convert.ToInt64(object)
    Dotmim.Sync.MySql.MySqlScopeInfoBuilder.GetLocalTimestampAsync(System.Data.Common.DbConnection, System.Data.Common.DbTransaction)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()
    Dotmim.Sync.CoreProvider.GetLocalTimestampAsync(Dotmim.Sync.SyncContext, System.Data.Common.DbConnection, System.Data.Common.DbTransaction, System.Threading.CancellationToken, System.IProgress<Dotmim.Sync.ProgressArgs>)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    ...
    [Call Stack Truncated]


I we await your swift response.

**Comment by Mimetis** [comment]
You are using a type in MySql that is not compatible
Can you share with me your sql & mysql table schema *?

**Comment by elkanahomonitan** [comment]
![MSSqlTableSchema](https://user-images.githubusercontent.com/32774117/92093410-3ade1b80-edcb-11ea-92d3-bb419f60c8de.PNG)
![MySqlTableSchema](https://user-images.githubusercontent.com/32774117/92093432-416c9300-edcb-11ea-9113-913d3ea62115.PNG)

Below is the SQL Server Schema and MySql Schema

**Comment by Mimetis** [comment]
I've tried with your schema an it s working fine
what is you mysql version ?

**Comment by Mimetis** [comment]
by the way using sql server or mysql directly from a xamarin application is not allowed
