### ISSUE TITLE
SQL Server problems with  Dotmim.Sync.SqlServer 0.5.6 nuget package

### ISSUE THREAD

**Issue by luc-cap** [Mimetis/Dotmim.Sync#305]
Hi,
   I have used SyncFramework for years,
Complements for a framework like .DOTMIM ! 
                                                            
I have implemented remote database synchronization

ENVIROMENT:

SO: Win10 1909
Client: .NET Framework 4.8
Server: ASP.NET Core Application based on .NET Core 2.2
         (developed as NopCommerce 4.20 Plugin).

VISUAL STUDIO 2019: version 16.6.2

DB Server: SQL Server 2017
           hosted as Docker Container on latest Docker for windows ( 2.3.0.4 )
           

Unfortunately I have problems with the assembly the NuGET 0.5.6 version

Especially with the assembly: Microsoft.Data.SqlClient 1.1.1
used by Dotmim.Sync.SqlServer.dll,
Perhaps because the specific version of the assembly is marked ? ! ?.

I resolved ONLY adding the projects to my solution :
        - Dotmim.Sync.Core
        - Dotmim.Sync.SqlServer
        - Dotmim.Sync.SqlServer.ChangeTracking
        - Dotmim.Sync.Web.Client
        - Dotmim.Sync.Web.Server
My project start working in production on a WINDOWS Server 2017
ONLY replacing System.Data.SqlClient (version 4.8.1)
in Dotmim.Sync.SqlServer and resolving error raised during compilation.
 
 I don't know what that means in terms of compatibility, but ...
 
 May you release a new NuGET version
 compiled with System.Data.SqlClient (version 4.8.1)?
 
 have a nice day.

**Comment by Mimetis** [comment]
`Microsoft.Data.SqlClient` is the newest package to use, in place of `System.Data.SqlClient`
- https://github.com/dotnet/SqlClient
- https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/
- https://www.connectionstrings.com/the-new-microsoft-data-sqlclient-explained/

Regarding your setup, I don't see the problem
Do you have a sample repro to share ?

**Comment by mangireesh** [comment]
Hi,

I am developing a xamarin.forms application, in which i am using Dotmim.Sync for syncing my local sqlite database with SQL server database.

I have installed 'Dotmim.Sync.Sqlite' and 'Dotmim.Sync.SqlServer' via nuget in my xamarin forms project(all project).

The xamarin.uwp is working fine. but when I am running 'android', I am getting an error as follows while executing the line

var result = await agent.SynchronizeAsync();

Dotmim.Sync.SyncException: Microsoft.Data.SqlClient is not supported on this platform.

**Comment by Mimetis** [comment]
hi @mangireesh 
You can't use a direct connection to your server side, from within an android / ios application
It's not possible AND it's a major security issue, since you would have to expose your server database to the internet

Your best bet is to use the ASP.Net core Proxy mode : https://dotmimsync.readthedocs.io/Web.html

**Comment by mangireesh** [comment]
> 
> 
> hi @mangireesh
> You can't use a direct connection to your server side, from within an android / ios application
> It's not possible AND it's a major security issue, since you would have to expose your server database to the internet
> 
> Your best bet is to use the ASP.Net core Proxy mode : https://dotmimsync.readthedocs.io/Web.html

Thanks for your reply. I will try with ASP.Net core.
