### ISSUE TITLE
Multiple clients access to different db parts

### ISSUE THREAD

**Issue by vunder** [Mimetis/Dotmim.Sync#307]
Is it possible to organice structure, when I have single web-server with multiple clients. Database structure (business model) is the same for all clients. Each client has it's unique name. While sync with server clien get's changes related to its identifier only. I'm searching for something as replacenet for Azure Mobile Services

**Comment by Mimetis** [comment]
You can filter any table based on a parameter
Check https://dotmimsync.readthedocs.io/Filters.html

**Comment by vunder** [comment]
I'm using UWP sample sync (HTTP mode)
I've added to server
```csharp
            var filter = new SetupFilter("Employee");
            filter.AddParameter("foo", DbType.String, true);
            filter.AddWhere("Comments", "Employee", "foo");
```
On client I've added
```csharp
var agent = new SyncAgent(new SqlSyncProvider(connectionString), new WebClientOrchestrator(serverAddress), new[]{"Employee"});
agent.Parameters.Add("foo", "112");
```

Manually I'm adding new record on server with numm Comments value. Synching data and getting this row on the client. I thought I should not get it since I have filter for it

**Comment by Mimetis** [comment]
the clause that will be generated for you filter is something like this;

``` sql
WHERE (
(
   ([Employee].[Comments] = @foo )
)
```

so all all the comments that have foo == 112 will be downloaded

**Comment by vunder** [comment]
It's either a bug or I did something wrong.
There is no such condition in server queries (I've checked that via SQL Profiler)

**Comment by vunder** [comment]
My mistake. I forgot to add new filter to `SyncSetup`

**Comment by Mimetis** [comment]
The doc is a little bit old on the filter part.
I should update it and make a proper sample

**Comment by vunder** [comment]
To implement logic mentioned above on service side each table has `UserId` column. The idea is to fill it with some unique value after authentication. Each client has its own database with the same structure, except the fact that there is no `UserId` column in tables.
However, it is impossible to sync. To add filter for `UserId` column on server side, this column must be added in the list of columns in `SyncSetup.Tables`. But this creates wrong schema on client side in `scope_info` table by adding `UserId` column in the list of columns. Which eventually fails during sync because trying to add `UserId` column in select query while getting changes

**Comment by Mimetis** [comment]
The schema should be the same between server and client, so yes, your `UserId` should be part of the schema.

Did you tried with an empty new client database ?

**Comment by vunder** [comment]
> Did you tried with an empty new client database ?

Mostly it is not possible since I'm adding sync to existing client database

**Comment by vunder** [comment]
Then anyway filter does not solve feature with different client access. Since `UserId` have to be filled with correct value after sing-in.
Possible workaround - use custom converter. On client side `UserId` colunm would always `NULL` but the value would be filled in `IConverter.BeforeSerialize`

**Comment by Mimetis** [comment]
> > Did you tried with an empty new client database ?
> 
> Mostly it is not possible since I'm adding sync to existing client database

The `DMS` framework is meant to be used with the same schema on both side.

I did not made any test with different schemas on server and on client.
I guess It could work if you're handling it manually, using the different interceptors
Let us know if you find a correct solution.

I guess you can add the `UserId` filter and manually edit the `SyncSetup` to *remove* the filter.
Not sure, but worth a try

**Comment by vunder** [comment]
> I guess you can add the `UserId` filter and manually edit the `SyncSetup` to _remove_ the filter.

I did not understand what do you mean

My local experiment. I've created two converters for server and client. Server's one does do nothing, just dummy. Client's converter adds necessary value for UserId in `BeforeSerialize` and set it to null in `AfterSerialized` to keep `NULL` value for this column in database (it helps not to tight database data to any specific account that user will use to login to server, i.e. UserId value)
Also, there are `UserId` filters for all tables and client also defines userId parameter value to apply filters.
Another thing that I've found is a problem with converters. In doc there is no information that `Key` have to be in lower-case.
https://github.com/Mimetis/Dotmim.Sync/blob/4ab0ed3f02f5875b0d3cbae7bfca75985767f1fc/Projects/Dotmim.Sync.Web.Server/WebServerOrchestrator.cs#L275
IMHO it should be
```csharp
                var clientConverter = serverOrchestrator.WebServerOptions.Converters.First(c => c.Key.ToLowerInvariant() == cs);
```
That would give more flexibility for developers
