### ISSUE TITLE
How does the WebClientOrchestrator know which scope schema to get when there's multiple schemas?

### ISSUE THREAD

**Issue by captmomo** [Mimetis/Dotmim.Sync#308]
`                

                WebClientOrchestrator proxyClientProvider = new WebClientOrchestrator(endPoint);
    
                SyncSet newSchema = await _serverOrchestrator.GetSchemaAsync();`

How does the WebClientOrchestrator know which scope schema to get when there's multiple schemas?

**Comment by Mimetis** [comment]
I don't get your question.
The scope represents a schema
the client should know the scope he need to sync, otherwise there is a problem in your architecture

**Comment by captmomo** [comment]
> I don't get your question.
> The scope represents a schema
> the client should know the scope he need to sync, otherwise there is a problem in your architecture

I have two server schemas on my web proxy server:

```
            services.AddSyncServer<SqlSyncChangeTrackingProvider>(customerConnectionString, "customer", customerSyncSetup);
            services.AddSyncServer<SqlSyncChangeTrackingProvider>(productConnectionString, "products", productsSyncSetup);
```

in the provisioning/deprovisioning example:
```
// Provision the Address triggers / stored proc again,
// This provision method will fetch the address schema from the database,
// so it will contains all the columns, including the new one added
await localOrchestrator.ProvisionAsync(SyncProvision.StoredProcedures | SyncProvision.Triggers);

// Now we need to save this to clientscope
// get the server scope again
var clientScope = await localOrchestrator.GetClientScopeAsync();

\
// At this point, if you need the schema and you are not able to create a RemoteOrchestrator,
// You can create a WebClientOrchestrator and get the schema as well
var proxyClientProvider = new WebClientOrchestrator("https://localhost:44369/api/Sync");
 var newSchema = proxyClientProvider.GetSchemaAsync();

// affect good values
clientScope.Setup = setup;
clientScope.Schema = newSchema;
```

how do I pass the schema to the webClientOchestrator?

**Comment by Mimetis** [comment]
You can pass the scope name on the constructor

**Comment by captmomo** [comment]
> You can pass the scope name on the constructor

![image](https://user-images.githubusercontent.com/25576022/90552234-12e49a80-e1c5-11ea-840d-d7553a379523.png)
sorry which parameter?

**Comment by Mimetis** [comment]
The scope name propagation is handled by the `SyncAgent` instance.
Here is a straightforward example:

``` cs
var clientProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(clientDbName));
var proxyClientOrchestrator = new WebClientOrchestrator("https://localhost:44369/api/Sync");

var agent = new SyncAgent(clientProvider, proxyClientProvider, "Products");

Console.WriteLine(agent.LocalOrchestrator.ScopeName);

// these 2 lines are completely equivalent, since proxy orchestrator IS the remote orchestrator
Console.WriteLine(agent.RemoteOrchestrator.ScopeName);
Console.WriteLine(proxyClientOrchestrator.ScopeName);

```

**Comment by captmomo** [comment]
Thank you, that was what I ended up doing in the end.
