### ISSUE TITLE
[Bug] Changing same field on two slaves results in different data (reopened)

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#31]
Hello Sebastien,
I have recorded a sample video to demonstrate the problem. In this video i use 3 MSSQL databases (DotminXAF as master and DotminXAF1, DotminXAF2 as slaves).
First I start the webserver of your samples that is slightly modified and then the client console, that syncs both slaves.
Now at first attempt the sync works fine, but when I modify the same field on both slaves, changes of first slave are synced to master, but second slave does not get the changes! Check out the video please.

[SyncBug.zip](https://github.com/Mimetis/Dotmim.Sync/files/1524626/SyncBug.zip)

**Comment by Mimetis** [comment]
Ok, will look at this...  
Can you share with a copy of your database, and your console app ?

**Comment by thefonzi** [comment]
[Dotmim.Sync.SampleConsole.zip](https://github.com/Mimetis/Dotmim.Sync/files/1524823/Dotmim.Sync.SampleConsole.zip)
[UWPSyncSampleWebServer.zip](https://github.com/Mimetis/Dotmim.Sync/files/1524824/UWPSyncSampleWebServer.zip)
[DotminXAF.zip](https://github.com/Mimetis/Dotmim.Sync/files/1524825/DotminXAF.zip)

**Comment by Mimetis** [comment]
I think I have found the bug.
Let me some times to make more tests and I will make an update as soon as possible.
Thx !

**Comment by Mimetis** [comment]
Can you make a test with the last version I just pushed on the master branch ?
Thx !

**Comment by thefonzi** [comment]
I have done a bunch of tests and everything works fine now.
Thanks

**Comment by Mimetis** [comment]
NICE !!!!!
Thx you so much to make so many tests, helping me to debuging dotmim.sync :)
