### ISSUE TITLE
OutOfDateException: Client database is out of date. Last client sync timestamp:0. Last server cleanup metadata:550 Try to make a Reinitialize sync.

### ISSUE THREAD

**Issue by captmomo** [Mimetis/Dotmim.Sync#310]
```
OutOfDateException: Client database is out of date. Last client sync timestamp:0. Last server cleanup metadata:550 Try to make a Reinitialize sync.
```

this is a fresh SQLite client database. I am testing the sync process.
I'm using a `SqlSyncChangeTrackingProvider` for the server side.
On the first sync, it throws this error.
My current workaround i:

```
           agent.LocalOrchestrator.OnOutdated(outdated =>
            {
               outdated.Action = OutdatedAction.Reinitialize;
            });
```

But I'm puzzled as why an updated client db is consider "outdated".

Sorry for all the questions!

**Comment by captmomo** [comment]
`sync_scope_id	sync_scope_name	scope_last_sync_timestamp	scope_last_sync_duration	scope_last_sync
D267DD08-45BC-44E6-AF60-BE201E3D6AD8	Ueios	550	14583036730	2020-08-19 17:41:11.760
69513B1D-92F7-481D-9A11-984A3B577ACB	Ueios	550	10102736664	2020-08-19 17:33:43.730
A09A6E52-AF78-4939-81BE-7A5A61A6730E	Ueios	550	4921803590	2020-08-19 17:25:05.637
4CD65C0C-8F01-4056-B9BE-0EB3FC80FD63	Ueios	550	193477927	2020-08-19 17:17:12.807
A6CE4365-B059-48C6-84C4-166431D3E1B7	Ueios	550	240323405	2020-08-19 16:48:07.230
71302FAF-E337-47AA-84ED-69024197A8C7	Ueios	550	218636868	2020-08-19 15:33:09.507
F1C7001D-9D68-4BEF-8B83-DDE6137E06DF	Ueios	550	15744558918	2020-08-19 14:38:36.187
D172169D-D240-4544-9BA7-85CB9EBE38AB	Ueios	550	13366466049	2020-08-19 14:34:38.377
DD426BB3-4384-4334-999A-7D4494C37A72	Ueios	550	8021371025	2020-08-19 14:22:06.873
D6F9BD0E-17D1-4414-B39C-0A474A71CFF1	Ueios	544	19395334788	2020-08-19 10:04:58.077
D941E4D4-2927-4038-AF50-4FE8DEE03A3B	Ueios	544	5823447711	2020-08-19 09:42:20.887
E24ACF5F-BA26-4958-99B8-A7F19DC12CBD	Ueios	544	302632416	2020-08-19 09:37:19.460
1B1878F5-CDFC-4B26-909E-848975C3D0CF	Ueios	544	187855685	2020-08-19 09:32:57.330
B4785232-EA1D-4698-9A4F-9CFA74E22044	Ueios	461	33004758724	2020-08-19 02:29:53.463
62F83F78-7746-4AE3-9444-7657BAD9D8E4	Ueios	449	29527675004	2020-08-19 02:24:05.753
4A9E5AE6-C25F-4549-8FCD-2B54F2B4D493	Ueios	449	28032734251	2020-08-19 02:21:36.260
2C599365-CE6D-419E-8B27-87B7FBDCC77D	Ueios	449	27352244951	2020-08-19 02:20:28.210
79E09CE2-86E5-412B-817E-ABCC22425C6F	Ueios	449	16908326773	2020-08-19 02:03:03.820
A8A691B6-2872-45B5-962A-3C3674937048	Ueios	380	45907891	2020-08-18 19:43:08.663
B7514FF7-37FA-4648-8447-1B318335FE68	Ueios	380	7920870720	2020-08-18 19:33:54.903
1B200BBB-51A9-4656-8DF5-009FE9054D33	Ueios	365	19742024589	2020-08-18 18:51:12.973
34D2B455-BB61-431D-9EAC-3C745E587278	Ueios	365	8733620500	2020-08-18 18:32:52.133
76856D08-AE35-4526-B1CF-B9CC9A21DF85	Ueios	353	1678117782	2020-08-18 18:21:06.580
C5C7A7F0-5610-4247-AB4A-79F4B30E6C8A	Ueios	297	2831533410	2020-08-18 10:55:44.610
A5B9EE05-EB2D-4D61-9FAD-A568DC5C13B0	Ueios	289	886587156	2020-08-18 10:07:36.770
7C6DF90F-04A6-4F04-B072-041F83CF61CD	Ueios	69	343343407	2020-08-18 07:49:53.830`

**Comment by captmomo** [comment]
|   | sync_scope_id                        | sync_scope_name | scope_last_sync_timestamp | scope_last_sync_duration | scope_last_sync         |
|---|--------------------------------------|-----------------|---------------------------|--------------------------|-------------------------|
|   | D267DD08-45BC-44E6-AF60-BE201E3D6AD8 | Ueios           | 550                       | 14583036730              | 2020-08-19 17:41:11.760 |
|   | 69513B1D-92F7-481D-9A11-984A3B577ACB | Ueios           | 550                       | 10102736664              | 2020-08-19 17:33:43.730 |
|   | A09A6E52-AF78-4939-81BE-7A5A61A6730E | Ueios           | 550                       | 4921803590               | 2020-08-19 17:25:05.637 |
|   | 4CD65C0C-8F01-4056-B9BE-0EB3FC80FD63 | Ueios           | 550                       | 193477927                | 2020-08-19 17:17:12.807 |
|   | A6CE4365-B059-48C6-84C4-166431D3E1B7 | Ueios           | 550                       | 240323405                | 2020-08-19 16:48:07.230 |
|   | 71302FAF-E337-47AA-84ED-69024197A8C7 | Ueios           | 550                       | 218636868                | 2020-08-19 15:33:09.507 |
|   | F1C7001D-9D68-4BEF-8B83-DDE6137E06DF | Ueios           | 550                       | 15744558918              | 2020-08-19 14:38:36.187 |
|   | D172169D-D240-4544-9BA7-85CB9EBE38AB | Ueios           | 550                       | 13366466049              | 2020-08-19 14:34:38.377 |
|   | DD426BB3-4384-4334-999A-7D4494C37A72 | Ueios           | 550                       | 8021371025               | 2020-08-19 14:22:06.873 |
|   | D6F9BD0E-17D1-4414-B39C-0A474A71CFF1 | Ueios           | 544                       | 19395334788              | 2020-08-19 10:04:58.077 |
|   | D941E4D4-2927-4038-AF50-4FE8DEE03A3B | Ueios           | 544                       | 5823447711               | 2020-08-19 09:42:20.887 |
|   | E24ACF5F-BA26-4958-99B8-A7F19DC12CBD | Ueios           | 544                       | 302632416                | 2020-08-19 09:37:19.460 |
|   | 1B1878F5-CDFC-4B26-909E-848975C3D0CF | Ueios           | 544                       | 187855685                | 2020-08-19 09:32:57.330 |
|   | B4785232-EA1D-4698-9A4F-9CFA74E22044 | Ueios           | 461                       | 33004758724              | 2020-08-19 02:29:53.463 |
|   | 62F83F78-7746-4AE3-9444-7657BAD9D8E4 | Ueios           | 449                       | 29527675004              | 2020-08-19 02:24:05.753 |
|   | 4A9E5AE6-C25F-4549-8FCD-2B54F2B4D493 | Ueios           | 449                       | 28032734251              | 2020-08-19 02:21:36.260 |
|   | 2C599365-CE6D-419E-8B27-87B7FBDCC77D | Ueios           | 449                       | 27352244951              | 2020-08-19 02:20:28.210 |
|   | 79E09CE2-86E5-412B-817E-ABCC22425C6F | Ueios           | 449                       | 16908326773              | 2020-08-19 02:03:03.820 |
|   | A8A691B6-2872-45B5-962A-3C3674937048 | Ueios           | 380                       | 45907891                 | 2020-08-18 19:43:08.663 |
|   | B7514FF7-37FA-4648-8447-1B318335FE68 | Ueios           | 380                       | 7920870720               | 2020-08-18 19:33:54.903 |
|   | 1B200BBB-51A9-4656-8DF5-009FE9054D33 | Ueios           | 365                       | 19742024589              | 2020-08-18 18:51:12.973 |
|   | 34D2B455-BB61-431D-9EAC-3C745E587278 | Ueios           | 365                       | 8733620500               | 2020-08-18 18:32:52.133 |
|   | 76856D08-AE35-4526-B1CF-B9CC9A21DF85 | Ueios           | 353                       | 1678117782               | 2020-08-18 18:21:06.580 |
|   | C5C7A7F0-5610-4247-AB4A-79F4B30E6C8A | Ueios           | 297                       | 2831533410               | 2020-08-18 10:55:44.610 |
|   | A5B9EE05-EB2D-4D61-9FAD-A568DC5C13B0 | Ueios           | 289                       | 886587156                | 2020-08-18 10:07:36.770 |
|   | 7C6DF90F-04A6-4F04-B072-041F83CF61CD | Ueios           | 69                        | 343343407                | 2020-08-18 07:49:53.830 |

**Comment by Mimetis** [comment]
On Sqlite, as a client you should have only one scope.
I assume The others are from previous tests ?

Out of Date occurs when your last sync is older than the last cleanup metadata on the server
You should check the values from the client and the server

**Comment by captmomo** [comment]
> On Sqlite, as a client you should have only one scope.
> I assume The others are from previous tests ?
> 
> Out of Date occurs when your last sync is older than the last cleanup metadata on the server
> You should check the values from the client and the server

This is how I tested:

1. Delete the sqlite db.
2. Run the sync
3. This error occurs.

The table I shared above is from the Server side, not the client.

**Comment by Mimetis** [comment]
Ok, I ll check.
Seems we have a problem here with the `SqlSyncChangeTrackingProvider`.
