### ISSUE TITLE
Existing tables are not syncing over HTTP

### ISSUE THREAD

**Issue by vunder** [Mimetis/Dotmim.Sync#312]
There is a client with existing SQLite database.
```csharp
            var serverOrchestrator = new WebClientOrchestrator("https://localhost:5001/api/sync");
            // Second provider is using plain old Sql Server provider,
            // relying on triggers and tracking tables to create the sync environment
            var builder = new SqliteConnectionStringBuilder { DataSource = "my_db.sqlite" };
            var clientProvider = new SqliteSyncProvider(builder);

            // Creating an agent that will handle all the process
            var syncSetup = new SyncSetup(new[] { "NewTable" });
            var agent = new SyncAgent(clientProvider, serverOrchestrator, new SyncOptions(), syncSetup);

            var s1 = await agent.SynchronizeAsync();
```
Client tale was following structure
```sql
CREATE TABLE "NewTable"(`ReceiverID` INTEGER PRIMARY KEY ASC autoincrement NOT NULL ,`Name` TEXT NOT NULL ,`Description` TEXT NULL , `SyncId` TEXT NOT NULL DEFAULT(0))
```

Server was just created with the save database structure but without data
```csharp
            var connectionString = Configuration.GetSection("ConnectionStrings")["DefaultConnection"];
            var tables = new[] { "NewTable" };
            var syncSetup = new SyncSetup(tables);
            syncSetup.Tables["NewTable"].Columns.AddRange(new[] { "ReceiverID", "Name", "Description", "SyncID" });
            services.AddSyncServer<SqlSyncProvider>(connectionString, syncSetup, null, new WebServerOptions());
```
Server table
```sql
CREATE TABLE [dbo].[NewTabe](
	[ReceiverID] [int] NOT NULL,
	[Name] [nvarchar](max) NULL,
	[Description] [nvarchar](max) NOT NULL,
	[SyncId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Receiver] PRIMARY KEY CLUSTERED 
(
	[SyncId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

Hovewer sync does not bring anything. Adding new rows to `NewTable` on the client affect sync: new data are sending to server and vice versa.But the problem is exactly with initial sync data to server.
I've tried changing sync direction for the table to `UploadOnly` - did not affect

**Comment by Mimetis** [comment]
Can you try this method (not yet documented) `UpdateUntrackedRowsAsync()` on the `LocalOrchestrator`.

https://github.com/Mimetis/Dotmim.Sync/blob/72da7c8ac51935330662ee98d95e7a7a4c03c400/Projects/Dotmim.Sync.Core/Orchestrators/LocalOrchestrator.cs#L664

``` cs
// Make a first sync to get the schema from server, provision all tracking tables , 
// stored procedures, triggers and so on...
var s = await agent.SynchronizeAsync();

// Here, we should not have any uploaded rows, since it's the first sync.
// But, eventually we have all the rows from server.
Console.WriteLine(s);

// Get local schema
var schema = await agent.LocalOrchestrator.GetSchemaAsync();

// Update all rows on the client side that does not have any tracking rows
await agent.LocalOrchestrator.UpdateUntrackedRowsAsync(schema);

// Make as second sync.
// All local rows that were existing before first sync happened, will be uploaded correctly
s = await agent.SynchronizeAsync();
```

**Comment by vunder** [comment]
It looks it will help. However, in my case there is still a problem.
For easier migration I've just added new column `Guid SyncId`. All other field remain the same. This means that PK is still INTEGER and calling `UpdateUntrackedRowsAsync` cause an exception that column `ID` was not found in `Table_tracking`

**Comment by vunder** [comment]
```cshart
                foreach (var t in schema.Tables)
                {
                    t.PrimaryKeys.Clear();
                    t.PrimaryKeys.Add("SyncId");
                }
```
But this made code works

**Comment by Mimetis** [comment]
> It looks it will help. However, in my case there is still a problem.
> For easier migration I've just added new column `Guid SyncId`. All other field remain the same. This means that PK is still INTEGER and calling `UpdateUntrackedRowsAsync` cause an exception that column `ID` was not found in `Table_tracking`

So You have a problem.
Seems you `Setup` object (stored in the database) is not correct.

Seems to me that you have a `Setup` table with a primary key THAT IS not the good one.

Your last code is correct, seems you're adding the correct primary key.
Be sure to save your schema in both server and client.

Since you seems to have resolve your issue, I will close it.
Do not hesitate to ask for re-open if your issue is still there!
