### ISSUE TITLE
Setup is reset ?

### ISSUE THREAD

**Issue by captmomo** [Mimetis/Dotmim.Sync#313]
Hi,
I'm trying to set up the following:

1. Call a WebApi to generate a SQLite file using the web proxy method.

https://recordit.co/oOm3urQmvB

However I noticed that the setup is reset? I'm not really sure how to describe it, so I've attached a video.

Afterwards, all subsequent calls will produce this error:

```
Dotmim.Sync.SyncException: Your setup does not contains any table.
```
Either that or if the setup has prefixes for stored procedures, it doesn't look for the correct stored procedure..
for example my setup has the prefix `f_`, but it throws this execeptions

`Dotmim.Sync.SyncException: Could not find stored procedure 'dbo.BATCH_RUN__initialize'.`

However it is present in the setup in my server, and I've added it in startup:
![image](https://user-images.githubusercontent.com/25576022/90980444-0201a380-e58e-11ea-9849-35d5a6725a78.png)
![image](https://user-images.githubusercontent.com/25576022/90980852-602f8600-e590-11ea-9867-57ed13c0e8d7.png)

`services.AddSyncServer<SqlSyncChangeTrackingProvider>(ueiosConnectionString, "FilteredBatchRun", filteredBatchRunSetup, options: _ueiosOptions);`
![image](https://user-images.githubusercontent.com/25576022/90980892-9a992300-e590-11ea-8bf0-ec0a05a257a8.png)

**Comment by captmomo** [comment]
Sure, will try to do one tomorrow. for now I'm doing this:

```
        internal async Task<bool> CreateSqliteDatabaseAsync(List<string> scopes, string databaseFileName, string clientId)
        {
            string tempSqliteStorage = _filePathProvider.GetSQLiteFilePath(clientId, databaseFileName);
            // Second provider is using plain old Sql Server provider,
            // relying on triggers and tracking tables to create the sync environment
            SqliteSyncProvider clientProvider = new SqliteSyncProvider(tempSqliteStorage);
            foreach (string scope in scopes)
            {
                WebServerOrchestrator serverProvider = _webServerManager.GetOrchestrator(scope);
                SqlSyncChangeTrackingProvider provider = new SqlSyncChangeTrackingProvider(serverProvider.Provider.ConnectionString);
                using (SyncAgent agent = new SyncAgent(clientProvider, provider, serverProvider.Options, serverProvider.Setup, scope))
                {

                    agent.LocalOrchestrator.OnOutdated(outdated =>
                    {
                        outdated.Action = OutdatedAction.Reinitialize;
                    });

                // Launch the sync process
                SyncResult s1 = await agent.SynchronizeAsync();
                _logger.LogInformation("{Client} : {scope} : {@results}", clientId, scope, s1);

                }
            }
            return true;
        }
```

**Comment by Mimetis** [comment]
Ok, I get it

The `WebServerOrchestrator` is not meant to be used with a `SyncAgent`.
This object is only used by **ASP.NET Core** backend.

When you want to make a synchronization, you are using a `SyncAgent` with 
- A `RemoteOrchestrator` when you are running locally
- A `WebClientOrchestrator` when you are running over http

I don't understand your use case, why do you need to use a `SyncAgent` from you web api ?

**Comment by captmomo** [comment]
I see.

We tried to sync the normal way using a web proxy, the sync for certain
scopes take around 8-10mins and usually fails for xamarin apps, usually
during the applying changes phase.
However, once it is synced, subsequent syncs are fine.

Now we are exploring for the initial sync to have the client databases
created on the server and sent to the clients.

**Comment by Mimetis** [comment]
Did you tried to use Snapshot?

**Comment by captmomo** [comment]
Yes. It doesn’t help as the data is sent over. The issue is on the client
side, when writing the data to the SQLite.

**Comment by Mimetis** [comment]
Strange
Can i do something to help you figure it out ?

**Comment by captmomo** [comment]
No it’s fine honestly. You’ve been most helpful with all my questions. I
suspect it’s the number of rows or xamarin platform.

Thanks again and sorry to be a bother.

**Comment by Mimetis** [comment]
Closing the issue, let me know if we need to re-open it
