### ISSUE TITLE
A SqlParameter with ParameterName '@changeTable' is not contained by this SqlParameterCollection.

### ISSUE THREAD

**Issue by kmkmehra** [Mimetis/Dotmim.Sync#318]
Hello having issue while syncing
A SqlParameter with ParameterName '@changeTable' is not contained by this SqlParameterCollection.

**Comment by Mimetis** [comment]
Need more info to help you

**Comment by akema-trebla** [comment]
Having this same issue now.

When I had no filters setup, I did not have this issue.

Now that I've setup filters and two parameters, I have this issue when I make changes to my local database and try to sync.

If no changes are made before sync, sync works fine but once changes are made to the local database, this error appears.

Any pointers?

**Comment by Mimetis** [comment]
Ok, 
Did you add the filter, AFTER having done a sync previously ?
IF it's the case, I guess the stored procedures have not ben created correctly.

Are you able to share a repro ?

**Comment by akema-trebla** [comment]
I was adding the filters one after the other and so for the older local sqlite databases, there would've been some syncs before adding the next filter.

However, the issue still shows up after I've set up all the filters, I create a new local sqlite database, perform a sync,  manipulate data in the local database and sync again.

Will the client application alone be enough?

**Comment by Mimetis** [comment]
Just need a table schema sample, the providers you are using, and the code you are using to reproduce on my side
If it's failing with any kind of table; I can use the Adventure Works tables

**Comment by akema-trebla** [comment]
Okay. 

What's the quickest way to generate the ER diagram on a Mac?

I'm using the `SqlSyncChangeTrackingProvider`

**Sync Code**
`var serverOrchestrator = new WebClientOrchestrator("https://my-url/api/sync/");

            // Second provider is using plain old Sql Server provider,
            // relying on triggers and tracking tables to create the sync environment
            var clientProvider = new SqliteSyncProvider("my.db3");
            

            // Using the IProgress<T> pattern to handle progession dring the synchronization
            var progress = new SynchronousProgress<ProgressArgs>(s =>
            {
                Console.WriteLine($"{s.Context.SyncStage}:\t{s.Message}");
            });

            // Creating an agent that will handle all the process
            var agent = new SyncAgent(clientProvider, serverOrchestrator);

            if (!agent.Parameters.Contains("parameterA"))
                agent.Parameters.Add("parameterA", "parameter-a-value");
            if (!agent.Parameters.Contains("parameterB"))
                agent.Parameters.Add("parameterB", "false");

            int i = 1;
            bool tryagain;
            do
            {
                
                Console.WriteLine("Sync Start");
                try
                {
                    Console.WriteLine($"Try number {i}");
                    var syncContext = await agent.SynchronizeAsync(progress);
                    Console.WriteLine(syncContext);
                    tryagain = false;
                }
                catch (Exception e)
                {
                    i++;
                    Console.WriteLine(e.Message);
                    tryagain = true;
                }

            } while (tryagain || Console.ReadKey().Key != ConsoleKey.Escape);

            Console.WriteLine("End");`

After running this I make edits to the local sqlite database and then run the code again, then the error shows up. No errors when you make changes on the online database and perform the sync.

**Comment by akema-trebla** [comment]
I recreated my online Azure database locally is SQL Server and sync after edits appear to be working. 

I also noticed different stored procedures being generated.

For each table in azure I don't see [tablename]_bulkdelete and [tablename]_bulkupdate but I can see these on my recreated local SQL Server database.

Does this mean anything?

**Comment by akema-trebla** [comment]
So I fixed it by deleting both scope tables, all the created stored procedures and all the user defined table types. Then I ran the sync again.

**Comment by Mimetis** [comment]
Ok, can i close this issue ?

**Comment by akema-trebla** [comment]
For me, I'm okay. I don't know about the original author.
