### ISSUE TITLE
How to use OR statement between two parameters in the WHERE statement of a setup filter

### ISSUE THREAD

**Issue by akema-trebla** [Mimetis/Dotmim.Sync#319]
**Description**
How can I set up OR statement between two parameters in the WHERE statement of a setup filter?

**What I've done**
`var myFilter = new SetupFilter("BaseTable");
myFilter AddParameter("ParameterA", "BaseTable");
myFilter.AddParameter("ParameterB", System.Data.DbType.String);
        myFilter.AddJoin(Join.Left, "Table1").On("Table1", "Id", "BaseTable", "Table1Id");
        myFilter.AddJoin(Join.Left, "Table2").On("Table1", "Table2Id", "Table2", "Id");
        myFilter.AddWhere("ParameterA", "BaseTable", "ParameterA");
        myFilter AddWhere("Id", "Table2", "ParameterB");
        setup.Filters.Add(myFilter);`

The above uses AND between the two parameters.

I have. also tried the following:

`var myFilter = new SetupFilter("BaseTable");
        myFilter AddParameter("ParameterA", "BaseTable");           
        myFilter.AddParameter("ParameterB", System.Data.DbType.String);
        myFilter.AddJoin(Join.Left, "Table1").On("Table1", "Id", "BaseTable", "Table1Id");
        myFilter.AddJoin(Join.Left, "Table2").On("Table1", "Table2Id", "Table2", "Id");
        myFilter.AddCustomWhere("WHERE (([base].[ParameterA] = @ParameterA) OR ([Tables2].[Id] = @ParameterB))");
        setup.Filters.Add(myFilter);`

With the above I get the error message:
 
`Incorrect syntax near the keyword 'WHERE'.`

Any pointers?

**Comment by Mimetis** [comment]
the `AddCustomWhere` clause is added after all generated where clauses.
So far you should not add the keyword `Where`
Can you try instead

``` cd
myFilter.AddCustomWhere("([base].[ParameterA] = @ParameterA OR [Tables2].[Id] = @ParameterB)");
```

Let me know

**Comment by akema-trebla** [comment]
Yes, it worked. Thanks
