### ISSUE TITLE
SQLite and guid storage

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#32]
Hello Sebastien,
do you see any chance to introduce a switch (maybe by recompiling the code my own) to store guids in sqlite as char? 
My clients do not support guid-blob out of the box and I would be a lot of work to change.

Thanks
Reinhold

**Comment by Mimetis** [comment]
Seems difficult. 
The best way to achieve this, is to make a PR on the [Microsoft.Data.Sqlite](https://github.com/aspnet/Microsoft.Data.Sqlite) repository .

But as you can see on [#363](https://github.com/aspnet/Microsoft.Data.Sqlite/pull/363), it seems that the ASP.NET Team has decided to not implement it

@bricelam : Any new considérations on this ?

The only solution would be fork the `Microsoft.Data.Sqlite` and make a local modification.
But it's not on my roadmap at the moment :)

**Comment by bricelam** [comment]
I think we've done all we're going to do in this area in 2.1.0 (in development). But I stand by my statement that any type conversions can easily be layerd on top of Microsoft.Data.Sqlite.

Has anyone asked System.Data.SQLite if they intend to support .NET Core?
