### ISSUE TITLE
How to provision/ Deprovision using ASP.NET core

### ISSUE THREAD

**Issue by hims889** [Mimetis/Dotmim.Sync#322]
Hi, 

I am using ASP .Net core as my web server, Is there any sample/example for provision/Deprovision using Asp .net core.

Thanks.

**Comment by gb0o** [comment]
You could put the provision/deprovision into a ASP.NET Core controller then build an admin client desktop app or web page to manage the process. Pretty straight forward:
```
namespace SomeServer.Sync.API.Controllers
{
    [Route("api/[controller]")]
    public class ProvisionController : Controller
    {
        private readonly WebServerManager _webServerManager;

        public ProvisionController(WebServerManager webServerManager)
        {
            _webServerManager = webServerManager;
        }

        [HttpPost("provision")]
        public async Task<IActionResult> Provision([FromQuery] int provision)
        {
            var orchestrator = _webServerManager.GetOrchestrator(HttpContext);
            await orchestrator.ProvisionAsync((SyncProvision) provision);

            return Ok();
        }

        [HttpPost("deprovision")]
        public async Task<IActionResult> Deprovision([FromQuery] int provision)
        {
            var orchestrator = _webServerManager.GetOrchestrator(HttpContext);
            await orchestrator.DeprovisionAsync((SyncProvision) provision);

            return Ok();
        }
    }
}
```

**Comment by Mimetis** [comment]
Following the @gb0o's response, if you want a **FULL** provision (with new Setup and Schema), you can follow this example:

Coming from this doc : https://dotmimsync.readthedocs.io/Provision.html#provision

``` cs
[HttpGet]
[Route("prov")]
public async Task PovisionAsync()
{
    // Get Orchestrator 
    var orchestrator = webServerManager.GetOrchestrator("DefaultScope");

    var progress = new Progress<ProgressArgs>(pa => Debug.WriteLine($"{pa.Context.SyncStage}\t {pa.Message}"));

    // get the server scope (and Create the table if needed)
    var serverScope = await orchestrator.GetServerScopeAsync();

    // Server scope is created on the server side.
    // but Setup and Schema are both null, since nothing have been created so far
    //
    // Provision everything needed (sp, triggers, tracking tables)
    // Internally provision will fectch the schema and will return it to the caller. 
    var newSchema = await orchestrator.ProvisionAsync(SyncProvision.StoredProcedures | SyncProvision.Triggers | SyncProvision.TrackingTable);

    // affect good values
    serverScope.Setup = orchestrator.Setup;
    serverScope.Schema = newSchema;

    // save the server scope
    await orchestrator.WriteServerScopeAsync(serverScope);

}

```

**Comment by hims889** [comment]
> 
> 
> You could put the provision/deprovision into a ASP.NET Core controller then build an admin client desktop app or web page to manage the process. Pretty straight forward:
> 
> ```
> namespace SomeServer.Sync.API.Controllers
> {
>     [Route("api/[controller]")]
>     public class ProvisionController : Controller
>     {
>         private readonly WebServerManager _webServerManager;
> 
>         public ProvisionController(WebServerManager webServerManager)
>         {
>             _webServerManager = webServerManager;
>         }
> 
>         [HttpPost("provision")]
>         public async Task<IActionResult> Provision([FromQuery] int provision)
>         {
>             var orchestrator = _webServerManager.GetOrchestrator(HttpContext);
>             await orchestrator.ProvisionAsync((SyncProvision) provision);
> 
>             return Ok();
>         }
> 
>         [HttpPost("deprovision")]
>         public async Task<IActionResult> Deprovision([FromQuery] int provision)
>         {
>             var orchestrator = _webServerManager.GetOrchestrator(HttpContext);
>             await orchestrator.DeprovisionAsync((SyncProvision) provision);
> 
>             return Ok();
>         }
>     }
> }
> ```

Hi @gb0o , 
I have tried your solution: 

1.  Created web API controller in my .net core application and pasted code provided by you. 
2. Now I am getting this error: 

![image](https://user-images.githubusercontent.com/6139240/92379867-c9cd9980-f125-11ea-97bd-eba357a0a613.png)


Here are some questions: 
1. I am trying to add 2 new tables and some columns in existing tables. How I will specify which tables/columns to add in your example. 
2. I am syncing data into SQL Server and winforms sqlite database(Client application), Do I need to call methods specified by you from winforms application? 
Note: I am very new to Asp .net Core.

**Comment by hims889** [comment]
Hi @Mimetis @gb0o , 

I have provided "DefaultScope" as scope name, this fixed the error I am getting but the new added table and columns are not syncing to Sqlite database. 

Here are the steps I have tried:

1. Added new Table and some columns in existing tables in my main SQL Server. 
2. Added Table name in list of tables inside Sync Server Application (Asp .Net Core Application). 
3. Then I ran De-Provision Method using postman
![DeProvision](https://user-images.githubusercontent.com/6139240/92591391-6d9c7e00-f2bb-11ea-8d52-c0a4229ca2c1.png)

4. Then I ran Provision Method using postman.
![Provision](https://user-images.githubusercontent.com/6139240/92591461-8efd6a00-f2bb-11ea-9e09-750c2a09cbc6.png)

5. Then I deleted by Sqlite database and ran Sync from my Desktop application (Client Application). All other tables and data is synced but newly added tables are columns are not syncing.

**Please let me know what I am missing or doing wrong.** 

Here is my complete code of provision/deprovision:


```
namespace WebApplication1.Controller
{
    [Route("api/Prov")]
    //[Authorize]
    public class ProvisionController : ControllerBase
    {
        private readonly WebServerManager _webServerManager;

        public ProvisionController(WebServerManager webServerManager)
        {
            _webServerManager = webServerManager;
        }

        [HttpPost("provision")]
        public async Task<IActionResult> Provision([FromQuery] int provision)
        {
            var orchestrator = _webServerManager.GetOrchestrator("DefaultScope");
            await orchestrator.ProvisionAsync((SyncProvision)provision);

            return Ok();
        }

        [HttpPost("deprovision")]
        public async Task<IActionResult> Deprovision([FromQuery] int provision)
        {
            var orchestrator = _webServerManager.GetOrchestrator("DefaultScope");
            await orchestrator.DeprovisionAsync((SyncProvision)provision);

            return Ok();
        }
    }
}
```

**Comment by Mimetis** [comment]
You should read carefully what I've posted in a last message, in this thread : https://github.com/Mimetis/Dotmim.Sync/issues/322#issuecomment-687096521

Once you have provision you DB, you have to save the scopes.

**Comment by hims889** [comment]
Hi @Mimetis, 
Here is my latest code: 

```
[HttpGet]
        [Route("provision")]
        public async Task PovisionAsync()
        {
            // Get Orchestrator 
            WebServerOrchestrator orchestrator = _webServerManager.GetOrchestrator("DefaultScope");

            //var progress = new Progress<ProgressArgs>(pa => Debug.WriteLine($"{pa.Context.SyncStage}\t {pa.Message}"));

            // get the server scope (and Create the table if needed)
            ServerScopeInfo serverScope = await orchestrator.GetServerScopeAsync();

            SyncSet newSchema = await orchestrator.ProvisionAsync(SyncProvision.StoredProcedures | SyncProvision.Triggers | SyncProvision.TrackingTable);

            // affect good values
            serverScope.Setup = orchestrator.Setup;
            serverScope.Schema = newSchema;

            // save the server scope
            await orchestrator.WriteServerScopeAsync(serverScope);

        }

        [HttpGet]
        [Route("deprovision")]
        public async Task DeprovisionAsync()
        {

            // Get Orchestrator 
            WebServerOrchestrator orchestrator = _webServerManager.GetOrchestrator("DefaultScope");

            //var progress = new Progress<ProgressArgs>(pa => Debug.WriteLine($"{pa.Context.SyncStage}\t {pa.Message}"));

            // get the server scope (and Create the table if needed)
            ServerScopeInfo serverScope = await orchestrator.GetServerScopeAsync();

            // Deprovision everything
            await orchestrator.DeprovisionAsync(SyncProvision.StoredProcedures
                | SyncProvision.Triggers | SyncProvision.TrackingTable);

            // Affect good values
            serverScope.Setup = null;
            serverScope.Schema = null;

            // save the server scope
            await orchestrator.WriteServerScopeAsync(serverScope);

        }
```

Now I am getting following error when I am trying to sync from my desktop application: 
![Sync](https://user-images.githubusercontent.com/6139240/92719414-b66a3a80-f380-11ea-9cf6-328d51cf5b88.png)

Here is the response I am getting when calling Deprovision:
![Deprovision](https://user-images.githubusercontent.com/6139240/92719891-722b6a00-f381-11ea-9b5f-3155e568d987.png)

When I am trying to Provision, Newly created table is in the list:
![image](https://user-images.githubusercontent.com/6139240/92720084-bf0f4080-f381-11ea-87ec-02be94b6b7ad.png)

Steps I have followed this time:

1. I called DeProvision.
2. I called Provision 
3. Then I called sync from desktop application.

What does I am doing wrong this time?

**Comment by Mimetis** [comment]
Try to call with reinitialize option from the client

**Comment by hims889** [comment]
@Mimetis  Any Example?
