### ISSUE TITLE
WebServer Authorization

### ISSUE THREAD

**Issue by gaurakshay** [Mimetis/Dotmim.Sync#326]
This is an amazing library and exactly what we are looking for. How would you go about adding authorization to the Web API so that only the clients who have been authenticated can access the API?

**Comment by akema-trebla** [comment]
https://github.com/Mimetis/Dotmim.Sync/issues/42

It's outlined here.

**Comment by Mimetis** [comment]
it's old, but with some minors changes, it should work
Let me know

**Comment by vunder** [comment]
Small addition. POST method can be simlified by adding custom policy
```csharp
            services.AddAuthorization(options =>
            {
                options.AddPolicy("SyncScope", policy =>
                {
                    policy.RequireAuthenticatedUser();
                    policy.RequireClaim("http://schemas.microsoft.com/identity/claims/scope", "Sync");
                });
            });
```
Within the controller all you need is to change `[Authorize]` to `[Authorize("SyncScope")]`.
Sync method would be simple
```csharp
        [HttpPost]
        public async Task PostAsync() =>
            await manager.HandleRequestAsync(this.HttpContext);
```
In case user would have wrong auth tokn or token would not contain necessary scope you'll get `Forbidden (403)` http response code

**Comment by vunder** [comment]
Addition to adapt sample for the latest version (just pass HttpClient with auth headers to orchestrator)
```csharp
        private static readonly HttpClient httpClient = new HttpClient();

....
        private async void AppBarButton_Click(object sender, RoutedEventArgs e)
        {
            httpClient.DefaultRequestHeaders.Authorization = AuthenticationHeaderValue.Parse(authResult.CreateAuthorizationHeader());
...
            var serverOrchestrator = new WebClientOrchestrator("https://localhost:6001/api/sync") { HttpClient = httpClient };

        }
```
