### ISSUE TITLE
Unhandled exception: Microsoft.Data.SqlClient is not supported on this platform.

### ISSUE THREAD

**Issue by Solution-Studio** [Mimetis/Dotmim.Sync#328]
Hi,

I can see that others have had this problem, and I have followed previous suggestions. However, I cannot solve the problem.

My platform is:
Xamarin Forms based on .NET Standard Library 2.0.3
Dotmim NuGet packages latest versions

The exception is thrown upon calling SyncronizeAsync in the following code:

  public class DatabaseSynchronisation
  {
    private static string clientConnectionString = "Data Source=.; Initial Catalog=AdventureWorks2019;Integrated Security=true;";
    private static SqlSyncProvider clientProvider;
    private static WebClientOrchestrator serverOrchestrator;
    private static SyncAgent agent;

    static DatabaseSynchronisation()
    {
      clientProvider = new SqlSyncProvider(clientConnectionString);
      serverOrchestrator = new WebClientOrchestrator("http://Server:5000/api/sync");

      agent = new SyncAgent(clientProvider, serverOrchestrator);
    }

    public static async Task SynchronizeAsync()
    {
      await agent.SynchronizeAsync();
    }
  }

I would be grateful for any help or suggestions.
Thanks
Ian

**Comment by Mimetis** [comment]
If you're trying to develop a Xamarin application, the only database allowed locally is `Sqlite`
So far you need to use `SqliteSyncProvider` instead of `SqlSyncProvider`

**Comment by Solution-Studio** [comment]
Of course. Thanks I'll try that.
