### ISSUE TITLE
Table with reserved column name is not processed correctly

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#33]
Hello Sebastien,
I'm not sure, if you want to exclude such a table structrue, but in any case I would like to inform you, that a table with the following structure causes sync to stop:

CREATE TABLE [dbo].[Log](
	[Oid] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[TimeStamp] [datetime] NULL,
	[Operation] [nvarchar](100) NULL,
	[ErrorDescription] [nvarchar](100) NULL,
	[OptimisticLockField] [int] NULL,
	[GCRecord] [int] NULL,
 CONSTRAINT [PK_Log] PRIMARY KEY CLUSTERED 
(
	[Oid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

**Comment by Mimetis** [comment]
Thx, I will take a look on this !

**Comment by Mimetis** [comment]
Hey @thefonzi,
I found the problem. **Timestamp** is a reserverd column name in the **Dotmim.Sync** world   
It will be a huge amount of works to correct this, so I believe your best choice so far is to rename your column.   

I have implemented a method to check all the columns name that are used in any synced table.  
If you use a reserved column name, you will have an exception raised:

```
if (columnNameLower == "sync_scope_name"
|| columnNameLower == "scope_timestamp"
|| columnNameLower == "scope_is_local"
|| columnNameLower == "scope_last_sync"
|| columnNameLower == "create_scope_id"
|| columnNameLower == "update_scope_id"
|| columnNameLower == "create_timestamp"
|| columnNameLower == "update_timestamp"
|| columnNameLower == "timestamp"
|| columnNameLower == "sync_row_is_tombstone"
|| columnNameLower == "last_change_datetime"
|| columnNameLower == "sync_scope_name"
|| columnNameLower == "sync_scope_name"
)
throw SyncException.CreateNotSupportedException(
    SyncStage.ConfigurationApplying, $"The Column name {column.ColumnName} from provider {this.ProviderTypeName} is a reserved column name. Please choose another column name.");
```
