### ISSUE TITLE
IConverter usage is not described fully

### ISSUE THREAD

**Issue by vunder** [Mimetis/Dotmim.Sync#332]
Current documentation does not mention any requirements for `Key` value in `IConverter` implementation. However, according to code it must be in lower case. Otherwise in HTTP mode server return an error that converter was not found.
Getting converter key in lower-case:
https://github.com/Mimetis/Dotmim.Sync/blob/302121209e6e9487f80fc104954e86d5ea2247bb/Projects/Dotmim.Sync.Web.Server/WebServerOrchestrator.cs#L89-L90
Looking for converter with case-sencitive comparison:
https://github.com/Mimetis/Dotmim.Sync/blob/302121209e6e9487f80fc104954e86d5ea2247bb/Projects/Dotmim.Sync.Web.Server/WebServerOrchestrator.cs#L275
It should be either everywhere lower-case comparison or updated docs and code that would check key to be in lower-case.

**Comment by Mimetis** [comment]
thx @vunder, I will try to fix it asap to include it in the next release

**Comment by Mimetis** [comment]
Thanks Vunder for discovering this bug.
It's now merged into master
