### ISSUE TITLE
Mapper bettween client model and server model

### ISSUE THREAD

**Issue by thanhhactld** [Mimetis/Dotmim.Sync#336]
Currently, my systems has already existed with difference table name and column name. So, how i can create custom mapper between client model and server model ?
Such as:

TableName: 
                  ClientUser <-> DbUser
Column Names:
                  id <-> user_id
                  name   <-> full_name

**Comment by Mimetis** [comment]
You can't.
The `DMS` framework is working based on table name and column names.
I guess this is something we can think for a future version, but for now, it's not possible.

Anyway, If you want to contribute, it could be a great addition !

**Comment by thanhhactld** [comment]
Thanks for your answer, i hope to contribute to your project in the future.  ^^
