### ISSUE TITLE
Error while syncing tables having identity column other than primary key 

### ISSUE THREAD

**Issue by mangireesh** [Mimetis/Dotmim.Sync#338]
Hi,
I am new to this Syncing process. I am trying to sync MSSQL Server with SQLite Client database(Sync over HTTP). In my server some tables having identity columns(auto-increment) and primary key(unique id or GUID) both are different columns. While performing the sync operation is completed successfully, but the value in the identity columns are NULL in client. Is there any way to rectify the same without changing the schema? 

Thanks and Regards
Gireesh M

**Comment by szakalo** [comment]
Hi, 
I have the same problem. One database is MSSQL, the other is SQL Lite. I have a table that has two Identity column. Dotmim is unable to synchronize this table. Is there any way to do this?

Regards 
Martin

**Comment by Mimetis** [comment]
You can't have two auto inc column in a table
And DMS is not handling auto inc for GUID (I even didn't know how it's possible ?????)
