### ISSUE TITLE
[Proposal] Initial Provisioning may take long time without progress indicator

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#34]
Hello,
i have tried to sync a database with about 250MB and the initial "Ensuring" takes some time, but the progress remains at 0 until the inserts start.
Would it be possible to provide a feedback in this phase?

**Comment by Mimetis** [comment]
Hi @thefonzi ;
I'm currently working on a new way of handling events.   
You will have more controls on events raised and more informations.  
I will test on a huge database to see what kind of feedback I can sent to the user.   
By the way, is it a database with few tables (and maybe one with a huge amount of data) or a database with a lot of tables ?

**Comment by thefonzi** [comment]
more info. This is the step, that takes most of time: 

Sync Start
Begin Session.
Ensure Scopes
Ensure Configuration
Configuration readed. 181 table(s) involved.
Ensure Database
Selecting changes...
Changes selected : 0

**Comment by thefonzi** [comment]
It's a mix of  a lot of tables and some of the tables contain more than 3000 records. 
BTW: the database content has in great parts scrambled string contents, as I used it for demo. If you want to get it for a test, let me know.

**Comment by Mimetis** [comment]
Well, if you can share it with me, it would be great !!!!

**Comment by Mimetis** [comment]
Eventually I found a big database, where I can make tests :)
