### ISSUE TITLE
Initial synchronization of non-empty DB not working?

### ISSUE THREAD

**Issue by mrauls** [Mimetis/Dotmim.Sync#342]
According [to this link](https://dotmimsync.readthedocs.io/AlreadyExisting.html) in the documentation, the sync framework should "just work" in terms of having a client DB with some data in it already that gets pushed to the server on initial sync. However I can't seem to get this to work. 
These are my details:
- This is all version 0.5.7 (client and server side)
- I am using SqlServer with change tracking on the server side, and using the web proxy
- On the client side, I am using Sqlite

Scenario 1 Works:
- Create record C&D in server side
- Sync. C&D are now on client
- Create A&B on client side.
- Sync. A, B, C and D are on the server, and on the client

Scenario 2 Doesn't work:
- Create record C&D in server side
- Create A&B on client side.
- Sync. A, B, C and D are on the client, but the server doesn't have A&B

I'm not sure if this would impact anything, but I have filters that filter data based on an attribute. The client data and the server data both have the correct attribute though.

I am not really sure where to go from here in terms of debugging / understanding what is happening. Any assistance would be appreciated. Thank you.

**Comment by vunder** [comment]
Check this one https://github.com/Mimetis/Dotmim.Sync/issues/312
I had similar problem: initial sync with existing data.

**Comment by Mimetis** [comment]
Thanks @vunder  for the link to #312 

@mrauls, as @vunder  says, the documentation is not up to date on this point (apologize for that, just need time (and motivation ) to update the doc)

The to use it the `UpdateUntrackedRowsAsync()` on the `LocalOrchestrator`.

https://github.com/Mimetis/Dotmim.Sync/blob/72da7c8ac51935330662ee98d95e7a7a4c03c400/Projects/Dotmim.Sync.Core/Orchestrators/LocalOrchestrator.cs#L664

``` cs
// Make a first sync to get the schema from server, provision all tracking tables , 
// stored procedures, triggers and so on...
var s = await agent.SynchronizeAsync();

// Here, we should not have any uploaded rows, since it's the first sync.
// But, eventually we have all the rows from server.
Console.WriteLine(s);

// Get local schema
var schema = await agent.LocalOrchestrator.GetSchemaAsync();

// Update all rows on the client side that does not have any tracking rows
await agent.LocalOrchestrator.UpdateUntrackedRowsAsync(schema);

// Make as second sync.
// All local rows that were existing before first sync happened, will be uploaded correctly
s = await agent.SynchronizeAsync();
```

Let us know if it's working as expected

**Comment by mrauls** [comment]
Thanks for the quick response. Yes this fixed the issue. Quick follow up:
1. Is this a bug, or expected? In other words is this eventually going to detect and pick up those items on initial sync, or do I always need to perform that second step?
2. Are there other conditions that cause that? I guess I am asking because the above effectively causes a double sync, which I don't want to do all the time. So I was just going to detect if its a first sync, and then if it is do the double sync. If not, then the second step is not performed. But I am just wondering if there are other edge cases that cause untracked items like this.

Thanks again, this is a great framework so far.

**Comment by Mimetis** [comment]
> 1. Is this a bug, or expected? In other words is this eventually going to detect and pick up those items on initial sync, or do I always need to perform that second step?

No, this is expected. 
You have to do this kind of things everytime you have a new database (with data in it) that wants to synchronise
Once you have done it, the first time, you don't have to do it after.
I mean, once it's done, it's done, all the next sync do not have to call this method.
Do it the first time you sync, that's all

> 2. Are there other conditions that cause that? I guess I am asking because the above effectively causes a double sync, which I don't want to do all the time. So I was just going to detect if its a first sync, and then if it is do the double sync. If not, then the second step is not performed. But I am just wondering if there are other edge cases that cause untracked items like this.

Yes, just see you are in a first sync, make the double sync, and that's it.
The second time, make a simple sync, as ususal
