### ISSUE TITLE
Multi-level synchronization

### ISSUE THREAD

**Issue by mrauls** [Mimetis/Dotmim.Sync#344]
I am experimenting with your framework and am trying to determine whether it can support multi-level synchronization. I have two-level sync working, using SqlServer to SqlServer as well as Sqlite to SqlServer. I am using the web components and everything seems like it is working OK.

However, when I try to have something like this:

SqlServer (A)
-syncs to-
SqlServer (B)
-syncs to-
Sqlite (C)

It seems like it doesn't work. So for example with empty DBs: 
- I sync B to A, then sync C to B, to "register" everything. 
- Then I create Item #1 in B, and sync B to A. This works, Item #1 is in A&B
- Then I sync C to B. Still good, now Item 1 is in A, B and C.
- Now I create Item #2 in C. I sync, it indicates that changes have been uploaded. Checking in the B DB, I see the item is actually there.
- Now, I sync B to A, expecting #2 to move to A. It says 0 changes have been uploaded. Checking in A DB confirms the item is not in A. 

It's as if the sync process doesn't see the item #2 in DB B as tracked or something. 

I know this is longwinded I am just trying to understand if this multi-level scenario is feasible. Thank you.

**Comment by Mimetis** [comment]
`DMS` is not a **Peer to Peer** synchronization framework.
It's more a **Master - Clients** system.

For instance, you may have **one** master and **several** clients.

All the clients will sync with the master, that is the rely endpoint for all
So far :
- A is master
- B can sync to A
- C can sync to A
- D can sync to A

but 
- B can't sync to C
- D can't sync to B

Make sense ?

**Comment by mrauls** [comment]
Thanks, yes. I understand. I was not hoping for peer to peer, more hierarchical, like maybe
     A
   /   \
  B    C
 / \
D  E

In other words I was hoping B could be both a master and a client. But sounds like that is not possible.

**Comment by Mimetis** [comment]
Indeed, A to B then B to D is somehow "peer to peer" typology

**Comment by kmacute** [comment]
Okay now I get it. multi level is not supported..
on my side, im planning to upgrade my pos 

1. Local Client , 
2. Local Server, 
3. Online Server


This one is working (**Going Down**)
```
Online Server ->  Sync to Local Server -> Working
Local Server -> Sync to Local Client (POS) -> Working
```

This one is working (**Going Down**)
```
Online Server ->  Sync to Local Server -> Working
Local Server -> Sync to Local Client (POS) -> Working
```


This one is not working (**Going Up**)
```
Local Client -> Sync to Local Server -> Working
Local Server -> Sync to Online Server -> NOT Working
```

**Comment by haleemzahid** [comment]
I am also facing the same issue. It would be helpful if @Mimetis can provide some guidance on how we can implement it. I can fork the Dotmim.Sync and add the peer-to-peer synchronization.

**Comment by Mimetis** [comment]
> I am also facing the same issue. It would be helpful if [@Mimetis](https://github.com/Mimetis) can provide some guidance on how we can implement it. I can fork the Dotmim.Sync and add the peer-to-peer synchronization.

If you think you can create a peer to peer sync, feel free to create it !
Honestly, I tried several times, but it's way much more complicated than what I was expecting 
Eventually I failed to implement it

If you can do it, would be awesome
