### ISSUE TITLE
Bulk Operations/Stored Procedures

### ISSUE THREAD

**Issue by fluffclark** [Mimetis/Dotmim.Sync#346]
I am just starting out with Dotmim.Sync...
I have set up a SQL Server database with change tracking, and I am using a WebApi for the client connection.
SQLite on the client end.

I have BulkOperations enabled, but it throws an error...
`Dotmim.Sync.SyncException: A SqlParameter with ParameterName '@changeTable' is not contained by this SqlParameterCollection.`
..when sending client changes back to the server. I realised that the bulkxxx stored procedures are missing. A quick look at the source code suggests that these should have been created, but they were not.

Is there a way to either create the stored procedures manually, or to force reinitialization?

**Comment by Mimetis** [comment]
To reforce a recreate, you can play with `ProvisionAsync` and `DeprovisionAsync`.
Since it's a one shot operation, my advice is to create a simple console application, and using directly a `RemoteOrchestrator` to your server.

Let me know if it's fixing things

**Comment by fluffclark** [comment]
I called 
`await orchestrator.ProvisionAsync(SyncProvision.StoredProcedures, cancellationTokenSource.Token, new Progress<ProgressArgs>());`
Intriguingly, for 1 of my tables, it created the bulkXXX procedures, but for the 2 others, it only created the 'other' stored procedures. 
Is there a property or suchlike on the table that the code uses to determine what to create?
Also, if I now call
`await orchestrator.DeprovisionAsync(SyncProvision.StoredProcedures, cancellationTokenSource.Token, new Progress<ProgressArgs>(ProvisioningProgressHandler));`
then it throws an exception trying to remove the non existent bulkXXX procedures from the tables that it didn't create the procedures for!

**Comment by fluffclark** [comment]
Ok - I determined that the 'types' created in the database 'xxxx_BulkType' were used as the check to determine if the stored procs needed to be provisioned.
Therefore I dropped the xxx_BulkType types, and provisioned the database - all the stored procedures are now in place.
Thanks for the clues. I'm not sure how it got 'out of sync', but I do know understand how to get it back to a clean point.

**Comment by Mimetis** [comment]
Thanks for the Feedback @fluffclark 
I should maybe make more tests on both existence of the stored procedures AND bulk types maybe.

I let this issue opened to have a trace.

**Comment by UweKeim** [comment]
Having the exact same issue(s) as described by @fluffclark 

Will try to fix it as outlined in https://github.com/Mimetis/Dotmim.Sync/issues/346#issuecomment-698917599

**Comment by UweKeim** [comment]
Manually deleting all entries in

> _MyDatabase_ → Programmability → Types → User-Defined Table Types

in both my local and my remote database did the trick.

### My suggestion

Please add an ability to deprovision those types programmatically, too. 

E.g. add another enum value like `SyncProvision.Types` or something like that.

**Comment by Mimetis** [comment]
It's coming with the next release of version `v0.6`
Take a look on https://github.com/Mimetis/Dotmim.Sync/discussions/391
