### ISSUE TITLE
Cannot sync a many to many table with extra column

### ISSUE THREAD

**Issue by Solution-Studio** [Mimetis/Dotmim.Sync#347]
I have a many to many table that is an association table between two other tables. At first all was fine and it synced happily over http between a client Sqlite database and an MS SQL Server database. The table had two columns forming the primary key which were foreign keys to the other tables.
I then added a third column (varchar(50) and now it won't sync. The table structures from the server are downloaded to the client if I synchronise using SyncType.Reinitialize and all initially looks OK.
When I insert a new row to the client table this is updated correctly into the sqlite database. However when I then perform a normal sync I get_ the following exception:
{Dotmim.Sync.SyncException: Trying to pass a table-valued parameter with 3 column(s) where the corresponding user-defined table type requires 2 column(s).  at Dotmim.Sync.Web.Client.HttpRequestHandler.HandleSyncError

I've tried resetting everything multiple times to no avail.
I'm using the 0.5.8 beta version as initially the third column was a blob field, and this version has a fix to support this. However I get the same issue with 0.5.7.

I'd be very grateful if anyone could help.

**Comment by Mimetis** [comment]
You may have a Table Type (TVP) in your database, that you did not delete.
Look into User-Define Table Types
![image](https://user-images.githubusercontent.com/4592555/94652993-240fe380-02fb-11eb-904c-1b39dec5f8bf.png)

You should use `DeprovisionAsync` and `ProvisionAsync` as well to ensure everything is deleted / created correctly

Let me know if it resolved your issue

**Comment by Solution-Studio** [comment]
That resolved it. Many thanks Mimetis :)
