### ISSUE TITLE
What security is currently implemented?

### ISSUE THREAD

**Issue by moggoly** [Mimetis/Dotmim.Sync#348]
For the sync over HTTP method, what security if any is there to prevent open access? i.e. shared key/secret, authorization, etc.

**Comment by Mimetis** [comment]
gey @moggoly 

`DMS` is **just** a framework. All the calls, in the http mode, are handled by the ASP.NET Core Web Api mechanism.
So far, you just have to secure your web api, like any other api.

A good starting point for protecting a Web API with Azure AD here : https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis

**Comment by gentledepp** [comment]
we for example add an OAUTH authorization header before the sync process starts.
(more advanced would be to implemented a delegatinghandler that is passed to `DMS` so that you can handle `401` responses and re-authenticate on-the-fly)
