### ISSUE TITLE
QUESTION - Is it possible to use an ALTERNATIVE or CANDIDATE key for synchronization?

### ISSUE THREAD

**Issue by dsfugabanjr** [Mimetis/Dotmim.Sync#349]
I understand I could use a different set or range for different clients or devices for **IDENTITY** columns, but instead of synchronizing with **IDENTITY** columns, is it possible to use another KEY/FIELD which is a **CANDIDATE** key with a **GUID** or **UNIQUEIDENTIFIER** type?

Does the documentation for setting different range or set of identities per client exist somewhere? Can I have the link to that please? While this seems possible, I wish my question above is also possible. Thanks!

**Comment by Mimetis** [comment]
The `DMS` framework works on primary keys to ensure everything is uniquely identified.
The tracking tables are generated with these primary keys as well.

As long as you have a primary key in your table, it should work.

If you're using an identifier, be sure you're handling correctly the seeding
