### ISSUE TITLE
Integation tests are not properly isolated per client

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#352]
The integration tests (e.g. SqlServerHttpTests) are not properly isolated:

Each tests runs *every* client implementation.

Because there is just one test for all clients (foreach (var client in Clients)) I had to calculate the number of rows that should be downloaded by the 2nd client or present on the server after the 2nd client synced...
I already split the tests to isolate them by client in my repository. 
See [here](https://github.com/gentledepp/Dotmim.Sync/tree/feature/7_splittests)
A pull request will follow somewhere in the future!

**Comment by Mimetis** [comment]
Well, I know this is complicated to handle, but it's intended.
Sometimes a bug can occurs when a sync is working on multiple clients
For example, C1 sync to S, then C2 sync to S, but did not get C1 rows.

I know this could be complicated to maintain, but if you want them to be isolated, you can always reset everything at the begining of the test, using the create database method with the flag `recreateDb` set to `true`

```
// create a server db without seed
await this.EnsureDatabaseSchemaAndSeedAsync(this.Server, false, UseFallbackSchema);

// create empty client databases
foreach (var client in this.Clients)
{
    await this.CreateDatabaseAsync(client.ProviderType, client.DatabaseName, true);
    var agent = ....
{

```

**Comment by gentledepp** [comment]
well but in this case, you really should write tests that do reproduce this multi-client issue scenario.
But having this scheme for every test still makes no sense to me.
That way it is more likely that you introduce a bug because the side-effects caused by other clients synchronizing with one server database cloud your view :-|
