### ISSUE TITLE
DefaultRequestHeaders is cleared

### ISSUE THREAD

**Issue by UweKeim** [Mimetis/Dotmim.Sync#354]
Using [this suggestion](https://github.com/Mimetis/Dotmim.Sync/issues/326#issuecomment-687146375) to send additional authentication headers from the client to a WebAPI, I found out that in my ASP.NET Core WebAPI endpoint the headers I added are gone.

Looking deeper at HttpRequestHander, I found out that [in line 81, the headers are cleared](https://github.com/Mimetis/Dotmim.Sync/blob/8398114ee904a1da8b488f89a5d250bdf8ffb94c/Projects/Dotmim.Sync.Web.Client/HttpRequestHandler.cs#L81):

    client.DefaultRequestHeaders.Clear();

As far as I could find out this is the reason why my headers do not arrive on the server.

### My question

Is there any other way for me to add additional headers to every request from the client to the server via WebAPI?

**Comment by Mimetis** [comment]
Oh, this is surely a bug in the headers processing.
The framework should not delete the headers.
I will fix that in the next update.
For now, if you're using the source, code, just comment this line. In the next release I will be more granular witht he headers

**Comment by UweKeim** [comment]
Awesome. Thanks for you fast, positive feedback 👍🏻☺️
