### ISSUE TITLE
Can be used to sync data from an API instead?

### ISSUE THREAD

**Issue by ibrahim-erx** [Mimetis/Dotmim.Sync#355]

**Comment by Mimetis** [comment]
Be a little bit more precise, please

**Comment by Ibrahim-Islam** [comment]
For example, there is an external API that basically returns all data of a table. I want to periodically call that API and sync it with my Azure SQL database. This library from the documentation is more like `database -> database` sync but I was hoping to use it for `api -> database`.

**Comment by Mimetis** [comment]
You can use the Web proxy feature, that allows you to expose your server database through a web api : https://dotmimsync.readthedocs.io/Web.html

**Comment by Ibrahim-Islam** [comment]
1. I mentioned **external** API. So, I don't have access to their infrastructure other than the API only.
2. Can we make the sync one way only e.g. configuration? i.e. API -> DB

I am open to work on this to support this features if you think they are worthwhile

**Comment by Mimetis** [comment]
Hey @Ibrahim-Islam 
Unfortunately, there is a deep relationship between the server and all the clients
the framework has to be installed on both side to be able to manage the full sync process.
