### ISSUE TITLE
[Bug] object ref not set using webproxy

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#36]
Hello Sebastien,
I have successfully synchronized a huge database (which I uploaded), but starting the same with syncConsole and WebServer gives an object ref not set error. 
How can I extract a better error message to pass this one to you?

**Comment by thefonzi** [comment]
Web sync start
UNKNOW EXCEPTION : Object reference not set to an instance of an object.
Sync Ended. Press a key to start again, or Escapte to end

**Comment by Mimetis** [comment]
argh .... 
Maybe in Visual Studio, check this 
![image](https://user-images.githubusercontent.com/4592555/34389217-b3bbf01a-eb38-11e7-96a5-8c77192fd1d3.png)

You will have a better error description.

Let me know

**Comment by thefonzi** [comment]
Hello,
I'm not sure, if these details will help you, but anyway I post all I got:

System.NullReferenceException
  HResult=0x80004003
  Nachricht = Object reference not set to an instance of an object.
  Quelle = Dotmim.Sync.Web
  Stapelüberwachung:
   at Dotmim.Sync.Web.HttpRequestHandler.<ProcessRequest>d__15`1.MoveNext() in D:\Documents\VisualStudio\Projects\Dotmin.Sync\Dotmim.Sync-master\Projects\Dotmim.Sync.Web\HttpRequestHandler.cs:line 155

![objectrefnotset](https://user-images.githubusercontent.com/6755910/34402190-6bfbab7c-eba0-11e7-8097-9004e52dcecb.PNG)

**Comment by thefonzi** [comment]
![image](https://user-images.githubusercontent.com/6755910/34402231-9c42650a-eba0-11e7-8a87-e28302fd0cb9.png)

**Comment by Mimetis** [comment]
The problem comes from the server side.   
Is it a huge and big database ?
Without web proxy (I mean, with just sample application) does it make long time to sync ?   
Maybe you have a timeout connection ?

**Comment by thefonzi** [comment]
I will try with some smaller databases and increase. Will let you know

**Comment by Mimetis** [comment]
Any update on this ?

**Comment by thefonzi** [comment]
hello Sèbastien,
sorry for my delay. You were right. this is related to timeouts in part.
I'm still testing. Will let you know

**Comment by Mimetis** [comment]
Ok so I will close this one. If you have more informations, feel free to re open it.
