### ISSUE TITLE
Is the WebClientOrchestrator able to provision/deprovision?

### ISSUE THREAD

**Issue by UweKeim** [Mimetis/Dotmim.Sync#362]
Using the `WebClientOrchestrator` together with the [provisioning examples](https://dotmimsync.readthedocs.io/Provision.html), I get 

> System.NotImplementedException: 'The method or operation is not implemented.'

errors when calling `ProvisionAsync` or `DeprovisionAsync` like here:

    using var client = new HttpClient();
    client.FillAuthentication(_configuration); // Extension method of mine to put credentials into the header.

    var serverOrchestrator = new WebClientOrchestrator(
        dbs.ServerEndpointUrl,
        client: client);

    var serverScope = await serverOrchestrator.GetServerScopeAsync();

    // Error occurs here.
    var newSchema = await serverOrchestrator.ProvisionAsync(
        SyncProvision.StoredProcedures |
        SyncProvision.Triggers |
        SyncProvision.TrackingTable);

The error occurs inside the call stack:

    at Dotmim.Sync.Web.Client.FancyCoreProvider.CreateConnection()

### My question

Is the Web client/proxy not capable of doing a provisioning/deprovisioning?

Or am I totally missing the point here?

**Comment by Mimetis** [comment]
Nop, because you're not supposed to provision the server from a client mobile application, for instance ;)

You best bet to provision "manually" the server side, is to create a `RemoteOrchestrator` (from a console app) and call the `ProvisionAsync` methods

**Comment by UweKeim** [comment]
Thanks, I'll try to get my head around this 😊.

Your mentioned console application should run on the server. Did I understand this correctly?

**Comment by Mimetis** [comment]
Nop, I mean "You should not provision a server from a web site" ;)
Just my thought on this.

But actually, you can create a Controller with a method that will internally call a RemoteOrchestrator that will do the job
But this controller MUST be admin only, from my point of view

**Comment by UweKeim** [comment]
In my scenario, I have two website databases that I intend to sync with your awesome library:

- One DB in a local Intranet
- One DB in a public [DMZ](https://en.wikipedia.org/wiki/DMZ_(computing)) Internet

Only the local Intranet can call the DMZ via Web API.

So I'm now writing a console app to run on the local Intranet to provision/deprovision the local Intranet DB.

And I'm writing a console app to run in the DMZ to provision/deprovision the public DMZ Internet DB.

I think, this might work.
