### ISSUE TITLE
table p doesnt exist

### ISSUE THREAD

**Issue by kmacute** [Mimetis/Dotmim.Sync#363]
Hi, im getting an error whenever I add this as dependency on my system

`        Dim allTables() As String = {
            "transaction00header",
            "transaction20xread",
            "transaction21xsalesdetail",
            "transaction22xtender",
            "transaction01details" ' I ALWAYS PRODUCE AND ERROR WHENEVER I ADD <-- THIS TABLE
        }`

![image](https://user-images.githubusercontent.com/48196638/99020617-f2e12f00-2599-11eb-8efd-c4abb2a1b916.png)

for the codesnippets
https://www.codepile.net/pile/DQx1n3jG.

Everything was fine except on one table that is always return table p doesn't exists

**Comment by Mimetis** [comment]
Can yiu share the schema of this table ? (transaction01details)

Did you add this table after a successful sync ? 
If so, did you tried to `DeprovisionAsync` then `ProvisionAsync` ?

**Comment by kmacute** [comment]
At the initial setup.. My process here is like
Initial synchronization was fine, nothing error, all datas from the server is copied,
but when the client made a new record, the table p doest exists where I dont have p table.

https://www.codepile.net/pile/PdebRmAE

**Comment by Mimetis** [comment]
Can you try a simple console application test, with only this table in the sync process, and see if it's working ?

**Comment by kmacute** [comment]
Okay please wait. will create simple console now

**Comment by kmacute** [comment]
It looks like the DMS doesnt support pre-existing trigger

When I deleted my existing trigger, everything works fine

[https://www.codepile.net/pile/aon8Dxem](url)

ps. im only using trigger to support live update

**Comment by Mimetis** [comment]
I'm sorry, I don't know MariaDB enough to figure out why you can't have more triggers?
**DMS** needs triggers to be able to run, otherwise no data will be tracked.

**Comment by kmacute** [comment]
Everything works fine now,including my triggers.. super thank you for this wonderful plugin :)
