### ISSUE TITLE
Sync fails with "A SqlParameter with ParameterName '@changeTable' is not contained by this SqlParameterCollection

### ISSUE THREAD

**Issue by REMjn832** [Mimetis/Dotmim.Sync#366]
I am having this same (#356) problem all of the sudden. I am using the 'SqlSyncChangeTrackingProvider' with 2 SQL-Server databases that I thought were working (synced fine when there was no data). I re-provisioned them (de-provision and re-provision) which worked. However, as soon as I add data to the server that should be synced to the client, this error will be thrown, and the sync fails. I can re-provision successfully still, and if I remove that row from the server, the sync succeeds again.

> "Dotmim.Sync.SyncException: A SqlParameter with ParameterName '@changeTable' is not contained by this SqlParameterCollection.\r\n ---> System.IndexOutOfRangeException: A SqlParameter with ParameterName '@changeTable' is not contained by this SqlParameterCollection.\r\n   at Microsoft.Data.SqlClient.SqlParameterCollection.GetParameter(String parameterName)\r\n   at Dotmim.Sync.SqlServer.Builders.SqlSyncAdapter.ExecuteBatchCommandAsync(DbCommand cmd, Guid senderScopeId, IEnumerable`1 applyRows, SyncTable schemaChangesTable, SyncTable failedRows, Int64 lastTimestamp, DbConnection connection, DbTransaction transaction)\r\n   at Dotmim.Sync.SyncAdapter.ApplyBulkChangesAsync(Guid localScopeId, Guid senderScopeId, SyncTable changesTable, Int64 lastTimestamp, List`1 conflicts, DbConnection connection, DbTransaction transaction)\r\n   at Dotmim.Sync.CoreProvider.ApplyChangesInternalAsync(SyncTable schemaTable, SyncContext context, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, DataRowState applyType, DatabaseChangesApplied changesApplied, CancellationToken cancellationToken, IProgress`1 progress)\r\n   at Dotmim.Sync.CoreProvider.ApplyChangesAsync(SyncContext context, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)\r\n   at Dotmim.Sync.LocalOrchestrator.ApplyChangesAsync(ScopeInfo scope, SyncSet schema, BatchInfo serverBatchInfo, Int64 clientTimestamp, Int64 remoteClientTimestamp, ConflictResolutionPolicy policy, CancellationToken cancellationToken, IProgress`1 progress)\r\n   --- End of inner exception stack trace ---\r\n   at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception)\r\n   at Dotmim.Sync.LocalOrchestrator.ApplyChangesAsync(ScopeInfo scope, SyncSet schema, BatchInfo serverBatchInfo, Int64 clientTimestamp, Int64 remoteClientTimestamp, ConflictResolutionPolicy policy, CancellationToken cancellationToken, IProgress`1 progress)\r\n   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress)\r\n   at OTC.DataAccess.CustomerPortal.SynchronizeDatabasesAsync()...

_Originally posted by @REMjn832 in https://github.com/Mimetis/Dotmim.Sync/issues/356#issuecomment-736019629_

**Comment by Mimetis** [comment]
we already have the issue opened, so I close this one
