### ISSUE TITLE
ERROR - Deleting Triggers on Client Deprovisioning

### ISSUE THREAD

**Issue by luc-cap** [Mimetis/Dotmim.Sync#369]
Hi,
   On a SQL Server connection i create a s SqlSyncProvider  and a LocalOrchestrator.

Calling   localOrchestrator.DeprovisionAsync()  I got Error:

Dotmim.Sync.SyncException: Sintassi non corretta in prossimità di 'BEGIN'.

There is an erron on

     Dotmim.Sync.SqlServer.Builders. SqlBuilderTrigger   Class

in method  DropTriggerAsync(..) .

The string builder  builds and invalid  IF  statement. 
Instead of  a BEGIN  END section,   builds a  BEGIN  BEGIN section,

**Comment by Mimetis** [comment]
It's complicated to figure out what the problem is, with the info you are sharing...
Can you please provide us a simple repro of the bug, using only the table that causes the bug ?

**Comment by luc-cap** [comment]
Yesterday I dowloaded and recompiled  sources. 
(Dotmim version  5.8-beta  date: 09-12-2020).

the function  DropTriggerAsync(...)  with namespace:   Dotmim.Sync.SqlServer.Builders.
simply  has an error.

the builder instead of   building a right sql command:

           IF ( condition)
           BEGIN
                    DROP trigger_name;
           END

now it is building:

           IF ( condition)
           BEGIN
                    DROP trigger_name;
           BEGIN

and fails because i can not find  END.

**Comment by Mimetis** [comment]
Thanks, I made the correction.
Seems i've disabled the tests on the provision / deprovision for some reasons ...

I made the fix, the tests, and publish a new beta version

**Comment by Mimetis** [comment]
This bug is resolved and will be published very soon in the next beta version `v0.6`
