### ISSUE TITLE
[Bug] getting strang errors with MSSQL.2016

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#37]
Hello, I'm trying to sync a database on MSSQL.2016 and get for example this error:

Web sync start
Error occured during TableChangesSelecting of type DataStore: The stored procedure "dbo.XEvent_selectchanges" has not been found.
Sync Ended. Press a key to start again, or Escapte to end

Though the table and XEvent_tracking are created in target database.

Shall I provide soure and database sample?

**Comment by Mimetis** [comment]
Maybe your provisionning database is not correct.
Are the stored procedure about XEvent exists ? (ie : XEvent_SelectChanges and so on ...) ?

if not, maybe you should try with a fresh starting database.

Or you can try to Unprovision then Provision again your database

See [https://mimetis.github.io/Dotmim.Sync/Provision](https://mimetis.github.io/Dotmim.Sync/Provision) for more about how to deal with provision / deprovision

**Comment by Mimetis** [comment]
Any update on this ?

**Comment by thefonzi** [comment]
after unprovision/Provision this works fine. 
I'm actually setting up a client, which does the neccesary steps after adding fields or tables to database. 
Will post soon some experiences

**Comment by Mimetis** [comment]
Ok so i will close this issue for now :) Feel free to re open it if necessary
