### ISSUE TITLE
How to sync with filter?

### ISSUE THREAD

**Issue by artem54325** [Mimetis/Dotmim.Sync#372]
How to sync by filter? 
So that the server sends only data matching the filter to the client?

For example, so that lines are sent to CompanyId when this client is synchronized.

**Comment by Mimetis** [comment]
https://dotmimsync.readthedocs.io/Filters.html

**Comment by artem54325** [comment]
@Mimetis But I don't have this constructor:

// add a SqlSyncProvider acting as the server hub
    services.AddSyncServer<SqlSyncProvider>(connectionString, setup, options);
