### ISSUE TITLE
Filters with schema get ignored?

### ISSUE THREAD

**Issue by Tuytje** [Mimetis/Dotmim.Sync#376]
When using a schema for our tables, we need to set all tables as "[SCHEMA].[TABLENAME]" (when making changes to direction, columns, ...), but the filter.addWhere has a seperate property for this:
```c#
            var filter = new SetupFilter("[TABLE]");
            filter.AddWhere("ColumnName", "[TABLE]", "paramName", "[SCHEMA]");
```

How do we need to define the scheme in this case? The table needs to be supplied twice, the schema once. I take it that the table name in this case is without the schema (2 times), since we need to supply it seperatly? 

I have tried different variations, but cannot get it to work. With the schema removed, and no other code touched it works as expected (filter is applied), but with the schema I can't get it to work. 

I couldn't find anything about filters + schema's in the documentation.

Anyone got this to work?

**Comment by Mimetis** [comment]
Did you resolve your issue ?

**Comment by Tuytje** [comment]
Sadly, no. 

I have removed the schema and have added a prefix to my tables instead. This means that both client and server have these prefixes, but it is ok in my case.
