### ISSUE TITLE
SQL Server performance issue

### ISSUE THREAD

**Issue by blenddata** [Mimetis/Dotmim.Sync#377]
I run the `Synchronization `method with these `SyncOptions`

```
UseBulkOperations = true,
BatchSize = 0 //which is default value, have tried 5000
```
and `SyncDirection=Bidirectional`, also I have filter on this table.

It runs `exec [dbo].[xxxx_selectrow] @ID=123456,@sync_scope_id=NULL`  consecutive on client side as you can see below:

![image](https://user-images.githubusercontent.com/50766350/102708111-b8b02f00-42b5-11eb-9954-77b12c9d1111.png)

Which has lock on table. Other tables are ok but this one is impacting sync process.
Is there any settings to help me out?

**Comment by blenddata** [comment]
I believe this is because of conflicts, it may detect filters as conflicts !!!

**Comment by Mimetis** [comment]
Indeed the `xxxx_selectrow` stored proc is used for **each** conflict you have in your database

If you're not sure why you have this conflict occuring, you can for example make a new sync on the client with `ReinitializeWithUpload` or `Reinitialize`
Look here for more info : https://dotmimsync.readthedocs.io/Synchronize.html#synctype

IF you think it's a bug from the DMS fx and there is no reason you have conflicts here, please send me a repro of the bug, if you can

**Comment by blenddata** [comment]
> Indeed the `xxxx_selectrow` stored proc is used for **each** conflict you have in your database
> 
> If you're not sure why you have this conflict occuring, you can for example make a new sync on the client with `ReinitializeWithUpload` or `Reinitialize`
> Look here for more info : https://dotmimsync.readthedocs.io/Synchronize.html#synctype
> 
> IF you think it's a bug from the DMS fx and there is no reason you have conflicts here, please send me a repro of the bug, if you can

I have 40K row on server  with no modification only deletes are allowed, with applied filter I have ~2k on client side. 
~38k rows on server are detected as conflict so I think its a bug, I will create a repo for that.

**Comment by Mimetis** [comment]
Any news on that ?
