### ISSUE TITLE
Use range to manage auto increment primary keys

### ISSUE THREAD

**Issue by NischalPV** [Mimetis/Dotmim.Sync#38]
Hello Mimetis,
It would be better if we could provide a reference column from the table to be synced on which synchronization would work. For e.g. we are generating a unique column in addition to auto generated primary key in the table.
Let me explain the scenario why we need this;

Lets say we have three offline databases A, B and C which needs to be synchronized to a central database X.

When we add data to a table, it will auto generate data in primary key column. so offline databases A, B and C will generate their own data in a table and these data needs to union and stored in database X, which generates its own primary key data in the column.

So, when we sync the data from either A, B or C to database X, it overwrites the data on X with the same primary key. So Lets say there is a table City in all the databases and the first row in each database is as follows:
ID 1 in A: NYC
ID 1 in B: Sydney
ID 1 in C: Delhi

Now every time I sync the data from the last one to sync will overwrite the data at ID 1 in X.

What i need is
ID 1 in X: NYC
ID 2 in X: Sydney
ID 3 in X: Delhi

Kindly suggest a work around or the already implemented feature in your marvellous project.

Thanks,
Nischal

**Comment by Mimetis** [comment]
Hi Nischal;

First of all, thanks for your feedback, I appreciate it!
And sorry for the response delay (Hollidays ... :) )

The *Identity Aut Increment column as Primary keys* is a big problem when we talk about synchronization.

There are several solutions to deal with that kind of behavior, in *theory*

**Sql Server** manages auto inc. with what I call *range areas* of primary keys:
* Master  : From 1 000 000 000 	to N
* Client 1: From 1 000 000 	to 1 999 999
* Client 2: From 2 000 000	to 2 999 999
* Client N: From N 000 000	to N 999 999

When any client has reach its upperbound limit, you can reallocate a new range area.

Your solution consists to add a new column as an unique column could be a potential solution but, there are many problems.
Actually the ID key will never be the same on each client and the server. It' a big concern actually, as you mention.

I will work on this (but any help will be appreciate !! :) ) to provide a solution, involving the range solution. 
Is this solution could be a good solution for you ?

Seb
