### ISSUE TITLE
CS7069: Reference to the type "MySqlConnectionStringBuilder" declare that its defined in "MySqlConnector", but can't be found

### ISSUE THREAD

**Issue by Technooz** [Mimetis/Dotmim.Sync#382]
Hi! Im making a app for android using xamarin and c#, I've made a simple app that can interact with a MySQL database, everything is working correctly, but i'm trying to implement an offline database (sqlite) and I saw Dotmim.Sync, i'm trying to use but no successful tries. Could you guys give me a hand please?

`using System;
using System.IO;
using SQLite;
using Dotmim.Sync;
using Dotmim.Sync.MySql;
using Dotmim.Sync.Sqlite;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using MySqlConnector;`

`public static async Task SyncDB()
        {
            MySQLCon db = new MySQLCon();
            var strong = db.CriarConexaoString();

            SQLitePCL.Batteries_V2.Init();
            // Sql Server provider, the "server" or "hub".
            MySqlSyncProvider serverProvider = new MySqlSyncProvider(strong);
            // Sqlite Client provider acting as the "client"
            SqliteSyncProvider clientProvider = new SqliteSyncProvider(sqlitePath);

            // Tables involved in the sync process:
            var tables = new string[] { "Clientes" };

            // Sync agent
            SyncAgent agent = new SyncAgent(clientProvider, serverProvider, tables);
            var progress = new SynchronousProgress<ProgressArgs>(args => Console.WriteLine($"{args.Context.SyncStage}:{args.Message}"));
            var result = await agent.SynchronizeAsync(progress);
            Console.WriteLine(result);
        }`

**Comment by Mimetis** [comment]
From a mobile perspective, you should use a proxy server, exposing your my sql database through a web api
Check this : https://dotmimsync.readthedocs.io/Web.html

**Comment by Technooz** [comment]
> From a mobile perspective, you should use a proxy server, exposing your my sql database through a web api
> Check this : https://dotmimsync.readthedocs.io/Web.html

Is this a fix? If yes, is there any other way of fixing this without the proxy server?

**Comment by Technooz** [comment]
Apparently changing Dotmin.Sync.Mysql to SQLServer fixed the issue, now I just need to make dotmin work

**Comment by Mimetis** [comment]
It's not a fix, only Sqlite is allowed from within a mobile app

**Comment by Technooz** [comment]
Ok, couldn't get SQL Server working with Mysql, I have to use the MySqlSyncProvider but I can't, it gives me the CS7069 error..
The app im developing is private so there is no problem in not using an WEB API on it, is there a way to solve the CS7069 error? I just need this working please

**Comment by Mimetis** [comment]
Only SQLite is allowed on a mobile app, you need to use the web api technic if u want to sync to any server
