### ISSUE TITLE
Index was outside the bounds of the array - Xamarin - MySQL

### ISSUE THREAD

**Issue by Technooz** [Mimetis/Dotmim.Sync#385]
I've been trying to use dotmim.sync but couldnt get it working..
I'm getting no errors on debug but when I build the release and test it on a phone, it gives me "Index was outside the bounds of the array".

**Defining some connections and classes for accesses**
`MySQLCon msql = new MySQLCon();
        static string relativePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "minhaDatabase.db3");
        public static string connectionPath = $"Data Source={relativePath}";
        public static SqliteConnection conSQLite = new SqliteConnection(connectionPath);
`

**Sync method, it gets called when I press a button on another class**
`public async Task SyncDB()
        {
            string con = msql.CriarConexaoString();
            MySqlConnection conMySQL = new MySqlConnection(con);
            string connectionString = conMySQL.ConnectionString;
            conMySQL.Open();
            conSQLite.Open();

            SQLitePCL.Batteries_V2.Init();
            // Sql Server provider, the "server" or "hub".
            MySqlSyncProvider serverProvider = new MySqlSyncProvider(connectionString);

            // Sqlite Client provider acting as the "client"
            SqliteSyncProvider clientProvider = new SqliteSyncProvider(connectionPath);

            // Tables involved in the sync process:
            string[] tables = new string[] { "Clientes", "Login" };

            // Sync agent
            SyncAgent agent = new SyncAgent(clientProvider, serverProvider, tables);
            await agent.SynchronizeAsync();
        }
    }
`

![image](https://user-images.githubusercontent.com/76762909/103433842-178b7780-4bd7-11eb-8eab-cfe72840dfb9.png)

ON DEBUG - When I press the button and synchronize the databases and try switching to offline mode, sqlite throws an "Clientes table non existant" so its not syncing apparently.

ON RELEASE- When I press the button I get the "Index was outside the bounds of the array"

**Comment by Technooz** [comment]
Ok I made SQLITE create the two first tables (Clientes and Login) they get created normally and I can see them on DDMS 
![image](https://user-images.githubusercontent.com/76762909/103443102-8948dd00-4c3a-11eb-8a33-adec9a23fdd4.png)

When I click to sync scope_info and sqlite_sequence get created apparently 
![image](https://user-images.githubusercontent.com/76762909/103443113-a1206100-4c3a-11eb-9239-7d4e458d4d53.png)
but my table isnt filled by the MySql server data

**Comment by Technooz** [comment]
I tried writing some data to the SQLITE database and then tried to synchronize, the sqlite data on Clientes wasnt sent to the MySQL server

**Comment by Mimetis** [comment]
Direct connection from a xamarin application to MySql IS NOT supported for now
You need to use the Web Api method

**Comment by Technooz** [comment]
Hey Mimetis, I'm sorry for making you mad or stressing you, I made the last thread but didn't really understand what you said before, I've searched a bit more and now I see that you really can't do that, sorry.

I'm now trying to make my application work with the web api
