### ISSUE TITLE
Syncing does nothing - Xamarin - MySQL with webapi and SQLITE

### ISSUE THREAD

**Issue by Technooz** [Mimetis/Dotmim.Sync#386]
When I try syncing, dotmim creates the sqlite with only scope_info table

Sync Method:
```
public async Task SyncDB()
        {
            try
            {
                MySQLCon msql = new MySQLCon();
                string con = msql.CriarConexaoString();
                MySqlConnection conMySQL = new MySqlConnection(con);
                conSQLite = new SqliteConnection(connectionPath);
                conSQLite.Open();
                conMySQL.Open();

                SQLitePCL.Batteries_V2.Init();
                // Database script used for this sample : https://github.com/Mimetis/Dotmim.Sync/blob/master/CreateAdventureWorks.sql 

                var serverOrchestrator = new WebClientOrchestrator("http://technoo.cf:5200/api/sync");
                // Second provider is using plain old Sql Server provider, relying on triggers and tracking tables to create the sync environment
                var clientProvider = new SqliteSyncProvider(conSQLite.ConnectionString);

                // Creating an agent that will handle all the process
                var agent = new SyncAgent(clientProvider, serverOrchestrator);

                var s1 = await agent.SynchronizeAsync();
                Console.WriteLine(s1);
            }
            catch(Exception ex)
            {
                throw ex; 
            }
        }
```
Button handling
![image](https://user-images.githubusercontent.com/76762909/103485931-c64ad600-4dd8-11eb-8f4d-6eb2f6e0043c.png)

My website: 
![image](https://user-images.githubusercontent.com/76762909/103485938-d1056b00-4dd8-11eb-939f-d9f668f8127b.png)

DEBUG - When I click the sync button, it doesnt give me any errors or anything

Updates: 
RELEASE - When clicking the sync button, it gives me "<div>Server is configured to Production mode. No options displayed.</div>" using https://technoo.cf/api/sync
RELEASE -  When clicking the sync button, it gives me "No route to host" using https://technoo.cf:5200/api/sync

**Comment by Mimetis** [comment]
Please, stop opening issues, until you start using a web api system in place of direct connexion with MySql

Direct connection from a xamarin application to MySql IS NOT supported for now
You need to use the Web Api method

**Comment by Mimetis** [comment]
Your code is really **unclear**
Please use the **Markdown** format to show your issue here.

I have edited your post to have something more readable.

Regarding Xamarin, you will find here a sample application using **Sqlite** on the Xamarin application, and **Sql Server** (or **MySql**) on the server side.

Please; look at the code carefully, you will see that everything is pretty simple if you are following the instructions

- Sync Through Web API : https://dotmimsync.readthedocs.io/Web.html
- Android Emulator Networking : https://developer.android.com/studio/run/emulator-networking
- Xamarin application sample : [XamAppSync.zip](https://github.com/Mimetis/Dotmim.Sync/files/5763975/XamAppSync.zip)

![image](https://user-images.githubusercontent.com/4592555/103521213-aa970c80-4e78-11eb-9d9d-99a296103784.png)

![image](https://user-images.githubusercontent.com/4592555/103521267-c13d6380-4e78-11eb-9cf0-78ea2702449a.png)

**Comment by Technooz** [comment]
Hey, thank you for not simply closing my thread again by seeing my name and having patience with me. 
I'm sorry for the other threads I created, I wasnt understanding what you were explaining..
I'm now using the WebApi, but my website shows "Server is configured to production mode. No options displayed", I think this is why I'm not able to communicate with the **WebApi** on my server, if I test the **Asp.Net app (WebApi)** on localhost, it works fine but I still cant sync using 127.0.0.1 on my **Xamarin** app.

- My Asp.Net app is already at the server, it has everything correct, Startup, Program, Controller, etc.
- My Xamarin app should work fine too, everything is correct, using WebApi, etc.

**Comment by Mimetis** [comment]
The page showing the properties on the server, are **sensitive** data.
That's why you have this message, when deploying your Web API in **Production** mode.

It's not related at all with your problem.
Having this message is just something like "Hey you are in production mode, just dont show this page sensitive info to users :)"

**Comment by Technooz** [comment]
Oh okay, but you have any idea of why i'm not able to communicate with the server?

On release build of my Xamarin app, I get the an error, and the Server is configured to production mode. No options displayed"Server is configured to production mode. No options displayed" message is displayed as an error.

**Comment by Mimetis** [comment]
No idea
Are you able to access the web api from a mobile web browser ?

**Comment by Technooz** [comment]
Let me test here, one second

**Comment by Mimetis** [comment]
you need to debug the application, see what going on, on the server side, with some break points I guess
Same on the client, and see what kind of inner exceptions you get

**Comment by Technooz** [comment]
Error when using no port on technoo.cf: 
![image](https://user-images.githubusercontent.com/76762909/103557669-4e40e680-4e92-11eb-9808-074dd2f67599.png)

No error when using port on technoo.cf, but no changes to the small text:
![image](https://user-images.githubusercontent.com/76762909/103557854-906a2800-4e92-11eb-9a17-04cd1622d217.png)

**Comment by Mimetis** [comment]
I won't be able to help you here
If it's working from a console app, I guess you have a limitation somewhere

You should maybe start with a really simple sync, using a simple database with one table and one line in it, and see if it's working
If not, you have a communication prob somewhere

**Comment by Technooz** [comment]
Ok, i'll try with a simple database

**Comment by Technooz** [comment]
Oh wait.

```Error Dotmim.Sync.SyncException: Table Login does not have any primary key.
   at Dotmim.Sync.Web.Client.HttpRequestHandler.HandleSyncError(HttpResponseMessage response, ISerializerFactory serializerFactory)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.ProcessRequestAsync[U](HttpClient client, String baseUri, Byte[] data, HttpStep step, Guid sessionId, String scopeName, ISerializerFactory serializerFactory, IConverter converter, Int32 batchSize, CancellationToken cancellationToken)
   at Dotmim.Sync.Web.Client.WebClientOrchestrator.EnsureSchemaAsync(CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress)
   at DataTest.Program.SyncDB() in C:\Users\Technoo\source\repos\DataTest\Program.cs:line 33

O C:\Users\Technoo\source\repos\DataTest\bin\Debug\net5.0\DataTest.exe (processo 8308) foi encerrado com o código 0.
Para fechar o console automaticamente quando a depuração parar, habilite Ferramentas -> Opções -> Depuração -> Fechar o console automaticamente quando a depuração parar.
Pressione qualquer tecla para fechar esta janela...```

**Boom, found the error probably, no primary key on login table**

**Comment by Technooz** [comment]
Fixed my app after 4 days..
It was 3 problems.

1. I was using direct connection to mysql, instead of WebApi.
2. Forgot a damn primary key on one of the tables.
3. I was using the wrong hostname.
Hope this can help someone
