### ISSUE TITLE
Error MariaDB

### ISSUE THREAD

**Issue by maverickgol** [Mimetis/Dotmim.Sync#387]
Dotmim.Sync.SyncException: 'Can't create table `8248233101_db0000000002`.`productos` (errno: 150 "Foreign key constraint is incorrectly formed")'
![image](https://user-images.githubusercontent.com/65125359/103569134-c4464d00-4e94-11eb-938e-074e91996cfb.png)

**Comment by Mimetis** [comment]
It's probably because the table and columns names concatenation is too long
Can you share the schema table ?

**Comment by maverickgol** [comment]
> It's probably because the table and columns names concatenation is too long
> Can you share the schema table ?

CREATE TABLE `productos` (
  `productosid` bigint(20) NOT NULL AUTO_INCREMENT,
  `productocodigo` varchar(21) NOT NULL DEFAULT '   ',
  `barras` varchar(40) NOT NULL DEFAULT '',
  `alterno1` varchar(21) NOT NULL DEFAULT '',
  `descripcion` varchar(150) DEFAULT '',
  `sri_tipos_ivas_codigo` varchar(1) NOT NULL DEFAULT '2',
  `productos_lineasid` bigint(20) NOT NULL DEFAULT 1,
  `productos_categoriasid` bigint(20) NOT NULL DEFAULT 1,
  `productos_subcategoriasid` int(11) NOT NULL DEFAULT 1,
  `productos_subgruposid` int(11) NOT NULL DEFAULT 1,
  `estado` tinyint(4) NOT NULL DEFAULT 1,
  `venta` tinyint(4) NOT NULL DEFAULT 1,
  `existenciastotales` decimal(20,8) NOT NULL DEFAULT 0.00000000,
  `reservado` decimal(20,8) NOT NULL DEFAULT 0.00000000,
  `controlnegativos` tinyint(4) NOT NULL DEFAULT 1,
  `controlprecios` tinyint(4) NOT NULL DEFAULT 1,
  `servicio` tinyint(4) NOT NULL DEFAULT 0,
  `bien` tinyint(4) NOT NULL DEFAULT 0,
  `series` tinyint(4) NOT NULL DEFAULT 0,
  `vehiculos` tinyint(4) DEFAULT 0,
  `cuentacontable_inventarios` varchar(30) NOT NULL DEFAULT '',
  `cuentacontable_ventas` varchar(30) NOT NULL DEFAULT '',
  `cuentacontable_costo` varchar(30) NOT NULL DEFAULT '',
  `sri_codigo_impuestos` varchar(6) NOT NULL DEFAULT '312',
  `fichatecnica` varchar(1000) DEFAULT '',
  `costoactual` decimal(20,8) NOT NULL DEFAULT 0.00000000,
  `costoestandar` decimal(20,8) NOT NULL DEFAULT 0.00000000,
  `costoultimacompra` decimal(20,8) NOT NULL DEFAULT 0.00000000,
  `fechaultimacompra` date DEFAULT NULL,
  `observaciones` varchar(1000) DEFAULT '0',
  `unidadinterna` int(11) NOT NULL DEFAULT 1,
  `unidadsuperior` int(11) DEFAULT 0,
  `unidadinferior` int(11) DEFAULT 0,
  `unidadcompra` int(11) NOT NULL DEFAULT 1,
  `unidadventa` int(11) NOT NULL DEFAULT 1,
  `proveedoresid_asignado` bigint(20) DEFAULT 0,
  `proveedoresid_ultimo` bigint(20) DEFAULT 0,
  `factorsuperior` decimal(16,4) NOT NULL DEFAULT 0.0000,
  `factorinferior` decimal(16,4) NOT NULL DEFAULT 0.0000,
  `subsidio` decimal(20,8) NOT NULL DEFAULT 0.00000000,
  `tonelaje` decimal(7,3) DEFAULT 0.000,
  `pasajeros` tinyint(3) unsigned DEFAULT 0,
  `cilindraje` decimal(7,3) DEFAULT 0.000,
  `marca` varchar(25) DEFAULT '',
  `modelo` varchar(25) DEFAULT '',
  `origen` varchar(15) DEFAULT '',
  `lado` varchar(15) DEFAULT '',
  `medidas` varchar(50) DEFAULT '',
  `ice_codigo` varchar(26) NOT NULL DEFAULT '',
  `ice_porcentaje` decimal(5,2) NOT NULL DEFAULT 0.00,
  `ice_valor` decimal(38,6) NOT NULL DEFAULT 0.000000,
  `peso_neto` decimal(14,4) NOT NULL DEFAULT 0.0000,
  `peso_bruto` decimal(14,4) NOT NULL DEFAULT 0.0000,
  `venta_peso` tinyint(4) NOT NULL DEFAULT 0,
  `materiaprima` tinyint(4) NOT NULL DEFAULT 0,
  `compuesto` tinyint(4) NOT NULL DEFAULT 0,
  `ecommerceid` int(11) NOT NULL DEFAULT 0,
  `ecommerce_estado` tinyint(3) unsigned NOT NULL DEFAULT 1,
  `fechacreacion` datetime(3) NOT NULL,
  `usuariocreacion` varchar(25) NOT NULL DEFAULT '',
  `fechamodificacion` datetime(3) DEFAULT NULL,
  `usuariomodificacion` varchar(25) NOT NULL DEFAULT '',
  PRIMARY KEY (`productosid`),
  UNIQUE KEY `productocodigo` (`productocodigo`),
  KEY `WDIDX1609200937143` (`barras`),
  KEY `WDIDX1609200937144` (`alterno1`),
  KEY `WDIDX1609200937145` (`descripcion`),
  KEY `WDIDX1609200937146` (`sri_tipos_ivas_codigo`),
  KEY `WDIDX1609200937147` (`productos_lineasid`),
  KEY `WDIDX1609200937148` (`productos_categoriasid`),
  KEY `WDIDX1609200938149` (`productos_subcategoriasid`),
  KEY `WDIDX1609200938150` (`productos_subgruposid`),
  KEY `WDIDX1609200938151` (`estado`),
  KEY `WDIDX1609200938152` (`venta`),
  KEY `WDIDX1609200938153` (`servicio`),
  KEY `WDIDX1609200938154` (`bien`),
  KEY `WDIDX1609200938155` (`series`),
  KEY `WDIDX1609200938156` (`vehiculos`),
  KEY `WDIDX1609200938157` (`cuentacontable_inventarios`),
  KEY `WDIDX1609200938158` (`sri_codigo_impuestos`),
  KEY `WDIDX1609200938159` (`unidadinterna`),
  KEY `WDIDX1609200938160` (`unidadsuperior`),
  KEY `WDIDX1609200938161` (`unidadinferior`),
  KEY `WDIDX1609200938162` (`unidadcompra`),
  KEY `WDIDX1609200938163` (`unidadventa`),
  KEY `WDIDX1609200938164` (`proveedoresid_asignado`),
  KEY `WDIDX1609200938165` (`proveedoresid_ultimo`),
  KEY `WDIDX1609200938166` (`materiaprima`),
  KEY `WDIDX1609200938167` (`compuesto`),
  KEY `WDIDX1609200938168` (`ecommerceid`),
  CONSTRAINT `productos_ibfk_109` FOREIGN KEY (`productos_subcategoriasid`) REFERENCES `productos_subcategoria` (`productos_subcategoriasid`),
  CONSTRAINT `productos_ibfk_110` FOREIGN KEY (`productos_subgruposid`) REFERENCES `productos_subgrupo` (`productos_subgruposid`),
  CONSTRAINT `productos_ibfk_44` FOREIGN KEY (`productos_lineasid`) REFERENCES `productos_lineas` (`productos_lineasid`),
  CONSTRAINT `productos_ibfk_45` FOREIGN KEY (`productos_categoriasid`) REFERENCES `productos_categorias` (`productos_categoriasid`),
  CONSTRAINT `productos_ibfk_46` FOREIGN KEY (`sri_tipos_ivas_codigo`) REFERENCES `sri_tipos_ivas` (`sri_tipos_ivas_codigo`),
  CONSTRAINT `productos_ibfk_49` FOREIGN KEY (`sri_codigo_impuestos`) REFERENCES `sri_impuestos` (`sri_codigo_impuestos`),
  CONSTRAINT `productos_ibfk_52` FOREIGN KEY (`unidadinterna`) REFERENCES `medidas` (`medidasid`),
  CONSTRAINT `productos_ibfk_53` FOREIGN KEY (`unidadventa`) REFERENCES `medidas` (`medidasid`),
  CONSTRAINT `productos_ibfk_54` FOREIGN KEY (`unidadcompra`) REFERENCES `medidas` (`medidasid`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

**Comment by Mimetis** [comment]
I'm able to sync this single table with a client type `sqlite`
I guess the problem is coming from the **Foreign Keys** tables...

`productos_subcategoria`, 
`productos_subgrupo`, 
`productos_lineas`, 
`productos_categorias`, 
`sri_tipos_ivas` ,
`sri_impuestos`, 
`medidas`

**Comment by maverickgol** [comment]
> Puedo sincronizar esta única tabla con un tipo de cliente `sqlite`
> , supongo que el problema proviene de las tablas de **claves** externas ...
> 
> `productos_subcategoria`,
> `productos_subgrupo`,
> `productos_lineas`,
> `productos_categorias`,
> `sri_tipos_ivas`,
> `sri_impuestos`,
> `medidas`

Te paso la DB Completa para que le pruebes por favor

[8248233101_db0000000001.zip](https://github.com/Mimetis/Dotmim.Sync/files/5766461/8248233101_db0000000001.zip)

**Comment by Mimetis** [comment]
I need the `SyncOptions` and `SyncSetup` you are using

**Comment by maverickgol** [comment]
> Necesito el `SyncOptions`y `SyncSetup`estas usando

using Dotmim.Sync;
using Dotmim.Sync.MariaDB;
using System;
using System.Threading.Tasks;


namespace Sincronizar
{
    class Program
    {
        private static string serverConnectionString = $"Server=127.0.01;Port=5588;Database=8248233101_db0000000001;Uid=root;Pwd=Alfayomega1232*; Convert Zero Datetime=true; CharSet=utf8;";
        private static string clientConnectionString = $"Server=127.0.01;Port=5588;Database=8248233101_db0000000002;Uid=root;Pwd=Alfayomega1232*; Convert Zero Datetime=true; CharSet=utf8;";

        static async Task Main(string[] args)
        {
            await SynchronizeAsync();
        }


        private static async Task SynchronizeAsync()
        {
            // Database script used for this sample : https://github.com/Mimetis/Dotmim.Sync/blob/master/CreateAdventureWorks.sql 

            // Create 2 Sql Sync providers
            // First provider is using the Sql change tracking feature. Don't forget to enable it on your database until running this code !
            // For instance, use this SQL statement on your server database : ALTER DATABASE AdventureWorks  SET CHANGE_TRACKING = ON  (CHANGE_RETENTION = 10 DAYS, AUTO_CLEANUP = ON)  
            // Otherwise, if you don't want to use Change Tracking feature, just change 'SqlSyncChangeTrackingProvider' to 'SqlSyncProvider'
            var serverProvider = new MariaDBSyncProvider(serverConnectionString);

            // Second provider is using plain old Sql Server provider, relying on triggers and tracking tables to create the sync environment
            var clientProvider = new MariaDBSyncProvider(clientConnectionString);

            // Tables involved in the sync process:
            var tables = new string[] {"medidas", "productos_subcategoria", "productos_subgrupo", "productos_lineas", "productos_categorias", "sri_tipos_ivas", "sri_impuestos"};

            // Creating an agent that will handle all the process
            var agent = new SyncAgent(clientProvider, serverProvider, tables);
         


                // Launch the sync process
                var s1 = await agent.SynchronizeAsync();
                // Write results
                Console.WriteLine(s1);



           
        }
    }
}

**Comment by Mimetis** [comment]
Please edit your post, and use correct markdown formatting

**Comment by maverickgol** [comment]
> Please edit your post, and use correct markdown formatting

No entendí a que se refiere

**Comment by Mimetis** [comment]
Please speak english.
Consider reading this : https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by maverickgol** [comment]
Sent you the project
[Sincronizar.zip](https://github.com/Mimetis/Dotmim.Sync/files/5766546/Sincronizar.zip)

**Comment by maverickgol** [comment]
Sent you the project

[Sincronizar.zip](https://github.com/Mimetis/Dotmim.Sync/files/5766561/Sincronizar.zip)

**Comment by Mimetis** [comment]
You have some problems with the provisioning of your database
Start from a fresh new database without any tracking tables or stored proc generated from `DMS`

You can use `DeprovisionAsync` if you want, or start with a previous version of your database

I Used this script (where I removed all the tracking / stored procedures , triggers)

[8248233101_db0000000001.txt](https://github.com/Mimetis/Dotmim.Sync/files/5766613/8248233101_db0000000001.txt)

And the snippet of the code i'm using

```
// Create 2 Sql Sync providers
var serverProvider = new MariaDBSyncProvider(DBHelper.GetMariadbDatabaseConnectionString("8248233101_db0000000001"));
var clientProvider = new MariaDBSyncProvider(DBHelper.GetMariadbDatabaseConnectionString("8248233101_db0000000002"));
//var clientProvider = new SqliteSyncProvider("dedee.db");

var tables = new string[] { "medidas", "productos_subcategoria", "productos_subgrupo","productos_lineas","productos_categorias", "sri_tipos_ivas", "sri_impuestos" };

var setup = new SyncSetup(tables);

var options = new SyncOptions();
// Creating an agent that will handle all the process
var agent = new SyncAgent(clientProvider, serverProvider, options, setup);

// Using the Progress pattern to handle progession during the synchronization
var progress = new SynchronousProgress<ProgressArgs>(s =>
{
    Console.ForegroundColor = ConsoleColor.Green;
    Console.WriteLine($"{s.Context.SyncStage}:\t{s.Message}");
    Console.ResetColor();
});

do
{
    // Console.Clear();
    Console.WriteLine("Sync Start");
    try
    {
        var r = await agent.SynchronizeAsync(SyncType.Reinitialize, progress);
        // Write results
        Console.WriteLine(r);
    }
    catch (Exception e)
    {
        Console.WriteLine(e.Message);
    }


    //Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");
} while (Console.ReadKey().Key != ConsoleKey.Escape);

Console.WriteLine("End");
```

![image](https://user-images.githubusercontent.com/4592555/103575467-135ea300-4ed2-11eb-9842-47d1fe2f78e6.png)

**Comment by maverickgol** [comment]
The products table is missing in the code

**Comment by maverickgol** [comment]
> You have some problems with the provisioning of your database
> Start from a fresh new database without any tracking tables or stored proc generated from `DMS`
> 
> You can use `DeprovisionAsync` if you want, or start with a previous version of your database
> 
> I Used this script (where I removed all the tracking / stored procedures , triggers)
> 
> [8248233101_db0000000001.txt](https://github.com/Mimetis/Dotmim.Sync/files/5766613/8248233101_db0000000001.txt)
> 
> And the snippet of the code i'm using
> 
> ```
> // Create 2 Sql Sync providers
> var serverProvider = new MariaDBSyncProvider(DBHelper.GetMariadbDatabaseConnectionString("8248233101_db0000000001"));
> var clientProvider = new MariaDBSyncProvider(DBHelper.GetMariadbDatabaseConnectionString("8248233101_db0000000002"));
> //var clientProvider = new SqliteSyncProvider("dedee.db");
> 
> var tables = new string[] { "medidas", "productos_subcategoria", "productos_subgrupo","productos_lineas","productos_categorias", "sri_tipos_ivas", "sri_impuestos" };
> 
> var setup = new SyncSetup(tables);
> 
> var options = new SyncOptions();
> // Creating an agent that will handle all the process
> var agent = new SyncAgent(clientProvider, serverProvider, options, setup);
> 
> // Using the Progress pattern to handle progession during the synchronization
> var progress = new SynchronousProgress<ProgressArgs>(s =>
> {
>     Console.ForegroundColor = ConsoleColor.Green;
>     Console.WriteLine($"{s.Context.SyncStage}:\t{s.Message}");
>     Console.ResetColor();
> });
> 
> do
> {
>     // Console.Clear();
>     Console.WriteLine("Sync Start");
>     try
>     {
>         var r = await agent.SynchronizeAsync(SyncType.Reinitialize, progress);
>         // Write results
>         Console.WriteLine(r);
>     }
>     catch (Exception e)
>     {
>         Console.WriteLine(e.Message);
>     }
> 
> 
>     //Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");
> } while (Console.ReadKey().Key != ConsoleKey.Escape);
> 
> Console.WriteLine("End");
> ```
> 
> ![image](https://user-images.githubusercontent.com/4592555/103575467-135ea300-4ed2-11eb-9842-47d1fe2f78e6.png

**Comment by maverickgol** [comment]
> You have some problems with the provisioning of your database
> Start from a fresh new database without any tracking tables or stored proc generated from `DMS`
> 
> You can use `DeprovisionAsync` if you want, or start with a previous version of your database
> 
> I Used this script (where I removed all the tracking / stored procedures , triggers)
> 
> [8248233101_db0000000001.txt](https://github.com/Mimetis/Dotmim.Sync/files/5766613/8248233101_db0000000001.txt)
> 
> And the snippet of the code i'm using
> 
> ```
> // Create 2 Sql Sync providers
> var serverProvider = new MariaDBSyncProvider(DBHelper.GetMariadbDatabaseConnectionString("8248233101_db0000000001"));
> var clientProvider = new MariaDBSyncProvider(DBHelper.GetMariadbDatabaseConnectionString("8248233101_db0000000002"));
> //var clientProvider = new SqliteSyncProvider("dedee.db");
> 
> var tables = new string[] { "medidas", "productos_subcategoria", "productos_subgrupo","productos_lineas","productos_categorias", "sri_tipos_ivas", "sri_impuestos" };
> 
> var setup = new SyncSetup(tables);
> 
> var options = new SyncOptions();
> // Creating an agent that will handle all the process
> var agent = new SyncAgent(clientProvider, serverProvider, options, setup);
> 
> // Using the Progress pattern to handle progession during the synchronization
> var progress = new SynchronousProgress<ProgressArgs>(s =>
> {
>     Console.ForegroundColor = ConsoleColor.Green;
>     Console.WriteLine($"{s.Context.SyncStage}:\t{s.Message}");
>     Console.ResetColor();
> });
> 
> do
> {
>     // Console.Clear();
>     Console.WriteLine("Sync Start");
>     try
>     {
>         var r = await agent.SynchronizeAsync(SyncType.Reinitialize, progress);
>         // Write results
>         Console.WriteLine(r);
>     }
>     catch (Exception e)
>     {
>         Console.WriteLine(e.Message);
>     }
> 
> 
>     //Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");
> } while (Console.ReadKey().Key != ConsoleKey.Escape);
> 
> Console.WriteLine("End");
> ```
> 
> ![image](https://user-images.githubusercontent.com/4592555/103575467-135ea300-4ed2-11eb-9842-47d1fe2f78e6.png)



The products table is missing in the code
