### ISSUE TITLE
Dotmim.Sync.SyncException: 'Table parts does not have any primary key.' -- Is it possible to sync two databases right away without checking primary keys?

### ISSUE THREAD

**Issue by knightmoverchan** [Mimetis/Dotmim.Sync#389]
![image](https://user-images.githubusercontent.com/12180132/103718971-f5dd2680-5002-11eb-85e6-f3aa305e55a5.png)

**Comment by knightmoverchan** [comment]
Is it possible to sync two databases right away without checking primary keys?

**Comment by Mimetis** [comment]
Nop, a primary key is mandatory to be able to track each row in the tracking table

**Comment by AvaSharkawy** [comment]
Is this still mandatory to get sync done?
Is there anyway to define custome criteria to select, update, delete and track rows based on custom expression?
I have a table that is working as many to many to relationship that has only two columns
I want to define that all operations made in this table to be based on these two columns
So when sync trying to update or do something make a query where [Column1] AND [Column2]
