### ISSUE TITLE
How to make a filter if the column is out of sync?

### ISSUE THREAD

**Issue by artem54325** [Mimetis/Dotmim.Sync#396]
How to make filtering, if during synchronization this column should not be synchronized?
And
How to set different values of a certain column for different clients during synchronization?

**Comment by Mimetis** [comment]
I guess you can use `CustomWhere` clause : https://dotmimsync.readthedocs.io/Filters.html#the-addcustomwhere-method

Never tested it, let me know if it's working as expected

**Comment by artem54325** [comment]
@Mimetis, How can I set a value in parameters in a table when syncing?

**Comment by Mimetis** [comment]
https://dotmimsync.readthedocs.io/Filters.html#example

You can set the parameters, through the agent:

``` cs
var agent = new SyncAgent(clientProvider, serverProvider, setup);

if (!agent.Parameters.Contains("City"))
    agent.Parameters.Add("City", "Toronto");

```

**Comment by artem54325** [comment]
@Mimetis, I mean something else. I mean how to set parameters in client to sync if parameters in client are null

**Comment by artem54325** [comment]
@Mimetis  It's just that when adding parameters in filters during synchronization, in some tables, new columns appear, how to add values to these columns?

**Comment by Mimetis** [comment]
https://github.com/Mimetis/Dotmim.Sync/discussions/391#discussioncomment-299575
