### ISSUE TITLE
Init database in xamarin

### ISSUE THREAD

**Issue by tothmartonjeno** [Mimetis/Dotmim.Sync#401]
Hi,
Task: 50 android mobile app (developed in xamarin) sync the app's sqlite database with sql server through web api.
I tried in console app: the init sqlite database is created within two minutes. (Size: 34 tables, all snaphost files 15-20 mb.)
In xamarin begins the sync but cannot finish after 30 minutes. (5 table version is done within 30 seconds.)
To init a database is required rarely: after install the app or upgrade new version.

Can I solve this problem in the following way?
1. init sqlite database in console app on the server
2. each mobile client app download this sqlite database
3. sync_scope_id will be the same on each device, so `update scope_info set sync_scope_id = {new guid}` in app's sqlite db
4. client init db is done, continue sync process using Dotmim.Sync

**Comment by Mimetis** [comment]
I never tested it, but I think it could work
Let me know if it's working as expected !

**Comment by tothmartonjeno** [comment]
It works so far.
But it doesn't work the following:
Table: 4 integer columns
Change tracking: 60.000 records for delete, 60.000 records for insert.
In Xamarin the sync cannot finish. Is it possible? (Stored proc runs for 2 sec.)
(200 row sync works.)

**Comment by tothmartonjeno** [comment]
I checked, 0.6.0 version solved both problems. This issue can be closed.
