### ISSUE TITLE
RequestTimeout syncing through Azure web app

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#404]
I refer to the DMS docs for [Timeout](https://dotmimsync.readthedocs.io/Timeout.html#server-side)

Apparently this has no effect as timeout for an Azure web app is fixed at 230 secs. Is there a workaround for this, other than running  IIS in a vm?

Or have I misundertood?

**Comment by Mimetis** [comment]
Did you tried to replace the web.config generated by Azure by the one from the DMS doc ? (or at least modifying it and add timeout value ?)

**Comment by VagueGit** [comment]
Thank you for the prompt response @Mimetis.  I increased the timeout on the client and in web.config as shown in the docs but sync times out after 4 mins.

I've been really impressed with the speed with which DMS syncs 35k customers and 89k orders within the 4 min Azure timeout. It only times out when I add syncing 133k payments.

We are currently exploring DMS and Azure with test data. Our production app runs hundreds of companies databases using other technologies on other hosts. We like DMS and if the Azure issue can't be resolved, we can move the DMS api and the databases to other hosts.

**Comment by Mimetis** [comment]
I assume you're using the `Snapshots` feature to reduce the first sync step ?
Usually, this is where the timeout occurs.

**Comment by VagueGit** [comment]
Not using snapshots. Will investigate and post back. Thank you for the tip.

**Comment by Mimetis** [comment]
Ok, Usually, during the first sync, the server needs to generate a lot of things.
That's why Snapshots are really useful to prepare everything "in advance".
Let me know

**Comment by VagueGit** [comment]
Don't snapshots assume the existing local (SQLite) database, or the existing server database (SQL Azure) were previously in use?

In our use case, both the local and server databases are new. Our production app uses different technologies on the client and the server.

**Comment by Mimetis** [comment]
I dont know if it can fit to you, but just in case, it could be a potential solution :)

**Comment by VagueGit** [comment]
For snapshots to work for us we would have to migrate legacy data directly to the server then sync back to the client. Is that correct?

**Comment by Mimetis** [comment]
I dont know how your architecture is constructed
Snaspshots just take the server data at T1 and prepare the batchs
You should see the doc and try, I guess

**Comment by VagueGit** [comment]
One of the production versions of this app uses Realm Cloud which is not compatible with DMS. Also our experience is that Realm Cloud can only reliably serve small volumes of data through a GraphQL api. So it isn't practical to upgrade data from Realm Cloud to Azure SQL Database. We must do the upgrade on the client side and then sync.

Also upgrade on the client is faster. It gets our customers back in business quicker.

We have other hosts that we are happy with. We will move our DMS api and some test data out of Azure for some perf testing. I'll post back here with the results.

Thanks @Mimetis  for your help.

**Comment by VagueGit** [comment]
I've had advice from a couple of cloud providers that extending request timeout is difficult due to load balancing. We've been testing DMS with a host that has a 10 min request timeout and have better results, but 10 mins is still marginal.

As we are doing the initial sync from the client to the server, we are able to recurse the object hierarchy and break sync up ie upgrade Customers then sync, upgrade orders then sync, upgrade payments then sync. This seems to work.

Where necessary we can break down the initial upgrade further ... every thousand rows or so. This reduces the server load, but increases downtime for our customers. The task now is to optimise this process.

We could therefore potentially still use Azure, but downtime will be longer for our customers for that initial sync. That's a business decision rather than a technical one.

**Comment by vunder** [comment]
@VagueGit for initial sync you can create separate copy of the app and on client, when local db has no sync scope use this "Initializing endpoint

**Comment by VagueGit** [comment]
Forgive me @vunder but I don't understand. Customers download our app from our website. What do you mean by a separate copy of the app?

**Comment by vunder** [comment]
@VagueGit Sorry for lack in description
Server-side has two sync endpoints (two server app instances): first is for regular sync, second is for initial sync with long rquest timeout
In client you before sync you can detect that you're starting initial sync by checking scope:
```csharp
    var scope = await agent.LocalOrchestrator.GetClientScopeAsync(cts.Token, progress);
    if (scope.IsNewScope)
    {
        //re-create serverOrchestrator and agent with new endpoint
    }
```
In this case server app instances are the same, except timeout value

**Comment by VagueGit** [comment]
Thank you @vunder. Unfortunately the cloud hosts we deal with limit the request timeout. We can't control request timeout.

**Comment by vunder** [comment]
@VagueGit other option - change `BatchSize` value. That allows you to split sync within several requests. You can calculate it.
I used `agent.LocalOrchestrator.GetEstimatedChangesCountAsync()` to get local changes and then `ContainerTable.GetRowSizeFromDataRow` to find out max row size. And then used calculated values to configure sync

**Comment by VagueGit** [comment]
Batch size is 2000. We've had it as low as 500. That reduces the size of each batch but the request still times out if syncing 100k rows from the client to the server.
