### ISSUE TITLE
The sample didn't work for me.

### ISSUE THREAD

**Issue by sarwary** [Mimetis/Dotmim.Sync#406]
here is my code. I am not sure what's the issue.
using System;
using Dotmim.Sync;
using Dotmim.Sync.Sqlite;
using Dotmim.Sync.SqlServer;

namespace SyncSqlite
{
    class Program
    {

        static void Main(string[] args)
        {
            sync();

        }

        async public static int sync()
        {

            try
            {
                // Sql Server provider, the "server" or "hub".
                SqlSyncProvider serverProvider = new SqlSyncProvider(
                    @"Data Source=.;Initial Catalog=AdventureWorks;Integrated Security=true;");

                // Sqlite Client provider acting as the "client"
                SqliteSyncProvider clientProvider = new SqliteSyncProvider("advworks.db");

                // Tables involved in the sync process:
                var tables = new string[] {"ProductCategory", "ProductDescription", "ProductModel", "Product", "ProductModelProductDescription",
                           "Address", "Customer", "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail" };

                // Sync agent
                SyncAgent agent = new SyncAgent(clientProvider, serverProvider, tables);
           
                do
                {
                    var result = await agent.SynchronizeAsync();
                    Console.WriteLine(result);
                 

                } while (Console.ReadKey().Key != ConsoleKey.Escape);

            }
            catch (Exception ex)
            {
                Console.WriteLine("some issue");
                Console.WriteLine(ex.Message);
            }

            return 1;
        }
    }
}

**Comment by Mimetis** [comment]
What is the exception?

**Comment by sarwary** [comment]
here is what it gives in console:

SyncSqlite.exe (process 137080) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

**Comment by Mimetis** [comment]
Does not help
Please try to improve your debug session.

**Comment by Mimetis** [comment]
I will soon close this issue since we can't go further until we have more information
