### ISSUE TITLE
BulkUpdate and BulkDelete procedures not created during server provisioning

### ISSUE THREAD

**Issue by DeakinWilson** [Mimetis/Dotmim.Sync#407]
Hi

I'm running on SQL Server with ChangeTracking.  Running a  provision on the server is not creating the BulkUpdate or BulkDelete procedures.  All other procedures seem to create ok, there is no error thrown. 

The issue is visible when trying to do a deprovision and the an error is thrown that the BulkDelete procedure doesn't exist.   I have also tried manually removing all procedures and the two _scope_info_* tables and re-running a provision.  The provision runs and doesn't throw any errors, but immediately followed by deprovision does throw the "BulkUpdate procedure missing" error.

Client syncing also fails as a result of the procedures not being there. 

What other information can I provide you to assist in debugging?

**Comment by DeakinWilson** [comment]
I've solved the issue.  I had to also remove the User Defined Table Types, then re-provision.  All worked again.

DotMimSync is awesome!

**Comment by Mimetis** [comment]
Hey @DeakinWilson.
Thanks for the feedback.
This is actually a bug from the `v0.5` version. 
Are you facing this issue with this version `v0.5` or do you experience it with the new beta version of `v0.6` ?

**Comment by DeakinWilson** [comment]
@Mimetis - I'm using the 0.5 version.  Sounds like I should upgrade to the new beta of 0.6
