### ISSUE TITLE
Current master fails build

### ISSUE THREAD

**Issue by vunder** [Mimetis/Dotmim.Sync#409]
A lot of errors while building after merge V0.6
`Dotmim.Sync.PostgreSql` is full of errors
WebServer sample contains unknown `WriteServerScopeAsync` method

**Comment by Mimetis** [comment]
Indeed, these 2 projects are *Unloaded* in my solutions.
The *unloaded* flag is not part of the `.sln`. That's why it's not preserved on Github.
I've removed them from the solution. Should be fine now.

Let me know

**Comment by vunder** [comment]
Works fine now

**Comment by vunder** [comment]
@Mimetis Console sample still references `Dotmim.Sync.PostgreSql`
