### ISSUE TITLE
[Bug] Deprovision does not work correctly

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#41]
Please try the following steps: 
- Setup a MasterDB with some tables and a blank SlaveDB.
- Run Sync with a defined table list.
- now run deprovision with same table list on masterdb and slavedb
- now repeat step 2: run Sync. You will get out of index Errors or Messages of missing procedures

**Comment by Mimetis** [comment]
Did you use the same `SyncAgent` ?  
Anyway, I will look into it.

Ths a lot @thefonzi  !

**Comment by Mimetis** [comment]
I made some tests.

Can you try Something like that:

```csharp
// Create a new agent
agent = new SyncAgent(clientProvider, serverProvider, syncConfiguration);

// Overwrite configuration to ensure database schema will apply again
agent.DatabaseApplying += (s, e) => e.OverwriteConfiguration = true;

// Syn
var session = await agent.SynchronizeAsync();

```

**Comment by marjanoh2** [comment]
this code does not work with the new version. Is there a replacement for this?
 agent.DatabaseApplying += (s, e) => e.OverwriteConfiguration = true;

**Comment by Mimetis** [comment]
Depends on what you want to do ? (Deprovisionning ?)
