### ISSUE TITLE
Invalid column name for the scop_info table fields

### ISSUE THREAD

**Issue by HunarAA** [Mimetis/Dotmim.Sync#412]
When I use the framework to sync two SQL Server databases I am getting invalid column name for the columns sync_scope_id, sync_scope_name, and so on...

**Comment by Mimetis** [comment]
Do you have a table to sync with this kind of columns name ?

**Comment by HunarAA** [comment]
To clarify both my tables are SQL Server, one is **local DB** and the other one is on **SQL Server Management Studio**. In my databases I don't have this kind of table, but the sync process have created a table named "**scope_info**" on the server, this table contains all the mentioned columns by the error. The process also created a table with the same name but different column names inside the client DB

**Comment by Mimetis** [comment]
The Server database should have 2 tables only : `scope_info_history` and `scope_info_server`
The Client database should have 1 table only : `scope_info`

Once you have designed a database as `Server`, you can't go back and design it as `Client`

You can have multiple `Client`s databases, but only 1 `Server` database

**Comment by HunarAA** [comment]
Thank you Mr. for your knowledge, I have swapped the client and server provider link and the problem has been solved. I don't know where was the problem because the server db is now the **local db** (that is inside visual studio) while the other one becomes client (the one that is on SQL Server Management Studio).
