### ISSUE TITLE
Error While Synching

### ISSUE THREAD

**Issue by PardeepBhandari** [Mimetis/Dotmim.Sync#413]
Hi

I am getting Error while syncing

this type name text is not supported

Can you explain reason.

same code is working for other database syncing. 

Synchronization done. 
	Total changes  uploaded: 0
	Total changes  downloaded: 1189825 
	Total changes  applied: 1189825 
	Total resolved conflicts: 0
	Total duration :0:8:56.300 

structure of both source databases are same.
I use blank database for destination.

**Comment by Mimetis** [comment]
The type text is not supported.
You need to use varchar(max) instead
