### ISSUE TITLE
Multiple Client

### ISSUE THREAD

**Issue by PardeepBhandari** [Mimetis/Dotmim.Sync#418]
Hi 
I am using sql server for source database and two client one is a desktop application 
and other is xamarin app. Server database have 7 tables and in two tables there are 100 above column.
it is working perfectly fine for desktop application to sync data remotely from server database.
although it took 23 minutes for 270000 rows.

but on xamarin app i don't need full information can i sync these tables with just selected column 15 each
because i am facing issue like operation cancel after 15 minutes or so.

Thanks.

**Comment by Mimetis** [comment]
You need to work with **Scopes**.

BE careful, you need to take care of what will be generated on the Server.
Be sure that:
- On both scopes, **Triggers** and **Tracking Tables** are the **Same**
- On each scopes, **Stored Procedures** are **NOT** the **Same**.
   - Mainly because scope 1 will have all columns in the stored procedures and scope 2 will only have few columns

Basically, on the server side, create **2** `SyncSetup` with differente **Scope Name**:

``` cs
// Setup 1 : Contains all tables, with All Columns
var setup = new SyncSetup(new string[] { "Address", "Customer", "CustomerAddress", 
            "SalesOrderHeader", "SalesOrderDetail" });

//  Add stored procedure prefix
setup.StoredProceduresPrefix = "all";
setup.StoredProceduresSuffix = "";

// Add this Setup as a scoped sync
services.AddSyncServer<SqlSyncProvider>(connectionString, "All", setup);

// Setup 2 : This setup contains fewer tables with fewer columns
var setup2 = new SyncSetup(new string[] { "Address", "Customer", "CustomerAddress" });
// Add only few columns
setup2.Tables["Customer"].Columns.AddRange(new string[] { "CustomerID", "FirstName", "LastName" });

// Add a DIFFERENT stored prefix
setup2.StoredProceduresPrefix = "restricted";
setup2.StoredProceduresSuffix = "";

// Add this second setup with ANOTHER scope name
services.AddSyncServer<SqlSyncProvider>(connectionString, "Fewer", setup);
```

Desktop Application will call **ONLY** scope name `All`:

```cs
var agent = new SyncAgent(clientProvider1, webClientOrchestrator, "All");
```

Xamarin Application will call **ONLY** scope name `Fewer`:

```cs
var agent = new SyncAgent(clientProvider2, webClientOrchestrator, "Fewer");
```

Make sense ?

**Comment by PardeepBhandari** [comment]
Hi

I am getting error Required property 'bc' not found in JSON. Path '', line 1, position 1. while syncing
from xamarin with web api.

I use following code for pc to pc syncing without using Web API

 Dim tables = New String() {"Series", "Accounts", "Item", "LotNo", "Transactions", "ItemDataFooter", "ItemData"}
        Dim ServerIP As String = TxtRemoteServer.Text
        Dim DBName As String = TxtRemoteDB.Text
        Dim DBUserID As String = TxtRemoteUserID.Text
        Dim DBPassword As String = TxtRemotePassword.Text

        Try
            serverConnectionString = $"Data Source={ TxtRemoteServer.Text};timeout=120; Min Pool Size=1; Max Pool Size=100; Initial Catalog={TxtRemoteDB.Text} ;Persist Security Info=True;User ID={TxtRemoteUserID.Text};Password={TxtRemotePassword.Text} ;"
            clientConnectionString = $"Data Source={ TxtClientServer.Text }; timeout=120; Min Pool Size=1; Max Pool Size=100; Initial Catalog={TxtClientDB.Text} ; Persist Security Info=True; User ID={TxtClientUserID.Text}; Password={TxtClientPassword.Text} ;"

            Dim serverProvider As SqlSyncProvider = New SqlSyncProvider(serverConnectionString)
            Dim syncoptions = New SyncOptions() With {.BatchSize = Val(TxtBuffer.Text)}

            Dim Setup = New SyncSetup(tables)
            Setup.StoredProceduresPrefix = "all"
            Setup.StoredProceduresSuffix = ""

            Dim clientProvider As SqlSyncProvider = New SqlSyncProvider(clientConnectionString)
            Dim agent As SyncAgent = New SyncAgent(clientProvider, serverProvider, syncoptions, Setup, "All")

            Dim syncContext As Object
            
            syncContext = Await agent.SynchronizeAsync(Dotmim.Sync.Enumerations.SyncType.Normal)
           
            TxtMessage.Text = syncContext.ToString()

            because when i use webapi then i get error Task Cancelled.

            I setup web api like following

            var connectionString = CommonFunctions.ConnectionString;

            var syncoptions = new SyncOptions()
            {
                SnapshotsDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Snapshots"),
                BatchSize = 200000
            };

            var setup = new SyncSetup(new string[] { "Series", "Accounts", "Item", "LotNo", "Transactions", "ItemDataFooter", "ItemData" });
            setup.StoredProceduresPrefix = "all";
            setup.StoredProceduresSuffix = "";
            services.AddSyncServer<SqlSyncProvider>(connectionString, "All", setup, syncoptions);

            var setup2 = new SyncSetup(new string[] { "Series", "Accounts", "Item", "LotNo", "Transactions", "ItemDataFooter", "ItemData" });
            setup2.Tables[0].Columns.AddRange(new string[] { "ID", "Series", "Status" });
            setup2.Tables[1].Columns.AddRange(new string[] { "ID", "Account", "AddressLine1", "AddressLine2", "State", "City", "Status" });
            setup2.Tables[2].Columns.AddRange(new string[] { "ID", "Item", "Status" });
            setup2.Tables[3].Columns.AddRange(new string[] { "ID", "LotNo", "Item", "MRP", "ExpiryDate", "PurchaseRate", "TradeRate", "Status" });
            setup2.Tables[4].Columns.AddRange(new string[] { "ID", "Series", "Invoice", "Account", "Particular", "Narration", "Dr", "Cr", "Status" });
            setup2.Tables[5].Columns.AddRange(new string[] { "ID", "Voucher_Date", "Series", "TotalAmount", "TAX", "Discount", "GrandTotal", "Status" });
            setup2.Tables[6].Columns.AddRange(new string[] { "ID", "Voucher_Date", "Series", "InvoiceNo", "QtyIn", "QtyOut", "FreeQtyIn", "FreeQtyOut", "Price", "PlusMinus", "Amount", "Status" });
            setup2.StoredProceduresPrefix = "restricted";
            setup2.StoredProceduresSuffix = "";
            services.AddSyncServer<SqlSyncProvider>(connectionString, "Fewer", setup2, syncoptions);

On Xamarin I use 

string APIString = eMuneem.CommonFunctions.ServerAPIUrl + "sync?Server=" + result.ServerIP + "&DBName=" + result.DBName + "&UserID=" + result.DBUserID + "&Password=" + result.DBPassword + "&CustomFilter=ID > 0 And ID < 100";

                var handler = new HttpClientHandler { AutomaticDecompression = DecompressionMethods.None };
                var client = new HttpClient(handler) { Timeout = TimeSpan.FromMinutes(30) };

                var RemoteServerProvider = new WebClientOrchestrator(APIString, null, null, client);
                var clientProvider = new SqliteSyncProvider(App.LocalDbFullPath);
                var progress = new SynchronousProgress<ProgressArgs>(args => ValidationMessage = ($"{args.Context.SyncStage}:{args.Message}"));

                var clientOptions = new SyncOptions {  BatchSize=200000 };
                var agent = new SyncAgent(clientProvider, RemoteServerProvider, clientOptions, "Fewer");

                // Launch the sync process
                var s1 = await agent.SynchronizeAsync();

                // See results
                ValidationMessage = s1.ToString();

**Comment by Mimetis** [comment]
Please format your message correctly, using markdown properly
thanks

**Comment by PardeepBhandari** [comment]
Hi

I am getting error Required property 'bc' not found in JSON. Path '', line 1, position 1. while syncing
from xamarin with web api.

I use following code for pc to pc syncing without using Web API
because when i use webapi for syncing all tables all columns then i get error Task Cancelled (same error i got whan i was using web api and xamarin app syncing all table all column).

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Dim tables = New String() {"Series", "Accounts", "Item", "LotNo", "Transactions", "ItemDataFooter", "ItemData"}
Dim ServerIP As String = TxtRemoteServer.Text
Dim DBName As String = TxtRemoteDB.Text
Dim DBUserID As String = TxtRemoteUserID.Text
Dim DBPassword As String = TxtRemotePassword.Text

Try
serverConnectionString = $"Data Source={ TxtRemoteServer.Text};timeout=120; Min Pool Size=1; Max Pool Size=100; Initial Catalog={TxtRemoteDB.Text} ;Persist Security Info=True;User ID={TxtRemoteUserID.Text};Password={TxtRemotePassword.Text} ;"
clientConnectionString = $"Data Source={ TxtClientServer.Text }; timeout=120; Min Pool Size=1; Max Pool Size=100; Initial Catalog={TxtClientDB.Text} ; Persist Security Info=True; User ID={TxtClientUserID.Text}; Password={TxtClientPassword.Text} ;"

Dim serverProvider As SqlSyncProvider = New SqlSyncProvider(serverConnectionString)
Dim syncoptions = New SyncOptions() With {.BatchSize = Val(TxtBuffer.Text)}

Dim Setup = New SyncSetup(tables)
Setup.StoredProceduresPrefix = "all"
Setup.StoredProceduresSuffix = ""

Dim clientProvider As SqlSyncProvider = New SqlSyncProvider(clientConnectionString)
Dim agent As SyncAgent = New SyncAgent(clientProvider, serverProvider, syncoptions, Setup, "All")
Dim syncContext As Object
syncContext = Await agent.SynchronizeAsync(Dotmim.Sync.Enumerations.SyncType.Normal)
TxtMessage.Text = syncContext.ToString()

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

I setup web api like following


var connectionString = CommonFunctions.ConnectionString;
var syncoptions = new SyncOptions()
{
	SnapshotsDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Snapshots"),
	BatchSize = 200000
};

var setup = new SyncSetup(new string[] { "Series", "Accounts", "Item", "LotNo", "Transactions", "ItemDataFooter", "ItemData" });
setup.StoredProceduresPrefix = "all";
setup.StoredProceduresSuffix = "";
services.AddSyncServer<SqlSyncProvider>(connectionString, "All", setup, syncoptions);

var setup2 = new SyncSetup(new string[] { "Series", "Accounts", "Item", "LotNo", "Transactions", "ItemDataFooter", "ItemData" });
setup2.Tables[0].Columns.AddRange(new string[] { "ID", "Series", "Status" });
setup2.Tables[1].Columns.AddRange(new string[] { "ID", "Account", "AddressLine1", "AddressLine2", "State", "City", "Status" });
setup2.Tables[2].Columns.AddRange(new string[] { "ID", "Item", "Status" });
setup2.Tables[3].Columns.AddRange(new string[] { "ID", "LotNo", "Item", "MRP", "ExpiryDate", "PurchaseRate", "TradeRate", "Status" });
setup2.Tables[4].Columns.AddRange(new string[] { "ID", "Series", "Invoice", "Account", "Particular", "Narration", "Dr", "Cr", "Status" });
setup2.Tables[5].Columns.AddRange(new string[] { "ID", "Voucher_Date", "Series", "TotalAmount", "TAX", "Discount", "GrandTotal", "Status" });
setup2.Tables[6].Columns.AddRange(new string[] { "ID", "Voucher_Date", "Series", "InvoiceNo", "QtyIn", "QtyOut", "FreeQtyIn", "FreeQtyOut", "Price", "PlusMinus", "Amount", "Status" });
setup2.StoredProceduresPrefix = "restricted";
setup2.StoredProceduresSuffix = "";
services.AddSyncServer<SqlSyncProvider>(connectionString, "Fewer", setup2, syncoptions);

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


On Xamarin App I use 

string APIString = eMuneem.CommonFunctions.ServerAPIUrl + "sync?Server=" + result.ServerIP + "&DBName=" + result.DBName + "&UserID=" + result.DBUserID + "&Password=" + result.DBPassword + "&CustomFilter=ID > 0 And ID < 100";

var handler = new HttpClientHandler { AutomaticDecompression = DecompressionMethods.None };
var client = new HttpClient(handler) { Timeout = TimeSpan.FromMinutes(30) };

var RemoteServerProvider = new WebClientOrchestrator(APIString, null, null, client);
var clientProvider = new SqliteSyncProvider(App.LocalDbFullPath);
var progress = new SynchronousProgress<ProgressArgs>(args => ValidationMessage = ($"{args.Context.SyncStage}:{args.Message}"));

var clientOptions = new SyncOptions {  BatchSize=200000 };
var agent = new SyncAgent(clientProvider, RemoteServerProvider, clientOptions, "Fewer");

// Launch the sync process
var s1 = await agent.SynchronizeAsync();

// See results
ValidationMessage = s1.ToString();

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 

Thanks

**Comment by Mimetis** [comment]
You should see others messages and see how they are formatted using markdown.
Here is a documentation, especially on code : https://gist.github.com/michaeljaggers/e4b4a94c5caa3ce5788c47f838149b37#code

for instance, encapsulating your code within ` ``` cs ` at the beginning and ` ``` ` at the end will produce:

``` cs
var clientOptions = new SyncOptions { BatchSize=200000 };
var agent = new SyncAgent(clientProvider, RemoteServerProvider, clientOptions, "Fewer");
```

Here is the markdown code I've written:
![image](https://user-images.githubusercontent.com/4592555/106860685-039ad000-66c5-11eb-8a9a-0b3fc6d2302b.png)

Now you have everything you need to format your message correctly ! :)

**Comment by PardeepBhandari** [comment]
Hi

I am getting error Required property 'bc' not found in JSON. Path '', line 1, position 1. while syncing
from xamarin with web api.

I use following code for pc to pc syncing without using Web API
because when i use webapi for syncing all tables all columns then i get error Task Cancelled (same error i got whan i was using web api and xamarin app syncing all table all column).

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Dim tables = New String() {"Series", "Accounts", "Item", "LotNo", "Transactions", "ItemDataFooter", "ItemData"}
Dim ServerIP As String = TxtRemoteServer.Text
Dim DBName As String = TxtRemoteDB.Text
Dim DBUserID As String = TxtRemoteUserID.Text
Dim DBPassword As String = TxtRemotePassword.Text

Try
serverConnectionString = $"Data Source={ TxtRemoteServer.Text};timeout=120; Min Pool Size=1; Max Pool Size=100; Initial Catalog={TxtRemoteDB.Text} ;Persist Security Info=True;User ID={TxtRemoteUserID.Text};Password={TxtRemotePassword.Text} ;"
clientConnectionString = $"Data Source={ TxtClientServer.Text }; timeout=120; Min Pool Size=1; Max Pool Size=100; Initial Catalog={TxtClientDB.Text} ; Persist Security Info=True; User ID={TxtClientUserID.Text}; Password={TxtClientPassword.Text} ;"

Dim serverProvider As SqlSyncProvider = New SqlSyncProvider(serverConnectionString)
Dim syncoptions = New SyncOptions() With {.BatchSize = Val(TxtBuffer.Text)}

Dim Setup = New SyncSetup(tables)
Setup.StoredProceduresPrefix = "all"
Setup.StoredProceduresSuffix = ""

Dim clientProvider As SqlSyncProvider = New SqlSyncProvider(clientConnectionString)
Dim agent As SyncAgent = New SyncAgent(clientProvider, serverProvider, syncoptions, Setup, "All")
Dim syncContext As Object
syncContext = Await agent.SynchronizeAsync(Dotmim.Sync.Enumerations.SyncType.Normal)
TxtMessage.Text = syncContext.ToString()

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

I setup web api like following


var connectionString = CommonFunctions.ConnectionString;
var syncoptions = new SyncOptions()
{
	SnapshotsDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Snapshots"),
	BatchSize = 200000
};

var setup = new SyncSetup(new string[] { "Series", "Accounts", "Item", "LotNo", "Transactions", "ItemDataFooter", "ItemData" });
setup.StoredProceduresPrefix = "all";
setup.StoredProceduresSuffix = "";
services.AddSyncServer<SqlSyncProvider>(connectionString, "All", setup, syncoptions);

var setup2 = new SyncSetup(new string[] { "Series", "Accounts", "Item", "LotNo", "Transactions", "ItemDataFooter", "ItemData" });
setup2.Tables[0].Columns.AddRange(new string[] { "ID", "Series", "Status" });
setup2.Tables[1].Columns.AddRange(new string[] { "ID", "Account", "AddressLine1", "AddressLine2", "State", "City", "Status" });
setup2.Tables[2].Columns.AddRange(new string[] { "ID", "Item", "Status" });
setup2.Tables[3].Columns.AddRange(new string[] { "ID", "LotNo", "Item", "MRP", "ExpiryDate", "PurchaseRate", "TradeRate", "Status" });
setup2.Tables[4].Columns.AddRange(new string[] { "ID", "Series", "Invoice", "Account", "Particular", "Narration", "Dr", "Cr", "Status" });
setup2.Tables[5].Columns.AddRange(new string[] { "ID", "Voucher_Date", "Series", "TotalAmount", "TAX", "Discount", "GrandTotal", "Status" });
setup2.Tables[6].Columns.AddRange(new string[] { "ID", "Voucher_Date", "Series", "InvoiceNo", "QtyIn", "QtyOut", "FreeQtyIn", "FreeQtyOut", "Price", "PlusMinus", "Amount", "Status" });
setup2.StoredProceduresPrefix = "restricted";
setup2.StoredProceduresSuffix = "";
services.AddSyncServer<SqlSyncProvider>(connectionString, "Fewer", setup2, syncoptions);

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


On Xamarin App I use 

string APIString = eMuneem.CommonFunctions.ServerAPIUrl + "sync?Server=" + result.ServerIP + "&DBName=" + result.DBName + "&UserID=" + result.DBUserID + "&Password=" + result.DBPassword + "&CustomFilter=ID > 0 And ID < 100";

var handler = new HttpClientHandler { AutomaticDecompression = DecompressionMethods.None };
var client = new HttpClient(handler) { Timeout = TimeSpan.FromMinutes(30) };

var RemoteServerProvider = new WebClientOrchestrator(APIString, null, null, client);
var clientProvider = new SqliteSyncProvider(App.LocalDbFullPath);
var progress = new SynchronousProgress<ProgressArgs>(args => ValidationMessage = ($"{args.Context.SyncStage}:{args.Message}"));

var clientOptions = new SyncOptions {  BatchSize=200000 };
var agent = new SyncAgent(clientProvider, RemoteServerProvider, clientOptions, "Fewer");

// Launch the sync process
var s1 = await agent.SynchronizeAsync();

// See results
ValidationMessage = s1.ToString();

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 

Thanks

**Comment by MaTToX3** [comment]
I have upgraded to version 0.6.0 today and getting the same error:

```
Dotmim.Sync.SyncException: Required property 'bc' not found in JSON. Path '', line 1, position 1.
  at Dotmim.Sync.Web.Client.HttpRequestHandler.HandleSyncError (System.Net.Http.HttpResponseMessage response, Dotmim.Sync.Serialization.ISerializerFactory serializerFactory) [0x0022f] in <b7eccb9974e74dd193f6a7e66f943841>:0 
  at Dotmim.Sync.Web.Client.HttpRequestHandler.ProcessRequestAsync[U] (System.Net.Http.HttpClient client, System.String baseUri, System.Byte[] data, Dotmim.Sync.Web.Client.HttpStep step, System.Guid sessionId, System.String scopeName, Dotmim.Sync.Serialization.ISerializerFactory serializerFactory, Dotmim.Sync.Serialization.IConverter converter, System.Int32 batchSize, System.Threading.CancellationToken cancellationToken) [0x0060b] in <b7eccb9974e74dd193f6a7e66f943841>:0 
  at Dotmim.Sync.Web.Client.WebClientOrchestrator.GetSnapshotAsync (Dotmim.Sync.SyncSet schema, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00247] in <b7eccb9974e74dd193f6a7e66f943841>:0 
  at Dotmim.Sync.SyncAgent.SynchronizeAsync (Dotmim.Sync.Enumerations.SyncType syncType, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress) [0x00d1c] in <bbea59c32d1f48e1b08b2225d94a7e6b>:0 
```

**Comment by PardeepBhandari** [comment]
Hi

after downgrade to 5.7 it is running fine 
Please remove bug from 0.6.0 version.

Thanks

**Comment by Mimetis** [comment]
Can you try with the last beta version `v0.6.1` ?
https://www.nuget.org/packages/Dotmim.Sync.Core/0.6.1-beta-0504 

@PardeepBhandari Please don't use a `BatchSize` of **200 000**. That means each file will be around **200 MB** !!
A correct value should between `2 000` and max `10 000`.

**Comment by MaTToX3** [comment]
Thank you for a quick update!

Sadly, in my case at least, the error persists.

**Comment by Mimetis** [comment]
Can you test with a clean new client database and a clean server (without anything provisioned) ?

**Comment by MaTToX3** [comment]
I did that - fresh client database and fresh server.

**Comment by Mimetis** [comment]
oh wow, that's not normal
You mean, with a Server database WITHOUT any sync stored procedure, tracking tables or config tables, you still have the issue on `'bc' not found in JSON` ?

**Comment by MaTToX3** [comment]
That's correct - I created a completely new database (with my tables) but nothing, related to Sync is there - until I run the sync.

Also, just for fun, I did a quick test with version 0.6.0-beta-0491 and there is a different error: I get a `Dotmim.Sync.HttpResponseContentException`.

**Comment by Mimetis** [comment]
Can you share your database schema ? and the code you're using ?

**Comment by MaTToX3** [comment]
Sorry, I am not allowed to.

However, I will try to reproduce the issue over the weekend and share you the whole repository when I am done.

**Comment by PardeepBhandari** [comment]
Thanks
