### ISSUE TITLE
System.TypeLoadException with Pomelo.EntityFrameworkCore.MySql

### ISSUE THREAD

**Issue by debugjan** [Mimetis/Dotmim.Sync#420]
Hi, 
I use Dotmim.Sync.MariaDB (0.6.0) , Dotmim.Sync.Web.Server (0.6.0) and Pomelo.EntityFrameworkCore.MySql (5.0.0-alpha.2) in an ASP.NET Core 5 project. I followed the tutorial https://dotmimsync.readthedocs.io/Web.html. When i navigate to _/api/sync_ a _System.TypeLoadException_ is thrown: 
```
 System.TypeLoadException: Could not load type 'MySql.Data.MySqlClient.MySqlConnectionStringBuilder' from assembly 'MySqlConnector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92'.
         at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
         at System.Reflection.RuntimeConstructorInfo.get_Signature()
         at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
[...]
 at Dotmim.Sync.Web.Server.WebServerManager.HandleRequestAsync(HttpContext context, CancellationToken cancellationToken, IProgress`1 progress)
at SyncController.Get() 
[...]
```

When i remove Pomelo.EntityFrameworkCore.MySql the exception is not thrown. Please let me know if the bug doesn't belong here . Thanks in advance

**Comment by Mimetis** [comment]
You need to downgrade Pomelo.EntityFrameworkCore.MySql to version 3.2.4

**Comment by debugjan** [comment]
Thank you for you reply. Because i am using .NET Core 5, i can not use Pomelo.EntityFrameworkCore.MySql 3.2.4 which requires Microsoft.EntityFrameworkCore.Relational to be >= 3.1.8 & < 5.0.0. 
Is there any other possible solution because i want to stick to .net core 5 ?

**Comment by Mimetis** [comment]
Nop; There is a conflict between ASP .Net 5 and ASP .Net Core 3.1 (especially with MySqlConnector used by DotMim.Sync and Pomelo)
I'm sorry, until a new solution appears, you can't use last version of Pomelo.
I think I will probably migrate everything to .Net 5, but not until the release of .Net 5
If you want to go a little bit deeper on "why"; I've raised an issue here : https://github.com/dotnet/aspnetcore/issues/29046

**Comment by debugjan** [comment]
Ok. Thank you for your effort.

**Comment by debugjan** [comment]
Hi,

I manually migrated the packages MySqlConnector to v.1.2.1 of Dotmin.Sync.MySql. I only had to change the namespaces to "using MySqlConnector;". Fortunately this solves the problem. 

you said 

> 
> 
> I think I will probably migrate everything to .Net 5, but not until the release of .Net 5

i am not quite sure what you mean by that. Did you mean .net 6 ?

**Comment by Mimetis** [comment]
Indeed, .Net 5 is already released :)
