### ISSUE TITLE
Snapshots download from api but not written to disk

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#421]
We are now using DMS to create a snapshot on our API after a big data upload. When I sync to a new client, the SQLite database with tables is created by DMS, but there is no data in the local SQL:ite database after sync completes.

The SQL Server db is ~ 800mb. This was synced up by DMS from a local SQLite db of ~450mb. Then the snapshot was created on the web server.

I can see with Fiddler DMS is downloading the snapshot in ~500k chunks. The client is configured to put the snapshot folder in the same folder as the SQLite database, but no snapshots appear there. Occasionally I see `Dotmim.Sync.Web.Client.HttpSyncWebException` in the output window.

The client configuration is
```
SyncOptions syncOptions = new SyncOptions();
syncOptions.SnapshotsDirectory = Path.Combine(AppDataFolder, "Snapshots");
syncOptions.CleanMetadatas = true; // clears local tracking tables after successful sync
syncOptions.BatchSize = 2000; // ~ 2mb https://github.com/Mimetis/Dotmim.Sync/issues/368#issuecomment-739430229
syncOptions.UseBulkOperations = true;

SyncAgent syncAgent = new SyncAgent(clientProvider, webClientOrchestrator, syncOptions);

```
Any suggestions for why the downloaded snapshot is not being written to disk? Where do I start looking?

**Comment by Mimetis** [comment]
We need more info on the exception raised. Do you have more info ?

First, `syncOptions.SnapshotsDirectory` is not used on the **Client** side. 
It's only used on the **Server** side to store the snapshot files

On the client, the `BatchDirectory` is used instead when downloading the files (files from snapshot or files from regular sync)

That been said, depending on the `Device.Platform`, you should careful choose the path to save your data.

Here is a sample of what I'm using when developing a **Xamarin** mobile application:

``` cs
public interface ISettingServices
{
    string DataSource { get; }
    string DataSourcePath { get; }
    string DataSourceName { get; }
    string BatchDirectoryPath { get; }
    string BatchDirectoryName { get; }
    string SyncApiUrl { get; }
    int BatchSize { get; }
}
```
``` cs
public class SettingServices : ISettingServices
{

    private string GetLibraryPath()
    {
#if __IOS__
        // we need to put in /Library/ on iOS5.1 to meet Apple's iCloud terms
        // (they don't want non-user-generated data in Documents)
        string documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.Personal); // Documents folder
        string libraryPath = Path.Combine(documentsPath, "..", "Library"); // Library folder instead
#else
        // Just use whatever directory SpecialFolder.Personal returns
        string libraryPath = Environment.GetFolderPath(Environment.SpecialFolder.Personal); ;
#endif

        return libraryPath;
    }

    public string DataSourceName => "Contoso.db";
    public string BatchDirectoryName => "dms";

    public string DataSourcePath => Path.Combine(GetLibraryPath(), DataSourceName);
    public string BatchDirectoryPath => Path.Combine(GetLibraryPath(), BatchDirectoryName);

    public string DataSource => $"Data Source={DataSourcePath}";

    public string SyncApiUrl => Device.RuntimePlatform == Device.Android ? 
                    "https://10.0.2.2:44313/api/sync" : "https://localhost:44313/api/sync";

    public int BatchSize => 1000;
}
```

And here is how I'm using it when creating a `SyncAgent`:

``` cs
  this.settings = DependencyService.Get<ISettingServices>();
  var syncApiUri = new Uri(this.settings.SyncApiUrl);
            
  this.httpClient = new HttpClient();

// Look here for implementation : https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/TodoREST
#if DEBUG
  var handler = DependencyService.Get<IHttpClientHandlerService>().GetInsecureHandler();
#else
  var handler = new HttpClientHandler();
#endif

  this.httpClient = new HttpClient(handler);

  // Check if we are trying to reach a SQL Server Express.
  // SQL Express does not allow any request other than localhost
  // So far,hacking the Host-Content header to mimic localhost call
  if (Device.RuntimePlatform == Device.Android && syncApiUri.Host == "10.0.2.2")
      this.httpClient.DefaultRequestHeaders.Host = $"localhost:{syncApiUri.Port}";

  this.webProxyProvider = new WebClientOrchestrator(this.settings.SyncApiUrl, client:this.httpClient);
  this.sqliteSyncProvider = new SqliteSyncProvider(this.settings.DataSource);
  var clientOptions = new SyncOptions { BatchSize = settings.BatchSize, BatchDirectory = settings.BatchDirectoryPath  };
            
  this.syncAgent = new SyncAgent(sqliteSyncProvider, webProxyProvider, clientOptions);
```

**Comment by VagueGit** [comment]
Thank you for the prompt response and advice @Mimetis . I've correctly configured the BatchDirectory as you said and the json now downloads to the correct folder.

The 800mb SQL Server snapshot was downloaded in 7 hrs 26 mins and results in 4.56 GB json on disk. Is that to be expected? The json on the server is 176mb.

Again the SQLite database was created correctly by DMS but no data was inserted into the SQLite database.

`Dotmim.Sync.Web.Client.HttpSyncWebException` has stack trace
 ```
at Dotmim.Sync.Web.Client.HttpRequestHandler.<ProcessRequestAsync>d__12`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.Web.Client.WebClientOrchestrator.<GetSnapshotAsync>d__33.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__51.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wbl.Services.DataService.<SyncNowAsync>d__26.MoveNext() in C:\Repos\v11\Wbl\Services\DataService.cs:line 120
```
The exception message is 
`Session loss: No batchPartInfo could found for the current sessionId. It seems the session was lost. Please try again.`

We handle that in our retry logic. The likely cause is memory exhaustion on our server. The test server we are using is under-spec. I'm hoping DMS is sufficiently resilient to deal with that. 

When I restarted the app I could see in Fiddler the json download had restarted. Is that to be expected? There have been no changes on the server nor client since the previous download.

**Comment by Mimetis** [comment]
> The 800mb SQL Server snapshot was downloaded in 7 hrs 26 mins and results in 4.56 GB json on disk. Is that to be expected? The json on the server is 176mb.

I don't understand: the json snapshot on the server is 176mb, but on mobile, it's 4.56gb ?
I guess downloading 176mb should not be a big deal on a mobile, but 4.56gb is too much I think :)


> When I restarted the app I could see in Fiddler the json download had restarted. Is that to be expected? There have been no changes on the server nor client since the previous download.

Seems you lost the session, so far the process has been interrupted and everything has been rollbacked.
There is only one retry logic : IF it failed THEN Everything is rollbacked and it's restarting from previous success sync.
So far, if you have lost your session (for some reasons, like server restarts or whatever) the Sync has failed and thrown an exception.
And the whole process has restarted again when you launched it again.

**Comment by VagueGit** [comment]
If I understand correctly, if a snapshot has already been downloaded, next sync DMS does not check to see if the snapshot it is uptodate before downloading, it just start again?

**Comment by Mimetis** [comment]
Right.

If snapshot has not been applied for some reasons (memory exception, timeout, whatever) `DMS` will rollback the sql statements to stay consistent.
Then on the next sync it will ask again for the server snapshot (and then will redownload everything)

I'm still trying to understand the differences between the 176mb and 4.56gb ?

**Comment by VagueGit** [comment]
Could the differences be explained by repeated session loss? We're going to move to our testing to a bigger server today to try to rule out memory exhaustion.

**Comment by Mimetis** [comment]
Could be a reason I guess.
Maybe you should delete the batch folder on the mobile before launching a sync.
`DMS` deletes the folder when the sync is done, but since you have some failure, I guess the folder is not deleted.

By the way, downloading 176 mb should not take 7hrs
Do you have a low bandwith connection ?

**Comment by VagueGit** [comment]
There is 176mb of json on the server but it downloaded 4.56gb. Speedtest shows 150mbps here, but there server is half a world away. Maybe it's just downloading the same 176mb over and over.

The app we are experimenting with is a UWP/WinUI desktop thing so there are plenty of local resources. I'll post back here after  we upgrade the server side.

**Comment by Mimetis** [comment]
Can you try with the last beta version `v0.6.1` ?
I've think I've resolved some memory leaks issues and maybe a little better performances. #426
Let me know if it's improving your sync server.
https://www.nuget.org/packages/Dotmim.Sync.Core/0.6.1-beta-0504

**Comment by VagueGit** [comment]
Thank you @Mimetis. I upgraded DMS to 0.6.1-beta-0504 on the client and the web server. Memory has been upgraded on this server. This is the only app running on this server. Server memory usage was higher than before, but we didn't experience any memory exhaustion issues.

This is the process I followed:
Legacy test data was upgraded to SQLite on the client. SQLite db 421 MB
DMS synced that data to SQL Server via api. SQL Server db 423 MB data, 328 MB log.
DMS created a snapshot on the web server via the api. Snapshot on server 178 MB
DMS then downloaded the snapshot to new client. There was at least one session lost and looking at Fiddler it seems download restarted. Json downloaded was 697 MB in total.
A SQLite exception was thrown `SQLite Error 19: 'FOREIGN KEY constraint failed'`. Stack trace:
```
   at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception)
   at Dotmim.Sync.BaseOrchestrator.<RunInTransactionAsync>d__66`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dotmim.Sync.BaseOrchestrator.<RunInTransactionAsync>d__66`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.LocalOrchestrator.<ApplySnapshotAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__51.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wbl.Services.DataService.<SyncNowAsync>d__26.MoveNext() in C:\Repos\v11\Wbl\Services\DataService.cs:line 120
```
I terminated the app at that point.

DMS appears to have created the SQLite database and tables correctly, but it has no data.

Where do we go from here?

**Comment by Mimetis** [comment]
Seems you have an exception on a foreign key.
Did you create the sqlite database, ou did yu let DMS do it ?

Why Server memory usage was higher than before ? Should not

Can you share the schema you are trying to sync (schema only, no need data, or at least a small amount of data could help) ?

Finally, can you share a small sample repro ?
I guess the error should be raised even with a small amount of data

**Comment by VagueGit** [comment]
Our process is:
User logs into the app
App calls a method on the api which invokes a stored proc on the SQL Server to create a new DB
DMS creates a local SQLite database on first sync from the SQL Server database.
If legacy data is detected on the client, that legacy data is inserted into the local SQLite database and synced to the server by DMS. DMS creates a snapshot on the web server.

We added more memory to the web server and we had a single error when the CPU peaked. So we moved to another web server with more CPU. This all works without a hitch now.

After the upgrade of legacy data has completed on one machine, that data must be synced down to other machines in the same company. We shouldn't see any foreign key constraints as DMS is creating the SQLite database and all the data has already been in one SQLite database and synced to a SQL Server database.

This time syncing down to a new machine I saw
`Dotmim.Sync.SyncException` The error message appears to be a ~500k json batch, way to long to post here

The stack trace is
```
   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__51.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Wbl.Services.DataService.<SyncNowAsync>d__26.MoveNext() in C:\Repos\v11\Wbl\Services\DataService.cs:line 120
```

At this point only 28.5 MB of the 176MB json snapshot has been downloaded. There have been no connection issues. There have been no server issues.

@Mimetis I don't have a tools to generate a script of the SQLite database, but I'm happy to generate a script if you can recommend a tool. The schema can only be shared in-confidence.

In the meantime I'll continue running tests on new machines to see what pops up.

**Comment by Mimetis** [comment]
Should not happens since `DMS` is disabling all the tables constraints before making any insert

**Comment by VagueGit** [comment]
So DMS downloads the snapshot, creates the SQLite database, turns foreign keys off then tries to insert.

But insert fails because foreign keys are on.

In DMS client configuration we explicitly turn foreign keys on (didn't realise foreign keys is on by default in SQLite 3). So next test I didn't turn foreign keys on and DMS synced to the new client without issue.

Thank you once again for your assistance and patience @Mimetis

**Comment by Mimetis** [comment]
Really happy you manage to turn around all these difficulties :)
