### ISSUE TITLE
Release notes on changes

### ISSUE THREAD

**Issue by satpal123** [Mimetis/Dotmim.Sync#427]
Hi @Mimetis,

It would be great if you can add release notes when releasing a latest version. I recently updated to 0.60 and few things were changed and depreciated so didn't knew what was changed. Had to go through the long commit logs to check the changes :-)

Cheers

**Comment by Mimetis** [comment]
Thanks for the feedback
Release notes will be implemented when we'll reach the version 1.0

Until then, there is so many things evolving that it's hard to maintain.

**Comment by satpal123** [comment]
Maybe don't include detailed release notes but only things that are deprecated or functions that will possibly break after version upgrade.

**Comment by Mimetis** [comment]
Ok, let's try it ! :)
