### ISSUE TITLE
[Help] How to increase timeout in WebProxy?

### ISSUE THREAD

**Issue by thefonzi** [Mimetis/Dotmim.Sync#43]
Hello Sebastien,
i'm back in "test-mode" :-).
I have a DB with about 2GB and local sync works fine (MSSQL-MSSQL).
But as soon as I use the WebProxy (debug mode in VS) I get an error "Object Reference not set". 
I suppose, this is just a timeout error.
How can I increase timeout when using WebProxy?

Thanks
Reinhold

**Comment by Mimetis** [comment]
did you try to set a batchsize, to prevent a timeout ?

**Comment by thefonzi** [comment]
no, not yet. Will try now.

**Comment by thefonzi** [comment]
hm,  "configuration.DownloadBatchSizeInKB = 65536" was the old value.
I have now increased up to 524288. 
But still the same error

**Comment by Mimetis** [comment]
No, try a small value, like 2048

**Comment by thefonzi** [comment]
I have testet now values from 512-8192.
But this gives meine an Error (Bad request) even in earlier

**Comment by thefonzi** [comment]
would it help, if I provide you DB+Client+Proxy?

**Comment by Mimetis** [comment]
Yes !

**Comment by Mimetis** [comment]
I reproduce the problem.   
Indeed, we ran into a `Timeout` error so far.  
Actually, I don't have any solution to resolve this error, unless you made the first sync in a local mode (ie: not with a `WebProxy` beetween client and server)

I think about a new solution that could resolve this issue, in a next version of `Dotmim.Sync`:

The idea will be to generate an **zip** archive containing a database version for every new `Dotmim.Sync` client.   
This archive has to be generated by the administrator on th server side, and on first sync, the client will just download the archive, uncompress, apply, and then make a classic sync to get the data beetween the archive and now.

How it should work:
* Admin generate a zip for new customers. Zip is marked for `Timestamp` **15**

Now, days later, a new client is create and launch a sync:
* Client reach the server, say it's a new sync, and download the last Zip archive.
* Client applies locally the Zip archive.
* Client will continue with a normal sync, saying he is on TimeStamp **15**
* Server get changes from Timestamp 15 and the last Timestamp
* Client applies the changes

Actually, the SQL Server merge sync is working like this.

It's a lot of work actually to be able to implement such feature in `Dotmim.Sync`.  
I will try to work on it during the next month.

Sebastien

**Comment by ashalkhakov** [comment]
Is this error due to an HTTP request taking too long? What if we used WebSockets connection in the web proxy, would this help?

**Comment by Mimetis** [comment]
https://mimetis.github.io/Dotmim.Sync/Timeout
https://mimetis.github.io/Dotmim.Sync/Snapshot
