### ISSUE TITLE
Transaction blocks server

### ISSUE THREAD

**Issue by tothmartonjeno** [Mimetis/Dotmim.Sync#430]
Server: SQL Server
Client: Xamarin Forms + SQLite database
Sync: every 10 minutes, cca. 200 rows download, 50 rows upload

This time I tested sqlserver response time during sync. An app's timer sends random call update/insert to 2 tables at sqlserver.
If there is no sync, call's duration is 10-20 ms. But this can increase 10-15 sec during sync. I think this is because sync transaction blocks the server database. Then I used READ_COMMITTED_SNAPSHOT = ON option, but this option doesn't help.
If 30 clients syncronize every 10 minutes, the server will be blocked all the time.
What kind of  isolation level do you use? Can be the transaction an option?
(MS Sync Framework doesn't block server during sync, maybe they don't use transaction default?)

**Comment by Mimetis** [comment]
Hey @tothmartonjeno 
First of all, thanks for the feedback !

The isolation level used is the `READ_COMMITED` level. 

When you say 30 clients every 10 min, do you mean *"Every 30 min, I launch simultaneously a sync from 30 clients"* ?
Or do you try to make 30 sync scaled in the 10 min ?

For the isolation level, you can do it like that:

``` cs

    agent.LocalOrchestrator.OnTransactionOpen(toa =>
    {
        var command = toa.Connection.CreateCommand();
        command.Connection = toa.Connection;
        command.Transaction = toa.Transaction;

        // Set transaction level for the session
        command.CommandText = "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;";
        command.ExecuteNonQuery();

    });

#if DEBUG
    agent.LocalOrchestrator.OnTransactionCommit(tca =>
    {

        var command = tca.Connection.CreateCommand();
        command.Connection = tca.Connection;
        command.Transaction = tca.Transaction;

        command.CommandText = $"SELECT  session_id AS SessionID, program_name AS ProgramName, DB_NAME(database_id) AS DatabaseName, " +
        $"CASE transaction_isolation_level WHEN 0 THEN 'Unspecified' WHEN 1 THEN 'ReadUncommitted'  WHEN 2 THEN 'ReadCommitted' " +
        $"WHEN 3 THEN 'Repeatable' WHEN 4 THEN 'Serializable' WHEN 5 THEN 'Snapshot'  END AS Transaction_Isolation_Level " +
        $"FROM sys.dm_exec_sessions where session_id > 30 and DB_NAME(database_id) = '{tca.Connection.Database}'";

        var reader = command.ExecuteReader();
        while (reader.Read())
            Console.WriteLine($"{reader[0]} {reader[1]} {reader[2]} {reader[3]}");

        reader.Close();
    });
#endif

```

Are you able to share how you are making this test. Just to see if I can reproduce locally ?

**Comment by tothmartonjeno** [comment]
I tested just one android emulator client. The target: 30 android devices syncronise its sqlite local database with sql server.
Clients: client-1, client-2, ... client-30
Sync start times for example:
Client-1 make sync at 08:00, 08:10, 08:20...
Client-2 make sync at 08:03, 08:13, 08:23...
...
When I tested the concurrency, I scheduled sync process with 10 minutes periodically in android emulator. Meanwhile an app executing sql commands to SQL Server. My experience: the sql server is blocked in case of concurrency.
I think, your proposal works on client. But the problem is at server. I try to change the web api's sync controller's post action according to your code.

**Comment by Mimetis** [comment]
Hey @tothmartonjeno 
Can you test with this last commit from the branch `v0.6.1` ? https://github.com/Mimetis/Dotmim.Sync/tree/v0.6.1

I've found a small issue that was preventing the SQL Server instance to use pooling and command sharing (when a transaction was involved)

I've made few tests and it's working quite fast on my machine, less than 5 sec for 30 Clients.

Let me know if it's resolving your issue.

If you can't clone the branch, let me know I will quickly publish a new beta version on nuget

**Comment by tothmartonjeno** [comment]
Hi,
I tested 0.6.1-beta-0511.
`Invalid cast from 'Double' to 'DateTime' ` is thrown by `agent.SynchronizeAsync` method.
Table definition in SQL Server:
```
CREATE TABLE [dbo].[SyncLog](
	[UID] [uniqueidentifier] NOT NULL,
	[FelhasznaloKod] [int] NULL,
	[pda_sync_scope_id] [uniqueidentifier] NULL,
	[AllapotKod] [char](1) NOT NULL,
	[Manual] [bit] NULL,
	[Interactive] [bit] NULL,
	[KezdoDatum] [datetime] NULL,
	[ZaroDatum] [datetime] NULL,
	[Duration] [int] NULL,
	[TotalChangesApplied] [int] NULL,
	[TotalChangesDownloaded] [int] NULL,
	[TotalChangesUploaded] [int] NULL,
	[TotalSyncErrors] [int] NULL,
	[ErrorMessage] [nvarchar](max) NULL,
 CONSTRAINT [PK_SyncLog] PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```
SyncSetup is UploadOnly for this table.
Reinit is done without error.
After I insert one row at client (SQLite):
```
insert into SyncLog ([UID], [FelhasznaloKod], [pda_sync_scope_id], [AllapotKod], [Manual], [Interactive], [KezdoDatum])
values ('99c52a7a-2dd3-4503-8608-e5c614301387', 1, '10c52a7a-2dd3-4503-8608-e5c614301387', 'R', true, true, '')

```
and call agent.SynchronizeAsync, exception is thrown.
I tested both in console app and in Xamarin.
Console app exception: `String '' was not recognised as a valid DateTime.`
Xamarin exception: `Invalid cast from 'Double' to 'DateTime'`
After DMS version update I didn't make deprovision and provision.

**Comment by Mimetis** [comment]
Hi @tothmartonjeno 
Seems this is another issue.
Can you please confirm the block server issue is fixed, and please open a new issue for you datetime prob?

**Comment by tothmartonjeno** [comment]
Hi,
There was a test for that issue. I've noticed a significant improvement in the concurrency, but it's not perfect yet.
Test:
3 android devices launched 60 (30 + 15 + 15) sync while a web app made queries to the sql server. 10 percent of sync's blocked the sql server 2 - 7 sec. What can be the reason of that blocking situation? Transaction? Can you give higher priority to concurrency over consistency with some snyc setup option?

**Comment by Mimetis** [comment]
Indeed, I guess transactions may block tables.
Did you tried with `Read Uncommited` options, using :

``` cs
agent.LocalOrchestrator.OnTransactionOpen(toa =>
    {
        var command = toa.Connection.CreateCommand();
        command.Connection = toa.Connection;
        command.Transaction = toa.Transaction;

        // Set transaction level for the session
        command.CommandText = "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;";
        command.ExecuteNonQuery();

    });
```

Is it changing something ?

**Comment by tothmartonjeno** [comment]
Hi,
No, this didn't help.
But I managed to find the source of the blocking situation.
When `ALTER TABLE <table> NOCHECK CONSTRAINT ALL` statement is executed in the beginning of the transaction, it locks the table object (Schema lock).
The solution: 
#1 `DisableConstraintsOnApplyChanges = false`
#2 `ALTER DATABASE <dbname>SET READ_COMMITTED_SNAPSHOT ON`
Both are required if concurrency has higher priority.

**Comment by Mimetis** [comment]
wow, that's completely makes sense ! Good catch @tothmartonjeno !
Be careful to declare your tables in the good orders to avoid foreign keys exceptions when making any sync.

Just out of curiosity, what are the performances right now ?

**Comment by tothmartonjeno** [comment]
Now the emulator sync has no remarkable effect to sql server performance. I watched 10-15 syncs.
It will be a test with four devices soon...
