### ISSUE TITLE
Xamarin not null DateTime field upload throws exception

### ISSUE THREAD

**Issue by tothmartonjeno** [Mimetis/Dotmim.Sync#436]
DMS version: 0.6.1-beta-0511
Server: SQLServer
Local: SQLite on xamarin
Sync table contains nullable DateTime field.
Setup for table: upload/bidirectional. 
After insert statement at xamarin client when the field has value `Invalid cast from 'Double' to 'DateTime'` exception is thrown by agent.SynchronizeAsync method.

Field is null -> works fine
Console app -> works fine
DownloadOnly -> works fine
0.6.0 -> works fine

Xamarin + Field is not null + Upload + 0.6.1-beta-0511 -> exception

**Comment by tothmartonjeno** [comment]
I am using sqlite-net-pcl package to store and retrieve objects.
Save a SyncLog object:

```
SyncLog syncLog = new SyncLog(){...}
await connection.InsertAsync(syncLog);

```
`connection ` is a SQLiteAsyncConnection type.

I think this changed in the beta version: storeDateTimeAsTicks.

In version 0.6.0 this works:
`static readonly Lazy<SQLiteAsyncConnection> _databaseConnectionHolder = new Lazy<SQLiteAsyncConnection>(() => new SQLiteAsyncConnection(_databasePath, SQLiteOpenFlags.ReadWrite | SQLiteOpenFlags.Create | SQLiteOpenFlags.SharedCache));
`
In version 0.6.1-beta-0511 this works:
`static readonly Lazy<SQLiteAsyncConnection> _databaseConnectionHolder = new Lazy<SQLiteAsyncConnection>(() => new SQLiteAsyncConnection(_databasePath, SQLiteOpenFlags.ReadWrite | SQLiteOpenFlags.Create | SQLiteOpenFlags.SharedCache, storeDateTimeAsTicks: false));`
        
Your ADO.NET solution is also works with the beta version.

**Comment by Mimetis** [comment]
So I guess we can close this issue :) (Re open it, if I'm wrong)

**Comment by Mimetis** [comment]
I need more details.
Looking at the discussion we have on the other issue #430, I've made some tests with your setup:

The server database table is this one:

``` sql
CREATE TABLE [dbo].[SyncLog](
	[UID] [uniqueidentifier] NOT NULL,
	[FelhasznaloKod] [int] NULL,
	[pda_sync_scope_id] [uniqueidentifier] NULL,
	[AllapotKod] [char](1) NOT NULL,
	[Manual] [bit] NULL,
	[Interactive] [bit] NULL,
	[KezdoDatum] [datetime] NULL,
	[ZaroDatum] [datetime] NULL,
	[Duration] [int] NULL,
	[TotalChangesApplied] [int] NULL,
	[TotalChangesDownloaded] [int] NULL,
	[TotalChangesUploaded] [int] NULL,
	[TotalSyncErrors] [int] NULL,
	[ErrorMessage] [nvarchar](max) NULL,
 CONSTRAINT [PK_SyncLog] PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```
Everything works fine on my **Xamarin** application.

Now, using your code:

```cs
insert into SyncLog ([UID], [FelhasznaloKod], [pda_sync_scope_id], [AllapotKod], [Manual], [Interactive], [KezdoDatum])
values ('99c52a7a-2dd3-4503-8608-e5c614301387', 1, '10c52a7a-2dd3-4503-8608-e5c614301387', 'R', true, true, '')
```
Makes the sync crashes, indeed.
Because you'are inserting **Wrong Types** in your **Sqlite** table (and **SQLite** allows you to do so)

So far, I just convert your code to this code, more efficient, more secure and more performant:
``` cs
var text = "insert into SyncLog([UID], [FelhasznaloKod], [pda_sync_scope_id], [AllapotKod], [Manual], [Interactive], [KezdoDatum])" +
            "values(@id, @fk, @pdascopeid, @ak, @m, @i, @kd)";


using (var sqliteConnection = new SqliteConnection(this.settings.DataSource))
{
    var c = new SqliteCommand(text)
    {
        Connection = sqliteConnection
    };


    var p = new SqliteParameter
    {
        DbType = DbType.Guid,
        ParameterName = "@id",
        Value = Guid.NewGuid()

    };
    c.Parameters.Add(p);

    p = new SqliteParameter
    {
        DbType = DbType.Int32,
        ParameterName = "@fk",
        Value = 1
    };
    c.Parameters.Add(p);

    p = new SqliteParameter
    {
        DbType = DbType.Guid,
        ParameterName = "@pdascopeid",
        Value = new Guid("10c52a7a-2dd3-4503-8608-e5c614301387")

    };
    c.Parameters.Add(p);

    p = new SqliteParameter
    {
        DbType = DbType.String,
        ParameterName = "@ak",
        Value = "R"

    };
    c.Parameters.Add(p);


    p = new SqliteParameter
    {
        DbType = DbType.Boolean,
        ParameterName = "@m",
        Value = true

    };
    c.Parameters.Add(p);

    p = new SqliteParameter
    {
        DbType = DbType.Boolean,
        ParameterName = "@i",
        Value = true

    };
    c.Parameters.Add(p);


    p = new SqliteParameter
    {
        DbType = DbType.DateTime,
        ParameterName = "@kd",
        Value = DateTime.Now

    };
    c.Parameters.Add(p);
    sqliteConnection.Open();

    using (var t = sqliteConnection.BeginTransaction())
    {
        c.Transaction = t;

        c.ExecuteNonQuery();

        t.Commit();
    }

    sqliteConnection.Close();

}
```

From that point, the sync starts to work as expected :)
