### ISSUE TITLE
SQL syntax on MariaDB

### ISSUE THREAD

**Issue by sylverbee** [Mimetis/Dotmim.Sync#439]
DMS version: 0.6.1
Server: MariaDB
Local: SQLite
Table count: 10
Total rows: 1000000

When executing agent.SynchronizeAsync(), I get an error
"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INTO sync_row_count;
IF (sync_row_count = 0) THEN
	INSERT  INTO `CANVAS`
	...' at line 40"

**Comment by Mimetis** [comment]
What is the version of your MariaDB Server ?

**Comment by sylverbee** [comment]
10.3.23

**Comment by Mimetis** [comment]
Can you test with a version `10.5` ?

**Comment by sylverbee** [comment]
My server won't support it.
I could move to 10.4

**Comment by sylverbee** [comment]
No way to use >10.3.27
If I switch to mySQL, what is the minimum version to use?

**Comment by Mimetis** [comment]
I'm always testing with the last version of MySql / MariaDB
Locally I'm working with `MySql 8.0.21`
