### ISSUE TITLE
Sync error: Force Update should always work...contact the author

### ISSUE THREAD

**Issue by menitamoses** [Mimetis/Dotmim.Sync#440]
I am using Dotmim.Sync.Core and Dotmim.Sync.SqlServer to Sync data from Server A to B. 'A' being the source and B the client. The is a one way push from A-> B only. B is mostly a read-only DB server. However, I still have to make the process resilient enough to fix conflicts as best as possible. For that, I am forcing a one column-one row update in a table in server B to test the 'ServerWins' conflict resolution policy.
When the sync jobs starts on a timer I see it spit out messages
ChangesApplying:	3:49:43 PM.168	 [DB] [Tabel1] Modified applied:44 resolved conflicts:0
ChangesApplying:	3:49:43 PM.168	 [DB] [Table2] Modified applied:1 resolved conflicts:0
....
There are 52 tables total...half way through the list of tables the messages like the ones above stops and I see thsi
Force update should always work.. contact the author :)
This is my sync config
   public static readonly SyncOptions SyncOptions = new SyncOptions
        {
            ConflictResolutionPolicy = ConflictResolutionPolicy.ServerWins,
            UseBulkOperations = true,
            UseVerboseErrors = true,
            CleanMetadatas = true,
            DisableConstraintsOnApplyChanges = true,
            BatchSize = 3000 //10240 //kb
        };

I didn't override OnApplyChangesFailed event. The first time I saw this I perform a reinitialize between Server A and B and it was successful
await agent.SynchronizeAsync(SyncType.Reinitialize,Config.GetProgress())
But a regular 
 await agent.SynchronizeAsync(progress); throws the above error half way through the sync. I have replicated the error several time. Is there an exception I can trap instead of this message?

**Comment by Mimetis** [comment]
You may have a conflict somewhere that is failing.
It's concerning only 1 table, for some reason.
Are you able to determine which table causes this failure and make a sync test with only this table ?

The best way to debug this is to isolate the table problem. If you're able to share a simple repro project with, I could eventually help you on that.

**Comment by Mimetis** [comment]
Do yo have any more info ?
Did you finally resolved the issue or you're still struggle with it ?

**Comment by menitamoses** [comment]
There was a snow storm that took down power and internet the past 5 days. I havent been able to spend time on it as much as I had hoped. However, I cant replicate the error predictably and the error message shows up without an exception. Is there a way to see it as an exception?

**Comment by Mimetis** [comment]
The problem is that there is no error raised.
It's just something that should not happens: `DMS` tries to update a row that does not exists. The Data Source just sent a `0` value instead of `1` (`0` means **0** rows affected by the statement)

**Comment by menitamoses** [comment]
I understand but since it did happen I am wondering if you can provide that message as an exception so I can program my application to recover gracefully

**Comment by Mimetis** [comment]
There is an exception raised actually

``` cs
//After a force update, there is a problem, so raise exception
if (!operationComplete)
   throw new UnknownException("Force update should always work.. contact the author :)");

```

**Comment by menitamoses** [comment]
ok.. I will catch that exception. Thank you!

**Comment by Mimetis** [comment]
Be careful, the error raised will be a `SyncException`.
And the `SyncException.TypeName` will be a string ("UnknownException")

**Comment by menitamoses** [comment]
Oh, Thanks for the headup. I wrote a catch(UnknownException)...I will change that
