### ISSUE TITLE
Concurrent synchronizations side effects

### ISSUE THREAD

**Issue by NunzioCar** [Mimetis/Dotmim.Sync#441]
Hi,
I have many local orchestrators, with the same scope, that can be execute concurrent batch syncronizations, and with different sync parameters.

Looking in the source code it seems that for each request the WebServerOrchestrator first sets context and after gets the context while manages the request. Can this behavior have side effects for concurrent syncronizations?

Thanks,
Nunzio

**Comment by Mimetis** [comment]
From databases, everything is under transactions, so far isolation should be fine
For the HttpContext and server session, the client is identified by a `sync_session_id` that is unique, so it should be fine as well

I made some tests on concurrent calls, you  can see here https://github.com/Mimetis/Dotmim.Sync/blob/6a1253081d94730d7a15d143f47cecfe2e861b37/Tests/Dotmim.Sync.Tests/HttpTests.cs#L1483

If you think about a scenario that could break something, please share :)

**Comment by NunzioCar** [comment]
Ok, so WebServerOrchestrator.SetContext() not should create any side effects for the GetContext(), also when concurrent syncronizations have different SyncParameter (tenant id in my case).
I'll try to test my scenario.

Thanks,
Nunzio

**Comment by Mimetis** [comment]
Will close this issue.
If you still have any errors specific to this issue topic, feel free to re-open it.
