### ISSUE TITLE
SYSTEM_VARIABLES_ADMIN on AWS RDS

### ISSUE THREAD

**Issue by sylverbee** [Mimetis/Dotmim.Sync#443]
DMS version: 0.6.1
Server: MySQL
Local: SQLite
Table count: 10
Total rows: 1000000

Where running first sync, I get an error : "Access denied; you need (at least one of) the SUPER or SYSTEM_VARIABLES_ADMIN privilege(s) for this operation".

What is the detail of privileges needed on DB? As I can't give a user SUPER privileges on AWS RDS.

**Comment by Mimetis** [comment]
We need to create triggers, stored procedures, table value parameter types, and tables
We need to be able to disable constraints as well (until you set the options `DisableConstraintsOnApplyChanges = false`)

Not sure what kind of privileges from MySql is needed for this kind of operations.

**Comment by sylverbee** [comment]
Can you check?
The user has all rights, except GRANT, on db:
- OBJECT: select, insert, update, delete, execute, show view
- DDL: create, alter, references (index, create view, create routine, alter routine, event, drop, trigger)
- Other: create temporary tables, lock tables

**Comment by Mimetis** [comment]
I can't, I don't have any AWS subscription.
You still can debug your sync, using the clone of the source code locally, or using the pdb exposed as explained here  https://dotmimsync.readthedocs.io/Debugging.html

**Comment by sylverbee** [comment]
I found how to give to my user SYSTEM_VARIABLES_ADMIN.
Now I get : "You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)"

**Comment by sylverbee** [comment]
Solution found : change on AWS DRS to set log_bin_trust_function_creators=1

So my conclusion : YES, we can use DOTMIM with AWS RDS so far!
