### ISSUE TITLE
On Database provisioning, remove existing PK column and set a GUID column as PK

### ISSUE THREAD

**Issue by satpal123** [Mimetis/Dotmim.Sync#444]
Update: Works with 0.5.7 version but not with 0.6.1

I am using Dotmim 0.6.1. When I am trying to provision the database, I want to remove a column from Scope but the issue is that the schema returns no columns in the table.

Basically, What I am trying to do is to add a GUID column in our existing table. Then on database provision I am removing the existing ID primary key and make the GUID column the primary key.

![image](https://user-images.githubusercontent.com/710270/107897949-958cbd80-6f8e-11eb-8cb6-9848d069e6aa.png)

I am using the below code :

The code below works with version 0.5.7 and only when using `SqlSyncProvider` but not with `SqlSyncChangeTrackingProvider`

```
static async Task ProvisionServerManuallyAsync()
        {
            SqlSyncProvider serverProvider = new SqlSyncProvider(serverConnectionString);

            var tables = new string[] { "Patient" };

            var options = new SyncOptions();

            var setup = new SyncSetup(tables);
            var patientFilter = new SetupFilter("Patient");
            patientFilter.AddParameter("SiteCode", "Patient", true);
            patientFilter.AddWhere("SiteCode", "Patient", "SiteCode");
            setup.Filters.Add(patientFilter);

            var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);

            remoteOrchestrator.OnDatabaseProvisioning(args =>
            {
                var schema = args.Schema;

                foreach (var table in schema.Tables)
                {
                    var columnsToRemove = new string[] { "ID" };
                    foreach (var columnName in columnsToRemove)
                    {
                        var column = table.Columns[columnName];

                        if (column != null)
                            table.Columns.Remove(column); 
                    }
                    table.PrimaryKeys.Remove("ID");
                    table.PrimaryKeys.Add("PGUID");
                }
            });

            var serverScope = await remoteOrchestrator.GetServerScopeAsync();

            var newSchema = await remoteOrchestrator.ProvisionAsync(SyncProvision.StoredProcedures
                | SyncProvision.Triggers | SyncProvision.TrackingTable);

            // affect good values
            serverScope.Setup = setup;
            serverScope.Schema = newSchema;

            // save the server scope
            await remoteOrchestrator.WriteServerScopeAsync(serverScope);
        }
```

Is it possible for the above code to work for `SqlSyncChangeTrackingProvider` or is that a limitation?

**Comment by Mimetis** [comment]
Changing a `Primary Key` will break the sync, since the tracking table should be recreated to have the correct `Primary Key`.
So far, my advice would be to `DeprovisionAsync()` everything and make a new sync setup from scratch.

If you can't do a full reinitialization, I guess you will have to edit the tracking table manually.

For `SqlSyncChangeTrackingProvider`, I guess the SQL Change Tracking should continue to work even if you're changing the primary keys, but you still need to recreate all the stored procedures.
You can use for instance the `CreateStoredProcedureAsync` method on your Orchestrator (or use `ProvisionAsync` with the correct paramter)

I will check why there is no columns using `SqlSyncChangeTrackingProvider`, but It won't change the theory

**Comment by satpal123** [comment]
Thanks for the reply @Mimetis

We have decided not to sync all the peer split DB's to the master DB. Instead we will make all the split DB's as master and then all the users will sync to those split DB's only to avoid all the complexity.

Later on we will just create a standalone DB with only details of clients for search and lookup.

**Comment by Mimetis** [comment]
Will close this issue.
If you still have any errors specific to this issue topic, feel free to re-open it.
