### ISSUE TITLE
Add and Remove Column

### ISSUE THREAD

**Issue by PardeepBhandari** [Mimetis/Dotmim.Sync#445]
Hi

My Server is sql server and for client database i have sqllite database.
i am able to sync my server database to client file although database was really big.

but now i want to alter some tables (add remove columns) on both side for that
i remove provisions from server and client now i alter databases from both side (add remove some column)

what will be the next steps do i sync again  (both sides have same data. this is the main point do i need to remove data from client).

Please guide me 

Thanks.

**Comment by Mimetis** [comment]
You don't need to remove data, unless the columns you've changed are primary keys.

You have several options to provision again.
The best option is to use `ProvisionAsync()`
You may read the documentation here : https://dotmimsync.readthedocs.io/Provision.html
