### ISSUE TITLE
Row merge and changes tracking

### ISSUE THREAD

**Issue by jromerus** [Mimetis/Dotmim.Sync#45]
I'm not sure how merging rows works when a conflict is detected, so I have a question regarding of this.

Suppose that at server side a user modifies only a column value and at client replicated database side the same object/row is modified by another user who only changes a different column. So the obvious question is, what will it happen? Will DotmimSync merge the row preserving changes on both sides?

Regards,
José Enrique

**Comment by Mimetis** [comment]
Hey @jromerus 

Did you read this section on the docs ? [https://mimetis.github.io/Dotmim.Sync/Conflict](https://mimetis.github.io/Dotmim.Sync/Conflict)

In a nutshell, by default, when a conflict occurs, the **server** row wins the challenge.  
You can specify who wins the conflict challenge by specifying the winner in the `SyncConfiguraition` object.

And you can as well, resolving the challenge during the `ApplyChangedFailed` event:

```
private void ApplyChangedFailed(object sender, ApplyChangeFailedEventArgs e)
{
    e.Action = (int)e.Conflict.RemoteRow["Id"] == 1 ? ConflictAction.ClientWins : ConflictAction.ServerWins;
}

```

**Comment by jromerus** [comment]
Yes, I have read it but it's still not clear to me if can achieve that neither server o client wins, and instead of that, apply smart merge. Suppose this:

Master Contact Row:
       id: 1
       name: John
       tel1: 666666
       tel2:
       comments: is a lead <- this has been modified

Slave Contact Row:
       id: 1
       name: John
       tel1: 666666
       tel2: 777777  <- this has been modified
       comments: 

The desired result after merge:
       id: 1
       name: John
       tel1: 666666
       tel2: 777777
       comments: is a lead

So, what is the behavior of merge at Dotmim?

**Comment by Mimetis** [comment]
By default, the server will wins this conflict, so you will have something like that:

```
tel2:
comments: is a lead
```

In your case, you want to achieve a `Merge` action (get one column from server, one column from client), so you have to handle the `ApplyChangedFailed` event:

```
// Subscribing to the ApplyChangedFailed event
agent.ApplyChangedFailed += ApplyChangedFailed;

// Custom conflict resolution
void ApplyChangedFailed(object sender, ApplyChangeFailedEventArgs e)
{
    e.Action = ConflictAction.MergeRow;
    e.FinalRow["tel1"] = e.Conflict.RemoteRow["tel1"];
    e.FinalRow["comments"] = e.Conflict.LocalRow["comments"];
}
```
Make sense ?

**Comment by jromerus** [comment]
No, because I don't know who should win. Now I see that there is no tracking changes of which column has been modified so without that tracking changes it is impossible to know which should win and make an "smart" merge.

Do you think it could be possible to implement this in the future or is so difficult to track column changes?

**Comment by Mimetis** [comment]
Yes, there is no tracking changes in the Dotmim.Sync Framework.
Implementing such features will be really complicated and the will run into performances issues.

Maybe, if you're using SQL Server, you may be able to use the Change Tracking features from SQL Server, and uses it to resolve your conflict (I didn't tried it, just an idea)

**Comment by Mimetis** [comment]
Will close this issue. If you need more informations, feel free to ask for re-open it :)
