### ISSUE TITLE
SQlite busy and cancellation token

### ISSUE THREAD

**Issue by sylverbee** [Mimetis/Dotmim.Sync#450]
DMS version: 0.6.1
Server: mySQL
Local: SQLite
Table count: 10
Total rows: 1000000

I'm looking for a way to kill agent.SynchronizeAsync() with a cancellation token.
It will avoid write conflict

**Comment by Mimetis** [comment]
You need to use a `CancellationTokenSource` : More info here : https://docs.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads

**Comment by sylverbee** [comment]
OK thx.
So it means you don't have such token embedded. No?
Other point : how do manage concurrent access to sqlite db when running sync?

**Comment by Mimetis** [comment]
1) Nop, you have to provide your token, it's by design and a good practice
2) Out of Scope.
