### ISSUE TITLE
Possible enhancement: 2P2 Sync?

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#46]
Hi!

I know, that Dotmim.Sync focuses on client-server synchronization.

For one customer, we have the requirement, to sync from client to client as well.

Do you have an idea if this would (at all) be possible to implement in Dotmim.Sync?
And as I am sure you had quite serious reasons to not implement it, what are those reasons?

Thank you for you insights!

**Comment by Mimetis** [comment]
P2P is too difficult to implement in **Dotmim.Sync** since the framework were not think in this way.
And I don't have enough knowledge on the P2P constraints to even try to implement it :)
