### ISSUE TITLE
Missing feature to full reinit server

### ISSUE THREAD

**Issue by sylverbee** [Mimetis/Dotmim.Sync#465]
When developping, many changes append.
How to reinit all procedures and triggers created on server without doing it manually?

**Comment by Mimetis** [comment]
Hi @sylverbee 
When you are not hiting an issue and your message is more or less a question, please use the [Discussion](https://github.com/Mimetis/Dotmim.Sync/discussions) tab and create a question in the **Q&A** section.

It will be easier for people to find out the answer if they have the same kind of question.

Apart from that, regarding your question, you can use the `DeprovisionAsync()` and `ProvisionAsync` method.
You can read more here : https://dotmimsync.readthedocs.io/Provision.html#provision and https://dotmimsync.readthedocs.io/Provision.html#deprovision

**Comment by sylverbee** [comment]
Oh, ok, I'm sorry.
Thx for the tip
