### ISSUE TITLE
User privileges

### ISSUE THREAD

**Issue by sylverbee** [Mimetis/Dotmim.Sync#469]
In order to run sync, an user with very high privileges if needed.
It's ok for setup, but very risky in real conditions. 
Is it possible to use a less capable user? If yes, with what privileges?

**Comment by Mimetis** [comment]
You need to define `Options.DisableConstraintsOnApplyChanges` to false, and then your use will just need the rights of read / write in your tables.
Be careful, if you need to update the sync schema, it could be mandatory to have higher rights to let DMS applies the alter tables needed

**Comment by sylverbee** [comment]
Thanks, exactly what I needed.
