### ISSUE TITLE
SqlCipher doesn't work on Android

### ISSUE THREAD

**Issue by gaurakshay** [Mimetis/Dotmim.Sync#477]
I am facing an issue similar to #402. What worked in that scenario doesn't work for me unfortunately.

I am working with a `Xamarin.Forms` application (Android and iOS). I installed `Dotmim.Sync.Sqlite` and `Dotmim.Sync.Web.Client` in my shared project and am using `sqlite-net-base` for ORM and `SQLitePCLRaw.bundle_e_sqlcipher` following his suggestions [here](https://github.com/ericsink/SQLitePCL.raw/wiki/How-to-use-SQLCipher-with-SQLite-net).

So I setup my project and tried to sync my database which works just fine for iOS but doesn't work when running the same on Android project. The error that I get is:
`Exception:You specified a password in the connection string, but the native SQLite library 'e_sqlite3' doesn't support encryption.`

## What didn't work
I tried to work with suggestions in #402 but that doesn't work for me and results in the same error
![image](https://user-images.githubusercontent.com/17280428/109233267-2df52000-778f-11eb-8fea-a25a87e49ee6.png)

## What does work?
If I download a copy of `Dotmim.Sync` github repo, change the nuget packages of the project `Dotmim.Sync.Sqlite` by applying the commands suggested by brycelam:
```
dotnet remove package Microsoft.Data.Sqlite
dotnet add package Microsoft.Data.Sqlite.Core
dotnet add package SQLitePCLRaw.bundle_e_sqlcipher
```
And then reference this version of `Dotmim.Sync.Sqlite`, it works on both iOS and Android!!

**Comment by sylverbee** [comment]
@gaurakshay 
I experienced a lot of bugs and concerns using any `sqlite-net-[X]` nugget with DMS.
I rewrited all my classes to only use `Microsoft.Data.Sqlite`.

**Comment by gaurakshay** [comment]
@sylverbee were you using encryption on your database? If yes, how did you setup a successful syncing process on Android phones with encrypted database?

**Comment by sylverbee** [comment]
I only use DMS on UWP.
For mobile apps, I a solution like `monkey-cache`

**Comment by gaurakshay** [comment]
@sylverbee good to know, I have a complicated database schema which I need to sync down to the phone and can't use API calls to bring all the data down to the phone as that will be 40-50 individual API calls. My current requirements are to have a syncing mechanism to have all the data on the phone locally in an encrypted format.
Looking at [monkey-cache](https://github.com/jamesmontemagno/monkey-cache), seems that it won't handle all the logic to determine what needs to be sent up to the server and what needs to be brought down intelligently like DMS does (and what makes it magical :) ).

**Comment by gaurakshay** [comment]
@Mimetis is it possible at all that I can convince you to re-consider [your thought](https://github.com/Mimetis/Dotmim.Sync/issues/402#issuecomment-760472163) here? It would be a great addition to the library to be able to support encrypted SQLite files. And I can offer up my time if anything is require with respect to maintenance or support of this feature.

**Comment by Mimetis** [comment]
Indeed, but I need to find a way to implement it seamlessly.
For now, you can get the source code and recompile it using the `bundle_e_sqlcipher` bundle ?

**Comment by gaurakshay** [comment]
I sure can and that is what I am doing atm!

**Comment by gaurakshay** [comment]
I tried following the comments by @bricelam [here](https://github.com/ericsink/SQLitePCL.raw/issues/236#issuecomment-430705777) so that I wouldn't have to download the code locally and instead just get by using nuget package. I tried to test if this could work in my case too and used the following:
```xml
    <PackageReference Include="Dotmim.Sync.Sqlite" Version="0.6.2" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.0.4" ExcludeAssets="All" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.0.4" />
```
Unfortunately that didn't work for me.

**Comment by bricelam** [comment]
@gaurakshay I'm surprised that didn't work. Try deleting you `bin` and `obj` folders to make sure there aren't any old assets hanging around.

**Comment by gaurakshay** [comment]
@bricelam will do!

**Comment by gaurakshay** [comment]
@bricelam I deleted the `bin` and `obj` folders to make sure there weren't any old artifacts that didn't help unfortunately.

@Mimetis, I tried your suggestion and encrypted SQLite DB does work in a .net 5 console app. So, I think this is not an issue with this library but the way SQLite libraries are loaded in `Xamarin.Forms`.

.net console app package references that works with encrypted SQLite DB:
```xml
<PackageReference Include="Dotmim.Sync.Sqlite" Version="0.6.2" />
<PackageReference Include="Dotmim.Sync.Web.Client" Version="0.6.2" />
<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="5.0.2" />
<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.0.4" ExcludeAssets="All" />
<PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.0.4" />
```

This leads me to believe that there is something funky going on in Xamarin.Forms app. I don't know enough to definitively say which libraries are loaded when the app is installed and started on Android. For reference, here are the packages that I am using in the Xamarin.Forms app.

## Xamarin.Forms Shared Project
```xml
<PackageReference Include="Xamarin.CommunityToolkit" Version="1.0.3" />
<PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />
<PackageReference Include="Xamarin.Essentials" Version="1.6.1" />
<PackageReference Include="Dotmim.Sync.Sqlite" Version="0.6.2" />
<PackageReference Include="Dotmim.Sync.Web.Client" Version="0.6.2" />
<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="5.0.2" />
<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.0.4" ExcludeAssets="All" />
<PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.0.4" />
```

## Xamarin.Forms Android Project
```xml
<PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher">
  <Version>2.0.4</Version>
</PackageReference>
<PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />
<PackageReference Include="Xamarin.Essentials" Version="1.6.1" />
```

## Xamarin.Forms iOS Project
```xml
<PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher">
  <Version>2.0.4</Version>
</PackageReference>
<PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />
<PackageReference Include="Xamarin.Essentials" Version="1.6.1" />
```

I also call `SQLitePCL.Batteries_V2.Init()` in each of the platform projects.

## Xamarin.Forms Android Project (MainActivity.cs)
```csharp
protected override void OnCreate(Bundle savedInstanceState)
{
    base.OnCreate(savedInstanceState);

    SQLitePCL.Batteries_V2.Init();

    Xamarin.Essentials.Platform.Init(this, savedInstanceState);
    global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
    LoadApplication(new App());
}
```

## Xamarin.Forms iOS Project (AppDelegate.cs)
```csharp
public override bool FinishedLaunching(UIApplication app, NSDictionary options)
{
    SQLitePCL.Batteries_V2.Init();

    global::Xamarin.Forms.Forms.Init();
    LoadApplication(new App());

    return base.FinishedLaunching(app, options);
}
```

## Current situation

I am just going to continue to use the code from this library directly (after changing the dependencies of `Dotmim.Sync.Sqlite`) as that is what works for me currently.

I am closing this issue as it is not really an issue of this library per my understanding. If there are any inputs that one might have, they are more than welcome to suggest in a comment and I might try them out.

Thank you for your time @Mimetis @bricelam !!
