### ISSUE TITLE
DateTimeUTC values Serialization/Deserialization 

### ISSUE THREAD

**Issue by menitamoses** [Mimetis/Dotmim.Sync#478]
I noticed an issue with syncing DateTimeUTC stored as varchar values from Server to Client.
Here is our setup
Primary (Server) - EF builds tables using CodeFirst
Client - EF builds tables using CodeFirst
First handshake of Primary and Client, Primary provisions client for Sync and syncs data over to client
 - DateTimeUTC stored as nvarchar gets synced over to Client in correct format (2021-02-26T23:40:00.000Z)
User make a insert into Primary, data is written into DB in DateTimeUTC
- at predefined interval Primary gets synced over to Client. At this point I figure the triggers/changetracking fires for the inserted records and syncs over to Client
  -   This DateTimeUTC is in diff format (2/26/2021 11:30:00 PM)
 **Primary DB**
Param	Value
StateDa te 2021-02-26T23:30:00.000Z

**Client DB**
StartDate 2/26/2021 11:30:00 PM

I came across this
https://stackoverflow.com/questions/11856694/json-net-disable-the-deserialization-on-datetime
https://stackoverflow.com/questions/36287255/net-datetime-serialization-deserialization-bug

Could this be an issue in the library
Can you please help figure out a solution for this? Thanks in advance

**Comment by Mimetis** [comment]
Will look deeper tomorrow, it's late.
Just as info, did you see custome converter here : https://dotmimsync.readthedocs.io/SerializerConverter.html#custom-converter ?

**Comment by Mimetis** [comment]
What providers are you using ? Sql Server on primary and Sqlite on client ?
Are you storing dates on classic DateTime type in primary or is it just a nvarchar ?

**Comment by menitamoses** [comment]
I am using SqlProvider on both Primary and Client. The values in question are dynamic DatTimeUTC values and are stored as varchar in the DB for other business reasons. I looked into you custom-converter but didnt pursue implementing it.

**Comment by Mimetis** [comment]
I'm not able to reproduce.

Here is my setup:

On Sql, just create a fancy `ProductCategory` table with a `nvarchar(250)` string type to store a datetime.
``` sql
USE [master]
GO 

-- Server database
if (exists (select * from sys.databases where name = 'AdvProductCategory'))
begin
	ALTER DATABASE AdvProductCategory SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE AdvProductCategory
End
Create database AdvProductCategory
Go
-- Client database. No need to create the schema, Dotmim.Sync will do
if (exists (select * from sys.databases where name = 'Client'))
begin
	ALTER DATABASE [Client] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [Client]
End
Create database [Client]
GO
Use AdvProductCategory;

CREATE TABLE [dbo].[ProductCategory](
	[ProductCategoryID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[ModifiedDate] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_ProductCategory_ProductCategoryID] PRIMARY KEY CLUSTERED 
([ProductCategoryID] ASC ))
```
And the code I'm using to reproduce:
I'm just forcing to store date as string in the database


First, I'm making a new sync to initialize and create the client database
``` cs
var localDateTime = DateTime.Now;
var utcDateTime = DateTime.UtcNow;

var localOrchestrator = new WebClientOrchestrator(serviceUri, SerializersCollection.JsonSerializer);

var agent = new SyncAgent(clientProvider, localOrchestrator, options);
await agent.SynchronizeAsync(localProgress);

```
Then i'm inserting data (and date as string) in the client database using Local or UTC datetime:
``` cs

string commandText = "Insert into ProductCategory (Name, ModifiedDate) Values (@Name, @ModifiedDate)";
var connection = clientProvider.CreateConnection();

connection.Open();

var command = connection.CreateCommand();
command.CommandText = commandText;
command.Connection = connection;

var p = command.CreateParameter();
p.DbType = DbType.String;
p.ParameterName = "@Name";
p.Value = "TestUTC";
command.Parameters.Add(p);

p = command.CreateParameter();
// Change DbTtpe to String for testing purpose
p.DbType = DbType.String;
p.ParameterName = "@ModifiedDate";
p.Value = utcDateTime;
command.Parameters.Add(p);

command.ExecuteNonQuery();

command.Parameters["@Name"].Value = "TestLocal";
command.Parameters["@ModifiedDate"].Value = localDateTime;
command.ExecuteNonQuery();


connection.Close();

// check
connection.Open();

commandText = "Select * from ProductCategory where Name='TestUTC'";
command = connection.CreateCommand();
command.CommandText = commandText;
command.Connection = connection;

var dr = command.ExecuteReader();
dr.Read();

Console.WriteLine($"UTC : {utcDateTime} - {dr["ModifiedDate"]}");

dr.Close();


commandText = "Select * from ProductCategory where Name='TestLocal'";
command = connection.CreateCommand();
command.CommandText = commandText;
command.Connection = connection;

dr = command.ExecuteReader();
dr.Read();

Console.WriteLine($"Local : {localDateTime} - {dr["ModifiedDate"]}");

dr.Close();

connection.Close();

Console.WriteLine("Sync");


```
Then I'm making a new sync and check results:
``` cs

var s = await agent.SynchronizeAsync(localProgress);
Console.WriteLine(s);

// check results on server
connection = serverProvider.CreateConnection();

// check
connection.Open();

commandText = "Select * from ProductCategory where Name='TestUTC'";
command = connection.CreateCommand();
command.CommandText = commandText;
command.Connection = connection;

dr = command.ExecuteReader();
dr.Read();

Console.WriteLine($"UTC : {utcDateTime} - {dr["ModifiedDate"]}");

dr.Close();

commandText = "Select * from ProductCategory where Name='TestLocal'";
command = connection.CreateCommand();
command.CommandText = commandText;
command.Connection = connection;

dr = command.ExecuteReader();
dr.Read();

Console.WriteLine($"Local : {localDateTime} - {dr["ModifiedDate"]}");

dr.Close();

connection.Close();


```

The server side is pretty standard:
``` cs
[HttpPost]
public async Task Post() => await webServerManager.HandleRequestAsync(this.HttpContext);

```

The results are consistant.
Can you help me to figure out where your bug is happening in this scenario ?

**Comment by menitamoses** [comment]
Thank you for the code sample. I tried it on my Dev setup in a simple console application and didnt see the issue we are seeing in our application. It could be that Newtonsoft serialization setting elsewhere in our application is contributing to this weird behavior. I am going to try setting a 'pass' of the DefaultSetting in the JsonConvert object and see if it makes a difference
