### ISSUE TITLE
Xamarin.Forms for iOS JSON issues with Utf8Json

### ISSUE THREAD

**Issue by JoshJacobAtHanson** [Mimetis/Dotmim.Sync#480]
While running a Xamarin.Forms project with Dotmim.Sync 0.6.1+ we are seeing the following exception from Dotmim.Sync.Serialization.Utf8JsonConverter:

```System.TypeInitializationException: The type initializer for 'Utf8Json.Resolvers.StandardResolver' threw an exception.
  System.TypeInitializationException: The type initializer for 'Utf8Json.Resolvers.Internal.DefaultStandardResolver' threw an exception.
    System.TypeInitializationException: The type initializer for 'InnerResolver' threw an exception.
      System.TypeInitializationException: The type initializer for 'Utf8Json.Resolvers.DynamicObjectResolver' threw an exception.
        System.TypeInitializationException: The type initializer for 'Utf8Json.Resolvers.Internal.DynamicObjectResolverAllowPrivateFalseExcludeNullFalseNameMutateOriginal' threw an exception.
          System.PlatformNotSupportedException: Operation is not supported on this platform.
```

According to the author of Utf8Json, use on iOS requires precode generation: https://github.com/neuecc/Utf8Json/issues/74#issuecomment-384912715

While investigating, I was able to switch from Utf8JsonConverter to the previous JsonConverter in BatchPartInfo.cs without running into that problem. Would it be possible to have JSON library selection be a global setting that we could adjust per platform?

**Comment by Mimetis** [comment]
Hey @JoshJacobAtHanson 
Thanks for the feedback

Can you try to force using the Json.Net library ?

``` cs
var localOrchestrator = new WebClientOrchestrator(serviceUri, SerializersCollection.JsonSerializer);
```
If there is an issue with `Utf8Json` by default with Xamarin on iOS, I guess I will revert back to JSON.NET as the default serializer in the next release.
Meanwhile, you can use this tip to force the serializer.

Thanks for the feedback !

**Comment by JoshJacobAtHanson** [comment]
@Mimetis Thanks for the quick reply.

Forcing the Json.Net library did not work, however, I think it's because the BatchPartInfo serializers are hardcoded to Utf8Json:

https://github.com/Mimetis/Dotmim.Sync/blob/f4731c68b2a27b51da724035fa9c09f2728bdffa/Projects/Dotmim.Sync.Core/Batch/BatchPartInfo.cs#L101
https://github.com/Mimetis/Dotmim.Sync/blob/f4731c68b2a27b51da724035fa9c09f2728bdffa/Projects/Dotmim.Sync.Core/Batch/BatchPartInfo.cs#L137

If the BatchPartInfo class could pull the serializer from the local orchestrator, then I think that would work.

**Comment by Mimetis** [comment]
Ok, I will fix that in the next commit
Will come back to JSON.NET as default and will try to make the batch part info accessible to this option (but not sure It will be possible)
