### ISSUE TITLE
Export Views

### ISSUE THREAD

**Issue by PardeepBhandari** [Mimetis/Dotmim.Sync#481]
Hi

Can i export views, function, stored procedure. Sql server database to sqlite database.

Thanks

**Comment by Mimetis** [comment]
I dont understand what you want to do
Can you elaborate a little bit more ?

**Comment by PardeepBhandari** [comment]
I have some views scaler functions and stored procedure in sql database which i use in my sql queries for reporting porposes
can i create migrate these objects to sqlite database

**Comment by Mimetis** [comment]
Nop sorry, `DMS` is all about **sync** data; not replicate a schema :)
