### ISSUE TITLE
No more access for user till 0.6.2

### ISSUE THREAD

**Issue by sylverbee** [Mimetis/Dotmim.Sync#482]
Everything was working well with DMS 0.6.1.

I upgraded to 0.6.2 and DMS returns each time the same error when running SynchronizeAsync: `One or more errors occurred. (Access denied for user '***' (using password: YES))`

**Comment by Mimetis** [comment]
Hum, can you show more details about this error ?

**Comment by sylverbee** [comment]
No, unfortunatly. That's the only message I get from DMS.
I'm investigating around mySQL server. Maybe something has changed...
