### ISSUE TITLE
Could not find stored procedure 'dbo.Companies_ParamCompanyId_changes' SetupFilter

### ISSUE THREAD

**Issue by maxrodro** [Mimetis/Dotmim.Sync#486]
Good morning, I have a problem trying to use the SetupFilter by adding a parameter to the Companies table.

I have nuget version
Dotmim.Sync.SqlServer (0.6.2)
Dotmim.Sync.SqlServer.ChangeTracking (0.6.2)

This is the code used and its response.

```
string serverConnectionString = "Azure SQL";
string clientConnectionString = "Localhost/SQLExpress";

var serverProvider = new SqlSyncChangeTrackingProvider(serverConnectionString);
var clientProvider = new SqlSyncProvider(clientConnectionString);

// Tables involved in the sync process:
//var tables = new string[] { "Accounts", "AccountSettings", "Companies" };

var setup = new SyncSetup(new string[] { "Accounts", "AccountSettings", "Companies" });

var companyFilter = new SetupFilter("Companies");
companyFilter.AddParameter("ParamCompanyId", System.Data.DbType.String, false, null);
companyFilter.AddWhere("CompanyId", "Companies", "ParamCompanyId");

setup.Filters.Add(companyFilter);

// Creating an agent that will handle all the process
var agent = new SyncAgent(clientProvider, serverProvider, setup);
agent.Parameters.Add("ParamCompanyId", "123");

var progress = new SynchronousProgress<ProgressArgs>(pa => Console.WriteLine($"{pa.PogressPercentageString}\t{pa.Message}"));

var s1 = agent.SynchronizeAsync(progress).Result;
```

Result:
Dotmim.Sync.SyncException: **Could not find stored procedure 'dbo.Companies_ParamCompanyId_changes**'.\r\n ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Could not find stored procedure 'dbo.Companies_Name_changes'.\r\n   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dotmim.Sync.BaseOrchestrator.InternalGetChangesAsync(SyncContext context, MessageGetChangesBatch message, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)\r\n   at Dotmim.Sync.LocalOrchestrator.<>c__DisplayClass5_0.<<GetChangesAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)\r\nClientConnectionId:8fd89dc9-651e-4c53-a95c-ac60cb11745c\r\nError Number:2812,State:62,Class:16\r\n   --- End of inner exception stack trace ---\r\n   at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception)\r\n   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)\r\n   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)\r\n   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress)

**Comment by Mimetis** [comment]
I guess you have made multiple tests, using (or not) filters ?

Maybe the setup configuration has failed at some point when migration was internally applied.

When you have this kind of error, you can try to `Deprovision` then `Provision` again everything.
This is the kind of step you want to do when you are changing your `SyncSetup` instance.

If you're making tests only, you may try to start with a fresh database with nothing provisionned.

Or you can Deprovision everything and start again 

``` cs
// Create providers
var serverProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(serverDbName));
var localProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(clientDbName));

// Create standard Setup and Options
var setup = new SyncSetup(new string[] { "Address", "Customer", "CustomerAddress" });
var options = new SyncOptions();

// Create orchestrators
var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);
var localOrchestrator = new LocalOrchestrator(serverProvider, options, setup);

// Deprovision everything
await remoteOrchestrator.DeprovisionAsync(SyncProvision.StoredProcedures
    | SyncProvision.Triggers | SyncProvision.TrackingTable 
    | SyncProvision.ServerScope | SyncProvision.ServerHistoryScope);

await localOrchestrator.DeprovisionAsync(SyncProvision.StoredProcedures
    | SyncProvision.Triggers | SyncProvision.TrackingTable 
    | SyncProvision.ClientScope);
```
At this point, you should have a database completely deprovisioned and you're good to make a new test

That being said, it's still a bug since you may not encountered this error... 
If you're able to reproduce it and show me HOW to reproduce the bug, I can find what's happening and fix it

**Comment by maxrodro** [comment]
Do what is indicated by your person without success.

What did I do?
1. I had a database with CHANGE_TRACKING = ON
2. Run the basic server and client test code (Everything worked fine)
      https://dotmimsync.readthedocs.io/Overview.html#tutorial-first-sync

3. I tried now to use the filters and here it failed.


Anything else I can try?

**Comment by Mimetis** [comment]
Can you show me the code you are using based on the tutorial ?

**Comment by maxrodro** [comment]
`string serverConnectionString = "Azure SQL";
string clientConnectionString = "Localhost/SQLExpress";

var serverProvider = new SqlSyncChangeTrackingProvider(serverConnectionString);
var clientProvider = new SqlSyncProvider(clientConnectionString);

// Tables involved in the sync process:
//var tables = new string[] { "Accounts", "AccountSettings", "Companies" };

var setup = new SyncSetup(new string[] { "Accounts", "AccountSettings", "Companies" });

var companyFilter = new SetupFilter("Companies");
companyFilter.AddParameter("ParamCompanyId", System.Data.DbType.String, false, null);
companyFilter.AddWhere("CompanyId", "Companies", "ParamCompanyId");

setup.Filters.Add(companyFilter);

// Creating an agent that will handle all the process
var agent = new SyncAgent(clientProvider, serverProvider, setup);
agent.Parameters.Add("ParamCompanyId", "123");

var progress = new SynchronousProgress<ProgressArgs>(pa => Console.WriteLine($"{pa.PogressPercentageString}\t{pa.Message}"));

var s1 = agent.SynchronizeAsync(progress).Result;`

**Comment by Mimetis** [comment]
This is not the schema used in the tutorial, right ?

**Comment by maxrodro** [comment]
It is my code modified to my environment, using code based on the tutorial link.

Can you explain to me what you need exactly?

**Comment by Mimetis** [comment]
I think you've found a bug :)
The migration does not create the stored procedures when you are adding a filter in an existing table (that has been already synced one time at least)

My advice (until the next release and the fix):

Do not change your `SyncSetup` once you have done some synchronizations
If you really need to add or remove tables, filters in your `SyncSetup`, be sure you Deprovision the Provision again your databases

I will post an update once the issue is fixed

Thanks a lot for finding this issue !
