### ISSUE TITLE
Add Prefix in SyncSetup

### ISSUE THREAD

**Issue by maxrodro** [Mimetis/Dotmim.Sync#490]
Hi there,

Today I continue with tests of this great tool and I am in the part of the prefixes in the tables and stored procedures, before doing this step, I did a Deprovision (Client and Server) so that everything was clean.

I made this simple code indicated by the documentation

My Code:
if the tables, stored procedures, were generated from the Azure database side, but not from the SQLExpress

```
string serverConnectionString = "Azure DB";
string clientConnectionString = "SQLExpress";

var serverProvider = new SqlSyncChangeTrackingProvider(serverConnectionString);
var clientProvider = new SqlSyncProvider(clientConnectionString);

 var tables = new string[] { "Accounts", "AccountSettings", "Companies" };
 var options = new SyncOptions();
var setup = new SyncSetup(tables)
{
    StoredProceduresPrefix = "Sync",
    TrackingTablesPrefix = "Sync",
    TriggersPrefix = "Sync",
};

var agent = new SyncAgent(clientProvider, serverProvider, options, setup);
var s2 = await agent.SynchronizeAsync();

// Write results
Console.WriteLine(s2);
```

But I got this error, did I do something wrong, or is it a BUG
This column (Test2) I added in the last test and it is in both databases and they have data synchronized without problems

`Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Test2'.\r\nInvalid column name 'Test2'.\r\nInvalid column name 'Test2'.\r\nInvalid column name 'Test2'.\r\nInvalid column name 'Test2'.\r\nInvalid column name 'Test2'.\r\n   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)\r\n   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)\r\n   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dotmim.Sync.BaseOrchestrator.InternalCreateTriggerAsync(SyncContext ctx, DbTableBuilder tableBuilder, DbTriggerType triggerType, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)\r\n   at Dotmim.Sync.BaseOrchestrator.InternalCreateTriggersAsync(SyncContext ctx, Boolean overwrite, DbTableBuilder tableBuilder, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)\r\n   at Dotmim.Sync.BaseOrchestrator.InternalProvisionAsync(SyncContext ctx, Boolean overwrite, SyncSet schema, SyncProvision provision, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)\r\n   at Dotmim.Sync.BaseOrchestrator.<>c__DisplayClass80_0.<<ProvisionAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)\r\nClientConnectionId:d6656443-5b48-4854-bf16-04b0f40d0cf3\r\nError Number:207,State:1,Class:16`

**Comment by maxrodro** [comment]
Hi @Mimetis , any idea about the topic or was it that I did something wrong?

**Comment by Mimetis** [comment]
will look into it on monday :)
can you share the schema of your table Test ?

**Comment by maxrodro** [comment]
I can't share it because I deleted the database, I made another one to continue testing, I'm looking for all possible scenarios, but I can share a similar one that I have right now

`/****** Object:  Table [dbo].[Accounts]    Script Date: 12/3/2021 17:00:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Accounts](
	[AccountId] [uniqueidentifier] NOT NULL,
	[AccountName] [nvarchar](50) NOT NULL,
	[PasswordAdmin] [nvarchar](100) NOT NULL,
	[PasswordAppInstallation] [nvarchar](10) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Licenses] [int] NOT NULL,
	[IsActive] [bit] NOT NULL,
	[Email] [nvarchar](50) NULL,
	[CreatedAt] [datetimeoffset](7) NOT NULL,
	[UpdateAt] [datetimeoffset](7) NOT NULL,
 CONSTRAINT [PK_Accounts] PRIMARY KEY CLUSTERED 
(
	[AccountId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AccountSettings]    Script Date: 12/3/2021 17:00:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AccountSettings](
	[AccountSettingId] [uniqueidentifier] NOT NULL,
	[AccountId] [uniqueidentifier] NOT NULL,
	[AccountSettingName] [nvarchar](50) NOT NULL,
	[AccountSettingValue] [nvarchar](50) NOT NULL,
	[AccountSettingType] [nvarchar](10) NOT NULL,
	[CreatedAt] [datetimeoffset](7) NOT NULL,
	[UpdateAt] [datetimeoffset](7) NOT NULL,
 CONSTRAINT [PK_AccountSettings] PRIMARY KEY CLUSTERED 
(
	[AccountSettingId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Companies]    Script Date: 12/3/2021 17:00:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Companies](
	[CompanyId] [uniqueidentifier] NOT NULL,
	[AccountId] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Logo] [nvarchar](50) NULL,
	[Address] [nvarchar](500) NULL,
	[Phone] [nvarchar](50) NULL,
	[CountryId] [nvarchar](2) NULL,
	[TimeZone] [nvarchar](50) NULL,
	[CreatedAt] [datetimeoffset](7) NOT NULL,
	[UpdateAt] [datetimeoffset](7) NOT NULL,
 CONSTRAINT [PK_Companies] PRIMARY KEY CLUSTERED 
(
	[CompanyId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Companies]  WITH NOCHECK ADD  CONSTRAINT [FK_Companies_Accounts] FOREIGN KEY([AccountId])
REFERENCES [dbo].[Accounts] ([AccountId])
GO
ALTER TABLE [dbo].[Companies] NOCHECK CONSTRAINT [FK_Companies_Accounts]
GO

`

**Comment by Mimetis** [comment]
I have tested with your 3 tables, and everything worked for me 

``` cs
// Create 2 Sql Sync providers
var serverProvider = new SqlSyncChangeTrackingProvider(DBHelper.GetDatabaseConnectionString(serverDbName));
var clientProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(clientDbName));

var options = new SyncOptions()
{
    BatchSize = 1000,
    DisableConstraintsOnApplyChanges = false
};

var setup = new SyncSetup(new string[] { "Accounts", "AccountSettings", "Companies" })
{
    StoredProceduresPrefix = "Sync",
    TrackingTablesPrefix = "Sync",
    TriggersPrefix = "Sync",
};

// Creating an agent that will handle all the process
var agent = new SyncAgent(clientProvider, serverProvider, options, setup);

// Using the Progress pattern to handle progession during the synchronization
var progress = new SynchronousProgress<ProgressArgs>(s =>
{
    Console.ForegroundColor = ConsoleColor.Green;
    Console.WriteLine($"{s.PogressPercentageString}:\t{s.Source}:\t{s.Message}");
    Console.ResetColor();
});

do
{
    try
    {
        var r = await agent.SynchronizeAsync(SyncType.Reinitialize, progress);
        Console.WriteLine(r);
    }
    catch (Exception e)
    {
        Console.WriteLine(e.Message);
    }

} while (Console.ReadKey().Key != ConsoleKey.Escape);
```
The objects have been created normally

![image](https://user-images.githubusercontent.com/4592555/111135750-52b60980-857d-11eb-81f3-e788ecdcdf2f.png)

**Comment by maxrodro** [comment]
Hi @Mimetis , do this test, create a column, for a data in it, transfer that column and data to the client, then do a Deprovision, try to create the prefixes.

To continue in the tests, I deleted the databases and did it again without problems in the generation of the prefixes

**Comment by Mimetis** [comment]
Can you create a simple repro ?

**Comment by Mimetis** [comment]
Hello @maxrodro 

Here is my test, with a filter, and a setup changing after a first sync (add prefixes and one table):

```cs
var options = new SyncOptions();
var setup = new SyncSetup(new string[] { "Customer" });

// Filtered columns. 
setup.Tables["Customer"].Columns.AddRange(new string[] { "CustomerID", "EmployeeID", "NameStyle", "FirstName", "LastName" });

// Add the filter
setup.Filters.Add("Customer", "EmployeeID");

// Create agent with filtered tables and parameter
var agent = new SyncAgent(client.Provider, Server.Provider, options, setup);
agent.Parameters.Add("EmployeeID", 1);

var s = await agent.SynchronizeAsync();

Assert.Equal(2, s.ChangesAppliedOnClient.TotalAppliedChanges);

// Deprovision everything on the local database
var localOrchestrator = agent.LocalOrchestrator;
await agent.LocalOrchestrator.DeprovisionAsync();

// Adding a new table
setup.Tables.Add("Employee");

// Adding prefixes
setup.StoredProceduresPrefix = "sync";
setup.StoredProceduresSuffix = "sp";
setup.TrackingTablesPrefix = "track";
setup.TrackingTablesSuffix = "tbl";
setup.TriggersPrefix = "trg";
setup.TriggersSuffix = "tbl";

// Create a new agent
agent = new SyncAgent(client.Provider, Server.Provider, options, setup);
agent.Parameters.Add("EmployeeID", 1);

// Sync again.
// Local database will be provisioned with new setup
// Server database will be migrated, comparing old setup with new setup
s = await agent.SynchronizeAsync();
Assert.Equal(5, s.ChangesAppliedOnClient.TotalAppliedChanges);
```

It's working well for me, do you see any difference between you and me ?

**Comment by maxrodro** [comment]
Hi, there really is not much difference in the code, I am going to rule it out as an error, it may be the number of tests I carry out and at some point it got corrupted

**Comment by Mimetis** [comment]
`DMS` is basically a sync framework.
It's not meant to change every day the config ;)
Try to get the good one for you and stick with it
