### ISSUE TITLE
Fetch Conflict Table/Row information without manual conflict resolution

### ISSUE THREAD

**Issue by menitamoses** [Mimetis/Dotmim.Sync#491]
This is not really an issue, but not sure how to pose the question.
I am using the built in conflict resolution with policy of ServerWins. During Sync I occasionally see Conflict: #count report in the log. But I don't have the conflicted table/row information. According to the documentation, if I manually intercept ApplyChangedFailed  and write my own resolution I will have access to objects that have the information but I dont want to go that far in overriding the built in conflict resolution. My setup is simple enough to not warrant that, however I would like to write the conflict information to our Logs. Is there a way to do that? I also came across your sample project 'Spy' to peak into several events during Sync but none of those actually have more information on the conflicts.
Here is the info I have in my logs:
2021-03-11 16:45:29,198 46  INFO  SAAnnounceRevolution.Redundancy.SyncService+<SyncDataAsync>d__8.MoveNext Synchronization done. 
	Total changes  uploaded: 0
	Total changes  downloaded: 42 
	Total changes  applied: 36 
	Total resolved conflicts: 6
	Total duration :0:0:0.515

**Comment by Mimetis** [comment]
Intercept `ApplyChangedFailed`, get the info you need, and log them ?

**Comment by menitamoses** [comment]
But I dont want to manually resolve the conflict. I only want to log the conflict records. In your documentation you say:

**[Handling conflicts manually
If you decide to manually resolve a conflict, the ConflictResolutionPolicy option will be ignored.
To be able to resolve a conflict, you just have to Intercept the ApplyChangedFailed method and choose the correct [version.]()**](https://dotmimsync.readthedocs.io/Conflict.html?highlight=conflict)

If I intercept it, wouldnt it mean that I have to also manually resolve it?

**Comment by Mimetis** [comment]
Yes, indeed, you have to specify a resolution if intercepting `ApplyChangedFailed`

You can do something like
``` cs
agent.OnApplyChangesFailed(args =>
{
    args.Resolution = agent.Options.ConflictResolutionPolicy == ConflictResolutionPolicy.ClientWins ? ConflictResolution.ClientWins : ConflictResolution.ServerWins;
    // Log
    this.Log.....
});
```
But I guess we can do something better from the logging perspective.
Are you using the Logger to get details or do you need something else ?

**Comment by Mimetis** [comment]
I have added information to the log output even if you're not intercepting the ApplyChangedFailed event.

**Comment by menitamoses** [comment]
Fantastic! Yes, I am using the Logger to do logging and also passing ProgressArgs in the SynchronizeAsync() call to log the sync progress

**Comment by Mimetis** [comment]
You have everything in the branch  [v0.7.1 branch](https://github.com/Mimetis/Dotmim.Sync/tree/v0.7.1)
Let me know if it's enough :)

**Comment by menitamoses** [comment]
Thank you for quick response. I will upgrade and try again
