### ISSUE TITLE
'Dotmim.Sync.SyncException' in System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by Menci77** [Mimetis/Dotmim.Sync#493]
I did the first steps as it was shown, I tried to sync for the first time on the server side (it is an UWP app), but I get an error and I don't know why or what is the problem.
The message: Exception thrown: 'Dotmim.Sync.SyncException' in System.Private.CoreLib.dll
It does not says anything else, so I have no idea where it comes from.
When I try to get string from the SyncResult I get an ArgumentNull exception, so something goes wrong before, because the result is not created.
Has anyone met this problem before or has any idea what I should check or try?
[code.txt](https://github.com/Mimetis/Dotmim.Sync/files/6130251/code.txt)

**Comment by Mimetis** [comment]
Do you have more info from the stack trace ?

**Comment by Menci77** [comment]
No I don't. It is strange, because when this exception is thrown the app doesn't stop, only when I try to get the SyncResult, but it is null.
![image](https://user-images.githubusercontent.com/61515787/110976189-e52d9180-8360-11eb-9ab9-aa716da0621d.png)

**Comment by Mimetis** [comment]
Try on .net core 3.1 ?

**Comment by Menci77** [comment]
UWP apps currently does not support .Net Core 3.0

**Comment by Menci77** [comment]
I disabled "just my code" to see more, and I got a lot more exceptions
![image](https://user-images.githubusercontent.com/61515787/111024861-2ebdc100-83e1-11eb-95e2-d51ce685f637.png)

**Comment by Menci77** [comment]
I made a WPF app which supports .net core 3.1, and tried to run the same code but it still doesn't work.
![image](https://user-images.githubusercontent.com/61515787/111025423-4e0a1d80-83e4-11eb-86db-75766d2641cb.png)

**Comment by Mimetis** [comment]
can you try with the last pre-release version ? (0.7.0-beta)

**Comment by Menci77** [comment]
The simple console application gives the same errors as before
![error2](https://user-images.githubusercontent.com/61515787/111136124-ad4f6580-857d-11eb-88f3-e0f8da52779c.png)

And when I tried the UWP app with the pre-release version, I got this exception
![error1](https://user-images.githubusercontent.com/61515787/111136233-cc4df780-857d-11eb-980f-63455d57ad90.png)

**Comment by Mimetis** [comment]
Can you show me the code you are using in your console application ?

**Comment by Menci77** [comment]
Sure,
![image](https://user-images.githubusercontent.com/61515787/111136659-441c2200-857e-11eb-802d-00f13062a2c2.png)

**Comment by Mimetis** [comment]
try 
``` cs
private static async Task Main(string[] args)
{
        await SynchronizeAsync();
}
```
of if you are not using C# 8

``` cs
    private static Task Main(string[] args)
    {
        SynchronizeAsync().GetAwaiter().GetResult();
    }

```

**Comment by Menci77** [comment]
This is what I get
![image](https://user-images.githubusercontent.com/61515787/111137674-5cd90780-857f-11eb-9972-8b2a09434de7.png)
![image](https://user-images.githubusercontent.com/61515787/111137748-737f5e80-857f-11eb-8ad3-53b63fd6f911.png)

**Comment by Mimetis** [comment]
Do you have an `xml` column somewhere ?
If yes, it's not supported by `DMS`

**Comment by Menci77** [comment]
Yes, it turns out that I have. 
I guess I will have to delete them, and then I try again the code.
Thanks

**Comment by Menci77** [comment]
So now my console application work
![done](https://user-images.githubusercontent.com/61515787/111149305-04a90200-858d-11eb-8c36-e69d3e171723.png)
But there is still two exception
![but](https://user-images.githubusercontent.com/61515787/111149358-14c0e180-858d-11eb-911f-3d9a29efd423.png)
And my uwp app still doesn't work, which was the original problem
![err](https://user-images.githubusercontent.com/61515787/111149433-2904de80-858d-11eb-840d-344397c5e0b3.png)

**Comment by Menci77** [comment]
Can you suggest any idea where/how to call the synchronization method? Because I was trying in the App(), but it can't be async, and I need it to be so I can use "await SynchDatabase()"

**Comment by Mimetis** [comment]
call it from a button handler, i guess ?

**Comment by Menci77** [comment]
Sadly the same exceptions remain

**Comment by Mimetis** [comment]
Sadly I can't help if you don't share any code :(
And please, don't use images to share your code, and use markdown script
Will be easier for me to grab and test your code, if neededf

**Comment by Menci77** [comment]
Yeah, sorry
Here is the whole project
[HumanResources.zip](https://github.com/Mimetis/Dotmim.Sync/files/6141854/HumanResources.zip)

**Comment by Mimetis** [comment]
I don't need the whole project. Please next time use markdown code, as I do now.

1) You need to use special folders when using UWP application and sqlite folder.
``` cs
private string sqliteConnectionString = Path.Combine(ApplicationData.Current.LocalFolder.Path, "Client.db");
```
2) Try to use last version of DMS (version `0.7.0`)

I tried and everything worked fine for me (with a different database)

**Comment by Menci77** [comment]
Then I don't know what is wrong with my app. I use microsoft's sample database AdventureWorks2019, and Client.db is an empty database file. And it worked with the console application.
I changed the sqlite connection string to the one above.
I'm using the latest version, but still there are a lot of exceptions.

**Comment by Mimetis** [comment]
I'm sorry, will not be able to help you more on this...
Can we close this issue, since it seems it's not related to `DMS` ?
