### ISSUE TITLE
Impossible to sync in Release mode

### ISSUE THREAD

**Issue by sylverbee** [Mimetis/Dotmim.Sync#494]
DMS version: 0.6.2
Server: mySQL
Local: SQLite
Table count: 10
Total rows: 1000000

When running uwp app in **debug** mode, eveything goes well.

In **release** mode, tracking tables & triggers are created in Sqlite db. But **no synchronisation starts**.

I get this error message : `One or more errors occurred. (A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.)`

How to identify what's happening?

**Comment by Mimetis** [comment]
if tracking and triggers are created then `DMS` is working, at least for creating Schema :)
We need more info to determine what's going on
If you are in release /debug mode, I assume you are using the source code  ?

**Comment by sylverbee** [comment]
Yes, schema is created. 
Yes, the source code is the same, exactly. 

I'd like to track more details. How to set up details for errors? I use serilog with a table in SQLite

**Comment by sylverbee** [comment]
I installed nuggets 0.6.3 beta 587 => everything is OK in release mode.
**There must be a bug in 0.6.2!**

**Comment by Mimetis** [comment]
It could be the json serializer, UTF8JSON, that causes this bug
It has been reverted back to JSON.NET in 0.6.3
