### ISSUE TITLE
I am trying to sync a table data using a filter one column, but filter is not applying and complete data is synced.

### ISSUE THREAD

**Issue by upendrar7** [Mimetis/Dotmim.Sync#497]
"Hello, I've a problem" Kindly help.

I am trying to sync a table data using a filter one column, but filter is not applying and complete data is synced.

Problem: I am trying to sync the data of a table between two different databases, with filter on one column of the table.
Example: As per by code and SQL query attached i trying sync the data with tentantid = 1 but the filter is not applying its syncing complete table.

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TiburonSyncTableFourteen](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerName] [varchar](50) NULL,
	[ContactName] [varchar](50) NULL,
	[Address] [varchar](100) NULL,
	[City] [varchar](50) NULL,
	[PostalCode] [varchar](15) NULL,
	[Country] [varchar](50) NULL,
	[TenantId] [int] NULL,
PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

using Dotmim.Sync;
using Dotmim.Sync.Enumerations;
using Dotmim.Sync.SqlServer;
using System;
using System.Threading.Tasks;

namespace DotMinSyncPOC
{
    class Program
    {
        static async Task Main(string[] args)
        {
            SqlSyncProvider clientProvider = new SqlSyncProvider(@"");

            SqlSyncProvider serverProvider = new SqlSyncProvider(@"");

            var setup = new SyncSetup(new string[] { "TiburonSyncTableFourteen" })
            {
                StoredProceduresPrefix = "",
                StoredProceduresSuffix = "_DOTMIN",
                TrackingTablesPrefix = "DOTMIN_",
                TrackingTablesSuffix = "",
                TriggersPrefix = "",
                TriggersSuffix = "_DOTMIN"
            };

            var tiburonSyncTableThirteenFilter = new SetupFilter("[dbo].[TiburonSyncTableThirteen]");

            tiburonSyncTableThirteenFilter.AddParameter("TenantId", "[dbo].[TiburonSyncTableThirteen]");

            tiburonSyncTableThirteenFilter.AddWhere("TenantId", "[dbo].[TiburonSyncTableThirteen]", "TenantId");

            setup.Filters.Add(tiburonSyncTableThirteenFilter);

            var agent = new SyncAgent(clientProvider, serverProvider, new SyncOptions(), setup);

            if (!agent.Parameters.Contains("TenantId"))
                agent.Parameters.Add("TenantId", 1);

            do
            {
                var s1 = await agent.SynchronizeAsync();
                Console.WriteLine(s1);
            } while (Console.ReadKey().Key != ConsoleKey.Escape);
        }
    }
}

**Comment by Mimetis** [comment]
https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

Update your post, by encapsulating your code with **```cs**

**Comment by Mimetis** [comment]
Hello upendrar7

You did not made any effort to expose clearly your problem.
It is not respectful to the OSS contributors... think about it.

That being said, I've worked on your problem, and here is the correct code you need to apply.
Look how clear is this post, with the correct formatting text and explanation.

Regarding the table; you missed the `varchar` length, I've corrected it and I've affected some random length to each column:
``` sql
if (exists (select * from sys.tables where name = 'TiburonSyncTableFourteen'))
Begin
	DROP TABLE [TiburonSyncTableFourteen]
End

CREATE TABLE [dbo].[TiburonSyncTableFourteen](
[Id] [int] IDENTITY(1,1) NOT NULL,
[CustomerName] varchar(250) NULL,
[ContactName] varchar(250) NULL,
[Address] varchar(250) NULL,
[City] varchar(50) NULL,
[PostalCode] varchar(10) NULL,
[Country] varchar(50) NULL,
[TenantId] [int] NULL,
PRIMARY KEY CLUSTERED ( [Id] ASC ))

Insert Into TiburonSyncTableFourteen(CustomerName, ContactName, Address, City, PostalCode, Country, TenantId)
Values ('John Doe', 'jod', 'Paris', 'Paris', '92000', 'France', 1);
Insert Into TiburonSyncTableFourteen(CustomerName, ContactName, Address, City, PostalCode, Country, TenantId)
Values ('Jane Doe', 'jad', 'Paris', 'Paris', '92000', 'France', 2);
```

Regarding the code, your filter was wrong. You must use the filter parameter to affect the table name and the schema.
By the way `dbo` is the default schema and can be omitted.
And the table name was false as well (`TiburonSyncTableThirteen` instead of `TiburonSyncTableFourteen`)
``` cs
// Create 2 Sql Sync providers
var serverProvider = new SqlSyncChangeTrackingProvider(DBHelper.GetDatabaseConnectionString(serverDbName));
var clientProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(clientDbName));

var setup = new SyncSetup(new string[] { "TiburonSyncTableFourteen" })
{
    StoredProceduresPrefix = "",
    StoredProceduresSuffix = "_DOTMIN",
    TrackingTablesPrefix = "DOTMIN_",
    TrackingTablesSuffix = "",
    TriggersPrefix = "",
    TriggersSuffix = "_DOTMIN"
};

var tiburonSyncTableThirteenFilter = new SetupFilter("TiburonSyncTableFourteen");
tiburonSyncTableThirteenFilter.AddParameter("TenantId", "TiburonSyncTableFourteen");
tiburonSyncTableThirteenFilter.AddWhere("TenantId", "TiburonSyncTableFourteen", "TenantId");
setup.Filters.Add(tiburonSyncTableThirteenFilter);

var agent = new SyncAgent(clientProvider, serverProvider, new SyncOptions(), setup);

if (!agent.Parameters.Contains("TenantId"))
    agent.Parameters.Add("TenantId", 1);

do
{
    var s1 = await agent.SynchronizeAsync();
    Console.WriteLine(s1);
} while (Console.ReadKey().Key != ConsoleKey.Escape);

```
I hope it will help you.
But I will not answer any other question, if you don't do any effort to be respectful of this community ;)
