### ISSUE TITLE
sync all tables implicitly ?

### ISSUE THREAD

**Issue by StevenLiSiwei** [Mimetis/Dotmim.Sync#502]
is there a way to sync all tables between two database server without explicitly declaring all tables ?

**Comment by Mimetis** [comment]
No, sorry

**Comment by VagueGit** [comment]
Perhaps I've misunderstood your question @StevenLiSiwei but we sync all tables like this
```
string sql = "SELECT name FROM sys.tables WHERE PATINDEX('%scope_%', name) = 0 AND PATINDEX('%sys%', name) = 0";
List<string> tableList = new List<string>();
using (SqlConnection con = new SqlConnection(orchestrator.Provider.ConnectionString))
{
    con.Open();
    using (SqlCommand cmd = con.CreateCommand())
    {
        cmd.CommandText = sql;
        using SqlDataReader reader = cmd.ExecuteReader();
        while (reader.Read())
        {
            tableList.Add(reader.GetString(0));
        }
    }
}
string[] tables = tableList.ToArray();
orchestrator.Setup = new SyncSetup(tables);

```

**Comment by Mimetis** [comment]
Very dangerous in my opinion.
If you're adding dynamicaly a new table, you will miss all the data of this table since the last sync (except if you know you have a new table and do a `Reinitialize` sync)
That's why there is no option in `DMS` to allow syncing all tables without explicit configuration.

**Comment by VagueGit** [comment]
It depends on the use case. If the developer of the app that uses DMS doesn't have control over the server database, that could be a problem.

However in our case, the server databases that are synced only exist as part of the app that uses DMS. Tables aren't going to appear on the server without our being aware.

It could perhaps be argued that syncing is inherently unsafe as even if sync tables must be explicitly defined, there is the risk the columns  and data will change without the developer knowing. This could result in massive unintended downloads.

So it does seem to me that in our use case where we have control over the server databases, this is quite safe and Sync All/Sync All in Schema<SCHEMA_NAME> would be useful options in DMS. Unless I've misunderstood.

**Comment by Mimetis** [comment]
I totally understand your point of view, and your method is definitively a good workaround to set all tables !
