### ISSUE TITLE
MERGE conflict in DMS 7.0

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#505]
The following exception is thrown by `SyncResult syncResult = await syncAgent.SynchronizeAsync();`

`The MERGE statement conflicted with the FOREIGN KEY SAME TABLE constraint "FK_Jobs_OrderDetails". The conflict occurred in database "AU13237", table "dbo.Jobs", column 'JobId'. The statement has been terminated.`

All jobs must appear on an order detail. Not all order details include a job.

On SQL Server the job on the order details table is defined `[JobId] [uniqueidentifier] NULL`
Order detail on the jobs table is defined `[Jobs].[OrderDetailId] [uniqueidentifier] NOT NULL`

Foreign keys
```
ALTER TABLE [dbo].[Jobs]  WITH CHECK ADD  CONSTRAINT [FK_Jobs_OrderDetails] FOREIGN KEY([OrderDetailId])
REFERENCES [dbo].[Jobs] ([JobId])

ALTER TABLE [dbo].[OrderDetails]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetails_Jobs] FOREIGN KEY([JobId])
REFERENCES [dbo].[Jobs] ([JobId])
```

This error does not occur in `DMS 6.2`. We've rolled back.

**Comment by Mimetis** [comment]
For some performances reasons, I've set the `SyncOptions.DisableConstraintsOnApplyChanges` to `false` by default.
See https://github.com/Mimetis/Dotmim.Sync/discussions/453#discussioncomment-380530 and https://github.com/Mimetis/Dotmim.Sync/issues/430#issuecomment-777344970

But it was too complicated to handle in some circumstances, that I've decided to revert back to `true` by default.

So far, I guess you can try with the last pre-release version `v0.7.1` and that should work as expected.

That's being said, what's the order you used to declare your tables ?
In your situation you may have something like `new string[] {"Jobs", "OrderDetails"}`.
It's important because `DMS` uses the table order to make insert / update / delete.

So far, if the performances are important for you, having `SyncOptions.DisableConstraintsOnApplyChanges=false` is important but be sure you have the correct order in your table definition.
Otherwise just upgrade to last version (I guess `v0.7.0` was already patched with `true` as default value)
And if you are not sure, just be sure you have `SyncOptions.DisableConstraintsOnApplyChanges=true` set in your options

**Comment by VagueGit** [comment]
I'm in Oz and have to hand over to the team in Europe now so I can't play with our sync api without disrupting them. I'll try 7.1 tmw my time and report back here.

**Comment by VagueGit** [comment]
Before I fall off my perch for the night ... I hadn't considered the order in which tables are declared. I had assumed that for inserts DMS would walk the relational hierarchy from top to bottom;  and for deletes it would walk the relational hierarchy from bottom to top.

Doesn't disabling constraints pose a risk to data integrity?

**Comment by Mimetis** [comment]
> Before I fall off my perch for the night ... I hadn't considered the order in which tables are declared. I had assumed that for inserts DMS would walk the relational hierarchy from top to bottom; and for deletes it would walk the relational hierarchy from bottom to top.

`DMS` tries to define a hierarchy, but sometimes (circular references) it could fail

> Doesn't disabling constraints pose a risk to data integrity?

Yes :)

**Comment by VagueGit** [comment]
In that case tmw I will experiment with the ordering of tables in the sync setup. I'll let you know how that goes.

**Comment by Mimetis** [comment]
can we close ?

**Comment by VagueGit** [comment]
This issue came back in `DMS 0.7.2`. I set `SyncOptions.DisableConstraintsOnApplyChanges = true` but it didn't make any difference. We've rolled back to `DMS 0.6.2`.

**Comment by Mimetis** [comment]
came back ? does it mean it worked on `v0.7.0` ?

**Comment by VagueGit** [comment]
My apologies. Poor choice of words by me. I can't confirm if it was fixed in `v0.7.0` as I only checked `v0.7.2`.

**Comment by Mimetis** [comment]
OK, thanks. 
I will try more tests., but honestly, it should work ...

**Comment by Mimetis** [comment]
@VagueGit I need a sample reproducing the bug, because all the tests I've done so far are good, and `SyncOptions.DisableConstraintsOnApplyChanges` works correctly.

**Comment by VagueGit** [comment]
This is the relevant snippet of the OrderDetails table
```
CREATE TABLE [dbo].[OrderDetails](
	[OrderDetailId] [uniqueidentifier] NOT NULL,
	[JobId] [uniqueidentifier] NULL,
 CONSTRAINT [PK_OrderDetails] PRIMARY KEY CLUSTERED 
(
	[OrderDetailId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]')
```

Also the relevant snippet of the Jobs table
```
CREATE TABLE [dbo].[Jobs](
	[JobId] [uniqueidentifier] NOT NULL,
	[OrderDetailId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Jobs] PRIMARY KEY CLUSTERED 
(
	[JobId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]')

```
and the foreign key constraint on the OrderDetails table referencing the Jobs table
```
ALTER TABLE [dbo].[Jobs] ADD  CONSTRAINT [FK_Jobs_OrderDetails] FOREIGN KEY([OrderDetailId])
REFERENCES [dbo].[Jobs] ([JobId])
```

and the foreign key contraint on the Jobs table referencing the OrderDetails table
```
ALTER TABLE [dbo].[OrderDetails] ADD  CONSTRAINT [FK_OrderDetails_Jobs] FOREIGN KEY([JobId])
REFERENCES [dbo].[Jobs] ([JobId])
```

For inserts we add the OrderDetail without the JobId, then add the Job to the Jobs table, then add the JobId to the OrderDetail.

`DMD 0.6.2` manages this just fine. We're happy with constraints being disabled for syncing.

**Comment by Mimetis** [comment]
You have an error in your script (`ALTER TABLE [dbo].[Jobs] ADD  CONSTRAINT [FK_Jobs_OrderDetails] FOREIGN KEY([OrderDetailId]) REFERENCES [dbo].[OrderDetails] ([OrderDetailId])`)

Anyway, here is the script I used.
Since you have a circular reference, I assume the client database is not created by `DMS` but is already existing:

``` sql
-- Server database
USE [master]
GO 

if (exists (select * from sys.databases where name = 'AdventureWorks'))
Begin
	ALTER DATABASE [AdventureWorks] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [AdventureWorks]
End
Create database [AdventureWorks]
Go
-- Client database.
if (exists (select * from sys.databases where name = 'Client'))
Begin
	ALTER DATABASE [Client] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [Client]
End
Create database [Client]
GO

Use Client
GO
CREATE TABLE [dbo].[OrderDetails](
	[OrderDetailId] [uniqueidentifier] NOT NULL,
	[JobId] [uniqueidentifier] NULL,
 CONSTRAINT [PK_OrderDetails] PRIMARY KEY CLUSTERED ([OrderDetailId] ASC))

GO
CREATE TABLE [dbo].[Jobs](
	[JobId] [uniqueidentifier] NOT NULL,
	[OrderDetailId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Jobs] PRIMARY KEY CLUSTERED ([JobId] ASC))

GO
ALTER TABLE [dbo].[Jobs] ADD  CONSTRAINT [FK_Jobs_OrderDetails] FOREIGN KEY([OrderDetailId])
REFERENCES [dbo].[OrderDetails] ([OrderDetailId])

ALTER TABLE [dbo].[OrderDetails] ADD  CONSTRAINT [FK_OrderDetails_Jobs] FOREIGN KEY([JobId])
REFERENCES [dbo].[Jobs] ([JobId])

GO
USE [AdventureWorks]
GO

CREATE TABLE [dbo].[OrderDetails](
	[OrderDetailId] [uniqueidentifier] NOT NULL,
	[JobId] [uniqueidentifier] NULL,
 CONSTRAINT [PK_OrderDetails] PRIMARY KEY CLUSTERED ([OrderDetailId] ASC))

GO

CREATE TABLE [dbo].[Jobs](
	[JobId] [uniqueidentifier] NOT NULL,
	[OrderDetailId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Jobs] PRIMARY KEY CLUSTERED ([JobId] ASC))

GO

ALTER TABLE [dbo].[Jobs] ADD  CONSTRAINT [FK_Jobs_OrderDetails] FOREIGN KEY([OrderDetailId])
REFERENCES [dbo].[OrderDetails] ([OrderDetailId])

ALTER TABLE [dbo].[OrderDetails] ADD  CONSTRAINT [FK_OrderDetails_Jobs] FOREIGN KEY([JobId])
REFERENCES [dbo].[Jobs] ([JobId])

GO
declare @orderDetailId uniqueidentifier = newid();
declare @jobId uniqueidentifier = newid();

INSERT [dbo].[OrderDetails] ([OrderDetailId], [JobId]) VALUES (@orderDetailId, null);
INSERT [dbo].[Jobs] ([JobId], [OrderDetailId]) VALUES (@jobId, @orderDetailId);
UPDATE [dbo].[OrderDetails] Set [JobId]=@jobId WHERE [OrderDetailId] = @orderDetailId;

```

I'm using an HTTP scenario.
Then my client console app is:

``` cs
var clientOptions = new SyncOptions()
{
    DisableConstraintsOnApplyChanges = true
};

var localOrchestrator = new WebClientOrchestrator(serviceUri);

var agent = new SyncAgent(clientProvider, localOrchestrator, clientOptions);

var localProgress = new SynchronousProgress<ProgressArgs>(s =>
{
    Console.ForegroundColor = ConsoleColor.Green;
    Console.WriteLine($"{s.PogressPercentageString}:\t{s.Message}");
    Console.ResetColor();
});

var s = await agent.SynchronizeAsync(localProgress);
Console.WriteLine(s);
```

The server side code is:
``` cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    // [Required]: Handling multiple sessions
    services.AddMemoryCache();

    var serverOptions = new SyncOptions()
    {
         DisableConstraintsOnApplyChanges = true,
    };
    var setup = new SyncSetup(new string[] { "OrderDetails", "Jobs" });
    services.AddSyncServer<SqlSyncProvider>(serverProviderConnectionString, setup, serverOptions);
}
```
The server controller is pretty straightforward:

```cs
[HttpPost]
public async Task Post() => await webServerManager.HandleRequestAsync(this.HttpContext);
```

SO, when I set `DisableConstraintsOnApplyChanges` to `false` on **both sides** (server side and client side) then I have an error raised: `The MERGE statement conflicted with the FOREIGN KEY constraint "FK_Jobs_OrderDetails". The conflict occurred in database "Client", table "dbo.OrderDetails", column 'OrderDetailId`

When I set `DisableConstraintsOnApplyChanges` to `true` on **both sides** (server side and client side), then everything works as expected.

Do you have any difference in your environment ?

**Comment by VagueGit** [comment]
@Mimetis Thank you for taking the trouble to work through this. I haven't been able to test as there is one part I do not understand. You say

> You have an error in your script (`ALTER TABLE [dbo].[Jobs] ADD CONSTRAINT [FK_Jobs_OrderDetails] FOREIGN KEY([OrderDetailId]) REFERENCES [dbo].[OrderDetails] ([OrderDetailId])`)

but you appear to use the same script. What is my error? Apologies if I have missed it in your explanation.

The SQLite database _is_ created by DMS.

**Comment by Mimetis** [comment]
You wrote

``` sql
ALTER TABLE [dbo].[Jobs] ADD  CONSTRAINT [FK_Jobs_OrderDetails] FOREIGN KEY([OrderDetailId])
REFERENCES [dbo].[Jobs] ([JobId])
```
But it's incorrect. I guess it's more

``` sql
ALTER TABLE [dbo].[Jobs] ADD CONSTRAINT [FK_Jobs_OrderDetails] FOREIGN KEY([OrderDetailId]) REFERENCES [dbo].[OrderDetails] ([OrderDetailId])
```

**Comment by VagueGit** [comment]
Thank you @Mimetis for all your help on this. DMS 0.7.2 is working like a charm
