### ISSUE TITLE
Dotmim.Sync.Web.WebProxyClientProvider and Sync Result not found

### ISSUE THREAD

**Issue by lucas91na** [Mimetis/Dotmim.Sync#506]
Dotmim.Sync.Web.WebProxyClientProvider and Sync Result not found in sample project AuthSyncSampleWebServer. I have to test sync bidirectional with webserver on azure with azure auth from xamarin client. Thanks in advantage

**Comment by Mimetis** [comment]
Need more information

**Comment by lucas91na** [comment]
Here you can find a screenshot about errors. I already tried to include references about Dotmim Core, Webclient, Webserver etc. from local path or Nuget without resolve.

https://ibb.co/gJy2t1C

**Comment by Mimetis** [comment]
try to clean and restore

**Comment by lucas91na** [comment]
already done and done it again now, nothing.

**Comment by Mimetis** [comment]
I will check on Monday, but I'm not sure to be able to help you here ...
This is really strange, to be honest...

**Comment by lucas91na** [comment]
ok, but if you clone from your repo and open AuthSyncSampleWebServer.csproj inside Samples/AuthSyncSampleWebServer dir, after include missing references, build?

**Comment by Mimetis** [comment]
Try to Open the solution file https://github.com/Mimetis/Dotmim.Sync/blob/master/Samples/Dotmim.Sync.Samples.sln
The AUhtSync sample is out of date, I will remove it in the next commit
You can see HelloWebAuthSync if you want a quick sample with authentication
