### ISSUE TITLE
Prefix for tracking tables and stored procedures. 

### ISSUE THREAD

**Issue by marjanoh2** [Mimetis/Dotmim.Sync#51]
Is there an option to put a prefix on the tracking tables and stored procedures ?

**Comment by Mimetis** [comment]
It's an option I have considered before, but honestly, I didn't see the use cases where this option were important, so far.
Why do you need to personalize the prefix for tracking items ? Just for my knowledge :)

**Comment by marjanoh2** [comment]
For better visibility. I think the prefix is a good way to separate tracking item.

**Comment by Mimetis** [comment]
Ok, I see. So you need an option for both. Prefix and suffix ?

**Comment by gentledepp** [comment]
👍  for this feature.
Scenario:
We have a system that uses the old microsoft sync framework.
Now we want to slowly migrate to dotmim.sync.
For that to work smoothly, we need to run both frameworks side-by-side for some time.

This is not possible, as there are name clashes (e.g. on the tracking tables)!

**Comment by Mimetis** [comment]
Hey @marjanoh2 @gentledepp 
I have added a new featur for this particular scenario
You can try something like that to configure the prefix and suffix for each tables:

``` cs
        var tables = new string[] {"ProductCategory",
                "ProductDescription", "ProductModel",
                "Product", "ProductModelProductDescription",
                "Address", "Customer", "CustomerAddress",
                "SalesOrderHeader", "SalesOrderDetail" };

        var configuration = new SyncConfiguration(tables)
        {
            ScopeName = "AdventureWorks",
            ScopeInfoTableName = "tscopeinfo",
            SerializationFormat = SerializationFormat.Binary,
            DownloadBatchSizeInKB = 400,
            StoredProceduresPrefix = "s",
            StoredProceduresSuffix = "",
            TrackingTablesPrefix = "t",
            TrackingTablesSuffix = "",
        };
```

**Comment by gentledepp** [comment]
that is AWESOME! Thanks! Will try that out 👍

**Comment by Mimetis** [comment]
Hey @gentledepp  did you try it already ?

**Comment by gentledepp** [comment]
I did not find the time yet, but will most probably be able to verify this next week!

**Comment by marjanoh2** [comment]
I tested the new version and works well with default dbo tables. But it makes a problem with tables that have a different schema. For example:
Table: deimos.r_bills
Prefix for tables and procedures tr_
Gives this error:
Dotmim.Sync.SyncException: 'The specified schema name "tr_deimos" either does not exist or you do not have permission to use it.'

**Comment by Mimetis** [comment]
@marjanoh2 oh, thx for this issue !! Will look into it asap. 
Are you working on a sync between 2 SQL SERVER ? (or do you use one SQLITE / MYSQL) ?

**Comment by marjanoh2** [comment]
Yes I work on sync between 2 SQL SERVER

**Comment by marjanoh2** [comment]
One more thing. An example table deimos.r_areas and a prefix tr_ is created a table deimos.tr_areas and that's fine but the procedures are deimos.tr_deimos_r_areas_bulkdelete ... I think it should be deimos.tr_r_areas_bulkdelete ...?

**Comment by gentledepp** [comment]
Hi @Mimetis 
I now found the time to use Dotmim.Sync in parallel with the old Microsoft Sync Framework.
What I noticed is that, using the prefix and/or postfix for tables and stored procedures, I can get rid of the name clashes.
However, Dotmim.Sync also names the triggers identical to Microsoft Sync Framework and as it does not apply any prefixes and/or postfixes, it detects that some triggers already exist and continues without creating them.
This is obviously bad.
=> Would it be hard to add this prefix/postfix stuff to the triggers also?

**Comment by Mimetis** [comment]
Yes, I can get a look on it, it makes sense !

**Comment by Mimetis** [comment]
Done, in the last commit https://github.com/Mimetis/Dotmim.Sync/commit/6d0f79101b34e3f0c9239d020f04b947fa43535a

You have now two new parameters in `SyncConfiguration` called `TriggersSuffix` and `TriggersPrefix`

Let me know if everything is working as expected :)
