### ISSUE TITLE
Database sync MySQL 5.7.xx(Client) and SQL Server(Server). Net Core 3.1

### ISSUE THREAD

**Issue by HungNgoT** [Mimetis/Dotmim.Sync#511]
Hi,
I have a prolem when i try to synchronize MySql 5.7.xx (Client) and SQL server(Server).
I use mysql 8.0 to work. 
--
An unhandled exception occurred while processing the request.
MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INTO sync_row_count;
IF (sync_row_count = 0) THEN
INSERT INTO `demo`
(`' at line 28
MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask<ArraySegment<byte>> task) in ServerSession.cs, line 816

MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INTO sync_row_count;
IF (sync_row_count = 0) THEN
INSERT INTO `demo`
(`' at line 28
MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in MySqlDataReader.cs, line 133

SyncException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INTO sync_row_count;
IF (sync_row_count = 0) THEN
INSERT INTO `demo`
(`' at line 28
Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception)

My code Net core 3.1

                **var serverProvider = new SqlSyncProvider(_configuration["ConnectionStrings:SqlServer"]);
                var clientProvider = new MySqlSyncProvider(_configuration["ConnectionStrings:MySQL"]);

                var agent = new SyncAgent(clientProvider, serverProvider, new string[] { "demo" });

                var syncContext = await agent.SynchronizeAsync();

                var progressClient = new Progress<ProgressArgs>(s => Console.WriteLine($"[Client]: {s.Context.SyncStage}:\t{s.Message}"));
                var progressServer = new Progress<ProgressArgs>(s => Console.WriteLine($"[Server]: {s.Context.SyncStage}:\t{s.Message}"));
               
                Console.WriteLine("progressClient :" + progressClient);
                Console.WriteLine("progressServer :" + progressServer);
                Console.WriteLine(syncContext);**

Thanks!

**Comment by Mimetis** [comment]
MySql version 5.X is not supported.
You must upgrade to las version

**Comment by HungNgoT** [comment]
> MySql version 5.X is not supported.
> You must upgrade to las version

Thank @Mimetis .
