### ISSUE TITLE
Possible bug when synchronizing a column of a decimal type

### ISSUE THREAD

**Issue by marjanoh2** [Mimetis/Dotmim.Sync#52]
I noticed that when synchronizing a column of a decimal type, the values are rounded off and transmitted as such. For example, 1,789 is transferred to 2,000. The column is decimal (10.3) in both places - server and client.
![bug](https://user-images.githubusercontent.com/37705345/39540880-510dc208-4e44-11e8-83c1-10bbb74191d7.jpg)

**Comment by marjanoh2** [comment]
Yes. SQL Server to SQL Server sync.

**Comment by Mimetis** [comment]
Ok, will check that as soon as possible !

**Comment by Mimetis** [comment]
Damn ! I found the issue.
Thank you very much @marjanoh2 !
The fix will be soon available :)
