### ISSUE TITLE
Filter on WebSync

### ISSUE THREAD

**Issue by Hantse** [Mimetis/Dotmim.Sync#53]
Hello,

What do you think about a Filter for post request execution to execute the sync ?

```
    public class SyncAttribute : IResultFilter
    {
        public string[] OnMethods { get; set; } = new[] { "POST" };

        public void OnResultExecuted(ResultExecutedContext context)
        {
            if (OnMethods.Contains(context.HttpContext.Request.Method))
            {
                WebProxyServerProvider _webProxyService = (WebProxyServerProvider)context.HttpContext.RequestServices.GetService(typeof(WebProxyServerProvider));

                _webProxyService.HandleRequestAsync(context.HttpContext);
            }
        }

        public void OnResultExecuting(ResultExecutingContext context)
        {
        }
    }
```

**Comment by Mimetis** [comment]
Hey, this could be awesome, and will simplify the Controller implementation !
Do you want to make a PR ?

Be careful it should work with the `[Authorize]` attribute as well.

See the sample here: [https://github.com/Mimetis/Dotmim.Sync/blob/master/Samples/AuthSyncSampleWebServer/Controllers/AuthSyncController.cs](https://github.com/Mimetis/Dotmim.Sync/blob/master/Samples/AuthSyncSampleWebServer/Controllers/AuthSyncController.cs)

So, if we can have something like that, it would be perfect:

``` csharp
    [Authorize]
    [SyncFilter]
    [Route("api/[controller]")]
    public class AuthSyncController : Controller
    {
    }
```
BTW, not sure, but is it rather a `IActionFilter` or a `IResultFilter` ?

Let me know if you want to work on it !

Seb

**Comment by Hantse** [comment]
Hello,

Yes i can work on this week :)
