### ISSUE TITLE
ASP.NET Core Web Authentication -  client.DefaultRequestHeaders.Clear();  before call API ! ? !

### ISSUE THREAD

**Issue by luc-cap** [Mimetis/Dotmim.Sync#533]
Hi,
    reading the documentation,  in chapter:  "ASP.NET Core Web Authentication"  
to set  a client authentication header ( Bear Token)  you suggest  to do so:

`HttpClient` httpClient = new HttpClient();
`httpClient.DefaultRequestHeaders.Authorization` = new AuthenticationHeaderValue("Bearer", token);

There is a Problem !

The method:    `public async Task<U> ProcessRequestAsync<U>(...)`
of the class:   `HttpRequestHandler`  in namespace:  Dotmim.Sync.Web.Client 
reinits  DefaultRequestHeaders  of the CLIENT  before call API methd !       : )   

`client.DefaultRequestHeaders.Clear();`

So, serverside, Bearer token is null.

it is really necessary to clear  DefaultRequestHeaders  ?

Please, do the necessary tests...

Is it necessary to correct the class ? or just change the documentation?

**Comment by Mimetis** [comment]
Can you point me the source code where you see this `Clear` call ?

I don't see any `client.DefaultRequestHeaders.Clear()` in https://github.com/Mimetis/Dotmim.Sync/blob/master/Projects/Dotmim.Sync.Web.Client/HttpRequestHandler.cs

**Comment by luc-cap** [comment]
Hi,
     was here:

![image](https://user-images.githubusercontent.com/36303714/114576632-9afb4100-9c7b-11eb-8d42-0f7254c2abaf.png)

**Comment by luc-cap** [comment]
There is a way
to obtain  the snapshot of sources  when the NuGet package is released ?

probably  HttpRequestHandler class was just edited, when I  cloned repository..

sorry

**Comment by Mimetis** [comment]
Well, this issue was fixed a long time ago, that's why I don't understand why you have it today ?
Are you using the last version from the master branch ?

**Comment by luc-cap** [comment]
No,
   I am using  a local copy of reporitory  cloned 
when version was  0.5.7.

My progect needed  Microsoft.Data.SqlClient and i had to  replace same package and rebuild all.

Now that  from version 0.7.0 you use it,
everything works fine.

thanks
