### ISSUE TITLE
Can type check be ignored for excluded columns?

### ISSUE THREAD

**Issue by Oaquasis** [Mimetis/Dotmim.Sync#535]
Hi, 

First of all I have to say that I'm quite new to C# .Net programming so I might be missing obvious solutions, but...
Is there a way to skip type checking columns in the schema that are not included in the sync?

What I'm trying to do:
`DatabaseA ----downloadonly----> DatabaseB`

`DatabaseA` is a vendor database that I cannot modify, `DatabaseB` is a database that I use in my application.
DatabaseA has a table (Table1) with a lot of columns, but two of which are `text` columns. But let's say there are 4 columns: 
```sql
Id as int, 
Name as nvarchar,
Emailaddress as nvarchar, 
Info as text
```
I only need the first 3 columns.
So this is my code.

```c#
...
var serverProvider = new SqlSyncProvider(Configuration.GetConnectionString("DatabaseA"));
var clientProvider = new SqlSyncProvider(Configuration.GetConnectionString("DatabaseB"));

var setup = new SyncSetup(new string[] { "Table1" });
setup.Tables["Table1"].Columns.AddRange(new string[] { "Id", "Name", "Emailaddress" });
setup.Tables["Table1"].SyncDirection = SyncDirection.DownloadOnly;

var agent = new SyncAgent(clientProvider, serverProvider, setup);

progress = new SynchronousProgress<ProgressArgs>(args =>
    Log.Information($"{args.PogressPercentageString}:\t{args.Source}:\t{args.Message}"));

var result = new SyncResult();

do {
   result = await agent.SynchronizeAsync(progress);
} while (Console.ReadKey().Key != ConsoleKey.Escape);
...
```

My assumption was that all other columns would be ignored, but this fails:
```
[11:11:08 INF] 0,00%:   b33de51e-a55e-4f00-957e-288424ab22c9:   Session Begins.
Unhandled exception. Dotmim.Sync.SyncException: this type name text is not supported
 ---> System.Exception: this type name text is not supported
   at Dotmim.Sync.SqlServer.Manager.SqlDbMetadata.ValidateOwnerDbType(String typeName, Boolean isUnsigned, Boolean isUnicode, Int64 maxLength)
   at Dotmim.Sync.SqlServer.Builders.SqlBuilderTable.GetColumnsAsync(DbConnection connection, DbTransaction transaction)
   at Dotmim.Sync.BaseOrchestrator.InternalGetTableSchemaAsync(SyncContext context, SyncSetup setup, SetupTable setupTable, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.BaseOrchestrator.InternalGetSchemaAsync(SyncContext context, SyncSetup setup, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.BaseOrchestrator.<>c__DisplayClass83_0.<<GetSchemaAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Dotmim.Sync.BaseOrchestrator.RunInTransactionAsync[T](SyncStage stage, Func`4 actionTask, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

Is there a way, maybe with an interceptor, to fully exclude that "info" column?

**Comment by Mimetis** [comment]
Hi @Oaquasis

Indeed, you find a bug here ! (THANKS A TON !)
You should not have any blockers if you are not including this `text` in your setup.
You code is fine and should work.

I've fixed the issue, and you will get it in the next beta version for `v0.8.1` 
This beta version should be available at the end of the day, I guess.

That being said, something bothers me a bit when I read "_DatabaseA is a vendor database that I cannot modify_" 
Well, `DMS` needs to modify the server database, to add metadatas, triggers, stored procedures and tracking table.
If you are not allowed to modify your server schema, it won't work...

Regarding your issue, you can grab the last commit from the master branch or wait a bit until all the tests are done and the beta version published.

Once again, thanks a lot for having spotted this issue !

**Comment by Oaquasis** [comment]
Thanks for the quick fix!

> That being said, something bothers me a bit when I read "_DatabaseA is a vendor database that I cannot modify_"
> Well, `DMS` needs to modify the server database, to add metadatas, triggers, stored procedures and tracking table.
> If you are not allowed to modify your server schema, it won't work...

Ah then I might have misunderstood DMS a bit, so I will look for another solution there. 
I think I will eventually want to switch to a ASP.NET Core Web Proxy setup for the DatabaseB --> ClientDB so DMS will be useful there. 

Anyway, thanks again.

**Comment by Mimetis** [comment]
You're welcome !
Thanks for finding this little bug ;)
