### ISSUE TITLE
Cleanup tracking tables, triggers, stored procedures

### ISSUE THREAD

**Issue by abunoman2003** [Mimetis/Dotmim.Sync#536]
I am trying to set server side  database to original state by dropping tracking tables, triggers and stored procedures

What is best way for that without doing it manually

Thanks

**Comment by Mimetis** [comment]
You can use `DeprovisionAsync` method: https://dotmimsync.readthedocs.io/Provision.html#deprovision

``` cs
// Create server provider
var serverProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(serverDbName));

// Create standard Setup and Options
var setup = new SyncSetup(new string[] { "Address", "Customer", "CustomerAddress" });
var options = new SyncOptions();

// Create a server orchestrator used to Deprovision everything on the server side
var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);

// Deprovision everything
await remoteOrchestrator.DeprovisionAsync();
```

**Comment by abunoman2003** [comment]
Thank you so much @Mimetis . 
Actually I was trying same with an older version. Updated to newest version, working like charm
