### ISSUE TITLE
How to get the progress in a WinForms app?

### ISSUE THREAD

**Issue by PixelHunter88** [Mimetis/Dotmim.Sync#537]
Hi Sébastien,

What a great piece of software, I have been looking for since month. Thank you a lot!
It solved all my tasks in days, with previous solutions I struggled for months with problems.

Some newbie questions are left and it would be very kind if you confirm my learnings:

* The best way to insert FK referenced tables at once is with `SyncOptions DisableConstaints = true` right?
* To filter rows in a range of value the approach is  `.AddCustomWhere` ?

* **How to get the progress in a WinForms app**?
Because I work with GUI and EF Core async/await is no option for me in my project, but with:

```
SyncResult syncResult = Task<SyncResult>.Run(() => 
    agent.SynchronizeAsync(syncType) // ,progress
    ).Result; 
```

everything works perfect, clean and stable, but when I try to get the progress:

```
// Using the IProgress<T> pattern to handle progression during the synchronization
var progress = new SynchronousProgress<ProgressArgs>(s => 
	Console.WriteLine($"{s.PogressPercentageString}:\t{s.Source}:\t{s.Message}")
);
```
the syncResult process runs forever and never calls back, neither an console output is visible. Which is not a huge problem because it's so amazing fast.

Would you recommend some improvements in my case?

Besides: There is a small typo in `ProgressArgs.PogressPercentageString` should be `ProgressArgs.ProgressPercentageString`.

Best regards
Florian

**Comment by Mimetis** [comment]
Hi Florian,
Thanks for the feedback, really appreciate !

> The best way to insert FK referenced tables at once is with `SyncOptions.DisableConstaints = true;`

Indeed. The only concern here is the performance issue. When using this options, your database engine will lock the table during the transaction. 
That means, if you have a lot of synchronizations happening at the same time, some of them will to wait until a lock is released (from a previous sync)
So far, be careful with this option.

> To filter rows in a range of value the approach is `.AddCustomWhere` ? 

Yes, but if you are using this method, you need to handle the tombstones rows.
There is a lack of documentation on this method, see https://github.com/Mimetis/Dotmim.Sync/issues/524#issuecomment-821533662  for a detailed explanation

> How to get the progress in a WinForms app?

Wow ! Never seen we can't use async await in WinForms !
Can you share a small repro sample, to have a clear view on this ?

> Besides: There is a small typo in ProgressArgs.PogressPercentageString should be ProgressArgs.ProgressPercentageString.

I will probably remove this property in the future, but thanks for the typo !

**Comment by PixelHunter88** [comment]
> Wow ! Never seen we can't use async await in WinForms !

You're right, it's just EF Core which is not really suitable for async operations in my experience.

I changed my code to call with await/async and now it works perfect .
