### ISSUE TITLE
Xamarin Android app doesn't support Microsoft.Data.SqlClient 

### ISSUE THREAD

**Issue by Menci77** [Mimetis/Dotmim.Sync#544]
I am creating a Xamarin Android app in Visual Studio.
When I try to sync it fails with this error: Dotmim.Sync.SyncException: 'Strings.PlatformNotSupported_DataSqlClient'.
I checked and the Dotmim.Sync.Sqlserver pakcage contains the Microsoft.Data.SqlClient dependency.
Does this mean that I cannot synchronize with sql server database from Xamarin Android app?
![image](https://user-images.githubusercontent.com/61515787/116402936-4506cb80-a82d-11eb-8031-a556bc8ec590.png)

**Comment by gentledepp** [comment]
Absolutely. For the very same reason why you cannot run Microsoft SSL Server on your Android phone... ;-)
There is only one database that you can use in apps: **SQLite**
SQL Server, PostgreSQL, Mongodb, .... etc. will **never** be supported by Android and/or iOS.

Please have a look at the documentation - it should explain this quite well
https://dotmimsync.readthedocs.io/

**Comment by Menci77** [comment]
Thanks.
