### ISSUE TITLE
Support ASP.NET Web API 2

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#55]
Migrate the project Dotmim.Sync.Web to ASP.NET to also support this legacy platform

I will do this shortly and create a PR!

**Comment by Mimetis** [comment]
In my opinion, it is already working
It's .net 2.0 standard, so I think it should work, by design, with .Net Fx 4.6 +

Did you encounter a problem ?

**Comment by gentledepp** [comment]
Yes we did:
Dotmim.Sync.**Web** depends on ASP.Net CORE libraries which are not compatible with the (old) ASP.Net

**Comment by Mimetis** [comment]
oh, thx. 
So feel free to PR :)

**Comment by gentledepp** [comment]
Hi!
I made some progress in adding support for Web Api 2.
See this PR: #69 

Currently, I am trying to get the UWPSyncSample to work with WebApi2.

**The only thing that is missing, is the CONTOSO database.**
Where can I get it from? Could you please provide a link?

**Comment by gentledepp** [comment]
done 👍
