### ISSUE TITLE
Why not  System.Data.SqlClient, for windows Users  ? Works better...

### ISSUE THREAD

**Issue by luc-cap** [Mimetis/Dotmim.Sync#550]
Hi,
      I use Dotmim since a couple of year.

Starting from Scratch, it is possible to make a .NET Core 5.0  console App which is able to 
estabish a connection  with a SQL server 2017 hosted  by docker desktop.

In particular , calling  
            SyncThroughWebApiAsync()
in: 
            Dotmim.Sync-master\Samples\Dotmim.Sync.SampleConsole\Program.cs 
works fine !

Le same  program  built  as   .NET Framework 4.8  Console App  does  not work.

The only way I found to make all working is  replacing the package

              Microsoft.Data.SqlClient" Version="2.1.1" 

with
             System.Data.SqlClient    Version="4.8.2"

For me this is a problem, because i can not  use nuGet compiled packages.

I'm sure I'm not the only one to have this problem....

It could not be used    System.Data.SqlClient    Instead  of     Microsoft.Data.SqlClient for windows users?
It works  Better ! 

thanks for everything, 

especially for sharing with us DotmimSync  source

Luca

**Comment by Mimetis** [comment]
Have a look here : https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/

> However, Microsoft.Data.SqlClient will be the only place we will be implementing new features going forward. 

Have a look here too : https://github.com/dotnet/aspnetcore/issues/10013

Looking at https://github.com/dotnet/sqlclient/ it seems that this package is compatible with .NET 4.6

> The Microsoft.Data.SqlClient package supports the below environments:
> 
> .NET Framework 4.6.1+
> .NET Core 2.1+
> .NET Standard 2.0+.

That being said, `DMS` will work on any runtime supporting `.Net Standard 2.0`

Unfortunately, the web packages of `DMS` is heavily using some `ASP.NET Core `apis. So not sure it will work with the `.Net 4.8 ` framework.

I will make some tests.

**Comment by Mimetis** [comment]
This code is working on `.Net 4.7.2`, using `DMS` version `0.8.0`
Be careful, it's not using Web Apis, but instead, direct link to each database.
Just to be sure that `Microsoft.Data.SqlClient` is working fine with an old framework version, like `4.7.2`.

``` cs
private static string serverConnectionString =
    "Data Source=(localdb)\\mssqllocaldb; Initial Catalog=AdventureWorks; Integrated Security=true;MultipleActiveResultSets=True;";

private static string clientConnectionString =
    "Data Source=(localdb)\\mssqllocaldb; Initial Catalog=Client; Integrated Security=true;MultipleActiveResultSets=True;";
private static async Task SynchronizeAsync()
{
    var serverProvider = new SqlSyncProvider(serverConnectionString);
    var clientProvider = new SqlSyncProvider(clientConnectionString);
    var setup = new SyncSetup(new string[] { "Customer" });

    // Using the Progress pattern to handle progession during the synchronization
    var progress = new SynchronousProgress<ProgressArgs>(s =>
    {
        Console.ForegroundColor = ConsoleColor.Green;
        Console.WriteLine($"{s.PogressPercentageString}:\t{s.Source}:\t{s.Message}");
        Console.ResetColor();
    });

    // Creating an agent that will handle all the process
    var agent = new SyncAgent(clientProvider, serverProvider, setup);
    do
    {
        Console.WriteLine("Sync start");
        try
        {
            var s = await agent.SynchronizeAsync(progress);
            Console.WriteLine(s);
        }
        catch (SyncException e)
        {
            Console.WriteLine(e.ToString());
        }
        catch (Exception e)
        {
            Console.WriteLine("UNKNOW EXCEPTION : " + e.Message);
        }


        Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");
    } while (Console.ReadKey().Key != ConsoleKey.Escape);

}
```

**Comment by luc-cap** [comment]
I understood...

There is no hurry, but it is better to pass everything on .NET Core 5.0 +.

Microsoft.Data.SqlClient will be the only place where will be implemented new features .

System.Data.SqlClient   will remain as-is and upon it will be only fixed important bugs and security issues.

Thanks

**Comment by Mimetis** [comment]
Actually,; it's working only if you are using a direct link to your server, like my previous example.

But if you want to protect your Server behind a Web API, it won't work if you are trying to create a Web API with .Net FX 4.8
Today, `Dotmim.Sync.Web.Server` is only working if you are creating a Web API with Asp.Net Core.

It could work with .Net 4.7 (and classic ASP.Net Web Api) but it would require a little bit of work on `Dotmim.Sync.Web.Server`, and I'm not sure it's worth to implement it, since .Net FX is near its end of life :)

**Comment by luc-cap** [comment]
Thanks Sebastian,
          but  WEB Side  I developed a NopCommerce 4.40  Plugin written in .NET core 5.0.

Only Client side,  I developed a client in .NET framework 4.8

And all works in production, but only with  System.Data.SqlClient Version="4.8.2" 

https://casaeregalo.com/

Bye

luca
