### ISSUE TITLE
Wrong dependencies when using netcore3.1 app

### ISSUE THREAD

**Issue by flacidsnake** [Mimetis/Dotmim.Sync#552]
Hi,

I'm trying to run the WebOrchestrator as a netcore3.1 Azure Function v3 as discussed in #243 , but I'm getting an error when attempting to add a sync server:

```
builder.Services.AddSyncServer<SqlSyncChangeTrackingProvider>(syncBuilder.ConnectionString, syncSetup);

System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.'
```

I'm using Dotmim.Sync v0.8. The issue seems to be caused by some dependencies pointing to v5 or greater (e.g. **Microsoft.Extensions.Logging**, Microsoft.Extensions.DependencyInjection...). In my case, for netcore3.1 function apps, those dependencies should point to v3.1.14, otherwise they will crash.

Is it possible to fix the Dotmim.Sync dependencies to point them to a version compatible with netcore3.1? Maybe >=3.1.14 instead of >=5.0.0?

Thanks in advance

**Comment by Mimetis** [comment]
That's strange.
The Web project is configured to be compatible with `.Net Core 3.1`
![image](https://user-images.githubusercontent.com/4592555/117666930-a707ef00-b1a4-11eb-9b79-fbb5940185c0.png)

And when we see the details of the packages; we have the correct version here:

![image](https://user-images.githubusercontent.com/4592555/117667049-c4d55400-b1a4-11eb-9ad8-fc1c0e54e503.png)

Can you share a simple repro ?

**Comment by Mimetis** [comment]
I workaround the `Logging ` version, but anyway, I'm running in the same issue as https://github.com/Mimetis/Dotmim.Sync/issues/243#issuecomment-646994084 on `Unable to resolve service for type 'Microsoft.Azure.WebJobs.Script.IFileLoggingStatusManager'`

Will try to resolve the issue, but not sure if it's feasible ...

**Comment by Mimetis** [comment]
Indeed, but in that case, the `Configure` method is never called, it won't help 🗡️ 

![image](https://user-images.githubusercontent.com/4592555/117827505-55796600-b271-11eb-82ac-893cd26e46f8.png)

**Comment by Mimetis** [comment]
Closing the issue.
It seems DMS is not compatible with azure function, finally
