### ISSUE TITLE
Sync operation stuck and and totally freezes in case of deleting many record from the client database 

### ISSUE THREAD

**Issue by Abdelrahmandev1984** [Mimetis/Dotmim.Sync#555]
I created a server provider of type "**_SqlSyncChangeTrackingProvider_**" and another one for the client of the same type, I am trying to sync two SQL Server databases, I configure the SyncDirection of the EnteranceLog table to be "_**UploadOnly**_" so data should be only transferred from client to the server based on the client database changes only, I executed the sync process and it succeed

`s1 = await agent1.SynchronizeAsync(SyncType.Normal,_cancellationTokenSource.Token, progress)`

Then I deleted many records from the table in the client database (about 60000 records) and tried the sync process again abut the sync operation stuck and totally freeze at this point (**_BaseOrchestrator.ApplyChanges.cs_**)
```
                // -----------------------------------------------------
                // 2) Applying Deletes. Do not apply deletes if we are in a new database
                // -----------------------------------------------------

if (!message.IsNew && hasChanges)
                    foreach (var table in schemaTables.Reverse())
                        await this.InternalApplyTableChangesAsync(context, table, message, connection,
                            transaction, DataRowState.Deleted, changesApplied, cancellationToken, progress).ConfigureAwait(false);
```

especially at applying table changes has many records deleted.

the progress logged in the Console is stopped here with no additional progress 

0.00%:  a9328b5c-338c-4687-8c8c-5455eef2ea17:   Session Begins.
21.67%: Marina2020_Client2:     [GateEntranceLog] [Total] Upserts:0. Deletes:65514. Total:65514.
21.67%: Marina2020_Client2:     [Total] Upserts:0. Deletes:65514. Total:65514

**Comment by Abdelrahmandev1984** [comment]
It completed synchronizing at the end after about 3 hours

**Comment by Abdelrahmandev1984** [comment]
It completed at the end after more than 3 hours to sync about 60000 records, it took too much to complete, I noticed that there is a line of code takes more than 200 milliseconds to execute, it executed more than 30000 times and that caused this delay
```

// execute the batch, through the provider
await syncAdapter.ExecuteBatchCommandAsync(command, message.SenderScopeId, arrayStepChanges, changesTable, failedPrimaryKeysTable, message.LastTimestamp, connection, transaction).ConfigureAwait(false);
// Get local and remote row and create the conflict object
                    foreach (var failedRow in failedPrimaryKeysTable.Rows)
                    {
                        // Get the row that caused the problem, from the opposite side (usually client)
                        var remoteConflictRow = changesTable.Rows.GetRowByPrimaryKeys(failedRow);
                        conflictRows.Add(remoteConflictRow);
                    }
```
The "**_GetRowByPrimaryKeys_**" is taking too much time ( more than 200 milliseconds)

**Comment by Mimetis** [comment]
It means that u have conflicts on these rows
Deletion of 60k rows will take about 10 sec (1 query)
but if there is conflicts on each line, EACH LINE will be retrieved from database (60k queries) and will handle the conflict

Try to make a test with no conflicts, it should work at a faster level

**Comment by Abdelrahmandev1984** [comment]
Thanks a lot for your response

I tried to delete many records from the client DB and the sync really went very fast, but What exactly causes the conflicts? would you explain, please

**Comment by Mimetis** [comment]
it means that you deleted a lot of records on one side (client or server) and you have updated the same records on the other side (server or client)
Then when a sync is occurring, `DMS` see that a record has been updated on one side and deleted on the other. 
Who win ? It's a conflict (and the winner is the server by default)

For each row in a conflict the solution is provided by resolving the conflict, and to be able to resolve the conflict, we need the row from the database with last version.

So, 60k rows deletes in conflicts means 60K queries to resolve them.
60k rows without conflict means ... 1 delete query
