### ISSUE TITLE
'The Column name TimeStamp is not allowed. Please consider to change the column name.'

### ISSUE THREAD

**Issue by GKG4** [Mimetis/Dotmim.Sync#556]
I have this database from almost 10 years now with all related softwares and all.
Changing the column name in all the tables is not feasible.

Is there any workaround for this?

**Comment by Mimetis** [comment]
Hello @GKG4 

In a future release, I will see if we can remove this check on this particular column, but I need to make more tests, to be sure it won't break anything

Meanwhile, you can clone the repository and compile your own version without this check

Take a look here : https://github.com/Mimetis/Dotmim.Sync/blob/f3fadabae4c591ecedfacdd44a5625414077ecc3/Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.Schema.cs#L190

**Comment by Mimetis** [comment]
This issue will be resolved in the next release

**Comment by jader1313** [comment]
Has this issue been resolved? If not why was it closed? Should it close only when resolved not? What is the next release you are referring to? We also have a field called "timestamp" in every table in our system. We commented the line
columnNameLower == "timestamp"
and we had no problems with Dotmim.Sync, but that way we need to keep our own version.
