### ISSUE TITLE
Metadata cleaning

### ISSUE THREAD

**Issue by marjanoh2** [Mimetis/Dotmim.Sync#559]
I have one main database and two local databases. When I sync the second local database for the first time, tracking table looks like this:
![sync1](https://user-images.githubusercontent.com/37705345/120635330-a5aca800-c46c-11eb-8b61-107cbb3c8b8b.jpg)

Rows with id 14,16,18 are changed after initial sync but metadata is not cleared. 

Tracking table on  first local database:
![sync2](https://user-images.githubusercontent.com/37705345/120635676-0b009900-c46d-11eb-8ec1-4e2541acfc3b.jpg)

Tracking table on main database:
![sync3](https://user-images.githubusercontent.com/37705345/120635864-397e7400-c46d-11eb-91cc-b7f2442986af.jpg)

Code I used for sync:
![sync4](https://user-images.githubusercontent.com/37705345/120636007-6894e580-c46d-11eb-8d29-c23d656a8d93.jpg)

Shouldn't metadata clean after each successful synchronization on client side?

**Comment by Mimetis** [comment]
IT should cleaned up the metadata
For some reasons, the directories could be locked
if it's the case, you can delete the tmp folders by yourself ?

**Comment by Mimetis** [comment]
Closing the issue.
If you think the issue should be reopened, do not hesitate to comment
