### ISSUE TITLE
Dotmim.Sync.Web.Client.HttpSyncWebException: Invalid object name '[TABLE]_tracking'. Statement(s) could not be prepared.

### ISSUE THREAD

**Issue by Tuytje** [Mimetis/Dotmim.Sync#561]
I'm seeing the following error, or variations on them from users in my logs:
Dotmim.Sync.Web.Client.HttpSyncWebException: Invalid object name '[TABLE]_tracking'. Statement(s) could not be prepared.

Where [TABLE] is one of the tables that need to be synced. Not always the same table. As I understand it, this is a single (or multiple) missing stored procedures. In what case would they not have been made? If there a 'check if they are there' call that can be done? Any pointers?

**Comment by Mimetis** [comment]
I need more info to help you ?
Did you made any changes in your code after a successful sync ?
Did you add or remove any tables ?

**Comment by Tuytje** [comment]
@Mimetis  thanks for the swift reply, as always :)

That is the thing. There are no code changes, no tables being added or removed. Some users just run into this, and I have no idea why.
A friend of mine was able to trigger the issue by 'clearing storage' inside android. This removes the database all data associated with the app, like the database. On first run after this, the database gets recreated and one would expect the stored procedures to be created as well, correct? I believe that Dotmim keeps it version (and if stored procedures are created) in the database itself, not some setting file, correct?

**Comment by Mimetis** [comment]
IF you lost the client database, I guess you just need to be sure you have restarted the client application`
DMS is checking metadatas / stored proc / tracking tables during the init phase (when you launch your first sync)

**Comment by Tuytje** [comment]
It is not that the database is lost. In android you can tell the OS 'remove all data for this app'. Which kind of moves it to a state of newly installed. In that case you have a chance of the sync failing because of said issue. Do you store any data for DMS outside the database which would make DMS think it is initialized already? The problem is not widespread, so it is not a 'the building is on fire' type of thing, but it is something I will keep an eye on

**Comment by Mimetis** [comment]
nop, the only data stored is the `sqlite `client database generated on the fly.
`DMS `has an internal `boolean` value indicating if the database has been already provisioned.
That's maybe the problem here. If `DMS `thinks the metadatas are generated (tracking tables, triggers, tables....) but the database is in fact empty, then it will probably fail.
That's why restarting the app (or the phone itself ?) just to ensure it's the problem here, can help

Did you find a solution to recover from that failing state ?

**Comment by Tuytje** [comment]
With internal value, you still mean that it is stored in the database, or in the settings? I have noticed that not all data is removed when clearing storage for an app since authentication data is still present after a clear data.

Uninstall / install is what I recommend now if it fails in this case, since I haven't been able to fully reproduce the issue yet (sometimes it works fine when doing this). 
Is there a way to manually force the library to check if the sp's exists, and if not to create them?

**Comment by Mimetis** [comment]
> Is there a way to manually force the library to check if the sp's exists, and if not to create them?

Yep

You can use `ProvisionAsync()`:
``` cs
public virtual Task<SyncSet> ProvisionAsync(SyncSet schema, SyncProvision provision, bool overwrite = false)
```

With overwrite set to false; you will:
- Check if table / tracking table exists
- If not, create table / tracking table
- Check if trigger / stored proc exists
- if not, create trigger / stored proc

With `overwrite` set to `true`, it will basically :
- Check if table / tracking table exists
- If not, create table / tracking table (there is no overwrite here, otherwise we would loose the data)
- Check if trigger / stored proc exists
- If exists, it will delete trigger / stored proc
- Will create trigger / stored proc

**Comment by Tuytje** [comment]
Thank you

**Comment by Abdelrahmandev1984** [comment]
I have the same issue with SQL Server, is there a way to re-create all the sync environment

**Comment by Mimetis** [comment]
# Provision

``` cs
// -----------------------------------------------------------------
// Server side
// -----------------------------------------------------------------

var serverProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(serverDbName));

// Create standard Setup and Options
var setup = new SyncSetup(new string[] { "Address", "Customer", "CustomerAddress" });
var options = new SyncOptions();

// This method is useful if you want to provision by yourself the server database
// You will need to :
// - Create a remote orchestrator with the correct setup to create
// - Provision everything

// Create a server orchestrator used to Deprovision and Provision only table Address
var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);

// Provision everything needed (sp, triggers, tracking tables)
// Internally provision will fectch the schema a will return it to the caller.
var newSchema = await remoteOrchestrator.ProvisionAsync();
```


``` cs
// -----------------------------------------------------------------
// Client side
// -----------------------------------------------------------------

// Create 2 Sql Sync providers
var serverProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(serverDbName));
var clientProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(clientDbName));

// Create standard Setup and Options
var setup = new SyncSetup(new string[] { "Address", "Customer", "CustomerAddress" });
var options = new SyncOptions();


// This method is useful if you want to provision by yourself the client database
// You will need to :
// - Create a local orchestrator with the correct setup to provision
// - Get the schema from the server side using a RemoteOrchestrator or a WebClientOrchestrator
// - Provision everything locally

// Create a local orchestrator used to provision everything locally
var localOrchestrator = new LocalOrchestrator(clientProvider, options, setup);

// Because we need the schema from remote side, create a remote orchestrator
var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);

// Getting the schema from server side
var serverSchema = await remoteOrchestrator.GetSchemaAsync();

// At this point, if you need the schema and you are not able to create a RemoteOrchestrator,
// You can create a WebClientOrchestrator and get the schema as well
// var proxyClientProvider = new WebClientOrchestrator("https://localhost:44369/api/Sync");
// var serverSchema = proxyClientProvider.GetSchemaAsync();

// Provision everything needed (sp, triggers, tracking tables, AND TABLES)
await localOrchestrator.ProvisionAsync(serverSchema);
``` 

# Deprovision

``` cs
// -----------------------------------------------------------------
// Server side
// -----------------------------------------------------------------

// Create server provider
var serverProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(serverDbName));

// Create standard Setup and Options
var setup = new SyncSetup(new string[] { "Address", "Customer", "CustomerAddress" });
var options = new SyncOptions();

// Create a server orchestrator used to Deprovision everything on the server side
var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);

// Deprovision everything
await remoteOrchestrator.DeprovisionAsync();
```

``` cs
// -----------------------------------------------------------------
// Client side
// -----------------------------------------------------------------
// Create client provider
var clientProvider = new SqlSyncProvider(DbHelper.GetDatabaseConnectionString(clientDbName));

// Create standard Setup and Options
var setup = new SyncSetup(new string[] { "Address", "Customer", "CustomerAddress" });
var options = new SyncOptions();

// Create a local orchestrator used to Deprovision everything
var localOrchestrator = new LocalOrchestrator(clientProvider, options, setup);

// Deprovision everything
await localOrchestrator.DeprovisionAsync();
```

**Comment by Tuytje** [comment]
The issue is still not resolved for me, but I think I have a bit more information. It seems that it is the server who is sending that error downstream, which is ery strange since the server is an sql server with change tracking enabled. 
Why is it looking for those _tracking tables, as I understand it it should be needing those. Any pointers?
