### ISSUE TITLE
synchronization works for some tables but not others

### ISSUE THREAD

**Issue by HunarAA** [Mimetis/Dotmim.Sync#562]
I have implemented the library to make a sync between two SQL server database (one is local, the other one is hosted on a server), at first it worked just fine, but know it syncs the content of some table while it does not work for the rest of the tables.

**Comment by Mimetis** [comment]
I need more infos to help you.
Do you have filters ?
Did you change something in the Setup ?
Did you make any drop in the Sync generated things ?
Did you changed something on the client / server ?

**Comment by HunarAA** [comment]
sorry for late replay
at that time after some tricks the sync worked properly, till then I haven't do the sync, yesterday I wanted to do the sync, again one of my tables on the server has more than 4000 rows, but the sync copies only nearly 2000 rows to the client which means id does not copies most of the new rows, but for the tables that do not has changes there isn't any problem.

**Comment by HunarAA** [comment]
Another thing that I have noticed, for example table A has the same number of records and getting to the same ID (table ID) in both server and client databases, but when I insert a row to the server database while online, another person inserting a row to the client database to the same table which gets the same table ID as the another inserted record, when I do sync because both records have the same ID, it deletes the client record and syncs the server record to the client. If I am not wrong this can be a bug? There should be a way to keep both rows.

**Comment by Mimetis** [comment]
Not a bug, that's normal actually
It means you are trying to Insert-Insert a row on both side with same ID
So far, DMS considers it's a conflict and make a resolution on it
By default, the Server wins the conflict, and then the client row is overwritten by the row from server


For your problem about the 2K rows not synced, can you create a small sample repro ?

**Comment by HunarAA** [comment]
What if I want to keep both rows? because in my case more than one user works on the database, for example one of the users has internet connection and inserts directly to the server, while another one does not have an internet connection at that moment and inserts to the client database and both of them gets the same ID one in the server database and the other one in the client database, but while the sync is done, as you mentioned the client row will be replaced by the server one. Did you have any idea?

And, what do you mean by small sample repro ?
I think the other problem is also caused because of ID confliction? isn't it?

**Comment by Mimetis** [comment]
I don't know if your problem is coming from ID conflict, but it can be, yes

If you want to keep both rows, be sure to have different primary keys values

If you are using identity columns, you will have to implement your own solution.
You can have a look at this discussion : https://github.com/Mimetis/Dotmim.Sync/discussions/442

But honestly, your best bet here is to use GUID instead of IDENTITY columns

**Comment by HunarAA** [comment]
Thank you for your informative answer, I will try your suggested solutions.
