### ISSUE TITLE
The method ToRfc1123String fails with Microsoft.Extensions.Primitives v5.0.0 as the method InplaceStringBuilder has been removed

### ISSUE THREAD

**Issue by akema-trebla** [Mimetis/Dotmim.Sync#564]
Error MT2101: Can't resolve the reference 'Microsoft.Extensions.Primitives.InplaceStringBuilder', referenced from the method 'System.String Microsoft.Net.Http.Headers.DateTimeFormatter::ToRfc1123String(System.DateTimeOffset,System.Boolean)' in 'Microsoft.Extensions.Primitives, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. (MT2101)

Any workaround for this?

Thanks in advance.

**Comment by Mimetis** [comment]
no ida

**Comment by akema-trebla** [comment]
Is it possible to bump up the dependency on Microsoft.Extensions.Logging, Microsoft.AspNetCore.Http.Features and Microsoft.Extensions.Primitives to version 5.0?

It appears other packages in my solution are using version 5.0 which has the removed method as against yours on version 2.2

So turning the linker on in Xamarin produces this error.

**Comment by Mimetis** [comment]
If you are using an assembly marked as 5.0, it will use the last version of logging
If you are using an assembly marked .net standard 1.0, it will use the compatible version of logging

You have xamarin sample in the Samples directory.
Maybe it can help ?

**Comment by akema-trebla** [comment]
I've been using it in my Xamarin apps just fine but since I updated Shiny nuget package to version 2, I can't build in release with linker on and the error message. 

Can you tryout Shiny Notifications v2 in your sample to see what I'm referring to?

**Comment by Mimetis** [comment]
If you are not sure about what version is used from any nuget package, for some reason, my advice would be to :
- Create a .Net Standard 2.0 project, to force any references to downgrade to .net standard
- Add DMS in this .net Standard 2.0 project. That way you are sure that there is no assembly incompatible with others fx

Let me know if it's resolving your issue here

**Comment by akema-trebla** [comment]
[TestApp.zip](https://github.com/Mimetis/Dotmim.Sync/files/7098033/TestApp.zip)
 
Kindly take a look at this test project for me. It's basically a port of your sample app with some Shiny nuget packages.

It produces the error in release mode with linker set to Link SDK assemblies only.

The Shared project is .Net Standard 2.0 and has DMS

There is no DMS in platform specific projects.

This has been driving me insane for months now as I can't update my app on the App Store. 

Kindly advise.

**Comment by akema-trebla** [comment]
I think I've solved it.

I installed Microsoft.Extensions.Primitives v3.1.10 in each of the platform specific projects and the error went away.
