### ISSUE TITLE
How to debug server validation errors

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#565]
Using SQLite locally and SQL Server via http. SQLite data types do not map directly onto SQL Server so it is possible for data to be invalid when DMS tries to sync from SQLite to the server.

In a commercial database we might sync hundreds of thousands of rows. Does DMS have a mechanism to feed back details of a server validation error? How do we know which data is failing?

Where data has failed to sync in the past, DMS retries syncing that same data next time it is called to sync. This accumulates an increasing backlog of 'invalid' data that DMS continues to retry syncing.

I've look at `ProgressArgs` and `TableChangesApplied` but can't see what to hook into to log data that fails to sync.

EDIT here is an example of what I'm seeing in the output on startup `d6944412-de17-40e1-9b61-93e32db2796d -ChangesApplying	 Sending Batch Changes. Batches: (17/161). Rows: (189444/1177257). Waiting Server Response...`

I assume I have missed something somewhere as this must be an issue everyone faces.

**Comment by Mimetis** [comment]
Until the sync is successful, DMS will retries to sync.

Do you know if the error is happening locally or on the server side ?
Once DMS has retried it will send back the error to the client

I don't know where your issue is coming from. So far I guess you should try to hook all the `On..` interceptors:

``` cs
OnDatabaseChangesApplying()
OnDatabaseChangesApplied()
OnDatabaseChangesSelecting()
OnDatabaseChangesSelected()
```
On the server side, you need to encapsulate your code in a  `try cactch` and cath all errors

If you can create a small repro sample, it will be easier to help you

**Comment by VagueGit** [comment]
Thank you for the prompt response @Mimetis . A million rows have been entered into a new local SQLite database and are being uploaded to a new SQL Server database via http

The server side is the DMS SyncController which is wrapped as per DMS docs in a try
```
catch (Exception ex)
{
    await WebServerManager.WriteExceptionAsync(this.HttpContext.Response, ex);
}

```
One example of a failure: SQL Server uses `decimal(9,2)`. DMS creates the local SQLite database with these columns as type `Numeric`. The million rows entered locally might include a value that is a valid `numeric`, but too large to be synced to `decimal(9,2)`. DMS throws the exception message `The stream does not support writing`. 

Another example: SQLite includes trailing blanks in strings. SQL Server ignores trailing blanks. SQLite will allow primary keys "MyString" and "MyString ", but SQL Server with throw a Primary Key Violation when DMS syncs. DMS throws the exception message `The stream does not support writing`. 

We try to trap such errors before updating the local database, but if they slip through, when DMS syncs to the server, it throws the exception message `The stream does not support writing`. This seems to be the response whenever an upsert is denied by the SQL Server. We'd like to be able to see which row fails so that we can respond.

Will interceptors on the client give me any clue to which row has failed to upsert via http on the server?

How do I get more detailed info back from the sync controller? I've looked at [Intercepting web events](https://dotmimsync.readthedocs.io/Interceptors.html#intercepting-web-events) but can't see where that shows which changes have failed.

I noticed your [Spy sample](https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/Spy) uses mssqllocaldb. Do you know if mssqllocaldb can be distributed with a UWP app? There is contradictory info out there. Having a local database that is consistent with the server might make this issue go away.

**Comment by Mimetis** [comment]
I guess you can use sql server express or sql local db (if installed) from a UWP application.
