### ISSUE TITLE
Enhancement - using multiple transactions on GetChangesBatchAsync

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#575]
Hi @Mimetis!

I recently took another look at the old DMS version as we are still stuck with it. (I know... I know...)

The reason is that we have some deadlock exceptions recently from users downloading changes while others are uploading them.
Note: The main reason for our deadlocks is not vanilla DMS, but our complex select queries.

However, I saw, that DMS is creating one transaction to call all `sp_getchanges` stored procedures.
Now, based on the fact, that - by default - it uses an isolation level of read committed, it does not make any difference to create one transaction per `sp_getchanges` call.
However, it does reduce the time that we have locks on our tables signifficantly. (If you have 5 tables, it now is one fifth of the time)

So I propose to change that.

However, as you can now change the isolation level with the newest DMS version (to e.g. "snapshot"), you may want to really have one transaction for all tables after all. With "snapshot" isolation, you won't run into issues with locks anyway.

So the new DMS would have to be configurable per scope to determine
* which isolation level to use
* whether one transaction should be used or one transaction per `sp_getchanges` 

What do you think? Am I crazy or missing something?

**Comment by Mimetis** [comment]
I understand the need behind the multiple transactions for each `sp_getchanges`.

That's being said, the problem I see in the first place, is that you may have new records inserted between two transactions, in any tables involved in the sync process.

I'm not sure it can have any incidence on the next sync (or the current one), to be honest.

But as you mentioned, the new snapshot isolation will make this behavior obsolete (if you have some performances issues here)

For you (using an old DMS version), did you tried to set the isolation level directly in the stored procedures ?

**Comment by gentledepp** [comment]
> For you (using an old DMS version), did you tried to set the isolation level directly in the stored procedures ?
No I did not try setting the isolation leve.

> That's being said, the problem I see in the first place, is that you may have new records inserted between two transactions, in any tables involved in the sync process.
This cannot happen, because if another transaction COMMITS between one of the `sp_getchanges` calls, it does not matter if we use the "1 transaction for all" or "1 transaction each" approach, as **read committed** will return those rows in any case ;-)

**Comment by Mimetis** [comment]
Implemented in last version ;)
