### ISSUE TITLE
Add and drop column in existing table for sync

### ISSUE THREAD

**Issue by Vinit456789** [Mimetis/Dotmim.Sync#578]
I am using using your application for syncing  of data between server (sql) and client(sqllite ). but not able sync newly added columns in existing tables from server

**Comment by Mimetis** [comment]
if you are adding new columns in server tables, and it's not working, try to:
- Specify the columns name in your Setup Table (Something like `setup.Tables["Address"].Columns.AddRange(new string[] { "AddressId", "AddressLine1", "AddressLine2", "City", "StateProvince", "CountryRegion", "PostalCode" }); ` )
- If it's still not working, try to `DeprovisionAsync()` and `ProvisionAsync()` your server and client

**Comment by ZhangChengJie** [comment]
It works well, but what causes it?
