### ISSUE TITLE
Server always wins even while using ConflictResolutionPolicy.ClientWins

### ISSUE THREAD

**Issue by Nobody84** [Mimetis/Dotmim.Sync#580]
Hi, 
I tried to using the sync service to sync a SqlServer (mssql) databsae behind a AspNetCore WebApi with a local Sqlite database.

I'm using a `WebClientOrchestrator` (serverOrchestator) and a `SqliteSyncProvider` (clientProvider) to create a `SyncClient` and set the `ConflictResolutionPolicy` to `ClientWins`.
```
var options = new SyncOptions() { ConflictResolutionPolicy = ConflictResolutionPolicy.ClientWins };
var syncAgent = new SyncAgent(clientProvider, serverOrchestrator, options);
```

### Environment
NetCore (3.1.0)
AspNetCore (3.1.10)

Dotmim.Sync.Core (0.8.0)
Dotmim.Sync.SqlServer (0.8.0)
Dotmim.Sync.SqlServer.ChangeTracking (0.8.0)
Dotmim.Sync.Web.Server (0.8.0)
 Dotmim.Sync.Web.Sqlite (0.8.0)

Microsoft.EntitifyFramework (5.0.8)

### Reproduction steps:
1.Create a new row on the SqlServer and perform a synchronization `syncAgent.SynchronizeAsync()` to make sure both databases contains the the same row. (Initial Sync)
2. Make a modification to the this row on both databases.
3. Performe a synchronization `syncAgent.SynchronizeAsync()`. (Second Sync)

### Result:
The SyncAgent recogniced the conflict but instead of pushing the changes made on the client side to the server it pulls the changes from server to the client.

### Example project
I created a project to reproduce the issue: [https://github.com/Nobody84/DotmimSyncIssue](https://github.com/Nobody84/DotmimSyncIssue).
**Note** that the SqlServer connection strings must be modified in the _WebApi/appsettings,json_ and _DotmimSyncIssue/Program.cs_
This is the output after running the DotmimSyncIssue project.
```
### Initial Sync
Synchronization done.
        Total changes  uploaded: 1
        Total changes  downloaded: 2
        Total changes  applied: 1
        Total resolved conflicts: 1
        Total duration :00.00:00.958

### Value stored in the databases before sync.
Sqlite   : Text=My new Item. Local modfication., Created=10:34:00.401
SqlServer: Text=My new Item. Remote modfication., Created=10:34:00.401

### Second Sync
Synchronization done.
        Total changes  uploaded: 1
        Total changes  downloaded: 1
        Total changes  applied: 1
        Total resolved conflicts: 1
        Total duration :00.00:00.074

### Value stored in the databases after sync.
Sqlite   : Text=My new Item. Remote modfication., Created=10:34:00.401
SqlServer: Text=My new Item. Remote modfication., Created=10:34:00.401
```

I wonder if I'm missing something or did something wrong.

**Comment by Mimetis** [comment]
Hey @Nobody84 !

Since conflicts are always resolved on the server side, you need to set the `ConflictResolutionPolicy` option on the server side as well.
So far, in your `Startup.cs`, just add a `SyncOptions`:

``` cs

var connectionString = Configuration.GetConnectionString("SqlServer");
var options = new SyncOptions {  ConflictResolutionPolicy = ConflictResolutionPolicy.ClientWins};

var tables = new string[] { "Items" };

services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString, tables, options);

```
That being said, the conflict resolution on the client is not mandatory (and is not used in this http mode case)

**Comment by Nobody84** [comment]
Hey @Mimetis 

That did the trick. I really must have overread this.
I updated my example to consider your proposed changes and it worked. The changes are pushed to github too.

Thanx for help.
