### ISSUE TITLE
PostgreSQL implementation state

### ISSUE THREAD

**Issue by EvK** [Mimetis/Dotmim.Sync#584]
What's current state \ plans for PostgreSQL sync provider implementation? I see there is `Dotmim.Sync.PostgreSql` project, but it's not included in main solution, likely because it doesn't compile. Was it abandoned (last change 8 months ago)? Any plans for it? Very nice sync framework, but unfotunately I need it specifically for PostgreSQL databases.

**Comment by Mimetis** [comment]
I'm not a PostgreSQL expert.
I'm searching developers with a good knowlegde in PostgreSQL to help me implementing the sync provider.
Until I found someone, I'm afraid the provider will stay as it is today (a simple draft)

**Comment by WasimAhmad** [comment]
hi @Mimetis, 
I hope this message finds you well.

I am currently working on PostgreSQL provider. During initial testing its working fine for DB types that can directly map with DBType.type. what's about array type in postgresql like text[], int[] etc. how can i map these type? any idea?

**Comment by WasimAhmad** [comment]
What if we use an extended form of DbType in Dotmim.Sync to accommodate more types accurately that are not common.?

**Comment by Mimetis** [comment]
Hey @WasimAhmad 
Thanks **A TON** for your contribution! (Did not checked your **PR** yet, but will do asap)

The thing about exotic types like PostgreSQL arrays is "what is the corresponding type for `SQLite` `MySQL` `MariaDB` or `SQL Server`"?

If we can map a specific type to all the other engines, we can find a way, I guess (and maybe extending `DbType` as you are suggesting, since we are in control of all parts where it's used)

**Comment by WasimAhmad** [comment]
> The thing about exotic types like PostgreSQL arrays is "what is the corresponding type for `SQLite` `MySQL` `MariaDB` or `SQL Server`"?

thanks for your quick response.

May be no corresponding type in all other DBs! You are right. I forgot the that point as i was focusing mainly on postgreSQL. 
I know framework is designed to support different type of databases at client and server sides. in that case all types can't me mapped.

but if we have the sample provider on both sides all types should mapped. please correct me if i am wrong.

**Comment by Mimetis** [comment]
> but if we have the sample provider on both sides all types should mapped. please correct me if i am wrong.

yes

**Comment by WasimAhmad** [comment]
same provider not sample. is it a typo? 😄

**Comment by Mimetis** [comment]
Just quoted your sentence ;)
