### ISSUE TITLE
EF core 5 auto-creates many-to-many joining table that does not get tracked by DotMim

### ISSUE THREAD

**Issue by hbraasch** [Mimetis/Dotmim.Sync#586]
I could not find anything on this topic in the documentation so decided to post it here. Help shall be much appreciated.
I'm using Entity Framework 5 Core (EF5core), code-first to generate the database. EF5core allows one to define a many-to-many relationship in the DbContext without the need to declare a joining table. 
Since there is therefore no C# class for the joining table, I cannot add it to the SyncSetup list of tables to enable tracking.
Am I missing something? Is there a workaround?

For completeness, I'm showing an example of tables created during provisioning, showing there is a missing tracking table.

![image](https://user-images.githubusercontent.com/7484186/128791932-658d7a24-7100-49b5-bb2e-9f890b1b7a6e.png)

Thanks and regards

**Comment by Mimetis** [comment]
If the table is not in the `SyncSetup` instance, it won't be part of the sync.

**Comment by hbraasch** [comment]
Thanks, I thought so much. Thanks for the reply.I then tried the alternative EF Many-to-Many approach suggested by the website https://www.entityframeworktutorial.net/efcore/configure-many-to-many-relationship-in-ef-core.aspx Here I came across the problem that DotMim Sqlite does not handle [Composite Primary Keys] created by EF like [modelBuilder.Entity<StudentCourse>().HasKey(sc => new { sc.StudentId, sc.CourseId })] correctly. It translates it right in SqlServer, but not in Sqlite. It does not give a clear error message except stating it does not find a specific column in a unspecific table and it took me quite a while to realise the problem lies with the composite key and Sqlite. However, once I realised the cause of the problem I managed to work around by adding an unique key to the joining table, then reference that with the Fluent statement. Anyway, would you like me to raise an issue on your Git Repo insofar the problem with composite keys, or do you expect not to address that functionality? Raising the issue with maybe the workaround could help others not getting into the same trouble? Thanks and regardsHeinrich Braasch Sent from Mail for Windows From: Sébastien PertusSent: Monday, 16 August 2021 8:40 AMTo: Mimetis/Dotmim.SyncCc: Heinrich Braasch; AuthorSubject: Re: [Mimetis/Dotmim.Sync] EF core 5 auto-creates many-to-many joining table that does not get tracked by DotMim (#586) If the table is not in the SyncSetup instance, it won't be part of the sync.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mimetis** [comment]
Your message is not readable.

Since your problem seems more related to `EF Core` than `DMS`, I will close this issue.
If you feel it should be re-opened, do not hesitate to comment here, and get more details on the issue.

**Comment by hbraasch** [comment]
What I tried to say is that when EF creates a SQL schema with a table with a composite key, Dotmim.Sync.Sqlite does not like that kind of SQL table. It can only handle one with a regular single key. The Dotmim.Sync.SqlServer on the remote side appears to handle composite keys well. Thanks and regardsHeinrich Sent from Mail for Windows From: Sébastien PertusSent: Saturday, 21 August 2021 11:16 PMTo: Mimetis/Dotmim.SyncCc: Heinrich Braasch; AuthorSubject: Re: [Mimetis/Dotmim.Sync] EF core 5 auto-creates many-to-many joining table that does not get tracked by DotMim (#586) Your message is not readable.Since your problem seems more related to EF Core than DMS, I will close this issue.If you feel it should be re-opened, do not hesitate to comment here, and get more details on the issue.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hbraasch** [comment]
What I tried to say is that when EF creates a SQL schema with a table with a composite key, Dotmim.Sync.Sqlite does not like that kind of SQL table. It can only handle one with a regular single key. The Dotmim.Sync.SqlServer on the remote side appears to handle composite keys well.

**Comment by Mimetis** [comment]
Sqlite should handle composite key

**Comment by hbraasch** [comment]
Thanks. I might take some time to create a simple sample project to demonstrate my problem. RegardsHeinrich Sent from Mail for Windows From: Sébastien PertusSent: Sunday, 29 August 2021 6:24 AMTo: Mimetis/Dotmim.SyncCc: Heinrich Braasch; AuthorSubject: Re: [Mimetis/Dotmim.Sync] EF core 5 auto-creates many-to-many joining table that does not get tracked by DotMim (#586) Sqlite should handle composite key—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
