### ISSUE TITLE
Synchronization Azure and SQLite - timeout

### ISSUE THREAD

**Issue by ondrejfiala** [Mimetis/Dotmim.Sync#59]
Hello Sebastien,

I am trying to synchronize Azure SQL database and local SQLite database. Server database is containing data (around 80MB) and SQLite should be created during the process. I use SqlSyncProvider and SqliteSyncProvider.

It has problem with proper provisioning. In original setting it always ends by exception _"Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding."_ during the **DatabaseApplying** phase. Setting properties DownloadBatchSizeInKB, ConnectTimeout, LoadBalanceTimeout doesn't help.

Temporary solution is to delete data in bigger tables (over 1K of records), selectively execute provisioning on server tables, get back data and then synchronize. Is timeout properly set in library? Or there are other ways except ConnectTimeout, LoadBalanceTimeout? It seems, that problem is between library and connection objects.

Thank you, Ondrej

**Comment by Mimetis** [comment]
The server side schema and data generation is taken too long time....

I don't know yet, how to deal with this situation... 
Let me think about it, I think a solution could be to generate a "ping" signal during the server generation
