### ISSUE TITLE
Question: Compression

### ISSUE THREAD

**Issue by mrauls** [Mimetis/Dotmim.Sync#596]
In this issue, https://github.com/Mimetis/Dotmim.Sync/issues/155, you seem to mention in point no. 10 that "our custom serialization mechanism already compresses data ... we are currently working with MessagePack and combine it with LZ4 compression"

I just wanted to confirm that 
1. This is accurate and still the case
2. If this is turned on by default, and/or is this configurable some place

I couldn't find any other mention of this in the documentation so I just wanted to confirm that I understood that comment correctly, and if so you might want to mention that more prominently this as that is a great feature.

**Comment by Mimetis** [comment]
It's not implemented by default in DMS
You can create your own serializer. You already have a small sample here to do that:

By default, the serialization mechanism is JSON et compression is GZIP web default compression
