### ISSUE TITLE
Unable to use Dotmim.Sync.Web.Client sync with Xamarin Forms (UWP) if sync progress requested

### ISSUE THREAD

**Issue by hbraasch** [Mimetis/Dotmim.Sync#599]
Sorry for the trouble but I am unable to get Xamarin Forms (UWP) to work. It responds with a exception [Send is not supported in the Windows Runtime SynchronizationContext]

![UwpProblem](https://user-images.githubusercontent.com/7484186/131199475-4450613f-c2c3-49d8-b872-f61793bee402.png)

For the test I've made an exact copy of the XamSyncSample in your samples folder, but targeting UWP, not Android.
I've attached my project for demonstration.
[XamUdpDotmimTest2.zip](https://github.com/Mimetis/Dotmim.Sync/files/7069844/XamUdpDotmimTest2.zip)

 In your documentation it says [Create any kind of client application (Console, Windows Forms, WPF …)], but could it be that [Dotmim.Sync.Web.Client] is not updated to also support UWP?

Your help shall be much appreciated.
Thanks and regards

**Comment by hbraasch** [comment]
I really want this to work so I did some debugging into the library. 

It boil down to the statement [m_synchronizationContext.Send(m_invokeHandlers, value);] in [SynchronousProgress.cs	line 74] which is not supported.

A dirty workaround is therefore to set the [progress] object in the user statement [var r = await this.syncAgent.SynchronizeAsync(syncType, null);] to null , to get the sync to work. Which is fine, but one now loses some insight into the syncing progress.

It would therefore be very nice to have this issue fixed.

Thanks and regards.

**Comment by Mimetis** [comment]
Don't use `SynchronousProgress<T>`. 
This synchronised progress object has been created to work only with console application

Use a simple `Progress<T>`.

Let me know if it's resolving your issue

**Comment by hbraasch** [comment]
Perfect! That resolved my issue. Thanks
