### ISSUE TITLE
Does Dotmim.Sync support batched uploads?

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#60]
Hello!

I could not find the answer in the source code so easily, so sorry for bothering you.
Is the batchsize only used for downloads, or also for uploads?

Because the problems with batches we had in sync.winrt was that there was no upload batching.

thank you for your time!

**Comment by Mimetis** [comment]
Hey @gentledepp 
Yes it's supported by default :)
