### ISSUE TITLE
Using Dotmim.Sync.Web.Client with .NET MAUI make error at build time

### ISSUE THREAD

**Issue by M144-Coder** [Mimetis/Dotmim.Sync#600]
I am building .NET MAUI Preview 7 (Android and iOS) app. When I install Dotmim.Sync.Web.Client package it causes this error:

`Error	NETSDK1082	There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'iossimulator-x64'.	MAUIApp	C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	419`

This is my .csproj file

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		
		<TargetFrameworks>net6.0-ios;net6.0-android</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<RootNamespace>MauiApp</RootNamespace>

		
		<ApplicationTitle>MauiApp</ApplicationTitle>

		
		<ApplicationId>com.companyname.MauiApp</ApplicationId>

		
		<ApplicationVersion>1.0</ApplicationVersion>
		<AndroidVersionCode>1</AndroidVersionCode>
	</PropertyGroup>

	<ItemGroup>
		
		<MauiImage
			Include="Resources\appicon.svg"
			ForegroundFile="Resources\appiconfg.svg"
			IsAppIcon="true"
			Color="#512BD4" />

		
		<MauiSplashScreen Include="Resources\appiconfg.svg" Color="#512BD4" />

		
		<MauiImage Include="Resources\Images\*" />

		
		<MauiFont Include="Resources\Fonts\*" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Dotmim.Sync.Core" Version="0.8.0" />
	  <PackageReference Include="Dotmim.Sync.Web.Client" Version="0.8.0" />
	</ItemGroup>

	<PropertyGroup>
		<RuntimeIdentifier Condition="$(TargetFramework.Contains('-ios'))">iossimulator-x64</RuntimeIdentifier>
		<RuntimeIdentifiers Condition="$(TargetFramework.Contains('-android'))">android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
		<UseInterpreter Condition="$(TargetFramework.Contains('-android'))">False</UseInterpreter>
		<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
	</PropertyGroup>

</Project>

**Comment by Mimetis** [comment]
Hello @M144-Coder 

`DMS `is not yet compiled to target `.Net 6`, since `.Net 6` is still in preview.
Once it will have reached a final version, I will publish a new version targeting `.Net 6` also.

For now, what you can do is (I did not tested these 2 solutions, but it's worth a try, I guess):
- Create a new library project, targeting `.Net standard 2.0`. That will force nuget to get the compatible version of `DMS`. Then try to reference this library in your .`Net 6 MAUI` application.
- Clone the `DMS` repo and try to compile everything with `.Net 6`. Since `DMS `is already compatible with `.Net 5`, I guess it should not be complicated to make it compatible with `.Net 6`

Let me know if one of these solutions is working for you.

**Comment by M144-Coder** [comment]
Hello @Mimetis 

I have tried the first solution and it worked very well. Once a new version is published I will move code to the main project and reference the new library from there. Thank you very much.

**Comment by Mimetis** [comment]
I will comment this post once the .Net 6 version will be ready !

**Comment by BoobalanK** [comment]
Hey @Mimetis , I'm still getting error when i build the project in .NET MAUI with .NET 6 using Dotmim.Sync.Web.Client version 0.9.3

Please can you shed some light

**Comment by Mimetis** [comment]
The last version is targetting .net 6 
It should work
Can you provide a simple repro I can test and see the error ?

**Comment by BoobalanK** [comment]
Hey @Mimetis , Thanks for the response.
here is the zip file of a sample mauibalzor project.
[MauiBlazorApp1.zip](https://github.com/Mimetis/Dotmim.Sync/files/8087367/MauiBlazorApp1.zip)

The below is the error I'm getting

```
Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | NETSDK1082 | There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'android-x86'. | MauiBlazorApp1 | C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets | 427 | 
``` 
@keithmullins, FYI

**Comment by BoobalanK** [comment]
Hey @Mimetis ,
with regards to the above issue 

> Hey @Mimetis , I'm still getting error when i build the project in .NET MAUI with .NET 6 using Dotmim.Sync.Web.Client version 0.9.3 I even tried the solutions you told. Still no luck
> 
> Please can you shed some light

With Regards to the above issue, I have installed the latest beta version **0.9.4-beta-0764** and tried, my build error gone but i get the below exception after SynchornizeAsync is called

`{Dotmim.Sync.Web.Client.HttpSyncWebException: Buffer cannot be null. (Parameter 'buffer')
   at Dotmim.Sync.Web.Client.HttpRequestHandler.HandleSyncError(HttpResponseMessage response)
   at Dotmim.Sync.Web.Client.HttpRequestHandler.SendAsync(HttpClient client, String requestUri, String sessionId, String scopeName, HttpStep step, Byte[] data, String ser, IConverter converter, String hashString, String contentType, CancellationToken cancellationToken)
   at Dotmim.Sync.SyncPolicy.<InternalExecuteAsync>d__17`1[[System.Net.Http.HttpResponseMessage, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at Dotmim.Sync.Web.Client.HttpRequestHandler.ProcessRequestAsync(HttpClient client, String baseUri, Byte[] data, HttpStep step, Guid sessionId, String scopeName, ISerializerFactory serializerFactory, IConverter converter, Int32 batchSize, SyncPolicy policy, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.Web.Client.WebClientOrchestrator.GetSnapshotAsync(SyncSet schema, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.<>c__DisplayClass53_0.<<SynchronizeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress`1 progress)
   at ShopScan.Pages.ScanPage.OnInitializedAsync() in C:\MyWorkspace\Handheld.ShopScan\ShopScan\Pages\ScanPage.razor.cs:line 98}`

I also tried this in a console app with .NET 6 target, it still throws the same issue. The schema is created but table doesn't have any data

Please assist me.

Thanks
BK

**Comment by Mimetis** [comment]
Do you have a columns named "`buffer`" ?

**Comment by BoobalanK** [comment]
no @Mimetis. No column named buffer is found on client and server side.

**Comment by Mimetis** [comment]
I don't have any clue on that :)
As I said, we need to wait until MAUI is released to debug it
