### ISSUE TITLE
Table [TableName] does not exist

### ISSUE THREAD

**Issue by akema-trebla** [Mimetis/Dotmim.Sync#606]
According to the documentation, adding new tables should automatically get synced on clients when `await agent.SynchronizeAsync();` is called but I end up getting an Exception saying Table [TableName] does not exist.

Kindly advise.

**Comment by Mimetis** [comment]
When you are adding a table, you need to add it also in your SyncSetup

**Comment by akema-trebla** [comment]
Sorry, my bad. There was a typo in the table name. Thanks
