### ISSUE TITLE
Sync to new device with DMS 0.8.1-beta-0687 does not follow relational hierarchy

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#616]
I did not experience this issue in previous versions but it might still be something wrong with my configuration.
On the server  new SQL Server database via a web api using `DMS 0.8.1-beta-0687`

In `ConfigureServices` I have

```
string scope = "All";
tables = new string[] { "Orders", "OrderDetails" };
services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString, scope, tables, syncOptions);

```
On the client I have the same scope specified
`services.AddSyncServer<SqlSyncChangeTrackingProvider>(usersConnectionString, scope, tables, syncOptions)`

An empty SQLite database on the client is not created by DMS
```
CREATE TABLE [OrderDetails] (
	"OrderDetailId"		integer NOT NULL,
	"OrderId"		integer NOT NULL,
    PRIMARY KEY ([OrderDetailId])
,
    FOREIGN KEY ([OrderId])
        REFERENCES [Orders]([OrderId])
);
```

I am able to add a new order and order detail on the client and sync successfully to the new server database, so DMS is syncing tables from the client to the server in the correct order. However when I sync to a new client,  DMS tries to sync OrderDetails before Orders and a foreign key constraint violation is thrown by SQLite.

I've also tried setting `DisableConstraintsOnApplyChanges=true` on the client and the server. This is not my preferred option, but it worked in previous versions but not in `DMS 0.8.1-beta-0687`.

I thought DMS would either follow the order specified in the scope, or attempt to follow the relational hierarchy. How do I ensure the relational hierarchy is followed in sync?

**Comment by Mimetis** [comment]
I tried your example with [AdventureWorks](https://github.com/Mimetis/Dotmim.Sync/blob/master/CreateAdventureWorks.sql) with tables `SalesOrderHeader` and `SalesOrderDetails`.

On the server side, I set this configuration:

``` cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    services.AddDistributedMemoryCache();
    services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

    var connectionString = Configuration.GetSection("ConnectionStrings")["SqlConnection"];

    var serverOptions = new SyncOptions()
    {
        DisableConstraintsOnApplyChanges = false,
    };

    var tables = new[] {
        "SalesOrderHeader",
        "SalesOrderDetail"
    };

    var syncSetup = new SyncSetup(tables)
    {
        StoredProceduresPrefix = "sp",
        StoredProceduresSuffix = "",
        TrackingTablesPrefix = "t",
        TrackingTablesSuffix = ""
    };

    services.AddSyncServer<SqlSyncChangeTrackingProvider>(serverProvider.ConnectionString, syncSetup, serverOptions);
}
```

The client side is pretty classic:

``` cs
   var localOrchestrator = new WebClientOrchestrator(serviceUri);

   var clientOptions = new SyncOptions();

   var localProgress = new SynchronousProgress<ProgressArgs>(s =>
   {
       var tsEnded = TimeSpan.FromTicks(DateTime.Now.Ticks);
       var tsStarted = TimeSpan.FromTicks(startTime.Ticks);
       var durationTs = tsEnded.Subtract(tsStarted);

       Console.ForegroundColor = ConsoleColor.Green;
       Console.WriteLine($"{durationTs:mm\\:ss\\.fff} {s.ProgressPercentage:p}:\t{s.Message}");
       Console.ResetColor();
   });

   var agent = new SyncAgent(clientProvider, localOrchestrator, clientOptions);

   var s = await agent.SynchronizeAsync(localProgress);
   Console.WriteLine(s);
```

The first sync from server to client, (where **client** database is created by `DMS`) worked as expected:

![image](https://user-images.githubusercontent.com/4592555/133910481-e9635d95-dd6d-4aa7-8efd-6450646bce1b.png)

Then I made this rows additions on the **server** side:

``` sql
Declare @SalesOrderId int;

INSERT INTO [dbo].[SalesOrderHeader] ([CustomerID], [DueDate], [ShipMethod])
     VALUES (29847, GetDate(), 'SERVER')

Select @SalesOrderId = SCOPE_IDENTITY()

Insert into SalesOrderDetail ([SalesOrderID], [OrderQty], [ProductID], [UnitPrice])
VALUES (@SalesOrderId , 1, 710, 10.00)

Insert into SalesOrderDetail ([SalesOrderID], [OrderQty], [ProductID], [UnitPrice])
VALUES (@SalesOrderId , 1, 710, 10.00)

Select * from SalesOrderHeader soh
Inner join SalesOrderDetail sod on sod.SalesOrderID = soh.SalesOrderID
Where soh.SalesOrderID = @SalesOrderId
```

And the result is as expected (**downloaded** to the **client**):

![image](https://user-images.githubusercontent.com/4592555/133910561-1dbc421f-cfe6-4e69-968b-1e6f77233c8b.png)

Then I did the same on the **client** side:

``` sql
Declare @SalesOrderId int;

INSERT INTO [dbo].[SalesOrderHeader] ([CustomerID], [DueDate], [ShipMethod])
     VALUES (29847, GetDate(), 'CLIENT')

Select @SalesOrderId = SCOPE_IDENTITY()

Insert into SalesOrderDetail ([SalesOrderID], [OrderQty], [ProductID], [UnitPrice])
VALUES (@SalesOrderId , 1, 710, 10.00)

Insert into SalesOrderDetail ([SalesOrderID], [OrderQty], [ProductID], [UnitPrice])
VALUES (@SalesOrderId , 1, 710, 10.00)


Select * from SalesOrderHeader soh
Inner join SalesOrderDetail sod on sod.SalesOrderID = soh.SalesOrderID
Where soh.SalesOrderID = @SalesOrderId
```

And it worked, as well (**upload** rows to the **server**):

![image](https://user-images.githubusercontent.com/4592555/133910573-951daa2a-e6c1-4bf5-93af-3cea77968a27.png)

What is the differences between me and you ?

**Comment by VagueGit** [comment]
There are two differences ... I don't set prefixes and the SQLite db is not created by DMS. I'll experiment with a SQLite db created by DMS and see if I can pick up the differences. I'll get back to you. You must be up very late working on this. Thank you very much.

**Comment by VagueGit** [comment]
I can confirm my configuration works if I allow DMS to create the SQLite db. I'll examine the differences and report back if I find anything that might be useful to others.

Thank you once again for your assistance.

**Comment by VagueGit** [comment]
The local SQL db had sync scopes already added to scope_info. Once I removed them and allowed DMS to create the scopes in the db, all was tickety-boo.
