### ISSUE TITLE
Column Is null-----> Syatem.ArgumentException: Column is null

### ISSUE THREAD

**Issue by AmalKRamachandran** [Mimetis/Dotmim.Sync#617]
![Untitled](https://user-images.githubusercontent.com/91714740/135566092-75bd4b48-ea71-4fe9-b18d-9cdff0c1ec29.png)

I am trying to sync some tables of databases with the same structure having data.  I have created Provision for both server and client by

"   _**var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);
 var newSchema = await Task.Run(() => remoteOrchestrator.ProvisionAsync(SyncProvision.StoredProcedures));
               
                newSchema = await Task.Run(() => remoteOrchestrator.ProvisionAsync(SyncProvision.TrackingTable));
                newSchema = await Task.Run(() => remoteOrchestrator.ProvisionAsync(SyncProvision.Triggers) );**_"

When I try to sync data from the client for the first time I have faced this error.  ("_**await agent.SynchronizeAsync(SyncType.Normal);**_")
When I use ("  _**await agent.SynchronizeAsync(SyncType.Reinitialize);**_") this will work, And once it worked, SyncType.Normal also start working. Once the server sync with any of the client databases then it's working perfectly with other clients with ( " _**await agent.SynchronizeAsync(SyncType.Normal);**_" ) from the first time itself. Please let me know if I had missed anything.

**Comment by Mimetis** [comment]
does your setup contains all columns or are you filtering some columns ?

**Comment by AmalKRamachandran** [comment]
All columns

**Comment by Mimetis** [comment]
are u creating the client schema by yourself before sync ?

**Comment by AmalKRamachandran** [comment]
yes

**Comment by Mimetis** [comment]
maybe you are creating a columns that does not allow null, and receive a null column from server

**Comment by AmalKRamachandran** [comment]
I had checked that once. Ok, let me check this once more.

**Comment by AmalKRamachandran** [comment]
I had checked with a single table to ensure there is no null column without values Still, I get this error. When Reinitialize using (" await agent.SynchronizeAsync(SyncType.Reinitialize);"), its working. Once it works, then there will not be any error with other clients created.

**Comment by Mimetis** [comment]
Well, I will be able to help you if you can provide a simple repro project.

**Comment by AmalKRamachandran** [comment]
I am sending you the link to a simple repro project what we did.
[https://we.tl/t-XHUHTY70ek](url)

**Comment by Mimetis** [comment]
Here are the things I found:

Use `SqlSyncChangeTrackingProvider` everywhere (you are using `SqlSyncProvider` when provisioning, that will conflict with `SqlSyncChangeTrackingProvider` later)

Make provisioning in order:

``` cs
await localOrchestrator.ProvisionAsync(serverSchema, SyncProvision.Table);
await localOrchestrator.ProvisionAsync(serverSchema, SyncProvision.TrackingTable);
await localOrchestrator.ProvisionAsync(serverSchema, SyncProvision.StoredProcedures);
await localOrchestrator.ProvisionAsync(serverSchema, SyncProvision.Triggers);
```

Or 

``` cs
var newSchema = await remoteOrchestrator.ProvisionAsync(SyncProvision.Table | SyncProvision.TrackingTable | SyncProvision.StoredProcedures | SyncProvision.Triggers);
```

Upgrade DMS to version `0.8.0` (you are running `0.5.7`)

![image](https://user-images.githubusercontent.com/4592555/136001780-5e94daea-f2f8-4fd9-ad97-6ea1c5cedac6.png)

**Comment by AmalKRamachandran** [comment]
It's working for me now.  Your guidance is so helpful. Thank you

**Comment by AmalKRamachandran** [comment]
![Screenshot 2021-10-06 184719](https://user-images.githubusercontent.com/91714740/136209441-f2f65a45-910d-4fc0-93c6-24252ef87be8.png)
I have faced another issue. Now first-time sync works fine. and when we try to sync again its shows the above error.

**Comment by Mimetis** [comment]
Well since you were using an old version of `DMS`, you did not applied the Upgrades commands.
My advice would be to test with a fresh database, where you never synced anything (and where all metadatas have not been created yet by `DMS`)

Otherwise, you can do this kind of trick, **Only One Time**, to reset everything correctly:

``` cs
var serverConnectionString = connServer;
var clientConnectionString = connClint;
var serverProvider = new SqlSyncChangeTrackingProvider(serverConnectionString);
var clientProvider = new SqlSyncChangeTrackingProvider(clientConnectionString);
var options = new SyncOptions();

var agent = new SyncAgent(clientProvider, serverProvider, options, setup);

await agent.LocalOrchestrator.DeprovisionAsync();
await agent.RemoteOrchestrator.DeprovisionAsync();

var result = await agent.SynchronizeAsync(SyncType.Reinitialize);

```

**Comment by AmalKRamachandran** [comment]
I have updated DMS to (0.8.0.0) and tried with fresh client and server database,But still have this issue. Let me try this trick and update you soon.
