### ISSUE TITLE
Cannot sync Identity column that is not a PK

### ISSUE THREAD

**Issue by gb0o** [Mimetis/Dotmim.Sync#62]
Hi @Mimetis ,

I have a table I cannot sync from SQL Server. It contains an Identity column that is not a PK. DotMim.Sync thinks the column should be synchronized however the update trigger fails with SqlException("Cannot update identity column 'Id'"). The insert trigger looks fine because IDENTITY_INSERT is enabled for inserts. 

Is it possible skip Identity columns in update triggers? Is there a better solution other than modifying the schema? 

This issue is similar to constraint problems encountered in https://github.com/Mimetis/Dotmim.Sync/issues/44 but in my case all updates fail.

Example SQL causing the problem, generated by SqlBuilderProcedure.BuildUpdateCommand()
```
SET @sync_row_count = 0;

UPDATE [Simple]
SET  [Id] = @Id
FROM [Simple] [base]
JOIN [Simple_tracking] [side]
ON [base].[PrimaryId] = [side].[PrimaryId]
WHERE ([side].[timestamp] <= @sync_min_timestamp OR @sync_force_write = 1)
AND ([base].[PrimaryId] = @PrimaryId);

SET @sync_row_count = @@ROWCOUNT;
```

* Schema script for SSMS
```
USE [master]
GO

CREATE DATABASE [SyncIdent]
GO
 
USE [SyncIdent]
GO

CREATE TABLE [dbo].[Simple](
	[PrimaryId] [int] NOT NULL,
	[Id] [int] IDENTITY NOT NULL,
        CONSTRAINT [PK_Simple] PRIMARY KEY CLUSTERED ([PrimaryId] ASC)
) ON [PRIMARY]
GO
```

* Client console app setup
Dotmim.Sync\Samples\Dotmim.Sync.SampleConsole\Program.cs
```c#
/// <summary>
/// Test a client syncing through a web api
/// </summary>
private static async Task TestSyncThroughWebApi()
{
    // Sqlite Client provider for a Sql Server <=> Sqlite sync
    var clientProvider = new SqliteSyncProvider("c:/work/test.db");
    var proxyClientProvider = new WebProxyClientProvider(new Uri("http://localhost:54348/api/values"));

    var agent = new SyncAgent(clientProvider, proxyClientProvider);

    agent.SyncProgress += (s, a) => Console.WriteLine($"[Client] : {a.Message} {a.PropertiesMessage}");
    proxyClientProvider.SyncProgress += (s, a) => Console.WriteLine($"[Server] : {a.Message} {a.PropertiesMessage}");

    Console.WriteLine("Press a key to start (be sure web api is running...)");
    Console.ReadKey();
    do
    {
        Console.Clear();
        Console.WriteLine("Web sync start");
        try
        {
            var s = await agent.SynchronizeAsync(SyncType.Normal);
            Console.WriteLine(s);
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
        }

        Console.WriteLine("Sync Ended. Press a key to start again, or Escape to end");
    } while (Console.ReadKey().Key != ConsoleKey.Escape);

    Console.WriteLine("End");
}
```
* Web server setup
Dotmim.Sync\Samples\Dotmim.Sync.SampleUWP\UWPSyncSample\UWPSyncSampleWebServer\Startup.cs

```c#
// Add services to the container.
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc();

    var connectionString = @"Data Source=DESKTOP-BSIVU73;Initial Catalog=SyncIdent;Integrated Security=true;";
    services.AddSyncServer<SqlSyncProvider>(connectionString, configuration =>
    {
        configuration.Add(new String [] { "Simple" });
    });
}
```

**Comment by Mimetis** [comment]
Thx for submitting this bug.
I will make a check on this, asap !!

Seb

**Comment by Mimetis** [comment]
Hey @gb0o 

I've resolved this issue. 
That was a little bit tricky, but eventually it should work now.
Be careful, you have an auto increment column that is NOT a primary column, so you can't UPDATE this value.   
All the stored procedures that references this column won't have the column as part of the update statement.

Again, you can test the solution with the last commit on the master branch.

Let me know if this is resolving your issue :)

Seb

**Comment by gb0o** [comment]
Hi @Mimetis, I have confirmed I can now sync the table below which is an association table with a superfluous Id identity column and is not a primary column.
   
![image](https://user-images.githubusercontent.com/39327472/42928006-7b484f30-8b79-11e8-8cba-866db0347ba6.png)

I later removed the identity column altogether because it was simply a bad schema design. Nonetheless having Dotmim.Sync deal with it makes it a better framework. Hope the code didn't have to jump thru too many loops to make it work.

Great work again. Thanks.
