### ISSUE TITLE
Foreign key exception if Source DB has active records deletes when Sync starts between Source and Remote DB

### ISSUE THREAD

**Issue by menitamoses** [Mimetis/Dotmim.Sync#620]
I have been able to replicate this problem and so has several of our customers who use our syncing software that uses DotmimSync Framework. I am hoping you can help figure out a solution to the problem

**Setup:**
Source (Primary) DB syncs data over to BackupDB periodically ( 1 min, 3 min or whatever, This is upto our customer)
Source DB and its associated application writes change to data to DB
_**Remote is purely backup and readonly ( no writes/deletes)**_

SyncSetup is **SyncDirection.DownloadOnly**
SyncOptions has DisableConstraintsOnApplyChanges = false

Here is how the sync job is setup

At the beginning of every sync cycle from Source -> Remote (download) 
- I manually TURN OFF ForeignKey constraints on the RemoteDB
- Perform the Sync
- I manually TURN ON ForeignKey  constraint on the RemoteDB

This works very well. However, the Source DB is being actively used and there are updates and deletes. We have noticed that if there is a database DELETE operation seconds in progress as the Sync cycle starts, we end up with orphaned relational records for some of the DB tables in Source and since the data is synced over to Remote that DB also ends up with ForeignKey exceptions. This is not a Sync error but seems to be a by product of DB delete operations when a Sync is in progress

I examined the Triggers, stored procedures setup of all sync tables, is there any possibility of some underlying SQL DB setting that would cause this behavior?

If I delete the same set of records from Source when there is no sync operation in progress or about to start all relational records from the Source DB is correctly deleted ( cascade delete )

Any help you can provide in trying to understand and overcome this problem is much appreciated.

**Comment by gentledepp** [comment]
This sounds to me like you did not specify the tables in the sync-setup in dependency order.
Normally, you do not need to turn off foreign key constraints during sync. We **never** do for the exact reason: FK violation exceptions and the possibility of invalid/corrupt data.

For all the tables you synchronize, 
- make sure to list those tables first that do not have any FKs
- and then add those tables, whose FKs point to tables you already listed.

E.g.
If you have a table Customers, Orders and CustomersOrders (where CustomersOrders is a MxN table), the table order for the sync setup should be

1. Customer
2. Orders
3. CustomersOrders

or 
1. Orders
2. Customers
3. CustomersOrders 

Does this make sense to you?

**Comment by menitamoses** [comment]
I see. Thank you for explanation. It is hard to maintain a manual list of tables in code to perform Sync setup when we have multiple developers working on the same application,

However, it makes sense.
