### ISSUE TITLE
NullException in web proxy after sync is called in android app - schemaColumn is null

### ISSUE THREAD

**Issue by Menci77** [Mimetis/Dotmim.Sync#621]
Hi!

I am trying to sync an mssql database with my xamarin android app's sqlite database. So I implemented the web proxy to reach the database from the android app.
The proxy starts fine, but then when I call the sync from the android app the Post method gives a null reference error, but I cannot find what is null. There is no more error message anywhere. 
![Screenshot 2021-10-23 175725](https://user-images.githubusercontent.com/61515787/138563828-bf7b59cd-884d-43ca-81ae-1a68d027fd2d.png)
![Screenshot 2021-10-23 180107](https://user-images.githubusercontent.com/61515787/138563831-e1967cae-978e-407c-927c-3e8e3373768a.png)

In the ASP.NET Core web app's Startup file:
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();

            // [Required]: To be able to handle multiple sessions
            services.AddMemoryCache();

            // [Required]: Get a connection string to your server data source
            var connectionString = @"[my connection string]";

            // [Required]: Tables list involved in the sync process
            var tables = new string[] { "dbo.Album", "dbo.Artist", "dbo.Customer", "dbo.Invoice", "dbo.InvoiceItem", "dbo.Track" };

            // [Required]: Add a SqlSyncProvider acting as the server hub.
            services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString, tables);
        }
```

The SyncController:
```
    [ApiController]
    [Route("api/[controller]")]
    public class SyncController : ControllerBase
    {
        private WebServerManager manager;

        public SyncController(WebServerManager man) => this.manager = man; 

        [HttpPost]
        public async Task Post()
        {
            await manager.HandleRequestAsync(this.HttpContext);
        }  //----> the Null error comes 

        [HttpGet]
        public async Task Get() => await manager.HandleRequestAsync(this.HttpContext);
    }
```

In the android app the sync function that is called:
```
public async Task SyncDatabase(string connString, Context context)
        {
            var handler = HttpClientHandlerService.GetInsecureHandler();

            HttpClient httpClient = new HttpClient(handler);
            httpClient.DefaultRequestHeaders.Host = $"localhost:44372";   

            var serverOrchestrator = new WebClientOrchestrator("https://10.0.2.2:44372/api/sync", client: httpClient);   

            // Second provider is using plain sqlite provider
            var clientProvider = new SqliteSyncProvider(connString);

            var agent = new SyncAgent(clientProvider, serverOrchestrator);

            try
            {
                var result = await agent.SynchronizeAsync();   //---> error comes when this line is called

                var output = result.ToString();
                output = output.Replace("\n", " ").Replace("\t", " ").Replace("\r", " ");
                Toast.MakeText(context, output, ToastLength.Long).Show();
            }
            catch (Exception e)
            {
                Toast.MakeText(context, e.Message, ToastLength.Long).Show();
            }
        }
```
EDIT:
Tried the POST in postman I got ```{"tn":"HttpHeaderMissingExceptiopn","m":"Header dotmim-sync-scope-name is missing."}```. The stacktrace is this: ```"   at Dotmim.Sync.BaseOrchestrator.<>c__DisplayClass89_0.<SetRelations>b__1(DbRelationColumnDefinition kc)"```

I checked and the scope name is DefaultScope.
In the WebserverManager:
![serverside](https://user-images.githubusercontent.com/61515787/139528724-857ebeaa-75ae-4ef8-8284-579939dc6eb2.png)

I found in the WebServerOrchestrator's code that this gives this kind of error:
![image](https://user-images.githubusercontent.com/61515787/139529103-ee4e9ee2-2bf2-4145-baee-e2c3f9a126b1.png)

I checked the http request header, and it has the scope name too:
![httpheader_scopename](https://user-images.githubusercontent.com/61515787/139529118-90da038f-f676-4774-bfda-066fac6f93bf.png)

Let me know what further information should I supply to solve this.
Thanks.

**Comment by Mimetis** [comment]
Can u try with Last version ?
Be carefull,  the code has changed a bit.
Take a look to the samples.
Be sure you have a fresh databasr

**Comment by Menci77** [comment]
Yes, I saw that on github there are different samples than in the docs. I tried it before with 0.8.0 version but didn't work.
Now I tried with the latest version, first I got ``` Dotmi.Sync.Core.pdb not loaded``` error. That's probably because of the beta version, so I checked in VS to use nuget.org symbol server as the symbol files location. After this I got a null reference error in the BaseOrchestrator.Schema.cs ```schemaColumn``` is null.
![image](https://user-images.githubusercontent.com/61515787/139543600-b58b9cc0-db4d-4c84-8782-b99d8e9cd41a.png)

**Comment by Mimetis** [comment]
Hard to diagnostic your issue here
can you share a sample repro ?

**Comment by Menci77** [comment]
Sorry, what exactly does that mean? How to reproduce the error?

**Comment by Mimetis** [comment]
yes with a sample schema and maybe a little app to reproduice

**Comment by Menci77** [comment]
Here is the schema:
```
CREATE TABLE [dbo].[Album]
(
    [AlbumId] INT NOT NULL,
    [Title] NVARCHAR(160) NOT NULL,
    [ArtistId] INT NOT NULL,
    CONSTRAINT [PK_Album] PRIMARY KEY CLUSTERED ([AlbumId])
);

CREATE TABLE [dbo].[Artist]
(
    [ArtistId] INT NOT NULL,
    [Name] NVARCHAR(120),
    CONSTRAINT [PK_Artist] PRIMARY KEY CLUSTERED ([ArtistId])
);

CREATE TABLE [dbo].[Customer]
(
    [CustomerId] INT NOT NULL,
    [FirstName] NVARCHAR(40) NOT NULL,
    [LastName] NVARCHAR(20) NOT NULL,
    [Phone] NVARCHAR(24),
    [Email] NVARCHAR(60) NOT NULL,
    CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([CustomerId])
);

CREATE TABLE [dbo].[Invoice]
(
    [InvoiceId] INT NOT NULL,
    [CustomerId] INT NOT NULL,
    [InvoiceDate] DATETIME NOT NULL,
    [Total] NUMERIC(10,2) NOT NULL,
    CONSTRAINT [PK_Invoice] PRIMARY KEY CLUSTERED ([InvoiceId])
);

CREATE TABLE [dbo].[InvoiceItem]
(
    [InvoiceItemId] INT NOT NULL,
    [InvoiceId] INT NOT NULL,
    [TrackId] INT NOT NULL,
    [UnitPrice] NUMERIC(10,2) NOT NULL,
    [Quantity] INT NOT NULL,
    CONSTRAINT [PK_InvoiceItem] PRIMARY KEY CLUSTERED ([InvoiceItemId])
);

CREATE TABLE [dbo].[Track]
(
    [TrackId] INT NOT NULL,
    [Name] NVARCHAR(200) NOT NULL,
    [AlbumId] INT,
    [UnitPrice] NUMERIC(10,2) NOT NULL,
    [Stock] INT,
    CONSTRAINT [PK_Track] PRIMARY KEY CLUSTERED ([TrackId])
);
```
And a small application which does only one thing, calls the synchronize method
[sample.zip](https://github.com/Mimetis/Dotmim.Sync/files/7463088/sample.zip)
:

**Comment by Mimetis** [comment]
I tried with your schema with[ the android sample](https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/XamAppSync) and it works correctly, for me:

![image](https://user-images.githubusercontent.com/4592555/141380878-18ab302e-9cbf-424a-808d-943ab907a922.png)

**Comment by Menci77** [comment]
Please could you try the zipped app that I provided, because that gives the error for me. So probably the problem is hidden somewhere in there and not the database.

**Comment by Mimetis** [comment]
@Menci77 The problem is coming from your side, I will let you find the problem :)
If you find a bug inside `DMS` I will help you as much as I can. For everything else, I'm afraid I won't have enough time to investigate.
You have the sample, do the comparison and your own research, I'm sure you will figure it out soon !

**Comment by Mimetis** [comment]
by the way, your sample worked for me

![image](https://user-images.githubusercontent.com/4592555/141437073-c6019ef1-061f-494b-bd59-9e0c33572daa.png)

**Comment by Menci77** [comment]
I debugged the source code since I had no other options. It seems that in the BaseOrchestrator.Schema.cs it skips a line, thus a variable stays null, and that is why I get the error. Now I cannot do anything with this since it is the frameworks code.
On the picture you can see I put  a breakpoint to ```var schemTable = ... ```, that line never gets called. And this is why below the ```var schemaColumn= schemaTable.Columns[kc.KeyColumnName]``` gives a null reference error, the schemaTable is null.
![image](https://user-images.githubusercontent.com/61515787/141457777-d00c64e9-c357-4920-aab0-de76cc9400e2.png)
Now what can I do with this?

**Comment by Mimetis** [comment]
I will be more than happy to help, but you must provide me a sample repro.
Otherwise I really dont know how I can help you here

**Comment by Menci77** [comment]
Yeah I understand that, but the previously zipped app does this for me. I really don't understand how is that possible, that the same works for you. I checked the samples a thousand times and started again from scratch three times and still the same error. It just doesn't hit that line.

**Comment by Mimetis** [comment]
Are you using a fresh server database (like the schema you are using ?) without any sync metadata ?

Does it work with a simple application console ? (using [HelloSync](https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/HelloSync) for example)

What are your settings ? collation ? language ? numeric format ? encoding ?

**Comment by Menci77** [comment]
Yes the database is fresh.
I will check the console app right away.
I'm sorry, which settings do you mean, database settings?

**Comment by Menci77** [comment]
Okay I tried, even with the console app the sync method gives the same error.
![image](https://user-images.githubusercontent.com/61515787/141485899-3a96a367-31bf-4e9c-9c23-59398bf60655.png)

**Comment by Menci77** [comment]
Okay, so I found a solution, kind of. I tried the sync with a different database and tables, and that worked, so it was clear that dotmim has some problem with the tables I was using. So after lot of thinking I tried with a different schema name instead of dbo, since the other database that worked had something else. And it turns out the sync has some problem if the schema name is dbo, something gets mixed probably when it tries to create its own new tables.
Which is weird since for you it worked with dbo.

**Comment by Mimetis** [comment]
You may have a specific configuration on your database schema that is not compatible with DMS.

Can you generate the whole schema ?
from Microsoft Sql Server Management Studio ?
![image](https://user-images.githubusercontent.com/4592555/141531726-cf9ab54c-225b-49e7-83a7-da234d6abbba.png)

Maybe we will see some weird config here ...

**Comment by Menci77** [comment]
I generated it, it is after I synced the database and changed the schema name.

[script.txt](https://github.com/Mimetis/Dotmim.Sync/files/7533772/script.txt)

**Comment by Mimetis** [comment]
Everything worked for me with your schema `media`

**Comment by Menci77** [comment]
Yes, with media it worked for me too, but with dbo it wasn't. Sorry if that wasn't clear from what I said before.

**Comment by Mimetis** [comment]
God damnit.. I got it
When you are declaring your tables, if you are in the default dbo schema, DON'T declare table with the schema...

Like
- DON'T DO THIS : `var setup = new SyncSetup(new string[] { "dbo.Album", "dbo.Artist", "dbo.Customer", "dbo.Invoice", "dbo.InvoiceItem", "dbo.Track" });`
- DO THIS INSTEAD : `var setup = new SyncSetup(new string[] { "Album", "Artist", "Customer", "Invoice", "InvoiceItem", "Track" });`

**Comment by Menci77** [comment]
Yeah, I was wondering if that would be the way to go. Thanks for the help!

**Comment by Mimetis** [comment]
I will make some check, in the next version
