### ISSUE TITLE
Sync error 'An SqlParameter with ParameterName "@sync_scope_id" 'is not contained by this SqlParameterCollection'

### ISSUE THREAD

**Issue by Post0lachi** [Mimetis/Dotmim.Sync#623]
Hello,

Please help!

DMS will not sync changes from client to server, it gives the following error: 'An SqlParameter with ParameterName "@sync_scope_id" 'is not contained by this SqlParameterCollection'.  I deleted the local db and let the DMS create all the tables, the sync from server to client is working fine, however when I modify a value on local db I get this error.

Here is the code for sync: 

`var serverProvider = new Dotmim.Sync.SqlServer.SqlSyncProvider(serverConnectionString);
            var clientProvider = new Dotmim.Sync.SqlServer.SqlSyncProvider(localConnectionString);

            var clientOptions = new SyncOptions { BatchSize = (int)this._batchSize };
            if (!string.IsNullOrEmpty(batchSpoolLocation))
            {
                clientOptions.BatchDirectory = batchSpoolLocation;
            }

            var agent = new Dotmim.Sync.SyncAgent(clientProvider, serverProvider, clientOptions, Settings.ReplicaSl_scope, Settings.ReplicaLocal_ScopeNameSL);

            var syncContext = agent.SynchronizeAsync().GetAwaiter().GetResult();`

Thank you,
Mihai

**Comment by Mimetis** [comment]
Try to start with a fresh new database
Otherwise, try to deprovision and provision again
I guess you made some tests and your database should be inconsistent right now

**Comment by Post0lachi** [comment]
Thank you for your message, I tried to deprovision the server database, but it doesn't work, I let it run for more than 12 hours and nothing happened. 

`var serverProvider = new Dotmim.Sync.SqlServer.SqlSyncProvider(serverConnectionString);

var setup = new SyncSetup(Settings.ReplicaASV_scope);
var clientOptions = new SyncOptions();

var remoteOrchestrator = new RemoteOrchestrator(serverProvider, clientOptions, setup);

remoteOrchestrator.DeprovisionAsync().GetAwaiter().GetResult();`

**Comment by Mimetis** [comment]
Does it work with a fresh server database ?
