### ISSUE TITLE
Edit sync metadata when SQL Server data type changed from tinyint to smallint

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#625]
I've read the docs on migrations ... deprovisioning and reprovisioning. I'd like to manually edit sync metadata.

I've manually edited scope_info_server.sync_scope_schema and the _update stored proc for the table, however DMS throws `Value was either too large or too small for an unsigned byte`. Where else in sync metadata should the datatype be changed?

We are using SQL Server change tracking on the server.

**Comment by Mimetis** [comment]
Did you restart the application (to delete the application cache) ? 
You need to do it on the client side as well, I guess
Error comes from server or client ?
