### ISSUE TITLE
Multiple clients do not sync on web proxy setup

### ISSUE THREAD

**Issue by SheltonAlves** [Mimetis/Dotmim.Sync#626]
I have implemented dotmim sync into my application using ASP.NET Core Web Proxy setup.
For server Database I use SQL Server and for Client DB I have used sqlite DB.

I have used sync type as 'Normal' to perform sync which is triggered every 1 minute.

When working with single client syncing works fine, New records inserted from client DB (Sqlite) gets synced with Server DB (SQL Server) and vice versa.

However when multiple clients perform sync each client do not receive changes of other client but records gets synced with server DB.

For eg : If ClientA adds record 'X' in his local DB (sqlite) and ClientB adds record 'Y' onto his local DB(sqllite) when syncing with server both records 'X' and 'Y' gets added to server but
ClientA does not get record 'Y' on his local DB and also ClientB does not gets record from CLientA i.e record 'X', But both records gets inserted on Server DB.

Am I missing something ? Can you guide me to perform sync for multiple users?

![image](https://user-images.githubusercontent.com/59496152/139706835-e726e91d-801a-4dcb-84e4-699d774e2e91.png)

**Comment by Mimetis** [comment]
Can you share your sync client code ?
Did you try with a Reinitialize mode ?
Can you share the server setup code ?

**Comment by SheltonAlves** [comment]
Thank you @Mimetis  for the replying , I have attached both Client-side and Server side sync code.

I tried adding Reinitialize and also Reinitialize with Upload ,Since my sync process works in background(triggers every 1 minute) if new changes made on client side simultaneously when sync is running in background newly added changes during sync were lost after sync process is completed.

For eg : If userA added Record 'X' on local sqlite DB and synchronization started in background and at same time when sync process is in execution User adds one more Record 'Y' after sync is completed only 'X' record is synced and Record 'Y' which was added during sync process gets deleted from LocalDB(sqlite) when syncing type is set to Reiniatize as it clears all data from Client Db and downloads again from server.

[ClientSide.zip](https://github.com/Mimetis/Dotmim.Sync/files/7458036/ClientSide.zip)
[ServerSide.zip](https://github.com/Mimetis/Dotmim.Sync/files/7458038/ServerSide.zip)

The attached code works fine with single client but fails with multiple clients.

**Comment by Mimetis** [comment]
Your code seems pretty legit.
Now I need a really simple database schema to be able to reproduce the error

**Comment by Mimetis** [comment]
I see that you are using the AddCustomWhere special function.
Please review the documentation about it, and the tombstone behavior : https://dotmimsync.readthedocs.io/Filters.html#the-addcustomwhere-method

I'm not sure it's the problem you have here, but it's definitively something that must be fixed in your code:

``` cs
custFilter.AddParameter("VesselID", "table3", true);
custFilter.AddCustomWhere("VesselID = @VesselID OR Global=2 OR side.sync_row_is_tombstone = 1");

```

**Comment by SheltonAlves** [comment]
I tried adding "side.sync_row_is_tombstone = 1" filter to my customwhere condition but got same error.
I also removed customwhere filter  to check if it resolves the issue, but faced same error with multiple clients.

Error : When multiple clients use syncing , their records gets synced to server but individual client does not fetch records added by other client with sync type as Normal.

eg: If clientA adds record 'P'(sqlite DB) and clientB adds record 'Q'(sqlite DB) after sync I get both 'P' and 'Q' records on server(SQL server),but ClientA does not get record 'Q' added by clientB and vice versa. Am I missing something?

If I use sync type as Reinitialize both clients can see each other records but If client adds record at exact same time when background sync is in execution the record added which is not synced yet gets cleared when sync process completes with Reinitialize.

Since my sync process is triggered after every 1 minute do I have to call the DeprovisionAsync and ProvisionAsync methods after every sync on client-side??

**Comment by Mimetis** [comment]
> Since my sync process is triggered after every 1 minute do I have to call the DeprovisionAsync and ProvisionAsync methods after every sync on client-side??

No, this method is to be called for exceptionals reasons, like migrations, failure and so on..

**Comment by Mimetis** [comment]
Can you try with only one table, and see if it still failing (use the table with the filter)

**Comment by vunder** [comment]
Some assumption about this issue. I had similar problem. It happened because I made initial sync on one device and then put a copy of client's database on other device. As a result - sync process dors not give expected result
What I've done is made sync over empty database on other client to make sync work as expected

**Comment by SheltonAlves** [comment]
Thankyou @vunder  and @Mimetis  for replying
It was the same problem as you mentioned @vunder , I was initializing clientDB on single client system and was distributing the same DB for all clients.
After I started reinitializing each client DB on every single client system syncing worked as expected.
Thank you :)

**Comment by Mimetis** [comment]
Ah, good catch @vunder !
Indeed, if you are copying the same client database, after a first successful sync, you will have the same client identifier in the metadata table...
