### ISSUE TITLE
Dotmim.Sync.SyncException: 'Cannot drop type 'Global.FirePermit_BulkType' because it is being referenced by object 'FirePermit_bulkinsert'. There may be other objects that reference this type.'

### ISSUE THREAD

**Issue by haolityler** [Mimetis/Dotmim.Sync#629]
Here is my code. I am getting an exception.  It doesn't make any sense to me. Sounds like it is trying to drop a column in server database. All I want is download changes from the server.

            var serverProvider = new SqlSyncProvider(serverConnectionString);
            // Sqlite Client provider acting as the "client"
            var clientProvider = new SqliteSyncProvider(clientConnectionString);
            // Setup and options define the tables and some useful options.
            var setup = new SyncSetup(new string[] { "dbo.ErrorLog", "Global.FirePermit" });
            setup.TrackingTablesSuffix = "_tracking";
            setup.TriggersSuffix = "_trigger";
            var options = new SyncOptions();
            setup.Tables["Global.FirePermit"].SyncDirection = SyncDirection.DownloadOnly;
            setup.Tables["dbo.ErrorLog"].SyncDirection = SyncDirection.DownloadOnly;
            options.UseBulkOperations = false;
            // Define a local orchestrator, using the Sqlite provider
            // and a remote orchestrator, using the MySql provider.
            var localOrchestrator = new LocalOrchestrator(clientProvider, options, setup);
            var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);
            // Create the agent with existing orchestrators
            var agent = new SyncAgent(localOrchestrator, remoteOrchestrator);
            // Launch the sync
            var result = await agent.SynchronizeAsync();

**Comment by Mimetis** [comment]
You have probably made some tests, with differents tables.
The best solution is to 
- Restart with a fresh database with no sync metadatas
- Drop all the sync metadatas generated like stored proc, triggers, TVP type, tracking tables and the sync tables

**Comment by haolityler** [comment]
> You have probably made some tests, with differents tables. The best solution is to
> 
> * Restart with a fresh database with no sync metadatas
> * Drop all the sync metadatas generated like stored proc, triggers, TVP type, tracking tables and the sync tables

I tried delete the db3 file and restart the app. The error still occurs. Where are those metatdatas? On the server or one the client.

**Comment by Mimetis** [comment]
on both.
For testing purpose, droping the client db is a good test (that way you are sure everything will be recreated)
On server, you need to remove manually:
- Stored Procedures generated
- Triggers generated
- Table Value Parameter Types generated
- Tracking tables generated
- scope_ tables generated

My advice would be to start with a server database with nothing related to DMS in it (start with a backup, before any sync, maybe)

**Comment by Mimetis** [comment]
Are you using a fresh server database (like the schema you are using ?) without any sync metadata ?

Does it work with a simple application console ? (using [HelloSync](https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/HelloSync) for example)

What are your settings ? collation ? language ? numeric format ? encoding ?
