### ISSUE TITLE
Transaction (Process ID 54) was deadlocked

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#630]
We're getting this error from 1 customer. Most of their machines sync happily but two of their machines are unable to sync.

`Dotmim.Sync.Web.Client.HttpSyncWebException: Transaction (Process ID 54) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. The data for table-valued parameter "@changeTable" doesn't conform to the table type of the parameter. SQL Server error is: 1205, state: 56 The statement has been terminated. ----------------------- at Dotmim.Sync.BaseOrchestrator.RaiseError(Exception exception) at Dotmim.Sync.RemoteOrchestrator.ApplyThenGetChangesAsync(ScopeInfo clientScope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress1 progress) at Dotmim.Sync.RemoteOrchestrator.ApplyThenGetChangesAsync(ScopeInfo clientScope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress1 progress) at Dotmim.Sync.Web.Server.WebServerOrchestrator.ApplyThenGetChangesAsync2(HttpContext httpContext, HttpMessageSendChangesRequest httpMessage, SessionCache sessionCache, Int32 clientBatchSize, CancellationToken cancellationToken, IProgress1 progress) at Dotmim.Sync.Web.Server.WebServerOrchestrator.HandleRequestAsync(HttpContext httpContext, Action1 action, CancellationToken cancellationToken, IProgress1 progress) ----------------------- ----------------------- INNER EXCEPTION ----------------------- Transaction (Process ID 54) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. The data for table-valued parameter "@changeTable" doesn't conform to the table type of the parameter. SQL Server error is: 1205, state: 56 The statement has been terminated. ----------------------- at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task1 result) at System.Threading.Tasks.ContinuationResultTaskFromResultTask2.InnerInvoke() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location where exception was thrown --- at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) --- End of stack trace from previous location where exception was thrown --- at Dotmim.Sync.SqlServer.Builders.SqlSyncAdapter.ExecuteBatchCommandAsync(DbCommand cmd, Guid senderScopeId, IEnumerable1 applyRows, SyncTable schemaChangesTable, SyncTable failedRows, Nullable1 lastTimestamp, DbConnection connection, DbTransaction transaction) at Dotmim.Sync.BaseOrchestrator.InternalApplyChangesBatchAsync(SyncContext context, Boolean useBulkOperation, SyncTable changesTable, MessageApplyChanges message, DataRowState applyType, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken) at Dotmim.Sync.BaseOrchestrator.InternalApplyTableChangesAsync(SyncContext context, SyncTable schemaTable, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, DataRowState applyType, DatabaseChangesApplied changesApplied, CancellationToken cancellationToken, IProgress1 progress) at Dotmim.Sync.BaseOrchestrator.InternalApplyChangesAsync(SyncContext context, MessageApplyChanges message, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress1 progress) at Dotmim.Sync.RemoteOrchestrator.ApplyThenGetChangesAsync(ScopeInfo clientScope, BatchInfo clientBatchInfo, CancellationToken cancellationToken, IProgress1 progress) -----------------------
`

Sync options set on client and server:
```
BatchSize=1000;
DisableConstraintsOnApplyChanges=false; // to avoid table locks
UseBulkOperations = true;
```

Is this saying multiple processes are competing for a table lock? Shouldn't `DisableConstraintsOnApplyChanges=false` prevent that?

The user uninstalled and reinstalled our app but these two machines return this error.

Would it help to make the batch size smaller?

Any thoughts on how we might deal with this issue?

**Comment by Mimetis** [comment]
> Is this saying multiple processes are competing for a table lock? Shouldn't DisableConstraintsOnApplyChanges=false prevent that?
Nop

> Would it help to make the batch size smaller?
Nop

> Any thoughts on how we might deal with this issue?
Does it work when you are doing nothing, except the sync ? 
I mean, no workload on the database, except the sync process itself ?

**Comment by VagueGit** [comment]
The server is only used for sync, so there are no other operations.

We are using `DMS 0.8.1-beta-0687` and SQL Server Change Tracking

**Comment by VagueGit** [comment]
This morning the user reported all machines at that site no longer sync. We now have hundreds of instances of the same error from that site in our logs.

**Comment by Mimetis** [comment]
My questions was related to the client application, not the server.
Is the client application does something else on the local database when you are launching a sync process ?

**Comment by Mimetis** [comment]
The error you are mentioning, is it coming from the client or from the server ?

**Comment by VagueGit** [comment]
The error is from the server. We use SQLite on the client. So I guess it doesn't matter if other work is happening on the SQLite database at the time?

**Comment by Mimetis** [comment]
Indeed, seems you have a problem on the server.

I don't understand this error : `the data for table-valued parameter "@changeTable" doesn't conform to the table type of the parameter.`

Do you have a different schema from the client and the server ? 
I mean, it seems that for one table you don't have the same schema on the client and on the server.

**Comment by VagueGit** [comment]
The schema is the same on client and server. We have 300 of our companies now using DMS in this app. Only one site of one company has this issue. Each site has it's own database.

I tried syncing their database. Sync ran for an hour without throwing any exceptions, but no data was synced.

**Comment by VagueGit** [comment]
I'll setup logging on the client and report back here.

**Comment by VagueGit** [comment]
The app allowed simultaneous syncs. Thanks for the hint to help me find that. I've added a semaphore to sync.

**Comment by Mimetis** [comment]
Thanks.
There is a lock in the `DMS` to not allow simultaneous sync on the client, but it seems it did not work properly.

Looking at the code, the lock is working when you are trying to do a simultaneous sync on the same instance of a `SyncAgent`
But it won't raise an error if you are making several instances.

Not sure how I can handle this, but I will try to look into it !

**Comment by VagueGit** [comment]
Yes we create a new sync agent for each sync so before the agent syncs, it now checks IsSyncing
