### ISSUE TITLE
Schema does not exists yet

### ISSUE THREAD

**Issue by yarmenteros** [Mimetis/Dotmim.Sync#636]
Hi,

Thank you for your work.

I'm trying to run the _HelloWebSync_ to sync one table wth  example but I getting the below error:

**Schema does not exists yet in your remote database. You must make a first sync with your server, to initialize everything required locally.**

I just copy/paste the example code and modify the following lines:
- Client: Connection String,
- Client: WebClientOrchestrator, url constructor parameter,
- Client: SyncAgent, scopeName constructor parameter,
- Server: Connection String from appsettings file,
- Server: Used a SyncSetup instance to define table and schema (none dbo) and columns (PK and varbinary),

`SyncSetup syncSetup = new()
{
  Tables = new()
  {
     new SetupTable("RecipeMethodContent", new string[] { "RecipeKey", "Method" }, "Culinary")
  }
};`

When I run the example, I can see that some triggers, tables and store procedures are created in both client and server databases.

this is what the client app says:

![image](https://user-images.githubusercontent.com/17187162/142364176-9234e8aa-9e11-43f4-95e6-5ef3a76fde31.png)

Do I missing something?

Thank you again.

**Comment by Mimetis** [comment]
Can you share the schema you are using for the table `RecipeMethodContent` ?

**Comment by yarmenteros** [comment]
**this is the script for my table:**

`CREATE TABLE [Culinary].[RecipeMethodContent](
	[RecipeKey] [uniqueidentifier] NOT NULL,
	[Method] [varbinary](max) NOT NULL,
	[SyncDate] [datetimeoffset](7) NULL,
	[RowVersion] [timestamp] NOT NULL,
 CONSTRAINT [PK_ICS.RecipeMethodContent] PRIMARY KEY CLUSTERED 
(
	[RecipeKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [Culinary].[RecipeMethodContent] ADD  CONSTRAINT [DF_RecipeMethodContent_RecipeMethodContentKey]  DEFAULT (newid()) FOR [RecipeKey]
GO`

**Comment by yarmenteros** [comment]
The difference is, at the server side used the '**SqlSyncChangeTrackingProvider**'
`services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString, syncSetup, options);`

Do yo u think it could be the issue?

**Comment by yarmenteros** [comment]
Weird, I used the same code with a new/clean DB and it worked. Thank you.
