### ISSUE TITLE
NullReferenceException at Migration.Compare()

### ISSUE THREAD

**Issue by yarmenteros** [Mimetis/Dotmim.Sync#639]
Hi,

I setted up a WebServerOrchestrator object with a SyncDirection = UploadOnly, and after I changed it to DownloadOnly I'm receiving a NullReferenceException inside the Migration.Compare methd, line 191

**at Dotmim.Sync.Migration.Compare() in /home/vsts/work/1/s/Projects/Dotmim.Sync.Core/Setup/SetupMigration.cs:line 191
at Dotmim.Sync.BaseOrchestrator.<InternalMigrationAsync>d__80.MoveNext() in /home/vsts/work/1/s/Projects/Dotmim.Sync.Core/Orchestrators/BaseOrchestrator.Migration.cs:line 34
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()**

![image](https://user-images.githubusercontent.com/17187162/142808116-47b6e8a1-1073-46f4-929b-2ab2c8c2a8e6.png)

![image](https://user-images.githubusercontent.com/17187162/142808316-db0d11a1-fb26-440a-bb32-7aeefbd199c7.png)

![image](https://user-images.githubusercontent.com/17187162/142808389-d16572a5-9ef3-4d29-93a9-5a702f34e13f.png)

It's weird because at that line only the MigrationSetupTable constructor is called with the newTable as parameter.

Any clue?
Thank you so much.

**Comment by Mimetis** [comment]
Here is a quick I've made and everything runs just fine:

``` cs
// Create 2 Sql Sync providers
var serverProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(serverDbName));
var clientProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(clientDbName));

var options = new SyncOptions {};

// Using the Progress pattern to handle progession during the synchronization
var progress = new SynchronousProgress<ProgressArgs>(s =>
{
    Console.ForegroundColor = ConsoleColor.Green;
    Console.WriteLine($"{s.ProgressPercentage:p}:\t{s.Source}:\t{s.Message}");
    Console.ResetColor();
});

try
{
    var setup = new SyncSetup(oneTable);

    // First test : Bidirectional
    var agent = new SyncAgent(clientProvider, serverProvider, options, setup);
    
    var s = await agent.SynchronizeAsync();
    Console.WriteLine(s);

    // Second test : UploadOnly
    setup.Tables[0].SyncDirection = SyncDirection.UploadOnly;
    s = await agent.SynchronizeAsync();
    Console.WriteLine(s);

    // Third test : UploadOnly
    setup.Tables[0].SyncDirection = SyncDirection.DownloadOnly;
    s = await agent.SynchronizeAsync();
    Console.WriteLine(s);

}
catch (SyncException e)
{
    Console.WriteLine(e.ToString());
}
catch (Exception e)
{
    Console.WriteLine("UNKNOW EXCEPTION : " + e.Message);
}
Console.WriteLine("Sync Ended. Press a key to start again, or Escapte to end");

```

Do you see something different in your case ?

**Comment by yarmenteros** [comment]
I'm using `WebServerOrchestrator`, and the issue happens if any change is detected in the setup, not only setting the `SyncDirection` value.

**Comment by Mimetis** [comment]
Can you make a simple repro project ? (maybe using the [Xamarin Sample](https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/XamAppSync) as a base project)
