### ISSUE TITLE
Cannot sync association table with just PKs

### ISSUE THREAD

**Issue by gb0o** [Mimetis/Dotmim.Sync#64]
Hi @Mimetis, 

I get an exception when attempting to sync an association or join table that defines a many-to-many relationship between two other tables. DotMim.Sync expects the association table to contain at least one column that is not a PK. The problem is an association table typically contains just two PKs.

When I sync with the below setup I get exception:

`NotSupportedException("PostTag does not contains any columns, excepting primary keys.")` 

I could create a superfluous column in the association table to keep Dotmim.Sync happy but that would be bad. It would be better to permit just syncing of PK data without the requirement of at least one non PK column.  

Hope it is easy to fix.

Database setup in SSMS
```
CREATE DATABASE [PostTag]
GO

USE [PostTag]
GO

CREATE TABLE [dbo].[Posts](
	[PostId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NULL,
	CONSTRAINT [PK_Posts] PRIMARY KEY CLUSTERED ([PostId] ASC) ON [PRIMARY]
)
GO

CREATE TABLE [dbo].[Tags](
	[TagId] [int] IDENTITY(1,1) NOT NULL,
	[Text] [nvarchar](max) NULL,
        CONSTRAINT [PK_Tags] PRIMARY KEY CLUSTERED ([TagId] ASC) ON [PRIMARY]
)
GO

CREATE TABLE [dbo].[PostTag](
	[PostId] [int] NOT NULL,
	[TagId] [int] NOT NULL,
	CONSTRAINT [PK_PostTag] PRIMARY KEY CLUSTERED ([PostId] ASC, [TagId] ASC) ON [PRIMARY]
)
GO

USE [PostTag]
SET IDENTITY_INSERT [dbo].[Posts] ON 
INSERT [dbo].[Posts] ([PostId], [Title]) VALUES (1, N'Best Boutiques on the Eastside')
INSERT [dbo].[Posts] ([PostId], [Title]) VALUES (2, N'Avoiding over-priced Hipster joints')
INSERT [dbo].[Posts] ([PostId], [Title]) VALUES (3, N'Where to buy Mars Bars')
SET IDENTITY_INSERT [dbo].[Posts] OFF
SET IDENTITY_INSERT [dbo].[Tags] ON 
INSERT [dbo].[Tags] ([TagId], [Text]) VALUES (1, N'Golden')
INSERT [dbo].[Tags] ([TagId], [Text]) VALUES (2, N'Pineapple')
INSERT [dbo].[Tags] ([TagId], [Text]) VALUES (3, N'Girlscout')
INSERT [dbo].[Tags] ([TagId], [Text]) VALUES (4, N'Cookies')
SET IDENTITY_INSERT [dbo].[Tags] OFF
INSERT [dbo].[PostTag] ([PostId], [TagId]) VALUES (1, 1)
INSERT [dbo].[PostTag] ([PostId], [TagId]) VALUES (3, 1)
INSERT [dbo].[PostTag] ([PostId], [TagId]) VALUES (1, 2)
INSERT [dbo].[PostTag] ([PostId], [TagId]) VALUES (3, 2)
INSERT [dbo].[PostTag] ([PostId], [TagId]) VALUES (2, 3)
INSERT [dbo].[PostTag] ([PostId], [TagId]) VALUES (3, 3)
INSERT [dbo].[PostTag] ([PostId], [TagId]) VALUES (2, 4)
INSERT [dbo].[PostTag] ([PostId], [TagId]) VALUES (3, 4)
GO
```
See https://blog.oneunicorn.com/2017/09/25/many-to-many-relationships-in-ef-core-2-0-part-1-the-basics/ for a code first setup.

The exception is generated in CoreProvider.Schema.ValidateTableFromColumns here:
```
if (columnsNotPkeys <= 0)
    throw new NotSupportedException($"{dmTable.TableName} does not contains any columns, excepting primary keys.");
```

**Comment by Mimetis** [comment]
Yes, indeed, the `Dotmim.Sync` can't handle those kind of tables, because we can't generate the Update triggers and Update stored procedure.
For now, an easy fix is to add a new "not used" column, like an auto generated date column.

I'm not sure to be able to fix this issue, but will look into it, quickly.

Thx @gb0o !

**Comment by Mimetis** [comment]
Ok it seems the issue is quite simple to resolve !!
Eventually, I just have to remove the `Update trigger` and the `Update stored procedure`, to make it work correctly.

@gb0o Can you can test the fix within the current master branch ?

I will make a new update on the nuget packages in the next couple of weeks.

You can have a look on this test file (I took your sample to make the tests :) )  [OneFiedTest](https://github.com/Mimetis/Dotmim.Sync/blob/master/Tests/Dotmim.Sync.Tests/SyncOneTableOneFieldTests.cs)

Let me know if it's working correctly for you.

Seb

**Comment by gb0o** [comment]
Hi @Mimetis, Thank you for the very fast fix.

Confirmed I can now sync the PostTag association table above successfully.

Here are contents of the PostTag table after syncing

![image](https://user-images.githubusercontent.com/39327472/42923948-6a7ff1ac-8b6b-11e8-9ffe-42124deddb1b.png)

Great work.

**Comment by gb0o** [comment]
I also checked Post and Tag rows are correct from both directions after loading using EF. The database was Sqlite.

![image](https://user-images.githubusercontent.com/39327472/42925314-26cee5de-8b71-11e8-925d-c7a8ccff9193.png)

![image](https://user-images.githubusercontent.com/39327472/42925347-40f59aac-8b71-11e8-80cd-d3894d02fa1d.png)
