### ISSUE TITLE
Just changed some column names and can't sync anymore (Unknown Column 'base.mycolumn' in 'field list')

### ISSUE THREAD

**Issue by wTechnoo** [Mimetis/Dotmim.Sync#640]
Using MYSQL on a web API and syncing SQLite with it.
Doesn't matter what I do, tried deleting the local SQLite table, synchronizing normally, synchronizing reinitializing, deleting MYSQL tracking tables and triggers and I'm still getting unknown column name base.mycolumnname

**Comment by Vextamour** [comment]
You need to deprovision and reprovision your server database. I created a deprovision and provision API call for when I make database changes on the server. You'll also need to do this for the client local file in the future as well.

**Comment by wTechnoo** [comment]
So I need to deprovision and provision on my WEB and LOCAL right? Do you have any starting point on how to make that WEB API so I can call it through code? I have no experience with WEB/HTTP stuff, I would have to modify and rebuild my ASP.net code everytime I change something on my table

**Comment by Vextamour** [comment]
//https://dotmimsync.readthedocs.io/Provision.html#deprovision
        [Route("[action]")]
        [HttpGet]
        [Authorize]
        public async Task<string> DeprovisionServerDatabase()
        {            
            var serverDBConnectionString = Configuration.GetConnectionString("EndCapDbConnectionString");
            // Create server provider
            var serverProvider = new SqlSyncProvider(serverDBConnectionString);

            // Create standard Setup and Options
            var setup = new SyncSetup(Configuration["DBServerSyncTables:TableList"].Split(',').ToArray());
            var options = new SyncOptions();

            // Create a server orchestrator used to Deprovision everything on the server side
            var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);

            // Deprovision everything
            await remoteOrchestrator.DeprovisionAsync();

            return "Server database successfully deprovisioned";
        }

        //https://dotmimsync.readthedocs.io/Provision.html#provision
        [Route("[action]")]
        [HttpGet]
        [Authorize]
        public async Task<string> ProvisionServerDatabase()
        {
            var serverDBConnectionString = Configuration.GetConnectionString("EndCapDbConnectionString");
            var serverProvider = new SqlSyncProvider(serverDBConnectionString);

            // Create standard Setup and Options
            var setup = new SyncSetup(Configuration["DBServerSyncTables:TableList"].Split(',').ToArray());
            var options = new SyncOptions();

            // -----------------------------------------------------------------
            // Server side
            // `-----------------------------------------------------------------`

            // This method is useful if you want to provision by yourself the server database
            // You will need to :
            // - Create a remote orchestrator with the correct setup to create
            // - Provision everything

            // Create a server orchestrator used to Deprovision and Provision only table Address
            var remoteOrchestrator = new RemoteOrchestrator(serverProvider, options, setup);

            // Provision everything needed (sp, triggers, tracking tables)
            // Internally provision will fectch the schema a will return it to the caller.
            var newSchema = await remoteOrchestrator.ProvisionAsync();

            return "Server database successfully provisioned";
        }

**Comment by wTechnoo** [comment]
Man, thank you so much, helped alot.
