### ISSUE TITLE
Dotmim.Sync.SyncException: Error reading JObject from JsonReader

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#647]
This is appearing in our logs from time to time.
`Dotmim.Sync.SyncException: Error reading JObject from JsonReader. Path '', line 0, position 0.`

Once this appears for a user, it reappears repeatedly. The full strack trace
```
Dotmim.Sync.SyncAgent.<>c__DisplayClass53_0
<<SynchronizeAsync>b__0>d.MoveNext$catch$1 ()
System.Runtime.ExceptionServices
ExceptionDispatchInfo.Throw ()
System.Runtime.CompilerServices
TaskAwaiter.ThrowForNonSuccess (Task)
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task)
System.Runtime.CompilerServices
TaskAwaiter.ValidateEnd (Task)
System.Runtime.CompilerServices
TaskAwaiter.GetResult ()
Dotmim.Sync.SyncAgent
<SynchronizeAsync>d__53.MoveNext ()
System.Runtime.ExceptionServices
ExceptionDispatchInfo.Throw ()
System.Runtime.CompilerServices
TaskAwaiter.ThrowForNonSuccess (Task)
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task)
System.Runtime.CompilerServices
TaskAwaiter.ValidateEnd (Task)
Wbl.Services.DataService
<SyncAsync>d__44.MoveNext ()
```
We've had a report from one company impacted with this issue, that their machines have not been able to sync to each other for a few days. All their data appears to have synced to the server, but we can't be sure.

Should we handle this exception in some way other than just logging it?

We have on the client
```
Dotmim.Sync.Sqlite 0.9.1
Dotmim.Sync.Web.Client 0.9.1
```
on the server
```
Dotmim.Sync.SqlServer.ChangeTracking 0.9.1
Dotmim.Sync.Web.Server 0.9.1
```

**Comment by Mimetis** [comment]
Hard to debug ...
Is it something you can reproduce ?

**Comment by VagueGit** [comment]
I wish I could reproduce. We have a few hundred companies (~1000 users) syncing to their server databases with DMS. This issue is currently striking 20 users.

Would it be ok to delete the batches folder when this arises? It might clear the way for a further syncs.

**Comment by VagueGit** [comment]
We now have ~100 users impacted by this issue so I have published an update which deletes the batches folder when this issue arises.

**Comment by Mimetis** [comment]
When batches are deleted, the issue does not appears anymore ?

**Comment by VagueGit** [comment]
We had one company upgrade over the weekend. They reported yesterday (Sunday) that all machines were now syncing. Will know more when other companies open for business this week, but I'm hopeful.

**Comment by Mimetis** [comment]
let me know :)

**Comment by VagueGit** [comment]
It looks like this has worked. However we still see thousands of instances of this exception across a hundred or so users who don't have the upgrade yet.

Those users are now outside the SQL Server change tracking retention period, 14 days. Will this cause their local data to be deleted when their local database is reinitialised?

**Comment by VagueGit** [comment]
If I change the retention period on the server to 90 days, will this allow clients whose last sync is outside the current retention period to sync?

**Comment by Mimetis** [comment]
> If I change the retention period on the server to 90 days, will this allow clients whose last sync is outside the current retention period to sync?

Not for the clients already out of date.
For all the others, yes

**Comment by VagueGit** [comment]
Apologies; I'm struggling to understand. I've changed the SQL Server retention period to 60 days for each company database. Those companies that were out of date when the retention period was 14 days, still have local data, but have not been able to sync due to this issue.

When they get the version that allows them to sync, they will be within the new 60 days retention period. For those companies, how will DMS handle data that has not been synced for more than 14 days but less than 60 days?
