### ISSUE TITLE
Custom Serializer fails in UWP Store App

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#648]
I've incorporated MessagePack as a custom serializer for DMS in our web api and UWP client app, pretty much a copy and paste from the DMS docs.

It works brilliantly on my dev machine but when published to the Micro$ Store DMS throws 
`Dotmim.Sync.SyncException: Dynamic code generation is not supported on this platform`

I assume that is a WinRT limitation. Does anyone have any advice on how to incorporate MessagePack as a custom serializer for DMS in a WinRT app? A simple can't be done might save save pain for others striking this issue.

**Comment by vunder** [comment]
Check types in `Defauld.rd.xml`
Try to add your serializable type the like this
```xml
    <Type Name="Full_Type_Name_Here" XmlSerializer="Required All" Dynamic="Required All" />
```

**Comment by VagueGit** [comment]
Thanks for that @vunder . Do you know if that works when published through the Micro$ Store?

**Comment by vunder** [comment]
It should. At some point it worked for me.
I recommend you first try it locally on Release build

**Comment by VagueGit** [comment]
Thanks but Release build will only run without .Net Native Tool Chain so is not comparable to a Store build. We've been burned before 😉 

We might have to wait until our customers disappear for their xmas break before we give it a go. Thanks for your help @vunder

**Comment by vunder** [comment]
@VagueGit you can try to create "flight submission" with a few emails of some testers to check changes

**Comment by VagueGit** [comment]
Thanks again for the suggestion @vunder but the app syncs through a web api and so the api must also have MessagePack which will break the app in prod (the api isn't versioned). 

In dev the app talks to localhost; the thought of configuring a store app to talk to localhost sends me into a swoon.

**Comment by vunder** [comment]
What stops you from changing sync address for that flight
