### ISSUE TITLE
EnsureVersion is failing

### ISSUE THREAD

**Issue by champcbg** [Mimetis/Dotmim.Sync#649]
I am getting this error when attempting to sync 

**Version string portion was too short or too long.
Parameter name: input**

here is the stack trace

```
System.ArgumentException: Version string portion was too short or too long.
Parameter name: input
  File "/Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Version.cs", line 331, col 37, in Version Version.ParseVersion(ReadOnlySpan<char> input, bool throwOnFailure)
  File "/Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Version.cs", line 305, col 13, in Version Version.Parse(string input)
  File "/Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Version.cs", line 80, col 13, in new Version(string version)
  ?, in Version SyncVersion.EnsureVersion(string v)
  ?, in bool LocalOrchestrator.InternalNeedsToUpgrade(ScopeInfo scopeInfo)
  ?, in async Task<SyncResult> SyncAgent.SynchronizeAsync(SyncType syncType, CancellationToken cancellationToken, IProgress<ProgressArgs> progress)+(?) => { }
```

I have been able to debug to this line of code

`public static Version EnsureVersion(string v) => v == "1" ? new Version(0, 5, 7) : new Version(v);`

the value of **V="20"** which is coming from **dbo.scope_info_server.sync_scope_version**

![image](https://user-images.githubusercontent.com/4595766/143770683-f8b1a49e-03c2-4718-b3bd-ba6b8af5f636.png)

**Comment by Mimetis** [comment]
That's not a normal value for a version.
Did you changed it manually ?
Version should correspond to the version of `DMS` (like `0.9.0` or `0.9.1`)
Try to update to the same version you are using, and see if it's resolving your issue

**Comment by champcbg** [comment]
In my process for for doing a Deprovision and Provision, during Provision i have this code

`serverScope.Version = (Convert.ToInt32(serverScope.Version) + 1).ToString();`

Didnt realize it was being used for version validation.  I have had this code in place for a long time.

Would it be best to force deprovision and provision and see if it updates that version automatically?

**Comment by Mimetis** [comment]
Nop
You can force the version to the current version you are using
Then make a deprovision and provision, if you can

**Comment by champcbg** [comment]
I manually set the server to 0.9.1 and then added logic to deprovision and provision when this error comes in.
