### ISSUE TITLE
Delete ruins Synchronization

### ISSUE THREAD

**Issue by JiriOgurek** [Mimetis/Dotmim.Sync#654]
I am using UploadOnly sync of several related tables (using identity ID in root parent table) from client to server only. Everything works fine unless I delete some records at the client, see my repro scenario.

`1. Both client and server brand new DBs created.`
`2. Insert #1 4.072 records`
`3. Synchro #1 - uploaded 0 records` <-- strange - changes tracking is ON since creation, but OK, may be init required
`4. Delete of insert #1.`
`5. Insert #2 3.950 records.`
`6. Synchro #2 - uploaded 8.022 records` <-- Error, uploads ALL even previously deleted records!

This is my source code:
```
var serverProvider = new SqlSyncChangeTrackingProvider(builder.ConnectionString);
var clientProvider = new SqlSyncChangeTrackingProvider(new Microsoft.Data.SqlClient.SqlConnectionStringBuilder(_currentConnectionString) {ConnectTimeout = 0}.ConnectionString);

var tables = new[] { "Measurements", ...};

var syncSetup = new SyncSetup(tables);
foreach (var table in syncSetup.Tables)
    table.SyncDirection = SyncDirection.UploadOnly;

var agent = new SyncAgent(clientProvider, serverProvider, syncSetup);

var progress = new SynchronousProgress<ProgressArgs>(args => progressBarControl.Position = (int)Math.Round(args.ProgressPercentage * 100);

agent.LocalOrchestrator.OnTableChangesSelected(args =>
{
    if (args.Changes is not { HasRows: true })
        return;

    foreach (var changedRow in args.Changes.Rows.ToArray())
    {
        if (changedRow.RowState == DataRowState.Deleted)
            args.Changes.Rows.Remove(changedRow);
    }
});

result = await agent.SynchronizeAsync(progress);
```

Thank you for your kind help. Edit: scenario simplified.

**Comment by JiriOgurek** [comment]
I've got hypotesis - synchronization works fine may be,  only Uploaded count contains all deletes as well since last synchronization. If so, only one problem remains, why (after delete) synchronization process takes so long, what's going on there?

**Comment by Mimetis** [comment]
Can you provide a simple walkthrough code ?

**Comment by JiriOgurek** [comment]
Sure, yes, I can. What walkthrough do you mean?

**Comment by Mimetis** [comment]
Yes, sure. Here are some examples of walkthrough I used to debug and help people.
Doing something that way will allow me to reproduce the error, and then will help me debug it:

- https://github.com/Mimetis/Dotmim.Sync/issues/636#issuecomment-973100192
- https://github.com/Mimetis/Dotmim.Sync/issues/637#issuecomment-974293971
- https://github.com/Mimetis/Dotmim.Sync/issues/622#issuecomment-971931834
- https://github.com/Mimetis/Dotmim.Sync/issues/616#issuecomment-922385639

**Comment by JiriOgurek** [comment]
It's not easy to setup repro environment, what about live remote session using TeamViewer, please?

In the mean time, I've focused the hot spot in the profiler, it seems to be this:
![image](https://user-images.githubusercontent.com/49657334/146003211-044c075d-3b16-483c-8cc8-82996f045689.png)

This method CreateSyncRowFromReader is performed 131.167 times, so clearly it's executed even for previously deleted records (there are only new 10.000 inserted records to be uploaded, 120.000+ records are deletes) so my first question is: can we avoid processing deletes this way to speed it up?

And the assignement at line 420 is very slow (due to unoptimized Equals and EqualsByProperties), so my second question is can we make it efficient, please? BTW this would optimize Remove method as well...

**Comment by Mimetis** [comment]
> This method CreateSyncRowFromReader is performed 131.167 times, so clearly it's executed even for previously deleted records (there are only new 10.000 inserted records to be uploaded, 120.000+ records are deletes) so my first question is: can we avoid processing deletes this way to speed it up?

All the rows processed are rows that should be synced.
Look at the stored procedure `[TABLE]_changes` to see how **DMS** is retrieving rows to sync

> And the assignement at line 420 is very slow (due to unoptimized Equals and EqualsByProperties), so my second question is can we make it efficient, please? BTW this would optimize Remove method as well...

It has been greatly improved in the next version (`v0.9.3`)

**Comment by JiriOgurek** [comment]
> All the rows processed are rows that should be synced.

Deleted records have been synced (uploaded) in the previous sync, this time are locally deleted only with no interest in syncing it to the server (deleting at the server). So can we avoid processing deletes this way?

> It has been greatly improved in the next version (`v0.9.3`)

Is it stable, so I can give it a try, please?

**Comment by Mimetis** [comment]
> Deleted records have been synced (uploaded) in the previous sync, this time are locally deleted only with no interest in syncing it to the server (deleting at the server). So can we avoid processing deletes this way?

Well if you have deleted locally some rows, you need to sync them to the server to be sure they are deleted also on the server, right ?

> Is it stable, so I can give it a try, please?

You can clone the master branch and makes some tests.
I will publish a pre release version on nuget later today

**Comment by JiriOgurek** [comment]
> I will publish a pre release version on nuget later today

Cool :-)

> Well if you have deleted locally some rows, you need to sync them to the server to be sure they are deleted also on the server, right ?

No, I don't need it, I want to delete it locally with no syncing. Can I do so?

**Comment by Mimetis** [comment]
> No, I don't need it, I want to delete it locally with no syncing. Can I do so?

Remove all lines from the tracking table (they are marked with `sync_row_is_tombstone` = 1 in tracking table)

**Comment by JiriOgurek** [comment]
> Remove all lines from the tracking table (they are marked with `sync_row_is_tombstone` = 1 in tracking table)

Would you be so kind and suggest how to do so, please?

**Comment by Mimetis** [comment]
`Delete From [TABLE]_tracking where sync_row_is_tombstone = 1`

**Comment by JiriOgurek** [comment]
I have no table like this, I am using Change Tracking of MS SQL Server.

**Comment by Mimetis** [comment]
We do not have control over change tracking mechanism

What you can do maybe is to Reinitialize the sync (calling SynchronizeAsync(SyncType.Reinitialize) to start from a fresh new client database

**Comment by JiriOgurek** [comment]
I am trying to evaluate beta v.0.9.3.0746, however a week ago you have replaced Changes argument with BatchPartInfo? Would you be so kind and suggest how to prevent server-side deletes with new argument, please?

This is old source code with Changes:

```
agent.LocalOrchestrator.OnTableChangesSelected(args =>
{
    if (args.Changes is not { HasRows: true })
        return;

    foreach (var changedRow in args.Changes.Rows.ToArray())
    {
        if (changedRow.RowState == DataRowState.Deleted)
            args.Changes.Rows.Remove(changedRow);
    }
});
```

**Comment by Mimetis** [comment]
Indeed. I've just published a new pre release with some improvements.

Here are some useful tips:

The first 3 events are raised, in order, when **selecting** rows from a table (on client or server):

``` cs
// This event is raised before selecting the changes for a particular table
// you still can change the DbCommand generated, if you need to
agent.RemoteOrchestrator.OnTableChangesSelecting(tcsa =>
{
    Console.WriteLine($"Table {tcsa.SchemaTable.GetFullName()}: " +
        $"Selecting rows from datasource {tcsa.Source}");
});

// This event is raised for each row read from the datasource.
// You can change the values of args.SyncRow if you need to.
// this row will be later serialized on disk
agent.RemoteOrchestrator.OnTableChangesSelectedSyncRow(args =>
{
    args.SyncRow["Name"] = $"D{args.SyncRow["Name"]}";
    Console.WriteLine(args.SyncRow);

});

// The table is read. The batch parts infos are generated and already available on disk
agent.RemoteOrchestrator.OnTableChangesSelected(tcsa =>
{
    Console.WriteLine($"Table {tcsa.SchemaTable.GetFullName()}: " +
        $"Files generated count:{tcsa.BatchPartInfos.Count()}." +
        $" Rows Count:{tcsa.TableChangesSelected.TotalChanges}");
});

```

These 3 others events are raised when applying rows:

``` cs
 // This event is raised when a table is applying some rows, available on the disk
 agent.LocalOrchestrator.OnTableChangesApplying(args =>
 {
     Console.WriteLine($"Table {args.SchemaTable.GetFullName()}: " +
         $"Applying changes from {args.BatchPartInfos.Count()} files. " +
         $"{args.BatchPartInfos.Sum(bpi => bpi.RowsCount)} rows.");
 });

 // This event is raised for each batch rows (maybe 1 or more in each batch)
 // that will be applied on the datasource
 // You can change something to the rows before they are applied here
 agent.LocalOrchestrator.OnTableChangesApplyingSyncRows(args =>
 {
     foreach (var syncRow in args.SyncRows)
         Console.Write(".");
 });

 // This event is raised once all rows for a table have been applied
 agent.LocalOrchestrator.OnTableChangesApplied(args =>
 {
     Console.WriteLine();
     Console.WriteLine($"Table applied: ");
 });

```

**Comment by JiriOgurek** [comment]
Thank you for your update and kind support. However no event is fired, what's wrong, please? And can you suggest how to get rid of delete changes using these events, please? First event - alter DbCommand to ignore deletes, what would you recommend, please?

**Comment by Mimetis** [comment]
I would do something like that:

``` cs
agent.LocalOrchestrator.OnTableChangesSelected(async tcsa =>
{
    foreach (var bpi in tcsa.BatchPartInfos)
    {
        var table = await tcsa.BatchInfo.LoadBatchPartInfoAsync(bpi);

        foreach (var row in table.Rows.ToArray())
        {
            if (row.RowState == DataRowState.Deleted)
            {
                table.Rows.Remove(row);
            }
        }

        await tcsa.BatchInfo.SaveBatchPartInfoAsync(bpi, table);
    }
});

```

**Comment by JiriOgurek** [comment]
This code is fired and delete rows get deleted, it's running faster now - 11 seconds in the past and 7 seconds now, anyway without deletes it takes 2 seconds only. Is there any source code available for this build 0749 so I can analyze it in profiler, please? Also after about six syncs I get exception: The MERGE statement conflicted with the FOREIGN key constraint, what's wrong, please?

**Comment by Mimetis** [comment]
>  The MERGE statement conflicted with the FOREIGN key constraint, what's wrong, please?

Try to use the options (on both side) `options.DisableConstraintsOnApplyChanges = true;`

> Is there any source code available for this build 0749

It's merged in the master branch

> so I can analyze it in profiler

Great ! If you found any issue, related to performance, please share it :)

**Comment by JiriOgurek** [comment]
Profiler complains about slow Remove method from generic list (SyncRows.cs, line 218), I would suggest HashSet, LinkedList or Dictionary structure instead. Also generic JsonSerializer is slow, it would the best to serialize manually: https://www.newtonsoft.com/json/help/html/Performance.htm#ManuallySerialize
