### ISSUE TITLE
Temporary batch files not removed after sync is completed

### ISSUE THREAD

**Issue by gb0o** [Mimetis/Dotmim.Sync#66]
I have been running Dotmim.Sync in batch mode using a .NET Core WebAPI backend and a WPF client.  The temporary files created on server are not removed from the server and accumulate with each sync. I can foresee this will be a problem in an operational context. I guess they could be easily removed at the end of a sync session.

I found the problem when my .NET Core API is deployed on Windows or Linux. Here are some temporary batch folders from 3 sync sessions in a Linux Docker container.

```
root@17935125588f:/tmp/DotmimSync# ls -la
total 20
drwxr-xr-x 5 root root 4096 Jul 26 06:30 .
drwxrwxrwt 3 root root 4096 Jul 26 05:59 ..
drwxr-xr-x 2 root root 4096 Jul 26 06:00 2018_07_26_00y1wyr5hoj5m
drwxr-xr-x 2 root root 4096 Jul 26 06:15 2018_07_26_390tkegtaod42
drwxr-xr-x 2 root root 4096 Jul 26 06:32 2018_07_26_44lpi32qbg42y
root@17935125588f:/tmp/DotmimSync# cd 2018_07_26_00y1wyr5hoj5m/
root@17935125588f:/tmp/DotmimSync/2018_07_26_00y1wyr5hoj5m# ls -la
total 91952
drwxr-xr-x 2 root root     4096 Jul 26 06:00 .
drwxr-xr-x 5 root root     4096 Jul 26 06:30 ..
-rw-r--r-- 1 root root  4722594 Jul 26 05:59 000_jfbnr1xw_cnm.batch
-rw-r--r-- 1 root root  3681241 Jul 26 05:59 001_jyypruil_ysb.batch
-rw-r--r-- 1 root root  3681241 Jul 26 05:59 002_1e0lwms0_ufi.batch
-rw-r--r-- 1 root root  3681241 Jul 26 05:59 003_45umefns_2bc.batch
-rw-r--r-- 1 root root 12760719 Jul 26 05:59 004_dappurlh_sam.batch
-rw-r--r-- 1 root root  4511765 Jul 26 05:59 005_gkc5pi1l_gtr.batch
-rw-r--r-- 1 root root  4506247 Jul 26 05:59 006_e5ro2spp_fkn.batch
-rw-r--r-- 1 root root  4506446 Jul 26 05:59 007_2bi4gt00_tmk.batch
-rw-r--r-- 1 root root  4524020 Jul 26 05:59 008_jb3of2yg_r05.batch
-rw-r--r-- 1 root root  4540813 Jul 26 05:59 009_lumfyat3_osz.batch
-rw-r--r-- 1 root root  4545502 Jul 26 05:59 010_cg4caqgh_ipp.batch
-rw-r--r-- 1 root root  4544673 Jul 26 05:59 011_4avuavkt_ezn.batch
-rw-r--r-- 1 root root  4553752 Jul 26 06:00 012_nvvt0lv0_ucz.batch
-rw-r--r-- 1 root root  4553271 Jul 26 06:00 013_i0elaeds_p4s.batch
-rw-r--r-- 1 root root  4560383 Jul 26 06:00 014_usxrd0gj_2x1.batch
-rw-r--r-- 1 root root  8367209 Jul 26 06:00 015_sfwfb11u_zmy.batch
-rw-r--r-- 1 root root  4700110 Jul 26 06:00 016_votahwim_ozv.batch
-rw-r--r-- 1 root root  4713215 Jul 26 06:00 017_t2cmov5v_f2a.batch
-rw-r--r-- 1 root root  2464614 Jul 26 06:00 018_sp2cciud_muy.batch
```

**Comment by Mimetis** [comment]
Hey @gb0o !
You're going to fast :)

Indeed, the temporaries folders are something I want to look into.   
In the same way, we can talk about the `tracking` tables that are never cleaned. (Especially when you have rows that are marked deleted and those rows are already deleted in all the synced databases)   

I have not think about any particular solutions to handle those two tasks.  
What do you think ?   
For you, how do you want to be able to delete those metadatas ?   
Apis ?
Notifications ?
Jobs ?

What kind of parameters do you need ?

**Comment by gb0o** [comment]
I don't think an API is needed to clean up. People could write their own clean up code by handling the end session event but I think it would better to clean up for everyone because this is more of an internal implementation detail. The clean up could be in `WebProxyServerProvider.EndSessionAsync` because it is guaranteed to be called by the `SyncAgent`.

This seems to work. 

```
        private async Task<HttpMessage> EndSessionAsync(HttpMessage httpMessage)
        {
            // call inner provider
            httpMessage.SyncContext = await this.EndSessionAsync(httpMessage.SyncContext);

            // delete temporary files
            var batchInfos = new[] {
                this.LocalProvider.CacheManager.GetValue<BatchInfo>("GetChangeBatch_BatchInfo"),
                this.LocalProvider.CacheManager.GetValue<BatchInfo>("ApplyChanges_BatchInfo") };

            foreach (var bi in batchInfos)
            {
                if (bi == null)
                {
                    continue;
                }

                var path = Path.Combine(this.Configuration.BatchDirectory, bi.Directory);
                if (Directory.Exists(path))
                {
                    foreach (var file in Directory.GetFiles(path))
                    {
                        File.Delete(file);
                    }
                    Directory.Delete(path);
                }
            }

            this.LocalProvider.CacheManager.Clear();
            return httpMessage;
        }
```
The idea is to get all `BatchInfo` objects from the `CacheManager` and delete the directories and temporary files. Also need to make sure the cache holds onto the `BatchInfo` objects and only removes these after directories are deleted. Might be better to clean up the cache in `WebProxyServerProvider.BeginSessionAsync`.

Tracking tables are an interesting case, specially deletions as you mention. It would be almost impossible to know whether a row has been deleted in all client databases and therefore you could never really remove a deletion tracking row. The server would have to have a list of known clients. If tracking tables needed to cleaned up for other reasons new enumerations could be added to `CoreProvider.Deprovision(string tables[], SyncProvision provision)`.

I will be writing an API command to drop all server tracking tables by calling `CoreProvider.Deprovision(tables, SyncProvision.TrackingTable)`. This is useful mainly for diagnostics and wouldn't expect a client to ever instigate it.

**Comment by gb0o** [comment]
Should mention the code example in my last comment is not complete. In batch mode temporary files are created on server and client side. The example only works for the server side. A better approach is obviously needed. Maybe a `BatchInfo` should be responsible for cleaning up its own temporary files?

**Comment by Mimetis** [comment]
Thx for the suggestions. Will look into it

**Comment by Mimetis** [comment]
It should be resolved with the latest version. 
Use the new `SyncConfiguration` property called `CleanMetadatas` to define if you want (or not) to clean the tmp metadatas folder.

Feel free to re-open the issue if it's not working correctly !

Seb
