### ISSUE TITLE
WindowsFormsClassic missing NuGet and cannot be located

### ISSUE THREAD

**Issue by spj-uk** [Mimetis/Dotmim.Sync#664]
I am trying the WindowsFormsClassic sample but I get the following error when building

Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\SQLitePCLRaw.lib.e_sqlite3.2.0.4\build\net461\SQLitePCLRaw.lib.e_sqlite3.targets.	WindowsFormsClassic	\Dotmim.Sync-master\Dotmim.Sync-master\Samples\WindowsFormsClassic\WindowsFormsClassic.csproj	259	

The file SQLitePCLRaw.lib.e_sqlite3.targets does not seem to exist in the NuGet manager

**Comment by Mimetis** [comment]
I dont know I'm sorry, it's working on my machine :)

**Comment by spj-uk** [comment]
Said like a true developer... :)
