### ISSUE TITLE
[Question] Support multiple client schema?

### ISSUE THREAD

**Issue by Menci77** [Mimetis/Dotmim.Sync#665]
Hi! I was wondering if Dotmim.Sync somehow supports clients with different schemas? Is there a way to handle this? Or can this scenario even occur, or when a new schema version comes we have to use the Provision/Deprovision methods thus all the clients will be updated to that schema?

**Comment by Mimetis** [comment]
> Dotmim.Sync somehow supports clients with different schemas

`DMS` is meant to be used with the same schema between server and client

> when a new schema version comes we have to use the Provision/Deprovision methods thus all the clients will be updated to that schema

I don't get what you mean.
If you are updating your schema, you have to deprovision / provision your sync server only one time, to be up to date.
Same for your clients

**Comment by Menci77** [comment]
Yes, what meant was that all the clients will have the same schema since we have to deprovision/provision on the client side to match the server side. So it cannot happen that different clients have different schemas. Thanks!
