### ISSUE TITLE
How to sync from server to client & client to server

### ISSUE THREAD

**Issue by jeremyv19** [Mimetis/Dotmim.Sync#666]
Please I need to sync from server to client example if I have new client system I need to pull data from server to sync client

and also I need to sync client to server 

I use c# winforms

try
            {
                // Sql Server provider, the "server" or "hub".
                SqlSyncProvider serverProvider = new SqlSyncProvider(
                    @"Data Source=...;Initial Catalog=EcoPOS1_Training;user=sqlserver;password=....;");
                // Sqlite Client provider acting as the "client"
                string dbname = "EcoPOS_Training"; //
                string domain = (AppDomain.CurrentDomain.BaseDirectory).ToString();
                string constring = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename= " + domain + dbname + ".mdf;" + "Integrated Security=True;Connect Timeout=0;";
                SqlSyncProvider clientProvider = new SqlSyncProvider(constring);
                //serverProvider
                //clientProvider
                // Tables involved in the sync process:

                var tables = new string[] { "admin_accts","inventory","order_no","product_category","products","profit","role_permission","shift","store_start",
                                        "transaction_details","user_role","users","void_transaction","xreading","zreading","transaction_items" };

                // Sync agent
                SyncAgent agent = new SyncAgent(clientProvider, serverProvider, tables);

                Invoke(new MethodInvoker(async delegate ()
                {
                    var result = await agent.SynchronizeAsync();
                    rtbResult.Text += (result);
                }));
            }
            catch (Exception ex)
            {
                rtbResult.Text += "\n \n";
                rtbResult.Text += ex.Message.ToString();
            }

The issue in this code is if I perform a test to sync in server to client
the deleted data in client uploading in the server database

**Comment by jeremyv19** [comment]
How to use download only

**Comment by Mimetis** [comment]
https://dotmimsync.readthedocs.io/Synchronize.html?highlight=DownloadOnly#syncdirection
