### ISSUE TITLE
Snapshot Problem/Questions

### ISSUE THREAD

**Issue by BluePalmTree** [Mimetis/Dotmim.Sync#668]
Hello,

first of I love the project. I have a couple of questions regarding creating a snapshot:

- Is it possible to increase the timeout of the RemoteOrchestrator that creates the snpashot files?
- Do the scope of the snapshot and the scope of the sync have to have the same name
- If I have multiple scopes do I need to create multiple snapshots

**Comment by Mimetis** [comment]
> Is it possible to increase the timeout of the RemoteOrchestrator that creates the snpashot files?

Usually, we are using a console application to create a snapshot. 
Why do you need a timeout ?
Did you had a lookt at https://dotmimsync.readthedocs.io/Timeout.html ?

> Do the scope of the snapshot and the scope of the sync have to have the same name

Yes
Even the parameters (if you have filters) should be the same
Usually, you should use the same SyncSetup object, everywhere

> If I have multiple scopes do I need to create multiple snapshots

Yes, because multi scopes, means differents tables / filters

**Comment by BluePalmTree** [comment]
Thank you for the fast answer. Yes I'm using a console application like the example but I get the following exception:

`Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.`

I asked because in the snapshot example it's a RemoteOrchestrator and in the TimeOut example it's a WebClientOrchestrator. And I can't seem to figure out how to set the timeout on a RemoteOrchestrator.

**Comment by Mimetis** [comment]
Hum, i guess the timeout is coming from your database, not from `DMS`.
Is it a huge database ?

Did you tried with the last version of `DMS` (pre-release `v0.9.3`) ? It has some major improvements on the snapshot creation.

**Comment by BluePalmTree** [comment]
Yeah I saw that it is an SqlException. But I don't know if I can change the timeout on an Azure SQL-Server.
I don't know but there are around 5.5 million rows to sync.

No I tried it with v0.9.1, is't possible to use v0.9.3 for the snapshot creation but v0.9.1 in the client and server?

**Comment by Mimetis** [comment]
> No I tried it with v0.9.1, is't possible to use v0.9.3 for the snapshot creation but v0.9.1 in the client and server?

Yes

**Comment by BluePalmTree** [comment]
In the end we had to increase the DTU of the azure database to get it to work.

**Comment by Mimetis** [comment]
> No I tried it with v0.9.1, is't possible to use v0.9.3 for the snapshot creation but v0.9.1 in the client and server?

Yes, you can
