### ISSUE TITLE
Second client fails with "synchronization already in progress" when first client is running

### ISSUE THREAD

**Issue by gb0o** [Mimetis/Dotmim.Sync#67]
Hi @Mimetis, It looks like only one sync is permitted at a time using the web providers. When I kick off a sync and then kick off a second when the first is still running I get an exception `synchronization already in progress`. 

Is this a limitation of .NET Core ASP on Kestrel or are the web providers designed to prevent multiple clients?

**Comment by gb0o** [comment]
I think this is basically because I set up the `WebProxyServerProvider` as a singleton in my .NET Core ASP project as shown in the example code. I can successfully handle multiple syncs at the same time if I manually cache the provider per sync session. I select the correct proxy instance to use using the session Id.

The proxy can also be a scoped instance like `services.AddScoped<IProvider, WebProxyServerProvider>`. This only works if batching is not used otherwise it can't remember its batch files.  `WebProxyServerProvider.IsRegisterAsSingleton` must also be `false`. Maybe there is a way to have a scoped instance persist across multiple requests that make up a sync session?

**Comment by gentledepp** [comment]
hmmm.... this seems to be a critical issue.

In principal, one could cache the WebProxyServerProvider using a MemoryCache. However, that would not work in a scaleout scenario... obviously.

I guess the way to go here is to cache the state of WebProxyServerProvider? (i.e. derive from the provider and use caching like a MemoryCache or Redis)

**Comment by gb0o** [comment]
The following initializes a `SessionCache`  in `WebProxyServerProvider`
```
            // Check if we should handle a session store to handle configuration
            if (!this.IsRegisterAsSingleton)
            {
                // try to get the session store service from DI
                var sessionStore = context.RequestServices.GetService(typeof(ISessionStore));

                if (sessionStore != null)
                    this.LocalProvider.CacheManager = new SessionCache(context);
            }
```
Not sure if this works correctly when multiple clients are requesting sync data. As you mention deriving from the provider and implementing another `ICache` object using `MemCached` or `Redis` would work. The session Id would be used as a key to the cache. Sync sessions would either be removed on `EndSessionAsync` or they would time out and delete their data.

**Comment by Mimetis** [comment]
Thx for the report. Major issue. Will look into it asap

**Comment by Mimetis** [comment]
@gb0o Is it still an issue ?

**Comment by gb0o** [comment]
I believe it is still an issue. In my project I worked around it by creating my own cache using `MemoryCache`. I think we should still keep this open to address in the future.

**Comment by Mimetis** [comment]
it's resolved in the last version :)
