### ISSUE TITLE
Reinitialize with multiple scopes

### ISSUE THREAD

**Issue by BluePalmTree** [Mimetis/Dotmim.Sync#670]
Hello,

this is not an issue but more a question about how it should be done.

We have two scopes, 1. configScope and 2. receiptsScope. The two scopes are connected, means the tables in the receiptsScope have foreign keys on the table in the configScope. We have seperated the two, because the receiptsScope should be synced every 5min on for this be as small as possible. The configScope contains all the other data and is synced once at the start of the application or explicitly. Now my problem is if a reinitialize is need it comes to problems with the foreign key constraints because first everything in the configScope is deleted. My question is how would one do a reinitialize in this case? All tables that need to be synced are present in these two scopes. The options I see are:

1. Somehow disable the foreign key constraints on the tables in the receiptsScope, the reinitialize (and reactivate the constraints?)
2. Create a third scope that contains all tables of the first two and do a reinitialize with that one (is that a good idea?)

So my question is which on of the two is the correct one or are there other options? If it is the first how would one go about it to disable constraints etc.

**Comment by Mimetis** [comment]
> 1. Somehow disable the foreign key constraints on the tables in the receiptsScope, the reinitialize (and reactivate the constraints?)

Can work. You have the option `options.DisableConstraintsOnApplyChanges=True;`

> 2. Create a third scope that contains all tables of the first two and do a reinitialize with that one (is that a good idea?)

Well, it should work also ! (be careful on the table orders or use `DisableConstraintsOnApplyChanges`)
