### ISSUE TITLE
SyncExeption 'SQLite Error 1: 'SQL logic error' with Microsoft.Data.Sqlite 6.0.1

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#671]
Since [#632](https://github.com/Mimetis/Dotmim.Sync/issues/632) I've been waiting for `Microsoft.Data.Sqlite 6.0.1`

We're using `Dotmim.Sync.Sqlite 0.9.1` on the client with `Microsoft.Data.Sqlite 5.0.12` without issues. When I upgrade to `Microsoft.Data.Sqlite 6.0.1` DMS throws `SyncException SQLite Error 1 SQL Logic Error`

Wind back to `Microsoft.Data.Sqlite 5.0.12` and the issue goes away.

**Comment by Mimetis** [comment]
Dont use sqlite 6.0.1 if you are not runnin on .net 6

What is your framework ?

**Comment by VagueGit** [comment]
.NET Standard 2

**Comment by VagueGit** [comment]
Actually the Nuget for `Microsoft.Data.Sqlite 6.0.1` takes a dependency on `.NET Standard 2` not `.NET 6`

**Comment by Mimetis** [comment]
What can we do here, from the `DMS` perspective ? :)

Not sure it's the correct place to investigate the issue, what do you think ?

**Comment by VagueGit** [comment]
It's DMS that throws `SyncException SQLite Error 1 SQL Logic Error`. Our app can sit on `Microsoft.Data.Sqlite 5.0.12`. Whether or not this is a DMS issue, the exception presents as a DMS issue.

**Comment by Mimetis** [comment]
I will try to make a test with `Microsoft.Data.Sqlite 6.0.1` for all the different platforms supported by **DMS** and see if everything is working fine.
If it's the case, I will update the source code and will publish a new beta package

**Comment by Mimetis** [comment]
Done in the last commit in master branch
