### ISSUE TITLE
Remove existing PK column and set GUID column as PK - during (first) provisioning

### ISSUE THREAD

**Issue by dev-rpichler** [Mimetis/Dotmim.Sync#672]
Hi,
first of all thank you for this great framework and work&effort you put into it!
I just startet (but heavily used the MS Sync Framework before) and set up a simple evaluation environment.

My target is to change the PK of several tables because I try to sync with an MSSQL Database with all PK (int) and the clients should also be able to insert new data rows - so I definitelly need GUIDs as PK

Similar to #444 (#285) I'm trying to change the PK-column during provisioning with no success so far.
I set up the ASP.net core version with an provisioning controller.
According to the examples found I tried:

` orchestrator_new.OnProvisioning(args =>
            {
                var schema = args.Schema;

                foreach (var table in schema.Tables)
                {
                    var columnsToRemove = new string[] { "ToFindListId" };
                    foreach (var columnName in columnsToRemove)
                    {
                        var column = table.Columns[columnName];

                        if (column != null)
                            table.Columns.Remove(column);
                    }
                    table.PrimaryKeys.Remove("ToFindListId");
                    table.PrimaryKeys.Add("myGuid");
                }
            });`

but the table comes with no columns so that did not work.

Instead of the rewriting it in the OnProvisioning event I also tried the following in the provisioning method:

`var serverScope = await orchestrator_new.GetServerScopeAsync();
foreach (var table in serverScope.Schema.Tables)
            {
                var columnsToRemove = new string[] { "ToFindListId" };
                foreach (var columnName in columnsToRemove)
                {
                    var column = table.Columns[columnName];

                    if (column != null)
                        table.Columns.Remove(column);
                }
                table.PrimaryKeys.Remove("ToFindListId");
                table.PrimaryKeys.Add("myGuid");
            }

            await orchestrator.SaveServerScopeAsync(serverScope);`

Does not work. I'm sure I do something totally wrong :-)
I hope someone could led me in the right direction!
(I'm using the latest version - hopping with change tracking, but currently with SqlSyncProvider - to be sure that is not reason)
Thank you very much!
Kind regards,
Robert

**Comment by Mimetis** [comment]
Won't work because u will have conflicts on the id generated between server and clients
See #590

**Comment by dev-rpichler** [comment]
Hi,
yes thank you, thats the reason why I would like to use GUID fields as PK.
In the old MS Syncframework we dropped the PK-int field and set the GUID Column as PK (in schema).
Thats exactly what I would like to do - same mentioned in #444.

Like:

table.PrimaryKeys.Remove("ToFindListId"); ==> remove PK (int)
table.Columns.Remove("ToFindListId");
table.PrimaryKeys.Add("myGuid"); ==> add PK-GUID

Thank you!
Kind regards,
Robert

**Comment by Mimetis** [comment]
Wow, that's complicated.
I've made some modification in the core code to make this possible.
If you can clone the repository and use the master branch code, you can do something like this:

``` cs
setup = new SyncSetup(new string[] { "Product" });

// Creating an agent that will handle all the process
var agent = new SyncAgent(clientProvider, serverProvider, options, setup);

// get scope based on the setup 
// getting the scope will provision the database
// so we will need to deprovision - provision again
var serverScope = await agent.RemoteOrchestrator.GetServerScopeAsync();

// [Optional] Create table on client if not exists
await agent.LocalOrchestrator.ProvisionAsync(serverScope.Schema, SyncProvision.Tab

// Get client scope
var clientScope = await agent.LocalOrchestrator.GetClientScopeAsync();

// Deprovision the server scope because it has been created
// And we want to replace all the metadatas where PK are used
await agent.RemoteOrchestrator.DeprovisionAsync(
    SyncProvision.StoredProcedures | 
    SyncProvision.TrackingTable | 
    SyncProvision.Triggers);

// get the schema and create a tmp Fake schema with another primary key
var schema = serverScope.Schema;

// Removing the primary key that is a auto inc column
schema.Tables[0].PrimaryKeys.Clear();

// Removing the primary key as a column as well
// This column will never be synced anymore
schema.Tables[0].Columns.Remove(
    serverScope.Schema.Tables[0].Columns.First(c => c.ColumnName == "ProductID"));

// Add the NEW unique identifier as fake primary key
schema.Tables[0].PrimaryKeys.Add("rowguid");

// affect temporary schema for provisioning
serverScope.Schema = schema;
clientScope.Schema = schema;

// Provision
await agent.RemoteOrchestrator.ProvisionAsync(SyncProvision.StoredProcedures |
    SyncProvision.TrackingTable |
    SyncProvision.Triggers, true, serverScope);

await agent.LocalOrchestrator.ProvisionAsync(SyncProvision.StoredProcedures |
    SyncProvision.TrackingTable |
    SyncProvision.Triggers, true, clientScope);

```

We are replacing the **ProductID** primary key column (`int auto increment`) with a the **rowguid** column (`uniqueidentifier`)
But only when provisioning.
The schema stored in the database is still the good one (in case you need it for create client table)

Let me know if it can work for you
Be careful, the real primary key will never be synced and you can have some records with different **ProductID** that will be considered as same

**Comment by dev-rpichler** [comment]
Hi,
thank you very much!!! 
I'll definitely try it out and give you a feedback. 
thx again!
Kind regards,
Robert

**Comment by Mimetis** [comment]
I'm curious
How your database is working if the primary keys (int auto increment) are different between server and clients ?

**Comment by dev-rpichler** [comment]
Currently we use it for only a few tables which needs a bidirectional sync. We added a GUID column (not null) and in the MS Sync Framework we chose this column as PK column. This works very good in a Windows environment MS SQL on both sides (standard+local).
Now we are going to multiplatform (using Xamarin) and would like to use more tables for bidirectional sync. At the moment I'm not quite sure if the previous concept will still work. Because beside the PK also the FK have to be resolved so we need a lot of logic during the sync process.
Therefore I'm also evaluting another way - with mirroring tables/database where all PK are already replaced with GUIDs - so that the sync with clients will be straightforward and relativly easy then to do and second sync (internally) with the mirrored tables in sql only (also using CT). Both ways seems to bring a lot of work & write ;-)
It is a pity that there is no out of the box solution ( #590 )! 
I let you know where I'm going to :-)
Kind regards,
Robert

**Comment by vunder** [comment]
@dev-rpichler Here is my experience over this issue.
I had local (client) tables with integer ids. Server-side needs to have GUID. To manage "transition period", I've added unique GUID column to each sync table (SyncId).
The configuration remains almost the same. On server SyncId is primary key, on Client Id is primary key. The one thing need to do on the client:
```csharp
...
                        var scope = await agent.LocalOrchestrator.GetClientScopeAsync(null, null, cts.Token, progress);
...
                        var s1 = await agent.SynchronizeAsync(
                            isSyncMode
                                ? Dotmim.Sync.Enumerations.SyncType.Normal
                                : Dotmim.Sync.Enumerations.SyncType.Reinitialize,
                            cts.Token,
                            progress);
...
                        if (scope.IsNewScope)
                        {
                            // Get local schema
                            var schema = await agent.LocalOrchestrator.GetSchemaAsync(null, null, cts.Token, progress);

                            // Resetting primary keys to force to use SyncId as primary key
                            foreach (var t in schema.Tables)
                            {
                                t.PrimaryKeys.Clear();
                                t.PrimaryKeys.Add("SyncId");
                            }
                            // Update all rows on the client side that does not have any tracking rows
                            await agent.LocalOrchestrator.UpdateUntrackedRowsAsync(schema, null, null, cts.Token, progress);
                            s1 = await agent.SynchronizeAsync(Dotmim.Sync.Enumerations.SyncType.Normal, cts.Token, progress);
                        }
// done
```

As you can see, I'm replacing primary keys with SyncId
