### ISSUE TITLE
Foreign key constraint errors same scope, but different filter parameters.  Not going through OnApplyChangesFailed event

### ISSUE THREAD

**Issue by slagtejn** [Mimetis/Dotmim.Sync#677]
We are converting an exiting application that was using sync framework to this nice library, but ran into an issue with FK errors that the sync framework was able to handle through sync knowledge.  The scenario is to sync data for the specific user logging in, but that user is also related to other users (Supervisor -> Employees).  To solve this with filters we create in instance of a 'UserFilterScope' with each parameter.  This needs to happen because of the dynamic relationship between employees.  If a new employee is added under a supervisor then all that data needs to sync to the client (historical) not just starting from the current time the parameter was added.  It's tracking the row version per filter parameter.  The issue is some of the data is crossing filters and only 1 scope syncs at a time.  If the 'UserFilterScope' with parameter 1 syncs, but has a FK to data with parameter 2 it will throw an exception in the SqlSyncAdapter and not bubble through to the OnApplyChangesFailed event like sync framework did.  Sync framework was able to handle this and the scope would continue to sync.  Once parameter 2 syncs it will possibly have inserted the correct records for parameter 1 to succeed on the next sync cycle.  I know you can remove constraints and apply after, but that only applies for a single scope.

The only solution we see is to combine all the filter parameters as a list into a hash as one scope and when that parameter list changes (hash will too) we re-initialize with upload, but that is syncing a lot of unnecessary data that already existed in the client.

Is there a workaround for this or another solution?

**Comment by Mimetis** [comment]
Not clear.
Can you create a repro sample, and explains a little bit better
Just past 10 minutes to read your text block, and I just can't

**Comment by slagtejn** [comment]
Yeah It's a bit confusing since I am combining multiple issues.  I created a sample repo that shows the issue.  Run CreateDatabases.sql before running the app.

[FK Error](https://github.com/slagtejn/Dotmim.Sync.FKError)

**Comment by Mimetis** [comment]
Thanks, will be easier to understand !!

**Comment by Mimetis** [comment]
It's working if you are using `options.DisableConstraintsOnApplyChanges = true;`
Can it be a solution for you ?

**Comment by slagtejn** [comment]
It will work for now, but not the ideal solution since it could leave the database in an inconsistent state.  It will set the foreign key as not trusted (is_not_trusted = 1) when re-enabling.  This also happens on the server so race conditions can occur when uploads from different clients happen at the same time and it could leave the server db in an inconsistent state for a period of time.

I can't think of another solution to handle this in a simple way without tracking the failed records.
