### ISSUE TITLE
Is it normal on each sync to run CREATE PROCEDURE [dbo].[XXX_changes] ?

### ISSUE THREAD

**Issue by hakakou** [Mimetis/Dotmim.Sync#679]
I'm in the process of replacing the native SQL server replication with Dotmim.Sync. There are two SQL servers using ```SqlSyncChangeTrackingProvider``` on both client and server.

I've set-up a service that executes the ```SyncAgent.SynchronizeAsync``` every minute for 14 tables. I've noticed that on every sync, even when there are 0 changes, the following SQL commands are executed on the client:

![image](https://user-images.githubusercontent.com/10587642/148415945-6623009d-ccc7-47dd-993e-17d0018f814d.png)

It seems odd to me that commands like CREATE PROCEDURE [dbo].[XXX_changes] are executed on each and every sync, every minute.

Is this normal? Also perhaps because of the large amount of SQL queries, each sync (even with 0 changes) takes about 2.5 seconds, which seems slow to me.

Thank you for this wonderful library!

**Comment by Mimetis** [comment]
Hello

It's not normal
Can you share your code ? 
Are you trying to `ProvisionAsync` every time ?

**Comment by hakakou** [comment]
I'm definitely not running ProvisionAsync. The code is simple:

```cs
        public ReplicationManager(ILogger logger)
        {
            this.logger = logger;

            string serverConnection = @"Data Source=.\SQL;Database=XXXRemote;Integrated Security=true;Encrypt=False";
            string clientConnection = @"Data Source=.\SQL;Database=XXX;Integrated Security=true;Encrypt=False";

            serverProvider = new SqlSyncChangeTrackingProvider(serverConnection);
            clientProvider = new SqlSyncChangeTrackingProvider(clientConnection);
            options = new SyncOptions();

            // Create standard Setup and Options
            setup = new SyncSetup(new string[] { "ElementJournal", "ElementJournalCode",
                "Order","Person","PersonDiscount","PersonInfo","PersonRole","ClassGroup",
                "DataCountry","DataDoy","DataState","Element","ElementClass","ElementFile",
                "ElementFileRole","ElementTranslation","GalaxyTransSync","Language","Setting" });
        }

        public async Task Execute()
        {
            var agent = new SyncAgent(clientProvider, serverProvider, options, setup);
      }
```

The service creates a static ReplicationManager, keeps it in memory, and runs Execute() every minute.

Anyway, I'll prepare now a small console app to demonstrate the problem.

**Comment by Mimetis** [comment]
I've just checked on a sample project, and I don't have the stored procedures creation every time.
That's strange
If you can provide a sample, it will be easier to figure it out !
Thanks !

**Comment by hakakou** [comment]
I am including a zip with a small project that demonstrates the problem: [SQLSyncTest2.zip](https://github.com/Mimetis/Dotmim.Sync/files/7824051/SQLSyncTest2.zip)

- I'm using (localdb)\MSSQLLocalDB
- Execute first the SQL in the comments of Program.cs, to create in databases TestServer and TestClient with a simple table each.
- Now run the exe; the first time, about 20 queries are produced on the server and client which I guess is normal to provision each database.
- But try running a second or third time. The output I had is below.

I've used the code here https://stackoverflow.com/questions/13638435/last-executed-queries-for-a-specific-database
to get the last queries produced in the past 5 seconds and their corresponding time.

Notice that on simple ```SynchronizeAsync``` for each table provisioned, I still see "CREATE PROCEDURE..." statements, run on both the client and the server.

```
6/1/2022 8:47:06 μμ: (@sync_scope_name nvarchar(100),@sync_scope_schema nvarchar(max) ,@sync_scope_se
6/1/2022 8:47:06 μμ: (@sync_scope_id nvarchar(max) )Select count(*) from [scope_info] where sync_scop
6/1/2022 8:47:06 μμ: (@sync_scope_name nvarchar(100),@sync_scope_id uniqueidentifier,@scope_last_sync
6/1/2022 8:47:05 μμ: (@sync_scope_id nvarchar(max) )Select count(*) from [scope_info_history] where s
6/1/2022 8:47:05 μμ: CREATE PROCEDURE [dbo].[Data_changes] @sync_min_timestamp bigint, @sync_scope_id
6/1/2022 8:47:05 μμ:  create procedure sys.sp_procedure_params_rowset ( @procedure_name sysname, @gro
6/1/2022 8:47:05 μμ: (@sync_scope_name nvarchar(100))SELECT [sync_scope_name] , [sync_scope_schema] ,
6/1/2022 8:47:05 μμ: CREATE PROCEDURE [dbo].[Data_changes] @sync_min_timestamp bigint, @sync_scope_id
6/1/2022 8:47:05 μμ:  create procedure sys.sp_procedure_params_rowset ( @procedure_name sysname, @gro
6/1/2022 8:47:05 μμ: IF EXISTS (SELECT t.name FROM sys.tables t WHERE t.name = N'scope_info_server')
6/1/2022 8:47:05 μμ: (@sync_scope_name nvarchar(100))SELECT [sync_scope_id] , [sync_scope_name] , [sy
6/1/2022 8:47:05 μμ: IF EXISTS (SELECT t.name FROM sys.tables t WHERE t.name = N'scope_info') SELECT
```

This is the important part of the program. Note that I get the connection from the server, but since we are querying the same DB, the results come from both server and client. 

In my production, of course the databases are on different servers, but again the same happens.

```cs
        public async Task Execute()
        {
            var agent = new SyncAgent(clientProvider, serverProvider, options, setup);
            await agent.SynchronizeAsync();

            var q1 = @"SELECT deqs.last_execution_time AS [Time],  dest.TEXT AS [Query] 
                " + "FROM sys.dm_exec_query_stats AS deqs CROSS APPLY sys.dm_exec_sql_text(deqs.sql_handle) AS dest "
                 + $"ORDER BY  deqs.last_execution_time DESC";

            var connection = serverProvider.CreateConnection() as SqlConnection;
            var command = new SqlCommand(q1, connection);
            connection.Open();
            SqlDataReader reader = command.ExecuteReader();
            while (reader.Read())
            {
                var time = (DateTime)reader["Time"];
                if ((DateTime.Now - time).TotalSeconds < 5)
                {
                    Console.WriteLine($"{time}: {FixResult(reader["Query"].ToString())}");
                }
            }
        }
```

**Comment by Mimetis** [comment]
Your sample is correct. I guess your query is wrong
Use the profiler to see the correct traces.
Here is mine:

![image](https://user-images.githubusercontent.com/4592555/148437491-d947ddbe-e9b8-4938-b3b2-f5feec788412.png)

As you can see, we have a Data_changes execution query, not a Data_changes creation

**Comment by Mimetis** [comment]
By the way, look carefully the first comment ..........

![image](https://user-images.githubusercontent.com/4592555/148437759-15c8d5aa-4f84-4c1d-977c-3aa7896af9ea.png)

**Comment by hakakou** [comment]
Dumbfounded! I guess I should read comments... Thank you for your time!
