### ISSUE TITLE
Switch between overlapping scopes

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#683]
Speculating ... define Scope1 as a subset of the tables of the default scope. When the default scope has synced and is uptodate, how do we set Scope1 as uptodate without it having to sync?

Thanks

**Comment by Mimetis** [comment]
I guess you can update the `scope_info` table (on the client side)
The important part here is to update the columns `[scope_last_server_sync_timestamp]` and `[scope_last_sync_timestamp]` (the others columns may be updated as well, but are just here for information)
