### ISSUE TITLE
Syncing from client to server resets all client changed data to 0 (SOMETIMES HAPPENS)

### ISSUE THREAD

**Issue by wTechnoo** [Mimetis/Dotmim.Sync#684]
So basically what's happening is:
I'm using this dotmim sync as a gateway between MySQL and SQLite (server and client), and when I modify/create new rows on this table (RoteiroDia), it doesn't get created/doesn't apply the changes to the current row and ALSO resets the client table to 0. 
The most important column on this table is Debito, whenever a already existing row gets modified and this gets a new value, it resets both mysql and sqlite to 0.

The Create Table for the table that is happening this:
```mysql
CREATE TABLE `RoteiroDia` (
 `id` int NOT NULL AUTO_INCREMENT,
 `Data` datetime NOT NULL,
 `idRota` int NOT NULL,
 `idCliente` int NOT NULL,
 `Pos` int NOT NULL,
 `idVendedor` int NOT NULL,
 `idPlaca` int NOT NULL,
 `Debito` float NOT NULL,
 `Acerto` float NOT NULL,
 `Diferenca` float NOT NULL,
 `Desconto` float NOT NULL,
 `Pagamento` float NOT NULL,
 `NovaVendas` float NOT NULL,
 `Entradas` float NOT NULL,
 `FormaPagamento` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
 `Entregue` tinyint(1) NOT NULL,
 `JaVendido` tinyint(1) NOT NULL,
 `Oculto` tinyint(1) NOT NULL,
 `LTS B` int NOT NULL,
 `LTS A` int NOT NULL,
 `AA` int NOT NULL,
 `AAA` int NOT NULL,
 `LING A` int NOT NULL,
 `LING AA` int NOT NULL,
 `BB` int NOT NULL,
 `BBB` int NOT NULL,
 `CC` int NOT NULL,
 `CCC` int NOT NULL,
 `5LTS B` int NOT NULL,
 `5LTS A` int NOT NULL,
 `DDD` int NOT NULL DEFAULT '0',
 `FFF` int NOT NULL DEFAULT '0',
 `A ICE` int NOT NULL DEFAULT '0',
 `EEEE` int NOT NULL DEFAULT '0',
 `RRR` int NOT NULL DEFAULT '0',
 `QQ` int NOT NULL DEFAULT '0',
 `EEE` int NOT NULL DEFAULT '0',
 `COCO` int NOT NULL DEFAULT '0',
 `WWW` int NOT NULL DEFAULT '0',
 `GGGGGG` int NOT NULL DEFAULT '0',
 `FFFF` int NOT NULL DEFAULT '0',
 `ZZZZ` int NOT NULL DEFAULT '0',
 `MEL` int NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1
```

I changed the name of some of them.
And yes, I know that's a LOT of columns, they're all needed.

**Comment by wTechnoo** [comment]
I'll make a quick sample here on console and send it to you, one second.

**Comment by Mimetis** [comment]
send it to spertus at microsoft dot com

**Comment by wTechnoo** [comment]
Sent.

**Comment by wTechnoo** [comment]
You received it?

**Comment by Mimetis** [comment]
Yes, But I don't have the server side
Is it a classic server side (like HelloWebSync) or something different ?

**Comment by Mimetis** [comment]
I Found, I guess

In `DeprovisionProvision()`, you are using a `SyncProvision.Table` enum value

``` cs
await agent.LocalOrchestrator.DeprovisionAsync(serverSchema, SyncProvision.TrackingTable | SyncProvision.Table | SyncProvision.Triggers | SyncProvision.StoredProcedures | SyncProvision.ClientScope);
```
This value will delete the table :)

**Comment by wTechnoo** [comment]
Hello, it is a classic server like HelloWebSync and the values getting reseted happens when I sync, not when I deprovision, are they related?

**Comment by Mimetis** [comment]
You are making a ReinitiliazeWithUpload, try a classic Normal

**Comment by wTechnoo** [comment]
I'm already syncing with the SyncType.Normal, I only reinitialize when needed, my method accepts a bool and I only use reinitialize when the bool is true

**Comment by Mimetis** [comment]
It's working fine on my side

![image](https://user-images.githubusercontent.com/4592555/149411176-e2f4a284-84cb-44b3-9613-a4c4dea71f5e.png)

**Comment by wTechnoo** [comment]
Those issues usually occur after using the database after some time, also one more question, when I modify/create a new column on a table, I need to do the deprovision and provision right? They sometimes don't work and mess up the inserts on those tables.

**Comment by Mimetis** [comment]
Yes,
On Server : Deprovision, add / edit your columns, provision
On Client  : Deprovision, add / edit your columns, get the server schema, provision

**Comment by Mimetis** [comment]
you were supposed to send me a repro sample, WHERE THE ISSUE OCCURS :)

**Comment by wTechnoo** [comment]
So, can I send my whole project and database access? Very hard to pick only where it's erroring when I have no idea what's happening :/

**Comment by Mimetis** [comment]
no, i just need a way to reproduce the issue

**Comment by wTechnoo** [comment]
Tomorrow I'll provide some more detailed data on the table current state, triggers and etc ok? Thanks for your time Mimetis.

**Comment by Mimetis** [comment]
You need to retrieve a way to reproduce it, otherwise it will be complicated for me to help you here

**Comment by wTechnoo** [comment]
Yes, I'll try to provide the data tomorrow, thanks.

**Comment by wTechnoo** [comment]
Hello mimetis, I'll send my table and procedures with full data through the email ok? Thanks.

**Comment by wTechnoo** [comment]
Sent a zip.

**Comment by wTechnoo** [comment]
So, with those dotmim metadatas and my current table, as I said earlier, it syncs, says that the sqlite data was uploaded but when I recheck the sqlite data, the values are all overwritten to 0, mysql doesn't receive the new values neither.

**A NOTE: THOSE SYNCING ISSUES ONLY HAPPEN ON REAL PHONE, IT WORKS FINE ON MY COMPUTER USING DEBUG MODE**

Some screenshots of the errors that sometimes happens:
![3f3743d6-4329-4498-aa26-c95a220851da](https://user-images.githubusercontent.com/71846381/149631932-b7ba57ce-e413-4e1b-a180-92fae503d590.jpg)
![8c66b8ba-f359-4f82-900d-e6721b8175c1](https://user-images.githubusercontent.com/71846381/149631948-ecd089de-32d5-453c-944d-8b7b50f68972.jpg)

**Comment by wTechnoo** [comment]
Do you accept payments to give some realtime support? I'm at the final of a project and it's already running and that's the only issue left here to fix, thanks.
I know I already opened a lot of issues here, this is my first big project and I needed to finish this to help my father.

**Comment by Mimetis** [comment]
No payments here.
I need a way to reproduce your error.
Try to reproduce in the emulator, and show me how it's breaking

**Comment by wTechnoo** [comment]
Ok, I also sent you the table with the metadatas, table tracking and etcetera.

**Comment by wTechnoo** [comment]
Ok, I also sent you the table, metadatas and the tracking table, thanks.

**Comment by wTechnoo** [comment]
Hello Mimetis, did you have the time to check if my tracking tables or metadatas had something wrong that could cause those errors? Thanks

**Comment by wTechnoo** [comment]
I'll have to figure out here, sent you those data thinking it could be the issue, I'll close this for now.

**Comment by Mimetis** [comment]
let me know your investigations
