### ISSUE TITLE
How to deprovision a single table

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#688]
We use multiple scopes. A migration adds a column to a table. Deprovision deletes the scope_info table.

The following pattern works well, syncing a single table. It create an entry in scope_info table in SQLite
`SyncAgent syncAgent = ConfigureSyncAgent(scope: SyncScopes.JobTypes);`

The pattern below syncs all tables and creates a DefaultScope entry in scope_info table 
`SyncAgent syncAgent = ConfigureSyncAgent();`

I deprovision JobTypes like this
```
SyncAgent syncAgent = ConfigureSyncAgent(scope: SyncScopes.JobTypes);
await syncAgent.LocalOrchestrator.DeprovisionAsync();
```
However this deletes the scope_info table and the whole database must be resynced.

How do I deprovision a single table where we have multiple scopes?

**EDIT 1:** Using `DMS Sync.SQLite 0.91` and `DMS Sync.Web.Client 0.91`

**Comment by Mimetis** [comment]
I don't understand everything, but I think that you should not deprovision the tracking table (if you are using `SqlSyncProvider` and not `SqlSyncChangeTrackingProvider`)

That way, you will not loose all the metadata need by another scope.
Usually, you don't want to loose any data in the tracking tables when you are "just" updating your schema.

Check https://github.com/Mimetis/Dotmim.Sync/blob/master/Samples/Migration/Program.cs

So far, I guess you should do something like that:

``` cs
// Now go for local orchestrator
var localOrchestrator = new LocalOrchestrator(clientProvider, options, setupAddress);

// Unprovision the Address triggers / stored proc. 
// We can conserve tracking table, since we just add a column, that is not a primary key used in the tracking table
// In this case, we will 
await localOrchestrator.DeprovisionAsync(SyncProvision.StoredProcedures | SyncProvision.Triggers);

// Provision the Address triggers / stored proc again, 
// This provision method will fetch the address schema from the database, 
// so it will contains all the columns, including the new one added
await localOrchestrator.ProvisionAsync(SyncProvision.StoredProcedures | SyncProvision.Triggers);


```

**Comment by VagueGit** [comment]
Perfect. Thank you for your assistance @Mimetis
