### ISSUE TITLE
[Enhancement] Use the same sample database for all systems: "chinook"

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#70]
Hi!
The samples and tests of dotmim.sync use different databases: Adventureworks, Contoso, etc.

- While for AdventureWorks there is a sql script to generate the database, this is missing from the others and it is kind of hard to find Contoso these days.
- Moreover, the sample databases only work for MSSQL, not MySql, PostgreSQL, etc.
- And there is another issue with the unittests: Some tests restore a database from a backup. However, the command uses the fixed path "C:\users\mimentis\......" which does not exist on every PC.

My proposal:
- [ ] Use the same sql sample database for all databases. I would suggest [**chinook**](https://github.com/lerocha/chinook-database)
- [ ] Provide the database with sql scripts, as they can be checked in and versioned correctly. Those sql scripts should then also be used in the integration tests

What do you think? 
I am happy to help you with implementing this, I just do not want to create a PR which is ignored because you disagree.

**Comment by Mimetis** [comment]
Agree if this database can handle most of the tests.
