### ISSUE TITLE
[Xamarin app] "SyncException: row array has too many items", but only in release mode, not in debug

### ISSUE THREAD

**Issue by Tuytje** [Mimetis/Dotmim.Sync#700]
I have noticed that I'm getting "SyncException: row array has too many items" when my Xamarin app is build in release mode and the synchronisation doesn't work because of it. I'm using v0.9.1 currently and both debug & release are targetting the same webapi for the sync.

Another error I'm seeing in the logs is "SyncException: row array must have one more item to store state", which seems the exact oposite of the other error ...

Database on the server is exactly the same as on the client, same fields. Only difference is that the userId field is cleared on the server. It does exist on the client as an empty column.

Any ideas?

**Comment by Mimetis** [comment]
Are you using snapshot ? I mean, there is some incompatibility with snapshot created on `v0.9.1` and `v0.9.3`

Otherwise, hard to see what's happens here, I need more Info I guess, like a little bit of code maybe ?
Or a sample repro

**Comment by Tuytje** [comment]
Thanks for the fast reply.
I'm not using a snapshot and I'm still on 0.9.1 (hence the comment on the discussion about 0.9.3). 

the code has been more or less the same for over a year:

```
var agent = new SyncAgent(CreateClientProvider(),
                          await CreateClientOrchestrator(),
                          CreateOptions(),
                          CreateSetup());

var syncResults = await agent.SynchronizeAsync(SyncType.Normal, CreateProgressTracker());
```
With the supporting methods being:
```
private static CoreProvider CreateClientProvider()
{
    return new SqliteSyncProvider(DataRepository.DatabaseLocation);
}

private static async Task<WebClientOrchestrator> CreateClientOrchestrator()
{
    var userContext = await App.GetUserContext();
    var handler = new HttpClientHandler { AutomaticDecompression = DecompressionMethods.GZip };

    var client = new HttpClient(handler) { Timeout = TimeSpan.FromMinutes(20) };

    var clientOrchestrator = new WebClientOrchestrator(SYNC_URL, client: client);
    clientOrchestrator.AddCustomHeader("Authorization", userContext.AuthenticationResult.CreateAuthorizationHeader());

    return clientOrchestrator;
}

private static SyncOptions CreateOptions()
{
    return new SyncOptions
    {
        BatchSize = BATCH_SIZE,
        UseVerboseErrors = true
    };
}

private static SyncSetup CreateSetup()
{
    return new SyncSetup
    {

    };
}
```

I saw that you replied on my comment on the upgrade discussion (thank you). I'll do the upgrade to 0.9.3 as well. See if it helps

**Comment by Mimetis** [comment]
Ok, are you able to make a sample repro where you are able to reproduce the bug ?
or is it random ? (and quite hard to reproduce)

**Comment by Tuytje** [comment]
I have been testing with v0.9.3 and the problem seems to be solved. I have done a release with the new versions on Android & iOS and will keep an eye on the crash logs for this specific error. Thank you for the assistance!
