### ISSUE TITLE
Precision Exception for decimal(2,0) columns in 0.9.3

### ISSUE THREAD

**Issue by ReinholdGuenter** [Mimetis/Dotmim.Sync#701]
I am syncing a database with a column defined as `(PK, decimal(2,0), not null)`.
With 0.9.1 that column got synced as expected.
With 0.9.3 I receive an argument exception:
`Precision value '2' is either less than 0 or greater than the maximum allowed precision of 38.`

The code causing this behaviour came with 1f8e4b253998e5229e803a3b0aea81c1dbfa0f1e
```
            if (sqlDbType == SqlDbType.Decimal)
            {
                var (p, s) = this.SqlMetadata.GetPrecisionAndScale(column);
                if (s > 0)
                {
                    return new SqlMetaData(column.ColumnName, sqlDbType, p, s);
                }
                else
                {
                    if (p == 0)
                        p = 18;
                    if (s == 0)
                        s = 6;
                    return new SqlMetaData(column.ColumnName, sqlDbType, p, s);
                }
            }
```
In my case `s` was set to six. Now `s > p`, which seems to cause the exception.
Is this a bug or can you explain this behaviour?

**Comment by Mimetis** [comment]
Thanks for finding this issue.
Honestly I don't remember why we made this modification. I've fixed it and it will be available in the master branch on the next commit.

If you want to test, here is the code I've changed:

``` cs
var (p, s) = this.SqlMetadata.GetPrecisionAndScale(column);
if (p > 0 && p > s)
{
    return new SqlMetaData(column.ColumnName, sqlDbType, p, s);
}
else
{
    if (p == 0)
        p = 18;
    if (s == 0)
        s = Math.Min((byte)(p-1), (byte)6);
    return new SqlMetaData(column.ColumnName, sqlDbType, p, s);
}

```

**Comment by ReinholdGuenter** [comment]
Thank you very much for the quick response.
I tested the fix and it works for my database.

**Comment by CarstenVogelsang** [comment]
Thank you too.

**Comment by Mimetis** [comment]
> Thank you too. You helped us alot.

I try ;)
