### ISSUE TITLE
SyncException when snapshot of empty table is created

### ISSUE THREAD

**Issue by ReinholdGuenter** [Mimetis/Dotmim.Sync#702]
When I try to create a snapshot of an empty table, a `SyncException` occurs.
My scope has only one table which is empty.

The folder `SnapshotDir/ScopeName/ALL` will be deleted in `RemoteOrchestrator::InternalCreateSnapshotAsync`:
```
            var directoryFullPath = Path.Combine(rootDirectory, nameDirectory);
            if (Directory.Exists(directoryFullPath))
                Directory.Delete(directoryFullPath, true);
```

It is then created in `BaseOrchestrator::InternalGetChangesAsync`:
```
            batchInfo = new BatchInfo(message.Schema, message.BatchDirectory, message.BatchDirectoryName);
            batchInfo.TryRemoveDirectory();
            batchInfo.CreateDirectory();
```

If the row count is 0, the folder will be deleted again in `BaseOrchestrator::InternalGetChangesAsync`:
```
            if (batchInfo.RowsCount <= 0)
                batchInfo.Clear(true);
```

Then a `DirectoryNotFoundException` is created in `RemoteOrchestrator::InternalCreateSnapshotAsync`:
```
            var summaryFileName = Path.Combine(directoryFullPath, "summary.json");
            using (var f = new FileStream(summaryFileName, FileMode.CreateNew, FileAccess.ReadWrite))
```
Finally a `SyncException` is created.

I would recommend, that an empty table should not result in a `SyncException`, which may be misleading.

**Comment by Mimetis** [comment]
Thanks for finding this issue !
I'm on it :)
