### ISSUE TITLE
Dotmim.Sync.SyncException: Execution Timeout Expired.

### ISSUE THREAD

**Issue by hakakou** [Mimetis/Dotmim.Sync#705]
I have two SQL servers syncing for about 3 months now, both of them using SqlSyncChangeTrackingProvider.

In random times, like once per 1 to 3 days (the sync runs every 1 minute all 24 hours) I get a message like this:
```
Dotmim.Sync.SyncException: Execution Timeout Expired.  
The timeout period elapsed prior to completion of the operation or the server is not responding. --->
Microsoft.Data.SqlClient.SqlException: Execution Timeout Expired.  
The timeout period elapsed prior to completion of the operation or the server is not responding. 
```

However today the sync stuck completely and kept failing with the above message. I managed to make it work and get it unstuck using this in the SyncAgent:

```cs
            options = new SyncOptions()
            {
                 BatchSize = 10,   // Default 5000
                 UseVerboseErrors = true,
            };
```

My guess is that every now and then, 10 or more rows with a big nvarchar(max) appear for syncing and some timeout occurs. I was wondering, what number should I set BatchSize to if I am having this problem?

**Comment by Mimetis** [comment]
10 is by far too low (that means each batch is around 10ko ....)
If you have some expiration, it's maybe because of deadlocks some where

- Which version are you using ?
- Are you using DisableConstraintsOnApplyChanges ?

**Comment by hakakou** [comment]
My setup is very simple, I've not changed any default options. Version is 0.9.3. Looks like this:

```cs
serverProvider = new SqlSyncChangeTrackingProvider(serverConnection);
clientProvider = new SqlSyncChangeTrackingProvider(clientConnection);
options = new SyncOptions()
{
     BatchSize = 1000,   // Default 5000
};
setup = new SyncSetup(new string[] { xxx....
var agent = new SyncAgent(clientProvider, serverProvider, options, setup);
var s1 = await agent.SynchronizeAsync();
```

**Comment by hakakou** [comment]
The sync has been running for about 4 months now, and runs every minute all 24h. What I did about 10 days ago, is changed the BatchSize to 1000 (from the default 5000), Since this change, I have never seen the message "The error message "Execution Timeout Expired." in my logs again. 

If I start seeing it again, I'll try your recommendations. Right now, with the default options and BatchSize=1000 everything looks perfect. Thanks!
