### ISSUE TITLE
Upload tables are no longer emptied after synchronization

### ISSUE THREAD

**Issue by AlfaGTA** [Mimetis/Dotmim.Sync#708]
I have two master-details tables whose sync direction is set as upload. After updating DotMim package to version 0.93, these tables are no longer emptied on the client db after synchronization. Has anything changed in the synchronization mechanism?

**Comment by Mimetis** [comment]
you talk about tracking tables ?

**Comment by AlfaGTA** [comment]
No, I'm talking about my tables.

**Comment by Mimetis** [comment]
your tables should be synced with the server, not emptied
I don't get it, can you post a sample ?

**Comment by AlfaGTA** [comment]
Up to version 0.92 the rows present on a table whose sync direction was set to upload were then automatically "deleted" from the client table. For me this behavior was fine. Now, however, this is no longer the case. Is there a reason why the behavior has changed?

**Comment by Mimetis** [comment]
Wow, can you post a sample with the previous version, where you have this behavior ?
Because that should not happens :)
