### ISSUE TITLE
Download only does not track delete statements

### ISSUE THREAD

**Issue by radulacatus** [Mimetis/Dotmim.Sync#711]
# Setup

DownloadOnly setup.
Version: 0.9.3
We are using `DisableConstraintsOnApplyChanges = true` 

Source database has a structure like this

```
CREATE TABLE [dbo].[Parking_Drivers](
	[Id] [uniqueidentifier] NOT NULL,
	[ContactFirstName] [nvarchar](256) NULL,
	.....
 CONSTRAINT [PK_Parking_Drivers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Parking_Drivers]  WITH NOCHECK ADD  CONSTRAINT [FK_Parking_Drivers_Parking_DriverTypes_DriverTypeId] FOREIGN KEY([DriverTypeId])
REFERENCES [dbo].[Parking_DriverTypes] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Parking_Drivers] CHECK CONSTRAINT [FK_Parking_Drivers_Parking_DriverTypes_DriverTypeId]
GO

CREATE TABLE [dbo].[Parking_LicensePlates](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DriverId] [uniqueidentifier] NOT NULL,
	[Number] [nvarchar](20) NOT NULL,
	[CountryCode] [nvarchar](5) NOT NULL,
 CONSTRAINT [PK_Parking_LicensePlates] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Parking_LicensePlates]  WITH NOCHECK ADD  CONSTRAINT [FK_Parking_LicensePlates_Parking_Drivers_DriverId] FOREIGN KEY([DriverId])
REFERENCES [dbo].[Parking_Drivers] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Parking_LicensePlates] CHECK CONSTRAINT [FK_Parking_LicensePlates_Parking_Drivers_DriverId]
GO
```

This might be related to issue #699 
It's reproducing on the same databases & versions.

# Scenario
On the source database we are executing updates on a parent-child aggregate in the same transaction.
Concurrency is possible. It is possible that the sync runs in the middle of a transaction of the source db.
In the simple case, we are removing one child and inserting a new one. The resulting sql commands look something like this:

```
DELETE FROM "Parking_LicensePlates" WHERE "Id" = @p0;
SELECT changes();

INSERT INTO "Parking_LicensePlates" ("Column1", "Column2", "Column3") VALUES (@p1, @p2, @p3);
SELECT "Id" FROM "Parking_LicensePlates" WHERE changes() = 1 AND "rowid" = last_insert_rowid();
```

# Result
On the source db we have only 1 row in `Parking_LicensePlates`.
On the destination db we have both rows, so the delete was not tracked.
There is no exception in the sync process.
The situation is not resolved after the next syncs.
If we do a full download from scratch, the correct data is synced, so only 1 row in `Parking_LicensePlates` on destination db as well.

# Other details
I tried executing similar delete&insert statements from outside our application context and the issue still reproduces.
I think the transactionality is not related to the bug, but somehow the fact that there are 2 changes in a short amount of time has an impact.

**Comment by Mimetis** [comment]
Can you try with the last pre release and see if it's resolving your issue ?
Can be related to #710

**Comment by radulacatus** [comment]
It seems to work.
We will deploy the patch and come back with an update.

Do you think it might also solve this issue #699 without using `DisableConstraintsOnApplyChanges `?

**Comment by Mimetis** [comment]
Yes, it could be the root issue. 
Let me know if it resolves this issue also

**Comment by radulacatus** [comment]
We are now running with the prerelease version and with `DisableConstraintsOnApplyChanges  = false` for 4 days and the issue did not reproduce anymore.
I will close this issue.
