### ISSUE TITLE
System.Reflection.TargetInvocationException: Object reference not set to an instance of an object during outdated sync

### ISSUE THREAD

**Issue by mlxyz** [Mimetis/Dotmim.Sync#714]
Hi,

I'm running version 0.9.1 using the web proxy setup and sqlite on the client side and MSSQL on the server side.
I'm seeing the following error from one of our clients device while syncing (the device hasn't been synced for a longer period of time).
```
  System.Reflection
  RuntimePropertyInfo.GetValue (System.Object obj, System.Object[] index)
  System.Reflection
  PropertyInfo.GetValue (System.Object obj)
  Dotmim.Sync
  SyncLogger.GetValue (System.Reflection.MemberInfo member, System.Object obj)
  Dotmim.Sync
  SyncLogger.GetLogMessageFrom[T] (T value, Microsoft.Extensions.Logging.EventId id)
  Dotmim.Sync
  SyncEventsExtensions.LogDebug[T] (Microsoft.Extensions.Logging.ILogger logger, Microsoft.Extensions.Logging.EventId id, T value)
  Dotmim.Sync
  BaseOrchestrator.InterceptAsync[T] (T args, System.Threading.CancellationToken cancellationToken)
  Dotmim.Sync
  BaseOrchestrator.IsOutDatedAsync (Dotmim.Sync.ScopeInfo clientScopeInfo, Dotmim.Sync.ServerScopeInfo serverScopeInfo, System.Threading.CancellationToken cancellationToken, System.IProgress`1[T] progress)
  Dotmim.Sync
  SyncAgent+<>c__DisplayClass53_0.<SynchronizeAsync>b__0 ()
```
Seems to be some sort of logging issue?
I'm passing a Serilog logger as follows:
```csharp
Microsoft.Extensions.Logging.ILogger logger = loggerFactory.CreateLogger("SyncLogger");

SyncAgent agent = new SyncAgent(clientProvider, webClientOrchestrator,
    new SyncOptions
    {
        UseVerboseErrors = true,
        Logger = logger,
        SerializerFactory = new DotmimMessagePackSerializerFactory()
    });
```

Thanks for the help!

**Comment by Mimetis** [comment]
I think you have a `BaseOrchestrator.IsOutDatedAsync` exception firstly
You client database is out of sync and must be reinitiliazed, I guess

**Comment by mlxyz** [comment]
Yes, there appears to be an out-of-sync exception which I also don't understand as I'm using the `SqlSyncChangeTrackingProvider` and don't make any calls to `DeleteMetadasAsync`.

So I don't think my clients should run into this error. Any thoughts why this might happen?

**Comment by Mimetis** [comment]
The Sql Server Change Tracking feature has its own Delete Metadata mechanism.
By default, if I remember well, the retention is 14 days. You will find more info here : https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/enable-and-disable-change-tracking-sql-server?view=sql-server-ver15#enable-change-tracking-for-a-database
