### ISSUE TITLE
Allow UseBulkOperations=false

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#716]
We use DMS to sync an Orders table and an OrderDetails table between SQLite on the client with SQL Server via https.

The OrderDetails table on the server fires a trigger to update a Transactions table which does not exist on the client.

This works as expected if a single order detail is added to an order. However if more than one order detail is added to an order, then the trigger only fires for the first order detail inserted.

Could this be because DMS is using a bulk insert to add the order details? If so, then this explains why the trigger only fires for the first insert. 

Earlier versions of DMS had the option UseBulkOperations. DMS 0.9.1 doesn't have that option. Is it possible to disable bulk insert in DMS 0.9.1?

**Comment by Mimetis** [comment]
**Bulk Update** is working with triggers correctly
Be careful the **Bulk Update** stored procedure can do either an insert or an update depending if the row already exist or not, for each row from the bulk TVP.

The **Bulk Update** stored procedure is using the `MERGE` statement, and there is something you should consider, really carefully:

When a trigger is fired by `MERGE` it holds the total number of rows affected by the statement. So if your `MERGE` statement inserted 9 rows and updated 3  @@rowcount will be 12 in all triggers.

In an `UPDATE` or `INSERT` trigger use: `SELECT * FROM inserted`

You have an example in any `DMS` trigger (if you are using `SqlSyncProvider`)

For instance, here is a code part from a `ProductCategory_update_trigger`:

``` sql
UPDATE [side] 
SET 	[update_scope_id] = NULL -- since the update if from local, it's a NULL
	,[last_change_datetime] = GetUtcDate()

FROM [ProductCategory_tracking] [side]
JOIN INSERTED AS [i] ON [side].[ProductCategoryID] = [i].[ProductCategoryID]
```
As u can see I'm getting all the rows updated from the `INSERTED` trigger temp table

**Comment by VagueGit** [comment]
Thank you for that explanation @Mimetis. We use the `Dotmim.Sync.SqlServer.ChangeTracking`.

The key bit of my stored proc only expects a single inserted
`SELECT @OrderId = i.OrderId, @ItemCode = i.ItemCode FROM inserted i`

I will rewrite the stored proc to expect a set from inserted or updated

Thank you for the prompt assistance.
