### ISSUE TITLE
[question] are multiple sync scopes supported?

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#72]
Hi!

In all the documentation, what I could find were samples of a sync process where you include one or more tables.

Is it also possible to sync two tables in a separate sync scope?
E.g.:
We have some table which contains all buildings of a company.
Then there is another table containing tasks for a particular user.

Now the scenario would be, that buildings need to be synchronized far less often (e.g. every day), while tasks need to be synchronized every 10 minutes.

In order to achieve that, we'd split the sync process into two separate ones, ans also provide two separate rest endpoints for the synchronization (e.g. /sync/buildungs and /sync/tasks)

Is that - will that ever by - supported?

**Comment by Mimetis** [comment]
It should be supported. I have to make some tests to be sure
