### ISSUE TITLE
Deleted row (Primary key) on the server causes conflict when client adds new record 

### ISSUE THREAD

**Issue by PeterJey** [Mimetis/Dotmim.Sync#723]
Hi - Iam using dotmim to sync a sqlite client with a sql server database.  When I delete a row in management studio.  A cannot add any records from the client in the same table (upload 1, conflict 1).  I am guessing there is a primary key conflict, as the primary key that the client is trying to use is not acceptable to sql server.  Is there a simple fix?  Can I set sql server to reseed? or are UniqueIdentifiers/Guids the way forward?  Thanks in advance - Pete
` 
        var serverProvider = new SqlSyncChangeTrackingProvider(@"connectionstring;");
       
        var clientProvider = new SqliteSyncProvider("Record.db3");

        var agent = new SyncAgent(clientProvider, serverProvider, new string[] { "Answer", "Question", "Response", 
       "ResponseType", "Site" });

        var syncContext = await agent.SynchronizeAsync(SyncType.ReinitializeWithUpload);`

**Comment by Mimetis** [comment]
Indeed, your best solution is to use GUID as primary keys.

**Comment by PeterJey** [comment]
> Indeed, your best solution is to use GUID as primary keys.

Thank you - I have just found issue #590 - which describes the issues - Ill give GUIDs ago
Pete

**Comment by PeterJey** [comment]
I am getting a datatype mismatch when I try to add a record from the client.
`public class Question
    {
        [PrimaryKey]
        public Guid QuestionID { get; set; }
        public string QuestionText { get; set; }
        public Guid SiteID { get; set; }
    }`
I am a noob, so the issue might be staring me in the face - 
not sure if its relevant - but in the sqlite documentation I found this, below...
The [rowid](https://www.sqlite.org/lang_createtable.html#rowid) of a table must be an integer. Attempt to set the [rowid](https://www.sqlite.org/lang_createtable.html#rowid) to anything other than an integer (or a NULL which will be automatically converted into the next available integer rowid) results in an SQLITE_MISMATCH error.

**Comment by Mimetis** [comment]
Maybe because u changed the column datatype, but you keeping using an old provisioned sync version
The first time you call `SynchronizeAsync`, the **DMS** fx will generate things in the database
If you change something in your schema, you have to regenerate these metadata

Try with a clean database (without any **DMS** metadata) otherwise call `DeprovisionAsync` / `ProvisionAsync` methods

If you are just trying the **DMS** framework, I guess starting from a clean database will be the easiest way to resolve this issue

**Comment by PeterJey** [comment]
I am still having issues...
I believe...
I need to avoid auto incremented integers as table primary keys
In preference to use Guids
I am having the issue that the SQL Server table requires 'change tracking', but this requires a primary key, then when I sync with Dotmim, the Sqlite table gets updated and the ID column gets updated and becomes an auto incrementing interger, then I get a data type mismatch when I try to add a row with a GUID value.  Could you give me some advice on how to avoid this? Thank you Pete (my sync code is above - but please feel free to ask for any other details)

**Comment by PeterJey** [comment]
Hi Iam trying to use the GUID - But when I use GUIDs - in SQL Server and use Change Tracking and consequently a primary key - the SQLite client updates to an integer data type - then theres a data type mismatch error. - Any advice would be appreciated. Pete

**Comment by VagueGit** [comment]
We use integer primary keys as below. This is adequate for many use cases (Google/Facebook wouldn't do it this way).

It will usually result in less fragmentation, less disk space, faster CRUD on the server than guids/uuids.
```
public static Int64 NewId
{// A loop that calls DateTimeOffset.Now.UtcTicks 10 times will return 7 distinct values (3 dupes) so we check for dupes
// This method will advance ~15 UtcTicks in 10 iterations and guarantees uniqueness.
// It is almost twice as fast as a while loop with SpinWait.SpinOnce();
// So this method will return a unique value appox every 1.5 milliseconds
    get
    {
        Int64 start = DateTimeOffset.Now.UtcTicks;
        Int64 end = DateTimeOffset.Now.UtcTicks;
        while (end == start)
            end = DateTimeOffset.Now.UtcTicks;
        return end;
    }
}
```
I welcome constructive critique

**Comment by PeterJey** [comment]
Thank you for you're knowledge and experience of this problem, I think your solution will be perfect for me.  Thanks Pete (Im not aiming to be google - so should be fine!)

**Comment by PeterJey** [comment]
I am using UTC ticks to generate a unique Int64  getting the following error...
Dotmim.Sync.SyncException: 'Can't create a SqlRecord based on the rows we have: Value was either too large or too small for an Int32.'

Im not sure where this Int32 is??

My SQLite client side seems to handle it OK - I can add the row to the database (I can see the data in DB Browser).  The SQL Server database is datatype bigint.  The interger in question is '12345650123'
The model of the data is 

`public class Question
    {
        //[PrimaryKey]
        public Int64 QuestionID { get; set; }
        public string QuestionText { get; set; }
        public Int64 SiteID { get; set; }
    }`

The error occurs on synchronisation...at line...

`var result = await agent.SynchronizeAsync();`

Any ideas?
Thanks in advance

**Comment by PeterJey** [comment]
For the moment iam using
int i = Guid.NewGuid().GetHashCode();
