### ISSUE TITLE
Dotmim.Sync.SyncException: 'SQLite Error 14: 'unable to open database file'.'

### ISSUE THREAD

**Issue by PeterJey** [Mimetis/Dotmim.Sync#726]
Hi - I have a xamarin forms project which I am trying to sync between SQLite and SQL server
I get the error...
Dotmim.Sync.SyncException: 'SQLite Error 14: 'unable to open database file'.'
when...
var result = await agent.SynchronizeAsync();

My full sync code is...
`
            //Sql Server provider, the "server" or "hub".
            SqlSyncProvider serverProvider = new SqlSyncProvider(@"Data Source=XXXXXX;Initial Catalog=XXXXXX;Integrated 
            Security=true;");

            // Sqlite Client provider acting as the "client"
            SqliteSyncProvider clientProvider = new SqliteSyncProvider("Kronical.db3");

            // Tables involved in the sync process
            var tables = new string[] { "Question", "Answer", "Area", "Site", "NotificationEmail" };

            // Sync agent
            SyncAgent agent = new SyncAgent(clientProvider, serverProvider, tables);

            var result = await agent.SynchronizeAsync();
            //   Console.WriteLine(result);
`

Not sure if its relevant but...
I am using MVVM
in the ViewModel
questions = new ObservableCollection<Question>(App.Database.GetPeopleAsync().Result);
is bound to the view

My Model is...
`
public class Question
    {
        public int QuestionID { get; set; }
        public string QuestionText { get; set; }
        public int SiteID { get; set; }
        public int QuestionOrder { get; set; }
        public int ResponseTypeID { get; set; }
        public int AreaID { get; set; }
        public int NotificationEmailID { get; set; }
`
If you need anymore info - please ask

**Comment by PeterJey** [comment]
This is the database setup in the App.xaml.cs...
`
private static Database database;

        public static Database Database
        {
            get
            {
                if (database == null)
                {
                    database = new Database(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Kronical.db3"));
                    //database = new Database(Path.Combine(Environment.GetFolderPath(FileSystem.AppDataDirectory, "Kronical.db3")));
                }

                return database;
            }
        }
`

**Comment by Mimetis** [comment]
You have a sample here you can use to debug your issue : https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/XamAppSync

**Comment by PeterJey** [comment]
OK Thanks
