### ISSUE TITLE
Filters not working when setup through web proxies  

### ISSUE THREAD

**Issue by gb0o** [Mimetis/Dotmim.Sync#73]
Filters work when syncing databases directly but not when using the web proxies. See below for details and proposed fix.

#### Server appSettings.json
```
  "Sync": {
    "ConnectionString": "Data Source=DESKTOP-BSIVU73;Initial Catalog=AdventureWorks;Trusted_Connection=True;MultipleActiveResultSets=true",
    "Filters": {
      "Address": "StateProvince"
    },
    "Tables": [
        "Address"
```

#### Client code
```
	var clientProvider = new SqliteSyncProvider(dbPath);
	var proxyClientProvider = new WebProxyClientProvider(new Uri(endPoint + "/sync"));
	var agent = new SyncAgent(clientProvider, proxyClientProvider);
	agent.Parameters.Add("Address", "StateProvince", "Texas");
```

### Testing
When I do a full (no db) or incremental sync I get the following error:
``` 
Dotmim.Sync.SyncException: Bad Request ---> System.Exception: Bad Request
   at Dotmim.Sync.Web.HttpRequestHandler.<ProcessRequest>d__25`1.MoveNext()
```

The exception was thrown from the server side in CoreProvider.GetChanges:
```
	EnumerateChangesInBatchesInternal
	...
	var parameter = context.Parameters.FirstOrDefault(p => p.ColumnName.Equals(filter.ColumnName, StringComparison.InvariantCultureIgnoreCase) && p.TableName.Equals(filter.TableName, StringComparison.InvariantCultureIgnoreCase));
```
because `Parameters(p => p.TableName)`  is `null` 

I tracked this down to property `SyncParameter.TableName`. It doesn't have a setter and therefore could not be deserialized by `WebProxyClientProvider`

### Fix
The fix is simply change `SyncParameter.TableName` property from: 
`public string TableName { get; }` 
to 
`public string TableName { get; set; }`

Looks like a simple typo. 

Regards,
Guy

**Comment by Mimetis** [comment]
Thx !!!
