### ISSUE TITLE
MARS support not enabled when using SqlSyncChangeTrackingProvider

### ISSUE THREAD

**Issue by matevzcesar** [Mimetis/Dotmim.Sync#736]
We're using SqlSyncChangeTrackingProvider with dependeny injection and I noticed that passing the `MultipleActiveResultSets=True` flag in the connection string did not seem to set the `SupportsMultipleActiveResultSets` of the Provider. I noticed that it's not beeing set inside the `SqlSyncChangeTrackingProvider` constructor and I'm wondering if this is by design or if there is a reason not to use MARS with this provider.

**Comment by Mimetis** [comment]
Seems you've spotted an issue here :)
Will be resolved in the next release.

That's being said, you can set manually the property on your `SqlSyncChangeTrackingProvider` instance (`provider.SupportsMultipleActiveResultSets = true;`

**Comment by matevzcesar** [comment]
Thank you! We'll do that in the mean time :)
