### ISSUE TITLE
How to use multi scopes

### ISSUE THREAD

**Issue by AlfaGTA** [Mimetis/Dotmim.Sync#738]
I need to synchronize in some cases only some tables.
If the database does not exist, I synchronize all the tables, then the user can decide to update only some of them.
I have looked at the guide for using multiscopes (https://dotmimsync.readthedocs.io/MultiScopes.html), 
however I would like to clarify following points:
1. Is it necessary to define the various scopes also on the server side (I don't find any reference to this in the guide)? If so, how?
2. Is it possible to include the same table in two different scopes?
3. Will a different folder be created on the client for each scope?
4. Is it possible to create a filter on a specific table to send only some rows of a single table in one synchronization session?

**Comment by Mimetis** [comment]
> 1. Is it necessary to define the various scopes also on the server side (I don't find any reference to this in the guide)? If so, how?

Yes. Define multi scopes with different setups:

https://github.com/Mimetis/Dotmim.Sync/blob/1b5208469c12f9789329fd49af0c5eadc7e375ad/Samples/MutliOrchestratorsWebSync/MutliOrchestratorsWebSyncServer/Startup.cs#L46-L48

(This example is about multi scopes on same setup with different provider, but same applies on different setups for same provider)

> 2. Is it possible to include the same table in two different scopes?

Yes
Not sure, but you will have some conflicts raised, when you will sync the second scopes (not sure, need to be tested)

> 3. Will a different folder be created on the client for each scope?

Yes

> 4. Is it possible to create a filter on a specific table to send only some rows of a single table in one synchronization session?

Setup are predefined on the setup. 
You can't change a filter unless you are deprovision & provision again

Of course the parameter value can be changed on each client (client 1 has parameter @ClientId = 1. client 2 has parameter @ClientId = 2)
