### ISSUE TITLE
Filter stored procs not deleted by Deprovision command

### ISSUE THREAD

**Issue by gb0o** [Mimetis/Dotmim.Sync#74]
When using the deprovision command I noticed that stored procedures for filters are not removed by the command CoreProvider.DeprovisionAsync(config, SyncProvision.StoredProcedures) but should be.

**Comment by gentledepp** [comment]
which database?
1) SQLite
2) MySQL
3) MSSQL
4) All of them?

**Comment by gb0o** [comment]
MSSQL, I haven't tested for databases.
