### ISSUE TITLE
Join and CustomWhere not working properly

### ISSUE THREAD

**Issue by AlfaGTA** [Mimetis/Dotmim.Sync#741]
I've set following filter:
```
            SetupFilter scadenzeFilter = new SetupFilter("Scadenze");
            scadenzeFilter.AddParameter("Agente", "Anagrafe", true);
            scadenzeFilter.AddParameter("TuttiClienti", System.Data.DbType.Int32, true);
            scadenzeFilter.AddJoin(Join.Inner, "Anagrafe")
                .On("Scadenze", "CodCli", "Anagrafe", "CodCli");
            scadenzeFilter.AddCustomWhere("Anagrafe.Agente = @Agente OR Anagrafe.Agente = -1 OR @TuttiClienti = 1 OR side.sync_row_is_tombstone = 1");
            setup.Filters.Add(scadenzeFilter);
```

The generated SQL is:
```
ALTER PROCEDURE [dbo].[Scadenze_AgenteTuttiClienti__changes]
	@sync_min_timestamp bigint = 0,
	@sync_scope_id uniqueidentifier = NULL,
	@Agente int = NULL,
	@TuttiClienti int = NULL
AS
BEGIN
SELECT DISTINCT	[side].[Id], 
	[base].[NumFatt], 
	[base].[NumEffetto], 
	[base].[Importo], 
	[base].[DataScad], 
	[base].[CodCli], 
	[base].[Datadoc], 
	[base].[DataLimite], 
	[base].[TipoEffetto], 
	[base].[Incassato], 
	[base].[ImpParzInc], 
	[base].[Anagrafe_Id], 
	[side].[sync_row_is_tombstone] as [sync_row_is_tombstone], 
	[side].[update_scope_id] as [sync_update_scope_id]
FROM [Scadenze] [base]
RIGHT JOIN [Scadenze_tracking] [side] ON [base].[Id] = [side].[Id]
INNER JOIN [Anagrafe] ON [base].[CodCli] = [Anagrafe].[CodCli]

WHERE (
(
  Anagrafe.Agente = @Agente OR Anagrafe.Agente = -1 OR @TuttiClienti = 1 OR side.sync_row_is_tombstone = 1
)
AND 
	[side].[timestamp] > @sync_min_timestamp
	AND ([side].[update_scope_id] <> @sync_scope_id OR [side].[update_scope_id] IS NULL)
)

```
This procedure not returns deleted rows. If I try to exchange RIGHT JOIN statement with INNER JOIN, like so:
...
FROM [Scadenze] [base]
INNER JOIN [Anagrafe] ON [base].[CodCli] = [Anagrafe].[CodCli]
RIGHT JOIN [Scadenze_tracking] [side] ON [base].[Id] = [side].[Id]
...

the query works fine and returns deleted rows too.
How can I fix this issue?

**Comment by Mimetis** [comment]
The order of the two lines you mention is not a resolution
The modification you mentioned do nothing.
Results is the same. You did not exchange anything here

Are you sure of the code you mention here ?

**Comment by AlfaGTA** [comment]
I tried, but I receive following sync error:

SQLite Error 19: 'NOT NULL constraint failed: Scadenze.Id'.

**Comment by Mimetis** [comment]
Can you share your table schema ?

**Comment by AlfaGTA** [comment]
Unfortunalety I still receive the error.

About the exchange of join statements, I made other tests and it works fine.
Here are 2 screenshots about the different behavios.
In the first image, you can se the query generated automatically. As you can see, deleted rows are missing:
[https://drive.google.com/file/d/1V8pqZaZ7ByrIMxNzmNtiYm3aqJxdlhYd/view?usp=sharing](url)

In this image, resultset contains the deleted rows:
[https://drive.google.com/file/d/1gDKWfTQHE0zwep217CuKFTyDVhioypiv/view?usp=sharing](url)

The second is the expected resultset.

**Comment by Mimetis** [comment]
I'm sorry, your links don't work

**Comment by AlfaGTA** [comment]
Sorry,
1st
![Immagine 2022-05-31 131841](https://user-images.githubusercontent.com/2462514/171177295-7bbbbc90-abba-41f6-858a-c8b72404615f.png)

2nd
![Immagine 2022-05-31 131906_2](https://user-images.githubusercontent.com/2462514/171177348-643eed8c-5188-4e2a-bf35-4bba304223bd.png)

**Comment by Mimetis** [comment]
Sorry, I don't know
One thing: If the row is deleted, the` [Scadenze].[CodeCli]` is always `null `(the row does not exists anymore)
