### ISSUE TITLE
After version update sync doesn't work

### ISSUE THREAD

**Issue by BluePalmTree** [Mimetis/Dotmim.Sync#743]
Hello,

I'm sorry to ask again but after we updated from 0.9.1 to 0.9.4 the sync doesn't work anymore on existing databases.
I tried creating a new server/client database and there the sync worked. We're syncing over HTTP.

On the existing I tried
**ServerSide**
`orchestrator.ProvisionAsync(overwrite:true);`

**ClientSide**
```c#
var serverSchema = await _serverOrchestrator.GetSchemaAsync();
await _agentConfig.LocalOrchestrator.ProvisionAsync(serverSchema);
```
But still the sync doesn't work.

Is there a way to completely reset the sync information on both databases, as if a sync never happen?

**Comment by Mimetis** [comment]
If you want to remove everything, just call `DeprovisionAsync()`

``` cs
await orchestrator.DeprovisionAsync(SyncProvision.StoredProcedures | SyncProvision.Triggers | SyncProvision.TrackingTable)
```
If u want to keep tracking rows, do not add `SyncProvision.TrackingTable`

You can delete scope tables as well (`SyncProvision.ServerScope | SyncProvision.ServerHistoryScope` on server, `SyncProvision.ClientScope` on client)
