### ISSUE TITLE
Upgrade library from 0.6.1 to 0.9.4 on a DB with schema changes

### ISSUE THREAD

**Issue by marina-lozovanu** [Mimetis/Dotmim.Sync#745]
We are using the library with version 0.6.1: SqlServer like remote DB and Sqlite for local one.
After a database schema change, we tried to apply deprovision/provision following the sample from the documentation. But the provisioning was throwing the following error "Table AgendaInfo has no columns". 
We were trying to update even the library to the latest version (0.9.4) using some methods like UpgradeAsync (without finding any test for this operation). 
We found in one sample the method ForceUpgradeClientAsync that should upgrade the client DB.
Can you tell us how to proceed in order to not lose the changes that are in pending on the remote and local repositories?

**Comment by marina-lozovanu** [comment]
In order to delete all triggers, can we use the method Deprovision method passing StoredProcedures and Triggers (without deleting the tracking tables)?

`Deprovision(SyncProvision.StoredProcedures | SyncProvision.Triggers)`

**Comment by Mimetis** [comment]
Yes, that should work
But since you have a problem with a table `AgendaInfo` I'm not sure it will work for this one.
But yes, since you are not passing `SyncProvision.TrackingTable`, you will not delete the tracking table
