### ISSUE TITLE
DotMimSync 0.9.4: Unable to sync Country Specific data using filters

### ISSUE THREAD

**Issue by AshwiniKunturkar** [Mimetis/Dotmim.Sync#753]
Hello Mimetis team,
                               Please find attached document with explanation of the issue we are facing and code snippet for your reference. 
[DMS_ProblemStatement.docx](https://github.com/Mimetis/Dotmim.Sync/files/9039850/DMS_ProblemStatement.docx)

Do let us know if you need any further information. 
Thanks in advance!!

**Comment by Mimetis** [comment]
You are changing the parameter value in your client application, for the same client database
Do not do this
A parameter is tight to a client database

**Comment by AshwiniKunturkar** [comment]
We have a requirement to download multiple country specific data to single client database based on user selected country. 
Is there any provision to achieve it using DotMim.Sync?

**Comment by Mimetis** [comment]
With the last version `v0.95` (still in preview) you can define multiples scopes with the same table.

``` cs
// Step 1: Create the setup
var setup = new SyncSetup(productCategoryTableName, productTableName);

// Add filters
var productFilter = new SetupFilter("Product");
productFilter.AddParameter("ProductCategoryID", "Product");
productFilter.AddWhere("ProductCategoryID", "Product", "ProductCategoryID");

var productCategoryFilter = new SetupFilter("ProductCategory");
productCategoryFilter.AddParameter("ProductCategoryID", "ProductCategory");
productCategoryFilter.AddWhere("ProductCategoryID", "ProductCategory", "ProductCategoryID");

setup.Filters.Add(productCategoryFilter);
setup.Filters.Add(productFilter);

// ------------------------------------------------
var paramMountb = new SyncParameters(("ProductCategoryID", "MOUNTB"));
var paramRoadfr = new SyncParameters(("ProductCategoryID", "ROADFR"));

// create agent with filtered tables and parameter
var agent = new SyncAgent(clientProvider, serverProvider, options);

var rTourb = await agent.SynchronizeAsync("Mountb", setup, paramMountb);
var rRoadfr = await agent.SynchronizeAsync("Roadfr", setup, paramRoadfr);

Assert.Equal(8, rTourb.TotalChangesDownloaded);
Assert.Equal(8, rTourb.TotalChangesApplied);
Assert.Equal(3, rRoadfr.TotalChangesDownloaded);
Assert.Equal(3, rRoadfr.TotalChangesApplied);

```

**Comment by AshwiniKunturkar** [comment]
Hello Sébastien,
                  We tried using multi scopes with 0.9.5 version of Dotmim.Sync. We seek your further support to analyze two issues as mentioned in the attachment. 
[List of doubts.docx](https://github.com/Mimetis/Dotmim.Sync/files/9452494/List.of.doubts.docx)

Appreciate your support.

**Comment by Mimetis** [comment]
If you are in a testing phase, you can test using this branch : https://github.com/Mimetis/Dotmim.Sync/tree/ClientHistory and see if it's working better ?

Be careful to start always from scratch (no already provisioned server / client database) to test this branch

**Comment by AshwiniKunturkar** [comment]
Hello Sébastien,
                         We've tested the same scenarios using fresh DB with version: 0.9.6-beta-0873 and found that it still works the same hence the reported both issues still exist.

**Comment by Mimetis** [comment]
Please provide a markdown sample where you are able to reproduce the bug, otherwise it will be complicated to reproduce and help you.

**Comment by AshwiniKunturkar** [comment]
Hello Sébastien,
                          Please find the attached document with code snippets and explanation to the issues we are facing. 
Do let us know if you need further information. 
[List of Doubts with code snippets.docx](https://github.com/Mimetis/Dotmim.Sync/files/9502847/List.of.Doubts.with.code.snippets.docx)

**Comment by Mimetis** [comment]
Hello @AshwiniKunturkar 

Please use Markdown code instead of using a word document, for next questions.
You can edit my message to see how I'm using it here, or you can check the documentation here : https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

The problem from your code is that you did not initialize the synchronization for the parameter `Sweden`, before adding rows on the client:

Here is a version that works correctly:

``` sql
use master;
-- Server database
if (exists (select * from sys.databases where name = 'AdventureWorks'))
Begin
	ALTER DATABASE [AdventureWorks] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [AdventureWorks]
End
Create database [AdventureWorks]
Go
-- Client database. No need to create the schema, Dotmim.Sync will do
if (exists (select * from sys.databases where name = 'Client'))
Begin
	ALTER DATABASE [Client] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [Client]
End
Create database [Client]
Go
USE [AdventureWorks]
GO

CREATE TABLE [dbo].[Customer](
	[Id] [uniqueidentifier] NOT NULL,
	[CustomerName] [nvarchar](200) NOT NULL,
	[Country] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED (Id ASC))
GO

INSERT [dbo].[Customer] ([Id], [CustomerName], [Country]) VALUES (NEWID(), 'A', 'USA')
INSERT [dbo].[Customer] ([Id], [CustomerName], [Country]) VALUES (NEWID(), 'B', 'USA')
INSERT [dbo].[Customer] ([Id], [CustomerName], [Country]) VALUES (NEWID(), 'C', 'USA')
INSERT [dbo].[Customer] ([Id], [CustomerName], [Country]) VALUES (NEWID(), 'D', 'India')
INSERT [dbo].[Customer] ([Id], [CustomerName], [Country]) VALUES (NEWID(), 'E', 'India')
INSERT [dbo].[Customer] ([Id], [CustomerName], [Country]) VALUES (NEWID(), 'F', 'India')
INSERT [dbo].[Customer] ([Id], [CustomerName], [Country]) VALUES (NEWID(), 'G', 'SouthAfrica')
INSERT [dbo].[Customer] ([Id], [CustomerName], [Country]) VALUES (NEWID(), 'H', 'SouthAfrica')
```

And the C# code using DMS version 0.9.6 beta:

``` cs
var serverProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(serverDbName));
var clientProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(clientDbName));

var setup = new SyncSetup("Customer");
setup.Filters.Add("Customer", "Country");


var agent = new SyncAgent(clientProvider, serverProvider);

var paramIndia = new SyncParameters(("Country", "India"));
var paramSouthAfrica = new SyncParameters(("Country", "SouthAfrica"));
var paramSweden = new SyncParameters(("Country", "Sweden"));

var resultIndia = await agent.SynchronizeAsync(setup, paramIndia);
Console.WriteLine(resultIndia);
var resultSweden = await agent.SynchronizeAsync(setup, paramSweden);
Console.WriteLine(resultSweden);

await DBHelper.ExecuteScriptAsync(clientDbName, 
    "INSERT [dbo].[Customer] ([Id], [CustomerName], [Country]) VALUES (NEWID(), 'S1', 'Sweden')");
await DBHelper.ExecuteScriptAsync(clientDbName, 
    "INSERT [dbo].[Customer] ([Id], [CustomerName], [Country]) VALUES (NEWID(), 'S2', 'Sweden')");

resultSweden = await agent.SynchronizeAsync(setup, paramSweden);
Console.WriteLine(resultSweden);

```
![image](https://user-images.githubusercontent.com/4592555/188813801-c9ac85f8-d7ed-4904-98bc-c40db3cdd3da.png)

Regarding all the stored procedures, I think you've used an older version than 0.9.6
In my case, here is the result of the TSQL generation:


![image](https://user-images.githubusercontent.com/4592555/188814730-5f414afa-f64b-41fa-85ce-176cd1364466.png)



Side note: Don't use `.Result` when calling an async method, prefer using `await` keyword

**Comment by AshwiniKunturkar** [comment]
Hello again, 
                  Thank you for your prompt reply. 
Now we are not only able to synchronize Sweden records from Client DB to Server DB but also able to avoid number of stored procedures by referring to your code snippets. 

Furthermore, we seek your extended support to enhance the code to handle country specific data entered by the user dynamically i.e. The user can enter the records for any other countries which will not be known at the moment to synchronize it before adding them into the Client DB. Filter parameter value for country should be handled dynamically. 
e.g. the user may enter records for Germany in Client DB and we don't have code to synchronize Germany specific records in advance. In that case, how do we get the added records for Germany into Server DB? 

Ideally, it is not an good idea to add synchronization code in advance for all countries. 

Please guide us accordingly.

**Comment by AshwiniKunturkar** [comment]
Hello Sébastien,
                         Thank you for your valuable support. 
By referring to above code, we have tried to add country specific records e.g. Sweden from one user's machine in Client database, it is synchronized successfully to Server Database also. When the second user synchronized the database using the same code then he could not get the records belong to Sweden country from Server database which are added by the first user. 
Is there any way to achieve it?

**Comment by Mimetis** [comment]
This code worked for me:

``` cs
var serverProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString("svProduct"));
var client1Provider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString("CliProduct"));
var client2Provider = new SqliteSyncProvider(Path.GetRandomFileName().Replace(".", "").ToLowerInvariant() + ".db");

var setup = new SyncSetup("Customer");
setup.Filters.Add("Customer", "Country");

var agent = new SyncAgent(client1Provider, serverProvider);

var paramIndia = new SyncParameters(("Country", "India"));
var paramSweden = new SyncParameters(("Country", "Sweden"));

var resultIndia = await agent.SynchronizeAsync(setup, paramIndia);
Console.WriteLine(resultIndia);

await DBHelper.ExecuteScriptAsync("CliProduct",
    "INSERT [dbo].[Customer] ([CustomerID], [LastName], [Country]) VALUES (NEWID(), 'S1', 'Sweden')");
await DBHelper.ExecuteScriptAsync("CliProduct",
    "INSERT [dbo].[Customer] ([CustomerID], [LastName], [Country]) VALUES (NEWID(), 'S2', 'Sweden')");

// try to get sweden info client instance:
// if it is not existing, DMS will create a new one, with IsNewScope set to true
var swedenScopeInfoClient = await agent.LocalOrchestrator.GetScopeInfoClientAsync(syncParameters: paramSweden);

if (swedenScopeInfoClient.IsNewScope)
{
    swedenScopeInfoClient.IsNewScope = false;
    swedenScopeInfoClient.LastSync = DateTime.Now;
    swedenScopeInfoClient.LastSyncTimestamp = 0;
    swedenScopeInfoClient.LastServerSyncTimestamp = 0;

    await agent.LocalOrchestrator.SaveScopeInfoClientAsync(swedenScopeInfoClient);
}

// sweden rows are sent to server
var resultSweden = await agent.SynchronizeAsync(setup, paramSweden);
Console.WriteLine(resultSweden);

agent = new SyncAgent(client2Provider, serverProvider);

resultIndia = await agent.SynchronizeAsync(setup, paramIndia);
Console.WriteLine(resultIndia);
resultSweden = await agent.SynchronizeAsync(setup, paramSweden);
Console.WriteLine(resultSweden);

```

**Comment by AshwiniKunturkar** [comment]
Hello Sébastien,
                         Thank you very much. It worked for us as well. 
Further queries are:
1. Is there any limitation to add number of tables inside the single scope? 
2. Is there any limitation to have number of client databases ? 
3. Is there any limitation for number of rows in the scope tables (scope_info_client and scope_info)?

**Comment by Mimetis** [comment]
> 1. Is there any limitation to add number of tables inside the single scope?

Nop

> 2. Is there any limitation to have number of client databases ?

Nop

> 3. Is there any limitation for number of rows in the scope tables (scope_info_client and scope_info)?

Nop

**Comment by AshwiniKunturkar** [comment]
Thank you so much Sébastien. With your proactive support, we managed well to achieve our goal using DotMimSync.
Highly appreciate your time and help :)
