### ISSUE TITLE
Conflict management - take both client and server changes?

### ISSUE THREAD

**Issue by spj-uk** [Mimetis/Dotmim.Sync#757]
Is it possible when resolving conflicts to keep both items e.g.

Server:  ID 2 Name "Bob"
Client: ID 2 Name "Jo"

Presumably ID would need to be changed / incremented and then inserted somehow.

**Comment by Mimetis** [comment]
hello @spj-uk 
I'm sorry, you can use the `Merge` option when dealing with conflicts, but to be in sync, both rows should have the same value

**Comment by spj-uk** [comment]
Thanks for replying. To confirm I want both rows in the synchronised database rather than to merge the records. i.e. Client ID 2 would have to become a new record with ID as it's a primary key. Is this possible?

**Comment by Mimetis** [comment]
DMS will not be able to do that.

**Comment by VagueGit** [comment]
The client must ensure unique ids. That's why DMS recommends using guids. It is possible to use sequential integer identifiers, but you will need an algorithm to generate identifiers that ensures uniqueness across devices even when disconnected.

**Comment by Mimetis** [comment]
Take a look here : https://github.com/Mimetis/Dotmim.Sync/issues/590
