### ISSUE TITLE
CI pipeline

### ISSUE THREAD

**Issue by ashalkhakov** [Mimetis/Dotmim.Sync#76]
Let's add a CI pipeline to this project.

The problem is I don't know which can we use, since this is an open source project. How about AppVeyor, they have a free plan for OSS projects. Or CircleCI, TravisCI or whatever else there is?

**Comment by gentledepp** [comment]
Do you have any experiences with one of those?
What's important is to have a running instance of MSSQL and MySQL, as lots of the tests are integration tests.
My lucky guess would be using some preconfigured docker image, but I have no experience with that. Maybe you can make a PR? :-)

**Comment by ashalkhakov** [comment]
> Maybe you can make a PR? :-)

I will work on this sometime next week. I don't have experience with any of these so I don't know if they allow to use databases during test runs.

**Comment by gentledepp** [comment]
Great!
I have seem some successful projects (e.g. AutoMapper) using appveyor.
A short google search shows, that they do support MySQL and several MSSQL versions:

https://www.appveyor.com/docs/services-databases/

Maybe that is the best place to start :-)

**Comment by Mimetis** [comment]
Im from Microsoft so we can use Visual Studio Team Services if you want ?

**Comment by gentledepp** [comment]
sure - if the setup is equally simple 👍 
But appveyor is free for open source projects - as far as I know

**Comment by ashalkhakov** [comment]
Please take a look. I will probably reopen another PR with cleaner git history. :)

**Comment by ashalkhakov** [comment]
Now that #79 has been merged, I guess the only thing missing is probably nuget packaging and publishing. And there is also #71, about versioning (I guess we should adopt semantic versioning, but how does that blend with the proposal?).

@Mimetis what do you think? I have little idea how others are doing it. @gentledepp do you have any ideas regarding the general workflow? IIUC, we want "stable" builds to produce NuGet packages, which are then published.

**Comment by gentledepp** [comment]
Basically I would suggest:
1) keep the assembly version at 1.0.0.0 and only raise the assembly file version
2) use semantic versioning for assembly file version and nuget package version
=> i.e. only raise first version part in case there are any breaking changes

Basically, I am a very strong supporter of backwardly compatibility, so any changes to a library that need modifications by the client projects should be avoided.

As for packaging - I guess this should not happen in CI directly.
There should be a process to release a new version which can be kicked-off manually - whenever the owners of the repository think it is time for it and not on every CI build (PR, daily build, whatever)

What I wish we would have is symbol packages, so we could debug dotmim.sync even if we had not compiled it ourselves.
There is even a system which directly links the sources on github to a library deployed via nuget, but I forgot the name :-|
