### ISSUE TITLE
Exception when trying to get scope from server via WebRemoteOrchestrator

### ISSUE THREAD

**Issue by flacidsnake** [Mimetis/Dotmim.Sync#760]
Hi @Mimetis ,

I'm testing the version 0.9.5, trying to reproduce (step by step) the [Migration](https://github.com/Mimetis/Dotmim.Sync/discussions/755#discussioncomment-3101947) example with my project.

Everything works fine at server side. I created a new scope at server side, which includes an extra nullable nvarchar(max) column. But, when I get the new server scope from the LocalOrchestrator, I get the exception below:

`Dotmim.Sync.Web.Client.HttpSyncWebException: Seems you are trying another Setup tables that what is stored in your server scope database. Please make a migration or create a new scope`

Any ideas?
As always, thanks in advance :)

**Comment by Mimetis** [comment]
If you have created a new scope on the server side (I don't know the name, but let's say new scope name is `wow`); you need to call the method from your `localOrchestrator` with this name:

``` cs
var remoteOrchestartor = new WebRemoteOrchestrator(serviceUri);
var serverScope = await remoteOrchestrator.GetServerScopeInfoAsync("wow")

// Provision the new "wow" scope on the client
await localOrchestrator.ProvisionAsync(serverScope);
```

If you already do that, I need more info to help you. (Please provide some code context :) )

**Comment by flacidsnake** [comment]
I think I got it sorted. I'll explain what I did just in case is relevant for somebody..

For the record, the example you provided (linked at my first post) works as intended :)

In my case, both server and client database were on version 0.9.4. Don't know exactly what I was doing wrong.. I think I didn't add the `SyncSetup` object when provisioning the new scope at server side.

In order to not get any errors during the migration, I did:

Server side

`            

            var serverProvider = new SqlSyncChangeTrackingProvider(serverConnectionString);
            var syncOptions = new SyncOptions
            {
                BatchSize = 2000,
                DisableConstraintsOnApplyChanges = false,
                ConflictResolutionPolicy = ConflictResolutionPolicy.ClientWins,
                UseVerboseErrors = true
            };
            var tables = new[] {
                // Since we are just adding a NULLABLE column to an existing column, here we put the same tables in the same order
            };
            var syncSetup = new SyncSetup(tables)
            {
                StoredProceduresPrefix = "sp",
                StoredProceduresSuffix = "",
                TrackingTablesPrefix = "t",
                TrackingTablesSuffix = ""
            };

            // Using the Progress pattern to handle progression during the synchronization
            var progress = new SynchronousProgress<ProgressArgs>(args => Console.WriteLine($"{args.ProgressPercentage:p}:\t{args.Message}"));

            var orch = new RemoteOrchestrator(serverProvider);
            bool needUpgrade = await orch.NeedsToUpgradeAsync();
            
            // We are in 0.9.4 and we need to upgrade to 0.9.5. So, upgrade to the last version
            if (needUpgrade)
            {
                var s1 = await orch.UpgradeAsync(progress: progress);
                Console.WriteLine(s1);
            }

            // Add a new column to the server
            await AddColumnToServerAsync(new SqlConnection(serverConnectionString));
            // Provision the server with the new scope.
            var serverScope = await orch.ProvisionAsync(scopeName: "NameOfTheNewScope", syncSetup, progress: progress);
            // (Optional) Update an existing record with a value on the new colum or just insert a new record populating the value
            using (var command = c.CreateCommand())
            await InsertOneRecordWithNewColumnAsync(new SqlConnection(serverConnectionString));`
            
Client side (Xamarin iOS app with SQLite)


`

            WebRemoteOrchestrator serverOrchestrator = new WebRemoteOrchestrator($"{ApiEndpoint}/sync", client: client);SqliteSyncProvider clientProvider = new SqliteSyncProvider(databasePath);
            SyncOptions clientOptions = new SyncOptions { ConflictResolutionPolicy = ConflictResolutionPolicy.ClientWins, BatchSize = 2000, DisableConstraintsOnApplyChanges = false, UseVerboseErrors = true };

            SyncAgent agent = new SyncAgent(clientProvider, serverOrchestrator, clientOptions);

            // 0.9.4 Sync to get rid of any pending changes (optional, since we are going to reinitialize with upload after)
            await agent.SynchronizeAsync(SyncType.Normal, progress);

            // Add a new column to the client
            await AddColumnToClientAsync(clientProvider.CreateConnection());

            // Getting the server scope from server side. Adding a SyncSetup object as a parameter provokes the error in my first post
            var serverScope = await agent.RemoteOrchestrator.GetServerScopeInfoAsync("NameOfTheNewScope", progress: progress);

            // Provision the client with the new scope
            var newClientScope = await agent.LocalOrchestrator.ProvisionAsync(serverScope, progress: progress);

            // ShadowScope old scope to new scope. In my case, the old scope was DefaultScope
            var oldClientScope = await agent.LocalOrchestrator.GetClientScopeInfoAsync("DefaultScope", progress: progress);
            newClientScope.ShadowScope(oldClientScope);
            newClientScope= await agent.LocalOrchestrator.SaveClientScopeInfoAsync(newClientScope, progress: progress);

            // 0.9.5 Sync
            result = await agent.SynchronizeAsync("NameOfTheNewScope", syncType: SyncType.ReinitializeWithUpload, progress: progress);

            // Get rid of the old scope
            await agent.LocalOrchestrator.DeprovisionAsync("DefaultScope", SyncProvision.StoredProcedures, progress: progress);
            await agent.LocalOrchestrator.DeleteClientScopeInfoAsync(oldClientScope, progress: progress);`

We can close this
