### ISSUE TITLE
Multiple scopes - Question

### ISSUE THREAD

**Issue by champcbg** [Mimetis/Dotmim.Sync#762]
Can I use multiple scopes even I add, remove, and update tables?  or is it just for when adding,removing, columns for the existing table set of the schema from the original scope.

Hope that makes sense.  if not I can explain more.

**Comment by Mimetis** [comment]
You can imagine a lot of scenario with scopes.
Not sure I understood your question, but regarding scopes update, once a scope is created, it's not editable. If u want to modify a scope, create a new one

**Comment by champcbg** [comment]
my question is:

scope_0 = schema:
table 1 - 5 col
table 2 - 5 col
table 3 - 5 col

i execute several EFCore Migrations and now want to provision scope_1 without deprovisions.  Can I do add a new scope:

scope_1 = schema:
table 1 - 6 col
table 2 - 6 col
table 3 - 6 col
table 4 - 6 col
table 5 - 6 col

From your earlier message I think I can do this.  Want to confirm.

I did want to much thinking about trying to have my mobile clients do auto updates.  I realize now that is really not realistic.  Database updates only need to happen when the app is updated.  

Hope this helps

**Comment by Mimetis** [comment]
Yes, this is the goal of multi scopes
