### ISSUE TITLE
JSON type

### ISSUE THREAD

**Issue by tonywarn** [Mimetis/Dotmim.Sync#763]
the Column DATA of type json from provider MySqlSyncProvider, Dotmim.Sync.MySql.MySqlSyncProvider is not currently supported.

Will column type json will be supported?

**Comment by Mimetis** [comment]
Hey @tonywarn 
Nop; the JSON type is not supported because there is no equivalent for clients using SQLite for example
If you are "just" storing json content, without querying it, you can change json to nvarchar maybe ?

**Comment by tonywarn** [comment]
ok, if I clone your project locally and not interested of SQLite what changes would you recomend I make so JSON type is supported?

**Comment by Mimetis** [comment]
You can start from here : https://github.com/Mimetis/Dotmim.Sync/blob/master/Projects/Dotmim.Sync.MySql/Builders/MySqlDbMetadata.cs

Let me know if you are able to make it work, I can probably help you on it

**Comment by Mimetis** [comment]
Actually adding `JSON` to `MySQL `was pretty simple:
- From `MySQL `to `MySQL`; the `JSON `type is replicated
- For other providers, the `JSON `type becomes a `Varchar`

I did it, and you have it in the [last commit](https://github.com/Mimetis/Dotmim.Sync/commit/1279d58dd41bbea169c63f518e5661d1924b344d#diff-46205bef3e09b77851ca57eb943a0317c222b7497c96c00184745e695eb37f79). 
It will be part of the next version, but you can already get the master branch and use it as is.
Let me know if it's working for you

**Comment by tonywarn** [comment]
It worked perfectly, thank you!
