### ISSUE TITLE
Missing dotmim-sync-scope-id in Header

### ISSUE THREAD

**Issue by tonywarn** [Mimetis/Dotmim.Sync#765]
I notice that HttpContext.GetClientScopeId() when using Dotmim.Sync.Web.Server always returned null.
And I located the missing part in here: Dotmim.Sync.Web.Client / HttpRequestHandler.cs  -> SendAsync
So I added this line:
requestMessage.Headers.Add("dotmim-sync-scope-id", context.ClientScopeId.ToString());
And now I getting CLientScopeID as a Guid

**Comment by Mimetis** [comment]
thanks
Do you want to make a quick pr to fix it ?
