### ISSUE TITLE
Scope/setup error when calling agent.SynchronizeAsync(tables) function

### ISSUE THREAD

**Issue by mzeesam** [Mimetis/Dotmim.Sync#767]
Exception: **Seems you are trying another Setup tables that what is stored in your server scope database. Please make a migration or create a new scope**

**Comment by Mimetis** [comment]
Not enough explicit ?

**Comment by flacidsnake** [comment]
Hi @mzeesam 

take a look to #760 

Hope that helps

**Comment by mzeesam** [comment]
Hi @flacidsnake and @Mimetis, 
My scenario is very simple. I am creating a DotNet MAUI app where i first create an SQLite database and would like to sync with my remote SQL server database as highlighted below:
**My model:**
namespace Silva
{
    public class Tree
    {
        [Key]
        public int TreeID { get; set; }
        [Column(TypeName = "nvarchar(150)")]
        public string CommonName { get; set; }
        [Column(TypeName = "nvarchar(150)")]
        public string BotanicalName { get; set; }
        [Column(TypeName = "nvarchar(150)")]
        public string FamilyName { get; set; }
        [Column(TypeName = "nvarchar(MAX)")]
        public string Description { get; set; }
        public int DeviceID { get; set; }
    }
    public class TreeLocations
    {
        [Key]
        public int LocationID { get; set; }
        public string LocationName { get; set; }
        public double Lat { get; set; }
        public double Long { get; set; }
        public int TreeID { get; set; }
    }
}

**My DataContext:**

namespace Silva
{
    public class TreesContext : DbContext
    {
        public DbSet<Tree> Trees { get; set; }  
        public DbSet<TreeLocations> TreeLocations { get; set; }

        public TreesContext()
        {
            SQLitePCL.Batteries_V2.Init();
            this.Database.EnsureCreated();  
            //this.Database.Migrate();

        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            string dbPath = Path.Combine(FileSystem.AppDataDirectory, "treesDB.db3");

            optionsBuilder.UseSqlite($"Filename={dbPath}");
        }
    }
}

**Code for syncing data:**

 public class SyncMaster
    {
        private static string serverConnectionString = $"Data Source=DBserver\\SQLEXPRESS01,1434;Initial Catalog=Silva;Persist Security Info=True;User ID=sa;Password=Password.";

        public static async Task SynchronizeAsync()
        {
            var serverProvider = new SqlSyncProvider(serverConnectionString);

            // Second provider is using plain old Sql Server provider, relying on triggers and tracking tables to create the sync environment
            var clientProvider = new SqliteSyncProvider(Path.Combine(FileSystem.AppDataDirectory, "treesDB.db3"));

            // Tables involved in the sync process:
            var tables = new string[] { "Trees" };

            // Creating an agent that will handle all the process
            var agent = new SyncAgent(clientProvider, serverProvider);

            // Launch the sync process
            var s1 = await agent.SynchronizeAsync(tables);

            // This first sync did not upload the client rows.
            // We only have rows from server that have been downloaded
            // The important step here is to have setup the sync (triggers / tracking tables ...)
            //Console.WriteLine(s1);

            // Now we can "mark" original clients rows as "to be uploaded"
            await agent.LocalOrchestrator.UpdateUntrackedRowsAsync();

            // Then we can make a new synchronize to upload these rows to server
            // Launch the sync process
            var s2 = await agent.SynchronizeAsync();
            //Console.WriteLine(s2);
        }
    }

I have tried to run migration (Add-Migration and Update-Database) on the nuget package manager console before running my app but still gives the same error. 
I have not done any changes to the schema for both server and client. 

**My SQLserver table is as below:**
CREATE TABLE [dbo].[Trees](
	[TreeID] [int] NOT NULL,
	[CommonName] [nvarchar](150) NOT NULL,
	[BotanicalName] [nvarchar](150) NULL,
	[FamilyName] [nvarchar](150) NULL,
	[Description] [nvarchar](max) NULL,
	[DeviceID] [int] NULL,
 CONSTRAINT [PK_Trees] PRIMARY KEY CLUSTERED 
(
	[TreeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

**Comment by Mimetis** [comment]
You have probably made some tests with different tables
That's why you have this error raising.

If you are testing, please start from scratch everytime you are testing something different.

I see you are using `await agent.LocalOrchestrator.UpdateUntrackedRowsAsync();`
Don't use it if you have a sqlite database empty at the begining.
This method is meant to be used **only 1 time**, when you are syncing a client database that has rows **already before** you started your first sync

From what I see from your code, you seem to create the client database, so I guess it's empty.

If you are not sure of what you did so far, delete all the sync metadatas and restart.
You can use this code to remove everything from your client or server side:

``` cs
// Create client provider
var clientProvider = new SqliteSyncProvider(Path.Combine(FileSystem.AppDataDirectory, "treesDB.db3"));
// Create a local orchestrator used to Deprovision everything
var localOrchestrator = new LocalOrchestrator(clientProvider);
// Drop everything
await localOrchestrator.DropAllAsync();

var serverProvider = new SqlSyncProvider(serverConnectionString);
var remoteOrchestrator = new RemoteOrchestrator(clientProvider);
await remoteOrchestrator.DropAllAsync();
```

Once you have dropped everything on both side, you can restart from scratch

**Comment by mzeesam** [comment]
Works like magic!... 
Thanks a lot. Merci @Mimetis

**Comment by Mimetis** [comment]
> Works like magic!... 

I try ;)
