### ISSUE TITLE
Sync conflicts using ClientWins through a webservice has endless loop

### ISSUE THREAD

**Issue by slagtejn** [Mimetis/Dotmim.Sync#775]
Using a conflict resolution of ClientWins through the OnApplyChangesFailed interceptor on a webservice will cause the same record to identify as a conflict many times.  This only happens if there are a large amount of conflicts.  In my scenario 13k conflicts turns into 67k when it's finally done.

How to replicate
1. Use AdventureWorks db, but insert a lot more customer records.  Run the below sql many times.
INSERT INTO [dbo].[Customer]
           ([NameStyle]
           ,[Title]
           ,[FirstName]
           ,[MiddleName]
           ,[LastName]
           ,[Suffix]
           ,[CompanyName]
           ,[SalesPerson]
           ,[EmailAddress]
           ,[Phone]
           ,[PasswordHash]
           ,[PasswordSalt]
           ,[rowguid]
           ,[ModifiedDate])
SELECT [CustomerID]
      ,[NameStyle]
      ,[Title]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[Suffix]
      ,[CompanyName]
      ,[SalesPerson]
      ,[EmailAddress]
      ,[Phone]
      ,[PasswordHash]
      ,[PasswordSalt]
      ,NEWID()
      ,[ModifiedDate]
  FROM [dbo].[Customer]

2. Sync a client with the customer table using a webservice with conflict resolution of ClientWins.  Use the interceptor 'OnApplyChangesFailed' in the SyncController and set acf.Resolution = ConflictResolution.ClientWins
3. Update Customer records on the client & server.  update Customer set CompanyName = CompanyName
4. Sync a client again and there will be conflicts, but it takes forever for them to resolve.
![image](https://user-images.githubusercontent.com/97198525/183781541-c7da31d8-5ce2-41e9-bd5d-bf06af5a26dd.png)

**Comment by Mimetis** [comment]
Hey @slagtejn 

Wow, that's a good catch !
It was really difficult to reproduce, but indeed, when you are making **a lot** of conflicts, you have this weird issue, with a really bad performance at the end, and conflicts applied over and over....

Well, the "**only when a lot of conflicts**" is in fact when you have more than 1 batch file in the process.
If everything fits in 1 single batch file, everything is fine.
But if your sync have 2 or more batch files, the issue happens

It took me a bunch of time to understand that !
I made the correction in the last commit on the master branch.

I've made some improvements as well in the conflict algorithm to prevent unnecessaries requests to be done.
It should work better now, and you should have better performances with this last commit.

Just out of curiosity, if you can do the same test and post the result ? Just curious to see the new "**Total duration**" value.

**Comment by slagtejn** [comment]
ok thanks!  I don't see a commit for this and only see the IsConflictingSetupAsync PR.  Is it within that?

**Comment by Mimetis** [comment]
> @Mimetis ok thanks! I don't see a commit for this and only see the IsConflictingSetupAsync PR. Is it within that?

Yep

**Comment by slagtejn** [comment]
@Mimetis I get the same result as before.  I still don't see a commit where this has been fixed.  Are you sure you pushed all your commits?

**Comment by slagtejn** [comment]
@Mimetis With this change how do to get the original conflict type?  There are scenarios where you want to perform ServerWins or ClientWins based on the type like before.

**Comment by Mimetis** [comment]
args.GetConflict

**Comment by slagtejn** [comment]
@Mimetis That method doesn't exist.

**Comment by Mimetis** [comment]
Sorry, was on the phone, hard to type :D 

``` cs
 agent.RemoteOrchestrator.OnApplyChangesFailed(async args =>
 {
     args.Resolution = ConflictResolution.ClientWins;
     var conflict = await args.GetSyncConflictAsync();
 });

```

**Comment by slagtejn** [comment]
Thanks!  Seemed to work.  Still a little slow, but it's working.

![image](https://user-images.githubusercontent.com/97198525/184009215-1fa20b66-542b-484a-805f-baa921772eab.png)

**Comment by Mimetis** [comment]
Yes, because the conflict resolution is applying an operation (and executing a stored procedure) on each conflict row.

In your example, we made **10207** stored procedures calls to resolve the conflict by applying the client row to the server row.

And if you are calling the `args.GetSyncConflictAsync();` we are doing a Select as well to get the local row and we have another **10207** stored procedures calls. 

**20414** stored procedures calls at the end .... 

I can imagine we may have a better solution, but it will come later, in a further version.
