### ISSUE TITLE
Upgrading from 0.9.4 to 0.9.5 gives SQLite Error 1: 'cannot start a transaction within a transaction'

### ISSUE THREAD

**Issue by bertah** [Mimetis/Dotmim.Sync#784]
First off, thank you for your awesome work on this framework ! Really looking forward for v1.0 :)

I'm having trouble upgrading my provisionned SQLite client database from 0.9.4 to 0.9.5. 

The UpgradeAsync() method keeps throwing the following exception, whether I'm calling it directly, or indirectly via SynchronizeAsync().  The server side (SQLProvider) upgraded without any issues.

```
Dotmim.Sync.SyncException: SQLite Error 1: 'cannot start a transaction within a transaction'. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'cannot start a transaction within a transaction'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Dotmim.Sync.LocalOrchestrator.UpgdrateTo095Async(ClientScopeInfo scopeInfo, SyncContext context, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress1 progress)
   at Dotmim.Sync.LocalOrchestrator.UpgdrateTo095Async(ClientScopeInfo scopeInfo, SyncContext context, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress1 progress)
   at Dotmim.Sync.LocalOrchestrator.InternalUpgradeAsync(List1 clientScopeInfos, SyncContext context, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress1 progress)
   --- End of inner exception stack trace ---
   at Dotmim.Sync.LocalOrchestrator.UpgradeAsync(DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken, IProgress1 progress)
```

Here are steps to reproduce:

```
var tekiServerOrchestrator = new WebRemoteOrchestrator("https://localhost:44362/api/sync/teki");
var tekiClientProvider = new SqliteSyncProvider($"Data Source=\"C:\\temp\\teki.db\";Password=asdf");
var tekiAgent = new SyncAgent(tekiClientProvider, tekiServerOrchestrator, new SyncOptions());

var needToUpgrade = await tekiAgent.LocalOrchestrator.NeedsToUpgradeAsync();

if (needToUpgrade)
    await tekiAgent.LocalOrchestrator.UpgradeAsync();
```

I'm getting the same error in SQL DB Browser, when executing the SQL query found in UpgdrateTo095Async()  (the one that renames and populates the new scope info table).

Any thoughts ?

**Comment by Mimetis** [comment]
Seems `PRAGMA` statement makes the query fails

Can you try this directly in **SQL DB Browser** (assuming your scope table is called `scope_info`) :

``` sql
BEGIN TRANSACTION;
ALTER TABLE [scope_info] RENAME TO old_table_scope_info;
CREATE TABLE [scope_info](
			sync_scope_id blob NOT NULL,
			sync_scope_name text NOT NULL,
			sync_scope_schema text NULL,
			sync_scope_setup text NULL,
			sync_scope_version text NULL,
			scope_last_server_sync_timestamp integer NULL,
			scope_last_sync_timestamp integer NULL,
			scope_last_sync_duration integer NULL,
			scope_last_sync datetime NULL,
			CONSTRAINT PK_scope_info PRIMARY KEY(sync_scope_id, sync_scope_name));

INSERT INTO [scope_info] SELECT * FROM old_table_scope_info;
DROP TABLE old_table_scope_info;

UPDATE [scope_info] SET [sync_scope_version] = '0.9.5'
COMMIT;
```

Let me know

**Comment by bertah** [comment]
Good catch. The `PRAGMA` statement seems to be issue.

The query you supplied passed successfully in SQL DB Browser, and the scope_info table was correctly updated.

**Comment by MaTToX3** [comment]
Is it possible to publish a new version of Nuget package that contains that fix?

**Comment by Mimetis** [comment]
I think you should look at the last version https://github.com/Mimetis/Dotmim.Sync/discussions/802

**Comment by MaTToX3** [comment]
Thank you for your reply! 

I did check the 0.9.6 version but it seems a major upgrade from 0.9.5 and not production ready so I would rather not upgrade just yet. Would you recommend skipping the 0.9.5 version and going directly to 0.9.6 or we rather stay on 0.9.4 for now? It's a production app.

**Comment by Mimetis** [comment]
Yes, I think 0.9.7 pre-release (the release version will come later this week or next week, with some minors changes) is worth it.
Especially as it's a major upgrade, and will be probably the **V1.0** version.

Be careful on the Upgrade, please read carefully the upgrade path, especially if you are using filters.
Test it before, and be sure you do not have any issues during upgrade
