### ISSUE TITLE
Microsoft.Data.Sqlite

### ISSUE THREAD

**Issue by talley** [Mimetis/Dotmim.Sync#787]
Remove Microsoft.Data.Sqlite dependency from DotMim.Sync.Sqlite and use sqlite-net-pcl instead.
There are issues with Microsoft.Data.Sqlite

**Comment by Mimetis** [comment]
Sqlite pcl is not an ADO provider.
Whaemt are the issues you are facing with Microsoft Data Sqlite ?
By the way,  DMS is using it internally,  but you still can use Sqlite-net in your application...

**Comment by talley** [comment]
Dotmim.Sync.SyncException: 'The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.'
"   at Dotmim.Sync.SyncAgent.<SynchronizeAsync>d__27.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at Dotmim.Syn.Demo.Form1.<SyncTables>d__2.MoveNext() in C:\\Apps\\Deskop\\hrexpress\\src\\desktop\\HRExpressSolutions\\Dotmim.Syn.Demo\\Form1.cs:line 47"

**Comment by Mimetis** [comment]
Can you share your code and the framework you are using ?
Looking at the class `Form1.cs `, you are testing in a `Windows Forms` project ?
Is it an old `Windows Forms` project or are you using the new version of `Windows Forms` ?
