### ISSUE TITLE
Deprovison SQL Server with DMS 0.91 using DMS 0.95

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#798]
We use DMS 0.95 with SQL Server change tracking on the server via https.

We have customer databases provisioned using DMS 0.91. We need to deprovision the customer databases by using  DMS 0.95.

On the server
```
WebServerAgent webServerAgent = webServerAgents.FirstOrDefault();

webServerAgent.Provider.ConnectionString = databaseHelper.DatabaseConnection(databaseName);
SyncProvision syncProvison = SyncProvision.ServerScope
        | SyncProvision.ServerHistoryScope
        | SyncProvision.StoredProcedures
        | SyncProvision.TrackingTable
        | SyncProvision.Triggers;
try
{
    await webServerAgent.RemoteOrchestrator.DeprovisionAsync(syncProvison);
}
catch (Exception ex)
{
}
```
`NullReferenceException` is thrown at `await webServerAgent.RemoteOrchestrator.DeprovisionAsync(syncProvison)`;

I can't see what might be null. `webServerAgent` looks like this
![image](https://user-images.githubusercontent.com/17174099/187065714-5ba4b6eb-4ec3-4e26-b8f7-4414d9d7d8a7.png)

Is it possible to deprovision a database provisioned with an earlier version of DMS or should I just delete DMS stuff on the server using TSQL?

**Comment by Mimetis** [comment]
Never tested this scénario. 

Try DropAllAsync ?

**Comment by Mimetis** [comment]
And Maybe try to Upgrade server to 0.95 before Deprovision.
Or Just remove everything manually

**Comment by VagueGit** [comment]
This worked
```
await webServerAgent.RemoteOrchestrator.UpgradeAsync();
await webServerAgent.RemoteOrchestrator.DropAllAsync();
```
Thanks for your help.
