### ISSUE TITLE
Syncing error that only occurs sometimes 

### ISSUE THREAD

**Issue by JoeMurrayH** [Mimetis/Dotmim.Sync#800]
Below is the error that is getting returned by the dot mim sync server it will happen for about a day then resolve itself afterward and return in a few weeks. and was wondering if anyone has any idea of what would cause it.

Some background on the current implementation.
There is a back-end SQL server database that is the sync master with multiple stores data in it every store only pulls data from this they never upload data each store could have multiple different clients pulling down the same data.

The sync master gets updated by triggers from the main master DB that stores the front-end website data so changes on the website would cause a trigger to update the sync master DB at the same time which would then sync down to the appropriate store using filters.

"Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct"

This error affects all stores that sync with that server

We are using version 0.5.7

**Comment by Mimetis** [comment]
Hello @JoeMurrayH

You are using a really old version of `DMS`
I apologize but I really don't know what kind of error it is, and how to debug it.
Maybe with more details from your side would help a little bit ?

**Comment by JoeMurrayH** [comment]
That's no problem because it is so infrequent I have had a hard time debugging it myself.
I was able to catch it last time and it was part of the below result when it attempted to sync.

{StatusCode: 400, ReasonPhrase: '', Version: 2.0, Content: System.Net.Http.StreamContent, Headers:
{
  dotmim-sync-error: InvalidOperationException
  Server: Microsoft-IIS/10.0
  Date: Wed, 31 Aug 2022 07:52:30 GMT
  X-Powered-By: ASP.NET
  Content-Length: 283
}}

I have never been able to recreate it locally, only seen it on the live server I will see if we can arrange to upgrade to the latest version and watch for it.

**Comment by Mimetis** [comment]
If you are upgrading to last version, please wait the new release `v0.9.6` that is a major one.
Unfortunately, since you are using a really old version, I'm not sure you will be able to easily upgrade your setup
