### ISSUE TITLE
Provision local database using DMS 0.96beta

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#806]
Using DMS 0.91 in production, when a customer installs our app on a new device, we sync from their remote database one table at a time. We use a distinct scope for each table. This saves maintaining snapshots on the server.

Once the local db is populated we provision a sync scope 'All' that includes all tables like this
```
SyncAgent syncAgent = ConfigureSyncAgent();
SyncSet syncSet = await syncAgent.RemoteOrchestrator.GetSchemaAsync();
await syncAgent.LocalOrchestrator.ProvisionAsync(syncSet, SyncProvision.StoredProcedures | SyncProvision.Triggers | SyncProvision.TrackingTable); 
```
We then update sync scope 'All' scope_last_server_sync_timestamp and scope_last_sync_timestamp with a SQL update query. From then on, sync scope 'All' only syncs subsequent changes. The individual table scopes are not used again. This works well.

Playing with DMS 0.96beta, I can't see how to provision the local sync scope 'All'.
`Task<ServerScopeInfo> thing = syncAgent.RemoteOrchestrator.GetServerScopeInfoAsync();`
returns this
![image](https://user-images.githubusercontent.com/17174099/188787439-995b4022-eedd-4b4f-a3fc-4034e3489651.png)

**EDIT:** How do we provision a local scope using DMS 0.96 without syncing first, and **without provisioning** the (https) server?

**Comment by Mimetis** [comment]
To get the scope from server, server should be provisioned first.
You forgot also to mention the **scopename** `All` when requesting a `ScopeInfo` instance from server
Be careful, as we have **scope_infos** table on both side, **that are identical**, there is no more "`ServerScopeInfo`" or "`ClientScopeInfo`" now in 0.9.6, but only `ScopeInfo`

```cs
var agent = new SyncAgent(clientProvider, serverProvider);

var r = await agent.SynchronizeAsync("All", setup);
Console.WriteLine(r);

var sScopeInfo = await agent.RemoteOrchestrator.GetScopeInfoAsync("All");
Console.WriteLine(sScopeInfo);
```

If you want to update last timestamp, you now have to do it with `ScopeInfoClient`, not in `ScopeInfo` anymore:

> EDIT: How do we provision a local scope using DMS 0.96 without syncing first, and without provisioning the (https) server?

I don't understand: If server is not provisioned, it will not work even you successfully provisioned client side

That's being said, you can provision a local database, if your database has an existing schema (tables) without requiring to get the `ScopeInfo` from server side

``` cs
var localOrchestrator = new LocalOrchestrator(clientProvider);

var schema = await localOrchestrator.GetSchemaAsync(setup);

var scopeInfo = new ScopeInfo
{
    Name = "All",
    Schema = schema,
    Setup = setup,
    Version = SyncVersion.Current.ToString()
};

await localOrchestrator.ProvisionAsync(scopeInfo);
```

**Comment by VagueGit** [comment]
I can get the scopeinfo if I provision the server first, but we don't have to provision the server first using DMS0.91. It takes longer to get the new machine operational if we have to provision the server first. It's a better user experience if we get the data down so they can start work and have the local machine provisioned ready to provision the server when the user next syncs.

Am I making sense?

**Comment by Mimetis** [comment]
> Am I making sense?
Probably ;)

**Comment by VagueGit** [comment]
We have synced to a new local db one table at a time. We now provision the local db like this
```
SqliteSyncProvider clientProvider = GetSqliteSyncProvider();
LocalOrchestrator localOrchestrator = new LocalOrchestrator(clientProvider);
SyncSetup syncSetup = new SyncScopes().GetSyncSetup("All");
SyncSet syncSet = await localOrchestrator.GetSchemaAsync(syncSetup);

ScopeInfo scopeInfo = new ScopeInfo
{
    Name = "All",
    Schema = syncSet,
    Setup = syncSetup,
    Version = SyncVersion.Current.ToString()
};
await localOrchestrator.ProvisionAsync(scopeInfo);
```
We know the local db is uptodate. How do we mark the new scope "All" as uptodate without having to sync "All"?

**Comment by Mimetis** [comment]
Here is a full example on how I would do it:

``` cs
var serverProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(serverDbName));
var clientProvider = new SqlSyncProvider(DBHelper.GetDatabaseConnectionString(clientDbName));

var setupProductCategory = new SyncSetup("ProductCategory");
var setupProduct = new SyncSetup("Product");
var setupAll = new SyncSetup("ProductCategory", "Product");

var agent = new SyncAgent(clientProvider, serverProvider);

var rProductCategory = await agent.SynchronizeAsync("sProductCategory", setupProductCategory);
Console.WriteLine(rProductCategory);

var rProduct = await agent.SynchronizeAsync("sProduct", setupProduct);
Console.WriteLine(rProduct);

// SERVER SIDE: Provision All scope
// --------------------------------------
await agent.RemoteOrchestrator.ProvisionAsync("ALL", setupAll);

// CLIENT SIDE: Create a local scope for all tables
// --------------------------------------
SyncSet syncSetAll = await agent.LocalOrchestrator.GetSchemaAsync(setupAll);

ScopeInfo cScopeInfo = new ScopeInfo
{
    Name = "All",
    Schema = syncSetAll,
    Setup = setupAll,
    Version = SyncVersion.Current.ToString()
};
await agent.LocalOrchestrator.ProvisionAsync(cScopeInfo);

// Get all scope info clients to get minimum Timestamp
// --------------------------------------
var cAllScopeInfoClients = await agent.LocalOrchestrator.GetAllScopeInfoClientsAsync();

var minServerTimeStamp = cAllScopeInfoClients.Min(sic => sic.LastServerSyncTimestamp);
var minClientTimeStamp = cAllScopeInfoClients.Min(sic => sic.LastSyncTimestamp);
var minLastSync = cAllScopeInfoClients.Min(sic => sic.LastSync);

// Get (and create) the scope info client for scope ALL
// --------------------------------------
var cScopeInfoClient = await agent.LocalOrchestrator.GetScopeInfoClientAsync("All");

if (cScopeInfoClient.IsNewScope)
{
    cScopeInfoClient.IsNewScope = false;
    cScopeInfoClient.LastSync = minLastSync;
    cScopeInfoClient.LastSyncTimestamp = minServerTimeStamp;
    cScopeInfoClient.LastServerSyncTimestamp = minClientTimeStamp;
    await agent.LocalOrchestrator.SaveScopeInfoClientAsync(cScopeInfoClient);
}

// SERVER SIDE: Add a product category to see if the line is correctly downloaded
// --------------------------------------
await DBHelper.AddProductCategoryRowAsync(serverProvider);


// --------------------------------------
var rAll = await agent.SynchronizeAsync("All");
Console.WriteLine(rAll);

```

![image](https://user-images.githubusercontent.com/4592555/189383092-a1f5530f-de57-4d8f-84db-950fdf206a6f.png)

**Comment by Mimetis** [comment]
Editing the code in the previous comment, as it was incorrect
