### ISSUE TITLE
DMS0.96 smallint is not currently supported

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#809]
DMS0.91 is able to sync smallint. DMS0.96 throws this exception
`Dotmim.Sync.SyncException: 'In table Expenses, the Column ExpenseFrequency of type smallint from provider SqliteSyncProvider, Dotmim.Sync.Sqlite.SqliteSyncProvider is not currently supported.`'

**Comment by Mimetis** [comment]
I don't get it.

`DMS` never generates a **SQLite** database with a type "`smallint`".
**SQLite** numeric values are generated with type "`integer`"

Here is a SQL Server database used as server side:

![image](https://user-images.githubusercontent.com/4592555/189359033-305044f5-f8a7-469a-82b6-fd14db701f6e.png)

And here the SQLite database once DMS has made a first sync:

![image](https://user-images.githubusercontent.com/4592555/189359141-22288147-538f-4ff9-a290-71b443414ef9.png)


Are you creating the SQLite database before making a first sync ? (Or do you let DMS does it for you ?)
If yes, consider changing your script from `smallint` to `integer`

By the way, the allowed type for SQLite are:

``` cs
    return typeName switch
    {
        "integer" or "float" or "decimal" or "bit" or "bigint" or "numeric" or "blob" or "image" or
        "datetime" or "time" or "text" or "varchar" or "real" => true,
        _ => false,
    };
```

**Comment by VagueGit** [comment]
We generate the SQLite db before the first sync. This is the script
```
CREATE TABLE [Expenses] (
	"ItemCode"		varchar(15) NOT NULL COLLATE NOCASE CHECK (length(ItemCode) <= 15),
	"ItemCost"		numeric NOT NULL CHECK (ItemCost BETWEEN -9999998.99 AND 9999999.99),
	"ExpenseFrequency"		smallint NOT NULL CHECK (ExpenseFrequency BETWEEN 0 AND 255),
	"ExpenseAllocation"		smallint NOT NULL CHECK (ExpenseAllocation BETWEEN 0 AND 255),
    PRIMARY KEY ([ItemCode])
);
```
I know SQLite plays fast and loose with types, but DMS0.91 doesn't throw for the smallint datatype.

**Comment by Mimetis** [comment]
That's weird, because it should have throw an exception, since I'm sure we never had `Smallint` in the `SqliteSyncProvider` ...

I've added the "`smallint`" in **SQLite**, especially for you ;)

You can try it on the **HandlingErrors** branch

**Comment by VagueGit** [comment]
That's much appreciated. We use a db creation script that takes advantage of SQLite type affinity to try to provide additional clues to the range of values expected for a column. Funny how DMS0.91 didn't seem to mind smallint ...

**Comment by VagueGit** [comment]
Actually the issue is not with the datatype with sync. smallint syncs up and it syncs down. This is without using the HandlingErrors branch. The error is thrown at
` SyncSet syncSet = await localOrchestrator.GetSchemaAsync(syncSetup);`

So the issue appears to be specific to GetSchemaAsync. I drilled down to `Dotmim.Sync.SyncColumn` maybe `CoerceDbType()`?

Imagine the mayhem unleashed if I were to submit a PR? <shudder>

**Comment by Mimetis** [comment]
Try with the beta of `0.9.7` and let me know if it's working

**Comment by VagueGit** [comment]
I can't see a DMS 0.9.7 nuget pre-release

**Comment by VagueGit** [comment]
Got it and it works thank you.

but now we get
`nvarchar(250) from provider SqliteSyncProvider, Dotmim.Sync.Sqlite.SqliteSyncProvider is not currently supported`

I'll close this as fixed but maybe broad support for SQLite type affinities might make DMS adoption easier for those with existing SQLite schemas.
