### ISSUE TITLE
Filter - only one sync filter per table supported?

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#81]
Hi!

In my sync scenario, I need to pass two filters to the select_changes stored procedure:
one denotes the tenant (tenantid), and one the current user (userId)

I noticed, that when I add the second column (userId) as filter, dotmim.sync does not create any tracking tables, procedures or whatever and just fails silently.

Now initially I was thinking that the problem is, that the second colum (userid) actually does not exist on the table, that it filters.

However, when I added the *userid* column to the table, just to try it out, still no tracking tables, procedures, ... were created by dotmim.sync

So what I guess is, that currently only one filter value is supported.
Is that correct?

Because if so, this is a major show stopper for us => we'd need to implement it.

**Comment by Mimetis** [comment]
Thx for feedback.
I never tried to make a multi filters scenario.
Let me think about it, and I will go back to you once I have made some tests

**Comment by gentledepp** [comment]
I am taking over now.
What I do not understand, is why you create two distinct selectChanges stored procedures

- one with the default name
- one with the filter name included and also the filter parameter

Whenever you *do* want to apply a filter in the sync process, you must always sync with that filter. Otherwise you will get all the other rows that you don't like and they stay on your client device, even if you start to use the filters again.
So honestly: I do not get why you do that.

I was expecting there was always only one selectChanges stored procedure - either with or without filter(s) (just as specified by the application developer)

**Comment by gentledepp** [comment]
@Mimetis 
I am currently implementing this. PR will follow shortly.
Could you please elaborate on the following details:

1) why are there multiple selectchanges stored procedures (filtered and unfiltered) - I guess you want to let the apps decide whether to filter or not?
2) Could you explain, how exactly the select changes stored procedure works?
  - Why are the filters also maintained in the tracking tables?
  - I created some test "SyncFilterMultipleFilters" where I copy your original SyncFilterTests and add an additional filter (StatusValue) into the mix. The stored procedure I come up with then looks like the following:

        CREATE PROCEDURE [dbo].[ServiceTickets_CustomerIDStatusValue__selectchanges]
        	@sync_min_timestamp bigint,
        	@sync_scope_id uniqueidentifier,
        	@sync_scope_is_new bit,
        	@sync_scope_is_reinit bit,
        	@CustomerID int,
        	@StatusValue int
        AS
        BEGIN
        SELECT 	[side].[ServiceTicketID], 
        	[base].[Title], 
        	[base].[Description], 
        	[base].[StatusValue], 
        	[base].[EscalationLevel], 
        	[base].[Opened], 
        	[base].[Closed], 
        	[base].[CustomerID], 
        	[side].[sync_row_is_tombstone], 
        	[side].[create_scope_id], 
        	[side].[create_timestamp], 
        	[side].[update_scope_id], 
        	[side].[update_timestamp] 
        FROM [ServiceTickets] [base]
        RIGHT JOIN [ServiceTickets_tracking] [side]
        ON [base].[ServiceTicketID] = [side].[ServiceTicketID]
        WHERE (
        	([side].[CustomerID] = @CustomerID AND [side].[StatusValue] = @StatusValue)
        	OR (([side].[update_scope_id] = @sync_scope_id or [side].[update_scope_id] IS NULL)
        		AND ([side].[CustomerID] IS NULL OR [side].[StatusValue] IS NULL))
        	)
        AND (
        	-- Update made by the local instance
        	[side].[update_scope_id] IS NULL
        	-- Or Update different from remote
        	OR [side].[update_scope_id] <> @sync_scope_id
        	-- Or we are in reinit mode so we take rows even thoses updated by the scope
        	OR @sync_scope_is_reinit = 1
            )
        AND (
        	-- And Timestamp is > from remote timestamp
        	[side].[timestamp] > @sync_min_timestamp
        	OR
        	-- remote instance is new, so we don't take the last timestamp
        	@sync_scope_is_new = 1
        	)
        AND (
        	[side].[sync_row_is_tombstone] = 1 
        	OR
        	([side].[sync_row_is_tombstone] = 0 AND [base].[ServiceTicketID] is not null	)
        )
        
        END

-> is that correct in your opinion?

**Comment by Mimetis** [comment]
- 1 Because we need a `selectchanges` for the `scope` where there is no filter and we need a `selectchanges` for the `scope` with parameters
- 2 Well it's a little bit complicated :)

First of all `@sync_scope_id` is always the scope where we need the changes.

```
	-- Update made by the local instance
	[side].[update_scope_id] IS NULL
	-- Or Update different from remote
	OR [side].[update_scope_id] <> @sync_scope_id
	-- Or we are in reinit mode so we take rows even thoses updated by the scope
	OR @sync_scope_is_reinit = 1

```
- When a row is updated on any local instance, the `update_scope_id` is always `null`. That's why we get all the rows that have been updated by the local instance
- Or we take all the rows edited by any other scopes
- Or we are in a `reinit` mode so we take the row even the row has been already updated

```
AND (
	-- And Timestamp is > from remote timestamp
	[side].[timestamp] > @sync_min_timestamp
	OR
	-- remote instance is new, so we don't take the last timestamp
	@sync_scope_is_new = 1
	)

```
Check the row has been updated **after** the last sync.   
If we are in a new process (first sync) we get the row (the `@sync_min_timestamp` is null, if I remember well)

```
AND (
	[side].[sync_row_is_tombstone] = 1 
	OR
	([side].[sync_row_is_tombstone] = 0 AND [base].[ServiceTicketID] is not null	)
)
```
Getting the row that are deleted OR getting the row that has no tracking changes (useful when you start a new sync on an existing database)

```
WHERE (
	([side].[CustomerID] = @CustomerID AND [side].[StatusValue] = @StatusValue)
	OR (([side].[update_scope_id] = @sync_scope_id or [side].[update_scope_id] IS NULL)
		AND ([side].[CustomerID] IS NULL OR [side].[StatusValue] IS NULL))
	)
```

Filter clause. But something is hurting me. I'm not on my dev machine right now, so I will update this post with more informations (not sure on `[side].[update_scope_id] = @sync_scope_id or [side].[update_scope_id] IS NULL`)

Make sense ?

**Comment by gentledepp** [comment]
And an **important question**
What actually is a **scope**? 

Is it the *unique identity* of a sync participant (client or server).
i.e. - If a server S and clients C1 and C2 are participating in a sync process, S,C1,C2 are three distinct scopes. 
But within each of those scopes, they represent the *local* scope by storing `NULL` as scopeid. (So C1 and C2 do store the scope id S of the server, but within the servers database, all its locally made changes are stored as `scopeId = NULL`

Did I understand that correctly?

**Comment by gentledepp** [comment]
> 1 Because we need a selectchanges for the scope where there is no filter and we need a selectchanges for the scope with parameters

.. but why then use these complicated naming schemes (concatenating the parameter names) when there will always be a maximum of two stored procedures?
Why not just call them:
*<TABLENAME>*_selectchanges
*<TABLENAME>*_selectchanges_filtered
?

**Comment by gentledepp** [comment]
Ok I see your intention now - I was just confused as this was not supported by *the old sync framework* ;-)

**Comment by gentledepp** [comment]
but back to my previous question:
**what actually is a scope**? 
(Did I guess the answer right?)

**Comment by Mimetis** [comment]
Just updated my answer, you're too quick ;)

**Comment by gentledepp** [comment]
sorry - we are quite pressed for time at the moment :-|

**Comment by Mimetis** [comment]
Closing this issue since PR is actually in progress

**Comment by Mimetis** [comment]
See #97
