### ISSUE TITLE
Not synchronising local changes to web

### ISSUE THREAD

**Issue by spj-uk** [Mimetis/Dotmim.Sync#813]
I am using the WebClientOrchestrator to sync from an 'offline' SQLite DB to a SQL Server however local changes are not being synchronised. 

``` cs
var authenticationBytes = Encoding.ASCII.GetBytes($"{mdlPlugin.Username}:{mdlPlugin.Password}");
HttpClient httpClient = new HttpClient();
httpClient.DefaultRequestHeaders.Authorization = 
   new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(authenticationBytes));

Uri uri = new Uri(mdlPlugin.WebApiUrl + "inc" + $"?name={Name}");
string localPath = System.IO.Path.Combine(FilePath, $"{Name}.inc");

var proxyClientProvider = new WebClientOrchestrator(uri.ToString(), client: httpClient);
proxyClientProvider.HttpClient.Timeout = TimeSpan.FromMinutes(20);

var clientProvider = new SqliteSyncProvider($"Data Source={localPath};Password={Password};");                   

var setup_tables = new SyncSetup(tables.ToList()) { };                

var progress = new SynchronousProgress<ProgressArgs>(s 
    => UpdateInt(s.Message, s.Context.SyncStage, s.ProgressPercentage));

SetStatus("In Progress", Color.Black);                   

var agent = new SyncAgent(clientProvider, proxyClientProvider, setup_tables);

var localOrchestrator = agent.LocalOrchestrator;
var remoteOrchestrator = agent.RemoteOrchestrator;                                                

var s1 = await agent.SynchronizeAsync(progress);                   
await localOrchestrator.UpdateUntrackedRowsAsync();

s1 = await agent.SynchronizeAsync(progress);            
SetStatus(s1.ToString(), Color.Black);
```

I must be missing something simple.

**Comment by Mimetis** [comment]
Hi @spj-uk 

> **Note**: I've edited your post to make it readable. **Please use correctly Markdown style**. I spent too much time editing posts.. 

If you are using `await localOrchestrator.UpdateUntrackedRowsAsync();`, I guess you have an existing client database before making a first sync ?

First of all, please note that `UpdateUntrackedRowsAsync()` should be used **only the first time** you are creating your synchronization mechanism.

Once it's done and you have upload these first records, you don't need to do it all the time.

First question so far, do you have any errors raised if you encapsulate in a try catch ?

``` cs
try
{
 await localOrchestrator.UpdateUntrackedRowsAsync();
}
catch (Exception ex)
{
 Debug.WriteLine(ex.Message);
}
```

**Comment by spj-uk** [comment]
Apologies on the code formatting. 

I do have an existing client database. I make some changes 'offline' and then go 'online' which runs the sync process. I added a try...catch around the UpdateUntrackedRowsAsync and did not get any errors.

**Comment by Mimetis** [comment]
I need more info, maybe a sample reproduction sample, to be able to reproduce and help you.

**Comment by Mimetis** [comment]
Any relevant info so far ?

**Comment by spj-uk** [comment]
Apologies for the delay. Not been able to make a sample yet.
I did notice the line "Sending All Changes. Rows: 1041. Waiting Server Response...."
The next line is then "Downloaded Batch Changes (1/1). Rows (0/0)"

Did it fail to send?

**Comment by Mimetis** [comment]
dont think so
Seems you were able to send the batch to the server, and server did not send any rows to apply locally

**Comment by spj-uk** [comment]
Have a sample winforms project - how can I get it to you?

**Comment by Mimetis** [comment]
Create a github repository, will be easier to clone and run locally (with a readme to explain
