### ISSUE TITLE
MSSQL - triggers use "GetDate()" instead of "GetUtcDate()" => BUG?

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#82]
Hi!
When looking at the triggers that manage the tracking table, I noticed, that they use "GetDate()" instead of "GetUtcDate()".

I just wonder if that is intended or a bug.

Sorry for this question, but I am not as deep in the technical details as you are @Mimetis , and I need to make sure that everything works as it should. :-|

**Comment by Mimetis** [comment]
Hum... good question !!
Actually, the date registered in the tracking table called `[last_change_datetime]` is **NOT** used to make a comparison beetween a client and the server.
It's typically informational. 
The information used to make the comparison are timestamp ( `[create_timestamp]`, `[update_timestamp]` and `[timestamp]`) , and they are managed by SQL Server itself :)

**Comment by Mimetis** [comment]
Yes, It could be a problem, let's fix it :)

**Comment by Mimetis** [comment]
Done, in the last commit https://github.com/Mimetis/Dotmim.Sync/commit/6d0f79101b34e3f0c9239d020f04b947fa43535a

Let me know if everything works as expected
