### ISSUE TITLE
Sql Server synchronization problems Sql Server Version Dotmin 0.97 

### ISSUE THREAD

**Issue by kanasg32** [Mimetis/Dotmim.Sync#824]
**My scenario is as follows**, My main server is an ApiWeb with Sql server, The api is in .Net 6 with the CQRS pattern, so the services are not in the program.cs
to start dotmin here is the code 

            services.AddDistributedMemoryCache();
            services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));
            var options = new SyncOptions
            {
                BatchSize = 1000
            };

            var tables = new string[] { "AVProductosSyncWeb", "AVFacturasSyncWeb", "AVItemsFacturaSyncWeb", "AVCxCSyncWeb", 
                                                      "AVClientesSyncWeb", "AVUsuariosSyncWeb", "AVCorrelativosSyncWeb", "AVVendedoresSyncWeb" };
           services.AddSyncServer<SqlSyncProvider>(configuration.GetConnectionString("DefaultConnection"),  tables, options);

**client side**, windows form .net 6 application sql server database provider the code is as follows

                var serverOrchestrator = new WebRemoteOrchestrator(serverConnectionString);
                var clientProvider = new SqlSyncProvider(clientConnectionString);
                var options = new SyncOptions
                {
                    BatchSize = 1000
                };
                var agent = new SyncAgent(clientProvider, serverOrchestrator,options);
                try
                {
                    var progress = new SynchronousProgress<ProgressArgs>(prog => datosSync($ {prog.ProgressPercentage:p}:\t{prog.Message}\r\n "));
                    var s1 = agent.SynchronizeAsync(progress);
                    _dataTask = s1;
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }

**### on the server side the tables are created, scope_info, scope_info_client**, the tracking tables are created as well as the triggers and stored procedures.

**### on the client side, it also creates the tables scope_info, scope_info_client,** but in this case it does not create the triggers nor the trace tables, nor does it create the stored procedures.

**in the client this is the message that it processes**

 0.00 %: [AvatarAdminDBCoreTest] Session Begins. Id:eac7d6c2-dcb6-4765-b802-ef4dbc98f656. Scope name:DefaultScope.
 100.00 %: [AvatarAdminDBCoreTest] Session Ends. Id:eac7d6c2-dcb6-4765-b802-ef4dbc98f656. Scope name:DefaultScope.

Thank you very much in advance for the support you can give me.

**Comment by Mimetis** [comment]
are you able to reach the web api url correctly ? 

![image](https://user-images.githubusercontent.com/4592555/192843350-80135ee0-4018-442f-838b-a5a112ecf506.png)

you forgot the `await` keyword here : `var s1 = agent.SynchronizeAsync(progress);`

**Comment by kanasg32** [comment]
**### The detail of placing the await in** var s1 = await agent.SynchronizeAsync(progress); allowed me to catch the error, I had not realized it was not working.

**### here is the corrected code**
                 try
                {
                  var progress = new SynchronousProgress<ProgressArgs>(prog => datosSync($" 
                     {prog.ProgressPercentage:p}:\t{prog.Message}\r\n "));
                    var s1 = await agent.SynchronizeAsync(progress);
                    _dataTask = s1;
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }


### **Now, what is the mistake?**  
**Answer:** the error catcher told me that there was no UserId column in the AVUsuariosSyncWeb_bulkupdate stored procedure but my model does not contain any property with that identifier.

**here the model**

 [Table("AVUsuariosSyncWeb")]
    public class UsuarioSyncWeb
    {
        public int UsuarioSyncWebId { get; set; }

        [MaxLength(13)]
        public string? Codigo { get; set; }
        [MaxLength(120)]
        public string? Descripcion { get; set; }
        public string? Email { get; set; }
        public string? Rol { get; set; }
        public string? Password { get; set; }
    }

for some reason when creating the stored procedures, a UserId was added that is not part of the model, and this does not allow the client to synchronize correctly.  

**when I remove that table from my synchronization, everything starts to work correctly.**

I remain attentive to your comment  @Mimetis  clearly I am not using the standart, because the name and properties of my class are in spanish, is it possible that this error occurs when trying to generate the stored procedures?

![github4](https://user-images.githubusercontent.com/5733541/192869911-eb9d2e5d-bc3f-476a-9145-2c6eb539a476.png)

**Thank you for your support** 👍

**Comment by Mimetis** [comment]
Server database is empty ? 
Do you have rows on client before making the first sync ? (if yes see [UpdateUntrackedRowsAsync](https://dotmimsync.readthedocs.io/AlreadyExisting.html?highlight=UpdateUntrackedRowsAsync))

**Comment by kanasg32** [comment]
If the databases are clean on both sides, I have deleted and completely removed the databases and recreated, I am using the code first approach, as soon as I place that table with the described model it throws the error.

The automatic generation of the stored procedures for this model AVUsersSyncWeb, will generate the error,

here the model so you can verify in your environment.

 public class UsuarioSyncWeb
    {
        public int UsuarioSyncWebId { get; set; }

        [MaxLength(13)]
        public string? Codigo { get; set; }
        [MaxLength(120)]
        public string? Descripcion { get; set; }
        public string? Email { get; set; }
        public string? Rol { get; set; }
        public string? Password { get; set; }
    }


attached image for graphic comprehension
I attach the image for graphic understanding

**### error capture** 

![github6](https://user-images.githubusercontent.com/5733541/192890046-150328fe-d210-406f-8859-d37db6965f55.png)

**### UserId(does not exist in the model) field added to the stored procedure**

![github7](https://user-images.githubusercontent.com/5733541/192890161-cad13c6f-194a-4ea8-9d64-695d11d7f44d.png)

**### The model**

![github8](https://user-images.githubusercontent.com/5733541/192890360-2fdb26f1-5d0a-4c0f-9d25-96f8363e8704.png)

**Comment by Mimetis** [comment]
can you show me the table itself from the database ?
need to see the schema, to check if there is a Userid somewhere

**Comment by kanasg32** [comment]
my friend @Mimetis  you are right, there is a UserId but it is a foreign key, the synchronization users are linked to a user of the Identity User of the Net Core. attached images, the detail is that the IdentityUser users should not synchronize for any reason.

![github11](https://user-images.githubusercontent.com/5733541/192910197-84455f32-ce83-4ef7-a464-74101118e9d6.png)

![github10](https://user-images.githubusercontent.com/5733541/192910216-60146b42-9c74-4c53-abe9-6dce413089e1.png)

![github9](https://user-images.githubusercontent.com/5733541/192910229-8218d359-ccfc-4dfd-87d2-5265e2d8a863.png)

**Comment by Mimetis** [comment]
Are you specifying the columns to sync in your sync code, for the  `AVUsuariosSyncWeb` table ? 
Did you try to add the UserId property in your `UsuarioSyncWeb` class ?

**Comment by kanasg32** [comment]
greetings, I was able to identify in more detail the problem, I think it is a bad design in the User model and the UserSyncWeb model.
originally look like this

     public class UsuarioSyncWeb
    {
        public int UsuarioSyncWebId { get; set; }
        public string? Codigo { get; set; }
        public string? Descripcion { get; set; }
        public string? Email { get; set; }
        public string? Rol { get; set; }
        public string? Password { get; set; }
    }

      public class User : IdentityUser
    {
        public string? NickName { get; set; }
        public int UsuarioSyncWebId { get; set; }
        public UserType UserType { get; set; }
        public virtual ICollection<UsuarioSyncWeb> AVUsuariosSyncWeb { get; set; }
    }

**### the detail of the User class is that it makes reference to a collection of users and the int UserSyncWebId is mandatory, I think it is for this reason that it creates a foreign key in the table UserSyncWeb referring to UserId for this to happen it is not necessary to have that property in the UserSyncWeb model.**

**### I made the change to the User model and it looks like this**

 public class User : IdentityUser
    {
        public string? NickName { get; set; }
        public int? UsuarioSyncWebId { get; set; }
        public UserType UserType { get; set; }
        public virtual UsuarioSyncWeb AVUsuariosSyncWeb { get; set; }
    }

**### the UserSyncWebId is not mandatory and I don't define the relationship with UserSyncWeb as a collection, now I define it as
public virtual UserSyncWeb AVUsersSyncWeb { get; set; }**

this way I included the table for synchronization and everything is working fine.


var tables = new string[] { "AVProductosSyncWeb", "AVFacturasSyncWeb", "AVItemsFacturaSyncWeb", "AVCxCSyncWeb", 
                "AVClientesSyncWeb",  "AVCorrelativosSyncWeb", "AVVendedoresSyncWeb", "AVUsuariosSyncWeb" };

           services.AddSyncServer<SqlSyncProvider>(configuration.GetConnectionString("DefaultConnection"),  tables, options);

![github4](https://user-images.githubusercontent.com/5733541/193045613-4e0ef79c-f028-434f-b55e-ba2da100a1fb.png)

I think this is solved, thank you very much for the support , Dotmin 100% functional, the fault or error was in the design of the application.
