### ISSUE TITLE
Help how solve this problem in Xamarin forms

### ISSUE THREAD

**Issue by mibuswolf** [Mimetis/Dotmim.Sync#830]
![imagen](https://user-images.githubusercontent.com/39713441/194115307-73dce662-0d96-4745-971d-e83c4a30693f.png)

Hello, I have a change in my server database but at the client level I am not sure how to capture and refresh those changes

**Comment by Mimetis** [comment]
Did you take a look at https://dotmimsync.readthedocs.io/Provision.html#migrating-a-database-schema ?

**Comment by mibuswolf** [comment]
> Did you take a look at https://dotmimsync.readthedocs.io/Provision.html#migrating-a-database-schema ?

Hello i try using is new scope for this case, thanks.
