### ISSUE TITLE
InternalGetLocalTimestampAsync Throws Object cannot be cast from DBNull to other types.

### ISSUE THREAD

**Issue by AvaSharkawy** [Mimetis/Dotmim.Sync#834]
Core.Orchestrators.BaseOrchestrator.TimeStamp.cs file
InternalGetLocalTimestampAsync method at line 59
this line "await action.Command.ExecuteScalarAsync().ConfigureAwait(false)"
returns null when executing the query "SELECT CHANGE_TRACKING_CURRENT_VERSION()"
so the line 
"long result = Convert.ToInt64(await action.Command.ExecuteScalarAsync().ConfigureAwait(false));"
always throw exception.
I need help with this

**Comment by AvaSharkawy** [comment]
I suggest if the change_tracking_current_version returns null sometimes, my suggestion is to replace the query to "SELECT ISNULL(CHANGE_TRACKING_CURRENT_VERSION(), 0)"
is there is no harm?
I don't know. I'm trying to help

**Comment by Mimetis** [comment]
Did you activate the change tracking on your sql server ?
can you share the code you are using to call this api ?

**Comment by AvaSharkawy** [comment]
Thanks for the fast reply.
I didn't activate the change tracking.
Where should I activate it? in the server side? or client side?
and I didn't notice anything about activating the change tracking in docs
These docs which I followed https://dotmimsync.readthedocs.io/Web.html

**Comment by AvaSharkawy** [comment]
I'm so dump, sorry for disturb.
I've noticed now "Add the server provider. As we are using sql server with change tracking, we are adding [Dotmim.Sync.SqlSyncChangeTrackingProvider](https://www.nuget.org/packages/Dotmim.Sync.SqlServer.ChangeTracking) ."
I will try the whole process in the server with Dotmim.Sync.SqlServer with no change tracking first

**Comment by Mimetis** [comment]
https://dotmimsync.readthedocs.io/ChangeTracking.html

**Comment by AvaSharkawy** [comment]
I've done ChangeTracking part and the error gone.
I think you think you need to throw more specific exception in this case.
anyway, now I've another exception related to stored procedures.
Could not find stored procedure 'dbo.Teachers_initialize'.?
dbo.Teachers is my table. where should I setup these procedures

**Comment by Mimetis** [comment]
Everything is generated by **DMS** on the first call

Seems you made a mistake somewhere... or you played a little bit too much with SyncSetup and so on ... :=)

Best thing to do in that case (if you are in testing phase) is to remove all scopes tables, store procedures, triggers and tracking tables from server, and start again
I mean, start from scratch when you are testing

You can call [DropAllAsync()](https://dotmimsync.readthedocs.io/Orchestrators.html#id17) as well, if you prefer to do it with **DMS** 

> I think you need to throw more specific exception in this case.

I still dont know how you produced this error

**Comment by AvaSharkawy** [comment]
My server setup is exactly the same as these docs https://dotmimsync.readthedocs.io/Web.html
`services.AddControllers();

            services.AddDistributedMemoryCache();

            services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

            // [Required]: Get a connection string to your server data source
            var connectionString = Configuration.GetConnectionString("StudentManagementDb");

            var options = new SyncOptions { };

            // [Required] Tables involved in the sync process:
            var tables = new string[] 
            {
                nameof(StudentManagementContext.Attendances), 
                nameof(StudentManagementContext.ExamResults), 
                nameof(StudentManagementContext.Students), 
                nameof(StudentManagementContext.SysGrades), 
                nameof(StudentManagementContext.SysGroups), 
                nameof(StudentManagementContext.Teachers), 
                nameof(StudentManagementContext.StudentFinancialTypes),
                nameof(StudentManagementContext.Expenses),
                nameof(StudentManagementContext.Incomes),
                nameof(StudentManagementContext.Lectures),
                nameof(StudentManagementContext.Exams),
                nameof(StudentManagementContext.StudentAttendanceSMSTemplates),
                nameof(StudentManagementContext.StudentAttendanceSMSSents),
                nameof(StudentManagementContext.ExamResultSMSTemplates),
                nameof(StudentManagementContext.ExamResultSMSSents),
                nameof(StudentManagementContext.StudentDataSMSTemplates),
                nameof(StudentManagementContext.StudentDataSMSSents),
            };

            // [Required]: Add a SqlSyncProvider acting as the server hub.
            services.AddSyncServer<SqlSyncChangeTrackingProvider>(connectionString, tables, options);
            
            // Configure Method
            app.UseRouting();
            app.UseSession();
`
and my client setup
`var clientConnectionString = @"My Client Connection String";

            var serverOrchestrator = new WebRemoteOrchestrator("https://localhost:5001/api/sync");

            // Second provider is using plain old Sql Server provider,
            // relying on triggers and tracking tables to create the sync environment
            var clientProvider = new SqlSyncProvider(clientConnectionString);

            // Creating an agent that will handle all the process
            var agent = new SyncAgent(clientProvider, serverOrchestrator);

            // Launch the sync process
            var s1 = await agent.SynchronizeAsync();
`

**Comment by AvaSharkawy** [comment]
> I still dont know how you produced this error

The error happens when I'm using SqlSyncChangeTracking setup and the change tracking is not activated on the database.

> this line "await action.Command.ExecuteScalarAsync().ConfigureAwait(false)"
> returns null when executing the query "SELECT CHANGE_TRACKING_CURRENT_VERSION()"
> so the line
> "long result = Convert.ToInt64(await action.Command.ExecuteScalarAsync().ConfigureAwait(false));"
> always throw exception.

**Comment by AvaSharkawy** [comment]
I will close this issue as we found the problem is: I've not activated change tracking on the server database.
after deleting existing databases and reinitialize with change tracking on the server side, the problem gone.
