### ISSUE TITLE
Remote changes not applied on second sync

### ISSUE THREAD

**Issue by spj-uk** [Mimetis/Dotmim.Sync#842]
I am using SQLite localling and syncing to SQLServer over http from Win Forms Classic. The initial database exists locally and is correctly created. 

```
var s1 = await agent.SynchronizeAsync(progress);
await agent.LocalOrchestrator.UpdateUntrackedRowsAsync();
s1 = await agent.SynchronizeAsync(progress);
```

In an attempt to get more details I added the following interceptor however it is not hit

```
agent.RemoteOrchestrator.OnDatabaseChangesApplied(args =>
{
    listBox1.Items.Add($"--------------------------------------------");
    listBox1.Items.Add($"Changes applied to the remote database:");
    listBox1.Items.Add($"--------------------------------------------");
    
   listBox1.Items.Add(args.ChangesApplied);
});
```
I noticed the source is empty in some of my logging (options set to SQL)

50%: [] ChangesApplying HttpGettingResponseMessageArgs: HttpGettingResponseMessageArgs

Is it possible to interrogate the Response Message Args? or am I missing a trick here?

Additionally we have an iOS product with the same code calling the same api which works.

**Comment by spj-uk** [comment]
```
30%: [main] ChangesSelecting ConnectionClosedArgs: [main] Connection Closed.
30%: [api.3sgroup.co.uk] ChangesApplying HttpSendingClientChangesRequestArgs: Sending Batch Changes. Batches: (1/50). Rows: (2/986). Waiting Server Response...
30%: [] ChangesApplying HttpGettingResponseMessageArgs: HttpGettingResponseMessageArgs
31%: [api.3sgroup.co.uk] ChangesApplying HttpSendingClientChangesRequestArgs: Sending Batch Changes. Batches: (2/50). Rows: (26/986). Waiting Server Response...
```

Just sits there after the first batch waiting.....

**Comment by spj-uk** [comment]
I am hosting my API on IIS, is there any settings I should investigate? When I run through IISExpress on dev machine the process appears to work.

**Comment by Mimetis** [comment]
No idea

**Comment by Mimetis** [comment]
Need a way to reproduce the error, otherwise will be hard to help you

**Comment by spj-uk** [comment]
I’ve just updated the fix branch (I hope).

Connect to our live api so you should see it.

Simon.

**Comment by Mimetis** [comment]
The problem is coming from the server side
What can I do with your update since the problem is coming from the server ?

**Comment by spj-uk** [comment]
Hopefully someone else may have come across the same issue. 

Where in the Dotmim,sync.core project is the ChangesApplying method? I've tried searching for the messages without success.

**Comment by spj-uk** [comment]
Could it mean anything that the source is missing in the ChangesApplying entry below (indicated by // here)? Two lines prior the connection is closed too? 

```
30%: [main] ChangesSelecting DatabaseChangesSelectedArgs: [Total] Upserts:1084. Deletes:0. Total:1084. [C:\Users\xxxx\AppData\Local\Temp\DotmimSync\2022_11_16_01hctvwh3azmc]
30%: [main] ChangesSelecting ConnectionClosedArgs: [main] Connection Closed.
30%: [api.xxx.co.uk] ChangesApplying HttpSendingClientChangesRequestArgs: Sending Batch Changes. Batches: (1/48). Rows: (2/1084). Waiting Server Response...
30%: [] ChangesApplying HttpGettingResponseMessageArgs: HttpGettingResponseMessageArgs // Here
31%: [api.xxx.co.uk] ChangesApplying HttpSendingClientChangesRequestArgs: Sending Batch Changes. Batches: (2/48). Rows: (26/1084). Waiting Server Response...
```

Thanks.

**Comment by Mimetis** [comment]
Did you tried the last beta version `0.9.8` on the server side where I put a lot of details in the error message ?

Let me know if you have something new

**Comment by spj-uk** [comment]
Thanks, we have put it to one side now as the .NET Core version worked but we will revisit the Classic .net Winforms example later.
