### ISSUE TITLE
MysqlConnector Version 0.69 => to 2.1.13

### ISSUE THREAD

**Issue by stephane3434** [Mimetis/Dotmim.Sync#845]
Hello 

Would it be possible to upgrade the version of MysqlConnector for MariaDb because we are stuck at version 0.69 ?

If we install a newer version an error appears in MariaDBSyncProvider for MysqlConnector. 

The latest version MysqlConnector is the version 2.1.13. 

Maybe there is a reason for the 0.69 but for big Mariadb tables we can not synchronize them the first time; 

Maybe changing the version of the connector it will work

Thank you

**Comment by Mimetis** [comment]
`MySqlConnector` is compatible with **.Net Standard 2.0** only with version `0.69`
If you want to upgrade to a more recent version, you need to upgrade your project using at least **.Net Core 3.1** (or latest version **.Net 6**)

That's being said, DMS is using 
- `0.69` for any project tageting **.Net Standard 2.0** and 
- `1.2.1` for any project tageting **.Net Core 3.1** and **.Net 6**

``` xml
<ItemGroup Condition=" '$(TargetFramework)' == '$(TargetFrameworkNet6)' ">
	<PackageReference Include="MySqlConnector" Version="1.2.1" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == '$(TargetFrameworkNetCore)' ">
	<PackageReference Include="MySqlConnector" Version="1.2.1" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == '$(TargetFrameworkNetStandard)' ">
	<PackageReference Include="MySqlConnector" Version="0.69.10" />
</ItemGroup>

```

I will upgrade the version to the latest in the next release, but the version 0.69 will remains as is, if you are still targeting `.Net Standard 2.0`

Make sense ?

**Comment by stephane3434** [comment]
Thanks,

I will test in net core 6 to see if the sync works correctly with our database that we are testing in mariadb and with version 1.2 of MysqlConnector

I will also test a fork of your project to see if I can give you a feedback on the latest version of MysqlConnector and how it works because there are a lot of improvements in the evolution of this connector

Have a nice day and thank you for your work

**Comment by stephane3434** [comment]
Hello 
we tested the MysqlConnector version in version 2.1.13 by Modifying Dotmin.Sync.Mariadb and it works correctly in net6 without changing anything in the code. 

As we are not specialists in packages we had to remove everything that referred to net standard and older versions to do our tests 

And regarding our database problem, after long research and tests we understood that we had to Deprovisoning the server before provisioning it during the first synchronization. 

We also discovered that we did not need to create the future database, the tables would be automatically created 

Thank you for your excellent work
