### ISSUE TITLE
Its taking too much time to initialize database from server to client.

### ISSUE THREAD

**Issue by hsharma89** [Mimetis/Dotmim.Sync#849]
Hi guys,

I am using Dotmim sync application to sync my data from sql server to local Sqlitedb and vice-versa. The version i am using is v0.5.5.0. It was working fine for few months, but suddenly its started taking too much time to Reinitialize the database. Its taking around 1 hour. However the size of database is ~40MB so far.

So, Can someone help me on this? In addition to this i notices few more things while debugging as mentioned below:

1. When i reinitialize the database from client application. I ran the Wireshark to test the traffic going to server. But i noticed it communicate with server for only 1-2 minutes. After that there is no incoming and outgoing traffic to my server. Then still taking another 1 hour to sync completely. Does it process locally after 2 mins?
2. Also, is there a way we can the progress that how much data is synced and how much is left to show on client side?

Looking forward for you reply!

Thanks

**Comment by hsharma89** [comment]
Hi,

Yes, i am using everything you asked. But still same issue. But i have upgraded to latest version and it worked really well. Now my 40 mb data synced in less than a minute. Also, i saw lots of new things in this version which reduced my database size significantly. 

There is one issue i am getting now related to Merge conflict. Is there a way to check on which row I got this issue?

issue is : The Merge_statement conflicted with the FOREIGN KEY constraint 'FK_xxxxx". The conflict occurred in database "abc:.

We also used the DisableConstraintsOnApplyChanges by setting this to true but it didn't help.

Thanks.

**Comment by Mimetis** [comment]
Try in order:

Be sure your tables are ordered correctly in your `SyncSetup`

A wrong setup: 
``` cs
var syncSetup = new SyncSetup("CustomerAddress", "Customer");
```
`Customer` should be created before creating a `CustomerAddress`

A correct setup version:
``` cs
var syncSetup = new SyncSetup("Customer", "CustomerAddress");
```

Use `DisableConstraintsOnApplyChanges=true`, in the **options from the asp.net core web api configuration**:

``` cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    services.AddDistributedMemoryCache();
    services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

    // [Required]: Get a connection string to your server data source
    var connectionString = Configuration.GetSection("ConnectionStrings")["SqlConnection"];
    // var connectionString = Configuration.GetSection("ConnectionStrings")["MySqlConnection"];

    var options = new SyncOptions
    {
        DisableConstraintsOnApplyChanges = true
    };

    // [Required] Tables involved in the sync process:
    var tables = new string[] {"ProductCategory", "ProductModel", "Product",
    "Address", "Customer", "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail" };

    // [Required]: Add a SqlSyncProvider acting as the server hub.
    services.AddSyncServer<SqlSyncProvider>(connectionString, tables, options);
}

```

Use a retry exception:

``` cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    services.AddDistributedMemoryCache();
    services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

    // [Required]: Get a connection string to your server data source
    var connectionString = Configuration.GetSection("ConnectionStrings")["SqlConnection"];
    // var connectionString = Configuration.GetSection("ConnectionStrings")["MySqlConnection"];

    var options = new SyncOptions
    {
        DisableConstraintsOnApplyChanges = true
        ErrorResolutionPolicy = ErrorResolution.RetryOneMoreTimeAndThrowOnError,
    };

    // [Required] Tables involved in the sync process:
    var tables = new string[] {"ProductCategory", "ProductModel", "Product",
    "Address", "Customer", "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail" };

    // [Required]: Add a SqlSyncProvider acting as the server hub.
    services.AddSyncServer<SqlSyncProvider>(connectionString, tables, options);
}

```

Let me know
