### ISSUE TITLE
String or binary data would be truncated. The data for table-valued parameter "@changeTable" doesn't conform to the table type of the parameter.

### ISSUE THREAD

**Issue by edotappstore** [Mimetis/Dotmim.Sync#852]
Hi, I am getting the following error when sqlite (client) is trying to sync with sql server (server).

"String or binary data would be truncated.
The data for table-valued parameter "@changeTable" doesn't conform to the table type of the parameter. SQL Server error is: 8152, state: 30
The statement has been terminated."

![string-truncate-error](https://user-images.githubusercontent.com/98312418/199449871-ace0274f-a317-475d-9296-0ccff4ba7cf2.PNG)

There are 22 tables which have changes and are trying to upload. I have checked all tables in the sqlite, no table columns have exceeded their string length.
There are sqlite columns with around 500 characters text column and in sql server the column datatype is defined as nvarchar(max).

We are using WebClientOrchestrator sync web proxy.

Is there a way to resolve this issue and sync the client data to server.

Dotmim package: 0.8.0
.Net core: 3.1

**Comment by Mimetis** [comment]
The problem is coming from the server, I think (and not sqlite)
I think your server provision is not correct
I guess you have more or less columns than what DMS has generated 
You can try to `DeprovisionAsync` the stored procedures and `ProvisionAsync` the stored procedures again and see if it's resolving the issue.

**Comment by edotappstore** [comment]
Hello, thank you for the reply.
I forgot to mention that we have multiple client sqlite db. All the other clients are able to sync normally, only one sqlite client is facing this problem.

**Comment by Mimetis** [comment]
nice !
can we close the issue (you can do it)

**Comment by edotappstore** [comment]
In client side sqlite db the datetime column is being inserted as '2022-11-01 06:52:43.6802316' which is 27 characters (created by DateTime.UtcNow by C# client code) which is not getting accepted by server database.
