### ISSUE TITLE
SQL Server unique keys not created in Sqlite

### ISSUE THREAD

**Issue by chance-jacobs** [Mimetis/Dotmim.Sync#853]
I am trying to sync a sql server database with sqlite.  I have 2 tabless PetOwner and Dog.  There is a unique key on DogId and PetOwnerId.  When I try to sync using Dotmim, the unique keys are not created in sqlite.  Please help

USE [SyncDb]
GO

/****** Object:  Table [dbo].[Dog]    Script Date: 11/2/2022 1:42:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Dog](
	[DogId] [int] IDENTITY(1,1) NOT NULL,
	[DogName] [nvarchar](50) NOT NULL,
	[PetOwnerId] [int] NOT NULL,
 CONSTRAINT [PK_Dog] PRIMARY KEY CLUSTERED 
(
	[DogName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Dog]  WITH CHECK ADD  CONSTRAINT [FK_Dog_PetOwner] FOREIGN KEY([PetOwnerId])
REFERENCES [dbo].[PetOwner] ([PetOwnerId])
GO

ALTER TABLE [dbo].[Dog] CHECK CONSTRAINT [FK_Dog_PetOwner]
GO

/****** Object:  Table [dbo].[PetOwner]    Script Date: 11/2/2022 1:42:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PetOwner](
	[PetOwnerId] [int] IDENTITY(1,1) NOT NULL,
	[PetOwnerName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_PetOwner] PRIMARY KEY CLUSTERED 
(
	[PetOwnerName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Index [UK_Dog]    Script Date: 11/2/2022 1:44:20 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_Dog] ON [dbo].[Dog]
(
	[DogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

USE [SyncDb]
GO

/****** Object:  Index [UK_PetOwner]    Script Date: 11/2/2022 1:44:44 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK_PetOwner] ON [dbo].[PetOwner]
(
	[PetOwnerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

**Comment by Mimetis** [comment]
Indeed.
Only table columns and primary keys are created if not already exist.
A solution : You can create tables yourself before First sync if you want.
