### ISSUE TITLE
Sync Web inqury 

### ISSUE THREAD

**Issue by MHefny123** [Mimetis/Dotmim.Sync#858]
good morning mr Mimetis
I have a solution based on your sync platform as below 

sync Api that directly connected to sql server 
the sql server has diffrent databases every 
 server databse syncing with multi clients with some filters 

every database on server and clients have the same schema of tables 

Some times clienst sync with wrong server database 

here is my solution files 

[SyncAPI.zip](https://github.com/Mimetis/Dotmim.Sync/files/9948983/SyncAPI.zip)
[SyncService.zip](https://github.com/Mimetis/Dotmim.Sync/files/9948985/SyncService.zip)

I think I have to dedicate asnapshot path for every database 

please help 
best regards

**Comment by Mimetis** [comment]
Make a test with the last version
Make a github project with both api and client, instead of sharing zip files
Make this project as simple as possible as I can't spent time understanding your business rules
Make a project that can compile without any missing dependencies

**Comment by MHefny123** [comment]
Thank your for sweet response 
here is the repo url: https://github.com/MHefny123/SyncSolution
included the db scripts

**Comment by MHefny123** [comment]
first I would like to appreciate your help and reply  latterly you made my day thank 
find your invitation please to the repo

**Comment by MHefny123** [comment]
yes every client database will sync with one server database  one server db Many clients DB's sync direction based on client ID or branch ID our case 

best regards

**Comment by Mimetis** [comment]
you have a solution in the mimetis/solution branch
