### ISSUE TITLE
Error MAUI on windows

### ISSUE THREAD

**Issue by mibuswolf** [Mimetis/Dotmim.Sync#859]
![image](https://user-images.githubusercontent.com/39713441/200638649-9446860e-a984-435b-9d1b-379eaa12bc1e.png)

I try to synchronize a local database in windows, the file is created but when I try to synchronize it gives me the previous error.

The error display when y call the event " var r = await this.syncAgent.SynchronizeAsync(syncType, progress);" On Android no have a problem and IOS never star the app XD

**Comment by Mimetis** [comment]
can you share a github repository sample ?

**Comment by mibuswolf** [comment]
> can you share a github repository sample ?

https://github.com/mibuswolf/ExamplesProyects

**Comment by Mimetis** [comment]
I get it

Don't use `SynchronousProgress` when you are in a visual application like **MAUI**
`SynchronousProgress` is meant to be used only in a **Console application**

Use `Progress` instead:

``` cs
var progress = new Progress<ProgressArgs>(args =>
{
    MainThread.BeginInvokeOnMainThread(() =>
    {
        this.SyncProgress = args.ProgressPercentage;
        this.SyncProgressionText = args.Message;
    });
});

```

**Comment by mibuswolf** [comment]
++

> 

Omg you are the best!!! Thanks
