### ISSUE TITLE
Seems you are trying another Setup tables that what is stored in your server scope database. Please create a new scope or deprovision and provision again your server scope.

### ISSUE THREAD

**Issue by rijolana** [Mimetis/Dotmim.Sync#864]
Hi guys,

I am using Dotmim sync application to sync my data from sql server to local sql dB and vice-versa. The version I am using is 0.9.7. It was working fine with sync scope with bidirectional. But when try to sync with both sync scope and sync direction we get an error message as shown in title. The client and server side code are attached below. Please find the attachments.

Client Code
`var serverOrchestrator = new WebRemoteOrchestrator("http://192.168.15.65:7745/api/sync");
            serverOrchestrator.HttpClient.Timeout = TimeSpan.FromMinutes(20);
            // Second provider is using plain old Sql Server provider, relying on triggers and tracking tables to create the sync environment
            var clientProvider = new SqlSyncProvider(clientConnectionString);

            var setupProducts = new SyncSetup("sprod");
            setupProducts.Tables["sprod"].SyncDirection = SyncDirection.UploadOnly;
            var agent = new SyncAgent(clientProvider, serverOrchestrator);

            do
            {
                try
                {
                    var progress = new SynchronousProgress<ProgressArgs>(s =>Console.WriteLine($"{s.Context.SyncStage}:\t{s.Message}"));

                    // Launch the sync process
                    //var s1 = await agent.SynchronizeAsync(progress);
                    var s1 = await agent.SynchronizeAsync("sup", setupProducts, progress);
                    // Write results
                    Console.WriteLine(s1);

                    //var schema = await agent.LocalOrchestrator.GetSchemaAsync("products", syncSetup);

                    // Update all rows on the client side that does not have any tracking rows
                    await agent.LocalOrchestrator.UpdateUntrackedRowsAsync("sup");

                    // Make as second sync.
                    // All local rows that were existing before first sync happened, will be uploaded correctly
                    s1 = await agent.SynchronizeAsync("sup", setupProducts, progress);
                    Console.WriteLine(s1);
                    //var s1 = await agent.SynchronizeAsync("customers", tables2);
                    // Write results
                    //Console.WriteLine(s1);

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }

            } while (Console.ReadKey().Key != ConsoleKey.Escape);

            Console.WriteLine("End");`

Server Code
` public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            services.AddDistributedMemoryCache();
            services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

            // [Required]: Get a connection string to your server data source
            var connectionString = Configuration.GetSection("ConnectionStrings")["SqlConnection"];

            var options = new SyncOptions { };

            // [Required] Tables involved in the sync process:
            //var tables1 = new string[] { "sprod" };
            var setupProducts = new SyncSetup("sprod");
            // [Required]: Add a SqlSyncProvider acting as the server hub.
            services.AddSyncServer<SqlSyncProvider>(connectionString, "sup", setupProducts, options);
        }`

**Comment by Mimetis** [comment]
if you are changing the syncdirection for a table, you are changing your setup.
DMS can't work with a different setup from the code and from the one DMS founds in the database

If you want to have the choice on the direction, you need to create 2 setups : One for bidirectional, one for another direction

**Comment by rijolana** [comment]
Hi guys,

we are change the server side code like the below one .But the same error exist. Can you give one sample for both sync direction with scope

`public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            services.AddDistributedMemoryCache();
            services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

            // [Required]: Get a connection string to your server data source
            var connectionString = Configuration.GetSection("ConnectionStrings")["SqlConnection"];

            var options = new SyncOptions { };

            // [Required] Tables involved in the sync process:
            //var tables1 = new string[] { "sprod" };
            //var setupProducts = new SyncSetup("sprod");
            // [Required]: Add a SqlSyncProvider acting as the server hub.
            /// DownLoad Only Tables
            var tblsDownLoadOnly = new string[] {

             "sprod",
            };


            //Upload Only Tables
            var tblsUploadOnly = new string[] {

               //"POS_Sales",
               //"POS_SalesDetail",
               //"POS_TempSales",
               //"POS_TempSalesDetail"
            };


            var tblsUpDown = new string[] {

                //"CustomerTitle",
                //"Customer",
                //"CustomerGroup",
                //"Zone",
                //"CustomerZoneAddress",
                //"Customer_AccountStatement"



            };
            var setup = new SyncSetup();
            SetupTable table;
            foreach (var obj in tblsDownLoadOnly)
            {
                table = new SetupTable();
                table.TableName = obj;
                table.SyncDirection = SyncDirection.DownloadOnly;
                setup.Tables.Add(table);
            }


            foreach (var obj in tblsUploadOnly)
            {
                table = new SetupTable();
                table.TableName = obj;
                table.SyncDirection = SyncDirection.UploadOnly;
                setup.Tables.Add(table);


            }


            foreach (var obj in tblsUpDown)
            {
                table = new SetupTable();
                table.TableName = obj;
                table.SyncDirection = SyncDirection.Bidirectional;
                setup.Tables.Add(table);
            }


            services.AddSyncServer<SqlSyncProvider>(connectionString, "sup",setup, options);
        }`

**Comment by Mimetis** [comment]
I don't get it, tbh

I think the problem is not coming from the setup, but more from a point in your code where you are modifying the setup
Or maybe you are trying different setups during your experimentations

Get the setup field from your database (it's a json field) and compare it with your setup code, and find why it's different

Not that everytime you are modifying an existing setup in your code (that already exists in the scope tables in your database) you need to create a new scope

**Comment by rijolana** [comment]
Our requirement is we have 3 client machines and one server.3 client machine having 3 different databases and server contain all the tables from three clients.
We need to sync some tables with upload only, download only & bidirectional.
We created three scope for each client and synchronization with bidirection work successfully.
But ones we change the sync direction of tables from client with sync setup then we are getting the errors.

**Comment by Mimetis** [comment]
As i said, do not modify a setup once you've used successfully (and the setup is saved in the db)
use another one with a new scope name
