### ISSUE TITLE
support oracle？

### ISSUE THREAD

**Issue by mingyangzhu** [Mimetis/Dotmim.Sync#870]
hi @Mimetis ,Oracle accounts for a large proportion of enterprise applications，Is there any plan to support oracle?This library is really great. There are great application scenarios.oracle support is really helpful. tks.

**Comment by Mimetis** [comment]
Hey @mingyangzhu 

I'm not an expert on **Oracle**. 
I'm still searching someone to contribute to create this provider (and for **PostgreSQL** as well)

**Comment by msh2050** [comment]
can you use the official one?
https://www.nuget.org/packages/Oracle.EntityFrameworkCore
