### ISSUE TITLE
Snapshot - not synching difference

### ISSUE THREAD

**Issue by dev-rpichler** [Mimetis/Dotmim.Sync#872]
Hello,
we have the problem that using snapshots for the first sync the changed/deleted data between the snapshot-timestamp and the current timestamp does not get synched anymore.

**Environment:**
SyncService/Server: MS SQL-Server (change tracking), ASP.NET Web proxy
Client: Xamarin/Sqlite

**Description/initial situation**
Create Snapshot  with timestamp **3250**
One day later firstSync on clients

Current timestamp on Server is now **3400**
(some of the the rows in one table were deleted)

**Expected behaviour:** 
Download and apply snapshot
Sync from 3250 to 3400

Current behaviour:
Download and apply snapshot
Mark timestamp 3400 as current version (my guess - without synching)

Sync is working from timestamp 3400!

Thank you very much!
Kind regards,
Robert

**Comment by dev-rpichler** [comment]
Are code snippets enough to check how the service looks like and how the clients are synching?
Otherwise I have to prepare an example I think, this is not a problem but I would need some time.
Kind regards,
Robert

**Comment by Mimetis** [comment]
Well I need to be able to reproduce the bug
Whatever the most convenient for you

**Comment by Mimetis** [comment]
Thax @dev-rpichler 
You 've spotted an issue!

Fix is in progress and will be available with the next release `0.9.8`

**Comment by Jeff534** [comment]
Hi there,

I have a similar issue. After syncing from the snapshot files successfully, I can't have the client to sync any new data from the server. 
The following code was used to sync at the client:

var clientOptions = new SyncOptions { DisableConstraintsOnApplyChanges = true };
SyncAgent agent = new SyncAgent(clientProvider, serverProvider, clientOptions);
var result = await agent.SynchronizeAsync(scopeName, setup);

Please note the same scopeName was used when syncing from the snapshot. 

Thanks!

**Comment by Jeff534** [comment]
Never mind. I was trying to sync from a slave DB. The replication is row based and trigger doesn't work in slave DB in this case.
