### ISSUE TITLE
RemoteOrchestrator.DropAllAsync() turns off ChangeTracking

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#878]
Using `DMS 0.9.7` via ASP.NET Core Web Proxy to SQL Server
in `SyncController` I have a method `DeprovisionServerAsync` for upgrading from `DMS 0.91` as suggested [here](https://github.com/Mimetis/Dotmim.Sync/issues/798#issuecomment-1229435692).

The database and tables have change tracking enabled before this line executes
`await webServerAgent.RemoteOrchestrator.DropAllAsync();`
However after the line executes, the database still has change tracking enabled, but change tracking is disabled on the tables.

I wonder if this is a little heavy handed as the database might be using change tracking for something else.

**Comment by Mimetis** [comment]
If you call `ProvisionAsync` after, it will enable again the **Change Tracking** again on the table.
`DropAllAsync` is calling internally the `DeprovisionAsync` method that disable the **Change Tracking** on the table.

However, you are right, if the table had already change tracking before `DMS` is installed, it could lead to a mis functional system.
That's being said, `DMS` is not maintaining a state of the table option before and after installing change tracking (or any other options).
You need to do it manually.

In your specific scenario, if you are not calling `ProvisionAsync` after your `DropAllAsync`, and you want to enable **Change Tracking** again, you can:

- Call the sql command manually `ALTER TABLE MY_TABLE ENABLE CHANGE_TRACKING WITH(TRACK_COLUMNS_UPDATED = ON);`
- Call the [Creating Tracking Table](https://dotmimsync.readthedocs.io/Orchestrators.html?highlight=createtrackingtableasync#creating-a-tracking-table) method on your `RemoteOrchestrator` or `LocalOrchestrator`:

``` cs
var provider = new SqlChangeTrackingSyncProvider(serverConnectionString);
var remoteOrchestrator = new RemoteOrchestrator(provider, options);
var scopeInfo = await remoteOrchestrator.GetScopeInfoAsync(setup);


var spExists = await remoteOrchestrator.ExistTrackingTableAsync(scopeInfo, "Employee");
if (!spExists)
    await remoteOrchestrator.CreateTrackingTableAsync(scopeInfo, "Employee");

```

**Comment by VagueGit** [comment]
Thank you for responding. You also suggested [Just remove everything manually](https://github.com/Mimetis/Dotmim.Sync/issues/798#issuecomment-1229437073), so I just dropped `scope_info_history` and `scope_info_server`. This is viable because we are offering our customers a new app to replace our old app so a complete resync is required anyway.

I'm really excited about this version of DMS as it promises to make debugging sync errors much easier.

Thanks again for your help.

**Comment by Mimetis** [comment]
Once you have dropped the old scopes tables, do not forget to drop all **stored procedures**, **triggers**, and **table value parameters**  
Basically, this is what is done by `DropAllAsync()`

**Comment by VagueGit** [comment]
Thanks but with change tracking on the server and a new database on the clients, I didn't think there is anything more to do

I misunderstand by convention ;-)
