### ISSUE TITLE
[Enhancement] Provide simple versionability for sync scopes

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#88]
Hi @Mimetis!

The following suggestion is a bit based on the problems described in issue #86 - namely if we wanted to support a versioning of the `SyncConfiguration`.

With the *old sync framework* it was usually the case, that, once you had your sync context setup (with all tables etc.) you could not change those tables anymore - or at least only with huge effort.

The basic feature description is:

*Allow the application developer to specify a version on a sync context and once a client connects with a different version (or lower), it reinitializes but tries to upload any changes first*

There are some "simple" scenarios, however, where versioning support would be **awesome**:

**Scenario 1**
The maximum period that a client is allowed to stay disconnected to a sync scope is - by default - 14 days.
Now when already in production, we realize, that we need to extend that period to (e.g.) 3 months.
What should happen then, is that a client, which synchronzies again after 15+ days, gets the new period (3 months) through the sync configuration and thus decides to just continue synchronizing data incrementally. After a disconnection period of 3 months. however, it should synchronize as `ReinitializeWithUpload`.
Basically, this scenario would not require the application developer to raise the version of the `SyncConfiguration`, as the disconnection period should be transmitted anyways.

**Scenario 2**
We add another column to a table.
In that case, the application developer wants to make sure, that all clients will get that data, so she raises the version of the `SyncConfiguration` object to `2`.
Once a client with version `1` synchronizes again, it notices the raised version, and thus runs the sync process as `ReinitializeWithUpload`.
Of course, Dotmim.Sync would then need to be able to alter existing table definitions (only add columns - deletion or modification to a stricter mode (e.g. make a column non nullable) cannot be supported as it would break existing clients)

**Scenario 3**
We add another table to the scope.
In that case, the application developer wants to make sure, that all clients get that data, so again the version of the `SyncConfiguration` is raised to `3`
So once a client connects, which is running version 1 or version 2, it runs the sync process as `ReinitializeWithUpload`, and thus also gets the new table.

I guess these scenarios are the ones that we missed the most, when it comes to maintain an application that is using the microsoft sync framework.

Do you agree, that these scenarios should be doable and included?

Do you think we are missing something? (e.g. the scenario, that a table is removed from a sync scope completely?)

**Comment by Mimetis** [comment]
Migration has been integrated in the last version
Closing this issue unless you have any other concern.
Feel free to comment, I will reopen it

**Comment by gentledepp** [comment]
I saw some of the changes, so I guess **scenario 1** is covered now.
But are scenarios **2* and **3** covered as well?

**Comment by Mimetis** [comment]
The migration is covered here https://mimetis.github.io/Dotmim.Sync/Migration

The only thing that is not covered, is the `Alter table`. Once a table is created on the client, it won't be touch anymore, automatically.

I guess you will have to `Provision` and `Deprovision` manually
