### ISSUE TITLE
sync/merge a SQL Server backup file

### ISSUE THREAD

**Issue by ToGoOrNotToGo** [Mimetis/Dotmim.Sync#884]
Hi,
great framework! Is it possible to sync/merge a SQL Server backup file (.bak) to an existing SQL Server instance database?

Regards

**Comment by Mimetis** [comment]
Hi,
No, `DMS` is a sync framework, not a restore backup thing
BTW, **SQL Server** is already able to restore a backup by default
Of course, you can't restore a backup with a merge option in an existing database

**Comment by Mimetis** [comment]
Please use the [discussion](https://github.com/Mimetis/Dotmim.Sync/discussions) tab for any question.
Use [Issues](https://github.com/Mimetis/Dotmim.Sync/issues) only if you think you found an issue related to `DMS`
