### ISSUE TITLE
MissingSchemaInScopeException

### ISSUE THREAD

**Issue by VagueGit** [Mimetis/Dotmim.Sync#885]
MissingSchemaInScopeException threw when DMS tried to sync a table that is missing on the server and we try to get the BatchInfo
```
catch (SyncException ex)
{
    var batchInfos = await syncAgent.LocalOrchestrator.LoadBatchInfosAsync();
```
Maybe LoadBatchInfosAsync could return an empty list? Then this would still work
```
foreach (var batchInfo in batchInfos)
{
```

**Comment by Mimetis** [comment]
The idea is to be able to read the content of the files without any schema validation ?

**Comment by VagueGit** [comment]
If there is no BatchInfo for any reason, return an empty list from LoadBatchInfosAsync.

Just an idea.

**Comment by Mimetis** [comment]
Ok, sounds like a good idea
I'm working on improving this area (reading files)
Another thing I'm trying to improve is to be able to open a batch info without any schema associated

I'll let you know once I have something to test

**Comment by VagueGit** [comment]
Would it be possible also to extract the sql for the error row? I don't think sql is available in progress for those who have to use `progress = new Progress<ProgressArgs>`

**Comment by Mimetis** [comment]
I've made an update in the master branch to let you load any batchinfo file without having to check the schema.
no more `MissingSchemaInScopeException`

**Comment by VagueGit** [comment]
Thank you!. Any chance of a nuget beta? (when you have had some sleep)

**Comment by Mimetis** [comment]
Yes, you can use the last beta version `0.9.8-beta-0965` published on nuget

**Comment by Mimetis** [comment]
I'll close the issue, since this ha been addressed by the last pre release package
Feel free to re open it, if you encounter a new error
