### ISSUE TITLE
 Dotmim.Sync.SyncException: This version needs a client manual upgrade

### ISSUE THREAD

**Issue by DamDucDuyIT** [Mimetis/Dotmim.Sync#890]
I am new in dotmin, I want to sync between 2 databases. I used the sample codes - HelloSync, the only thing I changed is 2 connectionstring of online database, but I got the error
`Unhandled exception. Dotmim.Sync.SyncException: This version needs a client manual upgrade.
 ---> System.Exception: This version needs a client manual upgrade.`
I don't understand why this happens. Please help me know which step I was wrong

**Comment by Mimetis** [comment]
Can you explain a little bit more your context:

- What kind of server database? SQL Server, MySQL?
- What kind of client database? SQL Server, MySQL, SQLite?

You usually have this message when you tried different versions of DMS (like trying an old version < `0.9.5`? current version is `0.9.7`)

Did you try different versions of `DMS`?

You can check both database and see if you have some tables like `sync_****`
Do you have this kind of tables?

If you are testing, just try to remove
- The `sync_***` tables in both databases.
- The table triggers generated
- The stored procedures generated
- The tracking tables generated

You can also use the [`DropAllAsync` method](https://dotmimsync.readthedocs.io/Orchestrators.html#dropallasync) on both side (that will drop all the DMS metadatas)

Something like:
``` cs
// On Client Side:
var localOrchestrator = new LocalOrchestrator(clientProvider);
await localOrchestrator.DropAllAsync();

// On Server side:
var remoteOrchestrator = new RemoteOrchestrator(serverProvider);
await remoteOrchestrator.DropAllAsync();

```

Once you are sure you have
- Delete all DMS metadatas
- Be sure you are using the correct version of DMS (at least `0.9.7`)

Make a new test

**Comment by MaTToX3** [comment]
Since I don't want to open another issue, I will ask here: can this error appear also for some different reason? Why am I asking that: we just got that error in a production app, which was never using any other Dotmim.Sync version but 0.9.7 so it doesn't really make any sense to see that? Could some metadata be missing or anything?

**Comment by Mimetis** [comment]
Can you test with last beta 1.0 version ?
