### ISSUE TITLE
UPDATE failed because the following SET options have incorrect settings: 'ANSI_WARNINGS, NUMERIC_ROUNDABORT'

### ISSUE THREAD

**Issue by ricardoamm** [Mimetis/Dotmim.Sync#906]
Hello, 

After provisioning the Database, I'm having the following error in the sync update trigger:

Msg 1934, Level 16, State 1, Procedure Item_update_trigger, Line 5 [Batch Start Line 18]
UPDATE failed because the following SET options have incorrect settings: 'ANSI_WARNINGS, NUMERIC_ROUNDABORT'. Verify that SET options are correct for use with indexed views and/or indexes on computed columns and/or filtered indexes and/or query notifications and/or XML data type methods and/or spatial index operations.

**Comment by Mimetis** [comment]
Seems you have a precision loss somewhere

https://learn.microsoft.com/en-us/sql/t-sql/statements/set-numeric-roundabort-transact-sql?view=sql-server-ver16

Can you confirm ?

**Comment by Mimetis** [comment]
If you are able to reproduce the error and creates a small sample github repro, I can look at it, otherwise, will be hard to figure it out
