### ISSUE TITLE
weird error occurred after updating to version 0.9.7

### ISSUE THREAD

**Issue by HunarAA** [Mimetis/Dotmim.Sync#916]
After I updated the framework to latest version from my side which is 0.9.7, I am getting this error "this version needs a client manual upgrade"
Could you please help me solve this?

**Comment by Mimetis** [comment]
Did you look at https://github.com/Mimetis/Dotmim.Sync/discussions/802 ?

**Comment by HunarAA** [comment]
Thank you I have downgraded the version to 0.9.5 and the above problem is solved. But know I am facing another problem which says "The value cannot be null. Parameter nameL Input."

**Comment by Mimetis** [comment]
I dont know
Need more info and details

**Comment by HunarAA** [comment]
unfortunately, it does not give me any further details. I am getting weird errors actually. I don't know is it from the library of from my side. Let share my code with you:
                **
                string constring = @"Data Source= " + Properties.Settings.Default.Server + " ; Database = " + 
                Properties.Settings.Default.Database + " ; User Id = " + Properties.Settings.Default.User_Name + "; Password = " + 
               Properties.Settings.Default.Password + "; Encrypt=True; TrustServerCertificate=True; MultipleActiveResultSets=True; 
               Connection Timeout=300";
                string connect = @"Data Source=(LocalDB)\MSSQLLocalDB;Initial Catalog=b_s_db1;Integrated 
                Security=SSPI;AttachDBFilename= " + Properties.Settings.Default.dbFilePath + "; Connection Timeout=300";

                SqlSyncProvider serverProvider = new SqlSyncProvider(connect);
                SqlSyncProvider clientProvider = new SqlSyncProvider(constring);

                var clientOptions = new SyncOptions { BatchSize = 500 };
                var setup = new SyncSetup("table1", "table2", "table3", "table4", "table4");

                SyncAgent agent = new SyncAgent(clientProvider, serverProvider);

                var syncContext = await agent.SynchronizeAsync(setup);
                MessageBox.Show("success:\n" + syncContext.ToString(), "info", MessageBoxButtons.OK, 
                MessageBoxIcon.Information);
               **

**Comment by Mimetis** [comment]
doesnt help, sorry

**Comment by HunarAA** [comment]
unfortunately, it does not give me any further details. I am getting weird errors actually. I don't know is it from the library of from my side. Let share my code with you:
                **
                string constring = @"Data Source= " + Properties.Settings.Default.Server + " ; Database = " + 
                Properties.Settings.Default.Database + " ; User Id = " + Properties.Settings.Default.User_Name + "; Password = " + 
               Properties.Settings.Default.Password + "; Encrypt=True; TrustServerCertificate=True; MultipleActiveResultSets=True; 
               Connection Timeout=300";
                string connect = @"Data Source=(LocalDB)\MSSQLLocalDB;Initial Catalog=bright_square_db1;Integrated 
                Security=SSPI;AttachDBFilename= " + Properties.Settings.Default.dbFilePath + "; Connection Timeout=300";

                SqlSyncProvider serverProvider = new SqlSyncProvider(connect);
                SqlSyncProvider clientProvider = new SqlSyncProvider(constring);

                var clientOptions = new SyncOptions { BatchSize = 500 };
                var setup = new SyncSetup("table1", "table2", "table3", "table4",
                    "table4");

                SyncAgent agent = new SyncAgent(clientProvider, serverProvider);

                var syncContext = await agent.SynchronizeAsync(setup);
                MessageBox.Show("success:\n" + syncContext.ToString(), "info", MessageBoxButtons.OK, 
MessageBoxIcon.Information);

**Comment by Mimetis** [comment]
Did you find ?

**Comment by HunarAA** [comment]
Unfortunately, no.
