### ISSUE TITLE
NpgsqlSyncProvider .Net 6 and 7 Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported.

### ISSUE THREAD

**Issue by WasimAhmad** [Mimetis/Dotmim.Sync#919]
hi @Mimetis

I am trying Postgresql provider with Web Proxy. it working fine asp.net core 3.1 on server side.
![image](https://user-images.githubusercontent.com/5045365/210181265-913c4ce1-a871-4c95-984d-c337c5166e79.png)

but throws "violates foreign key constraint" error with .net 6 and 7.
![image](https://user-images.githubusercontent.com/5045365/210181279-531af79a-cf18-454a-9f18-151a1e99702c.png)

and if i use DisableConstraintsOnApplyChanges= true then it does not throw error but skips that table changes.
![image](https://user-images.githubusercontent.com/5045365/210181313-e11290a8-6a9b-48dd-8a13-21dafb24fd03.png)

any idea?

**Comment by Mimetis** [comment]
Can you share the database schema / data, to be able to reproduce the error on my side ?

**Comment by WasimAhmad** [comment]
I have figured out..

second breaking changes in Npgsql database driver >= 6
https://www.npgsql.org/doc/release-notes/6.0.html#major-changes-to-timestamp-mapping

We need to set date Kind=UTC for DbType.DateTimeOffset mappings.. I hope this will help fixing problem.

![image](https://user-images.githubusercontent.com/5045365/210271904-97042696-6fe5-466c-aeea-a51de63a6673.png)

**Comment by Mimetis** [comment]
can you share a table schema example I can use to reproduce ?

**Comment by WasimAhmad** [comment]
[backup.zip](https://github.com/Mimetis/Dotmim.Sync/files/10333411/backup.zip)

**Comment by WasimAhmad** [comment]
```
var tables = new[] {"SaleInvoiceService",
    "SaleInvoiceItem",
    "SaleInvoices",
    "Services",
    "Configurations",
    "Units",
    "PurchasePriceHistories",
    "Items",
    "CustomerProject",
    "ItemUnitOfMeasure",
    "TaxExemptionReasons",
    "Taxes",
    "Customers",
    "BusinessInfos",
    "Branches"};
var reversetables = tables.Reverse();

var setup = new SyncSetup(reversetables);
```

**Comment by WasimAhmad** [comment]
i have tested with both orders

**Comment by Mimetis** [comment]
Problem is coming from `DateTimeOffset` handling in **Postgres**.
Check the last commit and let me know if it's resolving your issue.

**Comment by Mimetis** [comment]
Reopen, in case the issue is not fixed yet

**Comment by WasimAhmad** [comment]
issue persists

**Comment by Mimetis** [comment]
I tried with your table `SaleInvoiceItem`, where I removed the column `TermsAndConditions` (type `text[]`) and it's working fine:

``` cs
var setup = new SyncSetup("SaleInvoices");
setup.Tables["SaleInvoices"].Columns.AddRange("Id", "Uuid", "IssuedDate", "CustomerId", 
    "PaymentCompletionDate", "Total", "GrossTotal", "NetTotal", "AmountPaid", "ReturnAmount", "DiscountAmount", 
    "DiscountPercentage", "TotalVAT", "TotalCost", "PaymentMethod", "PaymentType", "SaleInvoiceType", 
    "VatPercentage", "TaxTreatmentNarration", "CustomerName", "CustomerAddress", "CustomerVATNumber", 
    "CustomerGroupVATNumber", "SellerNameEnglish", "SellerNameArabic", "SellerAddress", "SellerVATNumber", 
    "SellerGroupVATNumber", "QrCode", "Status", "ProjectId", "TaxId", "VatRate", "VatCategoryCode", 
    "TaxExemptionReason", "ReceiveAs", "ReceiveType",  "InvoiceCounter", "InvoiceHash", 
    "SupplyDate", "InvoiceType", "SaleInvoiceClearenceStatus", "SaleInvoiceSpecialBillingAgreement", "SaleInvoiceSpecialTransactionType",
    "IsScheduled", "CreatedBy", "CreatedAt", "LastUpdatedBy", "LastUpdatedAt", "IsDeleted", "DeletedAt", "BranchId");

var serverProvider = new NpgsqlSyncProvider(DBHelper.GetNpgsqlDatabaseConnectionString(serverDbName));
var clientProvider = new NpgsqlSyncProvider(DBHelper.GetNpgsqlDatabaseConnectionString(clientDbName));

var agent = new SyncAgent(clientProvider, serverProvider, options);
var s = await agent.SynchronizeAsync(scopeName, setup, progress: progress);
Console.WriteLine(s);
```
![image](https://user-images.githubusercontent.com/4592555/210322594-e9bd21e4-81da-4039-ad5a-4268db461445.png)

What is the error you have ?

**Comment by WasimAhmad** [comment]
i have no error on initial sync too. but when i add a  record in Saleinvoice (master) and its item in Saleinvoiceitem (details) and sync failed showing the error for foreign key while apply changes in (details) salesinvoiceitems table. as no record change is applied in (master) saleinvoice table. i have tried to figure it out by adding some break point on source code.
which revealed that while inserting record in (master) saleinvoice table following error occured.

Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported.

let me check it again. by verifying date columns data.. (may be issue is in data)

**Comment by WasimAhmad** [comment]
try insert a row on a table in clientdb and then sync.

applychanges from server to client works fine, but when you need to push changes from client to server there are issues.

here is an example.

using HelloWebSyncClient and HelloWebSyncServer (.NET 7) using current master branch

 ```
// HelloWebSyncClient 
private static async Task SynchronizeAsync()
        {
            string clientConnectionString = "Host=localhost;Username=postgres;Password=*****;Database=clientdb;Include Error Detail=true;";

            var serverOrchestrator = new WebRemoteOrchestrator("https://localhost:44342/api/sync");
            var clientProvider = new NpgsqlSyncProvider(clientConnectionString);
            var options = new SyncOptions
            {
                BatchSize = 1000
            };

            // Creating an agent that will handle all the process
            var agent = new SyncAgent(clientProvider, serverOrchestrator, options);

            do
            {
                try
                {
                    var progress = new SynchronousProgress<ProgressArgs>(args => Console.WriteLine($"{args.ProgressPercentage:p}:\t{args.Message}"));

                    // Launch the sync process
                    var s1 = await agent.SynchronizeAsync(progress);
                    // Write results
                    Console.WriteLine(s1);

                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }

            } while (Console.ReadKey().Key != ConsoleKey.Escape);

            Console.WriteLine("End");
        }
```




 ```
//Server Starup.cs
string connectionString = "Host=localhost;Username=postgres;Password=****;Database=serverdb;Include Error Detail=true;";
var options = new SyncOptions
{
       SnapshotsDirectory = "C:\\Tmp\\Snapshots",
        BatchSize = 2000,
};
 var setup = new[] { "exampletable" };
services.AddSyncServer<NpgsqlSyncProvider>(connectionString, setup, options);
```

```
CREATE TABLE exampletable (
    id SERIAL PRIMARY KEY,
    tsname text,
    tstamp TIMESTAMP,
    tstamptz TIMESTAMPTZ
);

INSERT INTO exampletable (tsname, tstamp, tstamptz) VALUES ('TEST',now(), now());
```


inserted new record on serverdb
![image](https://user-images.githubusercontent.com/5045365/211068624-ddbd2695-f0e7-4b8e-a858-7ab80bff0d0b.png)

and when inserted new record on clientdb got this
![image](https://user-images.githubusercontent.com/5045365/211068971-58698d97-0fca-4624-aa47-d46cb22e391f.png)

This issue is only Web Proxy

**Comment by WasimAhmad** [comment]
this works find on both ways

```
string serverConnectionString = "Host=localhost;Username=postgres;Password=***;Database=serverdb;Include Error Detail=true;";
string clientConnectionString = "Host=localhost;Username=postgres;Password=***;Database=clientdb;Include Error Detail=true;";
var serverProvider = new NpgsqlSyncProvider(serverConnectionString);
var clientProvider = new NpgsqlSyncProvider(clientConnectionString);

var tables = new[] { "exampletable" };


// Creating an agent that will handle all the process
var agent = new SyncAgent(clientProvider, serverProvider);

do
{
    // Launch the sync process
    var s1 = await agent.SynchronizeAsync(tables);
    // Write results
    Console.WriteLine(s1);

} while (Console.ReadKey().Key != ConsoleKey.Escape);

Console.WriteLine("End");
```

**Comment by Mimetis** [comment]
The problem is coming when you have a column with type `timestamp without time zone` and then the same column on the other side with type `timestamp with time zone`.

This is especially true when you let Entity Framework 6 or 7, generating the database, as EF 6 or 7 has a breaking change with older version, where date are by default generated with `timestamp with time zone`.

I'm currently working on a solution to let the sync provider (`NpgsqlSyncProvider` in that case) hook the command parameters each time a command is generated by the DMS core engine.

Something like that (in `NpgsqlSyncAdapter` class from `Dotmim.Sync.PostgreSql` project):

``` cs
public override DbCommand EnsureCommandParametersValues(DbCommand command, DbCommandType commandType,
    DbConnection connection, DbTransaction transaction)
{
    foreach (NpgsqlParameter npgsqlParameter in command.Parameters )
    {

        // We have a column timestamp with time zone
        // Need to convert all DateTime to UTC date
        // And all DateTimeOffset to DateTime UTC
        if (npgsqlParameter.NpgsqlDbType == NpgsqlDbType.TimestampTz)
        {
            if (npgsqlParameter.Value is DateTime dateTime)
                npgsqlParameter.Value = dateTime.ToUniversalTime();
            else if (npgsqlParameter.Value is DateTimeOffset dateTimeOffset)
                npgsqlParameter.Value = dateTimeOffset.UtcDateTime;
            else
                npgsqlParameter.Value = SyncTypeConverter.TryConvertTo<DateTime>
                                            (npgsqlParameter.Value).ToUniversalTime();

        }
        else if (npgsqlParameter.NpgsqlDbType == NpgsqlDbType.Timestamp)
        {
            if (npgsqlParameter.Value is DateTimeOffset dateTimeOffset)
                npgsqlParameter.Value = dateTimeOffset.UtcDateTime;
            else
                npgsqlParameter.Value = SyncTypeConverter.TryConvertTo<DateTime>
                                            (npgsqlParameter.Value).ToUniversalTime();
        }
        else
        {
            npgsqlParameter.Value = SyncTypeConverter.TryConvertFromDbType
                                            (npgsqlParameter.Value, npgsqlParameter.DbType);
        }
    }
    return command;
}

```

That way, Postgres provider (and only Postgres provider) will be able to mitigate this issue.

Make sense ?

**Comment by WasimAhmad** [comment]
yes. thanks you @Mimetis .

**Comment by WasimAhmad** [comment]
I can understand why this is working then

```
string serverConnectionString = "Host=localhost;Username=postgres;Password=***;Database=serverdb;Include Error Detail=true;";
string clientConnectionString = "Host=localhost;Username=postgres;Password=***;Database=clientdb;Include Error Detail=true;";
var serverProvider = new NpgsqlSyncProvider(serverConnectionString);
var clientProvider = new NpgsqlSyncProvider(clientConnectionString);

var tables = new[] { "exampletable" };


// Creating an agent that will handle all the process
var agent = new SyncAgent(clientProvider, serverProvider);

do
{
    // Launch the sync process
    var s1 = await agent.SynchronizeAsync(tables);
    // Write results
    Console.WriteLine(s1);

} while (Console.ReadKey().Key != ConsoleKey.Escape);

Console.WriteLine("End");
```

**Comment by WasimAhmad** [comment]
**at time zone 'utc'** this may help while selecting data from source

```
select tsname, tstamp, tstamptz from exampletable e 
select tsname, tstamp, tstamptz at time zone 'utc' from exampletable e 
```
what do you think

**Comment by Mimetis** [comment]
Hey @WasimAhmad 
I've just updated the master branch with the last changes, to be able to deal with datetime within **Postgres** and the ADO.Net `NpgsqlProvider`

Basically, the PostgresProvider is now able to deal with datetime, and will check the `Npgsql.EnableLegacyTimestampBehavior` value:

https://github.com/Mimetis/Dotmim.Sync/blob/11a77252d6ff69e38e185d3f97e3e79f417aac58/Projects/Dotmim.Sync.PostgreSql/NpgsqlSyncAdapter.cs#L57-L63

Then, the parameter value are defined correctly, depending on Framework version and legacy flag:

https://github.com/Mimetis/Dotmim.Sync/blob/11a77252d6ff69e38e185d3f97e3e79f417aac58/Projects/Dotmim.Sync.PostgreSql/NpgsqlSyncAdapter.cs#L149-L185

Can you make some tests on your side, using the last commit from master branch and see if it's working fine for you ?

**Comment by WasimAhmad** [comment]
thanks @Mimetis. i will get back to you after testing...

**Comment by WasimAhmad** [comment]
issue is fixed with new beta. >= 0.9.8-beta-1056
