### ISSUE TITLE
[Enhancement] - pull (MySQL/Sql)ObjectNames into core

### ISSUE THREAD

**Issue by gentledepp** [Mimetis/Dotmim.Sync#92]
With regards to #91, we have the need to know the names that are created by dotmim sync for a given table and syncconfiguration.

What we see is, that the ...ObjectNames object exists for every database.
Moreover there is an internal static method in each DbBuilder `GetParsers` which returns the names of the table and the tracking table.

Question:
Wouldn't it be better to 
- include all names for a given `DmTable` in the `...ObjectNames` object.
- create that object once in the CoreProvider and pass it along to all builders
- and additionally provide a method, that is accessible to the `ISyncEventInterceptor`s, so that we can use it to provision additional stuff and be sure that we always have the correct names in use

What do you think?

**Comment by Mimetis** [comment]
> *What we see is, that the ...ObjectNames object exists for every database.*

I guess you mean `IProvider` when you say *database*, right ?   
The idea is to delegate the naming convention to each provider.  

One quick example. Let's say the dmTable called `CustomerAddress`
 
For instance, the mySql provider does not support capital letters, so the the mysql provider will make a `ToLowerCase()` to all tables names. In our example it will be `customeraddress`.
In the opposite the Sql provider does not requires to changes the case of any table name, so we keep in our example `CustomerAddress`

So we will have two differents names for one table when we have a sync between sql and mysql (`CustomerAddress` and `customeraddress` )

> *include all names for a given DmTable in the ...ObjectNames object.*

I do not understand your point here ? We have one typed ObjectName for each provider. What do you want to do ?

> *and additionally provide a method, that is accessible to the ISyncEventInterceptors, so that we can use it to provision additional stuff and be sure that we always have the correct names in use*

We do not have any `ISyncEventInterceptors` for now, so I don't get your point ?

> *Need to know a name for a given DmTable*

Did you try something like this ? 

```
-- Getting the object names convention
var sqlObjectNames = new SqlObjectNames(dmTable);

-- Getting the ObjectNameParser object
(var tableName, var trackingName) = SqlBuilder.GetParsers(this.TableDescription);

```

**Comment by gentledepp** [comment]
I am sorry for confusing you.
We are actually using what you proposed:
```
-- Getting the object names convention
var sqlObjectNames = new SqlObjectNames(dmTable);

-- Getting the ObjectNameParser object
(var tableName, var trackingName) = SqlBuilder.GetParsers(this.TableDescription);

```
it took me a while, but I think I'm getting along quite well with the source code now.

What I was writing about is the following:

We are provisioning extra tables to support the sync process (syncfilters table) and also a customized selectchanges procedure on the server side. Therefore, I implemented the virtual "OnTableProvisionedAsync" methods.
To provision the selectchanges procedure, we need to alter the existing one, that was provisioned by Dotmim.Sync by default. 
To do that, we need to know the exact name. 

That was the reason I started digging for an easy way to find out the names that Dotmim.Sync uses based on what is configured in the `SyncConfiguration`

So I found there is a `SqlObjectNames` object that contains all names except those of the table and the tracking table.

So my suggestion is twofold:
1) include the table- and trackingtable-name in the `SqlObjectNames` object
2) create a method in the CoreProvider, that hands me out those `XYObjectNames` (no matter what provider), so I can get their names by simply handing over a `DbCommandType`

That way, on every provider, you can easily find out the name of the objects, that Dotmim.Sync created.

Does that make more sense now? (I admit that I can be quite confusing sometimes, when too much stuff is going on in my head ;-))

**Comment by Mimetis** [comment]
We can try something more easy, I guess :)

Do you want to make a PR ?   
I won't prioritize it for now, because we have a way to get thoses names and it's not a blocking issue (You give me a lot of work, those last days :) )

Seb

**Comment by gentledepp** [comment]
You are right, it has no priority at the moment.
And of course: I would do a PR.

I just like to make sure that a repository owner is aware of what I am planning to contribute and gives his/her "go"

**Comment by Mimetis** [comment]
Oh yes, totally make sense.   
Indeed, it would be a pity to work on a PR, that would be potentially not validated

thx !

**Comment by Mimetis** [comment]
Closing this one, since we may have a PR later based on it
