### ISSUE TITLE
SQLite.Interop.dll

### ISSUE THREAD

**Issue by sylverbee** [Mimetis/Dotmim.Sync#925]
Are some nugets of Dotmim 0.9.4 using SQLite.Interop.dll?
Due to new rules in Microsoft Store, I can't publish anymore new version of my product.

_L’API wsprintfW présente dans user32.dll n’est pas prise en charge pour ce type d’application. SQLite.Interop.dll appelle cette API.
L’API CorBindToRuntimeEx présente dans mscoree.dll n’est pas prise en charge pour ce type d’application. SQLite.Interop.dll appelle cette API.
L’API StrongNameErrorInfo présente dans mscoree.dll n’est pas prise en charge pour ce type d’application. SQLite.Interop.dll appelle cette API.
L’API StrongNameFreeBuffer présente dans mscoree.dll n’est pas prise en charge pour ce type d’application. SQLite.Interop.dll appelle cette API.
L’API StrongNameSignatureVerificationEx présente dans mscoree.dll n’est pas prise en charge pour ce type d’application. SQLite.Interop.dll appelle cette API.
L’API StrongNameTokenFromAssembly présente dans mscoree.dll n’est pas prise en charge pour ce type d’application. SQLite.Interop.dll appelle cette API._

**Comment by VagueGit** [comment]
I published a new version of our app to our beta testers via the Microsoft Store yesterday using DMS SQLite 0.9.8-beta-1049. It passed certification without issue.

We use Microsoft.Data.SQLite 7.0.1. Could the issue be with the version of Microsoft.Data.SQLite you are using? Or are you using System.Data.SQLite?

**Comment by Mimetis** [comment]
We are using Microsoft.Data.SQLite since Day 1 :)
I'm not sure about what version of `Microsoft.Data.SQLite` on `v0.9.4`, but I guess it was version `5.xxx` as version `6.0` was not compatible at this time:

``` xml
	<ItemGroup Condition=" '$(TargetFramework)' == '$(TargetFrameworkNetCore)' Or '$(TargetFramework)' == '$(TargetFrameworkNetStandard)'">
		<PackageReference Include="Microsoft.Data.Sqlite" Version="5.0.3" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == '$(TargetFrameworkNet6)'">
		<PackageReference Include="Microsoft.Data.Sqlite" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == '$(TargetFrameworkNet5)'">
		<PackageReference Include="Microsoft.Data.Sqlite" Version="5.0.12" />
	</ItemGroup>
``` xml

Today, we are using `6.0.11` for `Net. Framework <= 6`, `.Net Core` and `.Net Standard`, and version `7.0.0 `for `.Net framework 7.0`:

``` xml
<ItemGroup Condition=" '$(TargetFramework)' == '$(TargetFrameworkNet6)' OR '$(TargetFramework)' == '$(TargetFrameworkNetStandard)' OR '$(TargetFramework)' == '$(TargetFrameworkNetCore)' ">
		<PackageReference Include="Microsoft.Data.Sqlite" Version="6.0.11" />
	</ItemGroup>


	<ItemGroup Condition=" '$(TargetFramework)' == '$(TargetFrameworkNet7)' ">
		<PackageReference Include="Microsoft.Data.Sqlite" Version="7.0.0" />
	</ItemGroup>

```

IMO, You need to check which version `Microsoft.Data.Sqlite` you are using, and check the dependencies of this version

**Comment by sylverbee** [comment]
Thks for your returns. I also use Microsoft.Data.Sqlite 7.0.1, and previous versions till begining.
That' first time I've got pb (46 updates!)

**Comment by sylverbee** [comment]
Just a question : are you using w10 or 11? I'm under 11, could it be a pb? 
Also, do you run WACK before publishing? Because I also get this error.

**Comment by VagueGit** [comment]
@sylverbee we publish to the Micro$ store from a Win11 machine. We didn't run WACK. The app was last certified and published to the store on 6 January 2023.

Maybe it is a WACK thing? WACK does have a troubled history. We only run WACK if certification fails and we can't work out why.

**Comment by sylverbee** [comment]
With all your replies, I updated my nuggets to use Microsoft.Data.Sqlite 0.6.13 and Dotmim 0.9.4.
But I continue to have the problem, with WACK, and from Microsoft as my last submission has been rejected. 
I'm a bit lost as its the first time I face this situation

**Comment by VagueGit** [comment]
I don't have SQLite.Interop.dll anywhere in my solution so It must not be part of DMS.SQLite nor Microsoft.Data.SQLite. Do you know where it is used in your solution?

**Comment by sylverbee** [comment]
@VagueGit I don't know, as it's the first time I face this pb. I still use the same nuggets.
I checked each nugget, and none mentions a dependency on SQLite.Interop.dll

**Comment by sylverbee** [comment]
I found the nugget that makes this call : Serilog.Sinks.SQLite 5.5.0.
The version 5.0.0 is OK

**Comment by Mimetis** [comment]
Good to know, thanks @sylverbee !

**Comment by Mimetis** [comment]
Can we close this issue, now that you've found the issue ?
