### ISSUE TITLE
Did not worked in xamarin

### ISSUE THREAD

**Issue by Diledio** [Mimetis/Dotmim.Sync#942]
Everything worked in console app but in xamarin does not,
I have a xamarin app where to synchrinise data from  sql server to sqlite with this tool,
here is the code:
 private async void Button_Clicked_1(object sender, EventArgs e)
            {

            try
            {
                // Use this when you want to use sqlite on ios
                SQLitePCL.Batteries_V2.Init();

                // 10.0.2.2 is a special url to be able to reach the machine localhost web api
                var serverOrchestrator = new SqlSyncProvider("Data Source=.;Initial Catalog=test1;User ID=sa;Password=test.sa");

                // Path the local sqlite database
                string dbPath = Path.Combine(Xamarin.Essentials.FileSystem.AppDataDirectory, "database.db");

                var setup = new SyncSetup("A_Users");

                // Sqlite Client provider
                var clientProvider = new SqliteSyncProvider(dbPath);

                // Creating an agent that will handle all the process
                var agent = new SyncAgent(clientProvider, serverOrchestrator);

                // Launch the sync process
                var s1 = await agent.SynchronizeAsync(setup);

                // See results
                lblResult.Text = s1.ToString();
            }
            catch (Exception ex)
            {
                lblResult.Text = ex.Message;
            }
When button is clicked it shows : Strings.PlatformnotSupported_DataSqlClient,
Please help,
Thank you

**Comment by Mimetis** [comment]
You have a sample in the sample directory : https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/XamAppSync

**Comment by Diledio** [comment]
This is not what i am looking for, i watch this https://github.com/Mimetis/Dotmim.Sync/issues/368 when you did a sample function button clicked with asp.netcore api but what i need is with sql server, 
when i click button it shows Strings.PlatformnotSupported_DataSqlClient,, i guess is the configure with sql server and i do not know how to configure it, like you did in this link with web api, 
any help please
Thank you so much

**Comment by Mimetis** [comment]
from a mobile application, you can't reach directly SQL server, you need a web Api in between.

**Comment by Diledio** [comment]
yes i can access sql server in xamarin with connection string, but now i am developing an offline app with sqlite, and you think the best way to sync between sql server and sqlite is to build a web api? 
Thank you

**Comment by Mimetis** [comment]
Yes, this is the way to do it, as your server database should not be exposed on internet

**Comment by Diledio** [comment]
Okay thank you so much i will try it :)

**Comment by Diledio** [comment]
Hi again,
I did it with web api , here is my code in button clicked
private async void Button_Clicked_1(object sender, EventArgs e)
            {

            try
            {

                SQLitePCL.Batteries_V2.Init();

                // 10.0.2.2 is a special url to be able to reach the machine localhost web api
                var serverOrchestrator = new WebRemoteOrchestrator("https://localhost:111111/api/sync");

                // Path the local sqlite database
                string dbPath = Path.Combine(Xamarin.Essentials.FileSystem.AppDataDirectory, "WH.db");

                
                // Sqlite Client provider
                var clientProvider = new SqliteSyncProvider(dbPath);

                // Creating an agent that will handle all the process
                var agent = new SyncAgent(clientProvider, serverOrchestrator);

                var progress = new Progress<ProgressArgs>(args => lblProgress.Text = $"{args.Context.SyncStage}:{args.Message}");

                // Launch the sync process
                var s1 = await agent.SynchronizeAsync(progress);

                // See results
                lblResult.Text = s1.ToString();
            }
            catch (Exception ex)
            {
                lblResult.Text = ex.Message;
            }

        }
It said end session connection refused Scopename.Defaultscope,
Any solution please?
Thank you

**Comment by Diledio** [comment]
I think the error come from the connection with database sqlite, i changed the path of local sqlite database because my sqlite is in android asset with this : string dbPath = Path.Combine(Xamarin.Essentials.FileSystem.AppDataDirectory, "WH.db"); i cannot access
i changed it to var sqliteFilename = "WH.db";

                var stream = await FileSystem.OpenAppPackageFileAsync(sqliteFilename);

                var reader = new StreamReader(stream);

                var fileContents = await reader.ReadToEndAsync();
and it said illegal character in path

**Comment by Mimetis** [comment]
I'm sorry, I think you have some issues accessing the web api and your local database.
Nothing I can help you here.
Maybe you should try the sample: https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/XamAppSync and see if it's working for you
- Are you testing from the emulator running on your machine ?
- Are you testing from a real device ? IOS ? Android ?

**Comment by Diledio** [comment]
im testing from emulator
do you have any idea how to access db file in android assets into xamarin forms path?

**Comment by Mimetis** [comment]
no idea, i'm using SQLite as a database provider only

**Comment by Diledio** [comment]
Look what i have did, 
This was your code: 
string dbPath = Path.Combine(Xamarin.Essentials.FileSystem.AppDataDirectory, "SqliteDatabase4.db3");
 var clientProvider = new SqliteSyncProvider(dbPath);

My code:

**Comment by Diledio** [comment]
var stream = await Xamarin.Essentials.FileSystem.OpenAppPackageFileAsync("AgnaWH.db");

                var reader = new StreamReader(stream);
                    
                var fileContents = await reader.ReadToEndAsync();
                var clientProvider = new SqliteSyncProvider(fileContents);
               
               
![photo](https://user-images.githubusercontent.com/87453241/214787782-318ca92b-a447-401e-836a-8bc1d5d7172f.png)

My question how to sync this db in android assset by sqliteprovider with web api i have created

**Comment by Mimetis** [comment]
make no sense to read a sqlite database as a stream...
You need to put the datatabase in a special folder, that is allowed, like `Xamarin.Essentials.FileSystem.AppDataDirectory`

**Comment by Diledio** [comment]
yes i have put it as android asset, 
now in xamarin forms to read this sqlite database is
string dbPath = Path.Combine(Xamarin.Essentials.FileSystem.AppDataDirectory, "SqliteDatabase4.db3");?

**Comment by Mimetis** [comment]
I dont know

**Comment by Diledio** [comment]
okay no problem it seems it works but its my fault, thank you so much

**Comment by Diledio** [comment]
the problem was at url of web api it was with localhost but i changed from

var serverOrchestrator = new WebRemoteOrchestrator("http://localgost:5001/api/sync"); 

to

 var serverOrchestrator = new WebRemoteOrchestrator("http://10.150.2.101:5001/api/sync"); 

Any solution for this?


![Screenshot_1674730803](https://user-images.githubusercontent.com/87453241/214819894-ff9d0f9d-87d1-4435-b1b9-9ede76c837fd.png)

**Comment by Mimetis** [comment]
Nice !
Will close the issue if you resolved it
