### ISSUE TITLE
Configure in xamarin

### ISSUE THREAD

**Issue by Diledio** [Mimetis/Dotmim.Sync#946]
Hi again

your code
// 10.0.2.2 is a special url to be able to reach the machine localhost web api
var serverOrchestrator = new WebClientOrchestrator("http://10.0.2.2:50886/api/sync");

mine
var serverOrchestrator = new WebRemoteOrchestrator("https://localhost:44310/api/sync");

do i have to have this url with ip? is this the problem that i am not syncing

![Screenshot_1674736815](https://user-images.githubusercontent.com/87453241/214837787-e0a0b6a2-2920-4246-ab53-aa7f2175ad50.png)

**Comment by Mimetis** [comment]
I guess you will have all the information you need here: https://learn.microsoft.com/en-us/xamarin/cross-platform/deploy-test/connect-to-local-web-services

**Comment by Diledio** [comment]
My button clicked code in xamarin

 private async void Button_Clicked_1(object sender, EventArgs e)
            {

            try
            {

                SQLitePCL.Batteries_V2.Init();

                // 10.0.2.2 is a special url to be able to reach the machine localhost web api
                var serverOrchestrator = new WebRemoteOrchestrator("http://10.0.2.2:7959/api/sync");

                // Sqlite Client provider
                //string dbPath = Path.Combine(Xamarin.Essentials.FileSystem.AppDataDirectory, "AgnaWH.db");




                var sqliteFilename = "AgnaWH.db";
                string documentsDirectoryPath = System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal);
                var path = Path.Combine(documentsDirectoryPath, sqliteFilename);
                string dbPath = Path.Combine(Xamarin.Essentials.FileSystem.AppDataDirectory, "AgnaWH.db");


                var clientProvider = new SqliteSyncProvider(path);
                
                // Creating an agent that will handle all the process
                var agent = new SyncAgent(clientProvider, serverOrchestrator);

                var progress = new Progress<ProgressArgs>(args => lblProgress.Text = $"{args.Context.SyncStage}:{args.Message}");

                // Launch the sync process
                var s1 = await agent.SynchronizeAsync(progress);

                // See results
                lblResult.Text = s1.ToString();
            }
            catch (Exception ex)
            {
                lblResult.Text = ex.Message;
            }

            }

Asp.Net Core Web Api

[Route("api/[controller]")]
    [ApiController]
    public class SyncController : ControllerBase
    {
        private WebServerAgent webServerAgent;

        // Injected thanks to Dependency Injection
        public SyncController(WebServerAgent webServerAgent) => this.webServerAgent = webServerAgent;

        /// <summary>
        /// [Optional] This Get request is just here to show a default page
        /// </summary>
        [HttpGet]
        public async Task Get()
        {
            await this.HttpContext.WriteHelloAsync(webServerAgent);
        }

        /// <summary>
        /// [Required] This Post request is called by the all Dotmim.Sync.Web.Client apis
        /// </summary>
        [HttpPost]
        public async Task Post()
        {
            await webServerAgent.HandleRequestAsync(this.HttpContext);
        }



    }


public void ConfigureServices(IServiceCollection services)
        {

            services.AddControllers();

            services.AddMemoryCache();

            var connectionString = Configuration.GetSection("ConnectionStrings")["DefaultConnection"];
            var tables = new string[] { "A_Users"};
            var syncSetup = new SyncSetup(tables);
            services.AddSyncServer<SqlSyncProvider>(connectionString, syncSetup);
            services.AddSwaggerGen();
        }
![Screenshot_1674745154](https://user-images.githubusercontent.com/87453241/214869411-ce5c01b4-9b3d-4ec4-8ff2-bd44f033289b.png)

**Comment by Diledio** [comment]
This is done, thank you so much
