### ISSUE TITLE
The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception

### ISSUE THREAD

**Issue by mzeesam** [Mimetis/Dotmim.Sync#952]
Getting the above error when the below line is executed:
await agent.SynchronizeAsync(setup);

My code:
 ```
 private readonly string remoteCon = "Server=*******; Database=SIRC;TrustServerCertificate=True;User Id=sa;Password=******.";
private readonly string localCon = Path.Combine(FileSystem.AppDataDirectory, "SIRC.db3");

                var serverProvider = new SqlSyncProvider(remoteCon);
                var clientProvider = new SqliteSyncProvider(localCon);

                var setup = new SyncSetup("BusinessUnits");
                //var filter = new SetupFilter("raiserFilter");
                //filter.AddParameter("OriginatorUser", "SIRs", false, App.UserInfo.UserId);
                //filter.Parameters[0].DbType = System.Data.DbType.Guid;
                // add this filter to setup
                //setup.Filters.Add(filter);
                var agent = new SyncAgent(clientProvider, serverProvider);

                var syncContext = await agent.SynchronizeAsync(setup); //error here
                statusMessage = syncContext.ToString();
```

Below is the stack trace:
The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
   at Dotmim.Sync.Sqlite.SqliteSyncProvider.CreateConnection()
   at Dotmim.Sync.LocalOrchestrator.InternalBeginSessionAsync(SyncContext context, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.Sqlite.SqliteSyncProvider.CreateConnection()
   at Dotmim.Sync.LocalOrchestrator.InternalEndSessionAsync(SyncContext context, SyncResult result, ClientSyncChanges clientSyncChanges, ServerSyncChanges serverSyncChanges, CancellationToken cancellationToken, IProgress`1 progress)
   at Dotmim.Sync.SyncAgent.SynchronizeAsync(String scopeName, SyncSetup setup, SyncType syncType, SyncParameters parameters, CancellationToken cancellationToken, IProgress`1 progress)
   at SIRC.Maui.Services.SyncService.SyncData() in C:\Users\Hp\source\repos\SIRC\SIRC.Maui\Services\SyncService.cs:line 39

**Comment by Mimetis** [comment]
Can you show me the value of `localCon` ?

**Comment by Mimetis** [comment]
BTW, you can't access directly a SQL Server instance directly from Xamarin.

Please see this example, if you are building a mobile xamarin application : https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/XamAppSync

**Comment by mzeesam** [comment]
> Can you show me the value of `localCon` ?

The value of localCon is : **/data/user/0/com.companyname.eablsirc/files/SIRC.db3** 
This is the path of the SQLite database on my android emulator.

**Comment by mzeesam** [comment]
> BTW, you can't access directly a SQL Server instance directly from Xamarin.
> 
> Please see this example, if you are building a mobile xamarin application : https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/XamAppSync

Thanks, let me go through this sample. I am implementing a sync function in .net MAUI. This is an exisiting application with both SQLite and SQL server as existing databases. Wanted to include my library in my existing android foreground service.

**Comment by Mimetis** [comment]
You have also a MAUI example here : https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/MAUI

**Comment by mzeesam** [comment]
> You have also a MAUI example here : https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/MAUI

Thank you, let me follow this route.

**Comment by mzeesam** [comment]
Hi @Mimetis 
I trust you are well. I have implemented the the sync using the MAUI sample provided and it is working fine on a simple table. 
However, when I implement on a different table with filters, no synchronization takes place but I always get success message as shown below:
```
Synchronization done. 
	Total changes  uploaded: 0
	Total changes  downloaded: 0 
	Total changes  applied on client: 0 
	Total changes  applied on server: 0 
	Total changes  failed to apply on client: 0
	Total changes  failed to apply on server: 0
	Total resolved conflicts: 0
```
This is my client call with two parameters:
```
 this.syncAgent = DependencyService.Get<ISyncServices>().GetSyncAgent();
            this.settings = DependencyService.Get<ISettingServices>();

            Task.Run(async () =>
            {
                bool isBusy = false;
                while (true)
                {
                    if (isBusy) continue;
                    isBusy = true;
                    try
                    {
                        //Call Sync
                        this.syncAgent.LocalOrchestrator.OnConflictingSetup(async args =>
                        {
                            await this.syncAgent.LocalOrchestrator.DeprovisionAsync(connection: args.Connection, transaction: args.Transaction);
                            await this.syncAgent.LocalOrchestrator.ProvisionAsync(args.ServerScopeInfo, connection: args.Connection, transaction: args.Transaction);
                            args.Action = ConflictingSetupAction.Continue;
                        });
                        var parameters = new SyncParameters
                            {
                                { "OriginatorUser",App.UserInfo.UserId},
                                { "CloserUser",App.UserInfo.UserId}
                            };
                        var r = await this.syncAgent.SynchronizeAsync(SyncType.Normal, parameters,null);
                        System.Diagnostics.Debug.WriteLine($"{r}");

                    }
                    catch (Exception ex)
                    {
                        System.Diagnostics.Debug.WriteLine($"Sync Error: {ex.Message}");
                    }
                    finally { isBusy = false; }
                    Thread.Sleep(30000);
                }
            });
```
And my server API setup:

```
builder.Services.AddDistributedMemoryCache();
builder.Services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));
var connectionString = builder.Configuration.GetSection("ConnectionStrings")["dbcon"];
var setup = new SyncSetup("SIRs");
var sirsFilter = new SetupFilter("SIRs");
//filter by Raiser or Closer
sirsFilter.AddParameter("OriginatorUser", "SIRs", false);
sirsFilter.AddParameter("CloserUser", "SIRs", false);
[SIRs_table_schema.txt](https://github.com/Mimetis/Dotmim.Sync/files/10608996/SIRs_table_schema.txt)

sirsFilter.AddWhere("OriginatorUser", "SIRs", "OriginatorUser");
//sirsFilter.AddCustomWhere("{{{OriginatorUser}}} = @OriginatorUser OR {{{CloserUser}}} = @CloserUser");

sirsFilter.Parameters[0].DbType = System.Data.DbType.String;
sirsFilter.Parameters[1].DbType = System.Data.DbType.String;
// add this filter to setup
setup.Filters.Add(sirsFilter);

// add a SqlSyncProvider acting as the server hub
builder.Services.AddSyncServer<SqlSyncProvider>(connectionString, setup);
```
I have attached my table client's SQlite model class and SQL server's table schema
(https://github.com/Mimetis/Dotmim.Sync/files/10608997/SIRs_table_schema.txt)
[Sir.txt](https://github.com/Mimetis/Dotmim.Sync/files/10609002/Sir.txt)

Once more thanks a lot for your contribution.
