### ISSUE TITLE
Sync Conflict in xamarin multiuser

### ISSUE THREAD

**Issue by Diledio** [Mimetis/Dotmim.Sync#953]
Hello again, 
Im afraid i need your help again,
Im testing the synchronization in two android devices 
In each device user is inserting in the same table, 
Firstly, when a user insert and clicked sync button the sync is done
Secondly, when a user in the other device also insert and clicked syc button the sync doesnt worked, only download from server, not upload to server, it shows a conflict
Thank you

**Comment by Mimetis** [comment]
then you have a conflict somewhere I guess

**Comment by Diledio** [comment]
But why it shows conflict where there is nothing wrong?
so again im doing bidirectional sync, 
In the first android device, user insert to sqlite make sync with server is okay, the value is uploaded there in sqlserver
Also, In the second device another user is insertin to sqlite and when the sync is done it said: upload 1, download 1, applied in client 1, APPLIED IN SERVER 0(SHOULD BE 1) and conflict 1, i dont know why

**Comment by Mimetis** [comment]
what is your primary key ?
Identity ?

**Comment by Diledio** [comment]
I have the same table in sql server also in sqlite in android
The table Users with columns loginID, name, password(loginID is primary key auto incremental)
So, in the first andoid device im creating a new user name and password, it created and also is synced in server without problem(loginID incremental, name, password),
In the second android device im creating a new user with different name and password, it created and synced said: upload 1(the user i create), download 1(the user where device1 created) applied in client 1, and applied in server should be 1 but is 0(the user i create) and conflict 1

**Comment by Mimetis** [comment]
> The table Users with columns loginID, name, password(loginID is primary key auto incremental)
This is your problem
Both android client application is creating a record with the same loginID

First one is correctly synced to server (as the loginID is not existing yet on server side)
Second one wants to perform an insert of a loginID that already exist on server, then you have a conflict

As server is wining the conflict, by default, it will not overwrite the first record sent from first client, will generate a conflict and will sent you back the first record on client

**Comment by Diledio** [comment]
Yeap this is, they creating records with the same id
do you have any idea how to solve it by your experience?

**Comment by Mimetis** [comment]
Replace your primary keys with GUID

**Comment by Diledio** [comment]
Im gonna try it now, hope it will work thank you

**Comment by Diledio** [comment]
Sqlite doesnt have Guid

**Comment by Mimetis** [comment]
If you let DMS creates the table (SQLITE) for you, it will creates it as string

**Comment by Diledio** [comment]
Do you have any sample?

**Comment by Mimetis** [comment]
https://dotmimsync.readthedocs.io/
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/HelloSync
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/Dotmim.Sync.SampleConsole
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/Batchsize
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/ComplexFilter
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/ConflictHandling
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/HelloMultiScopesSync
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/HelloWebSync
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/MAUI
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/MutliOrchestratorsWebSync
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/Orchestrators
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/OutDated
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/Progression
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/ProvisionDeprovision
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/SimpleFilter
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/Spy
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/SqliteEncryption
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/SyncType
https://github.com/Mimetis/Dotmim.Sync/tree/master/Samples/XamAppSync


IF for some reasons, you are not able to navigate to the hundreds of examples, here is one code from the main page:

``` cs
// Sql Server provider, the "server" or "hub".
SqlSyncProvider serverProvider = new SqlSyncProvider(
   @"Data Source=.;Initial Catalog=AdventureWorks;Integrated Security=true;");

// Sqlite Client provider acting as the "client"
SqliteSyncProvider clientProvider = new SqliteSyncProvider("advworks.db");

// Tables involved in the sync process:
var setup = new SyncSetup("ProductCategory", "ProductDescription", "ProductModel",
 "Product", "ProductModelProductDescription", "Address", "Customer",
 "CustomerAddress", "SalesOrderHeader", "SalesOrderDetail" );

// Sync agent
SyncAgent agent = new SyncAgent(clientProvider, serverProvider);

do
{
   var result = await agent.SynchronizeAsync(setup);
   Console.WriteLine(result);

} while (Console.ReadKey().Key != ConsoleKey.Escape);
```

**Comment by Mimetis** [comment]
If your table is not existing in SQLite, it's automatically created by DMS on first call.
You have all the samples available.
As it seems you don't have an issue here, I will close the issue, until you have found an issue related to DMS.
If you need more information, I will suggest you read the docs and make your own tests.
Then, if you need more information, you can use the Q&A section of the discussions tab.
