### ISSUE TITLE
How to join two tables on two columns

### ISSUE THREAD

**Issue by mostafa4c** [Mimetis/Dotmim.Sync#957]
The relationship like this

`SELECT        dbo.BLI.ModifyDate
FROM            dbo.BLD LEFT OUTER JOIN
                         dbo.BLI ON dbo.BLD.BLID = dbo.BLI.BLID AND dbo.BLD.BLNo = dbo.BLI.BLNo`

**Comment by Mimetis** [comment]
Use `CustomWhere`

**Comment by mostafa4c** [comment]
Ok Thanks
