### ISSUE TITLE
Your version is 0.9.7 and you need to manually upgrade your client to be able to use the current verison 0.9.8

### ISSUE THREAD

**Issue by ricardoamm** [Mimetis/Dotmim.Sync#963]
I get the following error after upgrade.

Dotmim.Sync.SyncException: 'Your version is 0.9.7 and you need to manually upgrade your client to be able to use the current verison 0.9.8.
Your scope_info table contains setup with filters that need to be migrated manually, as new version needs the parameters values saved in the scope_info table and they are not present in the scope_info table version 0.9.7.
Please see this discussion on how to migrate to your version to the last one : https://github.com/Mimetis/Dotmim.Sync/discussions/802#discussioncomment-3594681

I thought the migration was automatically. The manual UpgradeAsync is not available anymore.

**Comment by Mimetis** [comment]
Can you share with me your tables `sync_scope` and `sync_scope_client` ?

**Comment by ricardoamm** [comment]
`sync_scope_name	sync_scope_schema	sync_scope_setup	sync_scope_version	sync_scope_last_clean_timestamp	sync_scope_properties
CDA	{"t":[{"n":"Unidades","s":"","op":"SqlSyncProvider, Dotmim.Sync.SqlServer.SqlSyncProvider","c":[{"n":"Unidade","dt":"17","iu":true,"iuc":true,"ml":5,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"Descricao","dt":"17","an":true,"iu":true,"iuc":true,"ml":50,"o":1,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"Arredondamento","dt":"6","an":true,"o":2,"ps":true,"p1":10,"odb":"Int","oty":"int","db":11,"dv":"(0)"}],"pk":["Unidade"]},{"n":"Familias","s":"","op":"SqlSyncProvider, Dotmim.Sync.SqlServer.SqlSyncProvider","c":[{"n":"Familia","dt":"17","iu":true,"iuc":true,"ml":10,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"Descricao","dt":"17","an":true,"iuc":true,"ml":35,"o":1,"odb":"NVarChar","oty":"nvarchar","db":23}],"pk":["Familia"]},{"n":"SubFamilias","s":"","op":"SqlSyncProvider, Dotmim.Sync.SqlServer.SqlSyncProvider","c":[{"n":"Familia","dt":"17","iu":true,"iuc":true,"ml":10,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"SubFamilia","dt":"17","iuc":true,"ml":10,"o":1,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"Descricao","dt":"17","an":true,"iuc":true,"ml":35,"o":2,"odb":"NVarChar","oty":"nvarchar","db":23}],"pk":["Familia","SubFamilia"]},{"n":"Artigo","s":"","op":"SqlSyncProvider, Dotmim.Sync.SqlServer.SqlSyncProvider","c":[{"n":"Artigo","dt":"17","iu":true,"iuc":true,"ml":48,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"Descricao","dt":"17","an":true,"iuc":true,"ml":50,"o":1,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"UnidadeVenda","dt":"17","an":true,"iuc":true,"ml":5,"o":2,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"UnidadeBase","dt":"17","iuc":true,"ml":5,"o":3,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"Iva","dt":"17","iuc":true,"ml":2,"o":4,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"Desconto","dt":"5","an":true,"o":5,"ps":true,"p1":24,"ss":true,"odb":"Real","oty":"real","db":15,"dv":"((0))"},{"n":"MovStock","dt":"17","an":true,"iuc":true,"ml":1,"o":6,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"Familia","dt":"17","an":true,"iuc":true,"ml":10,"o":7,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"TipoArtigo","dt":"17","iuc":true,"ml":3,"o":8,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"TipoComponente","dt":"8","an":true,"o":9,"ps":true,"p1":5,"odb":"SmallInt","oty":"smallint","db":10,"dv":"((0))"},{"n":"NecessarioRecalcPCM","dt":"1","o":10,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"SugestaoPrComposto","dt":"8","an":true,"o":11,"ps":true,"p1":5,"odb":"SmallInt","oty":"smallint","db":10,"dv":"((0))"},{"n":"PrazoEntrega","dt":"8","an":true,"o":12,"ps":true,"p1":5,"odb":"SmallInt","oty":"smallint","db":10,"dv":"((0))"},{"n":"SubFamilia","dt":"17","an":true,"iuc":true,"ml":10,"o":13,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"Peso","dt":"4","an":true,"o":14,"ps":true,"p1":38,"ss":true,"odb":"Float","oty":"float","db":8,"dv":"((0))"},{"n":"Volume","dt":"4","an":true,"o":15,"ps":true,"p1":38,"ss":true,"odb":"Float","oty":"float","db":8,"dv":"((0))"},{"n":"ArtigoAnulado","dt":"1","o":16,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"IntrastatPeso","dt":"4","an":true,"o":17,"ps":true,"p1":38,"ss":true,"odb":"Float","oty":"float","db":8,"dv":"((0))"},{"n":"TestaNumSerie","dt":"1","o":18,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"SujeitoRetencao","dt":"1","o":19,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"DimLote","dt":"1","o":20,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"TratamentoDim","dt":"8","o":21,"ps":true,"p1":5,"odb":"SmallInt","oty":"smallint","db":10,"dv":"((0))"},{"n":"OperacaoTesouraria","dt":"1","o":22,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"UnidadeCompra","dt":"17","an":true,"iuc":true,"ml":5,"o":23,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"UnidadeEntrada","dt":"17","an":true,"iuc":true,"ml":5,"o":24,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"UnidadeSaida","dt":"17","an":true,"iuc":true,"ml":5,"o":25,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"DeduzIvaNoImo","dt":"1","o":26,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"PermiteDevolucao","dt":"1","o":27,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((1))"},{"n":"Imposto","dt":"1","o":28,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"UtilizadoCCOP","dt":"1","o":29,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"Pesar","dt":"1","o":30,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"SujeitoProRata","dt":"1","o":31,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"PercIvaDedutivel","dt":"5","an":true,"o":32,"ps":true,"p1":24,"ss":true,"odb":"Real","oty":"real","db":15,"dv":"((100))"},{"n":"SujeitoEcotaxa","dt":"1","o":33,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"Ecovalor","dt":"4","an":true,"o":34,"ps":true,"p1":38,"ss":true,"odb":"Float","oty":"float","db":8},{"n":"AfectaPCM","dt":"1","o":35,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"ArtigoPai","dt":"17","an":true,"iuc":true,"ml":48,"o":36,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"OrdemDim","dt":"6","an":true,"o":37,"ps":true,"p1":10,"odb":"Int","oty":"int","db":11,"dv":"((0))"},{"n":"PercIncidenciaIVA","dt":"4","an":true,"o":38,"ps":true,"p1":38,"ss":true,"odb":"Float","oty":"float","db":8,"dv":"((100))"},{"n":"NaturezaAnalitica","dt":"6","an":true,"o":39,"ps":true,"p1":10,"odb":"Int","oty":"int","db":11},{"n":"IdClassificacao","dt":"16","an":true,"o":40,"odb":"UniqueIdentifier","oty":"uniqueidentifier","db":9},{"n":"SujeitoIEC","dt":"1","an":true,"o":41,"p1":1,"odb":"Bit","oty":"bit","db":3},{"n":"CategoriaIEC","dt":"17","an":true,"iuc":true,"ml":10,"o":42,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"CodigoTaric","dt":"17","an":true,"iuc":true,"ml":14,"o":43,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"EmbalagemIEC","dt":"17","an":true,"iuc":true,"ml":2,"o":44,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"CapacidadeEmbIEC","dt":"4","an":true,"o":45,"ps":true,"p1":38,"ss":true,"odb":"Float","oty":"float","db":8},{"n":"UnidadeTaric","dt":"17","an":true,"iuc":true,"ml":5,"o":46,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"FactConvIEC","dt":"4","an":true,"o":47,"ps":true,"p1":38,"ss":true,"odb":"Float","oty":"float","db":8},{"n":"ValorIEC","dt":"4","an":true,"o":48,"ps":true,"p1":38,"ss":true,"odb":"Float","oty":"float","db":8},{"n":"TaxaAlcool","dt":"4","an":true,"o":49,"ps":true,"p1":38,"ss":true,"odb":"Float","oty":"float","db":8},{"n":"UtilManutencao","dt":"1","an":true,"o":50,"p1":1,"odb":"Bit","oty":"bit","db":3},{"n":"PesoLiquido","dt":"4","an":true,"o":51,"ps":true,"p1":38,"ss":true,"odb":"Float","oty":"float","db":8},{"n":"GestaoSingular","dt":"1","o":52,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"FactorUnidadeSup","dt":"5","o":53,"ps":true,"p1":24,"ss":true,"odb":"Real","oty":"real","db":15,"dv":"((1))"},{"n":"IsentoPagDireitos","dt":"1","o":54,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"ControlaTransformacaoValor","dt":"1","an":true,"o":55,"p1":1,"odb":"Bit","oty":"bit","db":3},{"n":"IsentoIEC","dt":"1","o":56,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"TipoCusteio","dt":"2","o":57,"ps":true,"p1":3,"odb":"TinyInt","oty":"tinyint","db":2,"dv":"((0))"},{"n":"SujeitoRetencaoArtigo","dt":"1","an":true,"o":58,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"RetencaoArtigoValor","dt":"4","an":true,"o":59,"ps":true,"p1":38,"ss":true,"odb":"Float","oty":"float","db":8,"dv":"((0))"},{"n":"RetencaoArtigoTipoValor","dt":"1","an":true,"o":60,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"((0))"},{"n":"CDU_Owner","dt":"17","an":true,"iuc":true,"ml":5,"o":61,"odb":"NVarChar","oty":"nvarchar","db":23}],"pk":["Artigo"]},{"n":"ArtigoMoeda","s":"","op":"SqlSyncProvider, Dotmim.Sync.SqlServer.SqlSyncProvider","c":[{"n":"Artigo","dt":"17","iu":true,"iuc":true,"ml":48,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"Moeda","dt":"17","iuc":true,"ml":3,"o":1,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"Unidade","dt":"17","iuc":true,"ml":5,"o":2,"odb":"NVarChar","oty":"nvarchar","db":23}],"pk":["Artigo","Moeda","Unidade"]},{"n":"ArtigoUnidades","s":"","op":"SqlSyncProvider, Dotmim.Sync.SqlServer.SqlSyncProvider","c":[{"n":"Artigo","dt":"17","iu":true,"iuc":true,"ml":48,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"UnidadeOrigem","dt":"17","iu":true,"iuc":true,"ml":5,"o":1,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"UnidadeDestino","dt":"17","iuc":true,"ml":5,"o":2,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"UtilizaFormula","dt":"1","an":true,"o":3,"p1":1,"odb":"Bit","oty":"bit","db":3,"dv":"(0)"},{"n":"FactorConversao","dt":"4","an":true,"o":4,"ps":true,"p1":38,"ss":true,"odb":"Float","oty":"float","db":8,"dv":"(1)"},{"n":"Formula","dt":"17","an":true,"iuc":true,"ml":512,"o":5,"odb":"NVarChar","oty":"nvarchar","db":23},{"n":"ID","dt":"16","o":6,"odb":"UniqueIdentifier","oty":"uniqueidentifier","db":9,"dv":"(newsequentialid())"}],"pk":["ID"]}],"r":[{"n":"SubFamilias_Familias_FK","pks":[{"c":"Familia","t":"Familias","s":""}],"cks":[{"c":"Familia","t":"SubFamilias","s":""}]},{"n":"Artigo_Artigo_FK","pks":[{"c":"Artigo","t":"Artigo","s":""}],"cks":[{"c":"ArtigoPai","t":"Artigo","s":""}]},{"n":"Artigo_Familias_FK","pks":[{"c":"Familia","t":"Familias","s":""}],"cks":[{"c":"Familia","t":"Artigo","s":""}]},{"n":"Artigo_SubFamilias_FK","pks":[{"c":"Familia","t":"SubFamilias","s":""},{"c":"SubFamilia","t":"SubFamilias","s":""}],"cks":[{"c":"Familia","t":"Artigo","s":""},{"c":"SubFamilia","t":"Artigo","s":""}]},{"n":"Artigo_Unidades_FK01","pks":[{"c":"Unidade","t":"Unidades","s":""}],"cks":[{"c":"UnidadeBase","t":"Artigo","s":""}]},{"n":"Artigo_Unidades_FK02","pks":[{"c":"Unidade","t":"Unidades","s":""}],"cks":[{"c":"UnidadeVenda","t":"Artigo","s":""}]},{"n":"Artigo_Unidades_FK03","pks":[{"c":"Unidade","t":"Unidades","s":""}],"cks":[{"c":"UnidadeCompra","t":"Artigo","s":""}]},{"n":"Artigo_Unidades_FK04","pks":[{"c":"Unidade","t":"Unidades","s":""}],"cks":[{"c":"UnidadeEntrada","t":"Artigo","s":""}]},{"n":"Artigo_Unidades_FK05","pks":[{"c":"Unidade","t":"Unidades","s":""}],"cks":[{"c":"UnidadeSaida","t":"Artigo","s":""}]},{"n":"ArtigoMoeda_Artigo_FK","pks":[{"c":"Artigo","t":"Artigo","s":""}],"cks":[{"c":"Artigo","t":"ArtigoMoeda","s":""}]},{"n":"ArtigoMoeda_Unidades_FK","pks":[{"c":"Unidade","t":"Unidades","s":""}],"cks":[{"c":"Unidade","t":"ArtigoMoeda","s":""}]},{"n":"ArtigoUnidades_Artigo_FK","pks":[{"c":"Artigo","t":"Artigo","s":""}],"cks":[{"c":"Artigo","t":"ArtigoUnidades","s":""}]},{"n":"ArtigoUnidades_Unidades_FK01","pks":[{"c":"Unidade","t":"Unidades","s":""}],"cks":[{"c":"UnidadeOrigem","t":"ArtigoUnidades","s":""}]},{"n":"ArtigoUnidades_Unidades_FK02","pks":[{"c":"Unidade","t":"Unidades","s":""}],"cks":[{"c":"UnidadeDestino","t":"ArtigoUnidades","s":""}]}],"f":[{"t":"Familias","p":[{"n":"Destino","t":null,"dt":16}],"w":[],"j":[],"cw":["side.Familia IN (SELECT DISTINCT Familia FROM VW_SYNC_ARTIGOS_DESTINO WHERE Destino = @Destino)"]},{"t":"SubFamilias","p":[{"n":"Destino","t":null,"dt":16}],"w":[],"j":[],"cw":["side.SubFamilia IN (SELECT DISTINCT SubFamilia FROM VW_SYNC_ARTIGOS_DESTINO WHERE Destino = @Destino)"]},{"t":"Artigo","p":[{"n":"Destino","t":null,"dt":16}],"w":[],"j":[],"cw":["side.Artigo IN (SELECT DISTINCT Artigo FROM VW_SYNC_ARTIGOS_DESTINO WHERE Destino = @Destino)"]},{"t":"ArtigoMoeda","p":[{"n":"Destino","t":null,"dt":16}],"w":[],"j":[],"cw":["side.Artigo IN (SELECT DISTINCT Artigo FROM VW_SYNC_ARTIGOS_DESTINO WHERE Destino = @Destino)"]},{"t":"ArtigoUnidades","p":[{"n":"Destino","t":null,"dt":16}],"w":[],"j":[],"cw":["side.Id IN (SELECT DISTINCT au.Id FROM ArtigoUnidades au JOIN VW_SYNC_ARTIGOS_DESTINO vw ON au.Artigo = vw.Artigo WHERE vw.Destino = @Destino)"]}]}	{"tbls":[{"tn":"Unidades","sn":"","cols":["Unidade","Descricao","Arredondamento"],"sd":2},{"tn":"Familias","sn":"","cols":["Familia","Descricao"],"sd":2},{"tn":"SubFamilias","sn":"","cols":["Familia","SubFamilia","Descricao"],"sd":2},{"tn":"Artigo","sn":"","cols":["Artigo","Descricao","UnidadeVenda","UnidadeBase","Iva","Desconto","MovStock","Familia","TipoArtigo","TipoComponente","NecessarioRecalcPCM","SugestaoPrComposto","PrazoEntrega","SubFamilia","Peso","Volume","ArtigoAnulado","IntrastatPeso","TestaNumSerie","SujeitoRetencao","DimLote","TratamentoDim","OperacaoTesouraria","UnidadeCompra","UnidadeEntrada","UnidadeSaida","DeduzIvaNoImo","PermiteDevolucao","Imposto","UtilizadoCCOP","Pesar","SujeitoProRata","PercIvaDedutivel","SujeitoEcotaxa","Ecovalor","AfectaPCM","ArtigoPai","OrdemDim","PercIncidenciaIVA","NaturezaAnalitica","IdClassificacao","SujeitoIEC","CategoriaIEC","CodigoTaric","EmbalagemIEC","CapacidadeEmbIEC","UnidadeTaric","FactConvIEC","ValorIEC","TaxaAlcool","UtilManutencao","PesoLiquido","GestaoSingular","FactorUnidadeSup","IsentoPagDireitos","ControlaTransformacaoValor","IsentoIEC","TipoCusteio","SujeitoRetencaoArtigo","RetencaoArtigoValor","RetencaoArtigoTipoValor","CDU_Owner"],"sd":2},{"tn":"ArtigoMoeda","sn":"","cols":["Artigo","Moeda","Unidade"],"sd":2},{"tn":"ArtigoUnidades","sn":"","cols":["Artigo","UnidadeOrigem","UnidadeDestino","UtilizaFormula","FactorConversao","Formula","ID"],"sd":2}],"fils":[{"tn":"Familias","j":[],"cw":["side.Familia IN (SELECT DISTINCT Familia FROM VW_SYNC_ARTIGOS_DESTINO WHERE Destino = @Destino)"],"p":[{"n":"Destino","tn":null,"sn":null,"dt":16}],"w":[]},{"tn":"SubFamilias","j":[],"cw":["side.SubFamilia IN (SELECT DISTINCT SubFamilia FROM VW_SYNC_ARTIGOS_DESTINO WHERE Destino = @Destino)"],"p":[{"n":"Destino","tn":null,"sn":null,"dt":16}],"w":[]},{"tn":"Artigo","j":[],"cw":["side.Artigo IN (SELECT DISTINCT Artigo FROM VW_SYNC_ARTIGOS_DESTINO WHERE Destino = @Destino)"],"p":[{"n":"Destino","tn":null,"sn":null,"dt":16}],"w":[]},{"tn":"ArtigoMoeda","j":[],"cw":["side.Artigo IN (SELECT DISTINCT Artigo FROM VW_SYNC_ARTIGOS_DESTINO WHERE Destino = @Destino)"],"p":[{"n":"Destino","tn":null,"sn":null,"dt":16}],"w":[]},{"tn":"ArtigoUnidades","j":[],"cw":["side.Id IN (SELECT DISTINCT au.Id FROM ArtigoUnidades au JOIN VW_SYNC_ARTIGOS_DESTINO vw ON au.Artigo = vw.Artigo WHERE vw.Destino = @Destino)"],"p":[{"n":"Destino","tn":null,"sn":null,"dt":16}],"w":[]}]}	0.9.7	267	NULL`

'sync_scope_id	sync_scope_name	sync_scope_hash	sync_scope_parameters	scope_last_sync_timestamp	scope_last_server_sync_timestamp	scope_last_sync_duration	scope_last_sync	sync_scope_errors	sync_scope_properties
BE0806A7-26DB-4D16-A384-5D6BF747754A	CDA	ApqTxC8VqkxtAhWGuC7skhb95hBJ7gcHEsBvXQQV96w=	[{"pn":"Destino","v":"CPA"}]	290262184	735578163	791867	2023-01-27 16:38:20.743	NULL	NULL
E76727CC-8A2D-4B84-B398-64DF1DAACC3D	CDA	HfCF2Lv6R0dqSCJ+M0ktF/FCD4hJQcp6KJLkahIseyE=	[{"pn":"Destino","v":"MOL"}]	11840000	735578163	13740909	2023-01-27 16:38:07.133	NULL	NULL
95EF8F4D-19E8-43C1-9940-911B8C8F7F98	CDA	03dxcFbAd1VPsh0TpbldndK+wwSeU+gZqwdI39Ecq48=	[{"pn":"Destino","v":"PEP"}]	6482005	735578261	15493790	2023-02-01 10:36:21.833	NULL	NULL
B6E311C8-7A45-46E4-966F-D55C0149D51A	CDA	hT69CUVLayVwpBwV78LXq7SN60aNW9djEJ8GJVsebGk=	[{"pn":"Destino","v":"NGA"}]	219	329	90759144	2023-01-05 15:25:28.750	NULL	NULL'

**Comment by Mimetis** [comment]
Thanks @ricardoamm

You should not have to upgrade manually as your tables are already good (just one column missing)
I will look into it and fix the issue asap

Thanks !
