### ISSUE TITLE
Some of rows did not sync

### ISSUE THREAD

**Issue by Diledio** [Mimetis/Dotmim.Sync#966]
Hello, i am syncing one table or more with two databases, sqlserver and sqlite,
Some of the rows of table are syncing and others not,

**Comment by Diledio** [comment]
![Untitled](https://user-images.githubusercontent.com/87453241/219049138-ea7bb54a-de93-4b54-b8a8-7c1f788bf2ca.png)
In this table name password and roleid is synced, loginid not, i dont know where is the problem

**Comment by Diledio** [comment]
I made changes on name password roleid is everything okay, but for example when i change loginid it supposed to be synced to sqlite but is not

**Comment by Mimetis** [comment]
loginid is the primary key ?

**Comment by Diledio** [comment]
Nope, it is not
also when i synced 2 or more tables

var tables = new string[] { "Users", "Movs", "Head" };

The other table exept users did not synced

**Comment by Mimetis** [comment]
Need to see your code, I guess and an example to follow to reproduce

**Comment by Diledio** [comment]
Yes of course,
Here is the web api code,

public void ConfigureServices(IServiceCollection services)
        {
            try
            {
                services.AddControllers();

                //services.AddDistributedMemoryCache();
                //services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

                services.AddDistributedMemoryCache();
                services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));
                //services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

                var connectionString = Configuration.GetSection("ConnectionStrings")["DefaultConnection"];
                var tables = new string[] { "Movs", "Head", "Users" };
                var syncSetup = new SyncSetup(tables);
               
                services.AddSyncServer<SqlSyncProvider>(connectionString, syncSetup);
                services.AddSwaggerGen();
            }
            catch (Exception ex)
            {
                string sd = ex.Message;
            }


here i the code button clicked in xamarin

 try
            {

                SQLitePCL.Batteries_V2.Init();

                // 10.0.2.2 is a special url to be able to reach the machine localhost web api
                var serverOrchestrator = new WebRemoteOrchestrator("http://ip:45456/api/sync");

                // Sqlite Client provider


                var sqliteFilename = "ADB.db";
                string documentsDirectoryPath = System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal);
                var path = Path.Combine(documentsDirectoryPath, sqliteFilename);

               

                var clientProvider = new SqliteSyncProvider(path);
               
                // Creating an agent that will handle all the process
                var agent = new SyncAgent(clientProvider, serverOrchestrator);

                var progress = new Progress<ProgressArgs>(args => lblProgress.Text = $"{args.Context.SyncStage}:{args.Message}");

                // Launch the sync process
                var s1 = await agent.SynchronizeAsync(progress);

                // See results
                lblResult.Text = s1.ToString();
            }
            catch (Exception ex)
            {
                lblResult.Text = ex.Message;
            }

**Comment by Diledio** [comment]
Also i am trying into an console app to sync only Movs table and this is the error
How can i resolve it?
![ds](https://user-images.githubusercontent.com/87453241/219314256-b9f13359-ab50-4ce3-8b96-8d48f2edf806.png)

**Comment by Mimetis** [comment]
each time you are changing your setup, you need to create a new scope:

``` cs 
var setup = new SyncSetup("Movs", "Head", "Users" );
var agent = new SyncAgent(clientProvider, serverOrchestrator);

var r = await agent.SynchronizeAsync("all", setup);
```

``` cs 
var setup = new SyncSetup("Movs");
var agent = new SyncAgent(clientProvider, serverOrchestrator);

var r = await agent.SynchronizeAsync("only_movs", setup);
```

IF you are making a call to `SynchronizeAsync` without specifying the scope name, a default value is applied (`"DefaultScope"`)
Please see doc here: https://dotmimsync.readthedocs.io/Scopes.html#multi-scopes


if you are using a web api, you need to declare your scope as well:

``` cs
services.AddSyncServer<SqlSyncProvider>(connectionString, "all", setup_with_all_tables);
services.AddSyncServer<SqlSyncProvider>(connectionString, "movs", setup_with_one_table);
```
Please see doc here : https://dotmimsync.readthedocs.io/Web.html#multi-scopes

**Comment by Diledio** [comment]
Its getting error when i put "Movs
![dss](https://user-images.githubusercontent.com/87453241/219324053-182c4784-3418-4285-9478-0d2a25468f7f.png)
"

**Comment by Mimetis** [comment]
I think you are able to resolve it by yourself :)
Just look at the intelissense and add the missing pieces

**Comment by Diledio** [comment]
I tried like this but nothing works "cMovs" table did not synced

public void ConfigureServices(IServiceCollection services)
        {
            try
            {
                services.AddControllers();

                //services.AddDistributedMemoryCache();
                //services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

                services.AddDistributedMemoryCache();
                services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));
                //services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

                var connectionString = Configuration.GetSection("ConnectionStrings")["DefaultConnection"];
                var setupProducts = new SyncSetup("aUsers");
                var setupCustomers = new SyncSetup("cMovs");


                services.AddSyncServer<SqlSyncProvider>(connectionString, "products", setupProducts);
                services.AddSyncServer<SqlSyncProvider>(connectionString, "customers", setupProducts);
               
                services.AddSwaggerGen();
            }
            catch (Exception ex)
            {
                string sd = ex.Message;
            }
            
        }

**Comment by Mimetis** [comment]
not make any sense here:

``` cs
 var connectionString = Configuration.GetSection("ConnectionStrings")["DefaultConnection"];
            var setupProducts = new SyncSetup("aUsers");
            var setupCustomers = new SyncSetup("cMovs");


            services.AddSyncServer<SqlSyncProvider>(connectionString, "products", setupProducts);
            services.AddSyncServer<SqlSyncProvider>(connectionString, "customers", setupProducts);

```
you are adding two times the `setupProducts` in both scope

from you client side, do not forget to add the scope name when you call `SynchronizeAsync()`

Please make an effort to correctly write your markdown code, otherwise it will become uncormfortable for me to read

**Comment by Diledio** [comment]
This is my code in web api

 public void ConfigureServices(IServiceCollection services)
        {
            try
            {
                services.AddControllers();

                //services.AddDistributedMemoryCache();
                //services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

                services.AddDistributedMemoryCache();
                services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));
                //services.AddSession(options => options.IdleTimeout = TimeSpan.FromMinutes(30));

                var connectionString = Configuration.GetSection("ConnectionStrings")["DefaultConnection"];
                var tables = new string[] { "aUsers", "cMovs" };
               

                services.AddSyncServer<SqlSyncProvider>(connectionString,
                        "prod", tables);
               
                services.AddSwaggerGen();
            }
            catch (Exception ex)
            {
                string sd = ex.Message;
            }
            
        }



this is my code in client side by xamarin


 private async void Button_Clicked_1(object sender, EventArgs e)
        {

            try
            {

                SQLitePCL.Batteries_V2.Init();

                // 10.0.2.2 is a special url to be able to reach the machine localhost web api
                var serverOrchestrator = new WebRemoteOrchestrator("http://10.150.2.101:45456/api/sync");

                // Sqlite Client provider


                var sqliteFilename = "AGNAADB.db";
                string documentsDirectoryPath = System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal);
                var path = Path.Combine(documentsDirectoryPath, sqliteFilename);

                //var options = new SyncOptions { ConflictResolutionPolicy = ConflictResolutionPolicy.ClientWins };

                var clientProvider = new SqliteSyncProvider(path);
                //var clientOptions = new SyncOptions { BatchSize = 2000, S
                //copeInfoTableName = "A_Users" };
                // Creating an agent that will handle all the process
                
                var agent = new SyncAgent(clientProvider, serverOrchestrator);

                var progress = new Progress<ProgressArgs>(args => lblProgress.Text = $"{args.Context.SyncStage}:{args.Message}");

                // Launch the sync process
                var s1 = await agent.SynchronizeAsync(progress);

                // See results
                lblResult.Text = s1.ToString();
            }
            catch (Exception ex)
            {
                lblResult.Text = ex.Message;
            }

        }

**Comment by Diledio** [comment]
In this case, it synced only aUsers table, cMovs not, did not understand why, and what to do in this case
Before i have used this sync only to test it and i did with aUsers table it totally okay pretty good, now i want to sync cMovs, i add it but did not sync at all, any help please

**Comment by Diledio** [comment]
Solved it, Thank you
