### ISSUE TITLE
Deleted records in SQLServer are not deleted in SQLite

### ISSUE THREAD

**Issue by ricardoamm** [Mimetis/Dotmim.Sync#968]
Hi,

I'm facing the following situation, I have a bidirectional provisoning from SQL Server to SQLite.
All works ok, the deleted records in SQLite are deleted in SQL Server but in the opposite direction it doens't happen.
What I'm doing wrong?

Regards

**Comment by Mimetis** [comment]
Do you think you can make a small repro sample ?
Will be easier for me to debug and help you

**Comment by Mimetis** [comment]
Here is a small repro I have created in another issue, you can use to see what's the difference, and continue the discussion

https://github.com/Mimetis/Dotmim.Sync/issues/965#issuecomment-1434647649

**Comment by ricardoamm** [comment]
I don't see any difference. 
Here goes my SyncSetup:

`using System.Data;
using Dotmim.Sync;
using Dotmim.Sync.Enumerations;

namespace com.smartthink.sigo.server.sync.setup;

public class SigoDatabase
{
    public static string[] Tables =
    {
        "PermissionPolicyUser", "ErpCentros", "SigoCentrosCampBosses", "SigoCentrosSupervisores", "ErpDepartamentos",
        "ErpSituacoes", "ErpCategorias", "ErpFuncionarios", "ErpRemuneracoes", "ErpFaltas", "ErpHorasExtras",
        "SigoAtributosFuncionario", "SigoFuncionarioAtributos", "SigoEstadosTimeSheets", "SigoEstadosRegisto",
        "SigoCentrosMovimentos", "SigoTiposMovimentos", "SigoTimeSheets", "SigoTimeSheetsMovimentos",
        "SigoRegistoFaltas", "SigoRegistoFaltasMovimentos", "SigoRegistoOcorrencias", "SigoRegistoAcidentesTrabalho"
    };

    public static SyncSetup CreateSigoSyncSetup()
    {
        // Tables involved in the sync process:
        var setup = new SyncSetup(Tables);

        setup.Tables["ErpFaltas"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["ErpCentros"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["ErpSituacoes"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["ErpCategorias"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["ErpHorasExtras"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["ErpFuncionarios"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["ErpRemuneracoes"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["ErpDepartamentos"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["PermissionPolicyUser"].SyncDirection = SyncDirection.DownloadOnly;

        setup.Tables["SigoEstadosRegisto"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["SigoTiposMovimentos"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["SigoCentrosMovimentos"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["SigoCentrosCampBosses"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["SigoEstadosTimeSheets"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["SigoCentrosSupervisores"].SyncDirection = SyncDirection.DownloadOnly;
        setup.Tables["SigoAtributosFuncionario"].SyncDirection = SyncDirection.DownloadOnly;

        setup.Tables["SigoTimeSheets"].SyncDirection = SyncDirection.Bidirectional;
        setup.Tables["SigoRegistoFaltas"].SyncDirection = SyncDirection.Bidirectional;
        setup.Tables["SigoRegistoOcorrencias"].SyncDirection = SyncDirection.Bidirectional;
        setup.Tables["SigoFuncionarioAtributos"].SyncDirection = SyncDirection.Bidirectional;
        setup.Tables["SigoTimeSheetsMovimentos"].SyncDirection = SyncDirection.Bidirectional;
        setup.Tables["SigoRegistoFaltasMovimentos"].SyncDirection = SyncDirection.Bidirectional;
        setup.Tables["SigoRegistoAcidentesTrabalho"].SyncDirection = SyncDirection.Bidirectional;

        // Add filters

        var filterPermissionPolicyUser = new SetupFilter("PermissionPolicyUser");
        filterPermissionPolicyUser.AddParameter("UserName", "PermissionPolicyUser");
        filterPermissionPolicyUser.AddParameter("filterCampBoss", DbType.String);
        filterPermissionPolicyUser.AddParameter("IsActive", "PermissionPolicyUser");
        filterPermissionPolicyUser.AddParameter("active", DbType.Boolean, false, "true");
        filterPermissionPolicyUser.AddWhere("IsActive", "PermissionPolicyUser", "active");
        filterPermissionPolicyUser.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterPermissionPolicyUser);

        var filterCentros = new SetupFilter("ErpCentros");
        filterCentros.AddParameter("UserName", "PermissionPolicyUser");
        filterCentros.AddParameter("filterCampBoss", DbType.String);
        filterCentros.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("ErpCentros", "Armazem", "SigoCentrosCampBosses", "Centro");
        filterCentros.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterCentros.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterCentros);

        var filterCentrosCampBosses = new SetupFilter("SigoCentrosCampBosses");
        filterCentrosCampBosses.AddParameter("UserName", "PermissionPolicyUser");
        filterCentrosCampBosses.AddParameter("filterCampBoss", DbType.String);
        filterCentrosCampBosses.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterCentrosCampBosses.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterCentrosCampBosses);

        var filterDepartamentos = new SetupFilter("ErpDepartamentos");
        filterDepartamentos.AddParameter("UserName", "PermissionPolicyUser");
        filterDepartamentos.AddParameter("filterCampBoss", DbType.String);
        filterDepartamentos.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("ErpDepartamentos", "CDU_Centro", "SigoCentrosCampBosses", "Centro");
        filterDepartamentos.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterDepartamentos.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterDepartamentos);

        var filterSituacoes = new SetupFilter("ErpSituacoes");
        filterSituacoes.AddParameter("UserName", "PermissionPolicyUser");
        filterSituacoes.AddParameter("filterCampBoss", DbType.String);
        filterSituacoes.AddJoin(Join.Inner, "ErpFuncionarios")
            .On("ErpSituacoes", "Situacao", "ErpFuncionarios", "Situacao");
        filterSituacoes.AddJoin(Join.Inner, "ErpDepartamentos")
            .On("ErpFuncionarios", "CodDepartamento", "ErpDepartamentos", "Departamento");
        filterSituacoes.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("ErpDepartamentos", "CDU_Centro", "SigoCentrosCampBosses", "Centro");
        filterSituacoes.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterSituacoes.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterSituacoes);

        var filterFuncionarios = new SetupFilter("ErpFuncionarios");
        filterFuncionarios.AddParameter("UserName", "PermissionPolicyUser");
        filterFuncionarios.AddParameter("filterCampBoss", DbType.String);
        filterFuncionarios.AddJoin(Join.Inner, "ErpDepartamentos")
            .On("ErpFuncionarios", "CodDepartamento", "ErpDepartamentos", "Departamento");
        filterFuncionarios.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("ErpDepartamentos", "CDU_Centro", "SigoCentrosCampBosses", "Centro");
        filterFuncionarios.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterFuncionarios.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterFuncionarios);

        var filterCategorias = new SetupFilter("ErpCategorias");
        filterCategorias.AddParameter("UserName", "PermissionPolicyUser");
        filterCategorias.AddParameter("filterCampBoss", DbType.String);
        filterCategorias.AddJoin(Join.Inner, "ErpFuncionarios")
            .On("ErpCategorias", "Categoria", "ErpFuncionarios", "Categoria");
        filterCategorias.AddJoin(Join.Inner, "ErpDepartamentos")
            .On("ErpFuncionarios", "CodDepartamento", "ErpDepartamentos", "Departamento");
        filterCategorias.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("ErpDepartamentos", "CDU_Centro", "SigoCentrosCampBosses", "Centro");
        filterCategorias.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterCategorias.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterCategorias);

        var filterCentrosMovimentos = new SetupFilter("SigoCentrosMovimentos");
        filterCentrosMovimentos.AddParameter("UserName", "PermissionPolicyUser");
        filterCentrosMovimentos.AddParameter("filterCampBoss", DbType.String);
        filterCentrosMovimentos.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("SigoCentrosMovimentos", "Centro", "SigoCentrosCampBosses", "Centro");
        filterCentrosMovimentos.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterCentrosMovimentos.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterCentrosMovimentos);

        var filterCentrosSupervisores = new SetupFilter("SigoCentrosSupervisores");
        filterCentrosSupervisores.AddParameter("UserName", "PermissionPolicyUser");
        filterCentrosSupervisores.AddParameter("filterCampBoss", DbType.String);
        filterCentrosSupervisores.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("SigoCentrosSupervisores", "Centro", "SigoCentrosCampBosses", "Centro");
        filterCentrosSupervisores.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterCentrosSupervisores.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterCentrosSupervisores);

        var filterRegistoFaltas = new SetupFilter("SigoRegistoFaltas");
        filterRegistoFaltas.AddParameter("UserName", "PermissionPolicyUser");
        filterRegistoFaltas.AddParameter("filterCampBoss", DbType.String);
        filterRegistoFaltas.AddJoin(Join.Inner, "ErpFuncionarios")
            .On("SigoRegistoFaltas", "Funcionario", "ErpFuncionarios", "Codigo");
        filterRegistoFaltas.AddJoin(Join.Inner, "ErpDepartamentos")
            .On("ErpFuncionarios", "CodDepartamento", "ErpDepartamentos", "Departamento");
        filterRegistoFaltas.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("ErpDepartamentos", "CDU_Centro", "SigoCentrosCampBosses", "Centro");
        filterRegistoFaltas.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterRegistoFaltas.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterRegistoFaltas);

        var filterTimeSheets = new SetupFilter("SigoTimeSheets");
        filterTimeSheets.AddParameter("UserName", "PermissionPolicyUser");
        filterTimeSheets.AddParameter("filterCampBoss", DbType.String);
        filterTimeSheets.AddJoin(Join.Inner, "ErpDepartamentos")
            .On("SigoTimeSheets", "Departamento", "ErpDepartamentos", "Departamento");
        filterTimeSheets.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("ErpDepartamentos", "CDU_Centro", "SigoCentrosCampBosses", "Centro");
        filterTimeSheets.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterTimeSheets.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterTimeSheets);

        var filterTimeSheetsMovimentos = new SetupFilter("SigoTimeSheetsMovimentos");
        filterTimeSheetsMovimentos.AddParameter("UserName", "PermissionPolicyUser");
        filterTimeSheetsMovimentos.AddParameter("filterCampBoss", DbType.String);
        filterTimeSheetsMovimentos.AddJoin(Join.Inner, "SigoTimeSheets")
            .On("SigoTimeSheetsMovimentos", "TimeSheet", "SigoTimeSheets", "Oid");
        filterTimeSheetsMovimentos.AddJoin(Join.Inner, "ErpDepartamentos")
            .On("SigoTimeSheets", "Departamento", "ErpDepartamentos", "Departamento");
        filterTimeSheetsMovimentos.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("ErpDepartamentos", "CDU_Centro", "SigoCentrosCampBosses", "Centro");
        filterTimeSheetsMovimentos.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterTimeSheetsMovimentos.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterTimeSheetsMovimentos);

        var filterFuncionarioAtributos = new SetupFilter("SigoFuncionarioAtributos");
        filterFuncionarioAtributos.AddParameter("UserName", "PermissionPolicyUser");
        filterFuncionarioAtributos.AddParameter("filterCampBoss", DbType.String);
        filterFuncionarioAtributos.AddJoin(Join.Inner, "ErpFuncionarios")
            .On("SigoFuncionarioAtributos", "Funcionario", "ErpFuncionarios", "Codigo");
        filterFuncionarioAtributos.AddJoin(Join.Inner, "ErpDepartamentos")
            .On("ErpFuncionarios", "CodDepartamento", "ErpDepartamentos", "Departamento");
        filterFuncionarioAtributos.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("ErpDepartamentos", "CDU_Centro", "SigoCentrosCampBosses", "Centro");
        filterFuncionarioAtributos.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterFuncionarioAtributos.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterFuncionarioAtributos);

        var filterRegistoFaltasMovimentos = new SetupFilter("SigoRegistoFaltasMovimentos");
        filterRegistoFaltasMovimentos.AddParameter("UserName", "PermissionPolicyUser");
        filterRegistoFaltasMovimentos.AddParameter("filterCampBoss", DbType.String);
        filterRegistoFaltasMovimentos.AddJoin(Join.Inner, "SigoRegistoFaltas")
            .On("SigoRegistoFaltasMovimentos", "RegistoFalta", "SigoRegistoFaltas", "Oid");
        filterRegistoFaltasMovimentos.AddJoin(Join.Inner, "ErpFuncionarios")
            .On("SigoRegistoFaltas", "Funcionario", "ErpFuncionarios", "Codigo");
        filterRegistoFaltasMovimentos.AddJoin(Join.Inner, "ErpDepartamentos")
            .On("ErpFuncionarios", "CodDepartamento", "ErpDepartamentos", "Departamento");
        filterRegistoFaltasMovimentos.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("ErpDepartamentos", "CDU_Centro", "SigoCentrosCampBosses", "Centro");
        filterRegistoFaltasMovimentos.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterRegistoFaltasMovimentos.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterRegistoFaltasMovimentos);

        var filterRegistoOcorrencias = new SetupFilter("SigoRegistoOcorrencias");
        filterRegistoOcorrencias.AddParameter("UserName", "PermissionPolicyUser");
        filterRegistoOcorrencias.AddParameter("filterCampBoss", DbType.String);
        filterRegistoOcorrencias.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("SigoRegistoOcorrencias", "Centro", "SigoCentrosCampBosses", "Centro");
        filterRegistoOcorrencias.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        filterRegistoOcorrencias.AddWhere("UserName", "PermissionPolicyUser", "filterCampBoss");
        setup.Filters.Add(filterRegistoOcorrencias);

        var filterRegistoAcidentesTrabalho = new SetupFilter("SigoRegistoAcidentesTrabalho");
        filterRegistoAcidentesTrabalho.AddParameter("UserName", "PermissionPolicyUser");
        filterRegistoAcidentesTrabalho.AddParameter("filterCampBoss", DbType.String);
        filterRegistoAcidentesTrabalho.AddJoin(Join.Inner, "ErpFuncionarios")
            .On("SigoRegistoAcidentesTrabalho", "Funcionario", "ErpFuncionarios", "Codigo");
        filterRegistoAcidentesTrabalho.AddJoin(Join.Inner, "ErpDepartamentos")
            .On("ErpFuncionarios", "CodDepartamento", "ErpDepartamentos", "Departamento");
        filterRegistoAcidentesTrabalho.AddJoin(Join.Inner, "SigoCentrosCampBosses")
            .On("ErpDepartamentos", "CDU_Centro", "SigoCentrosCampBosses", "Centro");
        filterRegistoAcidentesTrabalho.AddJoin(Join.Inner, "PermissionPolicyUser")
            .On("SigoCentrosCampBosses", "User", "PermissionPolicyUser", "Oid");
        setup.Filters.Add(filterRegistoAcidentesTrabalho);

        return setup;
    }
}`

**Comment by Mimetis** [comment]
dont know
