### ISSUE TITLE
Q: Can I translate between different column types on server/client

### ISSUE THREAD

**Issue by dr-consit** [Mimetis/Dotmim.Sync#972]
Doing a download only sync.

I have a table with 3 columns
Col1-3

Col1 is Identity Integer on SQL Server and NVarchar(100) on the client. The other columns are identical between client and server.

Would it be possible to do this conversion/mapping from server to client?

**Comment by Mimetis** [comment]
I think it's possible, but it will be quite complicated.
You need to use Interceptors, I guess, and intercepts all call the database and see how you can convert

**Comment by dr-consit** [comment]
Ah... No shortcuts then? 
None of the schemaloading or applying events allow to modify the necessary objects/metadata/data?

**Comment by Mimetis** [comment]
No shortcuts

Once again, possible, but DMS is not designed like this. 
I think it's feasible if you are using interceptors.

I need to make a test, but currently I don't have the necessary free time to invest.

At least, if you are trying on your own, I can help maybe.

**Comment by dr-consit** [comment]
Would it be possible maybe to "cheat" where DMS is reading the schema information from the server/source database, to get it to ignore/not see the "identity" property on the column? 
Can you maybe point me in the right direction if this is maybe feasible?

I would of course be much obliged if do you find time to look at something, but I really don't expect you to!

**Comment by dr-consit** [comment]
Just to be clear, I realise I would probably have to patch DMS, and use this patched version to do the above.
