### ISSUE TITLE
DropAllAsync Error After upgrade from 0.9.7 to 0.9.8

### ISSUE THREAD

**Issue by mostafa4c** [Mimetis/Dotmim.Sync#981]
```
var agent = new SyncAgent(serverProvider, clientProvider);
await agent.LocalOrchestrator.DropAllAsync();
```
return error
[DropAllAsync]..[InternalGetSchemaAsync]..[InternalGetTableSchemaAsync].Table:HR_empvacationdata..[SetPrimaryKeysAsync].Table:HR_empvacationdata..Table HR_empvacationdata does not have any primary key.

this Table:HR_empvacationdata not in Sync process
in 0.9.7 no error return

**Comment by VagueGit** [comment]
I am experiencing the same error (I think) after upgrade from DMS 0.9.7 to 0.9.8.
Calling `await webServerAgent.RemoteOrchestrator.DropAllAsync();` now throws
`[DropAllAsync]..[InternalGetSchemaAsync]..[InternalGetTableSchemaAsync].Table:scope_info_server..[FillSyncTableWithColumns].Table:scope_info_server..In table scope_info_server, the Column name sync_scope_name is not allowed. Please consider to change the column name.`
