### ISSUE TITLE
Value cannot be null. (Parameter 'path1')

### ISSUE THREAD

**Issue by thanos232324353** [Mimetis/Dotmim.Sync#984]
Hello!
    I am using version 0.9.8，Dotmim.Sync.Web.Client，When I use the nuget package, I report an error，Value cannot be null. (Parameter 'path1')，When I use your Samples, make it run perfectly，Looks like there's a problem with the nuget package，

**Comment by Mimetis** [comment]
are you able to reproduce the issue with a simple example I can use to debug ?

**Comment by psyhlo** [comment]
i have the same error
![image](https://github.com/Mimetis/Dotmim.Sync/assets/1803170/1bb86d68-24a7-4bad-b8cd-9ee8e1699c4a)
i'm using sample projects FilterWebSyncClient and FilterWebSyncServer

**Comment by psyhlo** [comment]
i track it to this point
\Dotmim.Sync.Web.Client\Orchestrators\WebRemoteOrchestrator.ApplyChanges.cs
![image](https://github.com/Mimetis/Dotmim.Sync/assets/1803170/b14744ff-cadc-459d-8921-0b66896662e1)

![image](https://github.com/Mimetis/Dotmim.Sync/assets/1803170/5f3d3e2d-56f8-428f-af82-b6db55a3fe9f)

**Comment by Mimetis** [comment]
Are you using the same version on both side ?

**Comment by psyhlo** [comment]
one of the projects was with nuget and the other from git source.
change both to be with nuget and works.
thanks
