### ISSUE TITLE
WebRemoteOrchestrator Interceptors don't work

### ISSUE THREAD

**Issue by workgroupengineering** [Mimetis/Dotmim.Sync#990]
## Current behavior

When using WebRemoteOrchestrator the `agent.RemoteOrchestrator.On*Applying(args=>` isn't invoked.

[This](https://github.com/Mimetis/Dotmim.Sync/files/11113072/Issue_Test.patch)  is a test patch demonstrating the issue.

## Possible solutions

- Implement [Web host](https://melihercan.medium.com/running-net-core-web-host-and-kestrel-server-on-xamarin-forms-apps-2c5e3a3df5a5) in Dotmim.Sync.Web.Client add http header with callback uri when call remote methods.
- New WebSocketsRemoteOrchestrator (rif. [WebSockets](https://fullstackmark.com/post/3/websockets-with-aspnet-core-and-xamarin-forms))

**Comment by Mimetis** [comment]
Is `agent.RemoteOrchestrator` a `WebRemoteOrchestrator` ? (meaning you are in a HTTP scenario with a web api protecting your db)
If, yes, it's totally normal that you don't have access to the interceptors occuring on the web api side

if your `agent.RemoteOrchestrator` is a simple `RemoteOrchestrator` (meaning you are on a classic TCP sync) then it's an issue.

**Comment by workgroupengineering** [comment]
I miswrite the post. It wasn't a bug report but an improvement request.

The scenario is the mobile(Xamarin Forms).



> Is `agent.RemoteOrchestrator` a `WebRemoteOrchestrator` ? (meaning you are in a HTTP scenario with a web api protecting your db)
> If, yes, it's totally normal that you don't have access to the interceptors occuring on the web api side

`agent.RemoteOrchestrator.On*Applying(args=>` should throw an exception when RemoteOrchestrator is WebRemoteOrchestrator
